### ISSUE TITLE
Mojave remove support for i386

### ISSUE THREAD

**Issue by t3hp0rP** [unicorn-engine/unicorn#1029]
And i delete `i386` in MakeFile and works fine, is it ok to do it?

**Comment by cokia** [comment]
I think u must reopen,,
if u not want open, i will reopen my issue.. #1031

**Comment by Pr0phet** [comment]
👌

**Comment by Pr0phet** [comment]
Why they can't just fix this issue 🤕  It looks quite easy...... And maybe quick？

**Comment by cokia** [comment]
@Pr0phet U must be See my PR(pull Request,,,) 
I think they didn't want to change code,,,
#1032
