### ISSUE TITLE
Current data types are messy

### ISSUE THREAD

**Issue by aquynh** [unicorn-engine/unicorn#105]
currently we have the following data types in `unicorn.h`.

    ucengine
    uchook
    uc_arch
    uc_mode
    uc_err
    uc_mem_type
    uc_hook_t

the data types are not consistently named, as some are with `_` and `_t`, some are not. also `uchook` & `uc_hook_t` look similar, and can be mistaken with each other.

any idea on how to renaming these? here is my proposal:

    ucengine  --> uc_engine
    uchook     --> uc_hook
    uc_arch    --> <no change>
    uc_mode  --> <no change>
    uc_err       --> <no change>
    uc_mem_type  --> <no change>
    uc_hook_t        --> uc_hook_type

but still, `uc_mem_type` & `uc_hook_type` can have better names?

**Comment by JonathonReinhart** [comment]
I believe this can be closed.

**Comment by aquynh** [comment]
close, thanks
