### ISSUE TITLE
X86: Is there any hook or solution to intercept #BP (int 3) or #DB(eflags.TF=1 or sth.)?

### ISSUE THREAD

**Issue by hzqst** [unicorn-engine/unicorn#1055]
It is not possible to emulate SEH/VEH code path for uncorn. It just return UC_ERR_EXCEPTION with no more detail about why the execution is interrupted.

**Comment by cseagle** [comment]
Probably related to #1098 and #694

**Comment by hzqst** [comment]
it is okay to intercept #DB in UC_HOOK_INTR but still not able to determine if the exception is a hardware breakpoint (debug register) hit or single step. I would be grateful if unicorn add more detail for the exception handling.
