### ISSUE TITLE
Crashes when executing `rdrand`

### ISSUE THREAD

**Issue by sqall01** [unicorn-engine/unicorn#1060]
Hi,

I am using unicorn 1.0.1 installed via pip (since I am using it in a python project). The emulation crashes when executing the "rdrand" instruction from the amd64 instruction set. The instruction is just the following:

`49 0F C7 F2    rdrand  r10`

It crashes with the error:

`Invalid instruction (UC_ERR_INSN_INVALID)`

Can it be that this instruction is not yet implemented in unicorn?

Cheers and thanks for the help,
sqall

**Comment by sqall01** [comment]
Just to give a test case which can reproduce the bug:

```python
#!/usr/bin/python

from __future__ import print_function
from unicorn import *
from unicorn.x86_const import *

# code to be emulated
X86_CODE32 = b"\x49\x0F\xC7\xF2" # rdrand r10

# memory address where emulation starts
ADDRESS = 0x1000000

print("Emulate i386 code")
try:
    # Initialize emulator in X86-32bit mode
    mu = Uc(UC_ARCH_X86, UC_MODE_64)

    # map 2MB memory for this emulation
    mu.mem_map(ADDRESS, 2 * 1024 * 1024)

    # write machine code to be emulated to memory
    mu.mem_write(ADDRESS, X86_CODE32)

    # emulate code in infinite time & unlimited instructions
    mu.emu_start(ADDRESS, ADDRESS + len(X86_CODE32))

    # now print out some registers
    print("Emulation done. Below is the CPU context")

    r_r10 = mu.reg_read(UC_X86_REG_R10)
    print(">>> R10 = 0x%x" %r_r10)

except UcError as e:
    print("ERROR: %s" % e)
```

**Comment by dmarxn** [comment]
rdrand is not emulated by qemu (even upstream).

This can be implemented, by either emulating with a prng or using the host's rng.

Just as a reference on what the problem actually is :

In qemu/target-i386/translate.c
The case for "0f c7" is implemented just for cmpxchg8b and not rdrand

What should be done is a check for the REX prefix (which was parsed before) to distinguish between rdrand and cmpxchg8b, then act accordingly.

**Comment by sqall01** [comment]
This is too bad. Just for completeness if other people have the same problem, the workaround I came up yesterday looks something like this:

```python
def hook_code(mu: Uc, address, size, emu_env: EmulatorEnv):

    # Do some stuff [...]

    # Magic number of unicorn which means something does not work.
    if size == 0xf1f1f1f1:
        cs_gen = emu_env.capstone.disasm(mu.mem_read(address, 16), address)
        try:
            cs_instr = cs_gen.__next__()
        except:
            cs_instr = None
        # Since unicorn crashes when using rdrand and instruction hook on rdrand does not work either,
        # check it manually :(
        if cs_instr and cs_instr.mnemonic == "rdrand":
            # https://www.felixcloutier.com/x86/rdrand
            unicorn_reg = RegistersX64.from_str_to_unicorn(cs_instr.op_str)
            data = os.urandom(8)
            value = struct.unpack("Q", data)
            mu.reg_write(unicorn_reg, value[0])
            eflags_clear_of(mu)
            eflags_clear_sf(mu)
            eflags_clear_zf(mu)
            eflags_clear_af(mu)
            eflags_clear_pf(mu)
            eflags_set_cf(mu)
            mu.reg_write(UC_X86_REG_RIP, address + cs_instr.size)
            return

    # Do some other stuff [...]
```

Thanks for the explanation and for the great work with unicorn. Really appreciate it.

**Comment by aquynh** [comment]
Interesting, but the best approach is to emulate this instruction in the core. Should not be too hard.

**Comment by dmarxn** [comment]
This (and rdseed) can be added in a simple way.
Question is, how should we generate the random number?
On x86 systems we can probably call the instruction on the host like done with rdtsc.

On other systems I'm not sure which random function will suffice.
Thoughts, @sqall01 ?

**Comment by sqall01** [comment]
Actually, I had thought about it and have no idea how to solve it the best way.

On x86 systems you can just call the instruction, yes. However, what about older x86 processors that do not have this instruction? Using the operating system PRNG (/dev/urandom for Linux, some API call for Windows) for the other cases? However, using the operating system PRNG results in a rather huge performance overhead when comparing to the `rdrand` instruction.

On what architectures does unicorn also run?
