### ISSUE TITLE
Access to ARM IPSR

### ISSUE THREAD

**Issue by cfrantz** [unicorn-engine/unicorn#1065]
Hello,

I'm working on an emulator which includes an NVIC interrupt controller as part of the system to be emulated.  I have a sufficient implementation of NVIC for my project, but it seems unicorn lacks a public API for manipulating the IPSR register.

I'm not super familiar with the internal workings of unicorn, and I'd like my emulator to not have to depend on private APIs or structures.

I've attached a patch with a solution which works for me.
[unicorn.patch.txt](https://github.com/unicorn-engine/unicorn/files/2890667/unicorn.patch.txt)

**Comment by aquynh** [comment]
You can see how to add a new register update in a similar PR #1059.

Please send a pull req for your change.
