### ISSUE TITLE
Release ?

### ISSUE THREAD

**Issue by Summus6** [unicorn-engine/unicorn#1066]
Hello :)

The last release (1.0.1) was commited near 2 years ago.
When can we expect a tag for a (quite) stable version ?
Maybe the current master is stable enough ?

Thank you a lot for the work you're doing !

**Comment by anatol** [comment]
+1

And please sync the latest qemu version from upstream before the unicorn release.

**Comment by rhelmot** [comment]
I can do a 1.0.1.post1 release to pip based on the current master. This would at the very least make unicorn pip-installable for macos mojave users. @aquynh?

**Comment by tiffanyb** [comment]
I really hope you could release a new version on PyPI since the current version doesn't work on Mac Mojave due to i386 deprecation. It's been fixed in github, and all you need is to update it to PyPI.

**Comment by aquynh** [comment]
Anyone having Visual Studio can confirm that MSVC still compiles?

**Comment by yhql** [comment]
@aquynh I had to update the toolchain in the project files to v141 (MSVC 2017) because the v110_xp is not available anymore. It did compile correctly, but I didn't test it a lot.

Should I make a PR ?

**Comment by Summus6** [comment]
Hello, how it is ?

**Comment by disconnect3d** [comment]
Bump.

**Comment by Summus6** [comment]
Hello

**Comment by domenukk** [comment]
Any news on this? At least master is definitely more mature than ye olde version for my use case. Even a prerelease on pip might help.

**Comment by domenukk** [comment]
This looks good https://pypi.org/project/unicorn/1.0.2rc1/
