### ISSUE TITLE
[x86_64] incorrect emulation of vmovups instruction

### ISSUE THREAD

**Issue by stevielavern** [unicorn-engine/unicorn#1072]
Hi, 

The **vmovups** instruction is not properly emulated.

For instance in the attached test case, running **vmovups	xmm1, xmmword ptr [rsp]**:
- the size of the memory access passed to a **UC_HOOK_MEM_READ** callback is 1 instead of 16 (xmmword)
- the value of **xmm1** after the instruction is emulated is 0 instead of the value pointed to by rsp

Here's the output:
```
$  ipython uc_bug_vmovups.py
[INS] address=0x10000000 size=0x5	vmovups	xmm1, xmmword ptr [rsp]
00000000: C5 F8 10 0C 24                                    ....$
[MEM] access=16 address=0x20000000 size=0x1 value=0x0
00000000: 41 42 43 44 45 46 47 48  49 4A 4B 4C 4D 4E 4F 50  ABCDEFGHIJKLMNOP
[END] XMM1=0x0
```

And the test case:
```python
from capstone import *
from unicorn import *
from unicorn.x86_const import *
import hexdump

CODE_ADDR = 0x10000000
CODE_VAL = b"\xC5\xF8\x10\x0C\x24" # vmovups	xmm1, xmmword ptr [rsp]
STACK_ADDR = 0x20000000
STACK_VAL = b"ABCDEFGHIJKLMNOP"
PAGE_SIZE = 4096

class Tester(object):

    def mem_hook(self, mu, access, address, size, value, user_data):
        print("[MEM] access={} address={:#x} size={:#x} value={:#x}".format(access, address, size, value))
        hexdump.hexdump(self.uc.mem_read(address, 16))

    def code_hook(self, mu, address, size, user_data):
        (code, ins) = self.disasm(address, size)
        print("[INS] address={:#x} size={:#x}\t{}\t{}".format(address, size, ins.mnemonic, ins.op_str))
        hexdump.hexdump(code)

    def setup_uc(self):
        self.uc = Uc(UC_ARCH_X86, UC_MODE_64)
        self.uc.mem_map(CODE_ADDR, PAGE_SIZE)
        self.uc.mem_map(STACK_ADDR, PAGE_SIZE)
        self.uc.mem_write(CODE_ADDR, CODE_VAL)
        self.uc.mem_write(STACK_ADDR, STACK_VAL)
        self.uc.reg_write(UC_X86_REG_RSP, STACK_ADDR)
        self.uc.hook_add(UC_HOOK_MEM_READ, self.mem_hook)
        self.uc.hook_add(UC_HOOK_CODE, self.code_hook)

    def setup_cs(self):
        self.cs = Cs(CS_ARCH_X86, CS_MODE_64)
        self.cs.detail = True

    def disasm(self, address, size):
        code = self.uc.mem_read(address, size)
        ins = next(self.cs.disasm(code, address))
        return (code, ins)

    def test_vmovups(self):
        self.uc.emu_start(CODE_ADDR, CODE_ADDR + len(CODE_VAL))
        print("[END] XMM1={:#x}".format(self.uc.reg_read(UC_X86_REG_XMM1)))

    def main(self):
        self.setup_uc()
        self.setup_cs()
        self.test_vmovups()

if __name__ == '__main__':
    Tester().main()
```

**Comment by aquynh** [comment]
can Qemu 3.1 properly handle this instruction?

**Comment by stevielavern** [comment]
I wrote a quick test case to directly test qemu:
```c
#include <stdio.h>
#include <stdint.h>

int main(void) {
    uint8_t a[0x10] = "OK\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00";
    uint8_t b[0x10] = "NOTOK\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00";

    printf("Before vmovups: a=%s b=%s\n", a, b);

    __asm__ __volatile__("vmovups %0, %%xmm1":"=m"(*a)::"memory");
    __asm__ __volatile__("vmovups %%xmm1, %0":"=m"(*b)::"memory");

    printf("After vmovups: a=%s b=%s\n", a, b);

    return 0;
}
``` 

Normal output is:
```
$ clang -o vmovups vmovups.c
$  ./vmovups
Before vmovups: a=OK b=NOTOK
After vmovups: a=OK b=OK
```

Looks like qemu 2.11 doesn't handle the instruction properly:
```
$ qemu-x86_64 -version
qemu-x86_64 version 2.11.1

$ qemu-x86_64 -cpu qemu64,-vmx ./vmovups
Before vmovups: a=OK b=NOTOK
After vmovups: a=OK b=NOTOK
```

But qemu 3.1 does:
```
$ qemu-x86_64 -version
qemu-x86_64 version 3.1.0

$ qemu-x86_64 -cpu qemu64,-vmx ./vmovups
Before vmovups: a=OK b=NOTOK
After vmovups: a=OK b=OK
```

**Comment by stevielavern** [comment]
Commit 5bf6d77 had some related fixes so I ran the same testcase again using an updated Unicorn (`master` branch):

```
[INS] address=0x10000000 size=0x5	vmovups	xmm1, xmmword ptr [rsp]
00000000: C5 F8 10 0C 24                                    ....$
[MEM] access=16 address=0x20000000 size=0x8 value=0x0
00000000: 41 42 43 44 45 46 47 48  49 4A 4B 4C 4D 4E 4F 50  ABCDEFGHIJKLMNOP
[MEM] access=16 address=0x20000008 size=0x8 value=0x0
00000000: 49 4A 4B 4C 4D 4E 4F 50  00 00 00 00 00 00 00 00  IJKLMNOP........
[END] XMM1=0x504f4e4d4c4b4a494847464544434241
```

Emulation seems to be fixed since the XMM1 final value is correct. However there are 2 calls to the UC_HOOK_MEM_READ callback, each one with a 8-byte access, instead of a single call with 16-byte access. Is that expected?

**Comment by Waterman178** [comment]
#

> According to #1074, commit [5bf6d77](https://github.com/unicorn-engine/unicorn/commit/5bf6d77e4ee258c67c2d7ead94cf266a7b9773e7) had some related fixes so I ran the same testcase again using an updated Unicorn (`master` branch):
> 
> ```
> [INS] address=0x10000000 size=0x5	vmovups	xmm1, xmmword ptr [rsp]
> 00000000: C5 F8 10 0C 24                                    ....$
> [MEM] access=16 address=0x20000000 size=0x8 value=0x0
> 00000000: 41 42 43 44 45 46 47 48  49 4A 4B 4C 4D 4E 4F 50  ABCDEFGHIJKLMNOP
> [MEM] access=16 address=0x20000008 size=0x8 value=0x0
> 00000000: 49 4A 4B 4C 4D 4E 4F 50  00 00 00 00 00 00 00 00  IJKLMNOP........
> [END] XMM1=0x504f4e4d4c4b4a494847464544434241
> ```
> 
> Emulation seems to be fixed since the XMM1 final value is correct. However there are 2 calls to the UC_HOOK_MEM_READ callback, each one with a 8-byte access, instead of a single call with 16-byte access. Is that expected?

You can get the instruction length but can't get the correct memory access range.However, #1073  cannot get the instruction length.How to fix these problems?
