### ISSUE TITLE
[x86_64] Incorrect size passed to UC_HOOK_MEM_READ for vxorps instruction

### ISSUE THREAD

**Issue by stevielavern** [unicorn-engine/unicorn#1073]
Hi,

The size of the **vxorps** instruction passed to the **UC_HOOK_MEM_READ** callback is incorrect.
For instance, in the test case below, it is 3 instead of 4 for the instruction: `vxorps  xmm0, xmm0, xmm0` (which translates into `C5 F8 57 C0`).

Here's the output of the test case, where we can see that the passed size is 3 and capstone therefore fails to disassemble it:
```
[INS] address=0x10000000 size=0x3
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "/usr/local/lib/python3.7/site-packages/unicorn/unicorn.py", line 438, in _hookcode_cb
    cb(self, address, size, data)
  File "/tmp/uc_bug_vxorps.py", line 17, in code_hook
    (code, ins) = self.disasm(address, size)
  File "/tmp/uc_bug_vxorps.py", line 34, in disasm
    ins = next(self.cs.disasm(code, address))
StopIteration
```

And the test case:

```python
from capstone import *
from unicorn import *
from unicorn.x86_const import *
import hexdump

CODE_ADDR = 0x10000000
CODE_VAL = b"\xC5\xF8\x57\xC0" # vxorps  xmm0, xmm0, xmm0
PAGE_SIZE = 4096

class Tester(object):

    def code_hook(self, mu, address, size, user_data):
        print("[INS] address={:#x} size={:#x}".format(address, size))
        (code, ins) = self.disasm(address, size)
        hexdump.hexdump(code)
        print("[INS] {}\t{}".format(ins.mnemonic, ins.op_str))

    def setup_uc(self):
        self.uc = Uc(UC_ARCH_X86, UC_MODE_64)
        self.uc.mem_map(CODE_ADDR, PAGE_SIZE)
        self.uc.mem_write(CODE_ADDR, CODE_VAL)
        self.uc.hook_add(UC_HOOK_CODE, self.code_hook)

    def setup_cs(self):
        self.cs = Cs(CS_ARCH_X86, CS_MODE_64)
        self.cs.detail = True

    def disasm(self, address, size):
        code = self.uc.mem_read(address, size)
        ins = next(self.cs.disasm(code, address))
        return (code, ins)

    def test_vxorps(self):
        self.uc.emu_start(CODE_ADDR, CODE_ADDR + len(CODE_VAL))

    def main(self):
        self.setup_uc()
        self.setup_cs()
        self.test_vxorps()

if __name__ == '__main__':
    Tester().main()
```

**Comment by stevielavern** [comment]
Here's the corresponding JIT'ed call to `helper_uc_tracecode`, where we can see the size (`edi`) set to 3:
```
    0x105b1100c: mov    edi, 0x3
    0x105b11011: mov    esi, 0x2
    0x105b11016: lea    rdx, [rip - 0x52d861d]
    0x105b1101d: mov    ecx, 0x10000000
    0x105b11022: call   0x1055d6c90               ; helper_uc_tracecode
```

**Comment by stevielavern** [comment]
I wrote a quick test case to directly test qemu:
```c
#include <stdio.h>
#include <stdint.h>

int main(void) {
    uint8_t a[0x10] = "AAAAAAAAAAAAAAA";
    uint8_t b[0x10] = "BBBBBBBBBBBBBBB";

    __asm__ __volatile__("movaps %0, %%xmm0":"=m"(*a)::"memory"); // set XMM0 from memory
    __asm__ __volatile__("movaps %%xmm0, %0":"=m"(*b)::"memory"); // copy XMM0 to memory (ensure that XMM0 is set before excuting `vxorps`)

    printf("Before vxorps: a=%s b=%s\n", a, b);

    __asm__ __volatile__("movaps %0, %%xmm0":"=m"(*a)::"memory"); // set XMM0 from memory
    __asm__ __volatile__("vxorps %%xmm0, %%xmm0, %%xmm0":::); // clear XMM0
    __asm__ __volatile__("movaps %%xmm0, %0":"=m"(*b)::"memory"); // copy XMM0 to memory (ensure that XMM0 is set before excuting `vxorps`)

    printf("After vxorps: a=%s b=%s\n", a, b);

    return 0;
}
``` 

Normal output is:
```
$ clang -o vxorps vxorps.c 
$ ./vxorps 
Before vxorps: a=AAAAAAAAAAAAAAA b=AAAAAAAAAAAAAAA
After vxorps: a=AAAAAAAAAAAAAAA b=
```

Looks like qemu 2.11 doesn't handle the instruction properly, and even segfaults:
```
$ qemu-x86_64 -version
qemu-x86_64 version 2.11.1

$ qemu-x86_64 -cpu qemu64,-vmx ./vxorps
Before vxorps: a=AAAAAAAAAAAAAAA b=AAAAAAAAAAAAAAA
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

But qemu 3.1 does:
```
$ qemu-x86_64 -version
qemu-x86_64 version 3.1.0

$ qemu-x86_64 -cpu qemu64,-vmx ./vxorps
Before vxorps: a=AAAAAAAAAAAAAAA b=AAAAAAAAAAAAAAA
After vxorps: a=AAAAAAAAAAAAAAA b=
```

**Comment by aquynh** [comment]
Cool, please back port the fix, and do pull req.

**Comment by Waterman178** [comment]
> I wrote a quick test case to directly test qemu:
> 
> ```c
> #include <stdio.h>
> #include <stdint.h>
> 
> int main(void) {
>     uint8_t a[0x10] = "AAAAAAAAAAAAAAA";
>     uint8_t b[0x10] = "BBBBBBBBBBBBBBB";
> 
>     __asm__ __volatile__("movaps %0, %%xmm0":"=m"(*a)::"memory"); // set XMM0 from memory
>     __asm__ __volatile__("movaps %%xmm0, %0":"=m"(*b)::"memory"); // copy XMM0 to memory (ensure that XMM0 is set before excuting `vxorps`)
> 
>     printf("Before vxorps: a=%s b=%s\n", a, b);
> 
>     __asm__ __volatile__("movaps %0, %%xmm0":"=m"(*a)::"memory"); // set XMM0 from memory
>     __asm__ __volatile__("vxorps %%xmm0, %%xmm0, %%xmm0":::); // clear XMM0
>     __asm__ __volatile__("movaps %%xmm0, %0":"=m"(*b)::"memory"); // copy XMM0 to memory (ensure that XMM0 is set before excuting `vxorps`)
> 
>     printf("After vxorps: a=%s b=%s\n", a, b);
> 
>     return 0;
> }
> ```
> 
> Normal output is:
> 
> ```
> $ clang -o vxorps vxorps.c 
> $ ./vxorps 
> Before vxorps: a=AAAAAAAAAAAAAAA b=AAAAAAAAAAAAAAA
> After vxorps: a=AAAAAAAAAAAAAAA b=
> ```
> 
> Looks like qemu 2.11 doesn't handle the instruction properly, and even segfaults:
> 
> ```
> $ qemu-x86_64 -version
> qemu-x86_64 version 2.11.1
> 
> $ qemu-x86_64 -cpu qemu64,-vmx ./vxorps
> Before vxorps: a=AAAAAAAAAAAAAAA b=AAAAAAAAAAAAAAA
> qemu: uncaught target signal 11 (Segmentation fault) - core dumped
> ```
> 
> But qemu 3.1 does:
> 
> ```
> $ qemu-x86_64 -version
> qemu-x86_64 version 3.1.0
> 
> $ qemu-x86_64 -cpu qemu64,-vmx ./vxorps
> Before vxorps: a=AAAAAAAAAAAAAAA b=AAAAAAAAAAAAAAA
> After vxorps: a=AAAAAAAAAAAAAAA b=
> ```

Has this problem been solved yet?

**Comment by aquynh** [comment]
If we cant backport, at least we should fix the crash.
