### ISSUE TITLE
arm vfp support seems not well

### ISSUE THREAD

**Issue by fr0zenrain** [unicorn-engine/unicorn#1080]
this code from a real world android shared library function head

.text:000E0EF8 2D E9 F0 43                             PUSH.W          {R4-R9,LR}
.text:000E0EFC C0 EF 10 00                             VMOV.I32        D16, #0
.text:000E0F00 2D ED 02 8B                             VPUSH           {D8}
.text:000E0F04 04 46                                   MOV             R4, R0

dlsym return an odd address, so i start with thumb mode.

THUMB_CODE=\x2D\xE9\xF0\x43\xCD\xEF\x10\x00\x2D\xED\x02\x8B\x04\x46\x8c\x48\x98\x46
i have enable  cpu VFP mode, and i also mapped the memory for stack use ,but it doesn't work.
any one have met same issue?

**Comment by ninjahacker** [comment]
I ran into the same problem a few days ago. How did you enable cpu VFP mode?

**Comment by fr0zenrain** [comment]
> I ran into the same problem a few days ago. How did you enable cpu VFP mode?


`uint64_t tmp_val;
    err = uc_reg_read(uc, UC_ARM_REG_C1_C0_2, &tmp_val);
    if (err) {
        printf("reg write error\n");
        return ;
    }
    tmp_val = tmp_val | (0xf << 20);
    err = uc_reg_write(uc, UC_ARM_REG_C1_C0_2, &tmp_val);
    if (err) {
        printf("reg write error\n");
        return ;
    }
    size_t enable_vfp = 0x40000000;
    err = uc_reg_write(uc, UC_ARM_REG_FPEXC, &enable_vfp);
    if (err) {
    	printf("reg write error\n");
        return ;
    }`
i have single step the code,it don't run into the disas_vfp_insn. 
the vfp encoding not identify?

**Comment by ninjahacker** [comment]
Thanks! Okay, I see. I thought there might be a unicorn function to tell the emulator to enable it. This could be a problem where the emulator does not understand vfp bits. I'll try it in standard QEMU tomorrow to see if there is a difference between qemu and unicorn.
1. If works in QEMU, it should be an easy fix.
2. If doesn't work in QEMU, support may need to be added for the instructions in general.

**Comment by fr0zenrain** [comment]
i' am not familiar with qemu and vfp instruction set. when i debug again, i found vfp_disas_insn is invoked.exactly,  it's seems "vpush {d8}" instruction is not parse ok in unicorn, maybe i should to trace how qemu parse this instruction, if i have much time.

**Comment by ninjahacker** [comment]
I confirm qemu can emulate these instructions.

(gdb) disassemble $pc,$pc+0x10
Dump of assembler code from 0xf6ffdf68 to 0xf6ffdf78:
=> 0xf6ffdf68:	stmdb	sp!, {r4, r5, r6, r7, r8, r9, lr}
   0xf6ffdf6c:	vshr.s8	d16, d0, #3
   0xf6ffdf70:	vpush	{d8}
   0xf6ffdf74:	mov	r8, r3
   0xf6ffdf76:	movs	r0, r0
(gdb) info all-registers 
r0             0x1                 1
r1             0xf6fff0c4          -150998844
r2             0xf6fff0cc          -150998836
r3             0x1                 1
r4             0xf6ffef88          -150999160
r5             0x123462f0          305423088
r6             0x0                 0
r7             0x0                 0
r8             0x1                 1
r9             0x0                 0
r10            0x123cbf70          305971056
r11            0xf6ffef74          -150999180
r12            0x0                 0
sp             0xf6ffef28          0xf6ffef28
lr             0x12345e3c          305421884
pc             0xf6ffdf68          0xf6ffdf68
cpsr           0x20000030          536870960
d0             {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d1             {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d2             {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d3             {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d4             {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d5             {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
--Type <RET> for more, q to quit, c to continue without paging--
d6             {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d7             {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d8             {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d9             {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d10            {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d11            {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d12            {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d13            {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d14            {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d15            {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d16            {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d17            {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d18            {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d19            {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d20            {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d21            {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d22            {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d23            {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d24            {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d25            {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d26            {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d27            {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d28            {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
--Type <RET> for more, q to quit, c to continue without paging--
d29            {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d30            {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}
d31            {u8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, u16 = {0x0, 0x0, 0x0, 0x0}, u32 = {0x0, 0x0}, u64 = 0x0, f32 = {0x0, 0x0}, f64 = 0x0}

(gdb) b *0xf6ffdf74
Breakpoint 2 at 0xf6ffdf74
(gdb) c
Continuing.

Breakpoint 2, 0xf6ffdf74 in ?? ()

**Comment by ninjahacker** [comment]
I did a diff on:
unicorn/qemu/target-arm/translate.c qemu-3.1.0/target/arm/translate.c
The fix is not so straightforward as I had hoped.
Consider vshr.s8	d16, d0, #3
In unicorn/translate.c: 5753
In qemu/translate.c: 6752

The way the two operate are pretty different, so I'm not sure with all the helper functions qemu uses we'd be able to just copy-paste a fix so easily. Is there a standard way that unicorn pulls in qemu updates? Glancing through the code, I can't even begin to imagine the difference between them. I will do a debug session next to see if I can pinpoint a more exact spot.

**Comment by ninjahacker** [comment]
In my attempt to find the problem, I have found no problem. Unfortunately, we both ran into issues with "real" libraries. So I'm not sure what is going on that is different in them. See my attached sample code that successfully loads and runs the code in THUMB mode. Make sure the stack points somewhere in the middle of mapped memory. Also, if you get an error running this code, please post what it is. Thank you.

**Comment by ninjahacker** [comment]
```
/* Unicorn Emulator Engine */
/* By Nguyen Anh Quynh, 2015 */

/* Sample code to demonstrate how to emulate ARM code */

#include <unicorn/unicorn.h>
#include <string.h>


// code to be emulated
#define THUMB_CODE "\x2D\xE9\xF0\x43\xC0\xEF\x10\x00\x2D\xED\x02\x8B\x04\x46\x8c\x48\x98\x46" // sub    sp, #0xc

// memory address where emulation starts
#define ADDRESS 0x10000
#define STACK 0x400000

static void hook_block(uc_engine *uc, uint64_t address, uint32_t size, void *user_data)
{
    printf(">>> Tracing basic block at 0x%"PRIx64 ", block size = 0x%x\n", address, size);
}

static void hook_code(uc_engine *uc, uint64_t address, uint32_t size, void *user_data)
{
    printf(">>> Tracing instruction at 0x%"PRIx64 ", instruction size = 0x%x\n", address, size);
}

static void test_thumb(void)
{
    uc_engine *uc;
    uc_err err;
    uc_hook trace1, trace2;

    int sp = STACK;

    printf("Emulate THUMB code\n");

    // Initialize emulator in ARM mode
    err = uc_open(UC_ARCH_ARM, UC_MODE_THUMB, &uc);
    if (err) {
        printf("Failed on uc_open() with error returned: %u (%s)\n",
                err, uc_strerror(err));
        return;
    }

    // map 2MB memory for this emulation
    uc_mem_map(uc, ADDRESS, 2 * 1024 * 1024, UC_PROT_ALL);

    // map 2MB memory for this emulation
    uc_mem_map(uc, STACK, 2 * 1024 * 1024, UC_PROT_ALL);

    uint64_t tmp_val;
    err = uc_reg_read(uc, UC_ARM_REG_C1_C0_2, &tmp_val);
    if (err) {
      printf("reg write error\n");
      return;
    }
    tmp_val = tmp_val | (0xf << 20);
    err = uc_reg_write(uc, UC_ARM_REG_C1_C0_2, &tmp_val);
    if (err) {
      printf("reg write error\n");
      return;
    }
    
    tmp_val=0xffff1111;
    err = uc_reg_write(uc, UC_ARM_REG_D16, &tmp_val);
    if (err) {
      printf("reg write error\n");
      return;
    }

    size_t enable_vfp = 0x40000000;
    err = uc_reg_write(uc, UC_ARM_REG_FPEXC, &enable_vfp);
    if (err) {
      printf("reg write error\n");
      return ;
    }
    
    // write machine code to be emulated to memory
    uc_mem_write(uc, ADDRESS, THUMB_CODE, sizeof(THUMB_CODE) - 1);

    sp = STACK+0x1000;
    
    // initialize machine registers
    uc_reg_write(uc, UC_ARM_REG_SP, &sp);

    // tracing all basic blocks with customized callback
    uc_hook_add(uc, &trace1, UC_HOOK_BLOCK, hook_block, NULL, 1, 0);

    // tracing one instruction at ADDRESS with customized callback
    uc_hook_add(uc, &trace2, UC_HOOK_CODE, hook_code, NULL, ADDRESS, 0);

    uc_reg_read(uc, UC_ARM_REG_D16, &tmp_val);
    printf("D16 = 0x%"PRIx64 "\n", tmp_val);
    
    // emulate machine code in infinite time (last param = 0), or when
    // finishing all the code.
    // Note we start at ADDRESS | 1 to indicate THUMB mode.
    err = uc_emu_start(uc, ADDRESS | 1, ADDRESS + sizeof(THUMB_CODE) -1, 0, 0);

    printf("Finish!\n");

    if (err) {
        printf("Failed on uc_emu_start() with error returned: %u\n", err);
	printf("ERROR: %s\n", uc_strerror(err));
    }


    // now print out some registers
    printf(">>> Emulation done. Below is the CPU context\n");

    uc_reg_read(uc, UC_ARM_REG_SP, &sp);
    printf(">>> SP = 0x%x\n", sp);
    uc_reg_read(uc, UC_ARM_REG_PC, &sp);
    printf(">>> PC = 0x%x\n", sp);
    uc_reg_read(uc, UC_ARM_REG_D16, &tmp_val);
    printf("D16 = 0x%"PRIx64 "\n", tmp_val);

    uc_close(uc);
}

int main(int argc, char **argv, char **envp)
{
    // dynamically load shared library
#ifdef DYNLOAD
    if (!uc_dyn_load(NULL, 0)) {
        printf("Error dynamically loading shared library.\n");
        printf("Please check that unicorn.dll/unicorn.so is available as well as\n");
        printf("any other dependent dll/so files.\n");
        printf("The easiest way is to place them in the same directory as this app.\n");
        return 1;
    }
#endif
    
    test_thumb();

    // dynamically free shared library
#ifdef DYNLOAD
    uc_dyn_free();
#endif
    
    return 0;
}

```

**Comment by fr0zenrain** [comment]
@ninjahacker thanks your work, it seems ok now . it's strange we have the same issue last week, i don't know the reason.The previous error is invalid instruction .

**Comment by ninjahacker** [comment]
Yes, precisely. Invalid instruction is what I found as well.

**Comment by deadeert** [comment]
Hi guys,

Not sure that helps, but I managed to run VFP code using following init :
`
from unicorn import *
from unicorn.arm_const import * 

# from : http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0449b/ch02s01s02.html
# Enable CP10 and CP11 (NSACR) 
ENABLE_VFP= b"\x50\x0f\x11\xee" # mrc p15 0 r0 c1 c0 2
ENABLE_VFP+=b"\x0f\x06\x80\xe3"# ORR r0, r0, #2_11<<10  
ENABLE_VFP+=b"\x50\x0f\x01\xee"# mcr p15 0 r0 c1 c0 2
# Enable VFP in FPEXC (Coprocessor Access Control Register)
ENABLE_VFP+=b"\x40\x04\xa0\xe3"# mov r0 0x40000000
ENABLE_VFP+=b"\x10\x0a\xe8\xee"# vmsr fpexcr0
# Smoketest 
ENABLE_VFP+=b'\x0D\x07\x21\xF4' #vld1.8 {d0}, [r1]! 
ENABLE_VFP+=b'\x0D\x07\x0C\xF4' #vsd1.8 {d0}, [r12]! 



stack_addr = 0x80000000
start_mapping = 0x50000000
end_mapping = 0x50000028
start_addr = start_mapping
end_addr = end_mapping
p_size = 0x400 

  


def prepare():

  uc = Uc(UC_ARCH_ARM,UC_MODE_ARM)
  uc.mem_map(start_mapping,p_size*2)
  uc.mem_write(start_mapping,ENABLE_VFP)


  
  uc.mem_map(0x1000,p_size) 
  uc.mem_write(0x1000,b'testtest'*(p_size//8))
  uc.mem_map(0x2000,p_size)
 
  uc.reg_write(UC_ARM_REG_R12,0x2000)
  uc.reg_write(UC_ARM_REG_R1,0x1000)
  uc.reg_write(UC_ARM_REG_R2,8)
  
  
  from capstone import Cs, CS_MODE_ARM, CS_ARCH_ARM 
  cs=Cs(CS_ARCH_ARM, CS_MODE_ARM)
  cs.detail=True

  uc.emu_start(start_addr,end_addr,count=0,timeout=0)

  # Must printf 'testtest' 
  print('%s'%uc.mem_read(0x2000,8).decode('utf-8'))

if __name__ == '__main__':
  prepare()
  
`
