### ISSUE TITLE
Dead code?

### ISSUE THREAD

**Issue by maximumspatium** [unicorn-engine/unicorn#1081]
While working through Unicorn changes to QEMU code, I've stumbled around several code blocks wrapped in `#define CONFIG_PROFILER` that seem to be never used. The most of them reside in `qemu/tcg/tcg.c` and `qemu/tcg/tcg.h`, for example:

https://github.com/unicorn-engine/unicorn/blob/344d0161048147e48297a0e5a011bde3ad23f951/qemu/tcg/tcg.c#L2432-L2442

That function calls `qemu_log()` that has been replaced with `printf()` elsewhere. Moreover, it references the removed global array `tcg_table_op_count` so it won't compile with CONFIG_PROFILER defined.

Is there any reason for keeping that profiler code in Unicorn?

**Comment by aquynh** [comment]
Probably not. You may cleanup with a pull req.
