### ISSUE TITLE
Can't detect stops because of hlt

### ISSUE THREAD

**Issue by rhelmot** [unicorn-engine/unicorn#1082]
When emulating x86, the `hlt` instruction will trigger an immediate exit from uc_emu_start. There should be some indication for the reason for the stop. My suggestion would be to add a `uc_query` entry for "did we halt because of `hlt`". If this is fine, I can implement it and submit a PR.

**Comment by aquynh** [comment]
Halt is for x86 only, so we need a more generic mechanism.

Cant you detect the last exec instruction?

**Comment by rhelmot** [comment]
It is not x86-specific - in qemu/cpus.c on line 181 the clause for stopping if we got a halt is generalized by the EXCP_HLT exception, which can be generated in a variety of cases, all of which (I believe?) are halt-like instructions or conditions.

**Comment by aquynh** [comment]
Cant you look at the last instruction to verify?

hlt may not be the only reason of early exit, so i dont think a new query option.
