### ISSUE TITLE
Support for Cortex-M?

### ISSUE THREAD

**Issue by Lotharyx** [unicorn-engine/unicorn#1085]
Currently, in unicorn.h, amidst the architecture enumeration, is this:

    UC_MODE_MCLASS = 1 << 5,      // ARM's Cortex-M series (currently unsupported)

Mainstream QEMU supports the Cortex-M3; is there a plan to incorporate the Cortex-M capabilities into Unicorn?

I'm trying to trace my way through a Cortex-M3 image (by passing 1 as the "count" argument to `uc_emu_start`), but I can only get one instruction to execute; the second `uc_emu_start` call returns `UC_ERR_INSN_INVALID`.  This is if I use `UC_MODE_THUMB`; the immediately-obvious problem is that the PC register increments by 4 instead of 2 on that first instruction (which is a 16-bit instruction, ldr).  If I use `UC_MODE_MCLASS` or `UC_MODE_ARM`, the very first call to uc_emu_start returns `UC_ERR_INSN_INVALID`.

If I load the same firmware image in mainstream `qemu-system-arm`, QEMU emulates it without issue.  Unicorn is much easier to code against, though!  I hope Cortex-M support arrives soon.

**Comment by yhql** [comment]
Thumb mode has to be enforced (despite `UC_MODE_THUMB` already set) with the LSB of the address you're passing `uc_emu_start` set to 1.

`uc_emu_start(0x4000,0,count=1)` will be one ARM instruction but
`uc_emu_start(0x4001,0,count=1)` will be a Thumb instruction.
