### ISSUE TITLE
hook_intr processing broken for mips64

### ISSUE THREAD

**Issue by cseagle** [unicorn-engine/unicorn#1096]
Within the cpu_exec function in cpu-exec.c you do this:

```
#if defined(TARGET_MIPS) || defined(TARGET_MIPS64)
                    env->active_tc.PC = uc->next_pc;
#endif
```

however uc->next_pc is not set properly in all cases. I am seeing a stale value leftover from a previous syscall and not the address of the next instruction for the current syscall. This is happening the second time I hit this syscall code in a loop. Perhaps it's related to the tcg cache? I don't know enough about tcg, but it seems that if no translation is required (cache hit?) then next_pc  will not get updated.

Regardless, I have stated in the past that the ifdef block above is a bad idea and that PC control should be forced on the user for things like syscall emulation rather than assuming that PC should advance to the next instruction and overriding any attempt the use makes to set PC within their hook_intr handler.

**Comment by aquynh** [comment]
Agreed. If the syscall callback does not act, we advance the PC like it is now. Otherwise, callback can make the decision.

Please pull req.
