### ISSUE TITLE
pip install problems

### ISSUE THREAD

**Issue by Zardows** [unicorn-engine/unicorn#1100]
I tried to install unicorn and I get that:

Collecting unicorn
  Downloading https://files.pythonhosted.org/packages/7d/7f/47fe864fe967e91de2d57677618cffc91bee3918f0a3cdbaa6500b36855e/unicorn-1.0.1.tar.gz (1.5MB)
     |████████████████████████████████| 1.5MB 502kB/s 
Installing collected packages: unicorn
  Running setup.py install for unicorn ... error
    ERROR: Complete output from command /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/tmp/pip-install-3si_utlr/unicorn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-sr9r53ei/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    Building C extensions
    cd qemu && \
    	./configure --cc="cc" --extra-cflags="-DUNICORN_HAS_X86 -DUNICORN_HAS_ARM -DUNICORN_HAS_ARMEB -DUNICORN_HAS_M68K -DUNICORN_HAS_ARM64 -DUNICORN_HAS_MIPS -DUNICORN_HAS_MIPSEL -DUNICORN_HAS_MIPS64 -DUNICORN_HAS_MIPS64EL -DUNICORN_HAS_SPARC -fPIC -fvisibility=hidden -m32 -arch i386 -m64 -arch x86_64" --target-list="x86_64-softmmu, arm-softmmu, armeb-softmmu, m68k-softmmu, aarch64-softmmu, mips-softmmu, mipsel-softmmu, mips64-softmmu, mips64el-softmmu, sparc-softmmu,sparc64-softmmu,"
    
    ERROR: Cannot use 'python', Python 2.4 or later is required.
           Note that Python 3 or later is not yet supported.
           Use --python=/path/to/python to specify a supported Python.
    
    make: *** [qemu/config-host.h-timestamp] Error 1
    error: [Errno 2] No such file or directory: 'libunicorn.dylib'
    ----------------------------------------
ERROR: Command "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/tmp/pip-install-3si_utlr/unicorn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-sr9r53ei/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-3si_utlr/unicorn/

Help please

**Comment by carlsmith** [comment]
You're using the `pip` command included with your Python3 installation (3.7), but the package is for Python 2.

**Comment by 157charles** [comment]
Have you solved it？
wo tried python2 -m install unicorn-1.0.1.tar.gz.
This error occurs.

**Comment by aquynh** [comment]
You can install the 1.0.2-rc1 version with:

pip install --pre unicorn

**Comment by 157charles** [comment]
thank you.
i tried pip install --pre unicorn.
it has resolved.

**Comment by firmianay** [comment]
> You can install the 1.0.2-rc1 version with: pip install --pre unicorn

Hi, the method seems not work on macOS

```
    error: [Errno 2] No such file or directory: '/private/tmp/pip-install-9at2v726/unicorn/src/msvc/x64/Release/libunicorn.dylib'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-9at2v726/unicorn/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-9at2v726/unicorn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-u93oz4ag/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
```

**Comment by aquynh** [comment]
@rhelmot do you have any comments?

**Comment by rhelmot** [comment]
this is a different bug and should have been a different issue but it is an issue. I will push a fix. In the meantime you may work around it by removing `msbuild` from your PATH.

**Comment by Arusekk** [comment]
As of 2020, many distros have default python executable set to python 3.x, while the qemu bundled in 1.0.1 requires python 2 to build, rendering the stable version on PyPI virtually useless.

I would suggest cutting a new release, even from unstable source, but I know that it would influence not only PyPI, but also other package repositories. Do you know of any solutions to this?

**Comment by rhelmot** [comment]
I think pending the current stuff about the python bulld on macos, 1.0.2 should be able to release soon in a pretty stable condition, judging from the recent commit activity.

**Comment by aquynh** [comment]
I can tag 1.0.2-rc2 for this issue.

**Comment by rhelmot** [comment]
can we please just release 1.0.2 as soon as the mac stuff is resolved? it's been two and a half years since 1.0.1. I have to tell people to install with `--pre` in order to resolve problems so often and I am so tired :(

**Comment by aquynh** [comment]
we are still fixing OSS fuzz bugs. i want to have all cleared before 1.0.2 release.

**Comment by rhelmot** [comment]
Can we do the rc2 release now?

**Comment by aquynh** [comment]
yes, i tagged rc2, please update Pypi package, thanks!
