### ISSUE TITLE
calling convention

### ISSUE THREAD

**Issue by P4nda0s** [unicorn-engine/unicorn#1106]
I try to cross build unicorn use NDK, but i found an error when i run samples.
The  function 'helper_uc_tracecode' gets arguments from r0 ~ r3, but actually, the caller pass arguments by stack... how can i solve this problem?

I try to add  inline asm code to solve this problem(file: uc.c)

```c
// TCG helper
void __attribute__((naked)) helper_uc_tracecode(int32_t size, uc_hook_type type, void *handle, int64_t address);
void __attribute__((naked)) helper_uc_tracecode(int32_t size, uc_hook_type type, void *handle, int64_t address){
        asm(
    "LDR R0,[SP] \n\t"       
    "LDR R1,[SP,4] \n\t"
    "LDR R2,[SP,8] \n\t"
    "LDR R3,[SP,0xC] \n\t"
    "b helper_uc_tracecode_real"
    );

}
void helper_uc_tracecode_real(int32_t size, uc_hook_type type, void *handle, int64_t address)
{
.....
}
```

then helper_uc_tracecode runs correctly.however, i found many functions which name starts with ‘helper_’，such as 'helper_wfi_arm' had this problem.

all of their caller  are out of area of .text, maybe are dynamic gen.

**Comment by SmailCatLog** [comment]
https://github.com/unicorn-engine/unicorn/blob/63ebcf41a838bb9e259ba309f2025b1da819e323/qemu/tcg/tcg.c#L2378-L2381


```c++
 #if TCG_TARGET_REG_BITS == 32 && !define(__ARM_ARCH)
     // do this because msvc cannot have arrays with 0 entries. 
     nb_regs = 0; 
 #endif
