### ISSUE TITLE
TLB corrupted during memory callback

### ISSUE THREAD

**Issue by redmercury** [unicorn-engine/unicorn#1111]
The setup is:

1.  Have a read only memory block.
2. Register a callback on that block that updates the memory prior to the read from emulated code.

After accessing the block twice from the emulated code, the emulator segfaults.  Digging in, it appears that uc_mem_write temporarily makes the block writeable for the duration of the write, which then invalidates the TLB for the cpu state.  The helper in softmmu_template.h then uses the now invalidated addend of -1, leading to a crash.

Regression test can be found here:
https://github.com/redmercury/unicorn/commit/829c1615f8b5ce2b25319047260500885018ffac

**Comment by aquynh** [comment]
Nice, can you have a fix?
