### ISSUE TITLE
Potential return using uninitialized stack variable for return code

### ISSUE THREAD

**Issue by awana81** [unicorn-engine/unicorn#1115]
https://github.com/unicorn-engine/unicorn/blob/19ffa83d4353af8834c4c55590ca2ecd357a6bbe/qemu/cpu-exec.c#L100

I'm experiencing an issue where a program behaves differently depending on what is on the stack when calling uc_emu_start. valgrind blames resume_all_vcpus_x86_64 for using uninitialized values, but the value is really the return value from this function (cpu_x86_exec). This line appears to potentially break out without setting "ret" first, so is a potential source. There may be others here, would suggest initializing ret to an error value at the start of the function.

**Comment by aquynh** [comment]
Nice, can you send a pull req?

**Comment by awana81** [comment]
That would require me to actually have a development environment connected to the internet. Mine is currently offline, however,  I can confirm that initializing ret to EXCP_YIELD fixed my specific issue. I don't know it that's the best option, I just needed to avoid having it initialize to EXCP_HLT which happened to be what was on the stack in my case due to previous calls to uc_emu_start.

**Comment by aquynh** [comment]
Initialize ret to 0 should be fine for your case, too.

**Comment by awana81** [comment]
Yeah, that works

**Comment by aquynh** [comment]
i pushed a fix for this, by set ret = 0, thanks.
