### ISSUE TITLE
Possible incorrect x86 mov instruction emulation 

### ISSUE THREAD

**Issue by tulipszs** [unicorn-engine/unicorn#1116]
I am experiencing an issue where the interpretation/execution of an x86 instruction differs under unicorn and real hardware:

Expected instruction:
`8B 0D 28 0A D5 60    mov ecx, dword [0x60d50a2e]`

However, unicorn (and capstone) seem to interpret that sequence of byes as follows:
```
In [19] instruction = next(cs.disasm(b'\x8B\x0D\x28\x0A\xD5\x60', offset=0))
In [20] print(instruction.mnemonic + "\t" + instruction.op_str)
mov    ecx, dword ptr [rip + 0x60d50a28]
```

Radare2 seems to disassemble it to match the expected execution:
```
$ cat ~/error 
wx 8B0D280AD560
b 8
pd 1
$ r2 -qi ~/error -
            0x00000000      8b0d280ad560   mov ecx, dword [0x60d50a2e] ; 
```

During emulation this causes an invalid memory access since `RIP+0x60d50a2e` is an incorrect source address. Am I experiencing a bug or have I configured something incorrectly? Any tips on working past this would very much be appreciated. 

Thanks

Edit: I'm on unicorn version 1.0.1

**Comment by aquynh** [comment]
Can you post a minimize sample (as simple as possible) to trigger this
issue? Make it reliably reproduceable is the first step toward right fix.

**Comment by tulipszs** [comment]
After more digging I found that the target binary mixes 32 bit code and 64 bit code. Initializing unicorn to 32 bit mode fixed the above issue.
