### ISSUE TITLE
Segementation fault when setting FS register to any value above 0x3

### ISSUE THREAD

**Issue by tulipszs** [unicorn-engine/unicorn#1117]
When initializing the FS segment register to anything above 0x3, unicorn segfaults. This doesn't happen when unicorn is initialized with `UC_MODE_64`. 

```
Python 3.7.3 (default, Jun 24 2019, 04:54:02) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.6.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from unicorn import *                                                                                                           
In [2]: from unicorn.x86_const import *                                                                                                 
In [3]: uc = Uc(UC_ARCH_X86, UC_MODE_32)                                                                                                
In [4]: uc.reg_write(UC_X86_REG_FS, 0x3)                                                                                                
In [5]: uc.reg_write(UC_X86_REG_FS, 0x4)                                                                                                
Segmentation fault (core dumped)
```

**Comment by tulipszs** [comment]
I'm attempting to setup a GDT assuming that the segmentation fault is due to memory not being setup correctly..? 

(Python 3)
Code: https://gist.github.com/tulipszs/483154d6a659d9514d8a5775d5f4d8f1

I feel like the above shouldn't segfault and should return an invalid memory access. Any ideas? I'm unable to emulate my guest code because I'm unable to initialize the FS register / GDT (Which is used to access the TEB on Windows).

**Comment by aquynh** [comment]
this should be fixed now, please confirm

**Comment by Waterman178** [comment]
thanks
