### ISSUE TITLE
Why cant change UC_ARM64_REG_PC on Mac

### ISSUE THREAD

**Issue by deathmemory** [unicorn-engine/unicorn#1119]
When I execute this instruction in `UC_HOOK_CODE` function, on Mac 
```python
uc.reg_write(UC_ARM64_REG_PC, address + size)
```
`mu.emu_start()` will return immediately, the emulate stoped .

When I execute on Linux , it run ok.

Is it a bug  ?  Or some mistakes i made ?

my env :
python 2.7.15rc1
unicorn 1.0.2
macOs 10.13.6

**Comment by ePirat** [comment]
Maybe a duplicate of https://github.com/unicorn-engine/unicorn/issues/689

Maybe try compiling in debug mode (without optimizations) and try again? I ran into this issue a while ago and using a non-optimized build could work around it.

**Comment by Waterman178** [comment]
mark
