### ISSUE TITLE
Cross compiling a binary for unicorn to run 

### ISSUE THREAD

**Issue by RossComputerGuy** [unicorn-engine/unicorn#1128]
I'm trying to cross compile an aarch64 C program and I'm just normally compiling it with a cross compiler (aarch64-linux-gnu-gcc) and I cannot get it to run in my program which uses unicorn. Every time I try running the program, I get an interrupt and my hook catches it and says "Interrupt running 0x1". Can someone please explain to me why my program won't run correctly?

**Comment by dargueta** [comment]
How are you setting up the program? Are you compiling it to a flat binary, or some sort of executable format (ELF, PE, etc) and unpacking it in memory?

**Comment by RossComputerGuy** [comment]
Flat binary

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by dargueta** [comment]
And you're sure you're loading it into memory correctly, linking in the libraries it needs, going through all the relocation tables, etc.?

**Comment by RossComputerGuy** [comment]
Sent from ProtonMail mobile

-------- Original Message --------

**Comment by dargueta** [comment]
I think your reply got cut off or something.

**Comment by RossComputerGuy** [comment]
I said yes

**Comment by dargueta** [comment]
ARM64 is capable of switching endianness, right? I'm kinda grasping at straws here but you might want to try fiddling with the processor endianness. :neutral_face:
