### ISSUE TITLE
Uc.emu_stop() doesn't work in a hook if PC is updated.

### ISSUE THREAD

**Issue by Azertinv** [unicorn-engine/unicorn#1133]
As the title say emu_stop() won't work properly if we update the PC inside of a hook with the same type.

Example:
```python
from unicorn import *
from unicorn.x86_const import *

uc = Uc(UC_ARCH_X86, UC_MODE_64)

"""
    nop
    nop
    nop
    nop
    nop
    nop
    int 0x80
"""

sc = "909090909090CD80".decode("hex")
uc.mem_map(0, 0x1000)
uc.mem_write(0, sc)

def hook0(uc, addr, size, user_data):
    print("hook0 at 0x{:x}".format(addr))
    uc.reg_write(UC_X86_REG_RIP, uc.reg_read(UC_X86_REG_RIP) + 1)
    uc.emu_stop()

def hook1(uc, addr, size, user_data):
    print("hook1 at 0x{:x}".format(addr))
    uc.emu_stop()

uc.hook_add(UC_HOOK_CODE, hook0, begin=1, end=1)
# uc.hook_add(UC_HOOK_CODE, hook1, begin=2, end=2)
uc.emu_start(0, 20, 5000)
```

result:
```
hook0 at 0x1
Traceback (most recent call last):
  File "test.py", line 31, in <module>
    uc.emu_start(0, 20, 5000)
  File "build/bdist.linux-x86_64/egg/unicorn/unicorn.py", line 316, in emu_start
unicorn.unicorn.UcError: Unhandled CPU exception (UC_ERR_EXCEPTION)
```

Here the emulator fall through to the int 0x80 instruction.

I didn't manage to find the root cause but I think it has something to do with a special case for updates to PC registers.

**Comment by crass** [comment]
I believe I've hit this issue, however I'm having trouble creating a minimal example where this is triggered. I'd hoped that this would be it, but I can't seem to get it to trigger either. I realize this is an old issue, so I tested back to b55bbd0ac and still the emu_stop appears to work as it should. So I'm confused and wondering if there's some additional condition needed to trigger this.
