### ISSUE TITLE
How to use `UC_HOOK_INSN` with ARM?

### ISSUE THREAD

**Issue by goodguysoft** [unicorn-engine/unicorn#1135]
`UC_HOOK_INSN` requires instruction code. For x86, there is `uc_x86_insn` enumeration with instruction codes.

For ARM, there are no such enumeration.

So, how to use `UC_HOOK_INSN` with ARM?

**Comment by gerph** [comment]
I don't believe that those hooks work with ARM. I couldn't see a way to use them, myself.
