### ISSUE TITLE
`UC_HOOK_CODE` under `ARM`: why `PC` value sometimes changes we stop emulation from hook?

### ISSUE THREAD

**Issue by goodguysoft** [unicorn-engine/unicorn#1142]
Lets imagine following simple code:
```
void StepHook(uc_engine * uc, uint64_t address, uint32_t size, void *user_data)
{
    uint32_t pc_value;
    uc_reg_read(uc, uc_arm_reg::UC_ARM_REG_PC, &pc_value));
    std::cout << "pc = " << pc << "\r\n";
    uc_emu_stop(uc);
}
uc_hook code_hook;
uc_hook_add(engine, &code_hook, uc_hook_type::UC_HOOK_CODE, &CodeHook, nullptr, 0, 0);
uc_emu_start(engine, instruction_pointer, (std::numeric_limits<uint64_t>::max)(), 0, steps_count);
uint32_t pc_value;
uc_reg_read(uc, uc_arm_reg::UC_ARM_REG_PC, &pc_value));
std::cout << "pc = " << pc << "\r\n";
```
Here we setup code hook and print `PC` value at this hook and stop emulation.

After emulation finished, it prints `PC` value again.

I expect that `PC` value printed from `StepHook` is the same one that we have after `uc_emu_stop`. Sometimes it is true, and sometimes I get different value.

Can anyone explain why `PC` changes its value after `uc_emu_stop`? It makes it impossible to continue execution at the point where we stopped it, because we don't know where we stopped if `PC` value after emulation finished is something random instead of last instruction `PC`.

**Comment by gerph** [comment]
I've not found that doing anything much within those code hooks was reliable, myself. Basically, I have only found that these are useful for information, and not for changing the state.

However, your issue with `emu_stop` within the block may be related to how the pc is reset after the block terminates; I gave some details about how the PC would move around go backwards if you stopped at arbitrary points, and a possible fix in https://github.com/unicorn-engine/unicorn/issues/1105

The author of unicorn suggested that this probably right but insufficient - there's a couple of other cases that I need to catch. I intend to go back and produce a proper patch for that, but I've not needed to just yet, as I'm not heavily reliant on out-of-band termination of execution. Yet. Very soon I'm going to need that, so I keep feeling I should investigate further and do a proper fix to push upstream - but haven't yet.

If you have a quick look at that issue, you might see whether the issue you're seeing is similar to what I was seeing.

**Comment by hosaka-corp** [comment]
Are you branching into THUMB code? FYI I just realized that THUMB state is not necessarily encoded in the PC at the time of `emu_stop()`. This caused me to continue running in ARM mode, where I'd eventually die at some other random location after successfully interpreting a bunch of THUMB code as ARM code. 

```python
...
while True:
  try:
    pc = mu.reg_read(UC_ARM_REG_PC)
    if ((mu.reg_read(UC_ARM_REG_CPSR) & 0x20) != 0):
      pc |= 1
    mu.emu_start(pc, ..., count=2000)
    do_io_things()
    ...
  except UcError as e:
    ...
```

Perhaps this is related?

**Comment by goodguysoft** [comment]
I am aware about the fact that `Unicorn` switches ARM or Thumb automatically each time `emu_start` executed. It is actually expected behavior, because `emu_start` is similar to `BX`.

However, my issue is unrelated to ARM/Thumb automatic switch.
