### ISSUE TITLE
Interrupting thread race condition with hooks

### ISSUE THREAD

**Issue by gerph** [unicorn-engine/unicorn#1153]
Hiya,

I've been seeing an error where I'm getting an exception from my code (I'm using an ARM system):

`UcError: Unhandled CPU exception (UC_ERR_EXCEPTION)`

which was not understandable to me, as there should be NO unhandled CPU exceptions. I've  installed an exception hook on interrupts. The code inside `cpu-exec.c` is:

                    HOOK_FOREACH_VAR_DECLARE;
                    HOOK_FOREACH(uc, hook, UC_HOOK_INTR) {
                        ((uc_cb_hookintr_t)hook->callback)(uc, cpu->exception_index, hook->user_data);
                        catched = true;
                    }
                    // Unicorn: If un-catched interrupt, stop executions.
                    if (!catched) {
                        cpu->halted = 1;
                        uc->invalid_error = UC_ERR_EXCEPTION;
                        ret = EXCP_HLT;
                        break;
                    }

So if there is any hook present for INTR, it should always set `catched` and the condition that sets the `invalid_error` will never be triggered. So I had to look at the `HOOK_FOREACH` macro to see what it's doing, and the problem jumped out immediately...

```
// for loop macro to loop over hook lists
#define HOOK_FOREACH(uc, hh, idx)                         \
    for (                                                 \
        cur = (uc)->hook[idx##_IDX].head;                 \
        cur != NULL && ((hh) = (struct hook *)cur->data)  \
            /* stop excuting callbacks on stop request */ \
            && !uc->stop_request;                         \
        cur = cur->next)
```

The `uc->stop_request` should not be there. That means that if you've interrupted the system, hooks may not be executed, which means that so many things might not happen as you expect. In my case it meant that the 'impossible' condition of a CPU exception not being expected but being triggered, rather than my hook being called, happened.

If you've got hooks happening - for instructions, for memory checks, for blocks, for exceptions, etc - the fact that you've requested a stop shouldn't prevent the system from executing those hooks. If the hook execution is prevented, the system will do things differently than it was expected to, and resuming operation will be difficult if not impossible because a non-deterministic set of operations will have been performed.

I'd suggest that that check inside the `HOOK_FOREACH` macro should be removed, and the only place that the system should actually act on the `stop_request` should be the top level loop.

**Comment by gerph** [comment]
I have raised PR #1154 with this small change.

**Comment by Waterman178** [comment]
thanks

**Comment by gerph** [comment]
If you're looking to do a 1.0.2 release soon, this would be a useful change to include, as without it the use of hooks on instructions with a timer installed can be fatal.

**Comment by gerph** [comment]
Again, can I ask that if you're doing a 1.0.2 release soon (rc2 having been made this morning), can you please consider this change for merging.

This causes actual fatal problems if timers are in use and hooks change the behaviour of the system. It is not some academic issue, but one that requires that I distribute a special compiled version of Unicorn in order to have a functioning system.
