### ISSUE TITLE
Java binding use CodeHook on Windows, will invoke callback before every instruction.

### ISSUE THREAD

**Issue by wizdzz** [unicorn-engine/unicorn#1164]
Unicorn version 1.0.2-rc1
OS : Windows7 x64
JDK version: 1.8.0_121

I am trying use Unicorn on Windows Java, but found something that not turn out with my expect.
I compiled the needed dll(libunicorn_java.dll) for my Java code, and use the official test code of "Sample_arm.java";
and the "CodeHook" makes me confusing.

The code hooked ADDRESS(which is 0x10000) on line 68, and then call "emu_start" to start it;
so MyCodeHook.hook will be called **when the pc is 0x10000 only**,
but the fact is **it has been called before any instructions**:

![1](https://user-images.githubusercontent.com/38684262/67462910-0362f680-f673-11e9-881f-420453d95ab3.png)

so i checked "unicorn-master\bindings\java\unicorn_Unicorn.c";
 found the Jni function invoke "uc_hook_add" to add the hook handler:
```
err = uc_hook_add((uc_engine*)eng, &hh, (uc_hook_type)type, cb_hookcode, env, 1, 0, arg1, arg2);  // unicorn_Unicorn.c, line 587
```
noticed the last four params are:
"1, 0, arg1, arg2", on the caller, I really dont' know what the meaning of "1, 0",  but the last two params are begin address and end address;
However, according to the definition of uc_hook_add:
```
uc_err uc_hook_add(uc_engine *uc, uc_hook *hh, int type, void *callback,
        void *user_data, uint64_t begin, uint64_t end, ...);  // unicorn.h, line 561
```
"1, 0, arg1, arg2" should be explain as "begin is 1, end is 0, arg1 and arg2 will seem as variable arguments";
So, this is the problem, the params of "1, 0" hit the condition of **"For the special case in which begin > end, the callback will be invoked for ALL instructions.
"**, 
then i **simply modified the four params to "arg1, arg2"**, and compile it, with the new dll, i get the "right answer".

I found the last modification of unicorn_Unicorn.c was three years ago, but "uc.c" was two months ago, so maybe the "unicorn_Unicorn.c" need update ?

**Comment by wtdcode** [comment]
Just quote from #1434.

> The issue you described seems the expected behavior, too.
> 
> BTW, thanks for your interest. Sorry that Unicorn lack of contributors currently and I'm not familiar with JNI unfortunately.
