### ISSUE TITLE
Anyway to get current instruction in a hook?

### ISSUE THREAD

**Issue by james-tate** [unicorn-engine/unicorn#1169]
Done a bit of searching but no luck. I am looking to have some type of mnemonic print out in instruction hooks. I can do it in a round about way with something like keystone, but didn't know if unicorn has built-in ability to give you the assembled instruction.

**Comment by gerph** [comment]
Unicorn doesn't have a disassembler built in; for my case I use capstone (keystone is the assembler, and capstone is the disassembler).
