### ISSUE TITLE
Extend uc_open() to specify CPU model

### ISSUE THREAD

**Issue by aquynh** [unicorn-engine/unicorn#117]
we need to let users to specify CPU model at the time the engine is initialized. this is highlighted with a recent issue https://github.com/unicorn-engine/unicorn/issues/114#issuecomment-138341814

one way to do this is to extend `uc_open()` to contain one more param for CPU model. something like:

```
uc_err uc_open(uc_arch arch, uc_mode mode, uc_cpu model, uc_engine **uc);
```

any comments?

**Comment by Normmatt** [comment]
Any news on this? I'd really like to be able to have two arm cpus running at the same type both being different models (ARM946 and ARM1176).

**Comment by lunixbochs** [comment]
Writing a 3DS emulator? :)

**Comment by Normmatt** [comment]
maybe...

**Comment by aquynh** [comment]
we should not allow to change the CPU model after initializing the engine, so the only place to set the model is inside `uc_open()`. but it is ugly to have `uc_open_ex()` just for this, so i think we will have to break compatibility by adding one more argument to `uc_open()`, like below.

    uc_err uc_open(uc_arch arch, uc_mode mode, const char *model, uc_engine **uc);

in which if model = NULL, we go for the default model (for ex, with X86 default model is the latest CPU model, or with ARM it is "cortex-a15")

thoughts?

**Comment by aquynh** [comment]
i created a new branch https://github.com/unicorn-engine/unicorn/tree/cpu_model to implement the idea above: `uc_open()` now takes one more argument **model** in https://github.com/unicorn-engine/unicorn/blob/cpu_model/include/unicorn/unicorn.h#L262, so it is possible to specify CPU model at initialization time. pass NULL to this if you want to use the default CPU model (which is latest model for X86, Arm & Arm64 for now)

the Python binding of class `Uc` was already updated to accept a default model=None so if we ignore this argument, the default CPU model is used: https://github.com/unicorn-engine/unicorn/blob/cpu_model/bindings/python/unicorn/unicorn.py#L154

@Normmatt : can you test this branch to see if it works for you?

thanks.

**Comment by aquynh** [comment]
@Normmatt, any feedback on the "cpu_model" branch that provides what you requested?

**Comment by Normmatt** [comment]
I haven't had a chance to setup a development environment to compile this yet. (Windows)

**Comment by aquynh** [comment]
@Normmatt, have you tried that branch yet, even on Linux/OSX? let us know if you have any issues.

**Comment by aquynh** [comment]
any objection if i merge the branch "cpu_model" to "master"? 

@cseagle, @enkomio: this needs your attentions since this API change on `uc_open()` will break the Java & .NET bindings. at the moment Python & Go bindings already supported this.

**Comment by enkomio** [comment]
I will update the .NET binding.

**Comment by kitling** [comment]
Any news? I'd like to more closely emulate my platform of choice (Raspberry Pi) by selecting the precice model of CPU it has. This isn't too important to my application though, I think.

I see that the cpu_model branch exists, however, it doesn't appear to be merged in, and is way behind master at this point. Is it because you never recieved the okay from some binding maintainers?

**Comment by aquynh** [comment]
Let me look at that again to see how best to implement this. It is best if
we dont break any API.

**Comment by EverOddish** [comment]
I'm also interested in specifying a specific ARM CPU model. I've hard-coded it in my own build for now.

**Comment by aquynh** [comment]
which model do you use?

**Comment by wtdcode** [comment]
Re-open and link to #1449

**Comment by wtdcode** [comment]
Closed due to `uc_ctl` added.
