### ISSUE TITLE
build for ios

### ISSUE THREAD

**Issue by hulovebin** [unicorn-engine/unicorn#1177]
$ ./make.sh ios_arm64
make.sh - The build script for unicorn engine
USAGE:
    $ ./make.sh [OPTIONS]
OPTIONS:
                            Build the project
    asan                    Build for ASan
    install                 Install the project
    uninstall               Uninstall the project
    macos-universal         Build universal binaries on macOS
    macos-universal-no      Build non-universal binaries that includes only 64-bit code on macOS
    cross-win32             Cross-compile Windows 32-bit binary with MinGW
    cross-win64             Cross-compile Windows 64-bit binary with MinGW
    cross-android_arm       Cross-compile for Android Arm
    cross-android_arm64     Cross-compile for Android Arm64
    linux32                 Cross-compile Unicorn on 64-bit Linux to target 32-bit binary
    msvc_update_genfiles    Generate files for MSVC projects

**Comment by UESTC-LXY** [comment]
the same problem
