### ISSUE TITLE
How to distinguish between ARM and THUMB?

### ISSUE THREAD

**Issue by CCint3** [unicorn-engine/unicorn#1181]
[Python code] ARM cpu uses PC & 1 to distinguish between ARM instructions and thumb instructions; how does the simulator do this?
No matter whether ARM instruction or THUMB instruction is about to be executed, (mu.reg_read (UC_ARM_REG_PC) & 1 == 0) is always true.

**Comment by gerph** [comment]
The PC representation used for BX  and BLX (and some others) is to incorporate the mode into the lowest bits of the PC. However, that's secondary to the CPSR. The branching flags on the PC indicate that a mode change should occur when the branch is taken (a change into or out of Thumb mode), but this actually indicates that the CPSR's state should be changed.

CPSR bit 5 indicates whether Thumb mode is active or not. If clear, it's ARM mode [1]. When bit 0 is set on the branch address, the thumb mode flag in the CPSR is updated to reflect the status. If the bit is clear it is reset to indicate ARM mode.

Unicorn follows the same rules as the CPU, so the CPSR state is what determines whether ARM or Thumb code will be executed. If you're in a hook, you can determine the mode, therefore, by reading the CPSR and checking the Thumb flag - and then take appropriate action based on that. Each basic block will (as far as I understand the emulation), only ever contain ARM or Thumb - never a mix, as any mode change would terminate the basic block - so you can guarantee that you're executing only a single instruction set when the block hooks are called.

[1] Actually it's a little more complex than that, but in terms of your question, this suffices. Consult the ARM ARM for more detail on the processor modes and how they're controlled by the CPSR.

**Comment by CCint3** [comment]
> The PC representation used for BX and BLX (and some others) is to incorporate the mode into the lowest bits of the PC. However, that's secondary to the CPSR. The branching flags on the PC indicate that a mode change should occur when the branch is taken (a change into or out of Thumb mode), but this actually indicates that the CPSR's state should be changed.
> 
> CPSR bit 5 indicates whether Thumb mode is active or not. If clear, it's ARM mode [1]. When bit 0 is set on the branch address, the thumb mode flag in the CPSR is updated to reflect the status. If the bit is clear it is reset to indicate ARM mode.
> 
> Unicorn follows the same rules as the CPU, so the CPSR state is what determines whether ARM or Thumb code will be executed. If you're in a hook, you can determine the mode, therefore, by reading the CPSR and checking the Thumb flag - and then take appropriate action based on that. Each basic block will (as far as I understand the emulation), only ever contain ARM or Thumb - never a mix, as any mode change would terminate the basic block - so you can guarantee that you're executing only a single instruction set when the block hooks are called.
> 
> [1] Actually it's a little more complex than that, but in terms of your question, this suffices. Consult the ARM ARM for more detail on the processor modes and how they're controlled by the CPSR.
