### ISSUE TITLE
Segmentation Fault emulating MIPS on ARM 

### ISSUE THREAD

**Issue by domenukk** [unicorn-engine/unicorn#1183]
When running [the simple test harness of afl unicorn](https://github.com/Battelle/afl-unicorn/blob/master/unicorn_mode/samples/simple/simple_test_harness.py)  (without any afl patches!) using Unicorn 1.0.2rc1 on the Raspberri PI, the following line crashes with segmentation fault:
https://github.com/unicorn-engine/unicorn/blob/24f55a7973278f20f0de21b904851d99d4716263/qemu/target-mips/op_helper.c#L2277

The stack is completely bogus when it crashes. No clue what's going on, sadly. It works fine on x86...

Command line:
```bash
➜  simple git:(master) python simple_test_harness.py sample_inputs/sample1.bin
Loading data input from sample_inputs/sample1.bin
Starting the AFL forkserver by executing 1 instruction
[1]    20476 segmentation fault  python simple_test_harness.py sample_inputs/sample1.bin
```

**Comment by SmailCatLog** [comment]
https://github.com/unicorn-engine/unicorn/issues/1203#issue-562135253

retry it

**Comment by wtdcode** [comment]
Link to #1217 #1449

**Comment by wtdcode** [comment]
Seems fixed already.
