### ISSUE TITLE
UC_X86_REG_GS_BASE disappeared

### ISSUE THREAD

**Issue by Waterman178** [unicorn-engine/unicorn#1185]
I cannot find UC_X86_REG_GS_BASE UC_X86_REG_FS_BASE  in the master branch.what is going on?How can i set the kernel gs base?

**Comment by aquynh** [comment]
Were they there before?

**Comment by Waterman178** [comment]
> Were they there before?
I found that some code in the master branch is missing.Like below:
in function  x86_reg_read(struct uc_struct *uc, unsigned int *regs, void **vals, int count) at 794 line:
and function x86_reg_write(struct uc_struct *uc, unsigned int *regs, void *const *vals, int count) at 1428 line:
 
![image](https://user-images.githubusercontent.com/14991217/71984196-56f0e380-3263-11ea-9e79-92f9c4000ef8.png)

I have watched the master branch, some code has changed, but I don't see any notifications or related commits, issues.Like below:
in function tb_invalidate_phys_page_fast() at 1453 line:
[original]
`if ((nr & (BITS_PER_LONG - 1)) > 32){
    b = 0;
} else {
    b = p->code_bitmap[BIT_WORD(nr)] >> (nr & (BITS_PER_LONG - 1));
}`
[now]
`b = p->code_bitmap[BIT_WORD(nr)] >> ((nr & (BITS_PER_LONG - 1)) & 0x1f);`

what is going on？

**Comment by aquynh** [comment]
You can find them from some of the latest pull req, that got merged recently

**Comment by aquynh** [comment]
do you mean this? https://github.com/unicorn-engine/unicorn/pull/1166

**Comment by Waterman178** [comment]
Yes, but I remember this code has been merged into the master branch,really weird.And which commit does the code below come from?
in function tb_invalidate_phys_page_fast() at 1453 line:
[original]
if ((nr & (BITS_PER_LONG - 1)) > 32){ b = 0; } else { b = p->code_bitmap[BIT_WORD(nr)] >> (nr & (BITS_PER_LONG - 1)); }
[now]
b = p->code_bitmap[BIT_WORD(nr)] >> ((nr & (BITS_PER_LONG - 1)) & 0x1f);

**Comment by Waterman178** [comment]
> do you mean this? #1166

Yes, but I remember this code has been merged into the master branch,really weird.And which pull req does the code below come from?
in function tb_invalidate_phys_page_fast() at 1453 line:
[original]
if ((nr & (BITS_PER_LONG - 1)) > 32){ b = 0; } else { b = p->code_bitmap[BIT_WORD(nr)] >> (nr & (BITS_PER_LONG - 1)); }
[now]
b = p->code_bitmap[BIT_WORD(nr)] >> ((nr & (BITS_PER_LONG - 1)) & 0x1f);

**Comment by aquynh** [comment]
You can run "git blame" on that file and see

**Comment by Waterman178** [comment]
thanks!I ’ve been comparing code manually, and it looks like I need to research git tools

**Comment by Waterman178** [comment]
> You can run "git blame" on that file and see

thanks!I ’ve been comparing code manually, and it looks like I need to research git tools
