### ISSUE TITLE
M68K Unhandled CPU exception on add.i instruction

### ISSUE THREAD

**Issue by zznop** [unicorn-engine/unicorn#1187]
Unicorn (qemu?) is unable to emulate the dbf instruction depicted below. The result is a `UC_ERR_EXCEPTION`.

![image](https://user-images.githubusercontent.com/14361933/72214121-0c24d500-34ca-11ea-9ab1-4cfc6cd2bf62.png)

**Comment by zznop** [comment]
Revisited this project and it's actually breaking on the `addi.w` instruction, not the `dbf` instruction

**Comment by wtdcode** [comment]
Please have a try on our new uc2.

**Comment by zznop** [comment]
@wtdcode I've tried on UC2, still doesn't work. See https://github.com/unicorn-engine/unicorn/issues/1502
