### ISSUE TITLE
Upgrade used QEMU to 4.2

### ISSUE THREAD

**Issue by XVilka** [unicorn-engine/unicorn#1190]
There were TONS of changes since:
- An upcoming https://wiki.qemu.org/ChangeLog/5.0
- https://wiki.qemu.org/ChangeLog/4.2
- https://wiki.qemu.org/ChangeLog/4.1
- https://wiki.qemu.org/ChangeLog/4.0
- https://wiki.qemu.org/ChangeLog/3.1
- https://wiki.qemu.org/ChangeLog/3.0
- https://wiki.qemu.org/ChangeLog/2.8
- https://wiki.qemu.org/ChangeLog/2.7
- https://wiki.qemu.org/ChangeLog/2.6
- https://wiki.qemu.org/ChangeLog/2.5
- https://wiki.qemu.org/ChangeLog/2.4
- https://wiki.qemu.org/ChangeLog/2.3

**Comment by aquynh** [comment]
Unicorn inspires many cool ideas, that we believe it deserves serious upgrade. This is what everyone wants, but unfortunately requires huge effort & lots of time.

Who can sponsor Unicorn 2? Contact us.

**Comment by Halastra** [comment]
Pardon the question, but I've just come across this [fork of unicorn](https://github.com/yuzu-emu/unicorn/tree/master/qemu), which is [claimed](https://news.ycombinator.com/item?id=18302424) to follow upstream qemu more closely.

Are you familiar with this? 
Do you think this fork might compromise this project's priorites (e.g. thread safeness, oss-fuzz compatibility, instrumentation etc.)?

**Comment by XVilka** [comment]
@aquynh I suggest to pin this issue.

**Comment by aquynh** [comment]
@XVilka yes
