### ISSUE TITLE
Block hooks called twice immediately following an emulation stop

### ISSUE THREAD

**Issue by gerph** [unicorn-engine/unicorn#1193]
I'm seeing problem with the block hook being called twice (with no intervening code execution) when the emulation was stopped in the previous emulation cycle. That seems rather difficult to explain, so I'll give a sequence that causes it:

1. Register a block hook.
2. Register an exception hook (UC_HOOK_INTR)
3. Start execution of code (emu_start)
4. Our block hook is called to say that we're executing our code
5. When an exception instruction is executed, the hook issues an emu_stop to request that the system return.
6. We return from emu_start, and do whatever we need to do to handle the exception.
7. Start execution of code again.
8. Our block hook is called to say that we execute the instructions after the exception instruction.
9. Our block hook is called AGAIN, with the same block.
10. Execution continues.

That's the sequence that happens in the failure case, and if we insert hooks for code, we see that between the block hook being called at step 8 and step 9, no code is executed (or at least, no code hook is executed, and by constructing the code in known ways, it is clear that the code is not executed.

Actual example code that exhibits this issue:

```python
# Demonstrate the repeated block hooks being called.

from capstone import *
import capstone.arm_const

from unicorn import *
import unicorn.arm_const as arm

# The bit pattern that is used here is intended to expose execution issues:
#  * If an instruction is executed twice, there's a gap in the bit pattern that
#    will be filled (ie odd bits should never be set in normal execution)
#  * If a block is executed twice, multiple bits will be affected.
armcode = """
    8000 : .... : E3A00902 : MOV     r0,#&8000
    8004 : .... : E2800001 : ADD     r0,r0,#&1 ; = 1
    8008 : .... : E2800004 : ADD     r0,r0,#&4 ; = 4
    800C : .... : EF000001 : SWI     1
    8010 : .... : E2800010 : ADD     r0,r0,#&10 ; = 16
    8014 : @... : E2800040 : ADD     r0,r0,#&40 ; = 64
    8018 : .... : EF000002 : SWI     2
    801C : .... : E2800C01 : ADD     r0,r0,#&100 ; = 256
    8020 : .... : E3A0F000 : MOV     pc,#&0
"""

md = Cs(CS_ARCH_ARM, CS_MODE_ARM)
md.detail = True
md.syntax = CS_OPT_SYNTAX_NOREGNAME

code = []
lines = armcode.splitlines()
for line in lines:
    if line:
        # Change the little-endian string to a set of characters
        inst = line[18:26]
        chars = list(inst.decode('hex'))
        chars.reverse()
        code.extend(chars)

code = ''.join(code)

def diss(codeword, address):
    for i in md.disasm(codeword, address):
        print("0x%08x: %-8s %s" %(i.address, i.mnemonic, i.op_str))

def hook_block(uc, address, size, user_data):
    print("Block execution at 0x%08x + %x" % (address, size))

def hook_code(uc, address, size, user_data):
    codeword = uc.mem_read(address, 4)
    diss(codeword, address)

def hook_intr(uc, intno, user_data):
    print("CPU Exception %i" % (intno,))
    # Request that the emulation stops
    uc.emu_stop()


reg_map = [
        arm.UC_ARM_REG_R0,
        arm.UC_ARM_REG_R1,
        arm.UC_ARM_REG_R2,
        arm.UC_ARM_REG_R3,
        arm.UC_ARM_REG_R4,
        arm.UC_ARM_REG_R5,
        arm.UC_ARM_REG_R6,
        arm.UC_ARM_REG_R7,
        arm.UC_ARM_REG_R8,
        arm.UC_ARM_REG_R9,
        arm.UC_ARM_REG_R10,
        arm.UC_ARM_REG_R11,
        arm.UC_ARM_REG_R12,
        arm.UC_ARM_REG_SP,
        arm.UC_ARM_REG_LR,
        arm.UC_ARM_REG_PC,
    ]


# Base for the code
ADDRESS = 0x8000

# Initialize emulator in ARM mode
mu = Uc(UC_ARCH_ARM, UC_MODE_ARM)

# map 4K memory for this emulation
mu.mem_map(ADDRESS, 4 * 1024)

# Write the code to memory.
mu.mem_write(ADDRESS, code)

# Trace execution with a block, code hook and interrupt
mu.hook_add(UC_HOOK_BLOCK, hook_block, begin=ADDRESS, end=ADDRESS + 4 * 1024)
mu.hook_add(UC_HOOK_CODE, hook_code, begin=ADDRESS, end=ADDRESS + 4 * 1024)
mu.hook_add(UC_HOOK_INTR, hook_intr, begin=ADDRESS, end=ADDRESS + 4 * 1024)

mu.reg_write(arm.UC_ARM_REG_PC, ADDRESS)
while True:
    try:
        pc = mu.reg_read(arm.UC_ARM_REG_PC)
        print("Begin execution at 0x%08x" % (pc,))
        mu.emu_start(pc, ADDRESS + len(code))
    except UcError as exc:
        print("Exception: %s (errno=%i)" % (exc, exc.errno))
        if exc.errno == UC_ERR_FETCH_UNMAPPED:
            # That branch through 0 at the end of the code means that we're done
            break

        if exc.errno == UC_ERR_EXCEPTION:
            # An unhandled exception (which never happens, because we trap them in the hook)
            print("Unhandled CPU exception")
            pass

print("Finished, now print the registers")
for regnum, regcode in enumerate(reg_map):
    regvalue = mu.reg_read(reg_map[regnum])
    print("  r%-2i : %08x / %-3i" % (regnum, regvalue, regvalue))

# Show the bits to check that we actually have the right ones set
print("Bits in R0")
r0 = mu.reg_read(reg_map[0])
for bit in range(16):
    value = 1<<bit
    state = 'SET' if r0 & value else '0'
    print("Bit %2i (% 8x) : %s" % (bit, value, state))
```

This displays the following output, which shows that the block hook is being called twice, although no actual execution occurs.

```
Begin execution at 0x00008000
Block execution at 0x00008000 + 10
0x00008000: mov      r0, #0x8000
0x00008004: add      r0, r0, #1
0x00008008: add      r0, r0, #4
0x0000800c: svc      #1
CPU Exception 2
Begin execution at 0x00008010
Block execution at 0x00008010 + c
Block execution at 0x00008010 + c
0x00008010: add      r0, r0, #0x10
0x00008014: add      r0, r0, #0x40
0x00008018: svc      #2
CPU Exception 2
Begin execution at 0x0000801c
Block execution at 0x0000801c + 8
Block execution at 0x0000801c + 8
0x0000801c: add      r0, r0, #0x100
0x00008020: mov      pc, #0
Exception: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED) (errno=8)
Finished, now print the registers
  r0  : 00008155 / 33109
  r1  : 00000000 / 0  
  r2  : 00000000 / 0  
  r3  : 00000000 / 0  
  r4  : 00000000 / 0  
  r5  : 00000000 / 0  
  r6  : 00000000 / 0  
  r7  : 00000000 / 0  
  r8  : 00000000 / 0  
  r9  : 00000000 / 0  
  r10 : 00000000 / 0  
  r11 : 00000000 / 0  
  r12 : 00000000 / 0  
  r13 : 00000000 / 0  
  r14 : 00000000 / 0  
  r15 : 00000000 / 0  
Bits in R0
Bit  0 (       1) : SET
Bit  1 (       2) : 0
Bit  2 (       4) : SET
Bit  3 (       8) : 0
Bit  4 (      10) : SET
Bit  5 (      20) : 0
Bit  6 (      40) : SET
Bit  7 (      80) : 0
Bit  8 (     100) : SET
Bit  9 (     200) : 0
Bit 10 (     400) : 0
Bit 11 (     800) : 0
Bit 12 (    1000) : 0
Bit 13 (    2000) : 0
Bit 14 (    4000) : 0
Bit 15 (    8000) : SET
```

I suspect that something about the state is causing an abort of the block compile because the `emu_stop` had been detected (or something hung off it), and then it clears that state, and re-executes, but because of the hook being present we see two block executions.

**Comment by gerph** [comment]
If I'm reading this right, I think this is caused by the sequence in the  `gen_intermediate_code_internal` (in `target-arm/translate.c`) which generates code in the order:

* `gen_uc_tracecode`
* `gen_tb_start`

The former performs the hook callback. The latter performs a check whether exit has been requested (`tcg_exit_req` is non-0) and branches to the exit label if so (having executed nothing).

This is (again, if I'm reading this right), used when an interrupt is triggered through `cpu_interrupt`, or `cpu_exit` has been called. `cpu_exit` had been called, but not during this block execution - in the prior one. So I think the `tcg_exit_req` has been left set.

Exits that pass through `cpu_loop_exit` (in `cpu-exec.c`) execute a `longjmp` which will bypass any cleanup that might have been performed for that `tcg_exit_req` variable. The `tcg_exit_req` is only ever cleared by the return from `cpu_tb_exec`, so I'm assuming that I'm requesting the `emu_stop` in the INTR hook the result includes a `cpu_loop_exit` (or similar) which bypasses the `cpu_tb_exec` function's cleanup and leaves that flag set.

**Comment by gerph** [comment]
Ok, with a small patch present which clears this flag at the end of the execution loop (`cpu_exec` in `cpu-exec.c` my test code only triggers the block hook once. This might not be the correct place to put the change, but I believe that even if it's too late to catch all cases, the flag should never be set at this point, so it should not have any bad effects.

```
diff --git a/qemu/cpu-exec.c b/qemu/cpu-exec.c
index 6297508..7353bee 100644
--- a/qemu/cpu-exec.c
+++ b/qemu/cpu-exec.c
@@ -291,6 +291,9 @@ int cpu_exec(struct uc_struct *uc, CPUArchState *env)   // qq
         }
     } /* for(;;) */
 
+    // Unicorn: Clear any TCG exit flag that might have been left set by exit requests
+    uc->current_cpu->tcg_exit_req = 0;
+
     cc->cpu_exec_exit(cpu);
 
     // Unicorn: flush JIT cache to because emulation might stop in
```

**Comment by gerph** [comment]
If you're looking to do a 1.0.2 release soon, this would improve efficiency, and prevent additional reports being made for blocks following a prior stop request.

**Comment by gerph** [comment]
Again, if you're looking to do a 1.0.2 release soon, this change has an impact on the tracing capabilities of unicorn. In order to reliably state what blocks were passed through, it is necessary to apply this patch, as otherwise there are regular occassions when the block callback will be called twice, once without any work being done and a second time when the block is actually executed.

**Comment by gerph** [comment]
What do I need to do to get the associated PR merged?

This has bitten me yet again, as I have to supply a modified version of the unicorn library in order for my code to report the correct path taken by the execution.

**Comment by aquynh** [comment]
Sorry, i will look at this soon
