### ISSUE TITLE
Triggering an IRQ

### ISSUE THREAD

**Issue by mid-kid** [unicorn-engine/unicorn#1197]
I'm trying to emulate something that expects something akin to SysTick, i.e. an IRQ that gets ran periodically.
As far as I gather, to trigger such an IRQ I'd need to change the processor mode, and somehow write the `lr` register in such a way that doesn't modify the `lr` of the currently running code, and allows the code to somehow return safely from the ISR.
Is there any way to trigger an IRQ in this fashion? Additionally, does unicorn keep track of processor time somewhere?

**Comment by SteinsGatep001** [comment]
Unicorn engine hasn't implement interface for IRQ. There are too few function interfaces in unicorn. I also want to configure Qemu's smm mode, but I couldn't find any interface.
Besides, unicorn uses Qemu's Timer to manage cpu state, you may get time information from uc->cpu(CPUState from qemu).

**Comment by mid-kid** [comment]
Why was this closed? Is it implemented? Rejected?

**Comment by wtdcode** [comment]
> Why was this closed? Is it implemented? Rejected?

As @SteinsGatep001 perfectly explained, you have to do it on your own.

**Comment by mid-kid** [comment]
He didn't really explain anything but say "unicorn currently has no interfaces to do this". Should I resubmit this as a feature request?

**Comment by wtdcode** [comment]
> They didn't really explain anything but say "unicorn currently has no interfaces to do this". Should I resubmit this as a feature request?

I guess you could just start emulation in a few seconds and stop and check whether it's time for any IRQ. That's how a CPU exactly works.

**Comment by mid-kid** [comment]
That's not the root of my issue. The issue is that there currently is no way to *execute* an IRQ. Executing an IRQ entails more than changing the program counter, as the CPU has different registers across different execution states...

**Comment by wtdcode** [comment]
> That's not the root of my issue. The issue is that there currently is no way to _execute_ an IRQ. Executing an IRQ entails more than changing the program counter, as the CPU has different registers across different execution states...

Yes. You could then hook for any exception or change registers as you like. You may illustrate a more exact scenario to help me know whether it's a missing feature of unicorn.

**Comment by mid-kid** [comment]
It's been too long for me to recall the exact scenario I was up against, all I can say is I can recall there being more to it than manually saving a couple of registers (ARM changes some of these up depending on the processor mode), and support from unicorn for accessing timing information from e.g. python or stopping/hooking emulation after a certain time interval would be very useful (rather than doing the incredibly slow thing of executing one instruction at a time).
I guess I'll bring it up again if I ever bump against this issue again...

**Comment by wtdcode** [comment]
> It's been too long for me to recall the exact scenario I was up against, all I can say is I can recall there being more to it than manually saving a couple of registers (ARM changes some of these up depending on the processor mode), and support from unicorn for accessing timing/cycle count information from e.g. python or stopping/hooking emulation after a certain time interval would be very useful (rather than doing the incredibly slow thing of executing one instruction at a time). I guess I'll bring it up again if I ever bump against this issue again...

We (here refer to Qiling team) indeed implement cortex-m exception handling based on Unicorn2 though it's a little complex than expected. And I think your situation should be similar.
