### ISSUE TITLE
[x86-64] CPUID feature flag missing

### ISSUE THREAD

**Issue by Sonicadvance1** [unicorn-engine/unicorn#1198]
Unicorn sets 8000_0001_EDX to saying it supports 3DNow and RDTSCP.
Some projects (LLVM specifically) will check against bit 29 of this CPUID register to determine if the CPU supports Long Mode.
This can be seen on the following line of code:

https://github.com/unicorn-engine/unicorn/blob/8b99637f774436e222e6d4393135aab0964967a0/qemu/target-i386/unicorn.c#L66

This bit should be added a few lines lower when operating in UC_MODE_64.

https://github.com/unicorn-engine/unicorn/blob/8b99637f774436e222e6d4393135aab0964967a0/qemu/target-i386/unicorn.c#L158

**Comment by aquynh** [comment]
Please send pull req
