### ISSUE TITLE
cross build unicorn use NDK, helper_* function error

### ISSUE THREAD

**Issue by SmailCatLog** [unicorn-engine/unicorn#1203]
https://github.com/unicorn-engine/unicorn/issues/1106#issue-473980982

https://github.com/unicorn-engine/unicorn/blob/63ebcf41a838bb9e259ba309f2025b1da819e323/qemu/tcg/tcg.c#L2378-L2381

```c++
#if TCG_TARGET_REG_BITS == 32 && !defined(__ARM_ARCH)
    // do this because msvc cannot have arrays with 0 entries. 
    nb_regs = 0; 
#endif

**Comment by hexcoder-** [comment]
s/define/defined/

**Comment by hexcoder-** [comment]
The fix tested ok with Raspberry Pi 4 (on 32-bit raspbian). Please commit! Thanks.

**Comment by aquynh** [comment]
Please pull req.
