### ISSUE TITLE
MIPS fails to branch

### ISSUE THREAD

**Issue by lafielk** [unicorn-engine/unicorn#1210]
[simple_test.zip](https://github.com/unicorn-engine/unicorn/files/4236620/simple_test.zip)

MISP 32 LE fails to branch correct with 'bne' instruction.
Unicron 1.0.1 for python, installed with pip
Correct output:
  address 0x100000L
  address 0x100004L
  address 0x100008L
  address 0x10000cL
  address 0x100000L
  address 0x100004L
  address 0x100008L
  address 0x10000cL
  address 0x100000L

Unicorn from github, build from source code with MSYS2 MinGW 32-bit
Incorrect output:
address 0x100000L
address 0x100004L
address 0x100008L
address 0x10000cL
UC_MIPS_REG_PC: 0x140000L

#---------------------- test.py -----------------------------------
from unicorn import *
from unicorn.mips_const import *

def hook_mem_invalid(uc_engine, access, address, size, value, user_data):
    # Always allocate ANY accessed memory
    if access == UC_MEM_WRITE_UNMAPPED:
        try:
            uc_engine.mem_map(address & 0xFFFFF000, 0x1000, UC_PROT_ALL)
        except:
            pass
        return True
    elif access == UC_MEM_READ_UNMAPPED:
        try:
            uc_engine.mem_map(address & 0xFFFFF000, 0x1000, UC_PROT_ALL)
        except:
            pass
        return True
    elif access == UC_MEM_FETCH_UNMAPPED:
        print 'UC_MIPS_REG_PC:', hex(uc_engine.reg_read(UC_MIPS_REG_PC))
    return False

def hook_code(uc_engine, address, size, user_data):
    print 'address', hex(address)

code  = ''
code += '08008424' # addiu   $a0, 8
code += 'F8FF85AC' # sw      $a1, -8($a0)
code += 'FDFF8714' # bne     $a0, $a3, loc_100000
code += 'FCFF85AC' # sw      $a1, -4($a0)

code_addr = 0x00100000

uc_engine = Uc(UC_ARCH_MIPS, UC_MODE_LITTLE_ENDIAN|UC_MODE_MIPS32)

uc_engine.mem_map(code_addr, 0x1000, UC_PROT_ALL)
uc_engine.mem_write(code_addr, code.decode('hex'))

uc_engine.hook_add(UC_HOOK_CODE, hook_code)
uc_engine.hook_add(UC_HOOK_MEM_READ_UNMAPPED,   hook_mem_invalid)
uc_engine.hook_add(UC_HOOK_MEM_WRITE_UNMAPPED,  hook_mem_invalid)
uc_engine.hook_add(UC_HOOK_MEM_FETCH_UNMAPPED,  hook_mem_invalid)

uc_engine.emu_start(code_addr, 0xFFFFFFFF, count=10000000)

**Comment by elp0t0r1c0** [comment]
Same issue here, with latest release (f0e47055c80944a358d81bcf6b06dbe08bb65dc7)
