### ISSUE TITLE
UC_ERR_FETCH_UNMAPPED despite hook (ARM)

### ISSUE THREAD

**Issue by FD-** [unicorn-engine/unicorn#1225]
I'm trying to catch SIGILL signals on ARMv6 and want to interpret the instructions causing the signal with a Unicorn ARM CPU. I'm hoping to run ARMv7 binaries on an ARMv6 Raspberry Pi Zero in this way.

Unicorn seems perfectly suited for this task, but I cannot get it to work: Although I set a hook on UC_HOOK_MEM_READ_UNMAPPED | UC_HOOK_MEM_WRITE_UNMAPPED | UC_HOOK_MEM_FETCH_UNMAPPED, uc_emu_start always fails with error 8: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED), without ever calling the hook callback.

I already tried different ways of mapping my process's memory into the virtual CPU's memory, using uc_mem_map_ptr with address 4096 and size (0xffffffff - 4096 + 1) or by using uc_mem_map on just the page that contains the current instruction and loading other pages on demand (in the unmapped hook), but none of them lead to any difference.

What could be causing this problem?

Here is my full code:

```
#include <stdlib.h>
#include <signal.h>
#include <stdio.h>
#include <stdint.h>
#include <sys/ucontext.h>

#include <unicorn/unicorn.h>

#define CPSR_MASK_THUMB (1 << 5)

// On guest memory fault, map the corresponding page from host memory into the guest.
static bool hook_segfault(uc_engine *uc, uc_mem_type type, uint64_t addr, int size, int64_t value, void *user) {
    // assume null pointer deref
    if (addr < 0x4000) {
        printf("invalid access: 0x%zx\n", addr);
        return false;
    }
    printf("Segfault handler\n");
    size = (size + 0xfff) & ~0xfff;
    addr &= ~0xfff;
    uc_check(uc_mem_map_ptr(uc, addr, size, UC_PROT_ALL, (void *)addr));
    return true;
}

void sighandler(int signo, siginfo_t *si, void *data) {
    ucontext_t *ucontext = (ucontext_t *)data;
    mcontext_t *mcontext = &ucontext->uc_mcontext;

    uint32_t *instruction_ptr = (uint32_t*)mcontext->arm_pc;
    uint32_t state = (uint32_t)mcontext->arm_cpsr;
    int thumb_mode = (state & CPSR_MASK_THUMB) != 0;

    printf("Caught invalid instruction at address %p!\n", instruction_ptr);
    printf("Caught invalid instruction: %08x\n", *instruction_ptr);
    printf("Thumb Mode is: %d\n", thumb_mode);

    uc_engine *uc;
    uc_err err = uc_open(UC_ARCH_ARM, UC_MODE_ARM, &uc);
    if (err != UC_ERR_OK) {
        printf("Failed on uc_open() with error returned: %u\n", err);
        exit(1);
    }

    uc_hook hook1;
    err = uc_hook_add(uc, &hook1, UC_HOOK_MEM_READ_UNMAPPED | UC_HOOK_MEM_WRITE_UNMAPPED | UC_HOOK_MEM_FETCH_UNMAPPED, 
        hook_segfault, NULL, 1, 0);
    if (err != UC_ERR_OK) {
        printf("Failed on uc_hook_add1() with error returned: %u\n", err);
        exit(1);
    }

    // Map current instruction's page into virtual CPU memory
    void *page_start = mcontext->arm_pc & ~0xfff;
    uc_mem_map(uc, page_start, 4096, UC_PROT_ALL);
    if (err != UC_ERR_OK) {
        printf("Failed on uc_mem_map_ptr() with error returned: %u: %s\n", err, uc_strerror(err));
        exit(1);
    }

    // Copy current instruction's page to virtual CPU memory
    uc_mem_write(uc, page_start, page_start, 4096);

    // Set registers
    uc_reg_write(uc, UC_ARM_REG_R0, &mcontext->arm_r0);
    uc_reg_write(uc, UC_ARM_REG_R1, &mcontext->arm_r1);
    uc_reg_write(uc, UC_ARM_REG_R2, &mcontext->arm_r2);
    uc_reg_write(uc, UC_ARM_REG_R3, &mcontext->arm_r3);
    uc_reg_write(uc, UC_ARM_REG_R4, &mcontext->arm_r4);
    uc_reg_write(uc, UC_ARM_REG_R5, &mcontext->arm_r5);
    uc_reg_write(uc, UC_ARM_REG_R6, &mcontext->arm_r6);
    uc_reg_write(uc, UC_ARM_REG_R7, &mcontext->arm_r7);
    uc_reg_write(uc, UC_ARM_REG_R8, &mcontext->arm_r8);
    uc_reg_write(uc, UC_ARM_REG_R9, &mcontext->arm_r9);
    uc_reg_write(uc, UC_ARM_REG_R10, &mcontext->arm_r10);
    uc_reg_write(uc, UC_ARM_REG_FP, &mcontext->arm_fp);
    uc_reg_write(uc, UC_ARM_REG_IP, &mcontext->arm_ip);
    uc_reg_write(uc, UC_ARM_REG_SP, &mcontext->arm_sp);
    uc_reg_write(uc, UC_ARM_REG_LR, &mcontext->arm_lr);
    uc_reg_write(uc, UC_ARM_REG_PC, &mcontext->arm_pc);
    uc_reg_write(uc, UC_ARM_REG_CPSR, &mcontext->arm_cpsr);

    // Execute 1 instruction
    err = uc_emu_start(uc, (uint64_t) mcontext->arm_pc, (uint64_t) mcontext->arm_pc + 4096, (uint64_t) 0, 1);
    if (err) {
        printf("Failed on uc_emu_start() with error returned %u: %s\n",
         err, uc_strerror(err));
    }

    // TODO: Copy back emulation context to real context

    printf("Emulation done.\n");
    exit(1);
}

__attribute__((constructor)) void init(void) {
    struct sigaction sa, osa;
    sa.sa_flags = SA_ONSTACK | SA_RESTART | SA_SIGINFO;
    sa.sa_sigaction = sighandler;
    sigaction(SIGILL, &sa, &osa);
    printf("Loaded");
}

```

I'm compiling this into a shared library and injecting it into an ARMv7 binary with LD_PRELOAD. So, assuming you're on an ARMv6 machine and the 'cat' binary is compiled for ARMv7, you'd run:

    LD_PRELOAD=/home/pi/armv7for6/libarmv7for6.so ./cat 

The program output is:

```
LoadedCaught invalid instruction at address 0xdfb4!
Caught invalid instruction: e7eb3053
Thumb Mode is: 0
Failed on uc_emu_start() with error returned 8: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)
Emulation done.
```
The segfault handler is never called, I tested this by adding a printf call there.

**Comment by gerph** [comment]
```
    err = uc_hook_add(uc, &hook1, UC_HOOK_MEM_READ_UNMAPPED | UC_HOOK_MEM_WRITE_UNMAPPED | UC_HOOK_MEM_FETCH_UNMAPPED, 
        hook_segfault, NULL, 1, 0);
```

The final two parameters you have supplied are a start address of 1 and an end address of 0. There will never be an execution with pc>1 and pc<0. I suspect you need to supply 0 and the largest address you want to trap within for these parameters.

**Comment by FD-** [comment]
Thanks for your response! Going by the documentation in unicorn.h, begin > end would make it call the callback no matter the memory address:

    NOTE 2: if @begin > @end, callback is called whenever this hook type is triggered

Also, I just tried with begin at 0 and end at 0xffffffff and it still didn't work.

**Comment by gerph** [comment]
Ah, I see... I didn't know that, but I see in the implementation that it's checked like that too:

https://github.com/unicorn-engine/unicorn/blob/master/include/uc_priv.h#L129

So, thanks, I've learnt something.

One small thing; you should write the CSPR first, then the registers - otherwise you'll write the registers for the current mode, then switch to the target mode, and have lost the registers you expected. This only applies if you're expecting to ever be called with the CPSR in non-USR mode, but it's better practice to do that way.

Unlikely to be an issue, but I thought uc_reg_write expected to be given the value to write, not a pointer to the value - those `&mcontext->arm_xx` I would have expected to not use the `&`.

I cannot see where it's going wrong I'm afraid; it looks sane to me.

**Comment by NieDzejkob** [comment]
Could you try on latest master? (see #1246)

**Comment by wtdcode** [comment]
Link to #1449

**Comment by wtdcode** [comment]
Closed due to inactivity and unable to reproduce.
