### ISSUE TITLE
Newbie with ARM 

### ISSUE THREAD

**Issue by patoch01220** [unicorn-engine/unicorn#1226]
Hello, I need to code in assembler for my studies, and i am on macOS.
I installed and followed all the instruction that you gave in the file for compilation and installation. 
But i have a question now : i have a file .s that should just print hello world that our teacher gaves us. 
But how do i compile it with unicorn and how do i run it then ??

Sorry, this is for sure a dumb question, but i am pretty new in this domain and i did not find the commands to do that.

Thanks for your time !

**Comment by SteinsGatep001** [comment]
just check code in [samples](https://github.com/unicorn-engine/unicorn/tree/master/samples) or read [docs](http://www.unicorn-engine.org/docs/tutorial.html)
