### ISSUE TITLE
How to call interrupt in unicorn(interrupt function in qemu)

### ISSUE THREAD

**Issue by SteinsGatep001** [unicorn-engine/unicorn#1227]
I want to call interrupts like [x86_cpu_exec_interrupt](https://github.com/unicorn-engine/unicorn/blob/master/qemu/target-i386/seg_helper.c#L1288).But I found that any interrupt function in qemu source code wouldn't be called.

**Comment by wtdcode** [comment]
Unicorn is a cpu emulator, you have to do it by your own,
