### ISSUE TITLE
sample_arm  can't run on android os

### ISSUE THREAD

**Issue by Lucaks** [unicorn-engine/unicorn#1236]
"Failed on uc_emu_start () with error returned: 8 (Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)"when running sample_arm on nexus5&6.0.1.
What's the reason？

**Comment by kr1tzy** [comment]
Add the logs or stack trace please.

**Comment by NieDzejkob** [comment]
Could you try on latest master? (see #1246)
