### ISSUE TITLE
 ERROR: pthread check failed

### ISSUE THREAD

**Issue by liumengdeqq** [unicorn-engine/unicorn#1248]
NDK=~/android-ndk-r20b ./make.sh cross-android_arm
cd qemu && \
	./configure --cc="arm-linux-androideabi-gcc" --extra-cflags="-DUNICORN_HAS_X86 -DUNICORN_HAS_ARM -DUNICORN_HAS_ARMEB -DUNICORN_HAS_M68K -DUNICORN_HAS_ARM64 -DUNICORN_HAS_ARM64EB -DUNICORN_HAS_MIPS -DUNICORN_HAS_MIPSEL -DUNICORN_HAS_MIPS64 -DUNICORN_HAS_MIPS64EL -DUNICORN_HAS_SPARC -fPIC -fvisibility=hidden" --target-list="x86_64-softmmu, arm-softmmu, armeb-softmmu, m68k-softmmu, aarch64-softmmu, aarch64eb-softmmu, mips-softmmu, mipsel-softmmu, mips64-softmmu, mips64el-softmmu, sparc-softmmu,sparc64-softmmu," 

ERROR: pthread check failed
       Make sure to have the pthread libs and headers installed.

make: *** [qemu/config-host.mak] Error 1

**Comment by aquynh** [comment]
If you can fix this, please make pull req.

**Comment by wtdcode** [comment]
Link to #1407 #1449
