### ISSUE TITLE
uc_hook_add() error with UC_HOOK_INSN

### ISSUE THREAD

**Issue by qfrtt** [unicorn-engine/unicorn#1251]
Hello, I can't seem to get the UC_HOOK_INSN working for whatever instruction I try with
here's code

`uc_hook_add(uc, &hook3, UC_HOOK_INSN, hook_inst, nullptr, 1, 0, UC_X86_INS_MOV);`
and error code
`Failed on uc_hook_add() with error returned 9: Invalid hook type (UC_ERR_HOOK)`

**Comment by aquynh** [comment]
the reason is that UC_HOOK_INSN supports very few instructions, and MOV is
not one of them.

you may consider hooking everything, then filter what you want in your
callback.

**Comment by qfrtt** [comment]
Oh alright I didn't know that I am also having an other issue looks like its only reading the 16 low of the instructions / addresses
![image](https://user-images.githubusercontent.com/9437677/81374112-7b06e900-90cc-11ea-8037-2e4f1a6ee796.png)
![image](https://user-images.githubusercontent.com/9437677/81374117-7f330680-90cc-11ea-86b6-caa88552c27d.png)

`uc_open(UC_ARCH_X86, UC_MODE_32, &uc);`

`static void hook_code(uc_engine* uc, uint64_t address, uint32_t size, void* user_data)
{
	DWORD eax, ebx, ecx, edx, esi, edi, esp, ebp, eip;
	uc_reg_read(uc, UC_X86_REG_EAX, &eax);
	uc_reg_read(uc, UC_X86_REG_EBX, &ebx);
	uc_reg_read(uc, UC_X86_REG_ECX, &ecx);
	uc_reg_read(uc, UC_X86_REG_EDX, &edx);
	uc_reg_read(uc, UC_X86_REG_ESI, &esi);
	uc_reg_read(uc, UC_X86_REG_EDI, &edi);
	uc_reg_read(uc, UC_X86_REG_ESP, &esp);
	uc_reg_read(uc, UC_X86_REG_EBP, &ebp);
	uc_reg_read(uc, UC_X86_REG_EIP, &eip);

	uint8_t opcode;
	uc_mem_read(uc, address, &opcode, sizeof(opcode));
	
	ERR_PRINT("------------------------------------------------");
	ERR_PRINT(">>> Tracing instruction at 0x%llx AND eip = 0x%x AND opcode = 0x%x AND size = 0x%x", address, eip, opcode, size);
	ERR_PRINT("eax : 0x%X\n", eax);
	ERR_PRINT("ebx : 0x%X\n", ebx);
	ERR_PRINT("ecx : 0x%X\n", ecx);
	ERR_PRINT("edx : 0x%X\n", edx);
	ERR_PRINT("esi : 0x%X\n", esi);
	ERR_PRINT("edi : 0x%X\n", edi);
	ERR_PRINT("esp : 0x%X\n", esp);
	ERR_PRINT("ebp : 0x%X\n", ebp);
	ERR_PRINT("eip : 0x%X\n", eip);
	ERR_PRINT("------------------------------------------------");
}
`
