### ISSUE TITLE
X86: Setting Hidden Flags?

### ISSUE THREAD

**Issue by Fighter19** [unicorn-engine/unicorn#1273]
I'm trying to trace a snapshot (I created with QEMU) of a DOS application.

For this I've generated a core-dump and loaded it
using unicorn.

I've manually set all registers including segmentation register and tables.

I'm currently unable to load the stack segment selector, as: ```rpl != cpl
(rpl = 3; cpl = 0) (seg_helper.c:1592)```
Therefor:
```uc_reg_write(uc, UC_X86_REG_SS, &r_ss);``` fails.

As the current state of the machine should already be cpl = 3,
I wanted to ask, if there are any chances to expose setting of the hflags
manually, or if this is generally a bad idea.

Currently I have no clue how I'm supposed to set the current privilege level.

**Comment by wtdcode** [comment]
Could you have a check again on our new version Unicorn2?

**Comment by Fighter19** [comment]
The new version is on the master branch, I suppose?

**Comment by wtdcode** [comment]
Closed due to inactivity.
