### ISSUE TITLE
ARM MPU register support

### ISSUE THREAD

**Issue by pabx06** [unicorn-engine/unicorn#1290]
Hello. 
I am trying to emulate some bootloader. i mapped unicron memory. then run. The code is trying to set MPU's Write Memory Region Number Register.
unicorn doesn't seem to support that register.
 may be some configuration needed ?

so i setup an instruction code hook to increment PC register to the next instruction. it works

i used unicorn with capstone to decode asm.
```
Tracing instruction at 0x401e933c, instruction size = 0x4, PC=401e933c,R0=32,R1=401e9cc7,R2=0,R3=0,R4=0,R5=0,R6=33,R7=e59ff018,R8=0,R9=0,R10=e5,R11=e59ff018,R12=0,SP=c0007fcc,LR=401e932c,SB=0,SL=e5,FP=e59ff018,IP=0,CPSR=200001d3,TMode=0
MyCodeHook.hook - CP15/P15 mcr [WRITE] ADDRESS= 0x401e933c
decodeAsm - 0x401e933c:	mcr p15, #0, r4, c6, c2, #0 //set MPU's Write Memory Region Number Register
Emulation error:
unicorn.UnicornException: Invalid instruction (UC_ERR_INSN_INVALID)

```
Also  i suppose that i need to hook MPU register(s) read to put correct value back into the programm flow ?
thus increasing the amount of boiler plate need to run a simple boot-loader program. it would be nice to have MPU support built-in or being able to setup qemu stuff ?

Big Thanks to the unicorn team very good stuff here...

**Comment by wtdcode** [comment]
Duplicate #889

**Comment by wtdcode** [comment]
Closed due to features implemented.
