### ISSUE TITLE
Code in sample_arm64.py doesn't do what comment says.

### ISSUE THREAD

**Issue by stefanesser** [unicorn-engine/unicorn#1292]
Hi,

bindings/python/sample_arm64.py has the following code:

```
        # tracing all instructions with customized callback
        mu.hook_add(UC_HOOK_CODE, hook_code, begin=ADDRESS, end=ADDRESS)
```

The comment is not describing what the code does. The comment says ALL instructions are traced with this hook. However the hook registration only registers the hook for the first instruction at ADDRESS. So either comment or code should be fixed.

**Comment by aquynh** [comment]
fixed the comment, thanks.
