### ISSUE TITLE
Please bring back iOS support

### ISSUE THREAD

**Issue by jorgschulze73** [unicorn-engine/unicorn#1294]
As per title, I would love to be able to use Unicorn on iOS, but that doesn't seem to be supported anymore.

Please bring it back.

Thank you

**Comment by aquynh** [comment]
can you provide more details on your issue?

**Comment by jorgschulze73** [comment]
Sure, my issue is that currently there's no way to cross-compile Unicorn for iOS.

There used to be (or at least it seems so), but back in August that was removed from make files and never brought back.

I'm interested in running Unicorn on an iOS device but at the moment I can't do it due to these reasons.

**Comment by aquynh** [comment]
Please explain how you build, and what is wrong with it.

**Comment by jorgschulze73** [comment]
I'm building as reported in the following document:
https://github.com/unicorn-engine/unicorn/blob/master/docs/COMPILE-NIX.md

As you can see, such document claims you can simply invoke `./make.sh ios_arm64`, unfortunately by having a look at the source code of the `make.sh` file, you can see how there's no such definition.

That's because it's been removed in the following commit:
https://github.com/unicorn-engine/unicorn/commit/ca6cb2368fb8b669d083af5e893a2e294b65a246

You can also find a similar report from December here:
https://github.com/unicorn-engine/unicorn/issues/1177

**Comment by aquynh** [comment]
can you make a pull req to bring that back (and test it at the same time)?

**Comment by jorgschulze73** [comment]
If I opened a ticket it's because I'm not able to do it myself, otherwise I'd have just opened a pull request instead

**Comment by Artoria2e5** [comment]
I have a spare armv7-era iPad lying about. Let me try getting it to accept a non-ridiculous time setting so I can actually use it to run anything at all. And then it's hopefully just building and running tests.

By the way, Jonathan Afek have succeeded in [getting QEMU to run iOS](https://alephsecurity.com/2019/06/17/xnu-qemu-arm64-1/), so theoretically someone *could* throw together a Docker thing on the CI.

**Comment by wtdcode** [comment]
Link to #1217

**Comment by wtdcode** [comment]
https://github.com/utmapp/UTM/issues/2271

Looks like without jailbreak, we couldn't have `MAP_JIT` on iOS.
