### ISSUE TITLE
Disable MMU emulation

### ISSUE THREAD

**Issue by andreafioraldi** [unicorn-engine/unicorn#1301]
Is there any way to configure unicorn to not use MMU emulation, but, like qemu-user, the host virtual memory?

I qemu-user, h2g is simply `h2g(x) (x + guest_base)` and give a huge speedup to the emulator.

Now in Unicorn, to emulate arbitrary code the MMU is needed but would be nice to have an option to disable it and use the host mappings.

**Comment by aquynh** [comment]
No. Pull req is welcome :-)

**Comment by amimo** [comment]
something like this ? [UnicornVM](http://www.yunyoo.cn/product/UnicornVM) Virtual Machine based on unicorn for iOS/Android without Qemu MMU.

**Comment by amimo** [comment]
looks like it is a commercial product, no source code has been released yet.

**Comment by andreafioraldi** [comment]
Should be https://gitee.com/geekneo/VirtualCode

**Comment by andreafioraldi** [comment]
Mmmm I see only headers and precompiled shared libs. If they really patch unicorn, this is a violation of the QEMU GPL2

**Comment by amimo** [comment]
may be this one ? [https://gitee.com/geekneo/unicorn](https://gitee.com/geekneo/unicorn)

**Comment by marcospampi** [comment]
> Is there any way to configure unicorn to not use MMU emulation, but, like qemu-user, the host virtual memory?
> 
> I qemu-user, h2g is simply `h2g(x) (x + guest_base)` and give a huge speedup to the emulator.
> 
> Now in Unicorn, to emulate arbitrary code the MMU is needed but would be nice to have an option to disable it and use the host mappings.

Hi, there's an alternative to unicorn, at least for what concerns ARM and aarch64, Dynarmic, it is fairly customizable in memory management.
