### ISSUE TITLE
Unicorn (qemu part) will crash when run on Mac with SIP(System Integrity Protection) is on

### ISSUE THREAD

**Issue by Soulghost** [unicorn-engine/unicorn#1308]
# Replay
1. turn SIP on from the Recovery OS.
2. run the qemu tutorial demo https://www.unicorn-engine.org/docs/tutorial.html on macOS.

# Backtrace
```c++
// qemu/cpu-exec.c
/* Execute a TB, and fix up the CPU state afterwards if necessary */
static tcg_target_ulong cpu_tb_exec(CPUState *cpu, uint8_t *tb_ptr)
{
    CPUArchState *env = cpu->env_ptr;
    TCGContext *tcg_ctx = env->uc->tcg_ctx;
    uintptr_t next_tb;

    // ----------> crashed <----------
    next_tb = tcg_qemu_tb_exec(env, tb_ptr);
    // ...
}
```
The crash is caused by page protection in SIP, the dynamic generated executable page's prot is set in map_exec:
```c++
static inline QEMU_UNUSED_FUNC void map_exec(void *addr, long size)
{
    unsigned long start, end, page_size;

    page_size = getpagesize();
    start = (unsigned long)addr;
    start &= ~(page_size - 1);

    end = (unsigned long)addr + size;
    end += page_size - 1;
    end &= ~(page_size - 1);

    mprotect((void *)start, end - start,
             PROT_READ | PROT_WRITE | PROT_EXEC);
}
```

however, the page protection cannot be both writable and executable, so the page prot changes to rw- when SIP is on, so it crashed when call to tcg_qemu_tb_exec:
![image](https://user-images.githubusercontent.com/6300263/88363495-d33bb600-cdb2-11ea-80b1-9a63cfc4210c.png)

# Next
So is it a bug in qemu or it's part of unicorn, can we swap between rw- and r-x for the generated code, the simple try to change map_exec prot to r-x will not work and caused other crashes.

**Comment by aquynh** [comment]
can you test your idea and confirm it works on Mac?

**Comment by Soulghost** [comment]
> can you test your idea and confirm it works on Mac?

Okay, let me try if it works, I’m not very familiar with this part, it may take some time.

**Comment by aquynh** [comment]
you may look at qemu 5 to see how this part is implemented. (suppose that qemu 5 works without issue on modern Mac versions)

**Comment by Soulghost** [comment]
I found the problem. This is not a unicorn or qemu problem, the host binary has opened the Hardened Runtime by mistake. When SIP is on, this capability will reject qemu's dynamic executable page. So the solution is to turn off this mechanism, but this is not the best solution, I will try to make it works under the Hardened Runtime.

**Comment by wtdcode** [comment]
This has been fixed in uc2.
