### ISSUE TITLE
Incorrect value for instruction pointer reported when reading/writing XMM values from/to memory

### ISSUE THREAD

**Issue by dnivra** [unicorn-engine/unicorn#1312]
The value of RIP register is incorrectly report as start of the block when reading a value from memory into an XMM register or writing an XMM register to memory. Interestingly, if the particular instruction doing this is hooked using an instruction level hook, the correct value is reported. I've attached a sample C code that reproduces this. Uncomment line 60 in the C source file to see how the instruction level hook fixes the issue.

[unicorn-bug-xmm-read-write-repro.zip](https://github.com/unicorn-engine/unicorn/files/5011488/unicorn-bug-xmm-read-write-repro.zip)

**Comment by wtdcode** [comment]
Probably fixed in Unicorn2 and note that PC is not updated if you don't install some kind of hook.

**Comment by wtdcode** [comment]
> > Yes, that's right. Memory hooks won't update PC.
> 
> Ah I see. Is that a specific design choice or a bug? If a conscious design choice, then this issue can be closed. In previous comment, you said that PC is not updated unless some hook is installed and so I thought memory access hooks should be sufficient.

Sorry for my late reply since there are too many things. I checked the code and indeed, only `UC_HOOK_CODE` guarantees to update PC. The reason is to avoid performance overhead.

https://github.com/unicorn-engine/unicorn/wiki/FAQ#why-do-i-get-a-wrong-pc-after-emulation-stops

**Comment by dnivra** [comment]
Thank you very much for clarifying this!

**Comment by liangjs** [comment]
Is this still an issue? I encountered the same problem on unicorn 2.

> Sorry for my late reply since there are too many things. I checked the code and indeed, only `UC_HOOK_CODE` guarantees to update PC. The reason is to avoid performance overhead.
> 
> https://github.com/unicorn-engine/unicorn/wiki/FAQ#why-do-i-get-a-wrong-pc-after-emulation-stops

The document says the PC is sync-ed before any read/write events if memory hook is installed. But the PC is still not updated for xmm memory read/write.

**Comment by wtdcode** [comment]
> Is this still an issue? I encountered the same problem on unicorn 2.
> 
> > Sorry for my late reply since there are too many things. I checked the code and indeed, only `UC_HOOK_CODE` guarantees to update PC. The reason is to avoid performance overhead.
> > https://github.com/unicorn-engine/unicorn/wiki/FAQ#why-do-i-get-a-wrong-pc-after-emulation-stops
> 
> The document says the PC is sync-ed before any read/write events if memory hook is installed. But the PC is still not updated for xmm memory read/write.

Oh you are probably correct as iirc we didn't hook xmm read/write. Could you open a separate issue?
