### ISSUE TITLE
emu_start stuck with high cpu usage no instruction execution...

### ISSUE THREAD

**Issue by pabx06** [unicorn-engine/unicorn#1318]
hello. 

i am using java binding. on linux, oracle jdk 13
**version**
```
git log -1
commit 08240d54536a9fbb6e0580d35a5db2d8f70ad451 (HEAD -> master)
Author: Chen Huitao <h980501427@163.com>
Date:   Sat May 16 10:38:16 2020 +0800

    fix some oss-fuzz (#1258)
    
    * fix oss-fuzz 22107.
    
    * fix oss-fuzz 22112.
    
    * clean up build target.
    
    * fix oss-fuzz 22226.
    
    * fix oss-fuzz 22227.
    
    * fix oss-fuzz 11640.
    
    * fix oss-fuzz 20772.
```
i have hooks:
- basic block
- instruction hook
- mem hook Read & Write
- unmaped Event MemHook
- All of those hooks do print somethings even in case of unexpected params value...
 

After executing mixed ARM mod & thumb code mixed for 10-15 minutes without problems nor error. cpu usage do spikes a bit and no more instruction/event from hooks are being logged from hook

### Output
![image](https://user-images.githubusercontent.com/4013370/90981093-72450080-e55f-11ea-9c82-8c7e780e10b6.png)

### Debuging

![image](https://user-images.githubusercontent.com/4013370/90981310-83424180-e560-11ea-9edf-3ce6452da099.png)
![image](https://user-images.githubusercontent.com/4013370/90981360-d1efdb80-e560-11ea-960d-f6af809cfa5f.png)

debugging java code pinpoint down the code is stuck in emu_start native methods ... 

### Question

Any idea on to attach a gdb to unicorn JNI native lib and or unicorn lib & how to locate the process id of the native part ? without having to rewrite my whole app in pure c ?

**Comment by wtdcode** [comment]
Could you provide a reproduction script?

**Comment by wtdcode** [comment]
Closed due to inactivity.
