### ISSUE TITLE
Arm v8.3 Pointer Authentication and Arm v8.5 MemTag

### ISSUE THREAD

**Issue by pwn0rz** [unicorn-engine/unicorn#1324]
Hi guys, it seems that the upstream QEMU already have PAC and MemTag support. Modern Mach-O binaries on iOS and upcoming Apple Silicon will be shipped with this feature by default, also does the Android platform. Will you consider adding this feature to the future iteration plan?

**Comment by aquynh** [comment]
yes, we plan to do that with Unicorn 2: https://github.com/unicorn-engine/unicorn/issues/1217

**Comment by blacktop** [comment]
Has this been added now?

**Comment by wtdcode** [comment]
> Has this been added now?

I suppose it has been added. If not, please open another standalone issue and I would fix it.
