### ISSUE TITLE
Merge 'next' branch into master

### ISSUE THREAD

**Issue by TobiasScharnowski** [unicorn-engine/unicorn#1329]
There seems to be a bit of a deviation between the two branches 'next' and 'master'. Among others, the binding support differs between the two branches.

Is there a distinct reason for keeping the branches separate? Otherwise, merging the two would be nice to unify the functionality.

**Comment by aquynh** [comment]
We plan to merge after 1.0.2 release

**Comment by google-mirror** [comment]
> We plan to merge after 1.0.2 release

Did those bugs reported by Google AutoFuzz get fixed?

**Comment by domenukk** [comment]
Any updates on this? Thanks :)

**Comment by aquynh** [comment]
I synced next with master just now.

**Comment by domenukk** [comment]
So what's the deal here: will `next` ever end up in `main`?

**Comment by wtdcode** [comment]
The next branch is depreciated as of current development. Stay tuned for Unicorn2!
Link to #1217

________________________________

**Comment by wtdcode** [comment]
Closed due to uc2 beta release.
