### ISSUE TITLE
Why not support cr8？

### ISSUE THREAD

**Issue by SuperSystemToken** [unicorn-engine/unicorn#1330]
The cr8 reg controls the current irql privilege level. When I read and write synchronously, I need to check the current irql in uc. If I need to raise the irql, I can read and write data safely.How can I modify the code to support it?

**Comment by aquynh** [comment]
Please pull req

**Comment by wtdcode** [comment]
Could you be more specific?

**Comment by wtdcode** [comment]
Duplicate #889
