### ISSUE TITLE
Does Unicorn support the emulation of speculative execution?

### ISSUE THREAD

**Issue by Alexandercofa** [unicorn-engine/unicorn#1342]
I'm considering using Unicorn in my final year project, but I'd like to know if it supports speculative execution.
Thanks. :)

**Comment by aquynh** [comment]
can you elaborate on your question?

**Comment by egberts** [comment]
speculative at instruction-level or at CPU microarchitecture-level?

Branch predicture is at instruction scope (bit indicator available at Unicorn API/register set) but microarchitectual-level aspect is operated all within QEMU engine (but one can add additional hooks within then rebuild Unicorn/QEMU)
