### ISSUE TITLE
[1.0.2] Linking error when building with cmake

### ISSUE THREAD

**Issue by lgbaldoni** [unicorn-engine/unicorn#1346]
On openSUSE Tumbleweed, x86_64, see [log snippet](https://github.com/unicorn-engine/unicorn/files/5417264/unicorn102_error.txt).

**Comment by aquynh** [comment]
can you open a new issue on Github?

btw, how did you build?

the standard steps are:

$ mkdir build; cd build
$ ../cmake.sh

Thanks,
Quynh

**Comment by aquynh** [comment]
sorry, this was already on github ;-)

**Comment by lgbaldoni** [comment]
Oh, I didn't use that script, I used a macro to build the package for the distribution.
Log [here](https://github.com/unicorn-engine/unicorn/files/5418207/unicorn102_error_cmake.txt), I assume it's a question of flags, I've been seeing problems with regular Makefiles too.
