### ISSUE TITLE
Kernel module emulation

### ISSUE THREAD

**Issue by ang1337** [unicorn-engine/unicorn#1358]
Hello everyone

Is it possible to properly emulate Linux kernel modules using Unicorn? Theoretically, it can be used for kernel code fuzzing without leveraging complex things like hypervisors having a fine-grained instrumentation. Kernel modules are basically object files (aka relocatable) without program headers, so do I need to artificially link it with a Linux kernel binary and load it into the emulator as well? What about interrupts, privileged instructions? 

Of course, this is extremely hard to emulate a full OS, but for security research purposes it can be interesting to emulate arbitrary code chunks in kernel code, which seems to be more than feasible.

**Comment by google-mirror** [comment]
unicorn is just a cpu, you have to impl everything yourself
