### ISSUE TITLE
x86_64 emulation with AVX?

### ISSUE THREAD

**Issue by jayavanth** [unicorn-engine/unicorn#1359]
Just found this project. Wanted to know if Unicorn can emulate x86_64 with AVX enabled, without KVM?

**Comment by gabrieljcs** [comment]
Yes, take a look here: https://github.com/unicorn-engine/unicorn/blob/master/include/unicorn/x86.h#L819

**Comment by wtdcode** [comment]
> uh, I don't think it really can? even if i set cpu model to something relatively recent, like
> 
> ```python
> uc.ctl_set_cpu_model(UC_CPU_X86_EPYC_ROME)
> ```
> 
> the result of `cpuid(eax=1, ecx=0)` gives ecx=`0x2182200`. This indicates AVX (bit 28) and XSAVE (bit 26) are both not available. Both of those bits should be 1.
> 
> I also note that I cannot set OSXSAVE (cr4 bit 18) via emulated code. However the bit does get set through the `reg_write` API.
> 
> i.e. executing this in unicorn:
> 
> ```
> mov rax, cr4
> or rax, 1 << 18
> mov cr4, rax
> mov eax, 1
> mov ecx, 0
> cpuid
> ```
> 
> still results in output ecx of 0x2182200. meaning AVX=0, XSAVE=0, OSXSAVE=0
> 
> I am just doing something wrong?

From the cpu.c of i386, it should support AVX. Could you open a separate issue? A separate reproduction is highly appreciated.
