### ISSUE TITLE
Feature request: Nim binding for unicorn-engine

### ISSUE THREAD

**Issue by dmknght** [unicorn-engine/unicorn#1362]
Nim programming is a compiled systems programming language that has very easy syntax (Python like). It has very fast performance so i think it would be nice if unicorn engine supports Nim lang binding.
Homepage: https://nim-lang.org/

**Comment by wtdcode** [comment]
Link to #1217. Hopefully, someone would contribute.

**Comment by dmknght** [comment]
I used the Nimterop (kinda C to Nim generator) to create the binding from `libunicorn-dev` version 2.0.1.
https://github.com/dmknght/unimcorn
