### ISSUE TITLE
PC register isn't updated correctly

### ISSUE THREAD

**Issue by giltom** [unicorn-engine/unicorn#1374]
The PC register isn't updated properly after `emu_start` returns:
* If the `count` argument isn't provided, PC isn't updated at all and remains at its initial value even though the code runs.
* If `count` is given but emulation stops before it is reached, PC is off by one instruction.
* PC is correct only if `count` is reached.

Script to reproduce:
```python
from keystone import *
from unicorn import *
from unicorn.arm_const import *

ks = Ks(KS_ARCH_ARM, KS_MODE_ARM | KS_MODE_LITTLE_ENDIAN)
code, _ = ks.asm('ADD R1, #11; ADD R2, #22', as_bytes=True)

uc = Uc(UC_ARCH_ARM, UC_MODE_ARM | UC_MODE_LITTLE_ENDIAN)
uc.mem_map(0, 0x1000)
address = 40
uc.mem_write(address, code)
ctx = uc.context_save()

uc.context_restore(ctx)
uc.emu_start(address, address+len(code))
print(uc.reg_read(UC_ARM_REG_PC), uc.reg_read(UC_ARM_REG_R1), uc.reg_read(UC_ARM_REG_R2)) #prints 40 11 22

uc.context_restore(ctx)
uc.emu_start(address, address+len(code), count=5000)
print(uc.reg_read(UC_ARM_REG_PC), uc.reg_read(UC_ARM_REG_R1), uc.reg_read(UC_ARM_REG_R2)) #prints 44 11 22

uc.context_restore(ctx)
uc.emu_start(address, address+len(code)+50, count=2)
print(uc.reg_read(UC_ARM_REG_PC), uc.reg_read(UC_ARM_REG_R1), uc.reg_read(UC_ARM_REG_R2)) #prints 48 11 22
```

This also affects memory read/write hooks, e.g. reading the PC from inside a data hook will return the starting PC instead of the current PC value. Executing a code hook seems to update the PC to the correct value.

I am using Unicorn 1.0.2, Python 3.8.5, Ubuntu 20.04.

Thanks!

**Comment by wtdcode** [comment]
if there isn't any hook installed, the pc value isn't guaranteed to be updated for overall performance by design.
