### ISSUE TITLE
[x86 Real Mode Target] Allow User Configure CPU Reset Behavior

### ISSUE THREAD

**Issue by microwave89-hv** [unicorn-engine/unicorn#1375]
In order to simulate a BIOS dump from the first instruction at 0xfffffff0 (See Intel SDMs, "Processor Initial State" (or similar)) the base of the CS register must be set to 0xffff0000 rather than 0, and other settings might currently be wrong too.
However for MBR simulations this likely doesn't hold true, see #737.
Ideally, the user may pick a suitable "reset type" in this case (MBR-like reset, boot ROM-like reset).

If these days a user wants to simulate such a boot ROM she must comment those lines of the "uc_open()" function in the "./uc.c" file as shown below, prior to simulating her BIOS .bin:
```
        /*if (uc->reg_reset)
            uc->reg_reset(uc);*/
```

This workaround makes at least the "./samples/sample_all.sh" tests fail, so there should be a configurable solution.

By the way, one seemingly cannot fix the Unicorn state by fiddling with the registers, since there is no documented way to alter that CS base ("Descriptor cache", "shadow descriptor").
*Without a fix it might be possible for a user to kickstart the Unicorn with some carefully crafted "Unreal mode" code that loads a specifically crafted GDT to tweak the "shadow descriptor(s)" to the desired values, however this wasn't looked into yet.*

**Comment by wtdcode** [comment]
Why not do a soft reset to emulate the hardware reset? Like setting registers as you like.
