### ISSUE TITLE
Missing support for MacOS Arm64 in GitHub workflow

### ISSUE THREAD

**Issue by AeonLucid** [unicorn-engine/unicorn#1379]
Would be great to have arm64 builds back. It was merged https://github.com/unicorn-engine/unicorn/pull/1261 a year ago, but with the switch to GitHub actions it never came back. More specifically, I am interested in `macos arm64` because of the M1 MacBooks.

I am unsure how to add this myself to the GitHub workflow.

**Comment by wtdcode** [comment]
Unicorn1 probably won't have m1 support since it's shipped with Unicorn2. Stay tuned!

**Comment by wtdcode** [comment]
Also link this one to #1217.

**Comment by AeonLucid** [comment]
@wtdcode Just to confirm, you are talking about shipping compiled unicorn binaries and not about emulating M1 itself, correct?

**Comment by wtdcode** [comment]
@AeonLucid Yes, after applying some fixes from upstream qemu.

**Comment by AeonLucid** [comment]
Thanks, looking forward to it.

**Comment by n0thing2speak** [comment]
Is there an approximate release time?

**Comment by wtdcode** [comment]
> Is there an approximate release time?

About 1-2 months.

**Comment by aquynh** [comment]
We dont know yet when unicorn2 is ready.

**Comment by n0thing2speak** [comment]
> We dont know yet when unicorn2 is ready.

Suddenly feel that M1 has depreciated  ):

**Comment by wtdcode** [comment]
Released now.
