### ISSUE TITLE
QEMU softmmu: memory types, what are ...

### ISSUE THREAD

**Issue by egberts** [unicorn-engine/unicorn#1384]
Questions for QEMU x86/AMD64 whiz:

Excuse the jump in thought here but QEMU still has a broken TLB (translation lookaside buffer) algorithm for self-modifying code, so I lifted one question from #364 issue to help bring greater focus (and hopefully more clarification) in which to aid my debugging effort into fixing this multi-year QEMU bug:

   This is a QEMU design question on different memory types being deployed. 

What are the proper logic to determine an io-mem/qemu:memory-region? Is it a fall-thru?

```c
    if (unlikely(tlb_addr & ~TARGET_PAGE_MASK))
```
above logic certainly isn't working for a user-supplied `uc_mem_write` ("pc.ram") memory region.

But it is what is being used also in the `tlb_vaddr_to_host()`.

Perhaps, it was MARKED as an "io.mem" by accident.

Yep, according to `include/exec/cpu-defs.h`:

```c
    typedef struct CPUTLBEntry {
        /* bit TARGET_LONG_BITS to TARGET_PAGE_BITS : virtual address
            bit TARGET_PAGE_BITS-1..4 : 
```

Nonzero for accesses that should not go directly to ram.

#364 issue shows that User-supplied "pc.mem" via uc_mem_write was MARKED as `TLB_NOTDIRTY` (bit 4), perhaps by accident? As in tlb_addr = 0x60000010, where 0x10 part represent the TLB_NOTDIRTY.

Real question is, are we supposed to be supporting virtual address scheme with the user-supplied `uc_mem_write()` memory regions?

@farmdve, anyone?

**Comment by egberts** [comment]
This is a request for any kind of recap of different memory regions deployed within QEMU engine, any summarization on iomem, et. al., would be greatly appreciated at this point in pushing this same set of issues further along.

**Comment by wtdcode** [comment]
Hi! Thanks for pointing out the problem. Unicorn2 is based on qemu5 and could you confirm whether the same problem still exists on qemu5?

**Comment by egberts** [comment]
Found it!

https://airbus-seclab.github.io/qemu_blog/regions.html 

i'm closing this issue.
