### ISSUE TITLE
Non-deterministic behaviour in fetching with UC_MEM_FETCH_PROT in x64

### ISSUE THREAD

**Issue by old-pigeon** [unicorn-engine/unicorn#1393]
I am about to create a scenario with x64 emulation where the following is true:

- When hitting a `UC_MEM_WRITE_PROT` or `UC_MEM_READ_PROT`, replace the contents at the requested address with different data and set the protection to `UC_PROT_WRITE | UC_PROT_READ`
- When hitting a `UC_MEM_FETCH_PROT`, replace the data with instructions at the requested address and set the protection to `UC_PROT_EXEC`

To do that, I created a hook with `UC_HOOK_MEM_FETCH_PROT | UC_HOOK_MEM_WRITE_PROT | UC_HOOK_MEM_READ_PROT` and do the replacing action accordingly.

I realized that this causes strange bugs and it was very hard to find out what happens. I think I figured it out for at least the majority of all cases:

In the case of a `UC_MEM_FETCH_PROT` hook, _sometimes_ the `size` argument of the requested fetch is 4. I assume that unicorn fetches (or wants to fetch) 4 bytes of instructions. Now in those cases (`size = 4`) unicorn does not seem to re-fetch these 4 bytes after I replaced them with actual instructions, set the protection to `UC_PROT_EXEC` and returned `true` in the hook.

Instead unicorn tries to execute what was in the memory before that replacing happened. The strange behavior is that whenever the size parameter is 1, it works and unicorn seems to successfully re-fetch and so it gets the correct instructions.

I couldn't find a pattern when the size is 1 and when the size is 4. The strange thing is that this seems to be non-deterministic: it differs between different executions of my program without changing code or the input to the emulation.

1. Is this a bug in unicorn?
2. Why would unicorn be non-deterministic?
3. Why would unicorn not re-fetch for `size = 4` fetches but it does for `size = 1` ones? 
4. Is this some sort of pre-fetching or branch-prediction or whatever optimizations might be at place?
5. Is there a better way to achieve what I want?

I also tried to work-around this behavior by stopping the emulation and restart it at the same point the protected fetch happened in hope that it would solve the problem but it a) seems far from ideal because it's slow and dirty and b) it also doesn't seem to work in 100% of all cases.

**Comment by wtdcode** [comment]
Hello, could you check if the problem exists on Unicorn2 and provide a reproduction script?

**Comment by wtdcode** [comment]
Closed due to inactivity
