### ISSUE TITLE
What is the QEMU version used by the current Unicorn (1.0.2)?

### ISSUE THREAD

**Issue by liyansong2018** [unicorn-engine/unicorn#1396]
Hello :)

What is the QEMU version used in the latest version of Unicorn (1.0.2)?
Maybe you can try to declare the version of the upstream project in [ChangeLog](https://www.unicorn-engine.org/changelog/).

Thank you a lot for the work you're doing!

**Comment by wtdcode** [comment]
See https://github.com/unicorn-engine/unicorn/blob/master/qemu/VERSION

**Comment by liyansong2018** [comment]
Thank you very much.
