### ISSUE TITLE
Build failure with -fpic on aarch64

### ISSUE THREAD

**Issue by lgbaldoni** [unicorn-engine/unicorn#1403]
Building unicorn 1.0.3 on openSUSE Leap 15.2 and other. I see:
```
CMakeFiles/x86_64-softmmu.dir/qemu/tcg/tcg.c.o: in function `qemu_loglevel_mask_x86_64':
/home/abuild/rpmbuild/BUILD/unicorn-1.0.3/qemu/include/qemu/log.h:44:(.text+0x46ec): relocation truncated to fit: R_AARCH64_LD64_GOTPAGE_LO15 against symbol `qemu_loglevel' defined in COMMON section in CMakeFiles/unicorn.dir/qemu/qemu-log.c.o
/usr/lib64/gcc/aarch64-suse-linux/7/../../../../aarch64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/unicorn-1.0.3/qemu/include/qemu/log.h:44: warning: too many GOT entries for -fpic, please recompile with -fPIC
collect2: error: ld returned 1 exit status
```

This doesn't occur on other architectures or on openSUSE Tumbleweed with gcc11. Removing -fpic from CMakeLists.txt makes things work.

Perhaps there isn't much to be done on your end, but I thought you ought to know.

**Comment by wtdcode** [comment]
Could you draft a PR?

________________________________
From: Luigi Baldoni ***@***.***>
Sent: Monday, May 31, 2021 8:56:40 PM
To: unicorn-engine/unicorn ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [unicorn-engine/unicorn] Build failure with -fpic on aarch64 (#1403)


Building unicorn 1.0.3 on openSUSE Leap 15.2 and other. I see:

CMakeFiles/x86_64-softmmu.dir/qemu/tcg/tcg.c.o: in function `qemu_loglevel_mask_x86_64':
/home/abuild/rpmbuild/BUILD/unicorn-1.0.3/qemu/include/qemu/log.h:44:(.text+0x46ec): relocation truncated to fit: R_AARCH64_LD64_GOTPAGE_LO15 against symbol `qemu_loglevel' defined in COMMON section in CMakeFiles/unicorn.dir/qemu/qemu-log.c.o
/usr/lib64/gcc/aarch64-suse-linux/7/../../../../aarch64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/unicorn-1.0.3/qemu/include/qemu/log.h:44: warning: too many GOT entries for -fpic, please recompile with -fPIC
collect2: error: ld returned 1 exit status


This doesn't occur on other architectures or on openSUSE Tumbleweed with gcc11. Removing -fpic from CMakeLists.txt makes things work.

Perhaps there isn't much to be done on your end, but I thought you ought to know.

―
