### ISSUE TITLE
When will MAC M1 be supported

### ISSUE THREAD

**Issue by wukong6666** [unicorn-engine/unicorn#1405]
Why can't it run on MAC M1

**Comment by wtdcode** [comment]
Duplicate with #1379

________________________________
From: wukong6666 ***@***.***>
Sent: Wednesday, June 9, 2021 9:05:24 PM
To: unicorn-engine/unicorn ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [unicorn-engine/unicorn] When will MAC M1 be supported (#1405)


Why can't it run on MAC M1

―
