### ISSUE TITLE
only register hook_mem_invalid callback not correct read eip

### ISSUE THREAD

**Issue by kycgni** [unicorn-engine/unicorn#1409]
/* Unicorn Emulator Engine */
/* By Nguyen Anh Quynh & Dang Hoang Vu, 2015 */

/* Sample code to demonstrate how to emulate X86 code */

#define _CRT_SECURE_NO_WARNINGS
#include "../../Common/UlibHeader/unicorn/unicorn.h"
#pragma comment(lib,"unicorn_static.lib")
#include <string.h>

// callback for tracing basic blocks
static void hook_block(uc_engine* uc, uint64_t address, uint32_t size, void* user_data)
{
    printf(">>> Tracing basic block at 0x%llx, block size = 0x%x\n", address, size);
}

// callback for tracing instruction
static void hook_code(uc_engine* uc, uint64_t address, uint32_t size, void* user_data)
{
    printf(">>> Tracing instruction at 0x%llx, instruction size = 0x%x\n", address, size);
}

// callback for tracing memory access (READ or WRITE)
static bool hook_mem_invalid(uc_engine* uc, uc_mem_type type,
    uint64_t address, int size, int64_t value, void* user_data)
{
    UINT32 r_eip = 0;
    uc_reg_read(uc, UC_X86_REG_EIP, &r_eip);
    printf("eip = 0x%x\n", r_eip);//error eip
    return TRUE;
}

static void test_i386(void)
{
    uc_engine* uc;
    uc_hook trace1, trace2, trace3;

    BYTE x86Code[] = {
    0xB8, 0x04, 0x00, 0x00, 0x00,  //[0x1000]：mov eax, 4   
    0xB8, 0x04, 0x00, 0x00, 0x00,  //[0x1005]：mov eax, 4
    0xB8, 0x04, 0x00, 0x00, 0x00,  //[0x100A]：mov eax, 4
    0x8B, 0x00,                    //[0x100f]：mov [eax], eax
    0xB8, 0x04, 0x00, 0x00, 0x00,  //[0x1011]：mov eax, 4 
    0xB8, 0x04, 0x00, 0x00, 0x00,  //[0x1016]：mov eax, 4
    };

    uc_err err = uc_open(UC_ARCH_X86, UC_MODE_32, &uc);
    if (err) {
        printf("Failed on uc_open() with error returned: %u\n", err);
        return;
    }
    uc_mem_map(uc, 0x1000, 2 * 1024 * 1024, UC_PROT_ALL);
    if (uc_mem_write(uc, 0x1000, x86Code, sizeof(x86Code))) {
        printf("Failed to write emulation code to memory, quit!\n");
        return;
    }
    //uc_hook_add(uc, &trace1, UC_HOOK_BLOCK, hook_block, NULL, 1, 0);
    //uc_hook_add(uc, &trace2, UC_HOOK_CODE, hook_code, NULL, 1, 0);
    uc_hook_add(uc, &trace3, UC_HOOK_MEM_READ_UNMAPPED | UC_HOOK_MEM_WRITE_UNMAPPED, hook_mem_invalid, NULL, 1, 0);

    err = uc_emu_start(uc, 0x1000, 0x1000 + sizeof(x86Code), 0, 0);
    if (err) {
        printf("Failed on uc_emu_start() with error returned %u: %s\n",
            err, uc_strerror(err));
    }

    uc_close(uc);
}

int main(int argc, char** argv, char** envp)
{
    test_i386();
    return 0;
}

**Comment by kycgni** [comment]
If other callbacks are registered, the EIP reads correctly，

**Comment by wtdcode** [comment]
See #534

**Comment by kycgni** [comment]
I am implementing a Unicorn-based OS emulator and adding UC_HOOK_CODE hooks will cause the system to run slowly

**Comment by wtdcode** [comment]
> I am implementing a Unicorn-based OS emulator and adding UC_HOOK_CODE hooks will cause the system to run slowly
> If I don't install UC_HOOK_MEM_XXX_UNMAILED hooks, I can't handle memory access exceptions

It is possible to keep the PC accurate but that also has some performance overhead.
