### ISSUE TITLE
[BUG?]    The uc_open() Function will change my custom LIST_ENTRY struct.

### ISSUE THREAD

**Issue by Alimo1029** [unicorn-engine/unicorn#1410]
Before:
![image](https://user-images.githubusercontent.com/44513759/122780696-aa34e580-d2e1-11eb-8914-04850267e32d.png)

After:
![image](https://user-images.githubusercontent.com/44513759/122780771-b9b42e80-d2e1-11eb-8d26-d4b953798a80.png)

I don't know if this is a bug, maybe I use it in the wrong way.
If need more codes or infomation, please call me

Thanks..

**Comment by wtdcode** [comment]
We couldn't help if you even don't provide the source code in a TEXT format.

**Comment by Alimo1029** [comment]
OK
My struct:
![image](https://user-images.githubusercontent.com/44513759/122782352-3b588c00-d2e3-11eb-93f5-bafa3bed3792.png)

About LIST_ENTRY:
![image](https://user-images.githubusercontent.com/44513759/122782353-3b588c00-d2e3-11eb-9830-d4b3c3d8cf9b.png)

About uc_engine and main():
![image](https://user-images.githubusercontent.com/44513759/122782429-4dd2c580-d2e3-11eb-8011-79840be7ff3e.png)
![image](https://user-images.githubusercontent.com/44513759/122782539-6216c280-d2e3-11eb-9419-cd0d7ba40802.png)

(Only these two operations are related to uc_engine in these)

**Comment by Alimo1029** [comment]
sorry There's something wrong with the picture

**Comment by Alimo1029** [comment]
> We couldn't help if you even don't provide the source code in a TEXT format.
@wtdcode 

Test Code:
```
#include <stdlib.h>
#include <stdio.h>

#include "../Emulator/include/unicorn/unicorn.h"

LIST_ENTRY seglist = { 0 };


typedef struct _SEG_MAP_ENTRY
{

	DWORD			base;
	unsigned int	size;
	LIST_ENTRY		list;
	const char* file_name;
	unsigned char* buffer;

}SEG_MAP_ENTRY, * PSEG_MAP_ENTRY;

/* This function come from Windows Driver ( WDK ) */

void InitializeListHead(PLIST_ENTRY ListHead)
{
	ListHead->Flink = ListHead->Blink = ListHead;
	return;
}

void InsertTailList(PLIST_ENTRY ListHead, PLIST_ENTRY Entry)
{

	PLIST_ENTRY PrevEntry;

	PrevEntry = ListHead->Blink;
	if (PrevEntry->Flink != ListHead) {
		return;
	}

	Entry->Flink = ListHead;
	Entry->Blink = PrevEntry;
	PrevEntry->Flink = Entry;
	ListHead->Blink = Entry;
	return;
}
/********************************************************/

void init_files()
{
	InitializeListHead(&seglist);

	SEG_MAP_ENTRY seg1, seg2 = { 0 };
	seg1.base =			0x00401000;
	seg1.size =			0x00001000;
	seg1.file_name =	"C:\\Users\\limo1029\\Desktop\\vmprotect_00401000.bin";
	seg1.buffer =		NULL;

	seg2.base =			0x0019B000;
	seg2.size =			0x00005000;
	seg2.file_name =	"C:\\Users\\limo1029\\Desktop\\vmprotect_0019B000.bin";
	seg2.buffer =		NULL;

	InsertTailList(&seglist, &seg1.list);
	InsertTailList(&seglist, &seg2.list);
}

int main()
{
	init_files();

	uc_engine* uc = NULL;
	uc_err err = UC_ERR_OK;
	err = uc_open(UC_ARCH_X86, UC_MODE_32, &uc);


	return 0;
}
```

Before uc_open():
![image](https://user-images.githubusercontent.com/44513759/122906375-ab6b1e80-d384-11eb-9532-7c33fb174281.png)

But if I run uc_open():
there will be change, like:
![image](https://user-images.githubusercontent.com/44513759/122906581-e2d9cb00-d384-11eb-8274-42831f0e53b0.png)

Maybe I using LIST_ENTRY in the wrong way?
