### ISSUE TITLE
Feature gate build.rs from rust bindings

### ISSUE THREAD

**Issue by IamTheCarl** [unicorn-engine/unicorn#1413]
The build script in the Rust bindings searchs for and links against a globally installed instance of unicorn engine.
I need to cross compile my project. Having cross compiled instances of a library all installed globally is quite a hassle, so what I usually do is install a local copy in the project as a build artifact, and then link that in.

The build script gives me no way to do that. My temporary solution was to just delete the script all together, and now it just works.

You could hide the current build script behind a feature gate like the mLua crate does, giving you the convenience of auto linking (especially helpful for those who don't read the README) but also leaving people like me free to link Unicorn in manually.

See the vendored feature mentioned here as an example: https://crates.io/crates/mlua

**Comment by wtdcode** [comment]
Yes, how current rust bindings builds is not so ideal. Working on it.

**Comment by wtdcode** [comment]
New rust bindings would be released with uc2. Link to #1217

**Comment by wtdcode** [comment]
Also link to #1449

**Comment by wtdcode** [comment]
Closed. See https://crates.io/crates/unicorn-engine
