### ISSUE TITLE
How does unicorn hook_mem_invalid know where to access memory?

### ISSUE THREAD

**Issue by NickTsl** [unicorn-engine/unicorn#1415]
In this line, the memory is remapped so that the emulator can access this memory without any exceptions. https://github.com/unicorn-engine/unicorn/blob/master/samples/sample_x86.c#L79

But how does the emulator really know to access 0xaaaa0000? Wouldn't the emulator just try to read the same unmapped memory region?

**Comment by wtdcode** [comment]
This hook is intended for function `test_i386_invalid_mem_write`, not a general one.
