### ISSUE TITLE
No FLAGS register for 16-bit mode?

### ISSUE THREAD

**Issue by gaku** [unicorn-engine/unicorn#1416]
I am trying to run an old 8086 code with UC_MODE_16.  I tried to dump FLAGS register, but there's no UC_X86_REG_FLAGS.  UC_X86_REG_ELAGS is there, but it is a 32-bit register.

Is there a reason why UC_X86_REG_FLAGS is not included?

**Comment by wtdcode** [comment]
The FLAGS and EFLAGS basically are the same in the internal implementation. You could use UC_X86_REG_ELAGS to retrieve the register while the high 16bits are undefined.

**Comment by gaku** [comment]
Yes, but because I had to use UC_X86_REG_EFLAGS, I had a nasty bug by mistakenly passed uint16_t variable and neighboring local variable was overwritten.

It seems like introducing UC_X86_REG_FLAGS seems not too difficult.  Would you accept the PR if I make the change?

**Comment by wtdcode** [comment]
> Yes, but because I had to use UC_X86_REG_EFLAGS, I had a nasty bug by mistakenly passed uint16_t variable and neighboring local variable was overwritten.
> 
> It seems like introducing UC_X86_REG_FLAGS seems not too difficult. Would you accept the PR if I make the change?

The unicorn1 won't have major updates and I would implement FLAG in unicorn2. Link to #1217.

**Comment by gaku** [comment]
Okay that sounds good!  In the mean time, I'll fork for my own to deal with it.

**Comment by wtdcode** [comment]
Done in uc2. Also add RFLAGS for clarity.
