### ISSUE TITLE
Failed on uc_mem_map() with error returned 15 : Invalid argument (UC_ERR_ARG)

### ISSUE THREAD

**Issue by migraine-sudo** [unicorn-engine/unicorn#1417]
Hello, may I ask, how to solve such a problem?
Failed on uc_mem_map() with error returned 15 : Invalid argument (UC_ERR_ARG)
Code：

void map_memory(uint64_t addr,size_t size){
	//return !uc_mem_map(uc,addr,size,UC_PROT_ALL);
	uc_err err = uc_mem_map(uc,addr,size,UC_PROT_ALL);
    if (err) {
        	cout << ("Failed on uc_mem_map() with error returned ")
        	<< err << " : "<< uc_strerror(err) << endl;
        	//abort();
    	}
	}

**Comment by migraine-sudo** [comment]
I use libunicorn.a for development under Linux, and I don’t know if this will affect the results of the operation？

**Comment by wtdcode** [comment]
The error message speaks it loudly and we can’t help if you couldn’t provide a script to repreoduce.
________________________________
From: Migraine殇 ***@***.***>
Sent: Thursday, July 1, 2021 1:03:12 PM
To: unicorn-engine/unicorn ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [unicorn-engine/unicorn] Failed on uc_mem_map() with error returned 15 : Invalid argument (UC_ERR_ARG) (#1417)


Hello, may I ask, how to solve such a problem?
Failed on uc_mem_map() with error returned 15 : Invalid argument (UC_ERR_ARG)
Code：

void map_memory(uint64_t addr,size_t size){
//return !uc_mem_map(uc,addr,size,UC_PROT_ALL);
uc_err err = uc_mem_map(uc,addr,size,UC_PROT_ALL);
if (err) {
cout << ("Failed on uc_mem_map() with error returned ")
<< err << " : "<< uc_strerror(err) << endl;
//abort();
}
}

―

**Comment by migraine-sudo** [comment]
I suspect that the problem is caused by my local compiler or other environment variables, because the project I wrote before that can run normally has the same problem today

**Comment by migraine-sudo** [comment]
May I ask whether the mapped address in the uc_map_mem function must be byte-aligned. It seems that custom sizes cannot be allocated successfully.
