### ISSUE TITLE
siglongjmp() in  cpu_loop_exit_x86_64 crash

### ISSUE THREAD

**Issue by NickTsl** [unicorn-engine/unicorn#1419]
![image](https://user-images.githubusercontent.com/77312921/124304528-d0545400-db31-11eb-9c74-786033bd7146.png)

 It happens on visual studio 2019, in both release and debug builds of my program. I didn't have this crash before, but now I do. I cannot continue work on my project until I figure out how to solve this problem.

**Comment by wtdcode** [comment]
Unicorn version and reproduction script please.

**Comment by NickTsl** [comment]
> Unicorn version and reproduction script please.

Version major number: 1
Version Minor number: 0

This is the code that reproduces the bug:
`REG_CONTEXT emulate(
	std::vector<InstructionAccess>& Insns,
	REG_CONTEXT& RegContext
) {
	uint64_t rsp = UC_ADDRESS + 0x200000;
	RegContext.WriteToUC(global::UnknownCheats, rsp);
	
	unsigned int major, minor;
	uc_version(&major, &minor);

	uc_mem_map(global::UnknownCheats, UC_ADDRESS, 2 * 1024 * 1024, UC_PROT_ALL);

	int NumOfBytes = 0;
	for (int i = 0; i < Insns.size(); ++i)
	{
		uc_mem_write(global::UnknownCheats, UC_ADDRESS + NumOfBytes, Insns[i].Insn.bytes, Insns[i].Insn.size);
		NumOfBytes += Insns[i].Size;
	}

	uc_err err = uc_emu_start(global::UnknownCheats, UC_ADDRESS, UC_ADDRESS + NumOfBytes, 0, 0);`

**Comment by NickTsl** [comment]
Also, I should say that this bug ONLY happens on my laptop, it never occurs on my desktop PC, which is extremely strange. I copied the project files over and double checked that the code worked without issue on my desktop PC.

**Comment by NickTsl** [comment]
It seems to have been a hidden issue in my project properties. I solved the problem, and all I did was copy my project code into the sample project provided by Unicorn.
