### ISSUE TITLE
threading/forking

### ISSUE THREAD

**Issue by lunixbochs** [unicorn-engine/unicorn#142]
I want to be able to emulate threading and forking inside a single process under Unicorn. I think this will require at minimum a shared memory API.

Perhaps the easiest way would be a function allowing you to source a Unicorn's MMU from another Unicorn instance? New mappings against either instance should affect both instances. It's up to me (the "kernel") to keep things thread-safe. (I'm okay with Unicorn marking the memory mapping functions thread-unsafe and making me lock myself, as I'll already be dealing with that internally)

For fork(), I think I can implement copy-on-write by mapping everything read-only, trapping invalid memory access, and copying/remapping pages when you try to write to a CoW region. For this to be implemented via the Unicorn API, I'd need a way to do a zero-copy MMU clone pointing at the same memory but with everything marked read-only.

**Comment by lunixbochs** [comment]
You manage the CPU threads yourself by which thread you call uc_emu_start() from. The main issues are sharing memory as well as memory synchronization/barriers/locks between unicorn instances.

You should already be able to clone a thread by mapping all of your memory with uc_mem_map_ptr, then on clone, copy the registers and mappings into the new unicorn instance.

**Comment by Guy1524** [comment]
Yeah, implementing a custom scheduler would work, but that is slow ):

I think I'll go the uc_mem_map_ptr route, but I wish the API made this more convenient.

**Comment by lunixbochs** [comment]
You don't need to constantly update every thread's memory view every time a new mapping is made. Just add a memory fault handler that maps in regions on demand, like so:

https://github.com/lunixbochs/precorn/blob/master/src/precorn.c#L15

**Comment by Guy1524** [comment]
In my use-case, the mappings aren't 1:1 host to guest.  The host is in user-mode and the guest operating on a driver with addresses in that space.  Plus, not all of mappings have the same protections.

**Comment by lunixbochs** [comment]
That’s not really relevant for the example. I was just showing you how to do demand paging with unicorn. It’s up to you how the actual backing pages are managed.

**Comment by Guy1524** [comment]
Ah, so I should I should protect the pages myself using OS functionality instead of the builtin unicorn protections, OK, that works.

**Comment by lunixbochs** [comment]
No, it's fine to use the unicorn protections. I hoped you'd infer more of this yourself.

1. When something maps memory, allocate it on the host, and save the allocation information (guest addr, host addr, size, protection) somewhere.
2. When a thread segfaults, scan this list (if it's sorted by start addr you can binary search). If you find a matching page, call map_ptr to map it in with the right protections.

Worth noting if you're emulating a complex OS, you'll need to handle weird stuff like partial unmapping. Usercorn does a lot of this already.

**Comment by Guy1524** [comment]
Okay, so I store all the information about the address space myself and correct it when a thread isn't up to date.  Unmapping would be another pain point.  I'll just do the scheduler thing until perf is a problem.  Thanks.
