### ISSUE TITLE
Wrong decoding for instruction BL, BLX (immediate) Encoding T2

### ISSUE THREAD

**Issue by xtyi** [unicorn-engine/unicorn#1424]
According to the ARM manual, if H equals to 1, this instruction should be an UNDEFINED instruction.

![image](https://user-images.githubusercontent.com/49339959/126758891-e04b9bb1-5291-4eb1-b660-05e28b5f1cdd.png)

Unicorn should throw an UC_ERR_INSN_INVALID, but the instruction is executed normally.
This Bug may comes from qemu.
We have submitted this bug to qemu, and it has been confirmed.

https://bugs.launchpad.net/qemu/+bug/1925512

**Comment by wtdcode** [comment]
Hello, thanks for your issue, this would be fixed in uc2. Link to #1217.

**Comment by xtyi** [comment]
OK, Thanks for your effort. Just a reminder, we found that qemu also has the following two bugs, Of course unicorn also has.
https://bugs.launchpad.net/qemu/+bug/1905356
https://bugs.launchpad.net/qemu/+bug/1922887
