### ISSUE TITLE
About ARM Instruction UDF.

### ISSUE THREAD

**Issue by xtyi** [unicorn-engine/unicorn#1425]
According to arm manual, UDF generates an undefined instruction exception.
Usually, the instruction that generates undefined instruction exception would be treated as an invalid instruction. However, Unicorn emulates this instruction without triggering any exception. The right behavior might be raising the  UC_ERR_INSN_INVALID. We also run this instruction in the real device, and sigill signal is triggered.

**Comment by wtdcode** [comment]
Seems duplicate to your previous one?
