### ISSUE TITLE
why data size = 8 ?

### ISSUE THREAD

**Issue by icyfox168168** [unicorn-engine/unicorn#1426]
>>> Memory is being WRITE at 0x00000000017FFF08, data size = 4, data value = 0x0000000000000001
add dword ptr [rax], eax
>>> Memory is being WRITE at 0x00000000017FFF18, data size = 4, data value = 0x0000000000000001
add dword ptr [rax], eax
>>> Memory is being READ at 0x00000000017FFFC0,data size = 8
add byte ptr [rax], al
>>> Memory is being READ at 0x00000000017FFFC8,data size = 8
add byte ptr [rax], al
>>> Memory is being READ at 0x00000000017FFFD0,data size = 8
add byte ptr [rax], al
>>> Memory is being READ at 0x00000000017FFFD8,data size = 8
add byte ptr [rax], al
>>> Memory is being READ at 0x00000000017FFFE0,data size = 8
add byte ptr [rax], al
>>> Memory is being READ at 0x00000000017FFFE8,data size = 8
add byte ptr [rax], al
>>> Memory is being READ at 0x00000000017FFFF0,data size = 8
add byte ptr [rax], al
>>> Memory is being READ at 0x00000000017FFFF8,data size = 8
add byte ptr [rax], al
>>> Memory is being READ at 0x0000000001800000,data size = 8
add byte ptr [rax], al
Failed on uc_emu_start() with error returned 8: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)

**Comment by wtdcode** [comment]
Closed due to no detailed information.
