### ISSUE TITLE
Compilation under Android platform

### ISSUE THREAD

**Issue by enoorez** [unicorn-engine/unicorn#1429]
I need to compile this library on Android platform, but the current compilation script does not support it. 
The following modifications I added can support this requirement:

``` CMakeLists
  # GEN config-host.mak & target directories
  execute_process(COMMAND sh ${CMAKE_CURRENT_SOURCE_DIR}/qemu/configure
      ${EXTRA_CFLAGS}
      ${TARGET_LIST}
      --cc=${CMAKE_C_COMPILER}
      --cpu={UNICORN_TARGET_ARCH}
      WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
  )

```

To support the arm platform, you need to specify the compiler path for cross compilation before the previous step :

``` CMakeLists

# get compiler directory
string(REGEX REPLACE "(.+)/.*" "\\1" C_COMPILER ${CMAKE_C_COMPILER})
string(SUBSTRING "${CMAKE_C_COMPILER_TARGET}" 0 4 C_TARGET)

# get ndk abi
string(REGEX MATCH "id([0-9][0-9])" CC_ABI_ ${CMAKE_C_COMPILER_TARGET})
string(REGEX MATCH "([0-9][0-9])" CC_ABI "${CC_ABI_}")
# Select compiler
if ( ${C_TARGET} STREQUAL "armv" )
    string(REGEX MATCH "abi([0-9][0-9])" CC_ABI_ ${CMAKE_C_COMPILER_TARGET})
    string(REGEX MATCH "([0-9][0-9])" CC_ABI "${CC_ABI_}")
    set(CMAKE_C_COMPILER "${C_COMPILER}/armv7a-linux-androideabi${CC_ABI}-clang")
elseif (${C_TARGET} STREQUAL "aarc")
    set(CMAKE_C_COMPILER "${C_COMPILER}/aarch64-linux-android${CC_ABI}-clang")
elseif ("${C_TARGET}" STREQUAL "i686")
    set(CMAKE_C_COMPILER "${C_COMPILER}/i686-linux-android${CC_ABI}-clang")
elseif ("${C_TARGET}" STREQUAL "x86_")
    set(CMAKE_C_COMPILER "${C_COMPILER}/x86_64-linux-android${CC_ABI}-clang")
else()
    message(FATAL_ERROR "Unknown host target: ${CMAKE_C_COMPILER_TARGET}")
endif ()

```

**Comment by wtdcode** [comment]
Could you draft a PR? And how could I test your script?
________________________________
From: enoorez ***@***.***>
Sent: Sunday, August 1, 2021 3:12:53 PM
To: unicorn-engine/unicorn ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [unicorn-engine/unicorn] Compilation under Android platform (#1429)


I need to compile this library on Android platform, but the current compilation script does not support it.
The following modifications I added can support this requirement:

  # GEN config-host.mak & target directories
  execute_process(COMMAND sh ${CMAKE_CURRENT_SOURCE_DIR}/qemu/configure
      ${EXTRA_CFLAGS}
      ${TARGET_LIST}
      --cc=${CMAKE_C_COMPILER}
      --cpu={UNICORN_TARGET_ARCH}
      WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
  )



To support the arm platform, you need to specify the compiler path for cross compilation:


# get compiler directory
string(REGEX REPLACE "(.+)/.*" "\\1" C_COMPILER ${CMAKE_C_COMPILER})
string(SUBSTRING "${CMAKE_C_COMPILER_TARGET}" 0 4 C_TARGET)

# get ndk abi
string(REGEX MATCH "id([0-9][0-9])" CC_ABI_ ${CMAKE_C_COMPILER_TARGET})
string(REGEX MATCH "([0-9][0-9])" CC_ABI "${CC_ABI_}")
# Select compiler
if ( ${C_TARGET} STREQUAL "armv" )
    string(REGEX MATCH "abi([0-9][0-9])" CC_ABI_ ${CMAKE_C_COMPILER_TARGET})
    string(REGEX MATCH "([0-9][0-9])" CC_ABI "${CC_ABI_}")
    set(CMAKE_C_COMPILER "${C_COMPILER}/armv7a-linux-androideabi${CC_ABI}-clang")
elseif (${C_TARGET} STREQUAL "aarc")
    set(CMAKE_C_COMPILER "${C_COMPILER}/aarch64-linux-android${CC_ABI}-clang")
elseif ("${C_TARGET}" STREQUAL "i686")
    set(CMAKE_C_COMPILER "${C_COMPILER}/i686-linux-android${CC_ABI}-clang")
elseif ("${C_TARGET}" STREQUAL "x86_")
    set(CMAKE_C_COMPILER "${C_COMPILER}/x86_64-linux-android${CC_ABI}-clang")
else()
    message(FATAL_ERROR "Unknown host target: ${CMAKE_C_COMPILER_TARGET}")
endif ()



―

**Comment by enoorez** [comment]
OK, I will submit a PR later. If you need to test, you can pass the following environment and steps:
1. Linux 
2. Create an NDK project through Android studio,  and then modify the cmakelists.txt file of the NDK project through the command add_ subdirectory adds unicorn to the NDK project.

It must be on the Linux , because the compilation of qmenu requires the shell environment under Linux, so it cannot succeed on the Windows

**Comment by wtdcode** [comment]
Duplicate #1407
