### ISSUE TITLE
cpu_arm_exec_aarch64 Where is the source code reality ？ 

### ISSUE THREAD

**Issue by haidragon** [unicorn-engine/unicorn#1432]
#define cpu_arm_exec cpu_arm_exec_aarch64 ?

**Comment by wtdcode** [comment]
grep is your friend.

**Comment by haidragon** [comment]
unicorn % grep -r "cpu_arm_exec" ./ 
.//qemu/aarch64.h:#define cpu_arm_exec cpu_arm_exec_aarch64
.//qemu/aarch64eb.h:#define cpu_arm_exec cpu_arm_exec_aarch64eb
.//qemu/arm.h:#define cpu_arm_exec cpu_arm_exec_arm
.//qemu/armeb.h:#define cpu_arm_exec cpu_arm_exec_armeb
.//qemu/header_gen.py:    'cpu_arm_exec',
.//qemu/m68k.h:#define cpu_arm_exec cpu_arm_exec_m68k
.//qemu/mips.h:#define cpu_arm_exec cpu_arm_exec_mips
.//qemu/mips64.h:#define cpu_arm_exec cpu_arm_exec_mips64
.//qemu/mips64el.h:#define cpu_arm_exec cpu_arm_exec_mips64el
.//qemu/mipsel.h:#define cpu_arm_exec cpu_arm_exec_mipsel
.//qemu/sparc.h:#define cpu_arm_exec cpu_arm_exec_sparc
.//qemu/sparc64.h:#define cpu_arm_exec cpu_arm_exec_sparc64
.//qemu/target-arm/cpu.h:int cpu_arm_exec(struct uc_struct *uc, CPUARMState *s);
.//qemu/target-arm/cpu.h:#define cpu_exec cpu_arm_exec
.//qemu/x86_64.h:#define cpu_arm_exec cpu_arm_exec_x86_64
Binary file .//build/unicorn.build/Debug/armeb-softmmu.build/Objects-normal/x86_64/cpu-exec.o matches
Binary file .//build/unicorn.build/Debug/armeb-softmmu.build/Objects-normal/x86_64/cpus.o matches
Binary file .//build/unicorn.build/Debug/armeb-softmmu.build/libarmeb-softmmu.a matches
Binary file .//build/unicorn.build/Debug/aarch64-softmmu.build/Objects-normal/x86_64/cpu-exec.o matches
Binary file .//build/unicorn.build/Debug/aarch64-softmmu.build/Objects-normal/x86_64/cpus.o matches
Binary file .//build/unicorn.build/Debug/aarch64-softmmu.build/libaarch64-softmmu.a matches
Binary file .//build/unicorn.build/Debug/arm-softmmu.build/Objects-normal/x86_64/cpus.o matches
Binary file .//build/unicorn.build/Debug/arm-softmmu.build/Objects-normal/x86_64/cpu-exec.o matches
Binary file .//build/unicorn.build/Debug/arm-softmmu.build/libarm-softmmu.a matches
Binary file .//build/unicorn.build/Debug/aarch64eb-softmmu.build/Objects-normal/x86_64/cpu-exec.o matches
Binary file .//build/unicorn.build/Debug/aarch64eb-softmmu.build/Objects-normal/x86_64/cpus.o matches
Binary file .//build/unicorn.build/Debug/aarch64eb-softmmu.build/libaarch64eb-softmmu.a matches
Binary file .//build/Debug/libunicorn.dylib matches
Binary file .//build/Debug/libunicorn.1.dylib matches
haidragon@liuhailongdeMacBook-Pro unicorn % grep -r "cpu_arm_exec(" ./ 
.//qemu/target-arm/cpu.h:int cpu_arm_exec(struct uc_struct *uc, CPUARMState *s);
.//qemu/mips64el.h:#define cpu_arm_exec cpu_arm_exec_mips64el
.//qemu/mipsel.h:#define cpu_arm_exec cpu_arm_exec_mipsel
.//qemu/sparc.h:#define cpu_arm_exec cpu_arm_exec_sparc
.//qemu/sparc64.h:#define cpu_arm_exec cpu_arm_exec_sparc64
.//qemu/target-arm/cpu.h:int cpu_arm_exec(struct uc_struct *uc, CPUARMState *s);
.//qemu/target-arm/cpu.h:#define cpu_exec cpu_arm_exec
.//qemu/x86_64.h:#define cpu_arm_exec cpu_arm_exec_x86_64
Binary file .//build/unicorn.build/Debug/armeb-softmmu.build/Objects-normal/x86_64/cpu-exec.o matches
Binary file .//build/unicorn.build/Debug/armeb-softmmu.build/Objects-normal/x86_64/cpus.o matches
Binary file .//build/unicorn.build/Debug/armeb-softmmu.build/libarmeb-softmmu.a matches
Binary file .//build/unicorn.build/Debug/aarch64-softmmu.build/Objects-normal/x86_64/cpu-exec.o matches
Binary file .//build/unicorn.build/Debug/aarch64-softmmu.build/Objects-normal/x86_64/cpus.o matches
Binary file .//build/unicorn.build/Debug/aarch64-softmmu.build/libaarch64-softmmu.a matches
Binary file .//build/unicorn.build/Debug/arm-softmmu.build/Objects-normal/x86_64/cpus.o matches
Binary file .//build/unicorn.build/Debug/arm-softmmu.build/Objects-normal/x86_64/cpu-exec.o matches
Binary file .//build/unicorn.build/Debug/arm-softmmu.build/libarm-softmmu.a matches
Binary file .//build/unicorn.build/Debug/aarch64eb-softmmu.build/Objects-normal/x86_64/cpu-exec.o matches
Binary file .//build/unicorn.build/Debug/aarch64eb-softmmu.build/Objects-normal/x86_64/cpus.o matches
Binary file .//build/unicorn.build/Debug/aarch64eb-softmmu.build/libaarch64eb-softmmu.a matches
Binary file .//build/Debug/libunicorn.dylib matches
Binary file .//build/Debug/libunicorn.1.dylib matches
Binary file .//build/Debug/libunicorn.dylib matches
Binary file .//build/Debug/libunicorn.1.dylib matches
unicorn % grep -r "cpu_arm_exec(" ./ 
.//qemu/target-arm/cpu.h:int cpu_arm_exec(struct uc_struct *uc, CPUARMState *s);
