### ISSUE TITLE
UC_HOOK_CODE hook being called twice per instruction

### ISSUE THREAD

**Issue by crass** [unicorn-engine/unicorn#1434]
I'm not sure if this is a bug. My understanding is that `UC_HOOK_CODE` hooks should only be called once per instruction cycle. This appears to not be the case in [tests/regress/hook_code_stop_emu.py](../tree/master/tests/regress/hook_code_stop_emu.py). If a print statement is inserted at line 27, eg. `print(f"_stop_hook: 0x{address:x} ({args}, {kwargs})")`, it appears as though the hook is being run before and after each instruction.  I get the following output:
```
pc: 0x1000
_stop_hook: 0x1000 ((7, None), {})
_stop_hook: 0x1007 ((2, None), {})
pc: 0x1007
_stop_hook: 0x1007 ((2, None), {})
_stop_hook: 0x1009 ((7, None), {})
pc: 0x1009
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
```

Is this how unicorn is supposed to work?

**Comment by wtdcode** [comment]
Not the case. It's the expected output since UC_HOOK_CODE always get called before any instruction.

Take 0x1007 as an example. The first call is within the first step, the UC is about to execute 0x1007 and we let it stop since it has executed 0x1000. The second call is within the second step and we indeed would like the instruction to be executed.

**Comment by crass** [comment]
Ok, so then a `UC_HOOK_CODE` hook will be called for an instruction that would be executed if not for `emu_stop`. This seems like a bug to me. The hook should only be run for instructions that will definitely be executed. In this case the emu_stop happens in the first `_stop_hook`, which is before the instruction gets executed, so unicorn should know that a stop was requested and not call the hook after the instruction is run.

**Comment by wizdzz** [comment]
https://github.com/unicorn-engine/unicorn/issues/1164

I had found and fixed a similar issue in year 2019, however it was happened in Java Binding;
hope there are anything could help you;
by the way, there is no reply on my issue, and I do not know the reason, no guys would use Java Binding Unicorn?

**Comment by wtdcode** [comment]
> #1164
> 
> I had found and fixed a similar issue in year 2019, however it was happened in Java Binding;
> hope there are anything could help you;
> by the way, there is no reply on my issue, and I do not know the reason, no guys would use Java Binding Unicorn?

The issue you described seems the expected behavior, too.

BTW, thanks for your interest. Sorry that Unicorn lack of contributors currently and I'm not familiar with JNI unfortunately.

**Comment by wtdcode** [comment]
Closed due to inactivity.
