### ISSUE TITLE
Random value returned by m68k LEA with PC as base register

### ISSUE THREAD

**Issue by IridiumXOR** [unicorn-engine/unicorn#1435]
Hi,
if you try to emulate this simple code
```
.section .text
.globl _start
_start:
        movea.l #0x3, %A2
        lea (0x2, %PC, %A2 * 0x4), %A2
```

the content of A2 register resulting after the LEA is completely random, and change among executions...
The problem is present only if PC register is used as base register in addressing mode "Program Counter Indirect with Scaled 
Index and 8-Bit Displacement"

Please can you fix it?

**Comment by wtdcode** [comment]
Please provide a minimal reproduction script or we can’t help too much.
________________________________
From: IridiumXOR ***@***.***>
Sent: Saturday, August 21, 2021 7:05:21 PM
To: unicorn-engine/unicorn ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [unicorn-engine/unicorn] Random value returned by m68k LEA with PC as base register (#1435)


Hi,
if you try to emulate this simple code

.section .text
.globl _start
_start:
        movea.l #0x3, %A2
        lea (0x2, %PC, %A2 * 0x4), %A2


the content of A2 register resulting after the LEA is completely random, and change among executions...
The problem is present only if PC register is used as base register in addressing mode "Program Counter Indirect with Scaled
Index and 8-Bit Displacement"

Please can you fix it?

―

**Comment by IridiumXOR** [comment]
here a simple code
```
#!/usr/bin/env python3
from unicorn import *
from unicorn.m68k_const import *
from capstone import *

mu = Uc(UC_ARCH_M68K, UC_MODE_BIG_ENDIAN)
md = Cs(CS_ARCH_M68K, CS_MODE_BIG_ENDIAN)

mu.mem_map(0x0, 0x10000)
code = b"\x24\x7C\x00\x00\x00\x03\x45\xFB\xAC\x02\x4E\x71" # movea.l #0x3, %A2    lea (0x2, %PC, %A2 * 0x4), %A2    nop
mu.mem_write(0, code)

def hook_instr(uc, address, size, user_data):
    addr = mu.reg_read(UC_M68K_REG_PC)
    dec = list(md.disasm_lite(mu.mem_read(addr, 0x40), addr))[0]
    print(f"PC:{hex(addr)}, A2:{hex(mu.reg_read(UC_M68K_REG_A2))}, {dec}")


mu.hook_add(UC_HOOK_CODE, hook_instr)
mu.emu_start(0, 12)
```

and the results of two different execution
```
PC:0x0, A2:0x0, (0, 6, 'movea.l', '#$3, a2')
PC:0x6, A2:0x3, (6, 4, 'lea.l', '$a(pc, a2.l), a2')
PC:0xa, A2:0x562d, (10, 2, 'nop', '')


PC:0x0, A2:0x0, (0, 6, 'movea.l', '#$3, a2')
PC:0x6, A2:0x3, (6, 4, 'lea.l', '$a(pc, a2.l), a2')
PC:0xa, A2:0x559d, (10, 2, 'nop', '')
```

**Comment by wtdcode** [comment]
I tested your script with uc2 (#1217) and it looks good.

```
/tmp $ python3 test.py
PC:0x0, A2:0x0, (0, 6, 'movea.l', '#$3, a2')
PC:0x6, A2:0x3, (6, 4, 'lea.l', '$a(pc, a2.l), a2')
PC:0xa, A2:0x16, (10, 2, 'nop', '')
/tmp $ python3 test.py
PC:0x0, A2:0x0, (0, 6, 'movea.l', '#$3, a2')
PC:0x6, A2:0x3, (6, 4, 'lea.l', '$a(pc, a2.l), a2')
PC:0xa, A2:0x16, (10, 2, 'nop', '')
/tmp $ python3 test.py
PC:0x0, A2:0x0, (0, 6, 'movea.l', '#$3, a2')
PC:0x6, A2:0x3, (6, 4, 'lea.l', '$a(pc, a2.l), a2')
PC:0xa, A2:0x16, (10, 2, 'nop', '')
```

I'm not familiar with m64k and it looks right?.

**Comment by IridiumXOR** [comment]
I have used bot pip version, and i have compiled both version of Unicorn (1 not 2,  where is the github of unicorn 2?) and it does not work...

**Comment by wtdcode** [comment]
Unicorn2 is the next release of unicorn engine. Stay tuned!
________________________________

**Comment by IridiumXOR** [comment]
yep, but please can you check with unicorn 1 which is the only public available now?

**Comment by wtdcode** [comment]
Sorry that there won’t be new updates to current codebase until Unicorn2 is released.
________________________________

**Comment by IridiumXOR** [comment]
I think i will move to [this](https://github.com/yuzu-emu/unicorn) fork which is updated at the latest QEMU release and it works, thanks anyway

**Comment by wtdcode** [comment]
FYI: That fork is only tested against ARM.
________________________________

**Comment by IridiumXOR** [comment]
Yep, but i work perfectly in my case  and it is available now

**Comment by wtdcode** [comment]
Closed due to uc2 beta release.
