### ISSUE TITLE
Invalid size of the "mov r16, imm16" instruction

### ISSUE THREAD

**Issue by V-Lor** [unicorn-engine/unicorn#1436]
Example:
```c
#include <unicorn/unicorn.h>

#define ADDR 0x1000000
#define CODESZ 12

static uint8_t code[] = {
  0xB8, 0x1, 0x0,  /* mov ax, 1 */
  0xB9, 0x1, 0x0,  /* mov cx, 1 */
  0xBA, 0x1, 0x0,  /* mov dx, 1 */
  0xBB, 0x1, 0x0,  /* mov bx, 1 */
};

static void code_hook(uc_engine *uc, uint64_t addr, uint32_t size, void *)
{
  uint32_t idx = addr - ADDR;
  printf("Instruction 0x%X at index %d with size: %d\n", code[idx], idx, size);
}

int main()
{
  uc_engine *uc;
  uc_hook uh_trap;
  uc_open(UC_ARCH_X86, UC_MODE_32, &uc);
  uc_mem_map(uc, ADDR, 2*1024*1024, UC_PROT_ALL);
  uc_mem_write(uc, ADDR, code, CODESZ);
  uc_hook_add(uc, &uh_trap, UC_HOOK_CODE, code_hook, NULL, ADDR, 0);
  uc_emu_start(uc, ADDR, ADDR+CODESZ, 0, 0);
  uc_close(uc);
  return 0;
}
```
Output:
```
Instruction 0xB8 at index 0 with size: 5
Instruction 0x0 at index 5 with size: 6
```

**Comment by wtdcode** [comment]
Why not UC_MODE_16?
________________________________
From: Vilor ***@***.***>
Sent: Saturday, August 21, 2021 7:23:41 PM
To: unicorn-engine/unicorn ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [unicorn-engine/unicorn] Invalid size of the "mov r16, imm16" instruction (#1436)


Example:

#include <unicorn/unicorn.h>

#define ADDR 0x1000000
#define CODESZ 12

static uint8_t code[] = {
  0xB8, 0x1, 0x0,  /* mov ax, 1 */
  0xB9, 0x1, 0x0,  /* mov cx, 1 */
  0xBA, 0x1, 0x0,  /* mov dx, 1 */
  0xBB, 0x1, 0x0,  /* mov bx, 1 */
};

static void code_hook(uc_engine *uc, uint64_t addr, uint32_t size, void *)
{
  uint32_t idx = addr - ADDR;
  printf("Instruction 0x%X at index %d with size: %d\n", code[idx], idx, size);
}

int main()
{
  uc_engine *uc;
  uc_hook uh_trap;
  uc_open(UC_ARCH_X86, UC_MODE_32, &uc);
  uc_mem_map(uc, ADDR, 2*1024*1024, UC_PROT_ALL);
  uc_mem_write(uc, ADDR, code, CODESZ);
  uc_hook_add(uc, &uh_trap, UC_HOOK_CODE, code_hook, NULL, ADDR, 0);
  uc_emu_start(uc, ADDR, ADDR+CODESZ, 0, 0);
  uc_close(uc);
  return 0;
}

Output:

Instruction 0xB8 at index 0 with size: 5
Instruction 0x0 at index 5 with size: 6


―

**Comment by V-Lor** [comment]
This is just a demonstration, in a real situation all 32-bit registers are used, including the 8 and 16-bit parts.

**Comment by wtdcode** [comment]
> This is just a demonstration, in a real situation all 32-bit registers are used, including the 8 and 16-bit parts.

But you assemble the instruction in a wrong mode. For example:

```
In [3]: from keystone import *

In [4]: ks = Ks(KS_ARCH_X86, KS_MODE_32)

In [5]: bs, _ = ks.asm("mov ax, 1")

In [6]: list(map(hex, bs))
Out[6]: ['0x66', '0xb8', '0x1', '0x0']

In [7]:
```

**Comment by V-Lor** [comment]
I used NASM with the `-fbin` flag. It looks like it has a different behavior. It inserts 0x66 before the 32-bit move, not 16. I tried the `-felf32` flag and it assembled the code as in your example. Sorry to waste your time.
