### ISSUE TITLE
Is UC_MODE_V8 supporting in the plan?

### ISSUE THREAD

**Issue by maiyao1988** [unicorn-engine/unicorn#1455]
when I used 1.0.3 to simulate android10 libc.so, I found some new instruction  like this
LDAEXD.W        R1, [R0]

I found this instruction is new instruction on armv8 t32/a32, and unicorn will return UC_ERR_INSN_INVALID

UC_MODE_V8 is still marked as not support on unicorn 2.0

I think qemu used by uc2.0 has supported armv8 a32 t32

Is this mode supporting in the plan?

**Comment by FatsharkGo** [comment]
Any updates about this issue?
More and more apps are aarch64 only, please help!

**Comment by wtdcode** [comment]
> Any updates about this issue? More and more apps are aarch64 only, please help!

Sorry I'm slightly busy these days and I would take a look this weekend if possible.

**Comment by wtdcode** [comment]
In the last release, there is a feature to switch Unicorn CPU model. I checked the qemu code and the only CPU model that supports v8 instruction is `UC_CPU_ARM_CORTEX_M33`. See [here](https://github.com/unicorn-engine/unicorn/commit/5b3a9e1024f08f24c6ef4a0e11c7a7a495a32826#diff-b1dab5e34001e4643d754694930562a45821b8bcc8fda0a72720c06d1c5d032fR352) for an example how to use it.

For details, see 5b3a9e1024f08f24c6ef4a0e11c7a7a495a32826
