### ISSUE TITLE
Errors - Native build on Windows, with MSVC

### ISSUE THREAD

**Issue by NaLanXiaoD** [unicorn-engine/unicorn#1456]
unicorn-dev\qemu\target\arm\sve_helper.c(2200) : fatal error C1001: An internal error occurred in the compiler

when I comment out "d[0] = nn;" in "void HELPER(sve_punpk_p)(void *vd, void *vn, uint32_t pred_desc)", it works well.

visual studio community 2017 
cmake-3.21.3

Thanks for replying

**Comment by wtdcode** [comment]
> fatal error C1001: An internal error occurred in the compiler

Obviously, it's a bug of MSVC. You may report it to Microsoft.
