### ISSUE TITLE
Error when building dev version: `No such file or directory include/unicorn`

### ISSUE THREAD

**Issue by DUOLabs333** [unicorn-engine/unicorn#1466]
I'm trying to build the dev version of unicorn, but it fails with: `error: [Errno 2] No such file or directory: '/tmp/pip-req-build-ks84cm5d/../../include/unicorn`

**Comment by DUOLabs333** [comment]
I then tried to use `python setup.py install --prefix /home/system/.local`, but that failed with `error: [Errno 2] No such file or directory: '/home/system/Downloads/unicorn-2.0.0rc3/../../include/unicorn'`

**Comment by DirectorX** [comment]
@DUOLabs333 why did you closed the issue?

I can confirm this issue still relevant.

**Comment by wtdcode** [comment]
> @DUOLabs333 why did you closed the issue?
> 
> I can confirm this issue still relevant.

Hello, how to reproduce?

**Comment by DirectorX** [comment]
I got brand a new MacBook and as I set it up I tried to install [pwntools](https://github.com/Gallopsled/pwntools) from pip using python(3.9.9 from homebrew), unicorn is dependency of pwntools.

you should see `No such file or directory include/unicorn` error

**Comment by wtdcode** [comment]
> I got brand a new MacBook and as I set it up I tried to install [pwntools](https://github.com/Gallopsled/pwntools) from pip using python(3.9.9 from homebrew), unicorn is dependency of pwntools.
> 
> you should see `No such file or directory include/unicorn` error

Pwntools still depends on Unicorn1 which doesn't have M1 support. For Unicorn2 (dev branch), you could build it by cmake but there isn't precompiled binary yet.
