### ISSUE TITLE
Unicorn2 arm64 crashing in gt_cntfrq_period_ns(ARMCPU *cpu)

### ISSUE THREAD

**Issue by RomainQuidet** [unicorn-engine/unicorn#1471]
Trying the new Unicorn2 C lib with arm64 target, I've got a crash in the call to qemu code

`unsigned int gt_cntfrq_period_ns(ARMCPU *cpu)`

because cpu->gt_cntfrq_hz has never been initialized (division by 0).

I see a lot of timers from qemu have been commented out in unicorn, maybe a little bit too much!

**Comment by wtdcode** [comment]
This is fixed in a recent commit: cddc9cf2ede8d6c388e85c3828aec8a3004cfdb0

**Comment by RomainQuidet** [comment]
Thanks! Tested and working :)
