### ISSUE TITLE
hook_code added inside hook_block callback is skipped

### ISSUE THREAD

**Issue by P1224** [unicorn-engine/unicorn#1475]
Add a UC_HOOK_CODE hook in UC_HOOK_CODE callback for current block, the first callback is skipped.

```

from unicorn import *
from keystone import *

ADDR = 0x1000
code = '''
nop
//jmp loc_1
loc_1:
nop
mov ecx, 2
nop
loc_2:
nop
mov eax, 0xaaaaaaaa
nop
loop loc_2
nop
hlt
'''

ks = Ks(KS_ARCH_X86, KS_MODE_32)
raw, _ = ks.asm(code, ADDR)
raw = bytes(raw)
print(raw.hex())

addr1 = raw.find(b'\xb8\xaa\xaa\xaa\xaa') + ADDR

uc = Uc(UC_ARCH_X86, UC_MODE_32)
uc.mem_map(ADDR, 0x1000)
uc.mem_write(ADDR, raw)

def hook_code(uc:Uc, addr, size, data):
    print('hook code')

def hook_block(uc:Uc, addr, size, data):
    if addr == ADDR:
        uc.hook_add(UC_HOOK_CODE, hook_code, None, addr1, addr1)

uc.hook_add(UC_HOOK_BLOCK, hook_block)

uc.emu_start(ADDR, 0)

```

Expect to print two "hook code" but only get one.

If add a `jmp $+2` to seperate the basic block, the output will be correct.

Reproduced in latest dev branch.

**Comment by wtdcode** [comment]
For HOOK_BLOCK you have to know, the "Block" here is not the real basic blocks we refer to in normal program analysis. Besides, afaik, adding hooks during emulation is not well supported so far for both uc1 and uc2.
