### ISSUE TITLE
RISC-V Control Status Registers

### ISSUE THREAD

**Issue by QDucasse** [unicorn-engine/unicorn#1478]
Hello,
The different RISC-V Control Status Registers (https://five-embeddev.com/quickref/csrs.html) are not exposed through Unicorn. Exposing them would simplify the access and setup of a simulated RISC-V processor.

**Comment by wtdcode** [comment]
Done in https://github.com/qilingframework/qnicorn/commit/24b7d9357f0467fca8d58f3a4b8c48040faadee5

**Comment by wtdcode** [comment]
Fixed in c6fdbb373506adc3c725c4e97f93c6953e53aca3

**Comment by shinkarom** [comment]
This added allocated CSRs, but how to use unallocated registers? There are little less than 4096 of them.
