### ISSUE TITLE
How does one handle syscalls when using Unicorn?

### ISSUE THREAD

**Issue by jt0dd** [unicorn-engine/unicorn#1479]
I'm interested in using it to develop some automated analysis of x86 malware, but it just dawned on me that since this isn't fully emulating an OS, I need to facilitate system calls somehow. This is basically just a naïve question along the lines of "Am I doing this right guys??"

The way I'm imagining I would approach this is apply a hook to every 0x80 interrupt and read the value of `EAX`. Example:

    mov	eax,1		; system call number (sys_exit)
    int	0x80		; call kernel

Then in the context of a sandboxed process ([Windows' new-ish Sandbox feature](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview) is looking nice for this purpose) I make that system call, see what registers / memory ranges change, and pass those values back to my emulation process and write them in. Sounds a bit easier said than done, but at least that's my idea of how to get started.

Is this completely off-base or on the right track? And anyone have advice or pitfalls to recommend I look out for beyond just handling system calls?

**Comment by wtdcode** [comment]
https://github.com/unicorn-engine/unicorn/wiki/FAQ#i-get-an-unhandled-cpu-exception-why

**Comment by jt0dd** [comment]
@wtdcode Thanks Qiling might be just the trick. I just hope it has the same granular control that Unicorn does.
