### ISSUE TITLE
Unicorn 2.0.0-rc4 not working in macosx ?

### ISSUE THREAD

**Issue by vforkliu** [unicorn-engine/unicorn#1488]
- Code
code path : samples/sample_arm.c
- Output
```shell
zsh: segmentation fault  ./sample_arm
```
- Reason
enable HAVE_PTHREAD_JIT_PROTECT on MacOSX
2.0.0-rc4/qemu/accel/tcg/translate-all.c line 1556
```c
tb_exec_unlock(false);
```
should
```c
tb_exec_unlock(tcg_ctx);
```

**Comment by wtdcode** [comment]
Are you working on an M1 machine? We have CI for macOS and that shouldn’t happen.

**Comment by vforkliu** [comment]
> Are you working on an M1 machine? We have CI for macOS and that shouldn’t happen.
macOS Monterey 12.0.1
MacBook Pro (13-inch, 2019, Two Thunderbolt 3 ports)
1.7 GHz Quad-Core Intel Core i7
Intel Iris Plus Graphics 645 1536 MB
Xcode Version 13.1 (13A1030d)

**Comment by wtdcode** [comment]
Yes, you are right and I pushed a fix.
