### ISSUE TITLE
Add custom CSR registers in RISCV

### ISSUE THREAD

**Issue by cla7aye15I4nd** [unicorn-engine/unicorn#1489]
In the current version, the following commands will be recognized as illegal instruction. Because they are not defined in default csr, but sometimes we need to custom some new csr registers and access behaviors, may be UC_CSR_READ_HOOK, UC_CSR_WRITE_HOOK will be useful. 
```
73 a0 02 7d csrs 2000, t0 
73 90 72 30 csrw 775, t0 
73 90 c2 7e csrw 2028, t0 
73 e0 c0 7e csrsi 2028, 1
```
In order to implement csr hook, I guess we can add an interface for modifying csr_ops in 
https://github.com/unicorn-engine/unicorn/blob/dev/qemu/target/riscv/csr.c#L151
```c
static riscv_csr_operations csr_ops[CSR_TABLE_SIZE] = {
    /* User Floating-Point CSRs */
    [CSR_FFLAGS] =              { fs,   read_fflags,      write_fflags      },
    [CSR_FRM] =                 { fs,   read_frm,         write_frm         },
    [CSR_FCSR] =                { fs,   read_fcsr,        write_fcsr        },

    /* User Timers and Counters */
    [CSR_CYCLE] =               { ctr,  read_instret                        },
```

**Comment by wtdcode** [comment]
The QEMU upstream has several ongoing PRs about custom CSR: https://patchew.org/search?q=custom+CSR which haven't been merged into the mainline yet. I suggest you implementing custom CSR by mmio regions.

We may backport such patches in later releases, but for now, we have nothing more to do.
