### ISSUE TITLE
unicorn 2.0.0 rc4: fails to install shared libraries 

### ISSUE THREAD

**Issue by blshkv** [unicorn-engine/unicorn#1490]
Hi, I'm trying to compile unicorn for 1 target only ```x86```, but it fails similarly with all targets enabled by default:
```
   /usr/lib64/libunicorn.so.2
 * QA Notice: Unresolved soname dependencies:
 * 
 *      /usr/lib64/libunicorn.so.2: libmips-softmmu.so libmips64-softmmu.so libmips64el-softmmu.so libmipsel-softmmu.so libunicorn-common.so libx86_64-softmmu.so

```

here is output of configuration stage:
```
 * Source directory (CMAKE_USE_DIR): "/var/tmp/portage/dev-util/unicorn-2.0.0_rc4/work/unicorn-2.0.0-rc4"
 * Build directory  (BUILD_DIR):     "/var/tmp/portage/dev-util/unicorn-2.0.0_rc4/work/unicorn-2.0.0_rc4_build"
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-util/unicorn-2.0.0_rc4/work/unicorn-2.0.0-rc4 ...
 * Source directory (CMAKE_USE_DIR): "/var/tmp/portage/dev-util/unicorn-2.0.0_rc4/work/unicorn-2.0.0-rc4"
 * Build directory  (BUILD_DIR):     "/var/tmp/portage/dev-util/unicorn-2.0.0_rc4/work/unicorn-2.0.0_rc4_build"
cmake -C /var/tmp/portage/dev-util/unicorn-2.0.0_rc4/work/unicorn-2.0.0_rc4_build/gentoo_common_config.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DUNICORN_BUILD_SHARED=ON -DUNICORN_ARCH=x86  -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/dev-util/unicorn-2.0.0_rc4/work/unicorn-2.0.0_rc4_build/gentoo_toolchain.cmake  /var/tmp/portage/dev-util/unicorn-2.0.0_rc4/work/unicorn-2.0.0-rc4
loading initial cache file /var/tmp/portage/dev-util/unicorn-2.0.0_rc4/work/unicorn-2.0.0_rc4_build/gentoo_common_config.cmake
-- The C compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
Install prefix    /usr/local
binary directory  /usr/local/bin
library directory /usr/local/lib
libexec directory /usr/local/libexec
include directory /usr/local/include
config directory  /usr/local/etc
local state directory   /usr/local/var
ELF interp prefix /usr/gnemul/qemu-%M
Build directory   /var/tmp/portage/dev-util/unicorn-2.0.0_rc4/work/unicorn-2.0.0_rc4_build
Source path       /var/tmp/portage/dev-util/unicorn-2.0.0_rc4/work/unicorn-2.0.0-rc4/qemu
GIT binary        git
GIT submodules    
C compiler        /usr/bin/x86_64-pc-linux-gnu-gcc
Host C compiler   cc
C++ compiler      c++
Objective-C compiler /usr/bin/x86_64-pc-linux-gnu-gcc
ARFLAGS           rv
CFLAGS            -g -march=native -O2 -pipe
QEMU_CFLAGS       -fPIE -DPIE -m64 -mcx16 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -Wstrict-prototypes -Wredundant-decls -Wall -Wundef -Wwrite-strings -Wmissing-prototypes -fno-strict-aliasing -fno-common -fwrapv -std=gnu99  -DUNICORN_HAS_X86 -fPIC -Wexpansion-to-defined -Wendif-labels -Wno-shift-negative-value -Wno-missing-include-dirs -Wempty-body -Wnested-externs -Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers -Wold-style-declaration -Wold-style-definition -Wtype-limits -fstack-protector-strong
QEMU_LDFLAGS      -Wl,--warn-common -Wl,-z,relro -Wl,-z,now -pie -m64  -DUNICORN_HAS_X86 -fPIC -fstack-protector-strong
make              make
install           install
host CPU          x86_64
host big endian   no
target list       x86_64-softmmu   
strip binaries    yes
static build      no
mingw32 support   no
PIE               yes
TCG support       yes
malloc trim support yes
membarrier        no
madvise           yes
posix_madvise     yes
posix_memalign    yes
debug stack usage no
tcmalloc support  no
jemalloc support  no
avx2 optimization yes
avx512f optimization no
-- <<< Gentoo configuration >>>
Build type      Gentoo
Install path    /usr
Compiler flags:
C               -march=native -O2 -pipe
C++             
Linker flags:
Executable      -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0 -m64
Module          -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0
Shared          -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0 -m64

```

LDD shows the following output:
```
/usr/lib64/ $ ldd libunicorn.so.2 
        linux-vdso.so.1 (0x00007ffdb92e0000)
        libx86_64-softmmu.so => not found
        libmips-softmmu.so => not found
        libmipsel-softmmu.so => not found
        libmips64-softmmu.so => not found
        libmips64el-softmmu.so => not found
        libunicorn-common.so => not found
        libc.so.6 => /lib64/libc.so.6 (0x00007f9118206000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f91183f2000)

```

LS output:
```
/usr/lib64/ $ ls
libunicorn.so  libunicorn.so.2  pkgconfig

```

These missing libraries are compiled in the cmake build directory, but not getting installed properly

**Comment by wtdcode** [comment]
Hello, thanks for your issue. Looks like something goes wrong with our cmake script. I would have a look ASAP.

**Comment by wtdcode** [comment]
Hello, `lib*-softmmu.so` would only be built as static binaries. Do you compile Unicorn correctly?

**Comment by blshkv** [comment]
the compilation works fine, it's the install phase when it goes wrong.
Run the following:
cmake --install . --prefix "/tmp/unicorn"
```
-- Install configuration: "Gentoo"
-- Installing: /tmp/unicorn/lib64/libunicorn.so.2
-- Set runtime path of "/tmp/unicorn/lib64/libunicorn.so.2" to ""
-- Installing: /tmp/unicorn/lib64/libunicorn.so
-- Installing: /tmp/unicorn/include/unicorn/arm.h
-- Installing: /tmp/unicorn/include/unicorn/arm64.h
-- Installing: /tmp/unicorn/include/unicorn/m68k.h
-- Installing: /tmp/unicorn/include/unicorn/mips.h
-- Installing: /tmp/unicorn/include/unicorn/platform.h
-- Installing: /tmp/unicorn/include/unicorn/ppc.h
-- Installing: /tmp/unicorn/include/unicorn/riscv.h
-- Installing: /tmp/unicorn/include/unicorn/sparc.h
-- Installing: /tmp/unicorn/include/unicorn/unicorn.h
-- Installing: /tmp/unicorn/include/unicorn/x86.h
-- Installing: /tmp/unicorn/lib64/pkgconfig/unicorn.pc
```

**Comment by wtdcode** [comment]
> the compilation works fine, it's the install phase when it goes wrong. Run the following: bash$ cmake --install . --prefix "/tmp/unicorn"
> 
> ```
> -- Install configuration: "Gentoo"
> -- Installing: /tmp/unicorn/lib64/libunicorn.so.2
> -- Set runtime path of "/tmp/unicorn/lib64/libunicorn.so.2" to ""
> -- Installing: /tmp/unicorn/lib64/libunicorn.so
> -- Installing: /tmp/unicorn/include/unicorn/arm.h
> -- Installing: /tmp/unicorn/include/unicorn/arm64.h
> -- Installing: /tmp/unicorn/include/unicorn/m68k.h
> -- Installing: /tmp/unicorn/include/unicorn/mips.h
> -- Installing: /tmp/unicorn/include/unicorn/platform.h
> -- Installing: /tmp/unicorn/include/unicorn/ppc.h
> -- Installing: /tmp/unicorn/include/unicorn/riscv.h
> -- Installing: /tmp/unicorn/include/unicorn/sparc.h
> -- Installing: /tmp/unicorn/include/unicorn/unicorn.h
> -- Installing: /tmp/unicorn/include/unicorn/x86.h
> -- Installing: /tmp/unicorn/lib64/pkgconfig/unicorn.pc
> ```
> 
> and then: bash$ ldd /tmp/unicorn/lib64/libunicorn.so.2
> 
> ```
>         linux-vdso.so.1 (0x00007ffc2e3db000)
>         libx86_64-softmmu.so => not found
>         libunicorn-common.so => not found
>         libc.so.6 => /lib64/libc.so.6 (0x00007f7260239000)
>         /lib64/ld-linux-x86-64.so.2 (0x00007f7260423000)
> ```
> 
> The full log is here: https://pastebin.com/qhk0Nt6R

I mean, what’s your compilation flags or how to reproduce it? If you compile Unciorn correctly, there would be only lib*-softmmu.a instead of lib*-softmmu.so. You probably mess up with LDFLAGS.

**Comment by blshkv** [comment]
Run cmake to compile with any flags first, just make sure that shared library option is enabled. And then, run cmake install command above.

**Comment by blshkv** [comment]
this is a compilation log with ``` -DUNICORN_BUILD_SHARED=ON ```
https://pastebin.com/grmbk3tJ

**Comment by wtdcode** [comment]
> Run cmake to compile with any flags first, just make sure that shared library (UNICORN_BUILD_SHARED=yes) option is enabled. And then, run cmake install command above.
> 
> EDIT: `lib*-softmmu.a` are static libraries, it works fine. This bug report is about the problem with shared libraries. FYI, there is no issue with unicorn-1.0.3 _if_ you use make (Makefile) instead of cmake (CMakeLists.txt). But Makefile was removed recently, thus this issue.

It doesn’t matter how UNICORN_BUILD_SHARED, which means lib*-softmmu would only built as __static__ libraries in all cases.

**Comment by blshkv** [comment]
ok, the problem is exactly like that:
https://github.com/boatbod/op25/issues/47
