### ISSUE TITLE
Feature request: SuperH support

### ISSUE THREAD

**Issue by Heath123** [unicorn-engine/unicorn#1491]
This doesn't seem to support the [SuperH](https://en.wikipedia.org/wiki/SuperH) architecture, but QEMU [seems to support it](https://wiki.qemu.org/Documentation/Platforms/SH4). This is probably really niche though

**Comment by wtdcode** [comment]
Hello, thanks for your interest. Currently, I don't have too much time working on that sorry.

**Comment by mid-kid** [comment]
I encountered this architecture debugging an ancient artifact of Nintendo history, the Mobile Adapter GB. While I ended up writing my own simple CPU emulator, I would've appreciated this existing, and I reckon others would as well.

Please consider re-opening this issue.
