### ISSUE TITLE
Unicorn 2.0.0rc4 x86 registers definitions are misaligned with Capstone 4.0.2

### ISSUE THREAD

**Issue by elicn** [unicorn-engine/unicorn#1492]
It looks like the registers reduction mentioned in #1440 made it to Unicorn 2.0.0rc4 (except the FP registers).
Unfortunately that resulted in a misalignment between Capstone and Unicorn x86 registers enumeration, that were aligned to that point. Now Capstone and Unicorn definitions for x86 registers cannot be used interchangebly, which makes them difficult to use together.

Note: probably the best way to re-align the deinfitions would be having Capstone reduct the same non-existing registers, but I don't know if Capstone is still actively maintained.

**Comment by aquynh** [comment]
we can make similar change for Capstone 5.

**Comment by kabeor** [comment]
@elicn Capstone is still actively maintained. 
Looks like we just need remove X86_REG_EIZ and X86_REG_RIZ from Capstone refer to https://github.com/unicorn-engine/unicorn/commit/46e8ac03ad5d17083cc9041cf8007cde3c7d3a9d ?

**Comment by elicn** [comment]
> @elicn Capstone is still actively maintained. 
> Looks like we just need remove X86_REG_EIZ and X86_REG_RIZ from Capstone refer to https://github.com/unicorn-engine/unicorn/commit/46e8ac03ad5d17083cc9041cf8007cde3c7d3a9d ?

Good to know..!
There are more registers that got reducted. See the reference in my message above.

**Comment by wtdcode** [comment]
Keep it alive until cs5 is released.

**Comment by elicn** [comment]
According to the discussion with had on #1440, I believe Capstone should keep these non-existing [yet encode-able] registers to be able to disassemble instructions that use them. Consider aligning the definitions values instead (i.e. skip values that appear in Capstone but not in Unicorn, so the registers definitions that exist on both would match).

**Comment by iii-i** [comment]
This might be a non-goal for the Unicorn2 project, but so far I've been able to use the Unicorn2 shared library as a drop-in replacement of the Unicorn1 shared library. With `X86_REG_EIZ` gone, it's no longer possible.

Currently this seems to be the only thing that block this use case, even though in the future the projects may drift further apart.

But just to simplify migration in the short term, would it be possible to introduce "holes" where the removed registers used to be?

**Comment by wtdcode** [comment]
Closed due to PR merged.
