### ISSUE TITLE
Arm SVC call getting wrong PC

### ISSUE THREAD

**Issue by yuppox** [unicorn-engine/unicorn#1493]
I'm using the latest Unicorn (1.0.3), emulating arm.

I have a short program that uses two syscalls (svc). Using C, my `UC_HOOK_INTR` hook is getting the PC after the syscall, not during.

```
uc_hook_add(uc, &trace2, UC_HOOK_INTR, hook_code, NULL, 1, 0);
```

After looking at #980, this seems to be a bug.

I'm running `sample_asm.c` with the following arm code (32 bytes):

```
0x01, 0x00, 0xa0, 0xe3,
0x10, 0x10, 0x8f, 0xe2,
0x05, 0x20, 0xa0, 0xe3,
0x04, 0x70, 0xa0, 0xe3,
0x00, 0x00, 0x00, 0xef,
0x01, 0x70, 0xa0, 0xe3,
0x00, 0x00, 0x00, 0xef,
0x48, 0x69, 0x0a, 0x00
```

Lines 5, 7 are syscalls.

**Comment by wtdcode** [comment]
Could you try Unicorn2 at our dev branch?

**Comment by yuppox** [comment]
> Could you try Unicorn2 at our dev branch?

I'm looking at the dev branch. I don't see an .SLN for MSVC. That's expected?

**Comment by wtdcode** [comment]
> > Could you try Unicorn2 at our dev branch?
> 
> I'm looking at the dev branch. I don't see an .SLN for MSVC. That's expected?

Yes, you see docs/COMPILE.md for details.
