### ISSUE TITLE
`uc_mem_unmap` fails to split regions that have been mapped with `uc_mmio_map`

### ISSUE THREAD

**Issue by Kritzefitz** [unicorn-engine/unicorn#1497]
I'm not sure if this is a bug or just not supported, but I have not found any explicit documentation mentioning that this explicitly isn't supported.

This test case fails when run on 3627db5b83a753f34e364dff68f28040cb29363b:

```C
static void text_x86_splitting_mmio_unmap()
{
  uc_engine *uc;

  OK(uc_open(UC_ARCH_X86, UC_MODE_32, &uc));

  OK(uc_mmio_map(uc, 0x3000, 0x2000, NULL, NULL, NULL, NULL));

  OK(uc_mem_unmap(uc, 0x3000, 0x1000));

  OK(uc_close(uc));
}
```

This fails with the following error message:

```
Test text_x86_splitting_mmio_unmap...           [ FAILED ]
  test_x86.c:871: Check __err == UC_ERR_OK... failed
    No memory available or memory not present (UC_ERR_NOMEM)
```

This looks similar to #1495, but since the failure doesn't depend on the existence of an adjacent region I assume it is a separate issue.

I'm not sure if there are actual use cases for unmapping only part of an MMIO region, but I think if this is not supported, it should be mentioned somewhere in the header file.

**Comment by wtdcode** [comment]
Fixed in 78e0ddbc4d281761c7a7010a7ebf2a2dfc272f8f
