### ISSUE TITLE
arm p15 mrc error

### ISSUE THREAD

**Issue by yimingqpa** [unicorn-engine/unicorn#1503]
3C200B80 10 0F 11 EE MRC	P15, #0, R0, C1, C0, #0
3C200B84 02 14 A0 E3 MOV	R1, #0X2000000
3C200B88 01 00 80 E1  ORR	R0, R0, R1
3C200B8C  4F F0 7F F5 DSB	SY
3C200B90 10 0F 01 EE MCR	P15, #0, R0, C1, C0, #0
3C200B94 6F F0 7F F5 ISB	SY
3C200B98 11 0F 11 EE MRC	P15, #0, R0, C1, C1, #0

R0: 0x02C50078
R1: 0x02000000

3C200B98 Simulation error

**Comment by wtdcode** [comment]
Hello, could you provide a reproduction script?

**Comment by yimingqpa** [comment]
#define ARM_CODE_MRC                                                           \
    "\x10\x0F\x11\xEE\x02\x14\xA0\xE3\x01\x00\x80\xE1\x4F\xF0\x7F\xF5\x10\x0F" \
    "\x01\xEE\x6F\xF0\x7F\xF5\x11\x0F\x11\xEE"

static void test_arm_mrc(void)
{
    uc_engine *uc;
    uc_err err;
    uc_hook trace1, trace2;

    int r0 = 0; // R0 register
    int r2 = 0; // R1 register
    int r3 = 0; // R2 register
    int r1 = 0; // R1 register

    printf("Emulate ARM code mrc p15\n");

    // Initialize emulator in ARM mode
    err = uc_open(UC_ARCH_ARM, UC_MODE_ARM, &uc);
    if (err) {
        printf("Failed on uc_open() with error returned: %u (%s)\n", err,
               uc_strerror(err));
        return;
    }

    // map 2MB memory for this emulation
    uc_mem_map(uc, ADDRESS, 2 * 1024 * 1024, UC_PROT_ALL);

    // write machine code to be emulated to memory
    uc_mem_write(uc, ADDRESS, ARM_CODE_MRC, sizeof(ARM_CODE_MRC) - 1);

    // initialize machine registers
    uc_reg_write(uc, UC_ARM_REG_R0, &r0);
    uc_reg_write(uc, UC_ARM_REG_R2, &r2);
    uc_reg_write(uc, UC_ARM_REG_R3, &r3);

    // tracing all basic blocks with customized callback
    uc_hook_add(uc, &trace1, UC_HOOK_BLOCK, hook_block, NULL, 1, 0);

    // tracing one instruction at ADDRESS with customized callback
    uc_hook_add(uc, &trace2, UC_HOOK_CODE, hook_code, NULL, ADDRESS, ADDRESS);

    // emulate machine code in infinite time (last param = 0), or when
    // finishing all the code.
    err = uc_emu_start(uc, ADDRESS, ADDRESS + sizeof(ARM_CODE_MRC) - 1, 0, 0);
    if (err) {
        printf("Failed on uc_emu_start() with error returned: %u\n", err);
    }

    // now print out some registers
    printf(">>> Emulation done. Below is the CPU context\n");

    uc_reg_read(uc, UC_ARM_REG_R0, &r0);
    uc_reg_read(uc, UC_ARM_REG_R1, &r1);
    printf(">>> R0 = 0x%x\n", r0);
    printf(">>> R1 = 0x%x\n", r1);

    uc_close(uc);
}

uc_emu_start
Quit emulation due to invalid instruction

**Comment by wtdcode** [comment]
Fixed in 8ad9f8ecb1cbed9f1e5e451970f885b4b457c5bf.

Sorry for the long wait.
