### ISSUE TITLE
My program raise Unhandled CPU exception when i use uc->reg_write() to set segment: FS GS

### ISSUE THREAD

**Issue by LakerMoon** [unicorn-engine/unicorn#1505]
My error:

  File "C:/Users/yue_hu/Downloads/x86-64-pe-emu-master/x86-64-pe-emu-master/runpe.py", line 334, in runpe
    uc.reg_write(UC_X86_REG_FS, GDT_FS_IDX << 3)
  File "C:\Python27\lib\site-packages\unicorn\unicorn.py", line 448, in reg_write
    raise UcError(status)
unicorn.unicorn.UcError: Unhandled CPU exception (UC_ERR_EXCEPTION)

               
In Func:uc_check_cpu_x86_load_seg()，in unicorn.c:
                     
                      case UC_X86_REG_FS:
                        ret = **uc_check_cpu_x86_load_seg**(&X86_CPU(uc, mycpu)->env, R_FS, *(uint16_t*)value);
                        if (ret) {
                            return ret;
                        }
                        cpu_x86_load_seg(&X86_CPU(uc, mycpu)->env, R_FS, *(uint16_t *)value);
                        break;
                    case UC_X86_REG_GS:
                             ret = **uc_check_cpu_x86_load_seg**(&X86_CPU(uc, mycpu)->env, R_GS, *(uint16_t*)value);
                        if (ret) {
                            return ret;
                        }            
                        cpu_x86_load_seg(&X86_CPU(uc, mycpu)->env, R_GS, *(uint16_t *)value);
                        break;
                        

int uc_check_cpu_x86_load_seg(CPUX86State *env, int seg_reg, int sel)
{
    int selector;
    uint32_t e2;
    int cpl, dpl, rpl;
    SegmentCache *dt;
    int index;
    target_ulong ptr;
    printf("seg_reg:%d\nsel:%d\n", seg_reg, sel);
    if (!(env->cr[0] & CR0_PE_MASK) || (env->eflags & VM_MASK)) {
        return 0;
    } else {
        selector = sel & 0xffff;
        printf("selector:%d\n", selector);
        cpl = env->hflags & HF_CPL_MASK;
        if ((selector & 0xfffc) == 0) {
            /* null selector case */
            if (seg_reg == R_SS
#ifdef TARGET_X86_64
                && (!(env->hflags & HF_CS64_MASK) || cpl == 3)
#endif
                ) {
                printf("11111111111111111\n");
                return UC_ERR_EXCEPTION;
            }
            return 0;
        } else {
            if (selector & 0x4) {
                dt = &env->ldt;
            } else {
                dt = &env->gdt;
            }
            index = selector & ~7;
            if ((index + 7) > dt->limit) {
                **//------------error exception occured here-----------------**
                return UC_ERR_EXCEPTION;
            }

seg_reg:4
sel:80
selector:80
index:80
(index+7):87
dt->limit:0

**Please help me check if the arguments wrong.**

**Comment by wtdcode** [comment]
Hello, how to reproduce?

**Comment by LakerMoon** [comment]
> Hello, how to reproduce?

I download and run this prgoram
https://github.com/asamy/x86-64-pe-emu

in cmd: python runpe.py --file ....

**Comment by wtdcode** [comment]
> > Hello, how to reproduce?
> 
> I download and run this prgoram https://github.com/asamy/x86-64-pe-emu
> 
> in cmd: python runpe.py --file ....

If so, please go to https://github.com/asamy/x86-64-pe-emu/issues for an issue or write a minimal bug reproduction script. We are no responsible for other projects’ bugs.

**Comment by LakerMoon** [comment]
> > > Hello, how to reproduce?
> > 
> > 
> > I download and run this prgoram https://github.com/asamy/x86-64-pe-emu
> > in cmd: python runpe.py --file ....
> 
> If so, please go to https://github.com/asamy/x86-64-pe-emu/issues for an issue or write a minimal bug reproduction script. We are not responsible for other projects’ bugs.

i just ask some arguments about checking before laod_seg.If it’s not right, what’s the problem with these data compared to normal?

**Comment by wtdcode** [comment]
load_seg is not a function provided by Unicorn and thus we don’t know how it is implemented. If hou believe it’s a bug related to Unicorn, please write a minimal reproduction script.
________________________________

**Comment by redthing1** [comment]
@LakerMoon did you ever find a fix? Same issue.
