### ISSUE TITLE
error while loading shared libraries: libunicorn.so.2

### ISSUE THREAD

**Issue by RickyCong** [unicorn-engine/unicorn#1510]
I compile unicorn 'dev' branch, running the GO language results in the following error

![](https://user-images.githubusercontent.com/46929436/144956500-644ae95a-2e81-42cc-ab16-f9ae1b94550f.png)

**Comment by wtdcode** [comment]
Sorry for my late reply. Could you post more detailed reproduction steps?

**Comment by RickyCong** [comment]
First I downloaded the code locally
`git clone -b dev https://github.com/unicorn-engine/unicorn.git`
After compiling the code according to the documentation
https://github.com/unicorn-engine/unicorn/blob/dev/docs/COMPILE.md

Finally, I can't run the Go code in bindings.


After that, I found a solution, which is to run the commands in the script.
But the files compiled by this method are all in the root directory
https://github.com/unicorn-engine/unicorn/blob/dev/.github/workflows/Crate-publishing.yml

**Comment by wtdcode** [comment]
Hello, I'm afraid you have to install unicorn globally in this case.
