### ISSUE TITLE
Unicorn2 ARM64 activate PSTATE reg

### ISSUE THREAD

**Issue by blacktop** [unicorn-engine/unicorn#1523]
I apologize as this is probably a pretty dumb question, but is there something I need to do to get the PSTATE reg to work?

In my emulation I am seeing it always be `0x400003c5` shouldn't it have bits for `BranchType` etc?

**Comment by wtdcode** [comment]
I'm not too familiar with ARM. I would appreciate it if you could give more context.

I suspect it's related to #1520

**Comment by wtdcode** [comment]
I believe it should be fixed in 8ad9f8ecb1cbed9f1e5e451970f885b4b457c5bf.

If not, please post a reproduction script here.

**Comment by blacktop** [comment]
Now it seems to always  be `0x400003cd`.  I wanted to parse out that reg as is was the only other reg that seemed to have info (other than the main x0-30, SP,PC etc.  However, in the ARM spec I see:
<img width="768" alt="Screen Shot 2022-01-05 at 6 47 53 PM" src="https://user-images.githubusercontent.com/6118188/148315004-4bd7d3c9-dc3d-4392-86b3-4e4a7f599af7.png">

And in your code I see:
```cpp
/* Bit definitions for ARMv8 SPSR (PSTATE) format.
 * Only these are valid when in AArch64 mode; in
 * AArch32 mode SPSRs are basically CPSR-format.
 */
#define PSTATE_SP (1U)
#define PSTATE_M (0xFU)
#define PSTATE_nRW (1U << 4)
#define PSTATE_F (1U << 6)
#define PSTATE_I (1U << 7)
#define PSTATE_A (1U << 8)
#define PSTATE_D (1U << 9)
#define PSTATE_BTYPE (3U << 10)
#define PSTATE_IL (1U << 20)
#define PSTATE_SS (1U << 21)
#define PSTATE_PAN (1U << 22)
#define PSTATE_UAO (1U << 23)
#define PSTATE_V (1U << 28)
#define PSTATE_C (1U << 29)
#define PSTATE_Z (1U << 30)
#define PSTATE_N (1U << 31)
#define PSTATE_NZCV (PSTATE_N | PSTATE_Z | PSTATE_C | PSTATE_V)
#define PSTATE_DAIF (PSTATE_D | PSTATE_A | PSTATE_I | PSTATE_F)
#define CACHED_PSTATE_BITS (PSTATE_NZCV | PSTATE_DAIF | PSTATE_BTYPE)
/* Mode values for AArch64 */
#define PSTATE_MODE_EL3h 13
#define PSTATE_MODE_EL3t 12
#define PSTATE_MODE_EL2h 9
#define PSTATE_MODE_EL2t 8
#define PSTATE_MODE_EL1h 5
#define PSTATE_MODE_EL1t 4
#define PSTATE_MODE_EL0t 0
```

In the ARM spec I also see:
<img width="922" alt="Screen Shot 2022-01-05 at 6 50 51 PM" src="https://user-images.githubusercontent.com/6118188/148315276-4950d361-8bcd-4aeb-b59d-0dfa6bad3507.png">
<img width="553" alt="Screen Shot 2022-01-05 at 6 51 32 PM" src="https://user-images.githubusercontent.com/6118188/148315293-034b0866-14d1-4a92-a37c-36ecc4277afd.png">

So I thought I'd see that BTYPE field change around branch instructions (but maybe that field is only enabled if BTI is active?  However, I thought CPU_MAX enabled the BTI feature here:

`qemu/target/arm/cpu64.c#255`
```cpp
    t = cpu->isar.id_aa64pfr1;
    FIELD_DP64(t, ID_AA64PFR1, BT, 1, t);
    cpu->isar.id_aa64pfr1 = t;
```

**Comment by blacktop** [comment]
So based on your PSTATE flags DAIF is always set?

**Comment by blacktop** [comment]
And does the 0xD mean the MODE is `#define PSTATE_MODE_EL3h 13` ?

**Comment by blacktop** [comment]
I also see that `#define CACHED_PSTATE_BITS (PSTATE_NZCV | PSTATE_DAIF | PSTATE_BTYPE)` so maybe that's why DAIF is always set because it's cached?

**Comment by blacktop** [comment]
So I think PSTATE might be behaving properly?  Although I'm still confused why BTYPE isn't getting set?  I'll try and run a test and see if it changes, but a `braaz` instruction didn't affect it and that should have set it to 1
<img width="416" alt="Screen Shot 2022-01-05 at 7 56 24 PM" src="https://user-images.githubusercontent.com/6118188/148321054-29384e59-ddeb-46ba-b9e5-0f5f4fdf603a.png">

**Comment by blacktop** [comment]
I just tested a `blraaz` and got :
```bash
cpsr: 0x60000bcd [Z C D A I F INDCALL]
```
🥳

**Comment by blacktop** [comment]
However, a BL didn't set it to `DIRCALL` 😢

**Comment by wtdcode** [comment]
Hi, does PSATE behave correctly? If so, we can close this issue.

**Comment by blacktop** [comment]
Do you think that `PSTATE` should have had its `BTYPE` set to `DIRCALL` for the `BL` instruction?

**Comment by wtdcode** [comment]
> Do you think that `PSTATE` should have had its `BTYPE` set to `DIRCALL` for the `BL` instruction?

I'm not an arm expert. Please refer to the arm manual for details.

**Comment by blacktop** [comment]
I have supplied an excerpt from the ARM manual for the `BL` instruction above

**Comment by wtdcode** [comment]
If you think anything is unexpected, please leave a reproduction script here.
