### ISSUE TITLE
PPC Link Register. 

### ISSUE THREAD

**Issue by HorseTrain** [unicorn-engine/unicorn#1526]
How would i want to read/write the link register in a ppc context?

**Comment by wtdcode** [comment]
Sorry for my late reply. Could you give me a reference for the link register?

**Comment by HorseTrain** [comment]
Well, i want to access data to and from a (power pc 32 big endian context) link register, so if i were to execute the instruction "blr" the emulator will branch to my specified location. But i can not seem to find the enum for the register.

**Comment by wtdcode** [comment]
Fixed in 36afa1022c6cd482d7ff6e6afad800d2513e0c95
