### ISSUE TITLE
Cannot write to UC_X86_REG_FS_BASE

### ISSUE THREAD

**Issue by vancaho** [unicorn-engine/unicorn#1529]
Hi, when I simulate some instructions in x86 ,I found that I cannot write into UC_X86_REG_FS_BASE register.
Here is the example 
```
In [17]: mu = Uc(UC_ARCH_X86, UC_MODE_32)

In [18]: mu.reg_write(UC_X86_REG_FS_BASE, 0xaa)

In [19]: mu.reg_read(UC_X86_REG_FS_BASE)
```
It outputs 0 .
What is wrong?

**Comment by wtdcode** [comment]
AFAIK, there is no `fs.base` in x86-32.

**Comment by vancaho** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by vancaho** [comment]
I decompiled a 32 bit PE file, there is an instruction ```mov eax, dword ptr fs:[0x18]``` in ```kernelbase.dll```. If I want to simulate the instruction, which instructions should I set?

**Comment by wtdcode** [comment]
See sample here: https://github.com/unicorn-engine/unicorn/blob/dev/samples/sample_x86_32_gdt_and_seg_regs.c
