### ISSUE TITLE
Problem Dword ptr

### ISSUE THREAD

**Issue by nathanebar** [unicorn-engine/unicorn#1530]
Hi, 
In the code I try to emulate with Unicorn I have this instruction :  mov     ecx, dword ptr [rbp+arg_8]
Instead of load the word-size value (in my case '4') into ecx it puts the address of the value ( 0x30000)
and after that I have the instruction: add     eax, ecx
In my case eax=62 
I expected that eax=66 but because of that eax = 0x30062
I probably misunderstood something or I am missing information.
Ideas?
Thank you,
NB

**Comment by wtdcode** [comment]
We can't understand your problem exactly if you do not post a reproduction script.

**Comment by nathanebar** [comment]
[code64.zip](https://github.com/unicorn-engine/unicorn/files/7842173/code64.zip)

Here the script in python with the instructions I want to emulate
Thanks

**Comment by wtdcode** [comment]
> [code64.zip](https://github.com/unicorn-engine/unicorn/files/7842173/code64.zip)
> 
> Here the script in python with the instructions I want to emulate Thanks

The code you post seems unrelevant to your problem. Please post a **minimal** reproduction script.

**Comment by nathanebar** [comment]
my bad.
I solved the problem, it does not come from unicorn.
I closed the issues
