### ISSUE TITLE
unicorn stops emulation due to an invalid memory write, even after mapping in the target address

### ISSUE THREAD

**Issue by MellowNight** [unicorn-engine/unicorn#1532]
Unicorn stops emulation even if I map in the desired address in my UC_HOOK_MEM_WRITE_UNMAPPED hook. I use uc_mem_map_ptr to map in the write address and it returns status success. 

This is the part of code which causes unicorn to stop:

[[]()](https://github.com/unicorn-engine/unicorn/blob/master/qemu/softmmu_template.h#L826)

How can I fix this?

**Comment by wtdcode** [comment]
Please try our Unicorn2 at dev branch. If the problem still exists, I would have a further look.

**Comment by MellowNight** [comment]
> Please try our Unicorn2 at dev branch. If the problem still exists, I would have a further look.

I'm having a little trouble linking to the libraries built by Unicorn2 from the dev branch. There is no unicorn_static.lib so I tried to link to unicorn-common.lib, but I get a lot of unresolved external symbol errors. I also attempted to link to unicorn.lib but I couldn't find the unicorn DLL anywhere.

**Comment by wtdcode** [comment]
> > Please try our Unicorn2 at dev branch. If the problem still exists, I would have a further look.
> 
> I'm having a little trouble linking to the libraries built by Unicorn2 from the dev branch. There is no unicorn_static.lib so I tried to link to unicorn-common.lib, but that causes a lot of unresolved external symbol errors. I also attempted to link to unicorn.lib but I couldn't find the unicorn DLL anywhere.

You should link against `libunicorn.a`

**Comment by MellowNight** [comment]
> > > Please try our Unicorn2 at dev branch. If the problem still exists, I would have a further look.
> > 
> > 
> > I'm having a little trouble linking to the libraries built by Unicorn2 from the dev branch. There is no unicorn_static.lib so I tried to link to unicorn-common.lib, but that causes a lot of unresolved external symbol errors. I also attempted to link to unicorn.lib but I couldn't find the unicorn DLL anywhere.
> 
> You should link against `libunicorn.a`

I forgot to mention that I'm compiling on MSVC windows. I've managed to link against unicorn.dll from the dev branch dynamically, is there a way to link to unicorn2 statically?

**Comment by MellowNight** [comment]
What is happening here...

![image](https://user-images.githubusercontent.com/89277220/149462440-fc4a556e-d9e3-452b-90a0-18818171465d.png)

**Comment by MellowNight** [comment]
@wtdcode 

writing to RSP in Unicorn2 is broken:
![image](https://user-images.githubusercontent.com/89277220/149463109-fb344d49-712b-4c98-bfa3-cd96dc99fc39.png)

**Comment by wtdcode** [comment]
Please post a reproduction script for the bug.

If you use unicorn as a cmake subproject, all static libraries would be linked automatically.

**Comment by MellowNight** [comment]
> Please post a reproduction script for the bug.
> 
> If you use unicorn as a cmake subproject, all static libraries would be linked automatically.

I used cmake to generate the project files, then I compiled for Debug x64. Then I just added a few lines of code to the test_x86 project to write and then read RSP. uc_reg_read and uc_reg_write both returned UC_ERR_OK, but produced unexpected behavior.

**Comment by wtdcode** [comment]
> > Please post a reproduction script for the bug.
> > If you use unicorn as a cmake subproject, all static libraries would be linked automatically.
> 
> I used cmake to generate the MSVC project files, then I compiled for Debug x64. Next I just added a few lines of code to the test_x86 project to write and then read RSP. uc_reg_read and uc_reg_write both returned UC_ERR_OK, but reading from RSP gave me an unexpected value.
> 
> Reading to/writing from any other register works as expected.

You have to post a reproduction script for us to address the bug.

**Comment by MellowNight** [comment]
@wtdcode 

`
uc_engine *uc;
auto err = uc_open(UC_ARCH_X86, UC_MODE_64, &uc);
uintptr_t value1= 0x123456789;
uintptr_t value2;
err  = uc_reg_write(uc, UC_X86_REG_RSP, &value1);
err  = uc_reg_read(uc, UC_X86_REG_RSP, &value2);

std::cout << "value1: " << std::hex << value1 << std::endl;
std::cout << "value2: " << value2 << std::endl;
std::cout << "uc_err: " << err  << std::endl;
`

Output:
`
value1: 0x123456789
value2: 0xcccccccccccccccc
uc_err: 0
`

**Comment by wtdcode** [comment]
> @wtdcode
> 
> to reproduce the bug:
> 
> ```
> uc_engine *uc;
> auto err = uc_open(UC_ARCH_X86, UC_MODE_64, &uc);
> uintptr_t value1= 0x123456789;
> uintptr_t value2;
> err  = uc_reg_write(uc, UC_X86_REG_RSP, &value1);
> err  = uc_reg_read(uc, UC_X86_REG_RSP, &value2);
> 
> std::cout << "value1: " << std::hex << value1 << std::endl;
> std::cout << "value2: " << value2 << std::endl;
> std::cout << "uc_err: " << err  << std::endl;
> ```
> 
> Output:
> 
> ```
> value1: 0x123456789
> value2: 0xcccccccccccccccc
> uc_err: 0
> ```

What does your `sizeof(uintptr_t)` output?

**Comment by MellowNight** [comment]
> What does your `sizeof(uintptr_t)` output?
sizeof(uintptr_t) is 8.

**Comment by wtdcode** [comment]
It works perfectly on my machine (and on CI I think). Please post detailed reproduction steps.

**Comment by MellowNight** [comment]
> It works perfectly on my machine (and on CI I think). Please post detailed reproduction steps.

So I just got home and writing/reading RSP works now for some reason... 

Back to the original issue:
I was able to successfully link unicorn2 and get the basics set up. After mapping in an unmapped address using uc_mem_map_ptr and returning true in my UC_HOOK_MEM_WRITE_UNMAPPED hook, the engine still halts unexpectedly. I can confirm that the address I am trying to map in is valid in the host and that uc_mem_map_ptr returns 0x0 (UC_ERR_OK).

This is the portion of code which causes unicorn to stop emulation:
https://github.com/unicorn-engine/unicorn/blob/dev/qemu/accel/tcg/cputlb.c#L2019

This is my UC_HOOK_MEM_WRITE_UNMAPPED hook:
```
bool MemInvalidHook(uc_engine* uc, uc_mem_type type,
    uint64_t address, int size, int64_t value, EmulationContext* user_data)
{
    switch (type)
    {
    default:
    {
        // stop emulation
        return false;
    }
    case UC_MEM_WRITE_UNMAPPED:
    case UC_MEM_READ_UNMAPPED:
    {
        uc_mem_map_ptr(uc, address, size, perms, (void*)address);
        return true;
    }
    case UC_MEM_FETCH_UNMAPPED:
    {
        return true;
    }
    }
}
```

**Comment by wtdcode** [comment]
If you are certain about the root cause, please post a PR instead. Or post a **FULL** reproduction script here.

**Comment by MellowNight** [comment]
Hello, it seems like my PAGE_ALIGN mask was masking off the most significant 32 bits, leading to memory_mapping() being unable to find the page I mapped. Sorry for any inconvenience.
