### ISSUE TITLE
Unicorn crashes the Python interpreter on a register read

### ISSUE THREAD

**Issue by elicn** [unicorn-engine/unicorn#1540]
Not sure how to categorize this one, perhaps part of the internal state is preserved and become corrupted.

The following code example reads an (invalid?) ARM register twice. The first read goes well, but after re-creating a new Unicorn with the exact same parameters, reading the same register crashes the Python interpreter. Even if the accessed register is invalid, it is expected to fail in a graceful manner (e.g. raise an exception) and not crash the interpreter.

```python
>>> from unicorn import *
>>> from unicorn.arm_const import *
>>> u = Uc(UC_ARCH_ARM, UC_MODE_ARM + UC_MODE_MCLASS + UC_MODE_THUMB)
>>> u.reg_read(UC_ARM_REG_CPSR)
1073742291
>>> u = Uc(UC_ARCH_ARM, UC_MODE_ARM + UC_MODE_MCLASS + UC_MODE_THUMB)
>>> u.reg_read(UC_ARM_REG_CPSR)
Segmentation fault
```
Python: 3.8.10
Unicron: 2.0.0rc5.post1

**Comment by wtdcode** [comment]
I believe it's the bug fixed here: a5ceca6d515564c5b5e3ba5f7e395b8d293a8b25

**Comment by elicn** [comment]
Do you have a way to test the fix and verify it indeed fixes this bug?
If it does, you may close this issue.

**Comment by wtdcode** [comment]
> Do you have a way to test the fix and verify it indeed fixes this bug? If it does, you may close this issue.

I checked it on the latest dev branch and worked well. Thanks for your report.
