### ISSUE TITLE
Unicorn doesn't reflect ARM endianess through CPSR[9]

### ISSUE THREAD

**Issue by elicn** [unicorn-engine/unicorn#1542]
It looks like Unicorn fails to reflect ARM core endianess through `CPSR[9]`.
In fact, `CPSR` reads the exact same value both on big-endian and little-endian instances.
This is important if Unicorn claims to support flexible / bi-endianess for ARM.

```python
>>> from unicorn import *
>>> from unicorn.arm_const import *
>>> u = Uc(UC_ARCH_ARM, UC_MODE_ARM + UC_MODE_BIG_ENDIAN)
>>> u.reg_read(UC_ARM_REG_CPSR) & (1 << 9)
0
```
Expected output: `512`
Unicorn version: 2.0.0rc5.post1

**Comment by wtdcode** [comment]
Weird, would have a look.

**Comment by wtdcode** [comment]
See 5683a5484d39ea25eaaad59dda217abd294b9ce6, now it should work as intended.
