### ISSUE TITLE
Mapping a region of 0x0000-0x7fff

### ISSUE THREAD

**Issue by leapofazzam123** [unicorn-engine/unicorn#1551]
Hi, I'm making a MIPS-based hobby computer, and for the emulator, I'm using Unicorn as the engine. This is what the memory map for the computer looks like:

| Address range | Description |
| --- | --- |
| `0x0000000`–`0x0001fff` | Firmware |
| `0x0002000`–`0x7ffffff` | Main memory |
| `0x0800000`–`0x0ffffff` | Video memory |
| `0x1000000`–`0x8000000` | I/O reserved |

Some of the maximum range isn't 4K aligned. Is it possible to use this memory map with Unicorn?

**Comment by wtdcode** [comment]
Only the size and length are required to 4k aligned AFAIK.

**Comment by leapofazzam123** [comment]
Ok, but is it really possible to use this memory map with Unicorn?

**Comment by leapofazzam123** [comment]
My memory map is based on https://en.m.wikipedia.org/wiki/Memory-mapped_I/O#Examples

**Comment by wtdcode** [comment]
> https://en.m.wikipedia.org/wiki/Memory-mapped_I/O#Examples

hmmm, why not?

**Comment by wtdcode** [comment]
> Only the size and length are required to 4k aligned AFAIK.

Sorry, a typo here. It should be start and size.
