### ISSUE TITLE
Instruction trace is called for all except the last instruction

### ISSUE THREAD

**Issue by yuppox** [unicorn-engine/unicorn#1552]
This is in reference to the `dev` branch.

I'm using the `static void test_riscv(void)` function from the `sample_riscv.c` example.

Here is the code in question:
```
    // tracing all instruction
    uc_hook_add(uc, &trace2, UC_HOOK_CODE, hook_code, NULL, 1, 0);
```

This hook works except that the final instruction does not trigger it. I have tried different instructions and the result is the same.

If I allow `uint64_t until` ( from `uc_emu_start()` ) to run an extra instruction, then I see the final instruction in the hook. However, the emulator will return an error because it's gone past the program code.

**Comment by wtdcode** [comment]
I don't get it. What behavior doesn't meet your expectation? Could you give some example code?

**Comment by yuppox** [comment]
Hi @wtdcode.

Thanks for the reply. The problem turned out to be user error.
