### ISSUE TITLE
Install unicorn-1.0.3 failure on debian-mipsel

### ISSUE THREAD

**Issue by 0xC4SE** [unicorn-engine/unicorn#1553]
Hi,I tried to install unicorn
pip3 install unicorn
But I got error output as follows:

      /tmp/pip-install-4p06bxcc/unicorn_515af9d9d14f491db474e526fb1312ca/src/qemu/translate-all.c: In function ‘alloc_code_gen_buffer_m68k’:
      /tmp/pip-install-4p06bxcc/unicorn_515af9d9d14f491db474e526fb1312ca/src/qemu/translate-all.c:691:39: warning: passing argument 2 of ‘split_cross_256mb’ makes pointer from integer without a cast [-Wint-conversion]
        691 |         buf2 = split_cross_256mb(buf, size1);
            |                                       ^~~~~
            |                                       |
            |                                       size_t {aka unsigned int}
      /tmp/pip-install-4p06bxcc/unicorn_515af9d9d14f491db474e526fb1312ca/src/qemu/translate-all.c:584:67: note: expected ‘void *’ but argument is of type ‘size_t’ {aka ‘unsigned int’}
        584 | static inline void *split_cross_256mb(struct uc_struct *uc, void *buf1, size_t size1)
            |                                                             ~~~~~~^~~~
      /tmp/pip-install-4p06bxcc/unicorn_515af9d9d14f491db474e526fb1312ca/src/qemu/translate-all.c:691:16: error: too few arguments to function ‘split_cross_256mb’
        691 |         buf2 = split_cross_256mb(buf, size1);
            |                ^~~~~~~~~~~~~~~~~
      /tmp/pip-install-4p06bxcc/unicorn_515af9d9d14f491db474e526fb1312ca/src/qemu/translate-all.c:584:21: note: declared here
        584 | static inline void *split_cross_256mb(struct uc_struct *uc, void *buf1, size_t size1)
            |                     ^~~~~~~~~~~~~~~~~
      make[2]: *** [/tmp/pip-install-4p06bxcc/unicorn_515af9d9d14f491db474e526fb1312ca/src/qemu/rules.mak:54: translate-all.o] Error 1
      make[1]: *** [Makefile:84: subdir-m68k-softmmu] Error 2
      make[1]: *** Waiting for unfinished jobs....
        CC    armeb-softmmu/cpu-exec.o
      /tmp/pip-install-4p06bxcc/unicorn_515af9d9d14f491db474e526fb1312ca/src/qemu/translate-all.c: In function ‘alloc_code_gen_buffer_x86_64’:
      /tmp/pip-install-4p06bxcc/unicorn_515af9d9d14f491db474e526fb1312ca/src/qemu/translate-all.c:691:39: warning: passing argument 2 of ‘split_cross_256mb’ makes pointer from integer without a cast [-Wint-conversion]
        691 |         buf2 = split_cross_256mb(buf, size1);
            |                                       ^~~~~
            |                                       |
            |                                       size_t {aka unsigned int}
      /tmp/pip-install-4p06bxcc/unicorn_515af9d9d14f491db474e526fb1312ca/src/qemu/translate-all.c:584:67: note: expected ‘void *’ but argument is of type ‘size_t’ {aka ‘unsigned int’}
        584 | static inline void *split_cross_256mb(struct uc_struct *uc, void *buf1, size_t size1)
            |                                                             ~~~~~~^~~~
      /tmp/pip-install-4p06bxcc/unicorn_515af9d9d14f491db474e526fb1312ca/src/qemu/translate-all.c:691:16: error: too few arguments to function ‘split_cross_256mb’
        691 |         buf2 = split_cross_256mb(buf, size1);
            |                ^~~~~~~~~~~~~~~~~
      /tmp/pip-install-4p06bxcc/unicorn_515af9d9d14f491db474e526fb1312ca/src/qemu/translate-all.c:584:21: note: declared here
        584 | static inline void *split_cross_256mb(struct uc_struct *uc, void *buf1, size_t size1)
            |                     ^~~~~~~~~~~~~~~~~
      make[2]: *** [/tmp/pip-install-4p06bxcc/unicorn_515af9d9d14f491db474e526fb1312ca/src/qemu/rules.mak:54: translate-all.o] Error 1
      make[1]: *** [Makefile:84: subdir-x86_64-softmmu] Error 2
        CC    armeb-softmmu/tcg/tcg.o
      /tmp/pip-install-4p06bxcc/unicorn_515af9d9d14f491db474e526fb1312ca/src/qemu/translate-all.c: In function ‘alloc_code_gen_buffer_arm’:
      /tmp/pip-install-4p06bxcc/unicorn_515af9d9d14f491db474e526fb1312ca/src/qemu/translate-all.c:691:39: warning: passing argument 2 of ‘split_cross_256mb’ makes pointer from integer without a cast [-Wint-conversion]
        691 |         buf2 = split_cross_256mb(buf, size1);
            |                                       ^~~~~
            |                                       |
            |                                       size_t {aka unsigned int}
      /tmp/pip-install-4p06bxcc/unicorn_515af9d9d14f491db474e526fb1312ca/src/qemu/translate-all.c:584:67: note: expected ‘void *’ but argument is of type ‘size_t’ {aka ‘unsigned int’}
        584 | static inline void *split_cross_256mb(struct uc_struct *uc, void *buf1, size_t size1)
            |                                                             ~~~~~~^~~~
      /tmp/pip-install-4p06bxcc/unicorn_515af9d9d14f491db474e526fb1312ca/src/qemu/translate-all.c:691:16: error: too few arguments to function ‘split_cross_256mb’
        691 |         buf2 = split_cross_256mb(buf, size1);
            |                ^~~~~~~~~~~~~~~~~
      /tmp/pip-install-4p06bxcc/unicorn_515af9d9d14f491db474e526fb1312ca/src/qemu/translate-all.c:584:21: note: declared here
        584 | static inline void *split_cross_256mb(struct uc_struct *uc, void *buf1, size_t size1)
            |                     ^~~~~~~~~~~~~~~~~
      make[2]: *** [/tmp/pip-install-4p06bxcc/unicorn_515af9d9d14f491db474e526fb1312ca/src/qemu/rules.mak:54: translate-all.o] Error 1
      make[1]: *** [Makefile:84: subdir-arm-softmmu] Error 2
        CC    armeb-softmmu/tcg/optimize.o
      /tmp/pip-install-4p06bxcc/unicorn_515af9d9d14f491db474e526fb1312ca/src/qemu/translate-all.c: In function ‘alloc_code_gen_buffer_armeb’:
      /tmp/pip-install-4p06bxcc/unicorn_515af9d9d14f491db474e526fb1312ca/src/qemu/translate-all.c:691:39: warning: passing argument 2 of ‘split_cross_256mb’ makes pointer from integer without a cast [-Wint-conversion]
        691 |         buf2 = split_cross_256mb(buf, size1);
            |                                       ^~~~~
            |                                       |
            |                                       size_t {aka unsigned int}
      /tmp/pip-install-4p06bxcc/unicorn_515af9d9d14f491db474e526fb1312ca/src/qemu/translate-all.c:584:67: note: expected ‘void *’ but argument is of type ‘size_t’ {aka ‘unsigned int’}
        584 | static inline void *split_cross_256mb(struct uc_struct *uc, void *buf1, size_t size1)
            |                                                             ~~~~~~^~~~
      /tmp/pip-install-4p06bxcc/unicorn_515af9d9d14f491db474e526fb1312ca/src/qemu/translate-all.c:691:16: error: too few arguments to function ‘split_cross_256mb’
        691 |         buf2 = split_cross_256mb(buf, size1);
            |                ^~~~~~~~~~~~~~~~~
      /tmp/pip-install-4p06bxcc/unicorn_515af9d9d14f491db474e526fb1312ca/src/qemu/translate-all.c:584:21: note: declared here
        584 | static inline void *split_cross_256mb(struct uc_struct *uc, void *buf1, size_t size1)
            |                     ^~~~~~~~~~~~~~~~~
      make[2]: *** [/tmp/pip-install-4p06bxcc/unicorn_515af9d9d14f491db474e526fb1312ca/src/qemu/rules.mak:54: translate-all.o] Error 1
      make[2]: *** Waiting for unfinished jobs....
      make[1]: *** [Makefile:84: subdir-armeb-softmmu] Error 2
      make[1]: Leaving directory '/tmp/pip-install-4p06bxcc/unicorn_515af9d9d14f491db474e526fb1312ca/src/qemu'
      make: *** [Makefile:297: uc.o] Error 2
      error: [Errno 2] No such file or directory: 'libunicorn.so'

**Comment by wtdcode** [comment]
I'm afraid we don't support mipsel.
