### ISSUE TITLE
Support arbitrary MSRs on aarch64 (MRS instruction errors)

### ISSUE THREAD

**Issue by rickmark** [unicorn-engine/unicorn#1557]
We are attempting to run low level firmware, and from my understanding unlike x86 we don't have a generic MSR layout for aarch64.  The following instruction causes errors:

`MRS             X2, #0, c15, c5, #0`

We have mapped out all of the known registers for Apple's ARM implementation here:
https://github.com/hack-different/apple-knowledge/blob/main/_data/registers.yaml

**Comment by wtdcode** [comment]
Different CPU model has different coprocessor registers. Refer to qemu for details.

**Comment by rickmark** [comment]
This is understood - the proposal after speaking to others in hack-different is to work on arbitrary MSR in https://github.com/alephsecurity/xnu-qemu-arm64 where any non-implemented would store/get.  Unicorn would then provide a MSR hook allowing the emulation host free to handle these MSRs as seen fit.

Most of the time simply store/get is enough to get code to run well enough for a lot of purposes (such as testing that the MSR is set after execution)

**Comment by wtdcode** [comment]
A possible workaround to register a handler for CPU exception so you can handle such read/write.

**Comment by rickmark** [comment]
Would that mask any other issue though?  If it can be determined maybe a hook for MRS is better?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wtdcode** [comment]
Usually, you could get a unique exception index but I agree a dedicated hook with UC_HOOK_INSN would be better. Mark this with enhancement.

**Comment by wtdcode** [comment]
Done in the latest dev branch. Try it out! 7f8ff1af6a821002ff3e2bbcb7e39c12217d32b0

*aarch32 is also on the way.

**Comment by rickmark** [comment]
Hey there - so ... poetry...

I'm about to file a bug against them for not supporting `subdirectory` meaning we can't depend on unicorn in python on the dev branch... any chance of getting this as a alpha/beta/pre-release package?
