### ISSUE TITLE
Unicorn uses `libCORE_NAME.a` which might conflict

### ISSUE THREAD

**Issue by rickmark** [unicorn-engine/unicorn#1564]
Suggest moving the libs like `libaarch64-softmmu.a` to `libunicorn-aarch64-softmmu.a`etc. to prevent conflicts with libs of the same name.

**Comment by wtdcode** [comment]
`libaarch64-softmmu.a` is not intended to be installed and used AFAIK.

**Comment by rickmark** [comment]
a casual `make && make install` would do so, breaking all sorts of stuff (ask why I know 😆 )

**Comment by wtdcode** [comment]
I assume this issue has been solved in the recent dev branch.
