### ISSUE TITLE
TriCore Support

### ISSUE THREAD

**Issue by uberwoozle** [unicorn-engine/unicorn#1566]
I have a TriCore port from QEMU to UnicornV2.

This is my first time contributing to a public repository. How should I go about submitting a pull request? 

Also, is there a checklist of things I should provide besides just TriCore support?

**Comment by wtdcode** [comment]
Hello, thanks for your interest. You could firstly fork the repo and push your code to a new branch and then create a pull request.

For details, see: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by uberwoozle** [comment]
PR submitted

**Comment by aquynh** [comment]
Are you based on v5.0.1?

Make sure to have samples/sample_tricore.c, then we will add more testcases
later.
