### ISSUE TITLE
Possible to cut a Unicorn-2.0.0-RC7? (For MSR/MRS)

### ISSUE THREAD

**Issue by rickmark** [unicorn-engine/unicorn#1571]
We have #1557 which was added just after RC6.  Is it possible to cut a RC7 with this change to do some testing in `hack-different/ipwndfu`?  (Poetry doesn't let us easily depend on Git here)

**Comment by wtdcode** [comment]
Released ;), a bit late though

**Comment by rickmark** [comment]
Awesome - happy to provide feedback in general - we will be basing our checkm8 test code on executing SecureROM in Unicorn so should be an exciting use case!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by aquynh** [comment]
On Mon, Apr 18, 2022, 01:05 Rick Mark ***@***.***> wrote:

> Awesome - happy to provide feedback in general - we will be basing our
> checkm8 test code on executing SecureROM in Unicorn so should be an
> exciting use case!
>

Cool, any link?
