### ISSUE TITLE
Issues with uc_mem_map on linux?

### ISSUE THREAD

**Issue by KitMurdock** [unicorn-engine/unicorn#1596]
The code below causes the program to crash (on linux) - it seems to consume all the system memory. And has even completely stalled my host computer.

It looks like an issue with ```uc_mem_map``` and ```uc_close```

```
#include <unicorn/unicorn.h>
#include <string.h>

#define ADDRESS 0x1000

static uc_err _uc_err_check(uc_err err, const char *expr)
{
    if (err)
    {
        fprintf(stderr, "Failed on %s with error: %s\n", expr, uc_strerror(err));
        exit(1);
    }
    return err;
}
#define UC_ERR_CHECK(x) _uc_err_check(x, #x)

int main(int argc, char **argv, char **envp)
{
    uc_err err;

    for (int i=0;i<0xFFFFF;i++)
    {
        uc_engine *uc;
        err = uc_open(UC_ARCH_ARM, UC_MODE_ARM, &uc);
        UC_ERR_CHECK(err);

        // map 2MB memory for this emulation
        err = uc_mem_map(uc, ADDRESS, 2 * 1024 * 1024, UC_PROT_ALL);
        UC_ERR_CHECK(err);

        uc_close(uc);
    }
    return 0;
}
```

**Comment by wtdcode** [comment]
> #include <unicorn/unicorn.h>
> #include <string.h>
> 
> #define ADDRESS 0x1000
> 
> static uc_err _uc_err_check(uc_err err, const char *expr)
> {
>     if (err)
>     {
>         fprintf(stderr, "Failed on %s with error: %s\n", expr, uc_strerror(err));
>         exit(1);
>     }
>     return err;
> }
> #define UC_ERR_CHECK(x) _uc_err_check(x, #x)
> 
> int main(int argc, char **argv, char **envp)
> {
>     uc_err err;
> 
>     for (int i=0;i<0xFFFFF;i++)
>     {
>         uc_engine *uc;
>         err = uc_open(UC_ARCH_ARM, UC_MODE_ARM, &uc);
>         UC_ERR_CHECK(err);
> 
>         // map 2MB memory for this emulation
>         err = uc_mem_map(uc, ADDRESS, 2 * 1024 * 1024, UC_PROT_ALL);
>         UC_ERR_CHECK(err);
> 
>         uc_close(uc);
>     }
>     return 0;
> }

There was a serious memory leak in rc6, please try our latest dev branch.

**Comment by KitMurdock** [comment]
Yes - fixed in latest dev branch. Thanks!
