### ISSUE TITLE
How do we know if the run ended by hitting the max instruction count?

### ISSUE THREAD

**Issue by KitMurdock** [unicorn-engine/unicorn#1597]
How do we know if the run ended by hitting the max instruction count?

Could UC_QUERY be extended to include that?

**Comment by wtdcode** [comment]
You could simply install a `UC_HOOK_CODE` to implement your own logic, which the `count` parameter does.

**Comment by KitMurdock** [comment]
I still believe there should be some way to know if the run ended by meeting the max instruction count.
Yes - I can add this in myself, but then I'd be duplicating code that's already in unicorn.

**Comment by wtdcode** [comment]
> I still believe there should be some way to know if the run ended by meeting the max instruction count. Yes - I can add this in myself, but then I'd be duplicating code that's already in unicorn.

Could you illustrate your use case? I assume this is really easy to implement...
