### ISSUE TITLE
error with go binding

### ISSUE THREAD

**Issue by flyinbedxyz** [unicorn-engine/unicorn#1607]
I want to use unicorn in go1.18.1.
Howerever,I tried the sample.go and followed the Readme.
Error occured when go build.
`# github.com/unicorn-engine/unicorn/bindings/go/unicorn
D:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lunicorn
collect2.exe: error: ld returned 1 exit status`
I also tried it with go 1.15.13 in linux,but there is the same error
`# github.com/unicorn-engine/unicorn/bindings/go/unicorn
/usr/bin/ld: cannot find -lunicorn
/usr/bin/ld: cannot find -lunicorn
collect2: error: ld returned 1 exit status.`
I googled it but can't find the solution,can you help me ?

**Comment by bet4it** [comment]
You need to install the unicorn library globally before using the go binding.
