### ISSUE TITLE
Add type annotations to Python bindings

### ISSUE THREAD

**Issue by johnthagen** [unicorn-engine/unicorn#1610]
Editors such as PyCharm and VS Code can provide much better real-time autocomplete and type checking for users of Unicorn if the Python bindings had type annotations applied to them:

- https://docs.python.org/3/library/typing.html

In addition, users could use command line tools such as [Mypy](https://github.com/python/mypy) to statically type check their Unicorn applications from the terminal and within CI.

**Comment by wtdcode** [comment]
The typing is not yet added due to the complexity (or bad early design) of `uc_reg_read/write` API. #1517 

I would appreciate it if you could conribute.

**Comment by wtdcode** [comment]
Fixed in a221e378bfadee873b9ac289c2429ad17b075272

**Comment by johnthagen** [comment]
@wtdcode This is a great start, thanks!

A few places this could be improved:

https://github.com/unicorn-engine/unicorn/commit/a221e378bfadee873b9ac289c2429ad17b075272#diff-8633cd982589e7959e080ac0de235ae2d3b1f013642b3d91ef2d7f2ac6e2a2ffR797

```py
def hook_add(self, htype: int, callback: Callable, user_data: Any=None, begin: int=1, end: int=0, arg1: int=0, arg2: int=0):
```

`callback` could use a fully defined `Callable`.

Further up, you defined `Callable[["Uc", int, int, Any], int]`. If it's the same type used again, you could make a type alias for it to make it easy to reused.

```py
UcCallback: Callable[["Uc", int, int, Any], int]
```

Another idea, if you don't want to use strings for types like `"Uc"`, you can use:

```py
from __future__ import annotations
```

This defers evaluation of type hints (essentially they are all converted to strings internally).

Finally, the return types of functions could be annotated with `-> int` etc. 

I hope this information is helpful!

**Comment by wtdcode** [comment]
> @wtdcode This is a great start, thanks!
> 
> A few places this could be improved:
> 
> [a221e37#diff-8633cd982589e7959e080ac0de235ae2d3b1f013642b3d91ef2d7f2ac6e2a2ffR797](https://github.com/unicorn-engine/unicorn/commit/a221e378bfadee873b9ac289c2429ad17b075272#diff-8633cd982589e7959e080ac0de235ae2d3b1f013642b3d91ef2d7f2ac6e2a2ffR797)
> 
> ```python
> def hook_add(self, htype: int, callback: Callable, user_data: Any=None, begin: int=1, end: int=0, arg1: int=0, arg2: int=0):
> ```
> 
> `callback` could use a fully defined `Callable`.
> 
> Further up, you defined `Callable[["Uc", int, int, Any], int]`. If it's the same type used again, you could make a type alias for it to make it easy to reused.
> 
> ```python
> # Example type alias
> UcCallback = Callable[["Uc", int, int, Any], int]
> ```
> 
> Another idea, if you don't want to use strings for types like `"Uc"`, you can use:
> 
> ```python
> from __future__ import annotations
> ```
> 
> This defers evaluation of type hints (essentially they are all converted to strings internally).
> 
> Finally, the return types of functions could be annotated with `-> int` etc. This will improve editor completion/type checking from values returned from the bindings.
> 
> I hope this information is helpful!



> @wtdcode This is a great start, thanks!
> 
> A few places this could be improved:
> 
> [a221e37#diff-8633cd982589e7959e080ac0de235ae2d3b1f013642b3d91ef2d7f2ac6e2a2ffR797](https://github.com/unicorn-engine/unicorn/commit/a221e378bfadee873b9ac289c2429ad17b075272#diff-8633cd982589e7959e080ac0de235ae2d3b1f013642b3d91ef2d7f2ac6e2a2ffR797)
> 
> ```python
> def hook_add(self, htype: int, callback: Callable, user_data: Any=None, begin: int=1, end: int=0, arg1: int=0, arg2: int=0):
> ```
> 
> `callback` could use a fully defined `Callable`.
> 
> Further up, you defined `Callable[["Uc", int, int, Any], int]`. If it's the same type used again, you could make a type alias for it to make it easy to reused.
> 
> ```python
> # Example type alias
> UcCallback = Callable[["Uc", int, int, Any], int]
> ```
> 
> Another idea, if you don't want to use strings for types like `"Uc"`, you can use:
> 
> ```python
> from __future__ import annotations
> ```
> 
> This defers evaluation of type hints (essentially they are all converted to strings internally).
> 
> Finally, the return types of functions could be annotated with `-> int` etc. This will improve editor completion/type checking from values returned from the bindings.
> 
> I hope this information is helpful!

For the `callback` argument of `hook_add`, I can't find a proper way to add annotations. e.g.

```python
UC_HOOK_CODE_TYPE = Callable[["Uc", ...], None] # Uc is not identified

class Uc:
    # UC_HOOK_CODE_TYPE = Callable[["Uc", ...], None] # Uc is not identified, too
    def hook_add(..., callback: Union[..., UC_HOOK_CODE_TYPE], ...):
```

Of course, writing the full type in the signature works but it looks ugly. It's not that hard and seems you are more familiar than me. I'm more than happy if you could send a PR.

**Comment by johnthagen** [comment]
> # Uc is not defined

Hmm, is it actually a problem if you use a string or `from __future__ import annotations`? That is how type checkers deal with the forward reference problem.

What tool are you using to validate it? Is there output you can share?

**Comment by wtdcode** [comment]
Solved and if no more questions, the issue will be closed.

**Comment by johnthagen** [comment]
https://github.com/unicorn-engine/unicorn/commit/aab035e8c311556b167c5ccfeec46cee87121c17 looks great!

**Comment by wtdcode** [comment]
Closed.

**Comment by johnthagen** [comment]
Thanks @wtdcode!
