### ISSUE TITLE
Tricore sample code does not run.

### ISSUE THREAD

**Issue by KitMurdock** [unicorn-engine/unicorn#1614]
https://github.com/unicorn-engine/unicorn/blob/dev/samples/sample_tricore.c

Produces an error: 
```
Emulate TriCore code
Failed on uc_open() with error returned: 2 (Invalid/unsupported architecture (UC_ERR_ARCH))
```

(I'm on the branch: origin/dev)

**Comment by KitMurdock** [comment]
Hiya, @uberwoozle

I know you did the tricore work - any idea why the sample doesn't run?

**Comment by aquynh** [comment]
I think your system does have the matching unicorn version.

Try to remove all installed libs, then install the latest unicorn again.

**Comment by uberwoozle** [comment]
I agree with @aquynh, it would seem the version of unicorn your system is using does not have tricore built.

**Comment by KitMurdock** [comment]
Yup - I'm a muppet. Sorry both.
