### ISSUE TITLE
bindings support - submodule

### ISSUE THREAD

**Issue by kassane** [unicorn-engine/unicorn#1620]
## Suggestion

It would be interesting to separate the bindings from the main project repository and invoke as git submodule. This way it improves support distribution.

**Comment by wtdcode** [comment]
Yes, indeed. However, I don't have enough time to do this recently and it might break some existing workflows.

**Comment by aquynh** [comment]
Sorry but i dont see how this helps.

**Comment by kassane** [comment]
> Sorry but i dont see how this helps.
> 

Do these bindings have the same project priority level?

Separating the main project from the extensions/bindings would clean up more issues and patches, since some users care more about the extensions (favoring their predominant language) than contributing to the main project.

That way everything regarding the bindings will be handled exclusively in the equivalent repository.

**Comment by wtdcode** [comment]
It also helps distribution for some specific bindings like golang & rust and that's why I mark it as an enhancement.
