### ISSUE TITLE
is riscv64 support bitmanip extension???

### ISSUE THREAD

**Issue by yuyang-ok** [unicorn-engine/unicorn#1622]
https://github.com/riscv/riscv-bitmanip

**Comment by wtdcode** [comment]
If qemu does, then the answer is yes.

**Comment by QDucasse** [comment]
Hello, from the RISC-V [wiki](https://wiki.riscv.org/display/HOME/Emulators+and+Simulators#EmulatorsandSimulators-QEMU), the supported extensions in QEMU are: RV32GCE and RV64GC along with the E unratified extension! Spike however has support for some more unratifed extensions such as the B you're looking for

**Comment by yuyang-ok** [comment]
ok , thanks .

**Comment by wtdcode** [comment]
not yet, but porting `*.inc` is usually easier since it's already templated.
