### ISSUE TITLE
Extern functions / Host bindings & Webassembly

### ISSUE THREAD

**Issue by phillvancejr** [unicorn-engine/unicorn#1624]
Hello,

Is it possible to expose functions to the emulator to be called by the assembly code? Specifically I'd like to compile unicorn to Wasm and expose some Javascript functions to the emulator so I can call them from the program.

**Comment by wtdcode** [comment]
That’s exactly what hooks are for.

**Comment by phillvancejr** [comment]
> That’s exactly what hooks are for.

Thanks! I'll look at the documentation for hooks. I appreciate it.
