### ISSUE TITLE
.gitignore is too vague since #1584

### ISSUE THREAD

**Issue by ikelos** [unicorn-engine/unicorn#1626]
There was a change made in #1584 that changes `bindings/rust/target/` to just `target/` which then ignores anything under `qemu/target`.  This isn't a folder that seems to change that often, but it might catch out developers that are working across the whole tree.

https://github.com/unicorn-engine/unicorn/blob/55b2950cac4098bacfff3bdb72b58380ee15212c/.gitignore#L55

This can either be fixed by returning the `bindings/rust/` to the start of the rule, or by explicitly adding a `!/qemu/target/` to the `.gitignore` file.

Please let me know if you need any additional information....

**Comment by aquynh** [comment]
please pull req

**Comment by bet4it** [comment]
Fixed in #1616

**Comment by ikelos** [comment]
Thanks @bet4it, that seems to resolve the issue, but I'm confused what's it now ignoring, there isn't a top level target and I don't believe one is created during compilation, so the line seems redundant?

**Comment by bet4it** [comment]
The file `Cargo.toml` locates in the top level directory so `target` should also be created there.

**Comment by ikelos** [comment]
Ok, I see what's going on now, thanks.  5:)
