### ISSUE TITLE
uc_context_restore/save doesn't work fully for ARM CPUs

### ISSUE THREAD

**Issue by KitMurdock** [unicorn-engine/unicorn#1635]
uc_context_save() stores dynamically allocated pointers for ARM CPU architecture.

When saving the context for the ARM architecture uc_context_save() memcpy's all fields of the CPUARMState struct up to cpu_watchpoint into the allocated buffer. This includes the dynamically allocated sau.rbar and sau.rlar pointers as well as similar pointers in the pmsav7 and pmsav8 structs.

This prevents the context being restored into another uc_engine instance or being saved to persistent storage without generating segfaults or double-free errors.

It looks from the implementation for other CPU architectures that contexts are intended to be standalone.

**Comment by wtdcode** [comment]
Good catch! Looks like a deeper copy is needed.

**Comment by wtdcode** [comment]
Should be fixed in 19d8876e2350bf325181c52f7acf752e89452d15
