### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [unicorn-engine/unicorn#1637]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@liyansong2018) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by aquynh** [comment]
will do later today, thanks.

**Comment by JamieSlome** [comment]
@aquynh - thanks for your diligence 👍 

Just for reference, you can find the report directly here:
https://huntr.dev/bounties/3ea59112-5d51-440a-a04d-c9c7c89f748b/

It is private and only accessible to maintainers with repository write permissions :)

**Comment by wtdcode** [comment]
> @aquynh - thanks for your diligence 👍
> 
> Just for reference, you can find the report directly here: https://huntr.dev/bounties/3ea59112-5d51-440a-a04d-c9c7c89f748b/
> 
> It is private and only accessible to maintainers with repository write permissions :)

Hello, I don't have access to the report. Any idea?

**Comment by aquynh** [comment]
we already added SECURITY.md.

thanks.
