### ISSUE TITLE
GPL-2.0 is a deprecated SPDX license

### ISSUE THREAD

**Issue by chenrui333** [unicorn-engine/unicorn#1642]
[GPL-2.0](https://spdx.org/licenses/GPL-2.0.html) is deprecated by SPDX, please consider using [GPL-2.0-only ](https://spdx.org/licenses/GPL-2.0-only.html)or [GPL-2.0-or-later](https://spdx.org/licenses/GPL-2.0-or-later.html). Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/105364

**Comment by wtdcode** [comment]
Sorry I'm very familiar with the License stuff. What's the difference?

**Comment by lgbaldoni** [comment]
I think GPL-2.0 defaults to GPL-2.0-only if not otherwise specified.

**Comment by wtdcode** [comment]
Both licenses have the same link on the website given. So we are using `GPL-2.0-only` already, correct?

**Comment by chenrui333** [comment]
> I think GPL-2.0 defaults to GPL-2.0-only if not otherwise specified.

Nope, there is no such default thing, it can be inferred in terms of license compatibility purpose though

**Comment by wtdcode** [comment]
> > I think GPL-2.0 defaults to GPL-2.0-only if not otherwise specified.
> 
> Nope, there is no such default thing, it can be inferred in terms of license compatibility purpose though

So what's wrong with Unicorn's license?

**Comment by chenrui333** [comment]
> > > I think GPL-2.0 defaults to GPL-2.0-only if not otherwise specified.
> > 
> > 
> > Nope, there is no such default thing, it can be inferred in terms of license compatibility purpose though
> 
> So what's wrong with Unicorn's license?

I think it is just using the deprecated license. Nothing wrong though.

**Comment by wtdcode** [comment]
> > > > I think GPL-2.0 defaults to GPL-2.0-only if not otherwise specified.
> > > 
> > > 
> > > Nope, there is no such default thing, it can be inferred in terms of license compatibility purpose though
> > 
> > 
> > So what's wrong with Unicorn's license?
> 
> I think it is just using the deprecated license. Nothing wrong though.

But `[GPL-2.0](https://spdx.org/licenses/GPL-2.0.html)` is exactly the same as [GPL-2.0-only](https://spdx.org/licenses/GPL-2.0-only.html), isn't it?

**Comment by chenrui333** [comment]
> > > > > I think GPL-2.0 defaults to GPL-2.0-only if not otherwise specified.
> > > > 
> > > > 
> > > > Nope, there is no such default thing, it can be inferred in terms of license compatibility purpose though
> > > 
> > > 
> > > So what's wrong with Unicorn's license?
> > 
> > 
> > I think it is just using the deprecated license. Nothing wrong though.
> 
> But [GPL-2.0](https://spdx.org/licenses/GPL-2.0.html) is exactly the same as [GPL-2.0-only](https://spdx.org/licenses/GPL-2.0-only.html), isn't it?

With header declaration part, both GPL-2.0-only and GPL-2.0-or-later are the same as GPL-2.0
