### ISSUE TITLE
[2.0.0] Linking failures on armv7l, ppc64be and s390x

### ISSUE THREAD

**Issue by lgbaldoni** [unicorn-engine/unicorn#1645]
Seeing these errors whilst packaging for openSUSE Tumbleweed:

[unicorn200_armv7l.txt](https://github.com/unicorn-engine/unicorn/files/9076110/unicorn200_armv7l.txt)
[unicorn200_ppc64be.txt](https://github.com/unicorn-engine/unicorn/files/9076111/unicorn200_ppc64be.txt)
[unicorn200_s390x.txt](https://github.com/unicorn-engine/unicorn/files/9076114/unicorn200_s390x.txt)

**Comment by wtdcode** [comment]
We never tried to build unicorn on these platforms, however, we could check if Github Actions has these runners.
