### ISSUE TITLE
[2.0.0] test_mem fails on ppc64le

### ISSUE THREAD

**Issue by lgbaldoni** [unicorn-engine/unicorn#1646]
Seeing this whilst packaging for openSUSE Tumbleweed:

[unicorn200_ppc64le_test_failure.txt](https://github.com/unicorn-engine/unicorn/files/9076118/unicorn200_ppc64le_test_failure.txt)

**Comment by wtdcode** [comment]
How did you build & test?

**Comment by lgbaldoni** [comment]
> How did you build & test?

On [OBS](https://build.opensuse.org/) under a qemu VM, see log: [unicorn200_ppc64le_build.txt](https://github.com/unicorn-engine/unicorn/files/9077524/unicorn200_ppc64le_build.txt).

**Comment by roehling** [comment]
I see the same issue in Debian:
https://buildd.debian.org/status/fetch.php?pkg=unicorn-engine&arch=ppc64el&ver=2.0.0-1&stamp=1662836389&raw=0

**Comment by wtdcode** [comment]
@lgbaldoni @roehling could you retry with the latest dev branch?
