### ISSUE TITLE
Does it support branch instructions in AARCH64?

### ISSUE THREAD

**Issue by naveen126** [unicorn-engine/unicorn#1649]
I found "b  label" can not run correctly. It maybe have got int a deadloop in the uc_emu_start.
There is no return when execute a "b" instruction.

Please check and give me some help!
Thanks!

**Comment by wtdcode** [comment]
It of course supports. You could have a reproduction script so that we can help.

**Comment by naveen126** [comment]
> 

There are some steps to recover this issue.
I have got a little AARCH64 asm, the dump file is like this:
Disassembly of section .text:

0000000000200000 <_start>:
  200000:	d2803421 	mov	x1, #0x1a1                 	// #417
  200004:	91000422 	add	x2, x1, #0x1
  200008:	91000443 	add	x3, x2, #0x1
  20000c:	91000464 	add	x4, x3, #0x1
  200010:	91000485 	add	x5, x4, #0x1
  200014:	910004a6 	add	x6, x5, #0x1
  200018:	14000004 	b	200028 <main>
  20001c:	12001c00 	and	w0, w0, #0xff
  200020:	9b007c0a 	mul	x10, x0, x0
  200024:	9b007d4a 	mul	x10, x10, x0

0000000000200028 <main>:
  200028:	5800010b 	ldr	x11, 200048 <halt+0x4>
  20002c:	5800012c 	ldr	x12, 200050 <halt+0xc>
  200030:	5800014d 	ldr	x13, 200058 <halt+0x14>
  200034:	f90001ab 	str	x11, [x13]
  200038:	f90069ac 	str	x12, [x13, #208]
  20003c:	f94001b5 	ldr	x21, [x13]
  200040:	f94069b6 	ldr	x22, [x13, #208]

0000000000200044 <halt>:
  200044:	14000000 	b	200044 <halt>
  200048:	cafebeef 	eon	x15, x23, x30, ror #47
  20004c:	00000000 	udf	#0
  200050:	a1b2c3d4 	.inst	0xa1b2c3d4 ; undefined
  200054:	00000000 	udf	#0
  200058:	d00d0000 	adrp	x0, 1a202000 <__bss_end+0x1a001fa0>
  20005c:	00000000 	udf	#0

Firstly, Add the following code in front of test_arm64 in the file sample_arm64.c.
    uint64_t mem_data = 0;
    uint64_t pc_addr = 0;
    uint32_t isa_word = 0;
    char     isa_bytes[4];
Secondly, add the following code at end of test_arm64 in the file sample_arm64.c.
    // 14000004 	b	200028 <main>
    isa_word = 0x14000004;
    pc_addr = 0x200018;
    memcpy(isa_bytes, &isa_word, 4);
    uc_mem_write(uc, pc_addr, isa_bytes, 4);
    err = uc_emu_start(uc, pc_addr, pc_addr + 3, 0, 0);
    if (err) {
        printf("B-inst Test Failed on uc_emu_start() with error returned: %u\n", err);
    }

    err = uc_reg_read(uc, UC_ARM64_REG_PC, &mem_data);
    if (err) {
        printf("Read PC_reg Failed on uc_emu_start() with error returned: %u\n", err);
    }
    printf("PC = 0x%016lx\n", mem_data);

**Now, the whole test_arm64 function is:**

static void test_arm64(void)
{
    uc_engine *uc;
    uc_err err;
    uc_hook trace1, trace2;

    uint64_t mem_data = 0;
    uint64_t pc_addr = 0;
    uint32_t isa_word = 0;
    char     isa_bytes[4];

    int64_t x11 = 0x12345678;    // X11 register
    int64_t x13 = 0x10000 + 0x8; // X13 register
    int64_t x15 = 0x33;          // X15 register

    printf("Emulate ARM64 code\n");

    // Initialize emulator in ARM mode
    err = uc_open(UC_ARCH_ARM64, UC_MODE_ARM, &uc);
    if (err) {
        printf("Failed on uc_open() with error returned: %u (%s)\n", err,
               uc_strerror(err));
        return;
    }

    // map 2MB memory for this emulation
    uc_mem_map(uc, ADDRESS, 2 * 1024 * 1024, UC_PROT_ALL);

    // write machine code to be emulated to memory
    uc_mem_write(uc, ADDRESS, ARM64_CODE, sizeof(ARM64_CODE) - 1);

    // initialize machine registers
    uc_reg_write(uc, UC_ARM64_REG_X11, &x11);
    uc_reg_write(uc, UC_ARM64_REG_X13, &x13);
    uc_reg_write(uc, UC_ARM64_REG_X15, &x15);

    // tracing all basic blocks with customized callback
    uc_hook_add(uc, &trace1, UC_HOOK_BLOCK, hook_block, NULL, 1, 0);

    // tracing one instruction at ADDRESS with customized callback
    uc_hook_add(uc, &trace2, UC_HOOK_CODE, hook_code, NULL, ADDRESS, ADDRESS);

    // emulate machine code in infinite time (last param = 0), or when
    // finishing all the code.
    err = uc_emu_start(uc, ADDRESS, ADDRESS + sizeof(ARM64_CODE) - 1, 0, 0);
    if (err) {
        printf("Failed on uc_emu_start() with error returned: %u\n", err);
    }

    // now print out some registers
    printf(">>> Emulation done. Below is the CPU context\n");
    printf(">>> As little endian, X15 should be 0x78:\n");

    uc_reg_read(uc, UC_ARM64_REG_X15, &x15);
    printf(">>> X15 = 0x%" PRIx64 "\n", x15);

    // 14000004 	b	200028 <main>
    isa_word = 0x14000004;
    pc_addr = 0x200018;
    memcpy(isa_bytes, &isa_word, 4);
    uc_mem_write(uc, pc_addr, isa_bytes, 4);
    err = uc_emu_start(uc, pc_addr, pc_addr + 3, 0, 0);
    if (err) {
        printf("B-inst Test Failed on uc_emu_start() with error returned: %u\n", err);
    }

    err = uc_reg_read(uc, UC_ARM64_REG_PC, &mem_data);
    if (err) {
        printf("Read PC_reg Failed on uc_emu_start() with error returned: %u\n", err);
    }
    printf("PC = 0x%016lx\n", mem_data);


    uc_close(uc);
}

At last, following the steps in compile.md to build unicorn.
After building for unicorn, run the sample_arm64 in the ternimal.
././sample_arm64

**It turns out some information as bellow.**
>>> Emulate ARM64 fetching stack data from high address 10000000000000
>>> x0(Exception Level)=1
>>> X1 = 0xc8c8c8c8c8c8c8c8
Emulate ARM64 code
>>> Tracing basic block at 0x10000, block size = 0x8
>>> Tracing instruction at 0x10000, instruction size = 0x4
>>> Emulation done. Below is the CPU context
>>> As little endian, X15 should be 0x78:
>>> X15 = 0x78
>>> Tracing basic block at 0x200018, block size = 0x4
>>> Tracing basic block at 0x200028, block size = 0x4
### B-inst Test Failed on uc_emu_start() with error returned: 21
PC = 0x0000000000200028
-------------------------
Emulate ARM64 Big-Endian code
>>> Tracing basic block at 0x10000, block size = 0x8
>>> Tracing instruction at 0x10000, instruction size = 0x4
>>> Emulation done. Below is the CPU context
>>> As big endian, X15 should be 0x78:
>>> X15 = 0x12
-------------------------
Read the SCTLR register.
>>> SCTLR_EL1 = 0xc50838
>>> SCTLR_EL2 = 0x0
-------------------------
Hook MRS instruction.
>>> Hook MSR instruction. Write 0x114514 to X2.
>>> X2 = 0x114514
-----------------------------------------------------------------------------------------------------
I think "B-inst Test Failed on uc_emu_start() with error returned: 21" is not correct, that it should return an UC_ERR_OK.

Please check!
I need your help!
Thanks a lot.

**Comment by naveen126** [comment]
> 

There are some steps to recover this issue.
I have got a little AARCH64 asm, the dump file is like this:
Disassembly of section .text:

0000000000200000 <_start>:
  200000:	d2803421 	mov	x1, #0x1a1                 	// #417
  200004:	91000422 	add	x2, x1, #0x1
  200008:	91000443 	add	x3, x2, #0x1
  20000c:	91000464 	add	x4, x3, #0x1
  200010:	91000485 	add	x5, x4, #0x1
  200014:	910004a6 	add	x6, x5, #0x1
  200018:	14000004 	b	200028 <main>
  20001c:	12001c00 	and	w0, w0, #0xff
  200020:	9b007c0a 	mul	x10, x0, x0
  200024:	9b007d4a 	mul	x10, x10, x0

0000000000200028 <main>:
  200028:	5800010b 	ldr	x11, 200048 <halt+0x4>
  20002c:	5800012c 	ldr	x12, 200050 <halt+0xc>
  200030:	5800014d 	ldr	x13, 200058 <halt+0x14>
  200034:	f90001ab 	str	x11, [x13]
  200038:	f90069ac 	str	x12, [x13, #208]
  20003c:	f94001b5 	ldr	x21, [x13]
  200040:	f94069b6 	ldr	x22, [x13, #208]

0000000000200044 <halt>:
  200044:	14000000 	b	200044 <halt>
  200048:	cafebeef 	eon	x15, x23, x30, ror #47
  20004c:	00000000 	udf	#0
  200050:	a1b2c3d4 	.inst	0xa1b2c3d4 ; undefined
  200054:	00000000 	udf	#0
  200058:	d00d0000 	adrp	x0, 1a202000 <__bss_end+0x1a001fa0>
  20005c:	00000000 	udf	#0

Firstly, Add the following code in front of test_arm64 in the file sample_arm64.c.
    uint64_t mem_data = 0;
    uint64_t pc_addr = 0;
    uint32_t isa_word = 0;
    char     isa_bytes[4];
Secondly, add the following code at end of test_arm64 in the file sample_arm64.c.
    // 14000004 	b	200028 <main>
    isa_word = 0x14000004;
    pc_addr = 0x200018;
    memcpy(isa_bytes, &isa_word, 4);
    uc_mem_write(uc, pc_addr, isa_bytes, 4);
    err = uc_emu_start(uc, pc_addr, pc_addr + 3, 0, 0);
    if (err) {
        printf("B-inst Test Failed on uc_emu_start() with error returned: %u\n", err);
    }

    err = uc_reg_read(uc, UC_ARM64_REG_PC, &mem_data);
    if (err) {
        printf("Read PC_reg Failed on uc_emu_start() with error returned: %u\n", err);
    }
    printf("PC = 0x%016lx\n", mem_data);

**Now, the whole test_arm64 function is:**

static void test_arm64(void)
{
    uc_engine *uc;
    uc_err err;
    uc_hook trace1, trace2;

    uint64_t mem_data = 0;
    uint64_t pc_addr = 0;
    uint32_t isa_word = 0;
    char     isa_bytes[4];

    int64_t x11 = 0x12345678;    // X11 register
    int64_t x13 = 0x10000 + 0x8; // X13 register
    int64_t x15 = 0x33;          // X15 register

    printf("Emulate ARM64 code\n");

    // Initialize emulator in ARM mode
    err = uc_open(UC_ARCH_ARM64, UC_MODE_ARM, &uc);
    if (err) {
        printf("Failed on uc_open() with error returned: %u (%s)\n", err,
               uc_strerror(err));
        return;
    }

    // map 2MB memory for this emulation
    uc_mem_map(uc, ADDRESS, 2 * 1024 * 1024, UC_PROT_ALL);

    // write machine code to be emulated to memory
    uc_mem_write(uc, ADDRESS, ARM64_CODE, sizeof(ARM64_CODE) - 1);

    // initialize machine registers
    uc_reg_write(uc, UC_ARM64_REG_X11, &x11);
    uc_reg_write(uc, UC_ARM64_REG_X13, &x13);
    uc_reg_write(uc, UC_ARM64_REG_X15, &x15);

    // tracing all basic blocks with customized callback
    uc_hook_add(uc, &trace1, UC_HOOK_BLOCK, hook_block, NULL, 1, 0);

    // tracing one instruction at ADDRESS with customized callback
    uc_hook_add(uc, &trace2, UC_HOOK_CODE, hook_code, NULL, ADDRESS, ADDRESS);

    // emulate machine code in infinite time (last param = 0), or when
    // finishing all the code.
    err = uc_emu_start(uc, ADDRESS, ADDRESS + sizeof(ARM64_CODE) - 1, 0, 0);
    if (err) {
        printf("Failed on uc_emu_start() with error returned: %u\n", err);
    }

    // now print out some registers
    printf(">>> Emulation done. Below is the CPU context\n");
    printf(">>> As little endian, X15 should be 0x78:\n");

    uc_reg_read(uc, UC_ARM64_REG_X15, &x15);
    printf(">>> X15 = 0x%" PRIx64 "\n", x15);

    // 14000004 	b	200028 <main>
    isa_word = 0x14000004;
    pc_addr = 0x200018;
    memcpy(isa_bytes, &isa_word, 4);
    uc_mem_write(uc, pc_addr, isa_bytes, 4);
    err = uc_emu_start(uc, pc_addr, pc_addr + 3, 0, 0);
    if (err) {
        printf("B-inst Test Failed on uc_emu_start() with error returned: %u\n", err);
    }

    err = uc_reg_read(uc, UC_ARM64_REG_PC, &mem_data);
    if (err) {
        printf("Read PC_reg Failed on uc_emu_start() with error returned: %u\n", err);
    }
    printf("PC = 0x%016lx\n", mem_data);


    uc_close(uc);
}

At last, following the steps in compile.md to build unicorn.
After building for unicorn, run the sample_arm64 in the ternimal.
././sample_arm64

**It turns out some information as bellow.**
>>> Emulate ARM64 fetching stack data from high address 10000000000000
>>> x0(Exception Level)=1
>>> X1 = 0xc8c8c8c8c8c8c8c8
Emulate ARM64 code
>>> Tracing basic block at 0x10000, block size = 0x8
>>> Tracing instruction at 0x10000, instruction size = 0x4
>>> Emulation done. Below is the CPU context
>>> As little endian, X15 should be 0x78:
>>> X15 = 0x78
>>> Tracing basic block at 0x200018, block size = 0x4
>>> Tracing basic block at 0x200028, block size = 0x4
### B-inst Test Failed on uc_emu_start() with error returned: 21
PC = 0x0000000000200028
-------------------------
Emulate ARM64 Big-Endian code
>>> Tracing basic block at 0x10000, block size = 0x8
>>> Tracing instruction at 0x10000, instruction size = 0x4
>>> Emulation done. Below is the CPU context
>>> As big endian, X15 should be 0x78:
>>> X15 = 0x12
-------------------------
Read the SCTLR register.
>>> SCTLR_EL1 = 0xc50838
>>> SCTLR_EL2 = 0x0
-------------------------
Hook MRS instruction.
>>> Hook MSR instruction. Write 0x114514 to X2.
>>> X2 = 0x114514
-----------------------------------------------------------------------------------------------------
I think "B-inst Test Failed on uc_emu_start() with error returned: 21" is not correct, that it should return an UC_ERR_OK.

Please check!
I need your help!
Thanks a lot.

**Comment by naveen126** [comment]
> It of course supports. You could have a reproduction script so that we can help.

Hi, do you have recovered this issue?
