### ISSUE TITLE
Setting CPU model of UC_CPU_ARM_926 errors with an invalid argument

### ISSUE THREAD

**Issue by InvoxiPlayGames** [unicorn-engine/unicorn#1655]
When setting the CPU model of an emulated Arm CPU to UC_CPU_ARM_926, an invalid argument error is thrown.

In uc.c, when setting `UC_CTL_CPU_MODEL`, there is a check to see if model is less than or **equal to** zero, but UC_CPU_ARM_926 = 0.

**Comment by wtdcode** [comment]
Fixed in 3d028882ed0006c4ccc53150b28cd4e3e0bd20fd
