### ISSUE TITLE
Setting up the GS/FS TIB context pointers.

### ISSUE THREAD

**Issue by 0xhicham** [unicorn-engine/unicorn#1674]
there is one particular problem : 

imagine we want to access GS:[0x30] after mapping the memory and setting up UC_X86_REG_GS_BASE into the correct TEB addr.

```
TEB = 0x1000
GS_BASE = 0x1000
GS:[0x30] = 0x1030 !!
```

so to correct it we can do something like : 

```
TEB = 0x1000
GS_BASE = 0xFF0
GS:[0x30] = 0x1000
```

the problem is that now GS:[0x60] = 0x1050 wish is incorrect for my actual mapped mem wish should point to the PEB.

How can i setup GS/FS indexes correctly ?

**Comment by wtdcode** [comment]
Sorry, I can't understand what you are asking... You probably would like to refer to the Intel manual.

**Comment by 0xhicham** [comment]
My question is simple : 

how can you manage to make this :

gs:[0x30] = 1FF569C000
gs:[0x60] = 1FF569B000

**Comment by 0xhicham** [comment]
cause if you do something like : 

reg_write(UC_X86_REG_GS, 1FF569C000 - 30)

this will fuck up gs:[60] index

**Comment by wtdcode** [comment]
> cause if you do something like :
> 
> reg_write(UC_X86_REG_GS, 1FF569C000 - 30)
> 
> this will fuck up gs:[60] index

`gs` only makes sense in real mode, you probably would like `gs.base` which corresponds to `UC_X86_REG_GS_BASE`. Again, Intel manual should be your friend.
