### ISSUE TITLE
macOS-arm64 slice in Homebrew binary

### ISSUE THREAD

**Issue by jacobcxdev** [unicorn-engine/unicorn#1696]
The latest available binary on Homebrew currently lacks a macOS-arm64 slice. This has been causing issues when linking against libunicorn.dylib and building for macOS-arm64 (e.g. any Apple Silicon Mac).

Below is an excerpt from my build log.
```
Ignoring file /usr/local/Cellar/unicorn/2.0.0/lib/libunicorn.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
```

**Comment by wtdcode** [comment]
Please fire your ticket to Homebrew as we are not responsible for publishing them on Homebrew. Thanks.
