### ISSUE TITLE
I got a EXCEPTION_ACCESS_VIOLATION while i emulate a multiple thread program.

### ISSUE THREAD

**Issue by linpinjin** [unicorn-engine/unicorn#1701]
It looks like something goes wrong in function 'translate-all.c :  page_collection_lock' ,  i don't know why.  Can someone help me?

VERSION: 

F:\Github\dear3>pip list |findstr uni
unicodecsv         0.14.1
unicorn            2.0.0

INFO FROM X64DBG:

EXCEPTION_DEBUG_INFO:
           dwFirstChance: 1
           ExceptionCode: C0000005 (EXCEPTION_ACCESS_VIOLATION)
          ExceptionFlags: 00000000
        ExceptionAddress: 00007FFDAAB9A180 unicorn.00007FFDAAB9A180
        NumberParameters: 2
ExceptionInformation[00]: 0000000000000000 Read
ExceptionInformation[01]: FFFFFFFFFFFFFFFF Inaccessible Address
Exception first chance at 00007FFDAAB9A180 (C0000005, EXCEPTION_ACCESS_VIOLATION)！

00007FFDAAB99FD0 <unicorn. | 48:895C24 08             | mov qword ptr ss:[rsp+8],rbx                    |
00007FFDAAB99FD5           | 55                       | push rbp                                        |
00007FFDAAB99FD6           | 56                       | push rsi                                        |
00007FFDAAB99FD7           | 57                       | push rdi                                        |
00007FFDAAB99FD8           | 41:54                    | push r12                                        |
00007FFDAAB99FDA           | 41:55                    | push r13                                        |
00007FFDAAB99FDC           | 41:56                    | push r14                                        |
00007FFDAAB99FDE           | 41:57                    | push r15                                        |
00007FFDAAB99FE0           | 48:83EC 20               | sub rsp,20                                      |
00007FFDAAB99FE4           | 4C:8BE9                  | mov r13,rcx                                     |
00007FFDAAB99FE7           | 49:8BD8                  | mov rbx,r8                                      |
00007FFDAAB99FEA           | B9 10000000              | mov ecx,10                                      |
00007FFDAAB99FEF           | 4C:8BF2                  | mov r14,rdx                                     |
00007FFDAAB99FF2           | E8 B9B5FFFF              | call <unicorn.sub_7FFDAAB955B0>                 |
00007FFDAAB99FF7           | 49:C1EE 0C               | shr r14,C                                       |
00007FFDAAB99FFB           | 48:8BF0                  | mov rsi,rax                                     |
00007FFDAAB99FFE           | 48:C1EB 0C               | shr rbx,C                                       |
00007FFDAAB9A002           | 4C:897424 68             | mov qword ptr ss:[rsp+68],r14                   |
00007FFDAAB9A007           | 48:895C24 70             | mov qword ptr ss:[rsp+70],rbx                   |
00007FFDAAB9A00C           | 4C:3BF3                  | cmp r14,rbx                                     |
00007FFDAAB9A00F           | 76 18                    | jbe unicorn.7FFDAAB9A029                        |
00007FFDAAB9A011           | 4C:8D05 00A86900         | lea r8,qword ptr ds:[7FFDAB234818]              | 00007FFDAB234818:"start <= end"
00007FFDAAB9A018           | BA 93020000              | mov edx,293                                     |
00007FFDAAB9A01D           | 48:8D0D 04A86900         | lea rcx,qword ptr ds:[7FFDAB234828]             | 00007FFDAB234828:"D:\\a\\unicorn\\unicorn\\qemu\\accel\\tcg\\translate-all.c"
00007FFDAAB9A024           | E8 278E6900              | call <unicorn.sub_7FFDAB232E50>                 |
00007FFDAAB9A029           | 4C:8D0D B0020000         | lea r9,qword ptr ds:[<sub_7FFDAAB9A2E0>]        |
00007FFDAAB9A030           | 45:33C0                  | xor r8d,r8d                                     |
00007FFDAAB9A033           | 33D2                     | xor edx,edx                                     |
00007FFDAAB9A035           | 48:8D0D C4160000         | lea rcx,qword ptr ds:[<sub_7FFDAAB9B700>]       |
00007FFDAAB9A03C           | E8 AFA5FFFF              | call <unicorn.sub_7FFDAAB945F0>                 |
00007FFDAAB9A041           | 48:8906                  | mov qword ptr ds:[rsi],rax                      |
00007FFDAAB9A044           | 48:C746 08 00000000      | mov qword ptr ds:[rsi+8],0                      |
00007FFDAAB9A04C           | 0F1F40 00                | nop dword ptr ds:[rax],eax                      |
00007FFDAAB9A050           | 49:B9 FFFFFFFFFFFF0F00   | mov r9,FFFFFFFFFFFFF                            |
00007FFDAAB9A05A           | 66:0F1F4400 00           | nop word ptr ds:[rax+rax],ax                    |
00007FFDAAB9A060           | 4C:3BF3                  | cmp r14,rbx                                     |
00007FFDAAB9A063           | 0F87 38020000            | ja unicorn.7FFDAAB9A2A1                         |
00007FFDAAB9A069           | 49:6385 80020000         | movsxd rax,dword ptr ds:[r13+280]               |
00007FFDAAB9A070           | 49:8BD6                  | mov rdx,r14                                     |
00007FFDAAB9A073           | 41:8B8D 84020000         | mov ecx,dword ptr ds:[r13+284]                  |
00007FFDAAB9A07A           | 48:FFC8                  | dec rax                                         |
00007FFDAAB9A07D           | 48:D3EA                  | shr rdx,cl                                      |
00007FFDAAB9A080           | 48:23D0                  | and rdx,rax                                     |
00007FFDAAB9A083           | 49:8B85 70020000         | mov rax,qword ptr ds:[r13+270]                  |
00007FFDAAB9A08A           | 4C:8D04D0                | lea r8,qword ptr ds:[rax+rdx*8]                 |
00007FFDAAB9A08E           | 41:8B95 88020000         | mov edx,dword ptr ds:[r13+288]                  |
00007FFDAAB9A095           | 85D2                     | test edx,edx                                    |
00007FFDAAB9A097           | 7E 2B                    | jle unicorn.7FFDAAB9A0C4                        |
00007FFDAAB9A099           | 8D0C92                   | lea ecx,qword ptr ds:[rdx+rdx*4]                |
00007FFDAAB9A09C           | 03C9                     | add ecx,ecx                                     |
00007FFDAAB9A09E           | 66:90                    | nop                                             |
00007FFDAAB9A0A0           | 4D:8B00                  | mov r8,qword ptr ds:[r8]                        |
00007FFDAAB9A0A3           | 4D:85C0                  | test r8,r8                                      |
00007FFDAAB9A0A6           | 0F84 E8010000            | je unicorn.7FFDAAB9A294                         |
00007FFDAAB9A0AC           | 49:8BC6                  | mov rax,r14                                     |
00007FFDAAB9A0AF           | FFCA                     | dec edx                                         |
00007FFDAAB9A0B1           | 48:D3E8                  | shr rax,cl                                      |
00007FFDAAB9A0B4           | 83E9 0A                  | sub ecx,A                                       |
00007FFDAAB9A0B7           | 25 FF030000              | and eax,3FF                                     |
00007FFDAAB9A0BC           | 4D:8D04C0                | lea r8,qword ptr ds:[r8+rax*8]                  |
00007FFDAAB9A0C0           | 85D2                     | test edx,edx                                    |
00007FFDAAB9A0C2           | 7F DC                    | jg unicorn.7FFDAAB9A0A0                         |
00007FFDAAB9A0C4           | 49:8B08                  | mov rcx,qword ptr ds:[r8]                       |
00007FFDAAB9A0C7           | 48:85C9                  | test rcx,rcx                                    |
00007FFDAAB9A0CA           | 0F84 C4010000            | je unicorn.7FFDAAB9A294                         |
00007FFDAAB9A0D0           | 49:8BC6                  | mov rax,r14                                     |
00007FFDAAB9A0D3           | 25 FF030000              | and eax,3FF                                     |
00007FFDAAB9A0D8           | 48:8D0440                | lea rax,qword ptr ds:[rax+rax*2]                |
00007FFDAAB9A0DC           | 48:8D3CC1                | lea rdi,qword ptr ds:[rcx+rax*8]                |
00007FFDAAB9A0E0           | 48:85FF                  | test rdi,rdi                                    |
00007FFDAAB9A0E3           | 0F84 AB010000            | je unicorn.7FFDAAB9A294                         |
00007FFDAAB9A0E9           | 48:8B0E                  | mov rcx,qword ptr ds:[rsi]                      |
00007FFDAAB9A0EC           | 48:8D5424 78             | lea rdx,qword ptr ss:[rsp+78]                   |
00007FFDAAB9A0F1           | 49:8BC6                  | mov rax,r14                                     |
00007FFDAAB9A0F4           | 49:23C1                  | and rax,r9                                      |
00007FFDAAB9A0F7           | 48:894424 78             | mov qword ptr ss:[rsp+78],rax                   |
00007FFDAAB9A0FC           | E8 8FA4FFFF              | call <unicorn.sub_7FFDAAB94590>                 |
00007FFDAAB9A101           | 48:85C0                  | test rax,rax                                    |
00007FFDAAB9A104           | 75 59                    | jne unicorn.7FFDAAB9A15F                        |
00007FFDAAB9A106           | 48:8B5424 78             | mov rdx,qword ptr ss:[rsp+78]                   |
00007FFDAAB9A10B           | 49:8BCD                  | mov rcx,r13                                     |
00007FFDAAB9A10E           | E8 DD010000              | call <unicorn.sub_7FFDAAB9A2F0>                 |
00007FFDAAB9A113           | 48:8BE8                  | mov rbp,rax                                     |
00007FFDAAB9A116           | 48:85C0                  | test rax,rax                                    |
00007FFDAAB9A119           | 74 44                    | je unicorn.7FFDAAB9A15F                         |
00007FFDAAB9A11B           | 48:8B5C24 78             | mov rbx,qword ptr ss:[rsp+78]                   |
00007FFDAAB9A120           | B9 18000000              | mov ecx,18                                      |
00007FFDAAB9A125           | E8 86B4FFFF              | call <unicorn.sub_7FFDAAB955B0>                 |
00007FFDAAB9A12A           | 4C:8BC0                  | mov r8,rax                                      |
00007FFDAAB9A12D           | 4C:8BF0                  | mov r14,rax                                     |
00007FFDAAB9A130           | 48:8958 08               | mov qword ptr ds:[rax+8],rbx                    |
00007FFDAAB9A134           | 48:8D50 08               | lea rdx,qword ptr ds:[rax+8]                    |
00007FFDAAB9A138           | 48:8928                  | mov qword ptr ds:[rax],rbp                      |
00007FFDAAB9A13B           | 48:8B0E                  | mov rcx,qword ptr ds:[rsi]                      |
00007FFDAAB9A13E           | E8 CDA1FFFF              | call <unicorn.sub_7FFDAAB94310>                 |
00007FFDAAB9A143           | 48:8B4E 08               | mov rcx,qword ptr ds:[rsi+8]                    |
00007FFDAAB9A147           | 48:85C9                  | test rcx,rcx                                    |
00007FFDAAB9A14A           | 74 0A                    | je unicorn.7FFDAAB9A156                         |
00007FFDAAB9A14C           | 48:8B49 08               | mov rcx,qword ptr ds:[rcx+8]                    |
00007FFDAAB9A150           | 49:394E 08               | cmp qword ptr ds:[r14+8],rcx                    |
00007FFDAAB9A154           | 76 04                    | jbe unicorn.7FFDAAB9A15A                        |
00007FFDAAB9A156           | 4C:8976 08               | mov qword ptr ds:[rsi+8],r14                    |
00007FFDAAB9A15A           | 4C:8B7424 68             | mov r14,qword ptr ss:[rsp+68]                   |
00007FFDAAB9A15F           | 8B2F                     | mov ebp,dword ptr ds:[rdi]                      |
00007FFDAAB9A161           | 48:8B1F                  | mov rbx,qword ptr ds:[rdi]                      |
00007FFDAAB9A164           | 83E5 01                  | and ebp,1                                       |
00007FFDAAB9A167           | 48:83E3 FE               | and rbx,FFFFFFFFFFFFFFFE                        |
00007FFDAAB9A16B           | 0F84 14010000            | je unicorn.7FFDAAB9A285                         |
00007FFDAAB9A171           | 0F1F40 00                | nop dword ptr ds:[rax],eax                      |
00007FFDAAB9A175           | 666666:0F1F8400 00000000 | nop word ptr ds:[rax+rax],ax                    |
00007FFDAAB9A180           | 48:8B43 48               | mov rax,qword ptr ds:[rbx+48]                   | EXCEPTION_ACCESS_VIOLATION ===========================================================
00007FFDAAB9A184           | 48:8D5424 78             | lea rdx,qword ptr ss:[rsp+78]                   |
00007FFDAAB9A189           | 48:8B0E                  | mov rcx,qword ptr ds:[rsi]                      |
00007FFDAAB9A18C           | 48:C1E8 0C               | shr rax,C                                       |
00007FFDAAB9A190           | 48:894424 78             | mov qword ptr ss:[rsp+78],rax                   |
00007FFDAAB9A195           | E8 F6A3FFFF              | call <unicorn.sub_7FFDAAB94590>                 |
00007FFDAAB9A19A           | 48:85C0                  | test rax,rax                                    |
00007FFDAAB9A19D           | 75 54                    | jne unicorn.7FFDAAB9A1F3                        |
00007FFDAAB9A19F           | 48:8B5424 78             | mov rdx,qword ptr ss:[rsp+78]                   |
00007FFDAAB9A1A4           | 49:8BCD                  | mov rcx,r13                                     |
00007FFDAAB9A1A7           | E8 44010000              | call <unicorn.sub_7FFDAAB9A2F0>                 |
00007FFDAAB9A1AC           | 4C:8BF8                  | mov r15,rax                                     |
00007FFDAAB9A1AF           | 48:85C0                  | test rax,rax                                    |
00007FFDAAB9A1B2           | 74 3F                    | je unicorn.7FFDAAB9A1F3                         |
00007FFDAAB9A1B4           | 48:8B7C24 78             | mov rdi,qword ptr ss:[rsp+78]                   |
00007FFDAAB9A1B9           | B9 18000000              | mov ecx,18                                      |
00007FFDAAB9A1BE           | E8 EDB3FFFF              | call <unicorn.sub_7FFDAAB955B0>                 |
00007FFDAAB9A1C3           | 4C:8BC0                  | mov r8,rax                                      |
00007FFDAAB9A1C6           | 4C:8BF0                  | mov r14,rax                                     |
00007FFDAAB9A1C9           | 48:8978 08               | mov qword ptr ds:[rax+8],rdi                    |
00007FFDAAB9A1CD           | 48:8D50 08               | lea rdx,qword ptr ds:[rax+8]                    |
00007FFDAAB9A1D1           | 4C:8938                  | mov qword ptr ds:[rax],r15                      |
00007FFDAAB9A1D4           | 48:8B0E                  | mov rcx,qword ptr ds:[rsi]                      |
00007FFDAAB9A1D7           | E8 34A1FFFF              | call <unicorn.sub_7FFDAAB94310>                 |
00007FFDAAB9A1DC           | 48:8B4E 08               | mov rcx,qword ptr ds:[rsi+8]                    |
00007FFDAAB9A1E0           | 48:85C9                  | test rcx,rcx                                    |
00007FFDAAB9A1E3           | 74 0A                    | je unicorn.7FFDAAB9A1EF                         |
00007FFDAAB9A1E5           | 48:8B49 08               | mov rcx,qword ptr ds:[rcx+8]                    |
00007FFDAAB9A1E9           | 49:394E 08               | cmp qword ptr ds:[r14+8],rcx                    |
00007FFDAAB9A1ED           | 76 04                    | jbe unicorn.7FFDAAB9A1F3                        |
00007FFDAAB9A1EF           | 4C:8976 08               | mov qword ptr ds:[rsi+8],r14                    |
00007FFDAAB9A1F3           | 48:8B43 50               | mov rax,qword ptr ds:[rbx+50]                   |
00007FFDAAB9A1F7           | 48:83F8 FF               | cmp rax,FFFFFFFFFFFFFFFF                        |
00007FFDAAB9A1FB           | 74 6F                    | je unicorn.7FFDAAB9A26C                         |
00007FFDAAB9A1FD           | 48:8B0E                  | mov rcx,qword ptr ds:[rsi]                      |
00007FFDAAB9A200           | 48:8D5424 78             | lea rdx,qword ptr ss:[rsp+78]                   |
00007FFDAAB9A205           | 48:C1E8 0C               | shr rax,C                                       |
00007FFDAAB9A209           | 48:894424 78             | mov qword ptr ss:[rsp+78],rax                   |
00007FFDAAB9A20E           | E8 7DA3FFFF              | call <unicorn.sub_7FFDAAB94590>                 |
00007FFDAAB9A213           | 48:85C0                  | test rax,rax                                    |
00007FFDAAB9A216           | 75 54                    | jne unicorn.7FFDAAB9A26C                        |
00007FFDAAB9A218           | 48:8B5424 78             | mov rdx,qword ptr ss:[rsp+78]                   |
00007FFDAAB9A21D           | 49:8BCD                  | mov rcx,r13                                     |
00007FFDAAB9A220           | E8 CB000000              | call <unicorn.sub_7FFDAAB9A2F0>                 |
00007FFDAAB9A225           | 4C:8BF8                  | mov r15,rax                                     |
00007FFDAAB9A228           | 48:85C0                  | test rax,rax                                    |
00007FFDAAB9A22B           | 74 3F                    | je unicorn.7FFDAAB9A26C                         |
00007FFDAAB9A22D           | 48:8B7C24 78             | mov rdi,qword ptr ss:[rsp+78]                   |
00007FFDAAB9A232           | B9 18000000              | mov ecx,18                                      |
00007FFDAAB9A237           | E8 74B3FFFF              | call <unicorn.sub_7FFDAAB955B0>                 |
00007FFDAAB9A23C           | 4C:8BC0                  | mov r8,rax                                      |
00007FFDAAB9A23F           | 4C:8BF0                  | mov r14,rax                                     |
00007FFDAAB9A242           | 48:8978 08               | mov qword ptr ds:[rax+8],rdi                    |
00007FFDAAB9A246           | 48:8D50 08               | lea rdx,qword ptr ds:[rax+8]                    |
00007FFDAAB9A24A           | 4C:8938                  | mov qword ptr ds:[rax],r15                      |
00007FFDAAB9A24D           | 48:8B0E                  | mov rcx,qword ptr ds:[rsi]                      |
00007FFDAAB9A250           | E8 BBA0FFFF              | call <unicorn.sub_7FFDAAB94310>                 |
00007FFDAAB9A255           | 48:8B4E 08               | mov rcx,qword ptr ds:[rsi+8]                    |
00007FFDAAB9A259           | 48:85C9                  | test rcx,rcx                                    |
00007FFDAAB9A25C           | 74 0A                    | je unicorn.7FFDAAB9A268                         |
00007FFDAAB9A25E           | 48:8B49 08               | mov rcx,qword ptr ds:[rcx+8]                    |
00007FFDAAB9A262           | 49:394E 08               | cmp qword ptr ds:[r14+8],rcx                    |
00007FFDAAB9A266           | 76 04                    | jbe unicorn.7FFDAAB9A26C                        |
00007FFDAAB9A268           | 4C:8976 08               | mov qword ptr ds:[rsi+8],r14                    |
00007FFDAAB9A26C           | 48:8B5CEB 38             | mov rbx,qword ptr ds:[rbx+rbp*8+38]             |
00007FFDAAB9A271           | 8BEB                     | mov ebp,ebx                                     |
00007FFDAAB9A273           | 83E5 01                  | and ebp,1                                       |
00007FFDAAB9A276           | 48:83E3 FE               | and rbx,FFFFFFFFFFFFFFFE                        |
00007FFDAAB9A27A           | 0F85 00FFFFFF            | jne unicorn.7FFDAAB9A180                        |
00007FFDAAB9A280           | 4C:8B7424 68             | mov r14,qword ptr ss:[rsp+68]                   |
00007FFDAAB9A285           | 48:8B5C24 70             | mov rbx,qword ptr ss:[rsp+70]                   |
00007FFDAAB9A28A           | 49:B9 FFFFFFFFFFFF0F00   | mov r9,FFFFFFFFFFFFF                            |
00007FFDAAB9A294           | 49:FFC6                  | inc r14                                         |
00007FFDAAB9A297           | 4C:897424 68             | mov qword ptr ss:[rsp+68],r14                   |
00007FFDAAB9A29C           | E9 BFFDFFFF              | jmp unicorn.7FFDAAB9A060                        |
00007FFDAAB9A2A1           | 48:8B5C24 60             | mov rbx,qword ptr ss:[rsp+60]                   |
00007FFDAAB9A2A6           | 48:8BC6                  | mov rax,rsi                                     |
00007FFDAAB9A2A9           | 48:83C4 20               | add rsp,20                                      |
00007FFDAAB9A2AD           | 41:5F                    | pop r15                                         |
00007FFDAAB9A2AF           | 41:5E                    | pop r14                                         |
00007FFDAAB9A2B1           | 41:5D                    | pop r13                                         |
00007FFDAAB9A2B3           | 41:5C                    | pop r12                                         |
00007FFDAAB9A2B5           | 5F                       | pop rdi                                         |
00007FFDAAB9A2B6           | 5E                       | pop rsi                                         |
00007FFDAAB9A2B7           | 5D                       | pop rbp                                         |
00007FFDAAB9A2B8           | C3                       | ret                                             |
00007FFDAAB9A2B9           | CC                       | int3                                            |

**Comment by PhilippTakacs** [comment]
Can you provide a reproduction script?
