### ISSUE TITLE
Wrong type hint for reg_write in Python bindings

### ISSUE THREAD

**Issue by Sh4ww** [unicorn-engine/unicorn#1706]
I found a wrong type hint for ``reg_write`` method of ``Uc`` in Python bindings. 

Wrong:
```python
def reg_write(self, reg_id: Union[int, ARMCPRegValue, ARM64CPRegValue, X86MMRReg, X86FPReg], value: int):
    ...
```
Correct:
```python
def reg_write(self, reg_id: int, value: Union[int, ARMCPRegValue, ARM64CPRegValue, X86MMRReg, X86FPReg]):
    ...
```

I want to submit a PR to fix it, but I noticed that you are refactoring the python bindings and maybe release it in the next version. So I doubt if this fix is necessary?

**Comment by wtdcode** [comment]
Good catch. The refactor might stall for a while so you can submit it firstly.
