### ISSUE TITLE
Rust: Ability to pass the user data to the add_code_hook function

### ISSUE THREAD

**Issue by r3bb1t** [unicorn-engine/unicorn#1721]
Right now i can't find a proper way to fill some specific variables in my code during emulation. The only good idea came to my head is declaring the global variables and refer to them by using the ***unsafe*** blocks.

I'd like to do it in a more safe way.
In other words, C and Python provides the parameter for user data, while rust bindings don't. (i talk about the function "uc_hook_add").

**Comment by wtdcode** [comment]
Note you can bind your variables to the hook. Maybe you could have a look at the rust book.

**Comment by r3bb1t** [comment]
I'm quite new to rust programming. Can you please provide a simple example on how to do it? I can't figure it out on my own.
