### ISSUE TITLE
 Whether the [ldab] instruction supports

### ISSUE THREAD

**Issue by crazy-copy** [unicorn-engine/unicorn#1724]
```
<CsInsn 0x40000000 [70b5]: push {r4, r5, r6, lr}>
<CsInsn 0x40000002 [0546]: mov r5, r0>
<CsInsn 0x40000004 [2148]: ldr r0, [pc, #0x84]>
<CsInsn 0x40000006 [0c46]: mov r4, r1>
<CsInsn 0x40000008 [7844]: add r0, pc>
<CsInsn 0x4000000a [d0e88f0f]: ldab r0, [r0]>
Traceback (most recent call last):
  File "C:\Users\crazystone\PycharmProjects\pythonProject\main.py", line 34, in <module>
    uc.emu_start(0x40000000 | 1, 0x40000000 + len(code) - 1)
  File "C:\Users\crazystone\PycharmProjects\pythonProject\venv\lib\site-packages\unicorn\unicorn.py", line 548, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid instruction (UC_ERR_INSN_INVALID)

Process finished with exit code 1
```

**Comment by crazy-copy** [comment]
##this is test code

from unicorn import *
from unicorn.arm_const import *
from capstone import *

cs = Cs(CS_ARCH_ARM, CS_MODE_THUMB)

code = bytes([0x70, 0xB5, 0x05, 0x46, 0x21, 0x48, 0x0C, 0x46, 0x78, 0x44,
              0xD0, 0xE8, 0x8F, 0x0F, 0xC0, 0x07, 0x1C, 0xD0])

STACK_SIZE = 1024 * 1024 * 5
STACK_BASE = 0XB0000000

uc = Uc(UC_ARCH_ARM, UC_MODE_ARM)
# statck
uc.mem_map(STACK_BASE, STACK_SIZE)
uc.reg_write(UC_ARM_REG_SP, STACK_BASE + STACK_SIZE - 0x10)

# code
uc.mem_map(0x40000000, 0x1000)
uc.mem_write(0x40000000, code)

uc.mem_map(0, 0x1000)


def hook_code(uc: Uc, address, size, data):
    for i in cs.disasm(uc.mem_read(address, size), address):
        print(i)


uc.hook_add(UC_HOOK_CODE, hook_code)

if __name__ == '__main__':
    uc.emu_start(0x40000000 | 1, 0x40000000 + len(code) - 1)

**Comment by wtdcode** [comment]
See #1725 You have to set the CPU model.

Maybe a new FAQ should be added...
