### ISSUE TITLE
aarch64 target support for running code in AARCH32 execution state

### ISSUE THREAD

**Issue by enwony** [unicorn-engine/unicorn#1727]
Referencing arm A-series manual arm cpu working in two "execution states": aarch64(64 bit arm command set) and aarch32 (arm and thumb command set) - compat mode.

But I can't find if I can run 32-bit payload on 64 bit host in such mode, even if I set env->pstate[4] bit and env->aarch64 = 0 it seems that only aarch64 decoder used - first decoded command generate interrupt 1 (EXCP_UDEF) - mean command not decoded.

In current qemu unicorn codebase I find pieces that care about env->aarch64 when changing of exception level, but it seems that code is not effective.

When I ran this 32bit payload code on 32-bit arm host, it works well, but I met conditions when mode switch would be helpful.

My question, does unicorn support such transitions in execution states? Is it planned?

**Comment by wtdcode** [comment]
https://www.qemu.org/docs/master/system/arm/cpu-features.html

**Comment by enwony** [comment]
Thank you for the answer!
I spent bunch of hours try to figure out if there some logic exists in emu code to switch between aarch32/aarch64.
Does anybody know thread on qemu where such feature discussed? 
This feature would be very helpful to emulate or debug exception level/architecture switch.
