### ISSUE TITLE
Does the ARM/THUMB mode in CPSR get reset when (re)starting Unicorn emulation?

### ISSUE THREAD

**Issue by lemonjesus** [unicorn-engine/unicorn#1729]
I'm writing [an emulator for an iPod](https://github.com/lemonjesus/iPod-n3g-emulator). The firmware will switch between ARM and THUMB several times during normal execution. A feature I'm trying to write into the emulator is the ability to set breakpoints or send SIGQUIT and enter the debugger from there. If you do this during THUMB execution, it breaks because it seems the CPU switches back to ARM mode and thus incorrectly executes code and eventually fails.

The way I differentiate between ARM and THUMB in my code is always `cpsr & 0x20`. During normal execution, the switch from ARM to THUMB works as expected:

```
[...]
Tracing ARM instruction at 0x2201f6b8 instruction = blx #0xffffff3c (0xFAFFFFCD)
Tracing THUMB instruction at 0x2201f5f4 instruction = push {r1, r2, r3, lr} (0x0000B50E)
[...]
```
However, when I invoke my interactive debugger with SIGQUIT (or any other way) while executing instructions in THUMB mode, it seems that a call to `uc_emu_start` resets the `cpsr`.

First, I stop the emulation from inside a code hook [by calling `uc_emu_stop`](https://github.com/lemonjesus/iPod-n3g-emulator/blob/ab2e0690c6a3b716f39eb312188f37e632490a39/debugger.c#L243-L246). The interactive debugger runs:
```
[...]
Tracing THUMB instruction at 0x2200e826 instruction = ldr r0, [pc, #0x298] (0x000048A6)
^\
Stopping the emulation
DEBUGGER!
PC = 0x2200e798, inst = lsls r0, r0, #0x1f (0x     7C0)
CSPR = 0x600000FF
R0 = 0xf0       R1 = 0xffffffff R2 = 0x100      R3 = 0x2203f3a4 R4 = 0x1        R5 = 0x2203f3a4 R6 = 0x2        R7 = 0x3c600000
R8 = 0x0        SB = 0x0        SL = 0x0        FP = 0x0        IP = 0xffbb55e0 SP = 0x0        LR = 0x0        PC = 0x0
PROCESSOR IS IN THUMB MODE
```

The `c` command is used to resume emulation which eventually results in this code being run:
```c
uc_reg_read(uc, UC_ARM_REG_PC, &pc);
start_emulation(uc, pc + size, 0);
```

Before the call to `uc_emu_start` in [`start_emulation`](https://github.com/lemonjesus/iPod-n3g-emulator/blob/ab2e0690c6a3b716f39eb312188f37e632490a39/emulator.c#L163-L196) it prints the CPU mode once more to confirm it's still in THUMB mode based on the `cpsr` and then immediately starts executing instructions in ARM mode.
```
> c
Resuming emulation
CPU is in THUMB mode
Tracing ARM instruction at 0x2200e79a instruction = ldmdbvs r8!, {r4, r8, ip, lr, pc} (0x6938D110)
Failed to disassemble given code! 0x2200E79E: 0xD1FC2800 4 0
[repeats errors until a bad instruction breaks Unicorn]
```

Based on my understanding, a `uc_engine` should keep its internal state including the `cpsr` between stops and starts, however it's getting modified by `uc_emu_start` at which point it's too late to force it back. The only reason I can think of is because I create the `uc_engine` with `UC_ARCH_ARM` and `UC_MODE_ARM` and calling `uc_emu_start` resets the `cpsr` to respect the mode, but since there's already a state set, this shouldn't happen.

Is my understanding correct? Am I doing something wrong?

**Comment by wtdcode** [comment]
https://github.com/unicorn-engine/unicorn/wiki/FAQ#emulating-some-instructions-gives-an-error-like-invalid-instruction-what-should-i-do

> If you are on ARM, please check whether you are emulating a THUMB instruction. If so, please use UC_MODE_THUMB and make sure the starting address is odd.

Is this your case?

**Comment by lemonjesus** [comment]
> make sure the starting address is odd

Interesting... I think I may have fixed it with just:

```c
start |= (cpsr & 0x20) ? 1 : 0;
```

So that's good. But in my mind it's still an interesting behavior that the `cpsr` isn't treated as the source of truth when it comes to determining mode. I certainly don't think `uc_emu_start` should touch the state of the engine other than emulating it. But I guess this approach makes sense on some level because, in a way, you're telling Unicorn to `bx` to some address given some engine state, and since it's really an ARM engine, you need to set that bit once when "resuming" execution.

I'll close this issue since it's solved, but if my understanding about the underlying architecture or how Unicorn is designed, let me know. Always happy to learn stuff. 🙂
