### ISSUE TITLE
Feature request: Add nanomips support

### ISSUE THREAD

**Issue by bkerler** [unicorn-engine/unicorn#1731]
Hi,

as qemu already supports the nanomips architecture for quite a while, how hard is it to add it to unicorn (cpu i7200) ?

Currently quite a lot of newer mips devices seem to make usage of it (including for example all Mediatek 5G modems), and having it in unicorn would be awesome.

[Instruction set](https://s3-eu-west-1.amazonaws.com/downloads-mips/I7200/I7200+product+launch/MIPS_nanomips32_ISA_TRM_01_01_MD01247.pdf)

[NanoMips system emulator / qemu](https://qemu-project.gitlab.io/qemu/system/target-mips.html)

**Comment by aquynh** [comment]
That is a lot of effort.

If you can sponsor this work, contact us.

**Comment by wtdcode** [comment]
If you expect the CPU implementation, it's already there. See https://github.com/unicorn-engine/unicorn/blob/241a391cecacda2b1463b873e6de6a7b9a35ba4c/include/unicorn/mips.h#L39 

However, if you expect the board emulation, you could contact us.

**Comment by bkerler** [comment]
Ok, so if the i7200 cpu would be selected, then code snippets using nanomips instruction set could be emulated with the current unicorn code ?
I don't think board emulation is necessary at this point.

**Comment by wtdcode** [comment]
> Ok, so if the i7200 cpu would be selected, then code snippets using nanomips instruction set could be emulated with the current unicorn code ? I don't think board emulation is necessary at this point.

Yes, correct.
