### ISSUE TITLE
Python binding build error in macbook silicon

### ISSUE THREAD

**Issue by SajjadPourali** [unicorn-engine/unicorn#1734]
Hey

I am facing to build issues because of the following test file in macbook silicon.
https://github.com/unicorn-engine/unicorn/blob/241a391cecacda2b1463b873e6de6a7b9a35ba4c/tests/unit/endian.h#L53-L72

`Desktop/unicorn-2.0.1/tests/unit/endian.h:71:3: error: The file boost/detail/endian.hpp needs to be set up for your CPU type.`

Probably the `defined(__arm64__) || defined(__arm__)` should be added there.

**Comment by wtdcode** [comment]
#1730

**Comment by wtdcode** [comment]
Check https://github.com/unicorn-engine/unicorn/releases/tag/2.0.1.post1
