### ISSUE TITLE
M1 MacOS: # error The file boost/detail/endian.hpp needs to be set up for your CPU type.

### ISSUE THREAD

**Issue by GuaGithub** [unicorn-engine/unicorn#1738]
Can't compile Unicorn on M1 MacOS:

unicorn/tests/unit/endian.h:71:3: error: The file boost/detail/endian.hpp needs to be set up for your CPU type.
# error The file boost/detail/endian.hpp needs to be set up for your CPU type.
  ^

**Comment by wtdcode** [comment]
#1730

**Comment by wtdcode** [comment]
Check https://github.com/unicorn-engine/unicorn/releases/tag/2.0.1.post1
