### ISSUE TITLE
Compile in 'Debug' mode vs 'RelWithDebInfo' ?

### ISSUE THREAD

**Issue by Welgriv** [unicorn-engine/unicorn#1740]
What is the difference between compile with :
`cmake .. -DCMAKE_BUILD_TYPE=Debug`

and

`cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo`

?

Also its unclear in the CMake file which option are available for compiling and what they actually do :

> `//Choose the type of build, options are: None Debug Release RelWithDebInfo
> // MinSizeRel ...
> CMAKE_BUILD_TYPE:STRING=Debug`

For instance what does "..." means ?

It might be useful to put some info in the doc.

**Comment by wtdcode** [comment]
Google should be your fiend and it's not relevant to Unicorn.

https://stackoverflow.com/questions/48754619/what-are-cmake-build-type-debug-release-relwithdebinfo-and-minsizerel
