### ISSUE TITLE
Question regarding uc_open and uc_init or UC_INIT macro.

### ISSUE THREAD

**Issue by ZehMatt** [unicorn-engine/unicorn#1741]
Why is initialization not happening inside uc_open instead a lot of the functions use the macro UC_INIT which is this piece of code
```cpp
#define UC_INIT(uc)                                                            \
    if (unlikely(!(uc)->init_done)) {                                          \
        int __init_ret = uc_init(uc);                                          \
        if (unlikely(__init_ret != UC_ERR_OK)) {                               \
            return __init_ret;                                                 \
        }                                                                      \
    }
```
Wouldn't it make more sense to have the initialization done in uc_open instead of storing additional state and checking it every time one of the APIs is used such as uc_mem_map, uc_reg_read, etc.? To me it seems a bit pointless to have this as we are required to call uc_open first to obtain a new instance and that instance should be fully initialized. I'm wondering if there is a reason behind this, to me it seems safe to remove that UC_INIT macro and all the uses in all the functions if this is done in uc_open which also allows the user to pass more options such as the buffer size for TCG, passing options for initialization which happens later currently requires to store that in the context.

For context, heres how often UC_INIT is used:
![image](https://user-images.githubusercontent.com/5415177/206013040-46c4215f-35f5-48d5-a996-017447c4a71c.png)

**Comment by ZehMatt** [comment]
> > I'm wondering if there is a reason behind this
> 
> Check `uc_ctl`, where `UC_INIT` is not called in some places. This in fact allows us to pass more options to `uc_open` like CPU models, page size etc.
> 
> > if this is done in uc_open which also allows the user to pass more options such as the buffer size for TCG, passing options for initialization which happens later currently requires to store that in the context.
> 
> Unfortunately, this is impossible as it will **break both ABI and API** and we put compatibility first place.

I could refactor UC_INIT out without breaking the API, it would only break API if I change the signature of uc_open, or is that assumption incorrect? ABI wise I'm not 100% sure, uc_engine is passed as pointer so there shouldn't be a ABI break, unless people access the internals of the struct for some reason.

One alternative is to have uc_open_ext or whatever name where we can supply more settings for initialization without storing that for deferred initialization also. I do agree that API/ABI is important but I can probably work around it unless there are more reasons to why its done like this, I would be willing to work on this.

**Comment by wtdcode** [comment]
>  ABI wise I'm not 100% sure, uc_engine is passed as pointer so there shouldn't be a ABI break, unless people access the internals of the struct for some reason.

It depends on the calling convention, though I would assume in most cases it should work. However, it could indeed cause confusing and hard-to-debug problems for users.

> One alternative is to have uc_open_ext or whatever name where we can supply more settings for initialization without storing data for deferred initialization also.

This is also not good and we don't want two API doing almost the same thing, which destroys brevity and self-documenting. Only Win32 prefers that. :)

**Comment by ZehMatt** [comment]
> > ABI wise I'm not 100% sure, uc_engine is passed as pointer so there shouldn't be a ABI break, unless people access the internals of the struct for some reason.
> 
> It depends on the calling convention, though I would assume in most cases it should work. However, it could indeed cause confusing and hard-to-debug problems for users.
> 
> > One alternative is to have uc_open_ext or whatever name where we can supply more settings for initialization without storing data for deferred initialization also.
> 
> This is also not good and we don't want two API doing almost the same thing, which destroys brevity and self-documenting. Only Win32 prefers that. :)

What do you suggest?

**Comment by wtdcode** [comment]
> > > ABI wise I'm not 100% sure, uc_engine is passed as pointer so there shouldn't be a ABI break, unless people access the internals of the struct for some reason.
> > 
> > 
> > It depends on the calling convention, though I would assume in most cases it should work. However, it could indeed cause confusing and hard-to-debug problems for users.
> > > One alternative is to have uc_open_ext or whatever name where we can supply more settings for initialization without storing data for deferred initialization also.
> > 
> > 
> > This is also not good and we don't want two API doing almost the same thing, which destroys brevity and self-documenting. Only Win32 prefers that. :)
> 
> What do you suggest?

Current `uc_ctl` is already the best workaround we get so far. Why does lazy initialization look bad to you?

**Comment by ZehMatt** [comment]
> Why does lazy initialization look bad to you?

Because its not explicit, its not clear when the initialization actually happens, the fact that uc_ctl sometimes initializes and sometimes doesn't is pretty weird. This is also not really documented and can lead to surprises, calling uc_open and then uc_ctl with one of the settings that does UC_INIT may or may not allocate memory, since its not documented this may or may not be unwanted behavior.

**Comment by ZehMatt** [comment]
Going to close this, no further questions on this.
