### ISSUE TITLE
glib dependency

### ISSUE THREAD

**Issue by PhilippTakacs** [unicorn-engine/unicorn#1744]
For the vtlb (#1735 ) feature I would like to use some newer glib features (i.e. g_tree_lower_bound). Problem is the glib_combat version of glib is to old for this.

So I search for the reasons using glib_combat instead of depending on glib and found #686.

Besides the title of the issue, the glib dependency was not removed, it was replaced by depending on a private copy of glib. I think this combines the downsides of having a extra dependency and implementing everything yourself. So we have an old version of glib with neither bugfixes nor feature updates (and maybe some not obvious api-changes). To fix this I see two solutions:

1. remove glib dependency and replace the usage by some small self implemented data structures. That implementation may have a similar API.
2. remove glib_combat and depend on glib.

**Comment by aquynh** [comment]
I remember one of the reasons we had this glib copy was to support Windows
build.

Send in pull req if you can.
