### ISSUE TITLE
Mid-flight attached code hook not invoked "for some time?"

### ISSUE THREAD

**Issue by r0ptr** [unicorn-engine/unicorn#1747]
Hello!

This is a strange issue (looks like a regression), that I cannot reproduce on Unicorn 1.x . Basically, I start the emulation for a small piece of code, then attach a code hook, then let the emulation continue, and the code hook will not be invoked immediately (in my repro script, 250 instructions are skipped before it starts tracing them). Below is the repro script:

```py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import unicorn


def code_hook(uc, address, size, userdata):
    print('trace', hex(address))


def main():
    uc = unicorn.Uc(unicorn.UC_ARCH_X86, unicorn.UC_MODE_32)

    # Map two pages of `inc eax` instructions at address 0x0
    uc.mem_map(0x0, 4096 * 2)
    uc.mem_write(0x0, b'\x40' * 4096 * 2)

    # Map a single page that kicks off emulation (only two instructions)
    moveeax0_jmpeax = b'\xB8\x00\x00\x00\x00\xFF\xE0'
    endaddr = 0x20000 + len(moveeax0_jmpeax)
    uc.mem_map(0x20000, 4096)
    uc.mem_write(0x20000, moveeax0_jmpeax)

    # Execute only `mov eax, 0` and `jmp eax` instructions
    uc.emu_start(0x20000, endaddr, count=2)

    # PC is now at 0x0 , add hook to trace from this point onward
    uc.hook_add(unicorn.UC_HOOK_CODE, code_hook)

    # Code hook is invoked only from address: 0xfe , why?
    uc.emu_start(0x0, endaddr, count=8192)


if __name__ == '__main__':
    main()
```

Does anyone know what is happening? Is this a mistake on my side maybe?

**Comment by wtdcode** [comment]
https://github.com/unicorn-engine/unicorn/wiki/FAQ#editing-an-instruction-doesnt-take-effecthooks-added-during-emulation-are-not-called

**Comment by r0ptr** [comment]
Oh my, thanks a lot! so this is the first time I see that a FAQ page even exists! And it's filled with so much useful information! thanks again!
