### ISSUE TITLE
Consider controlling the arch list through features in rust.

### ISSUE THREAD

**Issue by edsky** [unicorn-engine/unicorn#1748]
I have encountered a strange problem. Using debug to compile under mips can succeed, but release compilation fails, and the error is as follows:
```
undefined reference to `helper_atomic_ldo_le_mmu_ppc64'
undefined reference to `helper_atomic_sto_be_mmu_s390x'
undefined reference to `helper_atomic_cmpxchgo_le_mmu_aarch64'
```
And so on.
A simple fix is to use only the required arch, add in `unicorn/bindings/rust/build.rs`
```
     let dst = config
         .define("UNICORN_BUILD_TESTS", "OFF")
         .define("UNICORN_INSTALL", "OFF")
+        .define("UNICORN_ARCH", "x86")
         .no_build_target(true)
         .build();
```
So I suggest here to add a feature to cargo to support different needs.

**Comment by wtdcode** [comment]
Unfortunately we never tried to build Unicorn on mips, why would you like to do that?

**Comment by edsky** [comment]
I need to simulate and run x86-64 assembly instructions on mips64. There are many difficulties in translating instructions, and it can be successfully run on mips64.

It is working very well at present, but a small problem is that the arch list needs to only support x86, and some ABIs of rust have problems, and some types need to be converted to isize, otherwise there will be problems with big and small endian.

**Comment by wtdcode** [comment]
Would you like to submit a pr for uc_arch support for rust? I can fix the symbols clash.
________________________________
