### ISSUE TITLE
unicorn.unicorn.UcError: Invalid argument (UC_ERR_ARG)

### ISSUE THREAD

**Issue by lyg4795** [unicorn-engine/unicorn#1750]
The following code will raise unicorn.unicorn.UcError: Invalid argument (UC_ERR_ARG)
···
    mu = Uc(UC_ARCH_ARM64, UC_MODE_ARM)
    address=0x10000
    mu.mem_map(address,  1024*1024)
    mu.mem_map(0x7dd9cfb6c0,  1024)
···
but I change the last code to  mu.mem_map(0x7dd9cfb000,  1024)
I will work?
Why?

**Comment by wtdcode** [comment]
Yes, you have to ensure the start address is properly aligned.

**Comment by wtdcode** [comment]
Closed due to inactivity.
