### ISSUE TITLE
Hot\Dynamicly patching in UnciornV2.0.1.post1

### ISSUE THREAD

**Issue by OSPFvX** [unicorn-engine/unicorn#1752]
Guys, hello everyone! Merry Christmas to everyone!
When patching values in the code (using uc_mem_write), which emulates Unicorn, I observe the following problem:
When I patch the values, they are written like this:
```
for (ZyanUSize i = 0; i < TT+1; ++i)
{
uc_mem_write(uc, RIP + i, &NOP_data[i], 1);
}
```
Then unicorn sees opcodes that are patched but executes the original instructions anyway, i.e.
As you can see in the screenshot, instead of nop, I have the original instructions executed, namely:
https://ibb.co/MV2mR4S
```
PUSH RDI
LEA RDI, QWORD PTR DS:[0x154340105]
XCHG QWORD PTR SS:[RSP], RDI
RET
```
P.S. TL DR
I am experiencing problems with dynamic memory patching. When i try to use uc.mem_write to fill some address with NOP's, the unicorn itself, seems to ignore my patches

**Comment by UnlimitedChild** [comment]
You have to clear translation cache via uc_ctl_remove_cache
https://github.com/unicorn-engine/unicorn/issues/1561

**Comment by OSPFvX** [comment]
https://pastebin.com/AYJ3Pqby
Yes, I have already done it, the above example
