### ISSUE TITLE
Thumb2  Instruction Not Support LDAEX

### ISSUE THREAD

**Issue by lykmoon** [unicorn-engine/unicorn#1753]
Code like this is Not Support
public static final byte[] THUMB_CODE1 = {(byte) 0xD3, (byte) 0xE8, (byte) 0xEF, 0x4F}; // ldaex	r4, [r3]

Similar Instruction like 
public static final byte[] THUMB_CODE2 = {(byte) 0xC3, (byte) 0xE8, (byte) 0xE5,0x2F} // stlex r5, r2, [r3]
is also not support 

These occur in simulate android "libc.so",in function "pthread_key_create".Am I wrong when using unicon?

code is here：
pthread_key_create                     
.text:00047964                                      
.text:00047964 ; __unwind {
.text:00047964                 PUSH            {R4,R5,R7,LR}
.text:00047966                 LDR.W           R12, =(_ZL7key_map - 0x47972)
.text:0004796A                 MOV.W           LR, #0
.text:0004796E                 ADD             R12, PC ; key_map
.text:00047970
.text:00047970 loc_47970                               ; CODE XREF: .text:000479A0↓j
.text:00047970                 LDR.W           R2, [R12,LR,LSL#3]
.text:00047974                 ADD.W           R3, R12, LR,LSL#3
.text:00047978                 B               loc_47994
.text:00047978 ; ---------------------------------------------------------------------------
.text:0004797A unk_4797A       DCB 0xD3                ; CODE XREF: .text:00047996↓j
.text:0004797B                 DCB 0xE8
.text:0004797C                 DCB 0xEF
.text:0004797D                 DCB 0x4F ; O
.text:0004797E ; ---------------------------------------------------------------------------
.text:0004797E                 CMP             R4, R2
.text:00047980                 BNE             loc_4798E
.text:00047982                 ADDS            R2, #1
.text:00047982 ; ---------------------------------------------------------------------------
.text:00047984                 DCB 0xC3
.text:00047985                 DCB 0xE8
.text:00047986                 DCB 0xE5
.text:00047987                 DCB 0x2F ; /
.text:00047988 ; ---------------------------------------------------------------------------
.text:00047988                 MOV             R2, R4
.text:0004798A                 CBNZ            R5, loc_47994
.text:0004798C                 B               loc_479A6
.text:0004798E ; -----------------------------------------------

**Comment by wtdcode** [comment]
https://github.com/unicorn-engine/unicorn/wiki/FAQ#emulating-some-instructions-gives-an-error-like-invalid-instruction-what-should-i-do

**Comment by lykmoon** [comment]
I know.I need enable arm vfp.
Thanks!

https://github.com/unicorn-engine/unicorn/blob/8c6cbe3f3cabed57b23b721c29f937dd5baafc90/tests/regress/arm_fp_vfp_disabled.py#L15

**Comment by wtdcode** [comment]
Try to change cpu model
________________________________

**Comment by lykmoon** [comment]
It already work
