### ISSUE TITLE
Unicorn V1 to V2 API changes

### ISSUE THREAD

**Issue by ksteuck** [unicorn-engine/unicorn#1757]
Hey folks,

Have there been any incompatible API changes between V1 and V2 (I'm mostly interested in X86 and ARM64)?
Generally, is there a high-level list of changes between the two versions? E.g. I understand that qemu was updated but probably there are other noteworthy changes.

Thanks.

**Comment by wtdcode** [comment]
Generally speaking, no. But note qemu itself is largely evovled
________________________________
From: ksteuck ***@***.***>
Sent: Saturday, January 7, 2023 8:46:34 AM
To: unicorn-engine/unicorn ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [unicorn-engine/unicorn] Unicorn V1 to V2 API changes (Issue #1757)


Hey folks,

Have there been any incompatible API changes between V1 and V2 (I'm mostly interested in X86 and ARM64)?
Generally, is there a high-level list of changes between the two versions? E.g. I understand that qemu was updated but probably there are other noteworthy changes.

Thanks.

―
