### ISSUE TITLE
can't run the unicorn project in  xcode

### ISSUE THREAD

**Issue by iOSPrincekin** [unicorn-engine/unicorn#1758]
Hi:
    I build unicorn project by 'cmake .. -GXcode -DCMAKE_BUILD_TYPE=Release', it can generate xcode project success,build when I run the 'test_x86' target in the xcode unicorn project,It shows error:

`'config-host.h' file not found` in the osdep.h file.

I don't know why,any help will be appreciated

**Comment by wtdcode** [comment]
Unfortunately, I don't have Xcode installed.

Could you list all directories and subdirectories of your build directory?
