### ISSUE TITLE
Invalid instruction error when executing pclmulqdq

### ISSUE THREAD

**Issue by cube0x8** [unicorn-engine/unicorn#1760]
I'm trying to emulate x86_64 assembly code by using the python bindings.
When unicorn tries to emulate this instruction:

`pclmulqdq xmm0, xmm2, 0`

it fails with the following error:
`Invalid instruction (UC_ERR_INSN_INVALID)`

To reproduce:

```
from unicorn import *
from unicorn.x86_const import *

ADDRESS = 0x8048000
SIZE = 0x2000

"""
movdqu xmm2, xmmword ptr [rsi]
movdqa  xmm0, xmm2
pclmulqdq xmm0, xmm2, 0
"""
ASSEMBLY = b"\xF3\x0F\x6F\x16\x66\x0F\x6F\xC2\x66\x0F\x3A\x44\xC2\x00"
mu = Uc(UC_ARCH_X86, UC_MODE_64)

mu.mem_map(ADDRESS, SIZE)

mu.mem_write(ADDRESS, ASSEMBLY)
mu.mem_write(ADDRESS + len(ASSEMBLY), b"\x41"*1000)
mu.reg_write(UC_X86_REG_RSI, ADDRESS + len(ASSEMBLY))

mu.emu_start(ADDRESS, ADDRESS + len(ASSEMBLY))
```

Output:
```
~/.local/lib/python3.10/site-packages/unicorn/unicorn.py in emu_start(self, begin, until, timeout, count)
    545         status = _uc.uc_emu_start(self._uch, begin, until, timeout, count)
    546         if status != uc.UC_ERR_OK:
--> 547             raise UcError(status)
    548
    549         if self._hook_exception is not None:

UcError: Invalid instruction (UC_ERR_INSN_INVALID)
```

**Comment by wtdcode** [comment]
Could you try to switch another CPU model like MAX?

**Comment by cube0x8** [comment]
I tried to switch CPU model to Haswell like this:

```
mu = Uc(UC_ARCH_X86, UC_MODE_64)                                                                                                                                                                        
mu.ctl_set_cpu_model(UC_CPU_X86_HASWELL) 
```

and I got the same behavior.
I'm pretty sure that Haswell supports that instruction.

What do you mean with "MAX"? I got the CPU models from [here](https://github.com/unicorn-engine/unicorn/blob/56f3bdedb42d26bee1532cc01baf5eaf44a9aa23/include/unicorn/x86.h#L17) and I don't see anything like "MAX".

**Comment by cube0x8** [comment]
I did other tests and I found out that the following code:
```
from unicorn import *
from unicorn.x86_const import *

ADDRESS = 0x8048000
SIZE = 0x2000

"""
0:  66 48 0f 6e c7          movq   xmm0,rdi
5:  c5 f9 ef c0                vpxor  xmm0,xmm0,xmm0
9:  c5 fd 74 0f               vpcmpeqb ymm1,ymm0,YMMWORD PTR [rdi] 
"""
ASSEMBLY = b"\x66\x48\x0F\x6E\xC7\xC5\xF9\xEF\xC0\xC5\xFD\x74\x0F"
mu = Uc(UC_ARCH_X86, UC_MODE_64)
mu.ctl_set_cpu_model(UC_CPU_X86_HASWELL)

mu.mem_map(ADDRESS, SIZE)

mu.mem_write(ADDRESS, ASSEMBLY)
mu.mem_write(ADDRESS + len(ASSEMBLY), b"\x41"*1000)
mu.reg_write(UC_X86_REG_RDI, ADDRESS + len(ASSEMBLY))

print(mu.emu_start(ADDRESS, ADDRESS + len(ASSEMBLY)))
```

get successfully emulated on unicorn 2.0.0 but it fails with "illegal instructions" on 2.0.1 and 2.0.1.post1. The instruction that cannot be emulated is `vpcmpeqb ymm1,ymm0,YMMWORD PTR [rdi]`.

Instead, the code I pasted in the first comment cannot be emulated neither on 2.0.0 nor on 2.0.1 or 2.0.1.post1. I think this is due to the lack of proper AVX2 support in the QEMU version implemented by unicorn.

**Comment by wtdcode** [comment]
Ymm is not supported so your observation is correct for `vpcmpeqb ymm1,ymm0,YMMWORD PTR [rdi]`.

See #1658
