### ISSUE TITLE
 "Segmentation fault  cargo run" - on M1 MacBook Pro

### ISSUE THREAD

**Issue by tigger1005** [unicorn-engine/unicorn#1762]
Hi,

during fault attack analysis of C code for ARM-M platform I recognized a strange segmentation fault. The main purpose change several code fragments to simulate HW fault attacks. During the change of "str R2, [R3, #0]  with the opcode of `0x601A` to the opcode `0x681A` on the address of an MMIO write hock the program crash and a "[1]    89392 segmentation fault  cargo run" is reported.
The code below with the code 0x1a, 0x60 works as expected.

```Rust
use unicorn_engine::unicorn_const::{Arch, Mode, Permission};
use unicorn_engine::{RegisterARM, Unicorn};

const CODE: u64 = 0x80000000;
const ADR: u64 = 0x0A000000;

fn main() {
    let arm_code: [u8; 2] = [0x1a, 0x68]; // {0x1a, 0x60} -> str R2, [R3,#0]
    let mut unicorn = Unicorn::new(Arch::ARM, Mode::LITTLE_ENDIAN | Mode::MCLASS).unwrap();
    let emu = &mut unicorn;
    // Setup memory and IO
    emu.mem_map(CODE, 0x1000, Permission::ALL).unwrap();
    emu.mmio_map_wo(ADR, 0x1000, mmio_callback).unwrap();
    emu.reg_write(RegisterARM::R3, ADR).unwrap();
    emu.mem_write(CODE, &arm_code).unwrap();
    emu.emu_start(CODE | 1, (CODE + 10) | 1, 0, 1).unwrap();
}

fn mmio_callback<D>(_: &mut Unicorn<D>, _: u64, _: usize, _: u64) {
    println!("mmio_callback addr");
}
```

**Comment by PhilippTakacs** [comment]
Hi

Can you post some code triggering the crash?

**Comment by tigger1005** [comment]
It is exactly the code in the comment above. The value in this line "0x1a, 0x68" triggers the segmentation fault. With the value "0x1a, 0x60" the code runs w/o errors.
```Rust
let arm_code: [u8; 2] = [0x1a, 0x68]; // {0x1a, 0x60} -> str R2, [R3,#0]```

**Comment by PhilippTakacs** [comment]
> It is exactly the code in the comment above

Sorry I have missread this.

I can reproduce your bug, which contains two bugs

1.  the rust function mmio_map_wo still registers a read callback with some empty userdata(https://github.com/unicorn-engine/unicorn/blob/master/bindings/rust/src/lib.rs#L358). This userdata is accesed causing the segfault. As a workaround you can register a read and write callback with ``emu.mmio_map(ADR, Some(mmio_read_dummy), Some(mmio_callback))``. To fix this either the mmio_map function has to pass a NULL if read callback is None (also for write) or the callback proxies check if userdata is NULL.

2. For some reasons I currently don't unterstand your code is handled different, when called from C and rust. On C this causes a UC_ERR_INSN_INVALID and the mmio is not called.

Also I have noticed you use Mode::MCLASS with is as far as I see a mode for ARM64.

**Comment by PhilippTakacs** [comment]
> For some reasons I currently don't unterstand your code is handled different

A I haven't reproduced correct. When I use ``uc_emu_start(uc_handle, code | 1, (code + 10) | 1, 0, 0);`` I get the same results in C. So only the wrong callback in the rust bindings.

**Comment by tigger1005** [comment]
Thanks for the investigation,
I was able to reproduce that the workaround also works for me. 
Should I look into the rust binding for fixing that?

**Comment by PhilippTakacs** [comment]
You can try following patch

```
diff --git a/bindings/rust/src/lib.rs b/bindings/rust/src/lib.rs
index 7959e2d5..2aac940d 100644
--- a/bindings/rust/src/lib.rs
+++ b/bindings/rust/src/lib.rs
@@ -388,12 +388,18 @@ impl<'a, D> Unicorn<'a, D> {
                 self.get_handle(),
                 address,
                 size,
-                ffi::mmio_read_callback_proxy::<D, R> as _,
+                match read_data {
+                    Some(_) => ffi::mmio_read_callback_proxy::<D, R> as _,
+                    None => ptr::null_mut(),
+                },
                 match read_data {
                     Some(ref mut d) => d.as_mut() as *mut _ as _,
                     None => ptr::null_mut(),
                 },
-                ffi::mmio_write_callback_proxy::<D, W> as _,
+                match write_data {
+                    Some(_) => ffi::mmio_write_callback_proxy::<D, W> as _,
+                    None => ptr::null_mut(),
+                },
                 match write_data {
                     Some(ref mut d) => d.as_mut() as *mut _ as _,
                     None => ptr::null_mut(),
```

I'll create a pr with this patch next week
