### ISSUE TITLE
Incorrect behavior of IP in x86 16-bit mode

### ISSUE THREAD

**Issue by cseagle** [unicorn-engine/unicorn#1770]
Reading the contents of IP during execution should always yield the current CS segment offset, however in 16-bit mode, reading IP sometimes yields the expected offset, while in other cases it yields the full linear address. In the attached example, reading the IP within the basic block hook always yields the offset, while reading IP in the code hook moments later yields the linear address.

Attachements:
[https://gist.github.com/cseagle/54e32617921d4fb860c999e7472ff9f2](url)
sample_x86_16.c - code runner
output.txt - output of running: ./sample_x86_16 test_exe_bin
[test.zip](https://github.com/unicorn-engine/unicorn/files/10555145/test.zip)
contains test_exe_bin

**Comment by wtdcode** [comment]
`uc_reg_read(uc, UC_X86_REG_EIP, &eip);`

This is incorrect, you should read `IP` instead of `EIP`.

**Comment by cseagle** [comment]
Nice try, but that is wrong and the code is still wrong.

Please see https://gist.github.com/cseagle/7d76181e26d581b605391bccdba75fad

Specifically note the difference between the printed 16-bit IP value at lines 4 and 6 of output_ip.txt. The execution address passed into the 2 hook functions is identical however the 16-bit IP reported in the code hook has changed from that reported in the block hook and it is wrong.

**Comment by wtdcode** [comment]
Fixed in 133504b504b4b9005b26f707d7d68cf18eba2993
