### ISSUE TITLE
unicorn v1 rust bindings for cargo plz?

### ISSUE THREAD

**Issue by invlpg** [unicorn-engine/unicorn#1774]
unicorn engine 2 has a lot of avx instructions which older cpus cannot executed (causes an STATUS_ILLEGAL_INSTRUCTION) for me. Could you possibly make it so in cargo you could include an older version?

ie:
unicorn-engine = "1.0.0" ?

thanks!

**Comment by wtdcode** [comment]
Link to #1601

**Comment by wtdcode** [comment]
Fixed in 3199dd88dee094c3fc456971e5f469c22cb1160d and will be included in the next release.

**Comment by invlpg** [comment]
i love you
