### ISSUE TITLE
Unicorn rust bindings failing to build on macOS github CI

### ISSUE THREAD

**Issue by bayedieng** [unicorn-engine/unicorn#1775]
There seems to be an [issue](https://github.com/obhq/obliteration/pull/138) with regards to building unicorn in macOS Github CI due to a memory leak. Unfortunately I do not possess an Intel mac to test locally.
Link to CI: https://github.com/obhq/obliteration/actions/runs/4128072841

**Comment by wtdcode** [comment]
Just saw this and if you are expecting some performance boost for Unicorn, stay tuned ;)

**Comment by VocalFan** [comment]
> Just saw this and if you are expecting some performance boost for Unicorn, stay tuned ;)

As another member of Obliteration, lmk!
