### ISSUE TITLE
UC_MEM_READ_PROT  error

### ISSUE THREAD

**Issue by stonerhash** [unicorn-engine/unicorn#1776]
Hello,

I have an allocated memory with READ_WRITE permissions and doing sequential reads and writes within the range. I have observed in some read/writes within the allocated memory I am getting an UC_MEM_READ_PROT (not all) which I handle with an invalid memory hook . This is very strange since other nearby read/writes are executed successfully.  The faulty access is of type UC_MEM_READ_PROT. Can you help me understand the reason behind this error?

Thanks

**Comment by PhilippTakacs** [comment]
Can you provide a small sample? This would help to reproduce the issue.

**Comment by stonerhash** [comment]
Please ignore the issue. It seems that the problem is the framework that uses unicorn and not unicorn itself. Apologies.
