### ISSUE TITLE
.NET Binding - Implement IDisposable

### ISSUE THREAD

**Issue by 9ee1** [unicorn-engine/unicorn#178]
Hello:

In the `Unicorn` class, standard practice dictates that you should implement `IDisposable` if you allocate unmanaged memory or have a reference to native handles. Otherwise, memory leaks can occur.

**Comment by enkomio** [comment]
Hi,

right, I will make the Unicorn class disposable.

**Comment by enkomio** [comment]
Hi,

in commit 232cff02d27e1e99f9d195084557972fb90f4104 the IDisposable interface was implemented.

**Comment by danghvu** [comment]
Close since in-active and issue seems resolved.
