### ISSUE TITLE
Arm64 failure on BLRAB instruction

### ISSUE THREAD

**Issue by jorgschulze73** [unicorn-engine/unicorn#1789]
Currently facing an issue when trying to emulate BLRAB instruction using latest upstream: an `UC_ERR_FETCH_UNMAPPED` error is raised cause program counter is not correctly stripped of the PAC signature.

Test case:
```
bool hit_unmapped_fetch = false;
static constexpr const uint64_t x8  = 0xec5a800100470160;
static constexpr const uint64_t x21 = 0x00000001fa6fd640;
static constexpr const uint32_t instruction = 0xd73f0d15; // blrab  x8, x21

// This hook should never be hit... but it is
void hook_mem_invalid(uc_engine *uc, uc_mem_type type, uint64_t address, int size, int64_t value, void *user_data) {
    assert(type == UC_MEM_FETCH_UNMAPPED);
    assert(address == x8);
    
    hit_unmapped_fetch = true;
}

void test() {
    static constexpr const uint64_t code_address = 0x10000;
    
    uc_engine* uc = nullptr;

    uc_err err = uc_open(UC_ARCH_ARM64, UC_MODE_ARM, &uc);
    assert(err == UC_ERR_OK);
    
    err = uc_ctl_set_cpu_model(uc, UC_CPU_ARM64_MAX);
    assert(err == UC_ERR_OK);
    
    err = uc_mem_map(uc, code_address, PAGE_SIZE, UC_PROT_ALL);
    assert(err == UC_ERR_OK);
    
    err = uc_mem_write(uc, code_address, &instruction, sizeof(instruction));
    assert(err == UC_ERR_OK);
    
    err = uc_reg_write(uc, UC_ARM64_REG_X8, &x8);
    assert(err == UC_ERR_OK);
    
    err = uc_reg_write(uc, UC_ARM64_REG_X21, &x21);
    assert(err == UC_ERR_OK);
    
    err = uc_reg_write(uc, UC_ARM64_REG_PC, &code_address);
    assert(err == UC_ERR_OK);
    
    uc_hook unmapped_mem_hook;
    err = uc_hook_add(uc, &unmapped_mem_hook, UC_HOOK_MEM_FETCH_UNMAPPED, (void*)&hook_mem_invalid, nullptr, 0, UINT64_MAX);
    assert(err == UC_ERR_OK);
    
    err = uc_emu_start(uc, code_address, code_address + sizeof(instruction), 0, 1);
    assert(err == UC_ERR_OK);
    assert(hit_unmapped_fetch == false);
}
```

**Comment by jorgschulze73** [comment]
Would somebody please acknowledge if this is supposed to be intended behaviour of if it's a bug?

**Comment by jorgschulze73** [comment]
Ping

**Comment by jorgschulze73** [comment]
More than two months have passed, do we know if this is in fact a bug?

**Comment by PhilippTakacs** [comment]
I'm not sure, but as far as I see the problem is that unicorn don't set the feature flag for PAC. So I would more call this a feature request. Access to Key registers is also missing.

Because most of pauth is already implemented it should be easy to enable this.

**Comment by jorgschulze73** [comment]
Bug or feature request, I would really appreciate if this could be enabled/implemented

**Comment by wtdcode** [comment]
Adding these lines should enable PAuth:

```C
    uc_arm64_cp_reg reg;

    // SCR_EL3
    reg.op0 = 0b11;
    reg.op1 = 0b110;
    reg.crn = 0b0001;
    reg.crm = 0b0001;
    reg.op2 = 0b000;

    err = uc_reg_read(uc, UC_ARM64_REG_CP_REG, &reg);
    assert(err == UC_ERR_OK);

    // NS && RW && API
    reg.val |= (1 | (1<<10) | (1<<17));

    err = uc_reg_write(uc, UC_ARM64_REG_CP_REG, &reg);
    assert(err == UC_ERR_OK);

    // SCTLR_EL1
    reg.op0 = 0b11;
    reg.op1 = 0b000;
    reg.crn = 0b0001;
    reg.crm = 0b0000;
    reg.op2 = 0b000;

    err = uc_reg_read(uc, UC_ARM64_REG_CP_REG, &reg);
    assert(err == UC_ERR_OK);

    // EnIA && EnIB
    reg.val |= (1<<31) | (1<<30);

    err = uc_reg_write(uc, UC_ARM64_REG_CP_REG, &reg);
    assert(err == UC_ERR_OK);
    
    // HCR_EL2
    reg.op0 = 0b11;
    reg.op1 = 0b100;
    reg.crn = 0b0001;
    reg.crm = 0b0001;
    reg.op2 = 0b000;

    // HCR.API
    reg.val |= (1ULL<<41);

    err = uc_reg_write(uc, UC_ARM64_REG_CP_REG, &reg);
    assert(err == UC_ERR_OK);
```

I kindly ask you to read more about arm architecture docs.

**Comment by nneonneo** [comment]
@wtdcode OK, that code does *not* actually work due to a bug in the way we're handling cp register writes.

Here's the sample code:

```c
#include <stdio.h>
#include <unicorn/unicorn.h>
#include <string.h>

#define ADDRESS 0x10000

#define CHECK(x) do {      \
    if((x) != UC_ERR_OK) {              \
        fprintf(stderr, "FAIL at %s:%d: %s\n", __FILE__, __LINE__, #x); \
        exit(1);            \
    }                       \
} while(0)

int main()
{
    uc_engine *uc;
    uint64_t x1 = 0x0000aaaabbbbccccULL;

    // paciza x1
    #define ARM64_PAC_CODE "\xe1\x23\xc1\xda"

    printf("Try ARM64 PAC\n");

    // Initialize emulator in ARM mode
    CHECK(uc_open(UC_ARCH_ARM64, UC_MODE_ARM, &uc));
    CHECK(uc_ctl_set_cpu_model(uc, UC_CPU_ARM64_MAX));
    CHECK(uc_mem_map(uc, ADDRESS, 2 * 1024 * 1024, UC_PROT_ALL));
    CHECK(uc_mem_write(uc, ADDRESS, ARM64_PAC_CODE, sizeof(ARM64_PAC_CODE) - 1));
    CHECK(uc_reg_write(uc, UC_ARM64_REG_X1, &x1));

    /** Initialize PAC support **/
    uc_arm64_cp_reg reg;

    // SCR_EL3
    reg.op0 = 0b11;
    reg.op1 = 0b110;
    reg.crn = 0b0001;
    reg.crm = 0b0001;
    reg.op2 = 0b000;

    CHECK(uc_reg_read(uc, UC_ARM64_REG_CP_REG, &reg));

    // NS && RW && API
    reg.val |= (1 | (1<<10) | (1<<17));

    CHECK(uc_reg_write(uc, UC_ARM64_REG_CP_REG, &reg));

    // SCTLR_EL1
    reg.op0 = 0b11;
    reg.op1 = 0b000;
    reg.crn = 0b0001;
    reg.crm = 0b0000;
    reg.op2 = 0b000;

    CHECK(uc_reg_read(uc, UC_ARM64_REG_CP_REG, &reg));

    // EnIA && EnIB
    reg.val |= (1<<31) | (1<<30);

    CHECK(uc_reg_write(uc, UC_ARM64_REG_CP_REG, &reg));
    
    // HCR_EL2
    reg.op0 = 0b11;
    reg.op1 = 0b100;
    reg.crn = 0b0001;
    reg.crm = 0b0001;
    reg.op2 = 0b000;

    // HCR.API
    reg.val |= (1ULL<<41);

    CHECK(uc_reg_write(uc, UC_ARM64_REG_CP_REG, &reg));

    /** Check that PAC worked **/
    CHECK(uc_emu_start(uc, ADDRESS, ADDRESS + sizeof(ARM64_PAC_CODE) - 1, 0, 0));
    CHECK(uc_reg_read(uc, UC_ARM64_REG_X1, &x1));

    printf("X1 = %" PRIx64 "\n", x1);
    if (x1 == 0x0000aaaabbbbccccULL) {
        printf("FAIL: No PAC tag added!\n");
    } else {
        // Expect 0x1401aaaabbbbccccULL with the default key
        printf("SUCCESS: PAC tag found.\n");
    }

    uc_close(uc);
}
```

Although the code runs, no PAC tag is applied to the value in x1 (the expected PAC tag is 0x1401).

The cause seems to be that we're not calling `arm_rebuild_hflags(env)` after changing an `sctlr` register. PAC enablement is controlled by the `PAUTH_ACTIVE` flag, which only gets updated from `rebuild_hflags_a64`.

The default `sctlr_write` handler for SCTLR writes calls `arm_rebuild_hflags`, but we bypass it via `raw_write`. This is sensible, since we may not have an active CPU context (e.g. context write), however it means that we end up failing to synchronize a portion of the CPU state with the register state.

In fact, if we enable `CONFIG_DEBUG_TCG`, we will actually trip the assert in `assert_hflags_rebuild_correctly`:

```
Try ARM64 PAC
TCG hflags mismatch (current:0x88104004 rebuilt:0x82104304)
zsh: abort      ./sample_arm64
```

because we changed the register state without updating the hflags.

The best solution would probably be to rebuild the hflags after a CP write. The tricky part is making sure this still works with a context write: we can't just call `arm_rebuild_hflags` unconditionally because it requires access to `env_cpu(env)`, which is undefined on a context object.

In fact, that issue probably affects other CP registers too: there's quite a few that have no `raw_writefn`, and whose `writefn`s access `env_cpu(env)` - for example, writing `TLBI_VMALLE1IS` (`.opc0 = 1, .opc1 = 0, .crn = 8, .crm = 3, .opc2 = 0`) using `uc_context_reg_write` will segfault. We could *probably* just slap a big "here be dragons" label on context register operations and call it a day - I imagine there are plenty of funny corner cases where a special register write won't work without a CPU structure.

We probably _also_ need to rebuild the hflags after restoring a context, in case SCTLRs (or other registers) are different in the incoming context...

**Comment by wtdcode** [comment]
> @wtdcode OK, that code does _not_ actually work due to a bug in the way we're handling cp register writes.
> 
> Here's the sample code:
> 
> ```c
> #include <stdio.h>
> #include <unicorn/unicorn.h>
> #include <string.h>
> 
> #define ADDRESS 0x10000
> 
> #define CHECK(x) do {      \
>     if((x) != UC_ERR_OK) {              \
>         fprintf(stderr, "FAIL at %s:%d: %s\n", __FILE__, __LINE__, #x); \
>         exit(1);            \
>     }                       \
> } while(0)
> 
> int main()
> {
>     uc_engine *uc;
>     uint64_t x1 = 0x0000aaaabbbbccccULL;
> 
>     // paciza x1
>     #define ARM64_PAC_CODE "\xe1\x23\xc1\xda"
> 
>     printf("Try ARM64 PAC\n");
> 
>     // Initialize emulator in ARM mode
>     CHECK(uc_open(UC_ARCH_ARM64, UC_MODE_ARM, &uc));
>     CHECK(uc_ctl_set_cpu_model(uc, UC_CPU_ARM64_MAX));
>     CHECK(uc_mem_map(uc, ADDRESS, 2 * 1024 * 1024, UC_PROT_ALL));
>     CHECK(uc_mem_write(uc, ADDRESS, ARM64_PAC_CODE, sizeof(ARM64_PAC_CODE) - 1));
>     CHECK(uc_reg_write(uc, UC_ARM64_REG_X1, &x1));
> 
>     /** Initialize PAC support **/
>     uc_arm64_cp_reg reg;
> 
>     // SCR_EL3
>     reg.op0 = 0b11;
>     reg.op1 = 0b110;
>     reg.crn = 0b0001;
>     reg.crm = 0b0001;
>     reg.op2 = 0b000;
> 
>     CHECK(uc_reg_read(uc, UC_ARM64_REG_CP_REG, &reg));
> 
>     // NS && RW && API
>     reg.val |= (1 | (1<<10) | (1<<17));
> 
>     CHECK(uc_reg_write(uc, UC_ARM64_REG_CP_REG, &reg));
> 
>     // SCTLR_EL1
>     reg.op0 = 0b11;
>     reg.op1 = 0b000;
>     reg.crn = 0b0001;
>     reg.crm = 0b0000;
>     reg.op2 = 0b000;
> 
>     CHECK(uc_reg_read(uc, UC_ARM64_REG_CP_REG, &reg));
> 
>     // EnIA && EnIB
>     reg.val |= (1<<31) | (1<<30);
> 
>     CHECK(uc_reg_write(uc, UC_ARM64_REG_CP_REG, &reg));
>     
>     // HCR_EL2
>     reg.op0 = 0b11;
>     reg.op1 = 0b100;
>     reg.crn = 0b0001;
>     reg.crm = 0b0001;
>     reg.op2 = 0b000;
> 
>     // HCR.API
>     reg.val |= (1ULL<<41);
> 
>     CHECK(uc_reg_write(uc, UC_ARM64_REG_CP_REG, &reg));
> 
>     /** Check that PAC worked **/
>     CHECK(uc_emu_start(uc, ADDRESS, ADDRESS + sizeof(ARM64_PAC_CODE) - 1, 0, 0));
>     CHECK(uc_reg_read(uc, UC_ARM64_REG_X1, &x1));
> 
>     printf("X1 = %" PRIx64 "\n", x1);
>     if (x1 == 0x0000aaaabbbbccccULL) {
>         printf("FAIL: No PAC tag added!\n");
>     } else {
>         // Expect 0x1401aaaabbbbccccULL with the default key
>         printf("SUCCESS: PAC tag found.\n");
>     }
> 
>     uc_close(uc);
> }
> ```
> 
> Although the code runs, no PAC tag is applied to the value in x1 (the expected PAC tag is 0x1401).
> 
> The cause seems to be that we're not calling `arm_rebuild_hflags(env)` after changing an `sctlr` register. PAC enablement is controlled by the `PAUTH_ACTIVE` flag, which only gets updated from `rebuild_hflags_a64`.
> 
> The default `sctlr_write` handler for SCTLR writes calls `arm_rebuild_hflags`, but we bypass it via `raw_write`. This is sensible, since we may not have an active CPU context (e.g. context write), however it means that we end up failing to synchronize a portion of the CPU state with the register state.
> 
> In fact, if we enable `CONFIG_DEBUG_TCG`, we will actually trip the assert in `assert_hflags_rebuild_correctly`:
> 
> ```
> Try ARM64 PAC
> TCG hflags mismatch (current:0x88104004 rebuilt:0x82104304)
> zsh: abort      ./sample_arm64
> ```
> 
> because we changed the register state without updating the hflags.
> 
> The best solution would probably be to rebuild the hflags after a CP write. The tricky part is making sure this still works with a context write: we can't just call `arm_rebuild_hflags` unconditionally because it requires access to `env_cpu(env)`, which is undefined on a context object.
> 
> In fact, that issue probably affects other CP registers too: there's quite a few that have no `raw_writefn`, and whose `writefn`s access `env_cpu(env)` - for example, writing `TLBI_VMALLE1IS` (`.opc0 = 1, .opc1 = 0, .crn = 8, .crm = 3, .opc2 = 0`) using `uc_context_reg_write` will segfault. We could _probably_ just slap a big "here be dragons" label on context register operations and call it a day - I imagine there are plenty of funny corner cases where a special register write won't work without a CPU structure.
> 
> We probably _also_ need to rebuild the hflags after restoring a context, in case SCTLRs (or other registers) are different in the incoming context...

Thanks for your reminder. I forget to push the `arm_rebuild_hflags` fix after writing the registers indeed. Regarding your problem, the best solution is to store such extra information in context. Note this code: https://github.com/unicorn-engine/unicorn/blob/f65f8f83805c778cd1fbbfc4ef676c9ba71105b2/include/uc_priv.h#L298

Actually we are lacking some handy libraries to do serialization/deserialization, which is the root cause when I faced with a few similar problems.

**Comment by wtdcode** [comment]
https://github.com/unicorn-engine/unicorn/wiki/FAQ#does-unicorn-support-arm-pac-pointer-authentication

Documented here!
