### ISSUE TITLE
.NET Binding - Possible Memory Leaks?

### ISSUE THREAD

**Issue by 9ee1** [unicorn-engine/unicorn#180]
Hello:

All over the `Unicorn` class, you are allocating unmanaged memory but you are never freeing that memory anywhere. I think you have a very serious memory leak problem, unless I am missing something?

**Comment by enkomio** [comment]
Hi,

you are right, there are some memory leak that must be handled. I will fix it asap.

**Comment by enkomio** [comment]
Hi,

in commit 232cff02d27e1e99f9d195084557972fb90f4104 all the unmanaged allocated memory are free in the Dispose function.

I think this should resolve the memory leak problem.

**Comment by danghvu** [comment]
Close since in-active and issue seems resolved.
