### ISSUE TITLE
.NET Binding - Consider the Use of Safe Handles

### ISSUE THREAD

**Issue by 9ee1** [unicorn-engine/unicorn#181]
Hello:

Safe handles are paradigm to ensure that handles to unmanaged memory blocks are correctly freed and cleaned up by the CLR in case the consumer of the API is unable, or forgets, to explicitly free the memory themselves.

**Comment by enkomio** [comment]
Hi,

I will evaluate the usage of the SafeHandle.

**Comment by aquynh** [comment]
I think this was solved, so closed, thanks
