### ISSUE TITLE
xsave  [rsp+0x40] error

### ISSUE THREAD

**Issue by pwnhacker0x18** [unicorn-engine/unicorn#1814]
Hello! I use unicorn from git clone in my C code. I encountered an unknown error - unicorn cannot execute xsave, and in the code hook this instruction is of an abnormal size.
before exec xsave:
![image](https://user-images.githubusercontent.com/51971493/229369512-6019622d-7aba-452c-afdc-53f424988fc4.png)
![image](https://user-images.githubusercontent.com/51971493/229369523-9d3881c1-244e-4669-831f-bbd76b412e7c.png)
![image](https://user-images.githubusercontent.com/51971493/229369532-d4f20367-5d0e-4bc8-91aa-0640e5b9c3d7.png)
after exec xsave:
![image](https://user-images.githubusercontent.com/51971493/229369583-da56dc1d-cae2-44a6-8af5-a301d9ee9b9c.png)
![image](https://user-images.githubusercontent.com/51971493/229369593-ca2a7273-65dc-4f6f-b73b-b98227c68c1d.png)
![image](https://user-images.githubusercontent.com/51971493/229369602-16590fac-8730-413d-8288-276664fab018.png)

I use context segments with elf. All segments and registers are identical. Here are screenshots of the original elf.
before xsave:
![image](https://user-images.githubusercontent.com/51971493/229369624-a264d367-b174-41bc-816a-29b2ea232bcc.png)
![image](https://user-images.githubusercontent.com/51971493/229369633-1e08d34e-7695-4f0c-a9c6-e9703fa8b855.png)
after xsave:
![image](https://user-images.githubusercontent.com/51971493/229369644-7cac9cea-61ab-438e-98f3-e2b249ee9fbe.png)
![image](https://user-images.githubusercontent.com/51971493/229369651-77077ce8-a465-4507-962e-3a66c6ca6f93.png)

**Comment by wtdcode** [comment]
It's better if you could give a reproduction.
