### ISSUE TITLE
rust: expose ffi

### ISSUE THREAD

**Issue by lockbox** [unicorn-engine/unicorn#1821]
the unicorn rust ffi is too high level for much customization, to enable an "opt-in" choice to more flexibility the `ffi` module should get re-exported public since there is no `unicorn-sys` create or equivalent etc.

**Comment by wtdcode** [comment]
Could you elaborate on your use case? I have the same thoughts for quite a long time.

**Comment by lockbox** [comment]
What i did in https://github.com/lockbox/unicorn was expose the `ffi` layer. this allows you to make your own callbacks and pass custom user data a la `ffi::uc_hook_add`. My use case is wrapping unicorn with some tlc.

**Comment by wtdcode** [comment]
Okay, make sense. I'm actually writing some raw wrapper for these but still WIP... Mark as enhancement.

**Comment by lockbox** [comment]
Cool! My changes I made work for me but are still a bit clunky. Looking forward to the changes

**Comment by lockbox** [comment]
Closed in #1847
