### ISSUE TITLE
distributed pkg-config unicorn.pc contains reference to $DESTDIR

### ISSUE THREAD

**Issue by anthraxx** [unicorn-engine/unicorn#184]
there is a bug while distributing the unicorn.pc for pkg-config:
if distributing via 

    make DESTDIR="${pkgdir}" install

then the unicorn.pc contains references to ${DESTDIR}

    > cat unicorn.pc
    Name: unicorn
    Description: Unicorn emulator engine
    Version: 0.9
    libdir=/build/unicorn/pkg/libunicorn/usr/lib
    includedir=/build/unicorn/pkg/libunicorn/usr/include
    archive=${libdir}/libunicorn.a
    Libs: -L${libdir} -lunicorn
    Cflags: -I${includedir}

this happens because LIBDIR and INCDIR are echo-ed into that file bug containing that reference:

    LIBDIR = $(DESTDIR)$(PREFIX)/$(LIBDIRARCH)

Edit:

However, it seems thats the case the generation gets also called during the 'install' target (after a build target has already been called). I was wondering what the difference is between capstone and unicorn because the code looks very some: turns out in capstone it does not get re-generated during 'install' target and therefor works. This should be the same for unicorn so that it does not contain the DESTDIR :smile:

**Comment by aquynh** [comment]
yes we copied a lot of code from Capstone to Unicorn, hence the similarity.

still dont get what is wrong. can you send a pull-request to fix what you are suggesting?

thanks

**Comment by radare** [comment]
Yeah this is wrong, it mus be fixed

**Comment by anthraxx** [comment]
@aquynh "/build/unicorn/pkg/libunicorn" clearly does not belong into unicorn.pc :wink: 
I currently have shitload of work so cant provide you a proper patch... a workaround would be to use "$(PREFIX)/$(LIBDIRARCH)" directly there instead of $LIBDIR...
however a proper fix would be to make sure make does not regenerate that file, in capstone there is "PKGCFGF = $(BLDIR)/$(LIBNAME).pc"... maybe it has to do with the $(BLDIR) variable.

however, just issue 'make' and then 'make install' and look for:

      GEN     unicorn.pc

that should *only* be there once (for make) but NOT for 'make install'

sorry that i currently don't have the time to contribute

**Comment by aquynh** [comment]
@anthraxx, there is a PR by @radare on this issue at https://github.com/aquynh/capstone/pull/532. before i merge it, let me know if this solves all the problems.

thanks

**Comment by aquynh** [comment]
@anthraxx, can you confirm with the PR https://github.com/unicorn-engine/unicorn/pull/255 by @radare ?

**Comment by anthraxx** [comment]
@aquynh I confirm it looks correct and also produces a correct pkgconfig .pc file, thx @radare 

    Name: unicorn
    Description: Unicorn emulator engine
    Version: 0.9
    libdir=/usr/lib
    includedir=/usr/include
    archive=${libdir}/libunicorn.a
    Libs: -L${libdir} -lunicorn
    Cflags: -I${includedir}

**Comment by aquynh** [comment]
i merged it, thanks!
