### ISSUE TITLE
Failing to build on Raspberry 2

### ISSUE THREAD

**Issue by kashieda** [unicorn-engine/unicorn#1840]
I'm trying to install unicorn from source (I've also tried pip install unicorn). 

Output from uname -a: 
Linux morethanthree 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux

lscpu says:
Architecture:                    armv7l
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       ARM
Model:                           5
Model name:                      Cortex-A7
Stepping:                        r0p5
CPU max MHz:                     900.0000
CPU min MHz:                     600.0000
BogoMIPS:                        38.40
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Not affected
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           half thumb fastmult vfp edsp neon vfpv3 tls vfp
                                 v4 idiva idivt vfpd32 lpae evtstrm

Things work well until:

[ 92%] Built target unicorn
[ 93%] Linking C executable test_ctl
/usr/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_ldo_le_mmu_ppc64'
/usr/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_ldo_be_mmu_ppc64'
/usr/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_cmpxchgo_le_mmu_aarch64'
/usr/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_cmpxchgo_be_mmu_aarch64'
/usr/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_sto_be_mmu_s390x'
/usr/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_ldo_be_mmu_s390x'
/usr/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_cmpxchgo_be_mmu_s390x'
/usr/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_cmpxchgo_be_mmu_ppc64'
/usr/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_sto_be_mmu_ppc64'
/usr/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_cmpxchgo_le_mmu_ppc64'
/usr/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_sto_le_mmu_ppc64'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/test_ctl.dir/build.make:104: test_ctl] Error 1
make[1]: *** [CMakeFiles/Makefile2:187: CMakeFiles/test_ctl.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

Where do I start the next part of the unicorn journey? Any specific package needs installing?

**Comment by wtdcode** [comment]
This looks weird, what's your build steps?
________________________________
From: kashieda ***@***.***>
Sent: Tuesday, June 6, 2023 9:17:37 PM
To: unicorn-engine/unicorn ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [unicorn-engine/unicorn] Failing to build on Raspberry 2 (Issue #1840)


I'm trying to install unicorn from source (I've also tried pip install unicorn).

Output from uname -a:
Linux morethanthree 6.1.21-v7+ #1642<https://github.com/unicorn-engine/unicorn/issues/1642> SMP Mon Apr 3 17:20:52 BST 2023 armv7l GNU/Linux

lscpu says:
Architecture: armv7l
Byte Order: Little Endian
CPU(s): 4
On-line CPU(s) list: 0-3
Thread(s) per core: 1
Core(s) per socket: 4
Socket(s): 1
Vendor ID: ARM
Model: 5
Model name: Cortex-A7
Stepping: r0p5
CPU max MHz: 900.0000
CPU min MHz: 600.0000
BogoMIPS: 38.40
Vulnerability Itlb multihit: Not affected
Vulnerability L1tf: Not affected
Vulnerability Mds: Not affected
Vulnerability Meltdown: Not affected
Vulnerability Mmio stale data: Not affected
Vulnerability Retbleed: Not affected
Vulnerability Spec store bypass: Not affected
Vulnerability Spectre v1: Mitigation; __user pointer sanitization
Vulnerability Spectre v2: Not affected
Vulnerability Srbds: Not affected
Vulnerability Tsx async abort: Not affected
Flags: half thumb fastmult vfp edsp neon vfpv3 tls vfp
v4 idiva idivt vfpd32 lpae evtstrm

Things work well until:

[ 92%] Built target unicorn
[ 93%] Linking C executable test_ctl
/usr/bin/ld: libunicorn.so.2: undefined reference to helper_atomic_ldo_le_mmu_ppc64' /usr/bin/ld: libunicorn.so.2: undefined reference to helper_atomic_ldo_be_mmu_ppc64'
/usr/bin/ld: libunicorn.so.2: undefined reference to helper_atomic_cmpxchgo_le_mmu_aarch64' /usr/bin/ld: libunicorn.so.2: undefined reference to helper_atomic_cmpxchgo_be_mmu_aarch64'
/usr/bin/ld: libunicorn.so.2: undefined reference to helper_atomic_sto_be_mmu_s390x' /usr/bin/ld: libunicorn.so.2: undefined reference to helper_atomic_ldo_be_mmu_s390x'
/usr/bin/ld: libunicorn.so.2: undefined reference to helper_atomic_cmpxchgo_be_mmu_s390x' /usr/bin/ld: libunicorn.so.2: undefined reference to helper_atomic_cmpxchgo_be_mmu_ppc64'
/usr/bin/ld: libunicorn.so.2: undefined reference to helper_atomic_sto_be_mmu_ppc64' /usr/bin/ld: libunicorn.so.2: undefined reference to helper_atomic_cmpxchgo_le_mmu_ppc64'
/usr/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_sto_le_mmu_ppc64'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/test_ctl.dir/build.make:104: test_ctl] Error 1
make[1]: *** [CMakeFiles/Makefile2:187: CMakeFiles/test_ctl.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

Where do I start the next part of the unicorn journey? Any specific package needs installing?

―

**Comment by kashieda** [comment]
Basically, I'm following the steps given in https://github.com/unicorn-engine/unicorn/blob/master/docs/COMPILE.md

I've previously installed bintools from source.

**Comment by wtdcode** [comment]
I know how to fix but it's weird because we have CI for arm linux.

**Comment by wtdcode** [comment]
May I have your compiler version and could you try to build a **Release** version?

**Comment by kashieda** [comment]
cc -v says:

Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/10/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 10.2.1-6+rpi1' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=arm-linux-gnueabihf- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --disable-libquadmath-support --enable-plugin --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --disable-werror --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20210110 (Raspbian 10.2.1-6+rpi1)

I thought that was what I was trying to do: 
from the unicorn directory:
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
make

Any advice?

**Comment by PhilippTakacs** [comment]
can you share your config-host.h?

**Comment by wtdcode** [comment]
Sorry I forget this thread. The root cause is that qemu relies on dead code elimination, i.e. these undefined symbols should not exist after optimization but your compiler seems not doing so. We can manually fix this by adding some macros as I once did.
________________________________

**Comment by kashieda** [comment]
build/config-host.h
/* Automatically generated by create_config - do not modify */
#define CONFIG_QEMU_CONFDIR "/usr/local/etc/qemu"
#define CONFIG_QEMU_LOCALSTATEDIR "/usr/local/var"
#define CONFIG_QEMU_HELPERDIR "/usr/local/libexec"
#define CONFIG_QEMU_LOCALEDIR "/locale"
#define HOST_ARM 1
#define CONFIG_POSIX 1
#define CONFIG_LINUX 1
#define QEMU_VERSION "5.0.1"
#define QEMU_VERSION_MAJOR 5
#define QEMU_VERSION_MINOR 0
#define QEMU_VERSION_MICRO 1
#define CONFIG_SYNC_FILE_RANGE 1
#define CONFIG_DUP3 1
#define CONFIG_PRCTL_PR_SET_TIMERSLACK 1
#define CONFIG_EPOLL 1
#define CONFIG_CLOCK_ADJTIME 1
#define CONFIG_SYNCFS 1
#define HAVE_STRCHRNUL 1
#define HAVE_STRUCT_STAT_ST_ATIM 1
#define CONFIG_BYTESWAP_H 1
#define CONFIG_SIGNALFD 1
#define CONFIG_TCG 1
#define CONFIG_MADVISE 1
#define CONFIG_POSIX_MADVISE 1
#define CONFIG_POSIX_MEMALIGN 1
#define CONFIG_MALLOC_TRIM 1
#define CONFIG_OPEN_BY_HANDLE 1
#define CONFIG_LINUX_MAGIC_H 1
#define CONFIG_PRAGMA_DIAGNOSTIC_AVAILABLE 1
#define CONFIG_HAS_ENVIRON 1
#define CONFIG_ATTRIBUTE_ALIAS 1
#define CONFIG_GETAUXVAL 1
#define CONFIG_SYSMACROS 1
#define CONFIG_STATIC_ASSERT 1
#define HAVE_UTMPX 1
#define CONFIG_GETRANDOM 1
#define CONFIG_THREAD_SETNAME_BYTHREAD 1
#define CONFIG_PTHREAD_SETNAME_NP_W_TID 1
#define HOST_DSOSUF ".so"

**Comment by wtdcode** [comment]
I even don't see ATOMIC64 supported, probably unicorn really can't build on your platform.

**Comment by kashieda** [comment]
Interesting :)

It doesn't feel like RPi2 with Raspian should be too weird a setup. 

Anything I can try to help try to make it build?

**Comment by wtdcode** [comment]
Because I don't have access to any similar environments, I could only give you rough way to do it:

1. Check if qemu builds on your platform, if not, unicorn probably won't either.
2. If qemu works (note version 5.0.1), try to run qemu `configure` and there should be a similar header fine defining these values. Please check the difference between them and post here.
3.  Try to build qemu with the same compiler, if that also works, then try to grep the symbol `helper_atomic_ldo_le_mmu` from all objects and let me know the result.

**Comment by kashieda** [comment]
Building qemu-5.0.1 works (at least, it doesn't complain about anything). 

How does one run that? Also, how do I find those symbols?

**Comment by flyn-org** [comment]
I am the maintainer of the Fedora unicorn package, and I am having a similar problem when building on s390x. This is the error the Fedora s390x build host triggers:
```
[ 93%] Linking C executable mem_apis
/usr/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_ldo_le_mmu_ppc64'
/usr/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_ldo_be_mmu_ppc64'
/usr/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_cmpxchgo_le_mmu_aarch64'
/usr/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_cmpxchgo_be_mmu_aarch64'
/usr/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_sto_be_mmu_s390x'
/usr/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_ldo_be_mmu_s390x'
/usr/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_cmpxchgo_be_mmu_s390x'
/usr/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_cmpxchgo_be_mmu_ppc64'
/usr/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_sto_be_mmu_ppc64'
/usr/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_cmpxchgo_le_mmu_ppc64'
/usr/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_sto_le_mmu_ppc64'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/sample_batch_reg.dir/build.make:98: sample_batch_reg] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:779: CMakeFiles/sample_batch_reg.dir/all] Error 2
```

**Comment by kashieda** [comment]
Any new ideas?

**Comment by wtdcode** [comment]
@flyn-org Sorry missed you message. Do you have any further problem on this? You could open a separate issue to track this.

@kashieda `objdump` will work with dumping symbols and please check. More importantly please paste `config-host.h` generated by qemu.

**Comment by kashieda** [comment]
Any specific qemu file to check objects in? 

The qemu config-host.h file:
/* Automatically generated by create_config - do not modify */
#define CONFIG_QEMU_CONFDIR "/usr/local/etc/qemu"
#define CONFIG_QEMU_DATADIR "/usr/local/share/qemu"
#define CONFIG_QEMU_FIRMWAREPATH "/usr/local/share/qemu-firmware"
#define CONFIG_QEMU_DOCDIR "/usr/local/share/doc/qemu"
#define CONFIG_QEMU_MODDIR "/usr/local/lib/qemu"
#define CONFIG_QEMU_LOCALSTATEDIR "/usr/local/var"
#define CONFIG_QEMU_HELPERDIR "/usr/local/libexec"
#define CONFIG_QEMU_LOCALEDIR "/usr/local/share/locale"
#define CONFIG_QEMU_ICONDIR "/usr/local/share/icons"
#define CONFIG_QEMU_DESKTOPDIR "/usr/local/share/applications"
#define HOST_ARM 1
#define CONFIG_MINIKCONF_MODE --defconfig
#define CONFIG_POSIX 1
#define CONFIG_LINUX 1
#define CONFIG_TOOLS 1
#define CONFIG_SLIRP 1
#define CONFIG_SMBD_COMMAND "/usr/sbin/smbd"
#define CONFIG_L2TPV3 1
#define CONFIG_AUDIO_DRIVERS \
    "oss",\

#define CONFIG_AUDIO_OSS m
#define CONFIG_BDRV_RW_WHITELIST\
    NULL
#define CONFIG_BDRV_RO_WHITELIST\
    NULL
#define CONFIG_VNC 1
#define CONFIG_VNC_PNG 1
#define QEMU_VERSION "5.0.1"
#define QEMU_VERSION_MAJOR 5
#define QEMU_VERSION_MINOR 0
#define QEMU_VERSION_MICRO 1
#define CONFIG_ICONV 1
#define CONFIG_PIPE2 1
#define CONFIG_ACCEPT4 1
#define CONFIG_SPLICE 1
#define CONFIG_EVENTFD 1
#define CONFIG_MEMFD 1
#define CONFIG_USBFS 1
#define CONFIG_FALLOCATE 1
#define CONFIG_FALLOCATE_PUNCH_HOLE 1
#define CONFIG_FALLOCATE_ZERO_RANGE 1
#define CONFIG_POSIX_FALLOCATE 1
#define CONFIG_SYNC_FILE_RANGE 1
#define CONFIG_FIEMAP 1
#define CONFIG_DUP3 1
#define CONFIG_PPOLL 1
#define CONFIG_PRCTL_PR_SET_TIMERSLACK 1
#define CONFIG_EPOLL 1
#define CONFIG_EPOLL_CREATE1 1
#define CONFIG_SENDFILE 1
#define CONFIG_TIMERFD 1
#define CONFIG_SETNS 1
#define CONFIG_CLOCK_ADJTIME 1
#define CONFIG_SYNCFS 1
#define CONFIG_INOTIFY 1
#define CONFIG_INOTIFY1 1
#define CONFIG_SEM_TIMEDWAIT 1
#define HAVE_STRCHRNUL 1
#define HAVE_STRUCT_STAT_ST_ATIM 1
#define CONFIG_BYTESWAP_H 1
#define CONFIG_GIO 1
#define CONFIG_TLS_PRIORITY "NORMAL"
#define CONFIG_QEMU_PRIVATE_XTS 1
#define HAVE_IFADDRS_H 1
#define HAVE_FSXATTR 1
#define HAVE_COPY_FILE_RANGE 1
#define CONFIG_ATTR 1
#define CONFIG_VHOST_SCSI 1
#define CONFIG_VHOST_NET 1
#define CONFIG_VHOST_NET_USER 1
#define CONFIG_VHOST_CRYPTO 1
#define CONFIG_VHOST_VSOCK 1
#define CONFIG_VHOST_KERNEL 1
#define CONFIG_VHOST_USER 1
#define CONFIG_VHOST_USER_FS 1
#define CONFIG_IOVEC 1
#define CONFIG_PREADV 1
#define CONFIG_FDT 1
#define CONFIG_SIGNALFD 1
#define CONFIG_TCG 1
#define CONFIG_FDATASYNC 1
#define CONFIG_MADVISE 1
#define CONFIG_POSIX_MADVISE 1
#define CONFIG_POSIX_MEMALIGN 1
#define CONFIG_MALLOC_TRIM 1
#define CONFIG_QOM_CAST_DEBUG 1
#define CONFIG_COROUTINE_BACKEND ucontext
#define CONFIG_COROUTINE_POOL 1
#define CONFIG_OPEN_BY_HANDLE 1
#define CONFIG_LINUX_MAGIC_H 1
#define CONFIG_PRAGMA_DIAGNOSTIC_AVAILABLE 1
#define CONFIG_HAS_ENVIRON 1
#define CONFIG_ATTRIBUTE_ALIAS 1
#define CONFIG_GETAUXVAL 1
#define CONFIG_LIVE_BLOCK_MIGRATION 1
#define CONFIG_TPM 1
#define CONFIG_TRACE_LOG 1
#define CONFIG_TRACE_FILE trace
#define CONFIG_RTNETLINK 1
#define CONFIG_REPLICATION 1
#define CONFIG_AF_VSOCK 1
#define CONFIG_SYSMACROS 1
#define CONFIG_STATIC_ASSERT 1
#define HAVE_UTMPX 1
#define CONFIG_GETRANDOM 1
#define CONFIG_IVSHMEM 1
#define CONFIG_CAPSTONE 1
#define CONFIG_THREAD_SETNAME_BYTHREAD 1
#define CONFIG_PTHREAD_SETNAME_NP_W_TID 1
#define CONFIG_BOCHS 1
#define CONFIG_CLOOP 1
#define CONFIG_DMG 1
#define CONFIG_QCOW1 1
#define CONFIG_VDI 1
#define CONFIG_VVFAT 1
#define CONFIG_QED 1
#define CONFIG_PARALLELS 1
#define CONFIG_SHEEPDOG 1
#define HAVE_GDB_BIN /usr/bin/gdb
#define HOST_DSOSUF ".so"

**Comment by kashieda** [comment]
Running objdump -t qemu-io | grep helper_atomic_ldo_le_mmu finds nothing.

**Comment by lv22** [comment]
@kashieda  @flyn-org  Hi guys! Any progress on getting past those errors and building Unicorn? I'm also trying on Raspberry Pi 2 and struggling with these binding errors for quite some time.  
@wtdcode  Any thoughts?

Thanks!

**Comment by kashieda** [comment]
Nothing new here - have had the RPi offline a while due to a large water leak problem... 

Anything I can try to help locate the problem?

**Comment by patryk4815** [comment]
@flyn-org your build system don't have:
`#define CONFIG_CMPXCHG128 1`

**Comment by jamesjer** [comment]
On some platforms, with some versions of gcc, you have to link with `-latomic` to get access to the 128-bit atomic functions.  That appears to be the case with s390x and recent gcc versions.

**Comment by uweigand** [comment]
I talked to @iii-i about this and he had the following comment:

There are a couple QEMU commits in this are that seem to be missing in Unicorn:

```
commit e61f1efeb730fd64441131ea721086065904ff67
Author: Richard Henderson <richard.henderson@linaro.org>
Date:   Sat Nov 5 11:34:58 2022 +0000

    meson: Detect atomic128 support with optimization

commit d2958fb0b6c7bcd8c4e6c0222554ef25d62ecef0
Author: Marc-André Lureau <marcandre.lureau@redhat.com>
Date:   Mon Feb 28 16:03:09 2022 +0400

    meson: fix CONFIG_ATOMIC128 check
```

In particular, the first one says:

```
+/*
+ * If __alignof(unsigned __int128) < 16, GCC may refuse to inline atomics
+ * that are supported by the host, e.g. s390x.  We can force the pointer to
+ * have our known alignment with __builtin_assume_aligned, however prior to
+ * GCC 13 that was only reliable with optimization enabled.  See
+ *   https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107389
+ */
```

which seems to be related to the Unicorn problem.

**Comment by flyn-org** [comment]
Could unicorn pull in the latest version of QEMU? The version of QEMU unicorn presently ships with still uses GNU autotools. This obviously makes backporting the commits above more difficult.

**Comment by patryk4815** [comment]
@wtdcode hi. I have no experience with cmake, so I can't help where to add ldflags.
But i can share what i know (tested on tag: 2.0.1 + dev branch):
❌ armv7l-linux (arm32): fail to build, missing atomic128
✅ aarch64-linux (arm64): success 
✅ i686-linux: success
✅ x86_64-linux: success
❌ mipsel-linux:  fail to build, missing atomic128
✅ ❗mips64-linux: build after adding ldflags "-latomic"
✅ ❗mips64el-linux: build after adding ldflags "-latomic"
✅ ❗powerpc64-linux: build after adding ldflags "-latomic"
❌ riscv32-linux: compiler errors, assertion: `/qemu/compiler.h:183:36: error: static assertion failed: "not expecting: TCG_TARGET_REG_BITS < TARGET_LONG_BITS"`
✅ ❗riscv64-linux: build after adding ldflags "-latomic"
❌ s390-linux: compiler errors `qemu/osdep.h:30:10: fatal error: config-host.h: No such file or directory`
✅ ❗s390x-linux: build after adding ldflags "-latomic"
❗sparc32-linux: i don't have cross compiler for it. someone else need check ;)
❗sparc64-linux: i don't have cross compiler for it. someone else need check ;)

It looks like unicorn don't support 32bit platform (except i686).
64bit supported after adding "-latomic"

According to this issue created by @kashieda (he has armv7l). It looks like arm32 is not supported?

**Comment by wtdcode** [comment]
Yes, as you may notice, the architectures covered by our CI are listed here: https://github.com/unicorn-engine/unicorn/actions/runs/7321961640

I'm not sure about arm32 because I have no device to test, though qemu-system may help. But anyway, I will try to backport `-latomic` when detecting these rare platforms. The easiest way I could think of is just add `-latomic` if the target platform is not the one covered by our CI.

**Comment by patryk4815** [comment]
@wtdcode did you try docker image `arm32v7/ubuntu:23.04`?

**Comment by patryk4815** [comment]
@wtdcode (dev branch) when i added `-DCMAKE_BUILD_TYPE=Debug` looks like now it builds for arm32 on cross 🤔

**Comment by patryk4815** [comment]
@wtdcode (dev branch) when i added `-G Ninja -DCMAKE_BUILD_TYPE=Debug` - success build for arm32 on cross 🤔 
~~probably it was nix fault, that they didnt use proper CMAKE_BUILD_TYPE 👎~~

When I add `-DCMAKE_BUILD_TYPE=Release` build fail.

**Comment by skriesch** [comment]
I have reproduced the issue on openSUSE (Tumbleweed and Leap). The Cmake Build Type Debug has helped together with  "-latomic". I have to add that aarch64 and s390x are failing continuously (if you don't use our rolling release Tumbleweed).

On our stable releases:
aarch64 has got a failing test test_uc_ctl_tb_cache afterwards.
s390x is failing continuously based on the "undefined reference" issue equal to [Fedora](https://github.com/unicorn-engine/unicorn/issues/1840#issuecomment-1636525171).

**Comment by patryk4815** [comment]
> The Cmake Build Type Debug has helped together with "-latomic".

@skriesch can you try with latest "dev" branch? It should be fixed since commit "04064072137649baa8c7d0de140509456b74b8fb" for s390x / riscv64 / mips64 / mips64el / powerpc64 / sparc64.

> `aarch64 has got a failing test test_uc_ctl_tb_cache afterwards.`

Look like different issue

**Comment by skriesch** [comment]
[Builds](https://build.opensuse.org/package/show/home:AdaLovelace:branches:Virtualization/unicorn-master) based on the master branch are looking good/better. We have to wait a little bit for s390x. The rest is succeeding.

Can we receive a new release for the beginning of this year, please? :)

**Comment by skriesch** [comment]
armv7 is failing without the required options:
```
[  323s] /usr/lib/gcc/armv7hl-suse-linux-gnueabi/13/../../../../armv7hl-suse-linux-gnueabi/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_ldo_le_mmu_ppc64'
[  323s] /usr/lib/gcc/armv7hl-suse-linux-gnueabi/13/../../../../armv7hl-suse-linux-gnueabi/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_ldo_be_mmu_ppc64'
[  323s] /usr/lib/gcc/armv7hl-suse-linux-gnueabi/13/../../../../armv7hl-suse-linux-gnueabi/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_cmpxchgo_le_mmu_aarch64'
[  323s] /usr/lib/gcc/armv7hl-suse-linux-gnueabi/13/../../../../armv7hl-suse-linux-gnueabi/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_cmpxchgo_be_mmu_aarch64'
[  323s] /usr/lib/gcc/armv7hl-suse-linux-gnueabi/13/../../../../armv7hl-suse-linux-gnueabi/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_sto_be_mmu_s390x'
[  323s] /usr/lib/gcc/armv7hl-suse-linux-gnueabi/13/../../../../armv7hl-suse-linux-gnueabi/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_ldo_be_mmu_s390x'
[  323s] /usr/lib/gcc/armv7hl-suse-linux-gnueabi/13/../../../../armv7hl-suse-linux-gnueabi/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_cmpxchgo_be_mmu_s390x'
[  323s] /usr/lib/gcc/armv7hl-suse-linux-gnueabi/13/../../../../armv7hl-suse-linux-gnueabi/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_cmpxchgo_be_mmu_ppc64'
[  323s] /usr/lib/gcc/armv7hl-suse-linux-gnueabi/13/../../../../armv7hl-suse-linux-gnueabi/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_sto_be_mmu_ppc64'
[  323s] /usr/lib/gcc/armv7hl-suse-linux-gnueabi/13/../../../../armv7hl-suse-linux-gnueabi/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_cmpxchgo_le_mmu_ppc64'
[  323s] /usr/lib/gcc/armv7hl-suse-linux-gnueabi/13/../../../../armv7hl-suse-linux-gnueabi/bin/ld: libunicorn.so.2: undefined reference to `helper_atomic_sto_le_mmu_ppc64
```

**Comment by patryk4815** [comment]
> [Builds](https://build.opensuse.org/package/show/home:AdaLovelace:branches:Virtualization/unicorn-master) based on the master branch are looking good/better.

@skriesch master branch is 7months old. Please checkout on commit "04064072137649baa8c7d0de140509456b74b8fb" or "dev"
armv7 now build only with `DCMAKE_BUILD_TYPE=Debug` (but for debug builds there will be missing features probably)
@wtdcode is armv7 supported? or can we use "Debug" for it?

**Comment by wtdcode** [comment]
@patryk4815 If debug version works, then somehow the root cause is in our codebase. I need a bit further investigation.

**Comment by wtdcode** [comment]
I pushed a fix which should resolve the root cause of this building issue. But still I will preserve the previous fix by adding `-latomic` as a fallback because there are still a few similar "dangerous code" not removed to keep minimum divergence from qemu code.

Refer to ae1b6ad89be5546d0062115efb6eebd6a74cffde for the root cause.

@patryk4815 Could you try the latest commit?  @kashieda I tested the code builds on qemu emulated arm32, could you test on your raspi?

**Comment by patryk4815** [comment]
@wtdcode now compile fine for arm32 / armv7l

**Comment by kashieda** [comment]
I'll give it a go, if I can re-figure out how :)

**Comment by kashieda** [comment]
I got the code down and tried to build; where do I add -latomic? / Kash

**Comment by wtdcode** [comment]
Just grab the latest dev branch and try to build.

Bests,
Ziqiao

From: kashieda ***@***.***>
Date: Friday, 5 January 2024 at 9:12 PM
To: unicorn-engine/unicorn ***@***.***>
Cc: lazymio ***@***.***>, Mention ***@***.***>
Subject: Re: [unicorn-engine/unicorn] Failing to build on Raspberry 2 (Issue #1840)
I got the code down and tried to build; where do I add -latomic? / Kash

**Comment by kashieda** [comment]
Hey :)

It seems to work - at least I got no errors. Now I have to figure out what
I was going to use it for, in the first place :)

Best, K

**Comment by wtdcode** [comment]
Nice to hear that. I'm closing this issue.
