### ISSUE TITLE
BUGS - bit shift instructions `RCL`, `RCR`, `ROL`, `ROR`, `SAL`, `SAR`, `SHL`, `SHR` compute incorrect results

### ISSUE THREAD

**Issue by basavesh** [unicorn-engine/unicorn#1855]
For example:
Before Executing:
```
RSI: 0xdc40db8452b6cdfb
```
ATT Instruction: `rclq $40, %rsi`

After Executing:
```
RSI: 0xdc40db8452b6cdfb                   <--- wrong
```

Expected result:
```
RSI: 0xb6cdfb6e206dc229
```

@wtdcode

**Comment by basavesh** [comment]
Looks like more of a keystone error than Unicorn Error. Closing this issue.

**Comment by basavesh** [comment]
The problem was with keystone's default radix being 16 and not 10. My x86_64 hardware's default radix is 10. This is a very strange deviation for me.

**Comment by wtdcode** [comment]
lol, that's quite confusing sometimes.
