### ISSUE TITLE
How to generate a coredump when emulation hits a crash?

### ISSUE THREAD

**Issue by c01dkit** [unicorn-engine/unicorn#1858]
Hi there,
Does unicorn support generate a coredump (to save memory data, registers, environment variables, etc.) when emulation hits a crash ( such as UC_ERR_READ_UNMAPPED) ? A coredump can automatically generates in normal linux system. I'm wondering if unicorn has already support the same feature, or one needs to implement such mechanism manually (in exit handler) ?

**Comment by wtdcode** [comment]
Coredump is generated when a process exits abnormally, e.g. `abort()` was called. `UC_ERR_READ_UNMAPPED` means a normal exit, not an `abort()`.

To save a "coredump", you may look at context API.

**Comment by c01dkit** [comment]
Thanks for reply! 
I found functions like `uc_context_*`, `uc_mem_*` and `uc_reg_*`. However, it seems that there is no ***single function*** aims to save all information. ( I'm not sure )
Maybe I should try to combine them.

**Comment by wtdcode** [comment]
uc_context will include both cpu registers and memory if you tweak it by uc_ctl api.
________________________________

**Comment by c01dkit** [comment]
Thanks for reply! I think this issue could be closed  : )
