### ISSUE TITLE
x86 xchg dword ptr [esp], eax invalid semantics...

### ISSUE THREAD

**Issue by CR3Swapper** [unicorn-engine/unicorn#1859]
small test case:

```
PUSH RAX
PUSHFQ
MOV RAX, AbsoluteAddress (or a constant for your test)
POPFQ
XCHG [RSP],RAX
RET
```

same issue for x86.

rax wont be the same as the constant/address in the mov rax...

**Comment by CR3Swapper** [comment]
(i feel retarded creating an issue related to qemu semantic inaccuracies because its highly unlikely that its really an issue on your guys end but ive debugged this for 3 days now)

**Comment by wtdcode** [comment]
It's a bit hard to believe this can't be emulated correctly... Could you give a full script?

**Comment by CR3Swapper** [comment]
😵‍💫

**Comment by CR3Swapper** [comment]
the issue was i was starting the emulation for 30 seconds and then after that time elapsed i read RAX and it wasnt finished emulating.

lmao my bad.
