### ISSUE TITLE
build fails on Ubuntu 12.04 / gcc 4.6

### ISSUE THREAD

**Issue by lunixbochs** [unicorn-engine/unicorn#187]
make[1]: Leaving directory `/home/travis/gopath/src/github.com/lunixbochs/usercorn/unicorn/qemu'
    make unicorn
    make[1]: Entering directory `/home/travis/gopath/src/github.com/lunixbochs/usercorn/unicorn'
      GEN     ./libunicorn.so
    /usr/bin/ld: qemu/x86_64-softmmu/exec.o: relocation R_X86_64_PC32 against symbol `cpu_physical_memory_write_rom_x86_64' can not be used when making a shared object; recompile with -fPIC
    /usr/bin/ld: final link failed: Bad value
    collect2: ld returned 1 exit status
    make[1]: *** [libunicorn.so] Error 1
    make[1]: Leaving directory `/home/travis/gopath/src/github.com/lunixbochs/usercorn/unicorn'
    make: *** [compile_lib] Error 2

**Comment by JonathonReinhart** [comment]
Glad to see you're setting up Travis CI, Ryan. What version of GCC is it using?  Is there anything else special in the `.travis-ci.yml` file? (I looked at your fork, but didn't see it there).

**Comment by lunixbochs** [comment]
I'm setting up Travis for Usercorn, though I could take a look at Unicorn afterwards.

**Comment by lunixbochs** [comment]
I'm currently working around this by using gcc 5: https://github.com/lunixbochs/usercorn/blob/travis/.travis.yml#L10

**Comment by JonathonReinhart** [comment]
Looking at [`Makefile`](https://github.com/unicorn-engine/unicorn/blob/4860fdb/Makefile), I see that `UNICORN_CFLAGS` (which includes `-fPIC`) is only used for configuring qemu. Is this intended to be the case @aquynh?  Should `uc.c` also be compiled with those CFLAGS?

**Comment by aquynh** [comment]
yes `uc.c` and everything should be also compiled with -fPIC. but then why the shared lib has no problem even without this flag?

can you send a PR to fix this? thanks.

**Comment by aquynh** [comment]
@lunixbochs : can you try to see if you can compile Qemu on Ubuntu 12.04?

**Comment by JonathonReinhart** [comment]
@aquynh That brings up a good point. Can we record (in the unicorn source, preferably), exactly which QEMU git commit Unicorn was based off of?  It will help when tracking down bugs like this one, and for the future when someone goes to try and update QEMU in Unicorn.

**Comment by aquynh** [comment]
see https://github.com/unicorn-engine/unicorn/blob/master/qemu/VERSION: we are basing on Qemu 2.2.1 at the moment.

(i plan to sync with newer Qemu sometime later this month)

**Comment by aquynh** [comment]
any ideas on why GCC 4.6 cannot compile?

**Comment by lunixbochs** [comment]
nope. is anything different about the cpu_physical_memory_write_rom_x86_64 from QEMU?

**Comment by aquynh** [comment]
On Nov 14, 2015 12:13 PM, "Ryan Hileman" <notifications@github.com> wrote:
>
> nope. is anything different about the
cpu_physical_memory_write_rom_x86_64 from QEMU?
>

Why do you ask this?

**Comment by lunixbochs** [comment]
It's the symbol in the error from exec.o

**Comment by aquynh** [comment]
this looks like a bug in older GCC, if i am not wrong. see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=19520

**Comment by egberts** [comment]
Confirmed on CentOS 6.6
gcc 4.4.7 20120313 (Red Hat gcc 4.4.7-16)
ld 2.20.51.0.2-5.43.el6 20100205

```sh
$ ./make.sh
if [ "x86 m68k arm aarch64 mips sparc" != "`cat config.log`" ]; then make clean; fi
rm -rf libunicorn* unicorn*.lib unicorn*.dll && cd qemu && make -j 8
make[1]: Entering directory `/home/XXXXXX/admin/emulator/unicorn-master/qemu'
make[1]: Leaving directory `/home/XXXXXX/admin/emulator/unicorn-master/qemu'
make unicorn
make[1]: Entering directory `/home/XXXXXX/admin/emulator/unicorn-master'
  GEN     ./libunicorn.so.0
/usr/bin/ld: qemu/x86_64-softmmu/exec.o: relocation R_X86_64_PC32 against symbol `cpu_physical_memory_write_rom_x86_64' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: ld returned 1 exit status
make[1]: *** [libunicorn.so.0] Error 1
make[1]: Leaving directory `/home/XXXXXX/admin/emulator/unicorn-master'
make: *** [compile_lib] Error 2
[~/admin/emulator/unicorn-master] 
```

**Comment by egberts** [comment]
Figured it out by doing `V=1 make`
* then doing `readelf exec.o | egrep '(GOT|PLT|JU?MP_SLOT)' | grep cpu_physical_write_rom`
to confirm that the compiler did make this function 'exportable'.  It didn't.

CPP expansion of UNICORN_EXPORT resulted into "`__attribute__((visibility("default")))`" which did not make the function exportable.

The following worked in `include/unicorn/unicorn.h` for HAVE_GCC
    `#define UNICORN_EXPORT extern`

Unfortunately, that breaks the sample directory build for all architecture supported.

**Comment by aquynh** [comment]
so confirmed that `unicorn_LDFLAGS="-Wl,-Bsymbolic-functions" ./make.sh` can solve this problem totally on older GCC? if this same setup can be used for newer GCC, should we make this the default setting in `make.sh` ?

**Comment by aquynh** [comment]
i committed this fix https://github.com/unicorn-engine/unicorn/commit/10228dcb121d42305a275291f20412f2bec8d728 for this issue, with @egberts credited. now Unicorn should compile on older GCC without any issues. 

thanks.

**Comment by lunixbochs** [comment]
usercorn travis has been working for a while without resorting to gcc5 - closing this, thanks
