### ISSUE TITLE
The memory regions returned from mem_regions() are not matched with the ones allocated by mem_map() in MIPS

### ISSUE THREAD

**Issue by SaerTrial** [unicorn-engine/unicorn#1877]
```
>>> from unicorn import *
>>> uc = Uc(UC_ARCH_MIPS, UC_MODE_MIPS32 | UC_MODE_LITTLE_ENDIAN)
>>> uc.mem_map(0x9d000000, 0x5000, 7)
>>> uc.mem_map(0x80000000, 0x80000, 7)
>>> for begin, size, perms in uc.mem_regions():
...     print("begin:0x{:x}, size:0x{:x}".format(begin, size))
... 
begin:0x0, size:0x7ffff
begin:0x1d000000, size:0x1d004fff
>>> uc = Uc(UC_ARCH_ARM, UC_MODE_THUMB | UC_MODE_MCLASS | UC_MODE_LITTLE_ENDIAN)
>>> uc.mem_map(0x9d000000, 0x5000, 7)
>>> uc.mem_map(0x80000000, 0x80000, 7)
>>> for begin, size, perms in uc.mem_regions():
...     print("begin:0x{:x}".format(begin))
... 
begin:0x80000000, size:0x8007ffff
begin:0x9d000000, size:0x9d004fff
```

**Comment by PhilippTakacs** [comment]
Are you using the master (or latest release) or the dev branch?

**Comment by SaerTrial** [comment]
The version of unicorn is 2.0.1

**Comment by SaerTrial** [comment]
It seems like that the addresses below 0x80000000 could be allocated correctly

`>>> uc = Uc(UC_ARCH_MIPS, UC_MODE_MIPS32 | UC_MODE_LITTLE_ENDIAN)
>>> uc.mem_map(0x1d000000, 0x5000, 7)
>>> uc.mem_map(0x3d000000, 0x4000, 7)
>>> for begin, size, perms in uc.mem_regions():
...     print("begin:0x{:x}, size:0x{:x}".format(begin, size))
... 
begin:0x1d000000, size:0x1d004fff
begin:0x3d000000, size:0x3d003fff
`

**Comment by wtdcode** [comment]
It looks like our mem_redirect hack which should be already removed in dev branch.
________________________________

**Comment by SaerTrial** [comment]
Thanks for this hint
