### ISSUE TITLE
Win32 & win64 lib download links are not avaliable

### ISSUE THREAD

**Issue by katewashere** [unicorn-engine/unicorn#1882]
Hi, RT

https://github.com/unicorn-engine/unicorn/releases/download/2.0.1/unicorn-2.0.1-win32.zip
https://github.com/unicorn-engine/unicorn/releases/download/2.0.1/unicorn-2.0.1-win64.zip

Also tried to find them in [Github Action](https://github.com/unicorn-engine/unicorn/actions/workflows/build-uc2.yml), but no success.

May I ask, where can I find them ?

**Comment by marameref** [comment]
Is this issue still open? I wish to work on it pls

**Comment by wtdcode** [comment]
The nightly build is available here as an example: https://github.com/unicorn-engine/unicorn/actions/runs/6048147154

We always build for all platforms for every commit but lack a CI to automatically attach them to releases. @marameref we are more than happy if you could help.

**Comment by marameref** [comment]
Hello @wtdcode i will need more context on the issue pls, do you need me to update the readme file with the download links with Win32 & win64 lib for unicorn or should the update be done elsewhere... i will need more context pls, so i can address the issue appropriately. Thanks

**Comment by marameref** [comment]
I have created and tested a yaml build file to address this issue for integrations from Linux platforms.  Pls review my PR, link is https://github.com/unicorn-engine/unicorn/pull/1888  @wtdcode

**Comment by marameref** [comment]
hello @wtdcode ,
I created a pull request for a  workflow on release.yml that automatically creates a release which is triggered by tag push to remote/origin. 
The workflow includes the steps to 
1.	Create a release,
2.	Download artifacts locally
3.	Attach the downloaded artifacts to the release
To trigger this, you can tag your repo using git tag <version> and push the repo to production using git push origin <version>, 
<version> can be  any tag starting with v* eg v0.09, v0.01, v1.2 etc

Pls review and merge my PR.
Thanks

**Comment by marameref** [comment]
@wtdcode 
As requested, I have :
-rebased my PR to dev 
- set prerelease to true and 
- attached pictures of successful run of each workflow. 

Please review and merge. Thanks
link to PR: https://github.com/unicorn-engine/unicorn/pull/1892


![all workflows](https://github.com/unicorn-engine/unicorn/assets/60928319/32017150-334a-4278-aa66-09d5915cc8f7)
![Crate-📦-Distribution-·-Workflow-runs-·-marameref-unicorn](https://github.com/unicorn-engine/unicorn/assets/60928319/efbf01cc-d
![PyPI-📦-Distribution-·-Workflow-runs-·-marameref-unicorn](https://github.com/unicorn-engine/unicorn/assets/60928319/f6a88c43-94f5-429b-9f78-a91260194274)
e78-45b1-88ac-bb2d482b9a58)


![Upload-Release-Assets-·-Workflow-runs-·-marameref-unicorn](https://github.com/unicorn-engine/unicorn/assets/60928319/a32511c9-393b-4b8a-b0e2-84808a0137a4)

**Comment by kenixter** [comment]
> Hi, RT
> 
> https://github.com/unicorn-engine/unicorn/releases/download/2.0.1/unicorn-2.0.1-win32.zip https://github.com/unicorn-engine/unicorn/releases/download/2.0.1/unicorn-2.0.1-win64.zip
> 
> Also tried to find them in [Github Action](https://github.com/unicorn-engine/unicorn/actions/workflows/build-uc2.yml), but no success.
> 
> May I ask, where can I find them ?

I Can't download too..
This problem hasn't been resolved, right?
Is there anyone help me? plz

**Comment by wtdcode** [comment]
Distributed at https://github.com/unicorn-engine/unicorn/releases/tag/2.1.0 now
