### ISSUE TITLE
xsavec triggers invalid instruction

### ISSUE THREAD

**Issue by niansa** [unicorn-engine/unicorn#1885]
I have this assembly:
```
    frame #0: 0x00007ffff7fdd438
->  0x7ffff7fdd438: xsavec 0x40(%rsp)
    0x7ffff7fdd43d: movq   0x10(%rbx), %rsi
    0x7ffff7fdd441: movq   0x8(%rbx), %rdi
    0x7ffff7fdd445: callq  0x7ffff7fdb030
```
And the marked line is where unicorn stops executing with `UC_ERR_INSN_INVALID`. Do I need so do something specific to support this instruction?

**Comment by wtdcode** [comment]
Probably need to switch cpu models

**Comment by niansa** [comment]
Is this documented anywhere?

**Comment by wtdcode** [comment]
https://github.com/unicorn-engine/unicorn/wiki/FAQ#emulating-some-instructions-gives-an-error-like-invalid-instruction-what-should-i-do

**Comment by niansa** [comment]
Ahhh, thank you!
I was only looking at the website so far, completely missed the wiki!
