### ISSUE TITLE
exit() in libunicorn

### ISSUE THREAD

**Issue by luigino** [unicorn-engine/unicorn#191]
Possibly a false positive, but rpmlint complains about it:

    RPMLINT report:
    ===============
    libunicorn0.x86_64: W: shared-lib-calls-exit /usr/lib64/libunicorn.so.0 exit@GLIBC_2.2.5
    This library package calls exit() or _exit(), probably in a non-fork()
    context. Doing so from a library is strongly discouraged - when a library
    function calls exit(), it prevents the calling program from handling the
    error, reporting it to the user, closing files properly, and cleaning up any
    state that the program has. It is preferred for the library to return an
    actual error code and let the calling program decide how to handle the
    situation.

**Comment by aquynh** [comment]
yes originally Qemu just aborts whenever it cannot handle errors. we already fixed a lot of code like this, but do not touch those we cannot reproduce. so perhaps this is false positive, and those exit() are just dead code. will fix whenever we get reports from users, or when we have more time to look at that, but so far we dont have any problem.

will put this in our TODO list, thanks!
