### ISSUE TITLE
v2.1.0 Plan

### ISSUE THREAD

**Issue by wtdcode** [unicorn-engine/unicorn#1924]
Hey community!

Finally, I got some time on releasing the next version, v2.1.0. So far, my top priority todo list includes:

- [x] Fully support M1, including CI, binary release etc giving the fact that Github is providing free runners. ~~(mostly done! still fixing)~~ (Really tedious due to apple closed source nature...)
- ~~[ ] Push java bindings to maven central~~ (postponed due to excessively CI work)
- [x] Port new py3 bindings and py2 compatibility #1629 #1823
- [x] Fix msvc linkage #1796 

I'm also considering some urgent bugs fixes to be released in this version so I'm hearing from you! I wish to release this in Feb, hopefully.

**Comment by mrj0n3s** [comment]
Would be fantastic if you could fix https://github.com/unicorn-engine/unicorn/issues/1869

**Comment by wtdcode** [comment]
@mrj0n3s I'm afraid I don't have time to send a patch to qemu or we have to fix it on our side. I will have a check the complexity of that issue.

**Comment by Montg0mery** [comment]
Great to hear that there's an upcoming release! This project is so useful.

I would love it if you would take a look at #1925.

**Comment by wtdcode** [comment]
#1925 is probably out-of-scope because:

- Unicorn and capstone are two projects overall. And even if you consider both are forks, they are forked from different projects. 
- The definitions provided by both projects are very different. For example, I don't see how to trivially map `UC_ARM_REG_CP_REG` to some equavelents.

**Comment by wtdcode** [comment]
#1869 is fixed and I sent a patch to QEMU for further review.

**Comment by Montg0mery** [comment]
> #1925 is probably out-of-scope because:
> 
>     * Unicorn and capstone are two projects overall. And even if you consider both are forks, they are forked from different projects.
> 
>     * The definitions provided by both projects are very different. For example, I don't see how to trivially map `UC_ARM_REG_CP_REG` to some equavelents.
> 
>     * This easily breaks our compatibility.

OK, thank you for the explanation.

**Comment by wtdcode** [comment]
Report from Eli, `UC_ERR_INSN_INVALID` doesn't respect the users' return value and halts emulation unconditionally.

**Comment by wtdcode** [comment]
> Report from Eli, `UC_ERR_INSN_INVALID` doesn't respect the users' return value and halts emulation unconditionally.

Fixed

**Comment by wtdcode** [comment]
Another TODO: Fix CI...

**Comment by wtdcode** [comment]
Closing.
