### ISSUE TITLE
Question and maybe even suggestion : )

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [unicorn-engine/unicorn#1926]
How this can be used to apply it to an Windows on ARM bootloader so that when an Intel PC user can natively run that bootloader and from there start the emulation of an ARM CPU architecture to be able to run Windows ARM on Intel CPUs natively. Or better, could an Windows/Linux bootloader be made that is basically like QEMU/Unicorn bootloader that supports many OS bootloaders so when an bootloader is selected from it it will emulate correct CPU architecture to be able to boot into it - it would be very interesting to see an Unicorn Bootloader Project for PCs (Windows and Linux users)

Thanks in advance for this wonderful emulation! Bless you and your family so much : )

**Comment by wtdcode** [comment]
That's far out of scope of unicorn duty. The similar thing you are looking for is QEMU system emulation and a Tier 1 hypervisor. For example, starting `qemu-system-aarch64` on proxmox is pretty a good start.

**Comment by wtdcode** [comment]
Close due to off-topic
