### ISSUE TITLE
API for switching emulation to a different "uc_mode"

### ISSUE THREAD

**Issue by gaffe23** [unicorn-engine/unicorn#193]
When Unicorn emulates processors with multiple modes, it doesn't have any problems switching between the modes on the fly during emulation. For example, when it hits a `BLX` instruction on ARM, it properly switches between ARM and Thumb state. However, if you want to switch between modes yourself, there doesn't seem to be an easy way to do that. It would be helpful to have an API that allows you to switch the emulation to a different `uc_mode`, like going from `UC_MODE_ARM` to `UC_MODE_THUMB`.

**Comment by lunixbochs** [comment]
Very closely related to #117. I think they could be implemented in the same way.

**Comment by aquynh** [comment]
no we cannot change the mode dynamically at run-time now. it is true that #117 is related to your request, and we will definitely need to support this feature in our next releases.

**Comment by lunixbochs** [comment]
Related to this request, I've implemented enough ARM support in Usercorn that I probably need to be able to retrieve the current ARM/Thumb mode of the CPU.

**Comment by aquynh** [comment]
i think we would need 2 new APIs like below (the final API name is subject to change)

- **uc_option(uc, UC_OPT_XXX, size_t value)**: this is to customize (set) runtime option of engine
- **uc_query(uc, UC_QUERY_XXX, size_t *value)**: this is to query (get) CPU context at runtime

**Comment by aquynh** [comment]
i added these 2 APIs to the TODO list: https://github.com/unicorn-engine/unicorn/wiki/TODO

**Comment by robhshu** [comment]
**uc_query** has been added. See #397 to suggest other queries.

**Comment by wtdcode** [comment]
re-open and link to #1449

**Comment by wtdcode** [comment]
API added.
