### ISSUE TITLE
Setting RIP inside callback doesn't change execution flow

### ISSUE THREAD

**Issue by smuthayan** [unicorn-engine/unicorn#1952]
Hello!
I place a hook on UC_MEM_FETCH_PROT. Inside the hook, I overwrite UC_X86_REG_RIP to a different address and return true to change the flow of execution. Instead, the code keeps executing at the previous RIP. It even leaves UC_X86_REG_RIP unchanged as it's executing. Is this normal behavior?

**Comment by wtdcode** [comment]
Could you provide a reproduction?

**Comment by smuthayan** [comment]
Hi. I think this was due to the fact that the RIP register is only synced at certain points. Instead, i just catch the error from uc_emu_start and set the RIP there and restart emulation.
