### ISSUE TITLE
Paging doesn't work on x86, is that by design?

### ISSUE THREAD

**Issue by kukrimate** [unicorn-engine/unicorn#1953]
Specifically the following patch to `qemu/target/i386/excp_helper.c`:646 makes paging non-functional:
```c
    // Unicorn: indentity map guest virtual address to host virtual address
    vaddr = addr & TARGET_PAGE_MASK;
    paddr = vaddr;
```

**Comment by wtdcode** [comment]
This should be addressed by e96ac42b2e8f8ded790fd156ef5a5d55ac088acb

**Comment by kukrimate** [comment]
Great, so if I rebase on the dev branch, I should be able to set a flag to disable forced identity mapping?

**Comment by wtdcode** [comment]
Identity mapping is disabled by default on dev branch and further 2.1.0 release.

**Comment by kukrimate** [comment]
Thank you for the quick reply, closing this.
