### ISSUE TITLE
Confusing `CMAKE_MSVC_RUNTIME_LIBRARY` checks

### ISSUE THREAD

**Issue by es3n1n** [unicorn-engine/unicorn#1958]
Hey!

I was working on a project that is being built by MSVC and it has a few more dependencies along with unicorn. One of the dependencies explicitly sets its MSVC_RUNTIME_LIBRARY to MT(d), and because of that, I need to set unicorn's runtime library type to the static one too. However, to my surprise, I can't just set MSVC_RUNTIME_LIBRARY because of the following checks:

https://github.com/unicorn-engine/unicorn/blob/5f5ef1546c4447fff3442682caa969ba075da329/CMakeLists.txt#L112-L124

Is there any reason why we can't set the `MSVC_RUNTIME_LIBRARY` by ourselves? Can't this code be changed to 
```cmake
if(NOT DEFINED CMAKE_MSVC_RUNTIME_LIBRARY)
    if(CMAKE_C_FLAGS MATCHES "[/-]MTd")
        set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreadedDebug")
    elseif(CMAKE_C_FLAGS MATCHES "[/-]MDd")
        set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreadedDebugDLL")
    elseif(CMAKE_C_FLAGS MATCHES "[/-]MT")
        set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded")
    elseif(CMAKE_C_FLAGS MATCHES "[/-]MD")
        set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreadedDLL")
    endif()
endif()
```

Since this code was added in 2912cd1e299456e71f9fc52b046d84cf1aff2144, I think the person who could explain me that would be @shuffle2.

I changed that part of the code to my suggestion and everything seemed to be working just fine, but I tested it only with my C++ project, so I might be missing something crucial for Rust there. Unfortunately, I don't have any Rust toolchains to check this.

**Comment by es3n1n** [comment]
If my proposed changes indeed still working with rust, then I would be happy to open a PR, but please let me know what was the reason for that behaviour in the first place, as it doesn't make much sense to me.

**Comment by recoil24** [comment]
It`s made for cmake lovers :)
Normal people use .sln

**Comment by es3n1n** [comment]
Thanks for the explanation, it does make much more sense now.

> In general, it is not recommended to link against static msvc runtime. It is much worse to hardcode the setting, like your dependency is doing. I'd rather suggest you modify the other dependency to use DLL or at least settable at compile time.

I agree, and I already notified the maintainer, but I still wanted to ask about that check since it looked weird.

> Having thought about it more, if you want to implement the consistency check (to see if CMAKE_MSVC_RUNTIME_LIBRARY and CMAKE_C_FLAGS conflict), then set CMAKE_MSVC_RUNTIME_LIBRARY if not already set - I think that would be ok.

Yeah, I wanted it to throw an error if both CMAKE_MSVC_RUNTIME_LIBRARY and CMAKE_C_FLAGS are set. If this indeed does sound good, then I would be happy to implement that myself. 

> fwiw, you really don't need to change unicorn to get your dependent project to work - just set CMAKE_C_FLAGS for unicorn from your project instead of CMAKE_MSVC_RUNTIME_LIBRARY

Thanks, I am aware of that.

**Comment by wtdcode** [comment]
> Yeah, I wanted it to throw an error if CMAKE_MSVC_RUNTIME_LIBRARY and CMAKE_C_FLAGS are conflicting. If this indeed does sound good, then I would be happy to implement that myself.

This options sounds go to me.

**Comment by wtdcode** [comment]
Close as PR gets through.
