### ISSUE TITLE
On-Demand mapping of memory

### ISSUE THREAD

**Issue by ranmrdrakono** [unicorn-engine/unicorn#199]
Hey, is there a way to map memory on demand (e.g. in an mem_fetch_invalid callback)? It seems that that just mapping/writing the required memory in the callback and return with true will still terminate the execution:

```golang
	invalid := uc.HOOK_MEM_READ_INVALID | uc.HOOK_MEM_WRITE_INVALID | uc.HOOK_MEM_FETCH_INVALID
	mu.HookAdd(invalid, func(mu uc.Unicorn, access int, addr uint64, size int, value int64) bool {
    mu.MemMap(addr, uint64(size))
    mu.MemWrite(addr, s.GetMem(addr,size))
		return true
	})
```

**Comment by aquynh** [comment]
yes, you can definitely map memory on demand in your instrumentation handlers, like in the samples you can find in https://github.com/unicorn-engine/unicorn/blob/master/bindings/python/sample_x86.py and https://github.com/unicorn-engine/unicorn/blob/master/samples/sample_x86.c

can you post the full code so it is possible to reproduce the issue?

(you may want to take a look at the source of Usercon at https://github.com/lunixbochs/usercorn to see how Go program handle dynamic memory mapping)

**Comment by ranmrdrakono** [comment]
Sorry it seems that MemMap needs to map entire pages. Therefore it is important to make sure to use proper alignment & size needs to be a multiple of the pagesize.

**Comment by aquynh** [comment]
yes, see documentation of `uc_mem_map()` at https://github.com/unicorn-engine/unicorn/blob/master/include/unicorn/unicorn.h#L434
