### ISSUE TITLE
QEMU base version?

### ISSUE THREAD

**Issue by pewterbrass** [unicorn-engine/unicorn#1996]
Does anyone know what exact commit of QEMU the current Unicorn code on the dev branch is based on?

I know there's been some rebasing of code from QEMU over the years. 

The reason is I want to be able to differentiate exactly what changes  to QEMU have been made for Unicorn. Im struggling with getting hypervisor and IPA (intermediary physical addresses) to work in ARM64 firmware that utilizes VMs and the ARM hypervisor framework (EL2 etc)

**Comment by aquynh** [comment]
Version 5.0.2

**Comment by wtdcode** [comment]
> Version 5.0.2

It shall be 5.0.1, no?

**Comment by aquynh** [comment]
yes, that is 5.0.1

https://github.com/unicorn-engine/unicorn/blob/master/qemu/VERSION

**Comment by pewterbrass** [comment]
Thanks!

**Comment by wtdcode** [comment]
Closing.
