### ISSUE TITLE
How to debug or turn off dynamic code snippets

### ISSUE THREAD

**Issue by 1034063174** [unicorn-engine/unicorn#2013]
In one of my runs, when executing the "shl dword ptr ss:[rsp+rcx*1-0x5D], cl" instruction, the cc_src in it is somehow equal to eip. This causes the calculated eflags to be wrong. When I tried to debug it, I found that the relevant code is dynamic code（Just like in the picture）. How can I debug the relevant code of unicorn? Should I look at the assembly of the dynamic code line by line, or is there any other better way? Sorry, this question may be stupid.
![1727319023745](https://github.com/user-attachments/assets/7cd60cc2-f0d5-434b-8f95-4628cdfd97e9)
![1727319629171](https://github.com/user-attachments/assets/29ccb95a-a8da-44a2-8f68-abc5c7912e60)

**Comment by 1034063174** [comment]
To add, I use vs2022 on windows and unicorn to simulate x86_64

**Comment by wtdcode** [comment]
dup of #1717

**Comment by wtdcode** [comment]
Closing.
