### ISSUE TITLE
UNICORN_DEBUG test backwards

### ISSUE THREAD

**Issue by JonathonReinhart** [unicorn-engine/unicorn#204]
As @anthraxx [reported](https://github.com/unicorn-engine/unicorn/issues/183#issuecomment-149059306), the UNICORN_DEBUG test [appears to be backwards](https://github.com/unicorn-engine/unicorn/blob/4860fd/Makefile#L61):

```Makefile
ifeq ($(UNICORN_DEBUG),yes)
CFLAGS += -O3
else
CFLAGS += -g
endif
```

And [Unicorn 0.9](https://github.com/unicorn-engine/unicorn/blob/0.9/config.mk#L11) shipped with this set to "yes".

**Comment by aquynh** [comment]
so we accidentally shipped the right setup for v0.9 :-)

fixed now, thanks
