### ISSUE TITLE
Supporting more host platform

### ISSUE THREAD

**Issue by Naville** [unicorn-engine/unicorn#2051]
Hi:
Following #2050 , I'm porting uc to more host environment.

For now, I'm targeting X86_64-Windows.
I've used WSL to execute create_config and configure, with some CRLF/LF patches, and made it past the configuration stage, as well as  adding include guard checks at many places to support building on environments with a **limited** libC functionality as well as shims.

However, now I'm stuck with the SJLJ code (to be precise: ``sigsetjmp / siglongjmp`` ) everywhere. Is it possible to disable those?

**Comment by wtdcode** [comment]
WSL2 should be supported out-of-box. Regarding WSL1, I have no idea and experience porting code for it.

**Comment by Naville** [comment]
> WSL2 should be supported out-of-box. Regarding WSL1, I have no idea and experience porting code for it.

我指的是, 在Windows下使用wsl来调用qemu/configure 和qemu/scripts/create_config 来生成对应的.h文件
现在在原生Windows上这是会失败的, 而且因为execute_process没有加COMMAND_ERROR_IS_FATAL ANY会导致静默失败

**Comment by aquynh** [comment]
What do you mean? Qemu may not work on Windows, but Unicorn does.
