### ISSUE TITLE
ARM64: paci[ab] and reta[ab] instructions are not supported

### ISSUE THREAD

**Issue by shmuelfomberg** [unicorn-engine/unicorn#2052]
these instructions encrypt and decrypt the function return address using a key. (a or b)
However, unicorn detect them as invalid instructions. 

A simple emulation can be xoring the address with a constant. or simply making pacia as nop and retaa as normal ret.

**Comment by wtdcode** [comment]
See #1522

**Comment by wtdcode** [comment]
And #1818 with doc: https://github.com/unicorn-engine/unicorn/wiki/FAQ#does-unicorn-support-arm-pac-pointer-authentication

**Comment by shmuelfomberg** [comment]
thank you, but the doc does not exists any more.

**Comment by shmuelfomberg** [comment]
so if I understand correctly, I need to setup my environment correctly, (by setting up various MSRs) and then it will work. thank you.
