### ISSUE TITLE
RUST BINDINGS: uc_reg_{read,write}_batch for rust

### ISSUE THREAD

**Issue by hsa1as** [unicorn-engine/unicorn#2059]
Hi,

I'd noticed that `uc_reg_read_batch` and `uc_reg_write_batch` do not have bindings in rust,

Can I open a PR to add these? 
My fix is here: https://github.com/unicorn-engine/unicorn/compare/dev...hsa1as:unicorn:dev

**Comment by wtdcode** [comment]
Sure yes. You are highly welcome.
________________________________
From: Sai Ashwin ***@***.***>
Sent: Thursday, December 5, 2024 12:18:52 AM
To: unicorn-engine/unicorn ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [unicorn-engine/unicorn] RUST BINDINGS: uc_reg_{read,write}_batch for rust (Issue #2059)


Hi,

I'd noticed that uc_reg_read_batch and uc_reg_write_batch do not have bindings in rust,

Can I open a PR to add these?
My fix is here: dev...hsa1as:unicorn:dev<https://github.com/unicorn-engine/unicorn/compare/dev...hsa1as:unicorn:dev>

―

**Comment by wtdcode** [comment]
Closing due to fixed already.
