### ISSUE TITLE
Compilation fails if python3 is the default interpreter

### ISSUE THREAD

**Issue by williballenthin** [unicorn-engine/unicorn#206]
Compilation via `make.sh` fails if Python 3.x is the default interpreter. Seems qemu requires Python 2.x.

error:
```
./configure --extra-cflags="-DUNICORN_HAS_X86 -DUNICORN_HAS_ARM -DUNICORN_HAS_M68K -DUNICORN_HAS_ARM64 -DUNICORN_HAS_MIPS -DUNICORN_HAS_MIPSEL -DUNICORN_HAS_MIPS64 -DUNICORN_HAS_MIPS64EL -DUNICORN_HAS_SPARC -fPIC -fvisibility=hidden" --target-list="x86_64-softmmu, arm-softmmu, m68k-softmmu, aarch64-softmmu, mips-softmmu, mipsel-softmmu, mips64-softmmu, mips64el-softmmu, sparc-softmmu,sparc64-softmmu," 

ERROR: Cannot use 'python', Python 2.4 or later is required.
       Note that Python 3 or later is not yet supported.
       Use --python=/path/to/python to specify a supported Python.
```

I got it working using the following minor patch:

```
diff --git a/Makefile b/Makefile
index 4ce6473..ff4b15f 100644
--- a/Makefile
+++ b/Makefile
@@ -206,11 +206,11 @@ config:
 qemu/config-host.h-timestamp:
 ifeq ($(UNICORN_DEBUG),yes)
        cd qemu && \
-       ./configure --extra-cflags="$(UNICORN_CFLAGS)" --target-list="$(UNICORN_TARGETS)" ${UNICORN_QEMU_FLAGS}
+       ./configure --python="$(which python2)" --extra-cflags="$(UNICORN_CFLAGS)" --target-list="$(UNICORN_TARGETS)" ${UNICORN_QEMU_FLAGS}
        printf "$(UNICORN_ARCHS)" > config.log
 else
        cd qemu && \
-       ./configure --disable-debug-info --extra-cflags="$(UNICORN_CFLAGS)" --target-list="$(UNICORN_TARGETS)" ${UNICORN_QEMU_FLAGS}
+       ./configure --python="$(which python2)" --disable-debug-info --extra-cflags="$(UNICORN_CFLAGS)" --target-list="$(UNICORN_TARGETS)" ${UNICORN_QEMU_FLAGS}
        printf "$(UNICORN_ARCHS)" > config.log
 endif
```

As you can see, it depends on `which` resolving `python2`, which should work on Linuxes. I don't have much experience with the portability of this approach.

**Comment by gaffe23** [comment]
In my experience, `python2` doesn't resolve on OS X.

I think the idea here is that you can pass the appropriate `--python=/path/to/python` parameter for your own Python setup using `UNICORN_QEMU_FLAGS`. Admittedly, that wasn't clear to me either, so I also just started modifying the `Makefile` until I got it to work. It is mentioned in `COMPILE.TXT`, though.

**Comment by williballenthin** [comment]
Ah, good catch on `UNICORN_QEMU_FLAGS`. Since `python2` isn't portable, perhaps the appropriate fix is a short update to `COMPILE.TXT`?

**Comment by aquynh** [comment]
would be better if we can fix this issue to support Python3 rather than fixing our docs.

**Comment by aquynh** [comment]
yes actually this issue was discussed at https://github.com/unicorn-engine/unicorn/issues/107, and can be solved with UNICORN_QEMU_FLAGS.

@williballenthin, if you can kindly send a PR to update COMPILE.TXT on this Python trick, i will happily merge it.

thanks.

**Comment by williballenthin** [comment]
done, but certainly open to feedback if you don't like the wording

**Comment by aquynh** [comment]
fixed, thanks!
