### ISSUE TITLE
Change behaviour of the RDTSC instruction

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [unicorn-engine/unicorn#2065]
Is it possible to tell Unicorn to change the values returned by the RDTSC instruction of amd64? I'm emulating some code that is hitting some timeout logic when I add code hooks that print debug information. So I'm looking for something the allows me to make that instruction always return 0 or have a timing system based on the number of instructions executed.

**Comment by wtdcode** [comment]
Close as PR got merged.
