### ISSUE TITLE
Python module installers ImportError

### ISSUE THREAD

**Issue by McLovi9** [unicorn-engine/unicorn#208]
I tried "Python 2.7 module for Windows" installers and its not working out of the box.
----------
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import unicorn
  File "C:\Python27\lib\site-packages\unicorn\__init__.py", line 4, in <module>
    from unicorn import Uc, uc_version, uc_arch_supported, version_bind, debug, UcError
  File "C:\Python27\lib\site-packages\unicorn\unicorn.py", line 81, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")

------
I've tested on 32-bit XP and 64-bit Win7 the same problem

**Comment by aquynh** [comment]
can you copy this attach file to overwrite your C:\python27\Lib\site-packages\unicorn\unicorn.py, then run your Python code again to see what is the output?

[unicorn.txt](https://github.com/unicorn-engine/unicorn/files/17235/unicorn.txt)

**Comment by McLovi9** [comment]
Python 2.7.3 (default, Apr 10 2012, 23:31:26) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import unicorn
1. Trying to load: C:\Python27\lib\site-packages\unicorn\libwinpthread-1.dll
1. Trying to load: C:\Python27\lib\site-packages\unicorn\libgcc_s_dw2-1.dll
1. Trying to load: C:\Python27\lib\site-packages\unicorn\libintl-8.dll
1. Trying to load: C:\Python27\lib\site-packages\unicorn\libunicorn.so
1. Trying to load: C:\Python27\lib\site-packages\unicorn\libunicorn.dylib
2. Trying to load: C:\Python27\Lib\site-packages\unicorn\libwinpthread-1.dll
2. Trying to load: C:\Python27\Lib\site-packages\unicorn\libgcc_s_dw2-1.dll
2. Trying to load: C:\Python27\Lib\site-packages\unicorn\libintl-8.dll
2. Trying to load: C:\Python27\Lib\site-packages\unicorn\libunicorn.so
2. Trying to load: C:\Python27\Lib\site-packages\unicorn\libunicorn.dylib

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import unicorn
  File "C:\Python27\lib\site-packages\unicorn\__init__.py", line 4, in <module>
    from unicorn import Uc, uc_version, uc_arch_supported, version_bind, debug, UcError
  File "C:\Python27\lib\site-packages\unicorn\unicorn.py", line 85, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
>>>

**Comment by Mar10us** [comment]
Try changing the order of the dll loading into:
_all_windows_dlls = ("libwinpthread-1.dll", "libgcc_s_seh-1.dll", "libiconv-2.dll", "libintl-8.dll","libglib-2.0-0.dll")

Also: I removed "libgcc_s_dw2-1.dll" from the list because it doesnot exist in the zip or package

**Comment by McLovi9** [comment]
Python 2.7.3 (default, Apr 10 2012, 23:31:26) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import unicorn

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import unicorn
  File "C:\Python27\lib\site-packages\unicorn\__init__.py", line 4, in <module>
    from unicorn import Uc, uc_version, uc_arch_supported, version_bind, debug, UcError
  File "C:\Python27\lib\site-packages\unicorn\unicorn.py", line 19, in <module>
    lib_path = split(__file_)[0]+'\\'
NameError: name '__file_' is not defined
>>>

**Comment by McLovi9** [comment]
Python 2.7.3 (default, Apr 10 2012, 23:31:26) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import unicorn

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import unicorn
  File "C:\Python27\lib\site-packages\unicorn\__init__.py", line 4, in <module>
    from unicorn import Uc, uc_version, uc_arch_supported, version_bind, debug, UcError
  File "C:\Python27\lib\site-packages\unicorn\unicorn.py", line 19, in <module>
    lib_path = split(__file_)[0]+'\\'
NameError: name '__file_' is not defined
>>>

**Comment by McLovi9** [comment]
Python 2.7.3 (default, Apr 10 2012, 23:31:26) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import unicorn

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import unicorn
  File "C:\Python27\lib\site-packages\unicorn\__init__.py", line 4, in <module>
    from unicorn import Uc, uc_version, uc_arch_supported, version_bind, debug, UcError
  File "C:\Python27\lib\site-packages\unicorn\unicorn.py", line 19, in <module>
    lib_path = split(__file_)[0]+'\\\'
NameError: name '__file_' is not defined
>>>

**Comment by Mar10us** [comment]
Looks like you removed a underscore after __file_ ?

**Comment by Mar10us** [comment]
Did you copied the line from this site or did you added the backslashes manually?

**Comment by McLovi9** [comment]
I copied it from this site

**Comment by McLovi9** [comment]
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import unicorn
  File "C:\Python27\lib\site-packages\unicorn\__init__.py", line 4, in <module>
    from unicorn import Uc, uc_version, uc_arch_supported, version_bind, debug, UcError
  File "C:\Python27\lib\site-packages\unicorn\unicorn.py", line 29, in <module>
    _lib_file = join(_lib_path, dll)
NameError: name '_lib_path' is not defined

**Comment by Mar10us** [comment]
copying directly from this site is not the best way to alter code...
This time you are missing the trailing underscore on line 19; it should be _lib_path

`_lib_path = split(__file__)[0]+'\\'`

**Comment by McLovi9** [comment]
>>> import unicorn
1. Trying to load: C:\Python27\lib\site-packages\unicorn\libwinpthread-1.dll
1. Trying to load: C:\Python27\lib\site-packages\unicorn\libiconv-2.dll
1. Trying to load: C:\Python27\lib\site-packages\unicorn\libunicorn.so
1. Trying to load: C:\Python27\lib\site-packages\unicorn\libunicorn.dylib
2. Trying to load: C:\Python27\Lib\site-packages\unicorn\libwinpthread-1.dll
2. Trying to load: C:\Python27\Lib\site-packages\unicorn\libiconv-2.dll
2. Trying to load: C:\Python27\Lib\site-packages\unicorn\libunicorn.so
2. Trying to load: C:\Python27\Lib\site-packages\unicorn\libunicorn.dylib

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import unicorn
  File "C:\Python27\lib\site-packages\unicorn\__init__.py", line 4, in <module>
    from unicorn import Uc, uc_version, uc_arch_supported, version_bind, debug, UcError
  File "C:\Python27\lib\site-packages\unicorn\unicorn.py", line 85, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
>>>

**Comment by Mar10us** [comment]
stick to the proposed order of dll's

**Comment by McLovi9** [comment]
I do stick to the proposed order of dll 
_all_windows_dlls = ("libwinpthread-1.dll", "libgcc_s_seh-1.dll", "libiconv-2.dll", "libintl-8.dll","libglib-2.0-0.dll")

Adding print 'error loading='+ _lib_file did not changed anything (nothing new in the log)

**Comment by aquynh** [comment]
@McLovi9, can you paste the output with the above DLL list?

**Comment by McLovi9** [comment]
its the same (nothing new in the log)

>>> import unicorn
1. Trying to load: C:\Python27\lib\site-packages\unicorn\libwinpthread-1.dll
1. Trying to load: C:\Python27\lib\site-packages\unicorn\libiconv-2.dll
1. Trying to load: C:\Python27\lib\site-packages\unicorn\libunicorn.so
1. Trying to load: C:\Python27\lib\site-packages\unicorn\libunicorn.dylib
2. Trying to load: C:\Python27\Lib\site-packages\unicorn\libwinpthread-1.dll
2. Trying to load: C:\Python27\Lib\site-packages\unicorn\libiconv-2.dll
2. Trying to load: C:\Python27\Lib\site-packages\unicorn\libunicorn.so
2. Trying to load: C:\Python27\Lib\site-packages\unicorn\libunicorn.dylib

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import unicorn
  File "C:\Python27\lib\site-packages\unicorn\__init__.py", line 4, in <module>
    from unicorn import Uc, uc_version, uc_arch_supported, version_bind, debug, UcError
  File "C:\Python27\lib\site-packages\unicorn\unicorn.py", line 86, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
>>> 

Sadly, I cant attach my unicorn.py file.

**Comment by aquynh** [comment]
for Win XP, can you use this order and report the result?

    _all_windows_dlls = ("libwinpthread-1.dll", "libgcc_s_dw2-1.dll", "libiconv-2.dll", "libintl-8.dll","libglib-2.0-0.dll")

**Comment by aquynh** [comment]
for Win64, can you use this order?

    _all_windows_dlls = ("libwinpthread-1.dll", "libgcc_s_seh-1.dll", "libiconv-2.dll", "libintl-8.dll", "libglib-2.0-0.dll")

**Comment by aquynh** [comment]
to keep it simple, overwrite your `c:\python27\lib\site-packages\unicorn\unicorn.py` with this file https://gist.githubusercontent.com/aquynh/eb0fc442f3e7e17e5bb0/raw/748279d75dbd919bf50f2375ae7a6d847e73fd55/unicorn.py on both your Win32 XP & Win64 7 to see if it solves your problem.

**Comment by McLovi9** [comment]
wow, it seems to work! I mean import unicorn no error (tested on XP and Win7 x64). Thank you

**Comment by aquynh** [comment]
fixed this issue in Python binding & also uploaded new Windows binaries with this new fix. thanks.

**Comment by egberts** [comment]
When executing `import unicorn`, now getting `ImportError` on my CentOS 6.6...

```c
$ python
Python 2.6.6 (r266:84292, Nov 22 2013, 12:16:22)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import unicorn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/unicorn/__init__.py", line 4, in <module>
    from .unicorn import Uc, uc_version, uc_arch_supported, version_bind, debug, UcError
  File "/usr/lib/python2.6/site-packages/unicorn/unicorn.py", line 81, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
```

Same error message using the maintainer's `unicorn.txt` as `unicorn.py` inside `/usr/lib/python/site-packages/unicorn`.

Performed following command to get a feel of what Python is trying to open during this simple Python `import unicorn` statement:
```sh
echo "import unicorn" > test.py
chmod a+x test.py
strace -f test.py 2>&1 | grep open | grep -v "No such file"
```
Output is captured here: [strace-opens.log.txt](https://github.com/unicorn-engine/unicorn/files/70359/strace-opens.log.txt)
