### ISSUE TITLE
Changing PC from within an UC_HOOK_CODE doesn't work

### ISSUE THREAD

**Issue by hugoreinaldo** [unicorn-engine/unicorn#210]
Is there a way to change the program counter from within an UC_HOOK_CODE ? None of the following examples seem to work: 

    def hook_code(uc, address, size, userdata):
        uc.reg_write(arm_const.UC_ARM_REG_PC, 0x00)

    def hook_code(uc, address, size, userdata):
        uc.mem_write(address+size, 0x00)

**Comment by lunixbochs** [comment]
Try stopping emulation and doing an emu_start() at the new address.

**Comment by aquynh** [comment]
Can you send a pull request to put your testcase under tests/regress/, so it is possible to test and confirm this issue? Thanks

**Comment by gaffe23** [comment]
There are test cases for this in `tests/regress/callback-pc.py` using both `UC_HOOK_CODE` and `UC_HOOK_BLOCK`.

**Comment by hugoreinaldo** [comment]
@lunixbochs I'm trying your solution as a workaround for the issue.

@gaffe23 The test case tests/regress/callback-pc.py covers this issue, however there is no assertion validating the PC change in this test.

**Comment by aquynh** [comment]
this issue was already discussed at https://github.com/unicorn-engine/unicorn/pull/4

**Comment by gaffe23** [comment]
@hugoreinaldo Yep, I wrote that before we actually had a test suite. I'm about to submit a pull request to add assertions, just to make it clear that we'd like this to work at some point.

**Comment by farmdve** [comment]
@aquynh 

Have you found a way to change EIP from hooked code? I've been studying Unicorn and the QEMU internals(thank god they are mostly stripped), it's difficult, there is lots of code, but I am making progress.

I do have some ideas, but they are incomplete.

**Comment by aquynh** [comment]
yes, a rough idea is to quit the current basic block immediately, flush the JIT translation cache, then tell the engine to change the EIP, so next time JIT will start from the new place.

that is the approach, but i dont have time to work on the implementation yet. this is a bit tricky to code. if you can, just go ahead doing it.

**Comment by aquynh** [comment]
you guys should send in a testcase about changing PC from the callback. i can fix that if i have time.

**Comment by farmdve** [comment]
I am feeling in the mood to try and tackle this.

So, you said you had something in mind, what is it? What I have in mind is, after setting EIP to a new location, we set the exitreq_label to true and some other variable to indicate we are not exiting, but merely changing eip. Then when the hook exits, check_exit_request is immediately called and sees we are requesting exit. Then once it is done, we find a suitable place and flush the translation blocks. Then  when tb_find_fast is called it will start translating the new address.

**Comment by aquynh** [comment]
yes in general the way to go when PC is modified from inside a callback (using uc_reg_write()) is:

- signal to quit the current BB immediately
- upon exit, flush a page in the JIT cache where the new PC belongs to
- let the execution continue

this is not really hard to implement, and i think you can do it :-)

**Comment by farmdve** [comment]
@aquynh 

Experimentally, just for myself, I have. https://github.com/farmdve/unicorn/commit/bd2f11117b116ba25a3f439a60b257015437fe0a

**Comment by aquynh** [comment]
can you have a testcase for this new feature?

do you really want to flush all the cache? how about flushing only a related cache page (that contains the new PC)?

**Comment by aquynh** [comment]
this feature is now implemented for all architectures in the commit https://github.com/unicorn-engine/unicorn/commit/5a04bcb115052835c680a5466ef1cc475bfc2e4d.

check out `tests/unit/test_pc_change` to see how this works.

if you find any issues, please report.
