### ISSUE TITLE
absurdly large mem_map() aborts unicorn

### ISSUE THREAD

**Issue by lunixbochs** [unicorn-engine/unicorn#223]
from unicorn import *
    u = Uc(UC_ARCH_X86, UC_MODE_32)
    u.mem_map(0x60802000, 0x28bd211200004000)

**Comment by aquynh** [comment]
can you put this script under `tests/regress/`?

**Comment by lunixbochs** [comment]
I haven't been paying attention but it looks like regression tests are now some kind of managed test suite?

This isn't a very nice unit test and will break the regression suite from running (because it aborts Unicorn). Do you still want it in the same format?

**Comment by aquynh** [comment]
On Sat, Oct 31, 2015 at 1:42 PM, Ryan Hileman <notifications@github.com>
wrote:

> I haven't been paying attention but it looks like regression tests are now
> some kind of managed test suite?
>
> This isn't a very nice unit test and will break the regression suite from
> running (because it aborts Unicorn). Do you still want it in the same
> format?
>

do you mean one test fails will abort all the following tests?

**Comment by lunixbochs** [comment]
I didn't see how the regressions run, but yes it will crash the enclosing Python process.

**Comment by aquynh** [comment]
can you send a PR to put your script there? i will look at that.

**Comment by JonathonReinhart** [comment]
CMOCKA is supposed to handle that. It will catch e.g. SIGSEGV, abort the test and go on.

**Comment by lunixbochs** [comment]
Added a C regression test for this.

**Comment by aquynh** [comment]
fixed, thanks!
