### ISSUE TITLE
unicorn  emulate binary

### ISSUE THREAD

**Issue by Noiled** [unicorn-engine/unicorn#227]
I want to emulate run a   mach-o arm based binary， can unicorn do this？

**Comment by aquynh** [comment]
you need to write your own tool on top of Unicorn, which is just a framework, not a tool itself.

see https://github.com/lunixbochs/usercorn, which can do what you want.

**Comment by Noiled** [comment]
@aquynh usercorn use golang, and still not support mach-o well
can you point out some simple guideline or steps to do that
may be just a function fun(){ } and  a main() { fun();}  and output is mach-o format 
although I am a newer at emulator,  I think this is fantastic  and I am very interested，I want to do it myself, tks

**Comment by lunixbochs** [comment]
I'm aware of no simple tutorials on running foreign binaries directly, especially not Mach-O. qemu-darwin is long gone, so a Darling dev or me are probably your best bets.

**Comment by Noiled** [comment]
sounds fantastic, thank you very much for your sharing

**Comment by Noiled** [comment]
seems that https://github.com/espes/Slave-in-the-Magic-Mirror/blob/5a80c28824e804c6b526b65bbb84089f3b9d5391/loader.py does that

**Comment by lunixbochs** [comment]
espes would be better person to comment on this, but my understanding is that slave-in-the-magic-mirror only does a subset of the mach loading process and eschews invoking an actual dyld to perform manual relocations and implements all of the required dynamic symbols using high level emulation

That is to say, it's more of a manual process and not very generic. Do you have a specific program in mind you're trying to run?

**Comment by Noiled** [comment]
@lunixbochs  yes , the binary he emulates  is a binary extracted from apple TV.
Emulates a generic program is a great work,
I just want to learn this technology, for then I can emulates the others
