### ISSUE TITLE
single step hook

### ISSUE THREAD

**Issue by McLovi9** [unicorn-engine/unicorn#228]
Would it be possible to add some sort of single step hook ? I mean to pause execution on every instruction until the return from single step hook function. I'd use this hook in my dry debugger project.

**Comment by lunixbochs** [comment]
Something like this should make unicorn return from emu_start() after every instruction:

    u.hook_add(UC_HOOK_CODE, lambda *a: u.emu_stop())

Then your "single step" loop is just something like this:

    ip = entry
    while True:
        u.emu_start(ip)
        ip = u.reg_read(UC_X86_REG_RIP)

**Comment by aquynh** [comment]
the hook `UC_HOOK_CODE` gets your handler executed at every instruction, so that is a kind of "single-step" hook, no?

**Comment by McLovi9** [comment]
yes, thanks guys. I will do more tests during the weekend.

**Comment by LoveMHz** [comment]
Someone let me know if this should be submitted as a new issue with more detail.. 

I did encounter a issue where a jump was being incorrectly executed while using the method suggested by @lunixbochs Though it does appear to be working correctly while using the uc_hook_add UC_HOOK_CODE instead. Just wanted to comment on this behaviour incase anyone else comes along and thinks to do the same.

**Comment by aquynh** [comment]
@LoveMHz, can you post your code?

**Comment by s0ns0n** [comment]
I don't know if it's still relevant, but anyway:
uc.emu(eip, end, count=1)

**Comment by blacktop** [comment]
@s0ns0n so do you put that in a loop across the range of `range(start:end)` what effect does constantly starting the `uc` have to you have to update the register state on each run or does it keep track of it? @aquynh 

Thank you for any info.

**Comment by lunixbochs** [comment]
Unicorn remembers the state (including registers, mem maps, memory, and hidden state) between runs.

**Comment by blacktop** [comment]
@lunixbochs thank you! So I guess I am a little confused about the concept of `end` and `count`.  I guess `count` supersedes `end` and `uc` won't allow itself to step past `end`?

Is it that `count=1` will single step, but `uc` won't stop qemu until it has emulated to `end`?

**Comment by lunixbochs** [comment]
`end` is a memory address, `count` is a number of instructions.

**Comment by blacktop** [comment]
I understand that, what I was asking is if I have `uc.emu_start(start, end, count=1)` in a while loop what will happen when it reaches `end`?  

Also I suppose I would have to update start to point at the `eip` on each loop?

**Comment by blacktop** [comment]
I guess I can just test it to see what happens?

**Comment by lunixbochs** [comment]
You need to read EIP each time (if this is a bottleneck maybe we could add `uc_cpu_resume()` which infers EIP)

There's no point in using both end and count=1. Both end and count=1 will stop at the end EIP, but you won't know which one stopped it. So you'll need to read EIP and compare, which means end didn't matter.

In Usercorn, I set end=0xffffffffffffffff because I want to handle the end conditions myself.

**Comment by blacktop** [comment]
I agree that that would be 'less confusing' and most likely appreciated by your users. 👍
