### ISSUE TITLE
Go binding `.Close()` method

### ISSUE THREAD

**Issue by williballenthin** [unicorn-engine/unicorn#230]
Should the Go bindings expose a `.Close()` method on Unicorn instances? Seems that the Java and Python bindings do call `uc_close` when destroying instances, but I can't find any similar references in the Go bindings.

**Comment by lunixbochs** [comment]
I added it locally, but I'm getting assert crashes as if something already closed the handle. Currently debugging.

**Comment by williballenthin** [comment]
thanks!
