### ISSUE TITLE
Unexpected behavior calling `emu.Stop` from `HOOK_CODE`

### ISSUE THREAD

**Issue by williballenthin** [unicorn-engine/unicorn#232]
In a Go program, I'm encountering unexpected behavior when trying to implement "single-stepping" using `HOOK_CODE` callbacks that stop the emulator. An example program and the expected vs observed output is available [here](https://gist.github.com/williballenthin/e7b1ec10efd2de19c46a). I intend to port the sample to C to determine if the issue is limited to the Go bindings, and I'll update this issue when that is done. If this is *expected* behavior, please simply tell me and close the issue.

The [sample program](https://gist.github.com/williballenthin/e7b1ec10efd2de19c46a) has a `step` function that registers a `HOOK_CODE` callback that unconditionally stops the emulator. The function then runs the emulator, which should emulate a single instruction (at least thats my understanding, and suggested in #228). It then removes the hook.

When invoking the `step` function two times, exactly one instruction is *not* emulated per invocation. During the first `step`, the emulator does two instructions (callback hit twice, RIP changed by two instruction's worth). During the second `step`, its unclear to me what the emulator does. The callback is hit twice, with the addresses of two valid instructions, but RIP is not changed after the emulation.

I expected the callback to be hit once per `step` invocation, and that RIP would change by one instruction's worth. Is this a bug?

**Comment by lunixbochs** [comment]
The Go bindings are a pretty thin wrapper around the C bindings. They shouldn't change any major behavior.

**Comment by aquynh** [comment]
if you can rewrite your code in C or Python, i will look at that.

**Comment by williballenthin** [comment]
I've ported the sample code to Python and updated the gist [here](https://gist.github.com/williballenthin/e7b1ec10efd2de19c46a). Same behavior.

**Comment by aquynh** [comment]
yes this is a bug. can you send a PR to put this Python testcase under `tests/regress/`?

thanks

**Comment by williballenthin** [comment]
Sure, I will do that. 

-----Original Message-----

**Comment by aquynh** [comment]
here is something we should discuss: at address 0x1000, you decide to stop emulation. then after that, the PC is still 0x1000, right? it seems illogical to have PC at the next instruction, like what you are expecting.

(of course currently we have a bug preventing engine to stop immediately, but only do that at end of the basic block. i am testing the fix now)

**Comment by aquynh** [comment]
note that the hook handler is actually executed **before** the hooked instruction is executed, so i think it makes sense to have the PC unchanged after emulation returns.

anybody has different ideas?

**Comment by williballenthin** [comment]
Ah, I see. Seems I misunderstood when the `CODE_HOOK` callback would be invoked. In that case, I'd agree that if the emulator were to be stopped in the callback, PC shouldn't change, as no instructions would be emulated.

**Comment by williballenthin** [comment]
Given that the hook handler is executed before an instruction is emulated, seems that the following should do single stepping.

```
class SingleStepper:
    def __init__(self, emu):
        self._emu = emu
        self._hit_count = 0

    def _stop_hook(self, uc, address, *args, **kwargs):
        try:
            if self._hit_count == 0:
                self._hit_count += 1
            else:
                uc.emu_stop()
        except UcError as e:
            print("ERROR: %s" % e)

    def step(self):
        self._hit_count = 0
        try:
            h = self._emu.hook_add(UC_HOOK_CODE, self._stop_hook)
            try:
                ip = self._emu.reg_read(UC_X86_REG_RIP)
                self._emu.emu_start(ip, ip+0x20)
            finally:
                self._emu.hook_del(h)
        except UcError as e:
            print("ERROR: %s" % e)

s = SingleStepper(mu)
s.step()
s.step()
```

**Comment by williballenthin** [comment]
test case added in #240

**Comment by aquynh** [comment]
this should be fixed now, please confirm.

**Comment by williballenthin** [comment]
test case passes for me. looks great, thanks!
