### ISSUE TITLE
python bindings should use package-relative imports

### ISSUE THREAD

**Issue by williballenthin** [unicorn-engine/unicorn#235]
To support Python3 bindings, the Unicorn binding source files should use package-relative imports.

```
[willi@hostname python]$ python
Python 3.5.0 (default, Sep 20 2015, 11:28:25) 
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import unicorn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/unicorn/__init__.py", line 3, in <module>
    from unicorn_const import *
ImportError: No module named 'unicorn_const'
```

Essentially the fix is:

```
-from unicorn_const import *
+from .unicorn_const import *
```

This should also work on Python2, so no change to existing Python2 users' behavior.

I'll submit a PR to fix this issue, probably today. Opened this issue not to request support, but coordinate/share ideas.

**Comment by aquynh** [comment]
great, look forward to your PR. thanks
