### ISSUE TITLE
"qemu: qemu_thread_create: Resource temporarily unavailable" when creating the 2048:th unused Uc object

### ISSUE THREAD

**Issue by practicalswift** [unicorn-engine/unicorn#237]
The following code crashes when trying to create the 2048:th unused Uc object:

```python
#!/usr/bin/env python
import unicorn
for _ in xrange(2 ** 11):
    unicorn.Uc(unicorn.UC_ARCH_X86, unicorn.UC_MODE_64)
```

Output (OS X):

```
qemu: qemu_thread_create: Resource temporarily unavailable
Abort trap: 6
```

However, when using the created Uc objects by invoking the emu_start(…) method the code runs without problems:

```python
#!/usr/bin/env python
import unicorn
for _ in xrange(2 ** 11):
    uc = unicorn.Uc(unicorn.UC_ARCH_X86, unicorn.UC_MODE_64)
    uc.mem_map(0, 4096)
    uc.emu_start(0, 0)
```

**Comment by aquynh** [comment]
this is interesting. could you send a PR to put this testcase (and also the other testcase on memory leaking) under `tests/regress/`?

thanks.

**Comment by practicalswift** [comment]
The issue appears to be limited to OS X. Cannot reproduce under Linux.

**Comment by aquynh** [comment]
this is fixed with the latest commit, please confirm.

**Comment by practicalswift** [comment]
Confirmed! :-)

The code now throws UcError: Insufficient resource (UC_ERR_RESOURCE)

Thanks for fixing and thanks for an excellent project!
