### ISSUE TITLE
Error reporting lacks in detail

### ISSUE THREAD

**Issue by 0xItx** [unicorn-engine/unicorn#238]
`uc_errno` & `uc_strerror` do not always reveal the entire picture to the user. 

For example, getting the faulty address from a `UC_ERR_WRITE_UNMAPPED` requires sifting through the registers & disassembling the current instruction. 
This information is available in `env->invalid_addr`, but that's not exposed to the library's user as far as I can tell.

**Comment by lunixbochs** [comment]
If you make an invalid memory hook it will be called with the address and reason, and can tell Unicorn whether to continue emulation.

**Comment by 0xItx** [comment]
Thanks!
For future reference, all the hooks are defined in [uc_hook_type](https://github.com/unicorn-engine/unicorn/blob/22ae47a9d0d0fe9ff154632b85d2200c55ff6b5d/include/unicorn/unicorn.h#L168)
