### ISSUE TITLE
Executing a conditional branch that leads to "nowhere" crashes Unicorn.

### ISSUE THREAD

**Issue by farmdve** [unicorn-engine/unicorn#247]
I am talking about a conditional jump like JNZ or JZ that leads to memory that contains no other instruction, like \x75\x01. The problem seems to stem from this function in qemu/translate-all.c

    static void page_flush_tb_1(int level, void **lp)
    {
    int i;

    if (*lp == NULL) {
        return;
    }
    if (level == 0) {
        PageDesc *pd = *lp;

        for (i = 0; i < V_L2_SIZE; ++i) {
            pd[i].first_tb = NULL;
            invalidate_page_bitmap(pd + i);
        }
    } else {
        void **pp = *lp;

        for (i = 0; i < V_L2_SIZE; ++i) {
            page_flush_tb_1(level - 1, pp + i);
        }
    }
    }

More specifically `pd[i].first_tb = NULL;`, the `'i'`th element points to nothing. 

The behaviour I was expecting was that the jump would lead to a section of code that is either 00 and would get executed as `add byte ptr ds:[eax],al` or an error would be raised of type UC_ERR_FETCH_UNMAPPED or some sort.

**Comment by JonathonReinhart** [comment]
Can you provide a repeatable test case, please? Either a standalone test in `tests/regress/` or, if you think it makes sense, integrated into the x86 unit tests in `tests/unit/`.

**Comment by aquynh** [comment]
yes please send in a testcase so we can confirm and fix the bug.

**Comment by farmdve** [comment]
Seems like the bug is a bit more subtle and I had wrongfully attributed it to branching. The jump goes to code that (ideally should) contains zero bytes which are treated as `add byte ptr ds:[eax],al`, Unicorn basically cannot execute this instruction, so the issue isn't with branching, it's with the 0x00 x86 opcode.

**Comment by aquynh** [comment]
this should be fixed now, please confirm.

**Comment by farmdve** [comment]
Yup my 00opcode_uc_crash passes, no more crash.
