### ISSUE TITLE
R/W from SSE registers fails silently

### ISSUE THREAD

**Issue by Sin42** [unicorn-engine/unicorn#251]
Reading/writing from SSE registers is not implemented.

Trying to read/write fails silently

**Comment by aquynh** [comment]
yes this issue is known, and easy to fix: everything should be in https://github.com/unicorn-engine/unicorn/blob/master/qemu/target-i386/unicorn.c.

can you send a pull request for this issue? thanks.

**Comment by sinaelgl** [comment]
From what I saw (https://github.com/unicorn-engine/unicorn/blob/master/bindings/python/unicorn/unicorn.py#L203) , the Python bindings use ctypes which doesn't have 128 bit variables. Adding support might need changing other things too. I'll take a closer look when I have more time

**Comment by aquynh** [comment]
this is a good point. so how should we handle 128/256/512 bits variables (for SSE registers) for Python binding? is it good to also consider other languages, so all bindings deal with this issue in the same way?

**Comment by farmdve** [comment]
Perhaps as a structure.

**Comment by JonathonReinhart** [comment]
Python supports big integers natively. I don't know about Go, but .NET added `BigInteger` in 4.0.  So these registers can be presented in an easy way to consumers. It's just a matter of marshaling the (array of bytes, probably) to/from these bigints.

**Comment by lunixbochs** [comment]
I don't think it's as simple as converting to bignum. Vector registers can be used to store many smaller numbers, which is kinda the point. I think they should just be represented as bytes.

    // *out needs to be a buffer of at least 64 bytes to store the largest known register size (512 bits)
    int uc_reg_big_read(uc_handle *handle, int enum, uint8_t *out, uint32_t *size) {
        memcpy(out, cpu->xmm0, sizeof(cpu->xmm0));
        *size = sizeof(cpu->xmm0);
        return 0;
    }

    int main() {
        uint8_t buf[64];
        uint32_t size;
        uc_reg_big_read(handle, X86_REG_XMM0, buf, &size);
        uc_reg_big_write(handle, X86_REG_XMM0, buf);
    }

**Comment by JonathonReinhart** [comment]
@lunixbochs Good point. I didn't really think that through, apparently. Considering how many different formats of vector registers there may be (across architectures), I think you're right about just using an array of bytes.

**Comment by JayFoxRox** [comment]
Partially fixed in #607 ?

(I think this should return data in bytes, 2 uint64_t or 4 uint32_t. It currently seems to use 2 float64 internally)
