### ISSUE TITLE
How does Unicorn see our code as? Userland/Kernel/None?

### ISSUE THREAD

**Issue by farmdve** [unicorn-engine/unicorn#252]
The reason is because I want to use it to emulate x86 code in Windows and get 1:1 behaviour, but there are a few things that prevent this.

One thing is that Windows has what is known as Structured Exception Handling and Vectored Exception Handling. Basically when anything happens that isn't allowed, division by zero or execution of privileged instructions(like hlt or mov dr0, eax) an exception handler at the top of the seh frame is executed, if it doesn't handle this exception, the other one is called and so forth. 

This however does require us to be able to change EIP from within hooked code.

Also, the EFLAGS behaviour is different under Unicorn than an OS, https://ideone.com/WQAvk1

When attempting to set all flags(except trap flag) we should get a value of eflags that is 0x00244ED7, in Unicorn it's just 0x00000ED7. However, if the trap flag is also set, in Windows, an exception is generated, and if there is an Exception Handler installed, it will be called.

**Comment by aquynh** [comment]
it is ring0, but actually this does not really matter as you have to emulate everything.

in the case you are asking, SEH can be handled by your callback handler: whenever something that you are interested happen (such as div by zero), your handler will get executed and emulate whatever you want.

for the problem with EFLAGS, can you provide a testcase exposing the issue?

**Comment by farmdve** [comment]
For eflags, I've made a pull request on the test case.

As for the SEH handler, it cannot, sadly. The handler will also need to run in Unicorn, not as callback, but as emulated instructions. E.g env->eip needs to be set to the handler.

**Comment by aquynh** [comment]
i think this problem can be solved simply by allowing to change EIP inside the callback?

@cseagle, do you also have to deal with this issue in your IDA plugin?

**Comment by farmdve** [comment]
it should. There is a more...difficult way, restarting Unicorn, copying over the old memory to the new instance, and changing EIP to the handler, executing handler.

However we also need to be able to hook more privileged/illegal instructions. I personally want to hook CPUID,RDTSC,UD2, and when my callback is called, being able to set EIP to some handler.

**Comment by aquynh** [comment]
to hook CPUID & RDTSC, you can do that now: just hook every instruction, then use disassembler (such as Capstone) to check for the instruction ID, then act accordingly.

i still need to check UD2, as i am not quite sure how Unicorn deals with it now.

**Comment by farmdve** [comment]
Wouldn't hooking all instructions be kind of slow?

Right now unicorn deals with UD2 by exiting Unicorn


if (uc->stop_interrupt && uc->stop_interrupt(cpu->exception_index)) {
    cpu->halted = 1;
    uc->invalid_error = UC_ERR_INSN_INVALID;
    ret = EXCP_HLT;
    break;
}

cpu->exception_index is 6 which is EXCP06_ILLOP and  uc->stop_interrupt handles it specifically.

**Comment by aquynh** [comment]
Unicorn handles some instructions specially by inserting callback directly in JIT phase. examples are: IN, OUT, SYSCALL, INT. see qemu/target-i386/translate.c to see how it works. we can think about doing the same thing with other instructions if there is good reason to do so.

otherwise you have to accept that it is slower by hooking with UC_HOOK_CODE.

can you please send a testcase for this UD2 instruction, so it is easy to track & confirm the fix?

thanks.
