### ISSUE TITLE
file mmap() support

### ISSUE THREAD

**Issue by lunixbochs** [unicorn-engine/unicorn#261]
I'd like to be able to directly mmap() files into target memory. I think this is facilitated in qemu-user by doing a "guest-to-host" address translation and just calling mmap() directly. Do host memory addresses backing guest memory ever change position? Something to guarantee a guest address range is backed by a fixed contiguous host memory region would be sufficient for this.

Maybe an API like `guest_fixed_map(host_addr, guest_addr, size)` would work, which points a region of guest memory at an existing region of host memory. This way it's not tied to anything overly platform specific like mmap() APIs.

**Comment by JonathonReinhart** [comment]
I think this is huge. The vast majority of data copied into guest memory is probably coming from a file anyway.

**Comment by aquynh** [comment]
yes this will be nice to have. Qemu has something called memory-backend-file, so you might want to look at that to see if we can use it for this API.

**Comment by lunixbochs** [comment]
qemu-user seems to think calling mmap directly is fine: https://github.com/hackndev/qemu/blob/master/darwin-user/mmap.c#L225

I just think a portable version of file mapping doesn't really need to be Unicorn's job. All I really want is the ability to make a fixed mapping from guest to host memory so I can do whatever I want with it.

**Comment by aquynh** [comment]
yes, feel free to propose new API and implement it.

**Comment by lunixbochs** [comment]
Proposed API usage (as implemented in the pull request):

    uc_mem_map_ptr(handle, addr, size, void *ptr);

Permissions are not specified because Unicorn does not control them.

**Comment by aquynh** [comment]
this is already solved with the new API `uc_mem_map_ptr()`, so closed. thanks
