### ISSUE TITLE
Unexpected behavior calling emu_start within basic blocks

### ISSUE THREAD

**Issue by williballenthin** [unicorn-engine/unicorn#263]
I'm seeing some unexpected behavior when running `emu_start` within basic blocks. I'm not sure what the root issue is, so I'll submit tests that seem to show incorrect behavior.

See #262. In this test, I try to emulate from the middle of one BB to the start of the next. The emulator raises an invalid fetch exception. This is not the weird behavior that prompted me to investigate, but let's start with this.

If you haven't guessed from my submitted issues, I'm learning unicorn by writing a little debugger-like toy that should let the user single step, step over, run to, etc.  So, I'd like to be able to instruct unicorn to run to specific addresses, emulate *N* instructions, etc. regardless of their location within a BB.

**Comment by farmdve** [comment]
Excuse me if I am wrong, but you are setting ESP to point to 0x2800 which is outside the 0x1000 bytes you requested to map, thus it's outside of the memory requested.

**Comment by farmdve** [comment]
At first I thought the issue was the stack, but I see you map it, I tested your code in my program and it works for me.

mov eax,0
inc eax
inc eax
mov edx,F1F1F1DA
push 1000015
ret
int3
int3
int3
mov eax,500
inc eax
inc eax

EAX: 0x00000502, EDX: 0xF1F1F1DA

**Comment by farmdve** [comment]
It's failing in tb_gen_code
```c
    if (tb->size) {
        target_ulong virt_page2 = (pc + tb->size - 1) & TARGET_PAGE_MASK;
        if ((pc & TARGET_PAGE_MASK) != virt_page2) {
            phys_page2 = get_page_addr_code(env, virt_page2);
        }
    }
```
In my case `tb->size` is `36045(0x8CCD)`, pc is 4113(0x1011) this should be where the ret instruction is.
`pc + tb->size - 1` == `40157 & TARGET_PAGE_MASK` which is  `0xfffff000` produces 36864 which is 0x9000, the code then tries to find whatever is at this address in the MMU, but it fails, because it's not mapped.

**Comment by williballenthin** [comment]
@farmdve thanks for taking an initial stab at this. 

I'm not yet familiar with the unicorn internals, so I can't promise to be effective soon. But, do you have any hints into how you ID'd this, and your debugging setup? Did you port the program to C and use gdb? Any tips or tricks would be appreciated so maybe one day I can contribute patches, rather than just report issues.

**Comment by farmdve** [comment]
Yes, I primarily use C. I compiled Unicorn with -g and -ggdb3 to produce symbols(note, they are large around 40-50 megabytes for each compiled object).

Then I used gdb and step through interesting functions and you get side-by-side execution showing the source code.

**Comment by farmdve** [comment]
I think I found the bug and believe I have fixed it.

**Comment by farmdve** [comment]
I haven't yet made a pull request, but you can go ahead and clone my fix_bugs1 branch OR apply the patch by hand, just add pc_ptr = pc_start before the goto done_generating; line and recompile.

**Comment by aquynh** [comment]
yes, but a better fix is to move the line

    pc_ptr = pc_start;

to front, so there is no need to initialize it later in the main code path.

thanks.

**Comment by aquynh** [comment]
and please use 4 spaces for indentation, rather than tabs.

**Comment by williballenthin** [comment]
i've also confirmed this patch fixes the bad instruction fetch. thanks!

**Comment by williballenthin** [comment]
With the bad instruction fetch fix, the test case still does not pass. When asking the emulator to begin executing the second block at 0x1010, it seems no instructions are executed. The code hook does not display any traced instructions, and EIP does not change to 0x1016 as expected.

@farmdve: while I appreciate the rapid triage and fix above, I certainly don't expect such great support 24/7! I immediately updated the issue here with the test failure simply as a status update.

If the test remains failing during my next code hacking session (perhaps Saturday afternoon), I'll try @farmdve's debugging setup described above and see what I can determine.

**Comment by aquynh** [comment]
i pull the fix of @farmdve , and fixed the remaining issue. please confirm, thanks.

**Comment by farmdve** [comment]
Doesn't seem to be. With my fix(I don't see it in your commit log), my own test case passes, but executing from ret to mov does not. Still getting UC_ERR_FETCH_UNMAPPED.

Looking at the code, the reason is because the eip is set to 0 in the translated code, and later calls to get_page_addr_code are called with addr=0.

**Comment by aquynh** [comment]
are you sure you pulled the latest code?

your commit is at https://github.com/unicorn-engine/unicorn/commit/661714d0c20dd36a4acee85b053b4a6bb2e6afb1

**Comment by farmdve** [comment]
I have the fix, but it's not in your commit log. I have not made any pull requests, I commited to my own repositories, but I had to reorg my branches so I didn't issue a pull request.

**Comment by aquynh** [comment]
the reason of the bug is that in the first emulation, the JIT code was incomplete as we stopped when we reached the "until" address, thus the related block is empty. i fixed that by flushing the JIT cache after every emulation.

**Comment by aquynh** [comment]
here is the output of this testcase now:

```
$ ./tests/regress/run_across_bb.py 

---- test: run_across_bb ----
pc: 0x1000
>>> Tracing instruction at 0x1000, instruction size = 5
>>> Tracing instruction at 0x1005, instruction size = 1
>>> Tracing instruction at 0x1006, instruction size = 1
>>> Tracing instruction at 0x1007, instruction size = 5
pc: 0x100c
>>> Tracing instruction at 0x100c, instruction size = 1
pc: 0x1010
>>> Tracing instruction at 0x1010, instruction size = 5
>>> Tracing instruction at 0x1015, instruction size = 1
pc: 0x1016
.
---- test: run_all ----
pc: 0x1000
>>> Tracing instruction at 0x1000, instruction size = 5
>>> Tracing instruction at 0x1005, instruction size = 1
>>> Tracing instruction at 0x1006, instruction size = 1
>>> Tracing instruction at 0x1007, instruction size = 5
>>> Tracing instruction at 0x100c, instruction size = 1
>>> Tracing instruction at 0x1010, instruction size = 5
>>> Tracing instruction at 0x1015, instruction size = 1
pc: 0x1016
.
----------------------------------------------------------------------
Ran 2 tests in 0.006s

OK
```

**Comment by farmdve** [comment]
Yes it appears my test case was erred after I modified it. I can confirm the issue no longer occurs.

**Comment by williballenthin** [comment]
fixed here, too. thanks!
