### ISSUE TITLE
Invalid write of size 4 in cpu_tb_exec_x86_64

### ISSUE THREAD

**Issue by practicalswift** [unicorn-engine/unicorn#269]
Offending code:

```#define BINARY "\xc4\xe2\xdb\xf6\xe2"```

Segfault:

```segfault at 480 ip 00007ffadbff5a8d sp 00007ffad88498c0 error 6 in libunicorn.so.0[7ffadbff5000+1000]```

valgrind:

```
==4198== Invalid write of size 4
==4198==    at 0x59B2A8B: ??? (in /usr/lib/libunicorn.so.0)
==4198==    by 0x1D1E18FF: ???
==4198==    by 0xDFFFFFFFF: ???
==4198==    by 0xE8FFFFFFFF: ???
==4198==    by 0x1A7F30EF: ???
==4198==    by 0x59B2AAA: ??? (in /usr/lib/libunicorn.so.0)
==4198==    by 0x7F2174681A3FEAFF: ???
==4198==    by 0x1D1E192F: ???
==4198==    by 0x4EB7D73: tcg_out_opc (tcg-target.c:450)
==4198==    by 0x1D1E192F: ???
==4198==  Address 0x480 is not stack'd, malloc'd or (recently) free'd
```

**Comment by farmdve** [comment]
I looked into this issue as well.

It's again a problem with the jitted code. 

mov rax,qword ptr ds:[r14+10] // moves the value of RDX to rax
mul rax // multiplies
mov dword ptr ds:[rax+280],eax // uh oh, it tries to store to rax+280, thats definitely not right.
mov dword ptr ds:[rsi+80],test64.1000005 // update pc counter I believe.

**Comment by aquynh** [comment]
then you should compare the output of "mulx rsp,rsp,rdx" and "mulx rsp,rax,rdx" to see the difference, then to find out the issue.

**Comment by aquynh** [comment]
How did you test this code with Qemu? Can you post your test here?

**Comment by farmdve** [comment]
I did not. Somebody else did and said it crashed for him on original qemu. I reported this to qemu, they wrote this test case https://gist.github.com/XanClic/b8d87473e5f324312a94 and it doesn't crash for them, however they have found that the order of updating is not correct. So while it doesn't crash for them, there is a bug still.

So I got even further on the segfault. In tcg_reg_alloc_op there is the following code.
```c
        if (NEED_SYNC_ARG(i)) {
            tcg_reg_sync(s, reg);
        }
```

It updates the registers, but remember, they are wrong. 

And what is `NEED_SYNC_ARGS`?
```c
#define NEED_SYNC_ARG(n) ((sync_args >> (n)) & 1)
```

This means the problem must stem from tcg_liveness_analysis.

**Comment by farmdve** [comment]
Please test the patch I provided. It works for me on @practicalswift's test case.

**Comment by aquynh** [comment]
can you send a pull request, so we can discuss on it?

**Comment by aquynh** [comment]
this is fixed now, please confirm.

big thanks go to @farmdve for doing most of the hard work on this issue!

**Comment by farmdve** [comment]
You are mistaken, I didn't do anything. I was as baffled as anyone, I started digging into the source code, saw the fix for the constant.

After bringing up the issue with qemu devs, they whipped up a fix http://lists.nongnu.org/archive/html/qemu-devel/2015-11/msg03848.html

But really, it was @practicalswift who first discovered it, if anything, he deserves the credit.

**Comment by aquynh** [comment]
@farmdve, yes i know that, but the point is that without your report to Qemu and backport to Unicorn, we are still struggling with this bug.

regarding this issue, i am also wondering how @practicalswift got this bug (and also the other bug on self-modifying code)

**Comment by farmdve** [comment]
Yep his test cases are very unusual, but interesting. I am curious if he can share his method.

**Comment by practicalswift** [comment]
@aquynh Confirming fix - the test case is no longer crashing.

Thanks again for really impressive turnaround times!

**Comment by farmdve** [comment]
It was thanks to your test cases.

We look forward to more of these :+1:

**Comment by aquynh** [comment]
yes fixing segfault is the first priority. thanks for working hard on your fuzzer :-)

**Comment by egberts** [comment]
Self modifying code?

i first saw that bug but reported much earlier, similar liveliness issue.
