### ISSUE TITLE
Unicorn should provide more details on error

### ISSUE THREAD

**Issue by JCYang** [unicorn-engine/unicorn#274]
For example, IP/PC value on error, and all other major registers? and maybe some memory range point by SP?
I just emulated some codes but a simple UC_ERR_INSN_INVALID help me nothing to location the bug or maybe fix it...
Is it a big project required non-trivial change or a simple one?

**Comment by farmdve** [comment]
You can print it in your callback.

void hook_ins(uc_engine *uc, uint64_t *address*, uint32_t size, void *user_data)

**Comment by JCYang** [comment]
well, I think you miss my point.
I mean, for any possible and unknown invalid instruction, how can I hook?
I don't know which instruction, and I've read the hook type supported now, no invalid_instruct hook type.

**Comment by aquynh** [comment]
at the moment `UC_ERR_INSN_INVALID` event only happens when the emulator hits invalid instruction, then the  emulator stop. you can get the address by retrieving the PC (EIP/RIP on X86).

i am not sure if we really need a callback for this event: what you are going to do with the handler (callback) when this happens?

**Comment by farmdve** [comment]
The only instruction that is both valid and invalid(per design) is UD2. It's the only valid instruction which Unicorn checks for and quits if it sees it.

**Comment by aquynh** [comment]
On Nov 27, 2015 4:28 AM, "farmdve" <notifications@github.com> wrote:
>
> The only instruction that is both valid and invalid(per design) is UD2.
It's the only valid instruction which Unicorn checks for and quits if it
sees it.

How do you want to fix this problem?

**Comment by JCYang** [comment]
Well, I didn't know when the emulator quits with such exception can the vm status still be queried. Thank you. I know how to locate the problem codes now.

**Comment by JCYang** [comment]
In realworld, invalid instructions will cause the program(user mode)/kernel crash, don't think we need a callback for this scenario, there must be something wrong in the codes being emulated. Not even the most evil pack codes will crash themselves, won't they?

**Comment by cseagle** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

An illegal instruction executed in user space results in the O/S
generating an illegal instruction exception/SIGILL.

Yes, some packers intentionally try to execute illegal instructions
after setting up the appropriate signal handlers.

On 11/26/2015 5:13 PM, JCYang wrote:
> In realworld, invalid instructions will cause the program(user 
> mode)/kernel crash, don't think we need a callback for this
> scenario, there must be something wrong in the codes being
> emulated. Not even the most evil pack codes will crash themselves,
> won't they?
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/unicorn-engine/unicorn/issues/274#issuecomment-160
013696>.
>
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (MingW32)

iEYEARECAAYFAlZXslMACgkQ9zL2pkgLDWmVagCghYD7Qu+c3JdcJucRuOJVJsa3
V2oAnjAJeL5wlXrdXSqSVAIS01OGsfwL
=XZ1S
-----END PGP SIGNATURE-----

**Comment by JCYang** [comment]
Didn't know this before, Thank you for the interesting knowledge, cseagle.

**Comment by aquynh** [comment]
in the case of UD2, the emulator will stop, then we can check for it by looking into the instruction at the PC address (using `uc_mem_read()` to read memory). after that we can decide what to do next, such as restarting emulation at another address.

**Comment by flex-lm** [comment]
JCYang: Unexpected input should never crash or cause unexpected behavior of program. Otherwise, the software should not be considered as secure or reliable.

**Comment by lunixbochs** [comment]
I vote to close - it's up to the user to print debug information relevant to their program. In Usercorn, I print a stacktrace and register dump myself if `emu_start()` returns with an error.

Unicorn is currently doing its job in still allowing you to read registers and memory after an error.
