### ISSUE TITLE
make.sh nix32 option not available

### ISSUE THREAD

**Issue by frederic** [unicorn-engine/unicorn#275]
File COMPILE.TXT mentions the option "nix32" "to cross-compile Unicorn on 64-bit OS to target 32-bit binary".
However, this option is not supported:

$ ./make.sh nix32
Usage: ./make.sh [|default|install|uninstall|cross-win32|cross-win64|cross-android|clang|gcc|ios|ios_armv7|ios_armv7s|ios_arm64|]

**Comment by aquynh** [comment]
can you fix this? i think this can be adapted from the same script from Capstone: https://github.com/aquynh/capstone/blob/next/make.sh#L133

**Comment by idl3r** [comment]
Not as simple as -m32 thanks to the qemu and static test programs.

Following env works on my Ubuntu 14.04 x64 (with all i386 libs installed):
export PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig
export CFLAGS=-m32
export LDFLAGS=-m32
export LDFLAGS_STATIC=-m32
export LIBRARY_PATH="/usr/lib/i386-linux-gnu"
export UNICORN_QEMU_FLAGS="--cpu=i386"

**Comment by aquynh** [comment]
fixed this by adding a new option **linux32**, by @idl3r. so you now can simply do this to cross-compile to Linux 32bit:

    $ ./make.sh linux32

the only dependency is the package **libglib2.0-dev** for i386, which is **libglib2.0-dev:i386** on Ubuntu.

get the latest Github code, and report if you still have issues, thanks.
