### ISSUE TITLE
Provide MIPS/universal way to access program counter

### ISSUE THREAD

**Issue by michalmalik** [unicorn-engine/unicorn#276]
Hello,

could you provide a way to access the program counter register on MIPS? I wouldn't be asking for this if MIPS actually had an accessible PC (IP) register like x86 does for example.

I don't think it's very important, but there could be a universal API for all architectures for this. Something like:

```
emu.get_pc()
```

Or is there a way to do this that I am not aware of?

Thank you

**Comment by farmdve** [comment]
Honestly, this is not a bad idea at all.

**Comment by lunixbochs** [comment]
from Python, `emu.reg_read(MIPS_REG_PC)`

I think this just clutters the API. You'll already need arch-specific code if you want to do anything complex.

**Comment by michalmalik** [comment]
@lunixbochs  Wow, I must be getting blind.. I completely missed that constant. Sorry for the unnecessary issue and thank you!
