### ISSUE TITLE
[mips32] code hook not executed for delay slot instructions

### ISSUE THREAD

**Issue by xorstream** [unicorn-engine/unicorn#290]
When using a code hook with mips it is not calling the hook for instructions in a delay slot.

The instructions in a delay slot do get executed by the emulator, as I can see their effect on values in registers. Just the hook doesn't get called for them.

My test instructions are:

	unsigned char loop_test_code[] = {
		0xFF,0x00,0x04,0x24,	// li      $a0, 0xF
		// loop1
		0xC0,0x10,0x04,0x00,	// sll     $v0, $a0, 3
		0x00,0x00,0x44,0xAC,	// sw      $a0, 0($v0)
		0xFD,0xFF,0x80,0x14,	// bnez    $a0, loop1
		0xFF,0xFF,0x84,0x24,	// addiu   $a0, -1
	};

I have previously set an instruction hook by doing:

	// hook all instructions by having @begin > @end
	uc_hook hhc;
	uc_hook_add(uc, &hhc, UC_HOOK_CODE, mips_codehook, NULL, (uint64_t)1, (uint64_t)0);

The hook gets called for every instruction except "addiu   $a0, -1"

**Comment by aquynh** [comment]
could you please send in a pull request on this issue to put a test under either tests/regress/ or tests/unit/? it makes it easier to confirm the problem & test the fix this way.

thanks.

**Comment by lunixbochs** [comment]
Huh, in #133 it was calling the hook twice.

**Comment by aquynh** [comment]
@xorstream, do you still see your problem with the latest Unicorn (from Github)?

**Comment by xorstream** [comment]
I was using the v0.9 stable build not the latest build from git. So perhaps things have changed. I am reading up on how to use git/github atm. I will download the latest version later today and test it. If the issue still exists i'll create test code for it and submit a pull request.

**Comment by aquynh** [comment]
yes, the latest code on Github fixes quite a lot of issues since v0.9.

just in case, you can always get the latest code directly from this link: https://github.com/unicorn-engine/unicorn/archive/master.zip

**Comment by xorstream** [comment]
Ok I can confirm that the issue still exists with latest code from github. I'll make up a test for it.

Btw is it standard to build the source inside your local repo clone?
When I did so it detected a change to "qemu\config-all-disas.mak"
It looks like perhaps that needs to be added to .gitignore after the "qemu/config-all-devices.mak" entry.

**Comment by aquynh** [comment]
it is recommended to build & install Unicorn like this (on Mac, Linux)

    $ ./make.sh
    $ sudo ./make.sh install

i dont see `config-all-disas.mak` modified with "git status" on my Mac

**Comment by xorstream** [comment]
I installed GitHub Desktop for windows.
That is what is saying that "config-all-disas.mak" has been altered.
Funnily enough it is saying that the file is empty when I can see it clearly is not when I open it in a text editor?!

As for building, I am using MinGW-w64 with msys2.
I did ./make.sh cross-win32
Which worked fine, although "./make.sh install" doesn't work. No biggie though.

**Comment by xorstream** [comment]
Test code submitted in pull request

**Comment by xorstream** [comment]
@aquynh it seems that your fix for #133 is what causes it to skip the callback for the branch delay slot.
Specifically if I revert "unicorn\qemu\target-mips\translate.c" line 18526 from:
if (!is_bc_slot && env->uc->hook_insn) {
  to
if (env->uc->hook_insn) {

It appears to fix the issue.
Perhaps you had some reason for this check though?
If this is the correct change then the other changes for decode_mips16_opc() and decode_micromips_opc() will also need reverting.
