### ISSUE TITLE
Read from large addresses behaves will create multiple read events

### ISSUE THREAD

**Issue by ranmrdrakono** [unicorn-engine/unicorn#300]
when executing `mov rax, [rax]` multiple read events are triggered if rax is a big number not ending in 0. I'm not sure if this is some really weird x86_64 behavior or a bug.
A Testcase was added in PR #298.

**Comment by Nukem9** [comment]
Are you sure this isn't because of QEMU emulating real CPU behavior? IIRC unaligned addresses are always split reads.

**Comment by ranmrdrakono** [comment]
Not for small addresses (when reading from 90000001 we only get one read event). However it is quite possible that this is just some weird cornercase of x86, I honestly don't know.

**Comment by ranmrdrakono** [comment]
I looked more into it, and it appears that the read will be split in 3 memory reads (the correct/expected unaligned read, and two reads such that the region is covered by aligned reads) if the upper bound of the read exceeds `0x0010000000000000`. That means the smallest value which triggers this behavior on a 8 byte read is   `0x000ffffffffffff9`.

**Comment by JonathonReinhart** [comment]
Those addresses aren't in the "canonical form" as required by x86-64 processors. I believe those reads would trigger an exception on a real CPU.

**Comment by ranmrdrakono** [comment]
Oh good point (Today I learned). However this doesn't seem to be the reason since addresses like 0xfffff00000000009 are 'canonical form' but don't work, while 0x000ffffffffffff5 is not canonical but works as expected.

**Comment by ranmrdrakono** [comment]
Also, it appears a single 8 byte write fires eight 1-byte events if the address of the highest written byte exceeds  0x0010000000001000 (note the additional 1 that was not necessary for reads).

**Comment by ranmrdrakono** [comment]
Additionally It appears that the read will always return 0 instead of the correct value.

**Comment by ranmrdrakono** [comment]
I debuged a bit, and it appears that  https://github.com/unicorn-engine/unicorn/blob/master/qemu/softmmu_template.h#L279-L282 this check fails. I believe the implication is that unicorn considers addresses above 0x0010000000000000 to be IO mapped. Anyone with more qemu experience able to say something about this?

**Comment by aquynh** [comment]
no this "high" address cannot be considered IO mapped. have no time to look closely at this, but perhaps you get this (unrelated) code path because some address involved is unmapped.

**Comment by farmdve** [comment]
As far as the value returned being 0, the reason is because the read hook is called before the value is obtained. I will experiment to see if the hook can be called when the value IS obtained.

And the code responsible for the 8 1 byte write events is this one

```c
    /* Handle slow unaligned access (it spans two pages or IO).  */
    if (DATA_SIZE > 1
        && unlikely((addr & ~TARGET_PAGE_MASK) + DATA_SIZE - 1
                     >= TARGET_PAGE_SIZE)) {
        int i;
    do_unaligned_access:
#ifdef ALIGNED_ONLY
        cpu_unaligned_access(ENV_GET_CPU(env), addr, MMU_DATA_STORE,
                             mmu_idx, retaddr);
        env->invalid_addr = addr;
        env->invalid_error = UC_ERR_WRITE_UNALIGNED;
        cpu_exit(uc->current_cpu);
        return;
#endif
        /* XXX: not efficient, but simple */
        /* Note: relies on the fact that tlb_fill() does not remove the
         * previous page from the TLB cache.  */
        for (i = DATA_SIZE - 1; i >= 0; i--) {
            /* Little-endian extract.  */
            uint8_t val8 = val >> (i * 8);
            /* Note the adjustment at the beginning of the function.
               Undo that for the recursion.  */
            glue(helper_ret_stb, MMUSUFFIX)(env, addr + i, val8,
                                            mmu_idx, retaddr + GETPC_ADJ);
            if (env->invalid_error != UC_ERR_OK)
                break;
        }
        return;
    }
```

**Comment by aquynh** [comment]
can you send a pull request to fix this?

**Comment by aquynh** [comment]
@ranmrdrakono, this issue (thus all the problems in `test_mem_high`) is fixed now, please confirm.

**Comment by ranmrdrakono** [comment]
Confirmed.
