### ISSUE TITLE
Hooking read/write events doesn't work sometimes?

### ISSUE THREAD

**Issue by univm** [unicorn-engine/unicorn#303]
It seems like if the memory being read/write to is in the stack, the hooks aren't called.

**Comment by lunixbochs** [comment]
You mean instructions like push/pop? There's usually no "stack memory" as far as the cpu is concerned, just a current stack pointer.

**Comment by aquynh** [comment]
if you find any issues, it is best to provide a sample code/script so we can reproduce it.

thanks

**Comment by univm** [comment]
@lunixbochs

No, instructions like 
```asm
mov eax, dword ptr ss:[ebp - 0xc]
```
or
```asm
mov dword ptr ss:[ebp - 0x14], eax
```

Do not get logged. I'll try and provide a test case.

**Comment by aquynh** [comment]
please provide a testcase.
