### ISSUE TITLE
Another issue with EFLAGS.

### ISSUE THREAD

**Issue by farmdve** [unicorn-engine/unicorn#313]
So I was executing code in Unicorn and noticed that the EFLAGS I get from uc_reg_read was inconsistent with real execution,furthermore if I were to single-step in Unicorn e.g with max_count = 1; the internal eflags did not properly sync and it affected branches and it didn't execute properly. So I started digging in and I was wondering if the following code is wrong in cpu.h

``` c
static inline uint32_t cpu_compute_eflags(CPUX86State *env)
{
    return env->eflags0 | cpu_cc_compute_all(env, CC_OP) | (env->df & DF_MASK);
}
```

Here we are using `env->eflags0`, but I think this must be `env->eflags`. In fact, after I changed it to `env->eflags`, `uc_reg_read` was returning correct results and my single-step was no longer executing wrong branches. E.g

``` c
static inline uint32_t cpu_compute_eflags(CPUX86State *env)
{
    return env->eflags | cpu_cc_compute_all(env, CC_OP) | (env->df & DF_MASK);
}
```

Cause in `x86_cpu_exec_exit` we have a redundant `env->eflags0 = env->eflags;` when  `cpu_compute_eflags` returns  `env->eflags0` which made me think that it was a simple typo.

``` c
void x86_cpu_exec_exit(CPUState *cs)
{
    X86CPU *cpu = X86_CPU(cs->uc, cs);
    CPUX86State *env = &cpu->env;

    env->eflags = cpu_compute_eflags(env);
    env->eflags0 = env->eflags;
}
```

Re-examining my old eflags_nosync test, it fails with my change, though. With my change ZF is set somehow, without it ZF is not set(which is the correct behaviour for that test).
So I further do this

``` c
static inline uint32_t cpu_compute_eflags(CPUX86State *env)
{
    env->eflags &= ~(CC_O | CC_S | CC_Z | CC_A | CC_P | CC_C | DF_MASK);
    return (env->eflags | cpu_cc_compute_all(env, CC_OP) | (env->df & DF_MASK)) & (~IOPL_MASK);
}
```

This eliminates the problem. Well, the other problem is that in Windows(ring3) the default value for EFLAGS is 0x202, if I use that eflags value, my eflags_nosync test does not fail.

Furthermore, the IOPL bits in eflags(bits 12-13) are set. In my own copy of Unicorn I clear them. However I know that people will use Unicorn to emulate firmware, and other non-OS specific code, so how do we unset these flags internally without manual patch?
Perhaps we should make an options API where we set various options that further allow us to fine-tune the execution.

**Comment by aquynh** [comment]
the reason we use `eflags0` is because the way JIT works in Qemu: the EFLAGS is only updated at the end of basic block to improve performance.

can you provide a testcase on what is wrong?

to setup IOPL bits, you can do that by writing to the EFLAGS with the value you want?

**Comment by farmdve** [comment]
After changing 

```c
static inline uint32_t cpu_compute_eflags(CPUX86State *env)
{
    env->eflags &= ~(CC_O | CC_S | CC_Z | CC_A | CC_P | CC_C | DF_MASK);
    return (env->eflags | cpu_cc_compute_all(env, CC_OP) | (env->df & DF_MASK)) & (~IOPL_MASK);
}
```

to

```c
static inline uint32_t cpu_compute_eflags(CPUX86State *env)
{
    env->eflags0 &= ~(CC_O | CC_S | CC_Z | CC_A | CC_P | CC_C | DF_MASK);
    return (env->eflags0 | cpu_cc_compute_all(env, CC_OP) | (env->df & DF_MASK)) & (~IOPL_MASK);
}
```

The issue is not present. But we need to unset some of the bits. If we are recomputing eflags, some of the flags are not unset.

**Comment by zardus** [comment]
Hello,

I'm current working on unicorn integration in angr, and I was also seeing divergent paths (as in, unicorn would go off in a different direction than the equivalent VEX-emulated path). Clearing those flags, as farmdve suggested, delayed the divergence until much later.

I'm still looking into why it ends up diverging in the end, but for now, here's my diff in case it's helpful:

```diff
diff --git a/qemu/target-i386/cpu.h b/qemu/target-i386/cpu.h
index 4628a8d..8cc951f 100644
--- a/qemu/target-i386/cpu.h
+++ b/qemu/target-i386/cpu.h
@@ -1315,7 +1315,7 @@ void update_fp_status(CPUX86State *env);
 
 static inline uint32_t cpu_compute_eflags(CPUX86State *env)
 {
-    return env->eflags0 | cpu_cc_compute_all(env, CC_OP) | (env->df & DF_MASK);
+    return (env->eflags0 & ~(CC_O | CC_S | CC_Z | CC_A | CC_P | CC_C | DF_MASK)) | cpu_cc_compute_all(env, CC_OP) | (env->df & DF_MASK);
 }
 
 /* NOTE: the translator must set DisasContext.cc_op to CC_OP_EFLAGS
```

**Comment by aquynh** [comment]
please send a PR to put a testcase under tests/ for what you are trying to fix, thanks.

**Comment by zardus** [comment]
Err, that's a bit complex. The issue is buried very deep in an angr testcase that uses parts of angr that haven't been released yet. Might be a little while :-)

**Comment by farmdve** [comment]
I actually reverted the code above and instead I force-sync the eflags all the time. You can test if it works for you too.

**Comment by aquynh** [comment]
i am quite sure that we dont have any testcase for this issue yet, even @farmdve reported it long ago?

without a testcase, it is hard to fix the problem.

**Comment by farmdve** [comment]
I will try to come up with a test case, however @zardus seems to have a better one, where certain branches are not taken, I've not yet come across that particular issue.

**Comment by lunixbochs** [comment]
#496 related?
