### ISSUE TITLE
Memory and address alignment. Can we relax it?

### ISSUE THREAD

**Issue by univm** [unicorn-engine/unicorn#314]
Right now Unicorn forces 4K alignment on addresses and 8K alignment on memory, this disparity in alignment is making it very difficult or near impossible for me to correctly copy memory from host to Unicorn(yeah I need to do it this way).

Why?

Because in Windows everything is 4K page aligned, but Unicorn expects 8K of memory. If I copy 4K into an 8K memory block in Unicorn that was previously unmapped, the latter 4K is empty but is no longer considered unmapped, this is making it very difficult to emulate some stuff correctly. I also can't copy 8K memory, because then I'd overwrite previously mapped memory with uc_mem_write, and I can't 8K align Windows addresses, because sometimes the memory in Windows is not mapped and APIs like ReadProcessMemory fail.

Is it possible to make memory mapping also 4K aligned?

**Comment by aquynh** [comment]
Can you send a pull request for this?
