### ISSUE TITLE
Failed on uc_open() with error returned: 2

### ISSUE THREAD

**Issue by geek-li** [unicorn-engine/unicorn#315]
After  I  bulit  the  binding example msvc/dynload ，run dynload.exe ,then  throw  this  error message.what's wrong with it?

**Comment by aquynh** [comment]
@xorstream, can you please look at this?

**Comment by xorstream** [comment]
@geek-li Are you doing a 32bit or 64bit build? What version of visual studio are you using? Did you alter the sample code at all?

These samples work fine for me, but I did realise that moving unicorn_dynload.h required changes to the lines that include that file. While I don't expect that this issue would result in the error you get, I suggest updating to this once pull request #317 gets merged and then trying again.

**Comment by aquynh** [comment]
@geek-li, #317 was merged, please try again with the latest code from Github.
