### ISSUE TITLE
How much is aarch64 supported?

### ISSUE THREAD

**Issue by ThomsonTan** [unicorn-engine/unicorn#324]
I didn't see LDAXR/STLXR instructions in the implementation.

**Comment by aquynh** [comment]
can you provide a testcase for the missing instructions? (for reference, see https://github.com/unicorn-engine/unicorn/tree/master/tests)

in general, there are two solutions:

- verify if the latest Qemu version supports the missing instructions. if Qemu does, backport to Unicorn. 

- if Qemu does not support them, go ahead implementing them yourself. then it is best to send your fix upstream (Qemu) so your implementation is approved.

in any cases, if you can fix the issue, then send us pull requests. thanks.

**Comment by farmdve** [comment]
I asked the QEMU devs. they said these instructions are supported. 

Note however that unlike x86 where instructions are byte-encoded, ARM instructions are bit encoded(they were in ARM32, so I assume it's the same for aarch64)  so finding where the implementation is can be tricky, but a good start would be *translate-a64.c*.

**Comment by aquynh** [comment]
This is why i asked for testcase to verify and test bugfix.
