### ISSUE TITLE
Debugging UC_ERR_WRITE_UNMAPPED (.NET binding)

### ISSUE THREAD

**Issue by master131** [unicorn-engine/unicorn#325]
I just started using Unicorn (version 0.9) today through it's .NET binding and am having issues trying to debug a "UC_ERR_WRITE_UNMAPPED" error returned by Unicorn.EmuStart.

I've attempted to register an event hook to determine the cause of this error but it seems that the hook itself is causing my application to crash shortly after calling EmuStart when Unicorn attempts to call the hook handler, possibly due to marshalling errors in the provided binding.

````c#
u.AddEventMemHook(new EventMemHook(EventMemHook), Common.UC_HOOK_MEM_WRITE_UNMAPPED, null);

/// .......

private static void EventMemHook(Unicorn u, ulong address, int size, ulong value, object userData)
{
            
}
````

Visual Studio reports this as a NullReferenceException and simply tells me that it happened in an "Unknown Module", providing me with no option to debug the native code or check the disassembly. When I debug with WinDbg, it reports it as an access violation (0xc0000005). The stack trace suggests it's occurring within CLR code.
```
STACK_TEXT:  
0a7ef68c 0a0da8cf 00000000 00000004 00000000 mscorlib_ni+0x3efa85
WARNING: Frame IP not in any known module. Following frames may be wrong.
0a7ef6bc 09db8d5e 00000000 00000004 00000000 0xa0da8cf
0a7ef6fc 10118893 05628820 00000014 0019ff64 0x9db8d5e
0a7ef81c 101133ac 0567caa8 ff7eb246 0a7ef870 unicorn!helper_le_stl_mmu_x86_64+0x186
0a7ef82c 74698017 006a0000 00000008 74698074 unicorn!tlb_reset_dirty_range_x86_64+0x13
0a7ef870 00000000 0566f7e4 0a7ef8ac 10121a89 msvcrt!_calloc_impl+0x136
```
Sadly since the Windows binaries have been compiled with GCC using DWARF symbols, most Microsoft tools (WinDbg, Visual Studio) are incapable of utilising the provided debug information. I've also tried cv2pdb which hasn't seemed to have made a difference in narrowing down the line number in Unicorn but I'm pretty certain it's trying to call the handler.

I would have tweaked and played around the code if I could but it's sadly written in F#, a language that I am not very familiar with. Any help would be greatly appreciated.

EDIT - It appears this issue was caused by invalid setup of the ESP and EBP register values. I have fixed the problem now with the help of the new Github bindings which throws exceptions and pointed this out to me. Now I am having the same issue, but now with the "UC_ERR_FETCH_UNMAPPED" error and "UC_HOOK_MEM_FETCH_UNMAPPED" hook type respectively.

**Comment by aquynh** [comment]
@enkomio, would you please look at this?

**Comment by enkomio** [comment]
I'll looking into it.

**Comment by enkomio** [comment]
Hi,

commit 2c54f1a969a89d14fde7c7c8fbaf41369ba1e728 should have resolved the problem. 

The example X86Code32InvalidMemWriteWithRuntimeFix in class X86Sample32 of the UnicornSamples project should provide an example of how to fix an access to an unmapped memory inside the EvenMemHook event handler.

To run the sample you need to download the Capstone dll and put it in the output directory.

**Comment by master131** [comment]
Sorry for the delay; indeed the commit has fixed the crashing issue with the binding.
