### ISSUE TITLE
Go binding broken with go 1.6 beta

### ISSUE THREAD

**Issue by ebfe** [unicorn-engine/unicorn#326]
$ go version
    go version go1.6beta1 linux/amd64
    
    $ go run bindings/go/sample.go
    panic: runtime error: cgo argument has Go pointer to Go pointer
    
    goroutine 1 [running]:
    github.com/unicorn-engine/unicorn/bindings/go/unicorn._cgoCheckPointer0(0x4c9500, 0xc820086020, 0x0, 0x0, 0x0, 0x4b6eb0)
    	github.com/unicorn-engine/unicorn/bindings/go/unicorn/_obj/_cgo_gotypes.go:75 +0x4d
    github.com/unicorn-engine/unicorn/bindings/go/unicorn.(*uc).HookAdd(0xc820086000, 0x8, 0x4e1e80, 0x541dd8, 0x0, 0x0, 0x0, 0xc820028020, 0x0, 0x0)
    	go/src/github.com/unicorn-engine/unicorn/bindings/go/unicorn/hook.go:110 +0x26e
    main.addHooks(0x7f2c89cba000, 0xc820086000)
    	go/src/github.com/unicorn-engine/unicorn/bindings/go/sample.go:22 +0x70
    main.run(0x0, 0x0)
    	go/src/github.com/unicorn-engine/unicorn/bindings/go/sample.go:65 +0x119
    main.main()
    	go/src/github.com/unicorn-engine/unicorn/bindings/go/sample.go:102 +0x1c
    exit status 2

Apparently there are new restrictions on what is allowed to cross the Go <-> C boundary.
See golang/go#12416.

**Comment by lunixbochs** [comment]
No! But I made sure it was safe :(
