### ISSUE TITLE
UC_MEM_READ hook fix discussion.

### ISSUE THREAD

**Issue by farmdve** [unicorn-engine/unicorn#327]
The commit is here https://github.com/farmdve/unicorn/commit/a3556f174cbb95854cc9d7b8b54eb984d1dc59d9 but I have not made a pull request as I want to discuss some things.

Basically the read hook will be called last and only if there is indeed data at that location and no other code returns early. This means a non-readable memory hook will be called first if there is one.

This is ok for architectures that do not rely on aligned access, but MIPS and SPARC do have ALIGNED_ACCESS defined and the `#ifdefs` 

For instance if this piece of code runs on SPARC or MIPS

``` c
#ifdef ALIGNED_ONLY
        if ((addr & (DATA_SIZE - 1)) != 0) {
            //cpu_unaligned_access(ENV_GET_CPU(env), addr, READ_ACCESS_TYPE,
            //                     mmu_idx, retaddr);
            env->invalid_addr = addr;
#if defined(SOFTMMU_CODE_ACCESS)
            env->invalid_error = UC_ERR_FETCH_UNALIGNED;
#else
            env->invalid_error = UC_ERR_READ_UNALIGNED;
#endif
            cpu_exit(uc->current_cpu);
            return 0; // <-- early exit, no read hook will be called
        }
#endif
```

and returns, the read hook will never be called, because the read hook is at the end of the function in order to get the result and put it in our callback instead of `0` like before.

The only solution I see if wrap my code around #ifdefs and have two pieces of the same code, one for ALIGNED_ACCESS and one for arches that don't need aligned access.

Furthermore I want to discuss this code here

``` c
    // Unicorn: callback on non-readable memory
    if (READ_ACCESS_TYPE == MMU_DATA_LOAD && mr != NULL && !(mr->perms & UC_PROT_READ)) {  //non-readable
        if (uc->hook_mem_read_prot_idx != 0 && ((uc_cb_eventmem_t)uc->hook_callbacks[uc->hook_mem_read_prot_idx].callback)(
                                       uc, UC_MEM_READ_PROT, addr, DATA_SIZE, 0,
                                       uc->hook_callbacks[uc->hook_mem_read_prot_idx].user_data)) {
            env->invalid_error = UC_ERR_OK;
        }
        else {
            env->invalid_addr = addr;
            env->invalid_error = UC_ERR_READ_PROT;
            // printf("***** Invalid memory read (non-readable) at " TARGET_FMT_lx "\n", addr);
            cpu_exit(uc->current_cpu);
            return 0;
        }
    }
```

The code sets `env->invalid_error = UC_ERR_OK;` if our hook returns `true`, but what happens if the hook never made the region readable but still returns true? There are no checks there.

**Comment by aquynh** [comment]
on (1): basically you want to change the way we handle read events. currently we will always get notified no matter what when emulated code tries to read memory. with your change, we dont get notified any more in the cases you mentioned. but sometimes you still want to know everything?

on (2): we need one more (simple) check to make sure that the related memory now is readable. if it is still unreadable, then we exit with error. currently i put some question marks there, but this issue is easy to fix.

**Comment by farmdve** [comment]
Do you have any ideas for 1?

My idea is to make an inline function like so

```c
static inline DATA_TYPE do_readhook(uc_struct *uc, DATA_TYPE res)
{
    // Unicorn: callback on memory read
    if (READ_ACCESS_TYPE == MMU_DATA_LOAD && env->uc->hook_mem_read) {
        struct hook_struct *trace = hook_find(env->uc, UC_HOOK_MEM_READ, addr);
        if (trace) {
            ((uc_cb_hookmem_t)trace->callback)(env->uc, UC_MEM_READ,
                    (uint64_t)addr, (int)DATA_SIZE, (int64_t)res, trace->user_data);
        }
    }

    return res;
}

Then do something like this

```c
    /* Handle aligned access or unaligned access in the same page.  */
#ifdef ALIGNED_ONLY
    if ((addr & (DATA_SIZE - 1)) != 0) {
        //cpu_unaligned_access(ENV_GET_CPU(env), addr, READ_ACCESS_TYPE,
        //                     mmu_idx, retaddr);
        env->invalid_addr = addr;
#if defined(SOFTMMU_CODE_ACCESS)
        env->invalid_error = UC_ERR_FETCH_UNALIGNED;
#else
        env->invalid_error = UC_ERR_READ_UNALIGNED;
#endif
        cpu_exit(uc->current_cpu);
        return do_readhook(uc, res);
    }
#endif
```

And obviously change `DATA_TYPE res;` to a default value 0 so we don't get random stack value;

**Comment by aquynh** [comment]
looks OK to me, but i still need to see the final fix to be sure.

**Comment by farmdve** [comment]
I've created a pull request, please check it out. The changes are minimal.

**Comment by danghvu** [comment]
Is this still an issue ? Where is the PR @farmdve  we should refer it to for keeping track.
