### ISSUE TITLE
hook_add, hook_del UC_HOOK_CODE does not work properly

### ISSUE THREAD

**Issue by michalmalik** [unicorn-engine/unicorn#334]
Hello,

I am using the git version from today. Please, don't mind that incorrect hook_code function when hooking UC_HOOK_INTR.

**1) Double hook_add raises no exception with UC_HOOK_CODE**

I've got this code:

```python
from unicorn import *
from unicorn.x86_const import *

ADDRESS = 0x8048000
STACK_ADDRESS = 0xffff000
STACK_SIZE = 4096
CODE = "1\xDBSCSj\x02jfX\x89\xE1"
EP = ADDRESS + 0x54

emu = Uc(UC_ARCH_X86, UC_MODE_32)
emu.mem_map(ADDRESS, 0x1000)
emu.mem_write(EP, CODE)

emu.mem_map(STACK_ADDRESS, STACK_SIZE)
emu.reg_write(UC_X86_REG_ESP, STACK_ADDRESS + STACK_SIZE)

def hook_code(mu, address, size, user_data):
        print(">>> Tracing instruction at 0x%x, instruction size = %u" %(address, size))
        
#####
       
emu.hook_add(UC_HOOK_INTR, hook_code, None)
emu.hook_add(UC_HOOK_INTR, hook_code, None)
       
#####
       
emu.emu_start(EP, EP + len(CODE), count = 3)
print("EIP: 0x%x" % emu.reg_read(UC_X86_REG_EIP))

emu.emu_start(EP, EP + len(CODE), count = 3)
print("EIP: 0x%x" % emu.reg_read(UC_X86_REG_EIP))
```

When executed, this raises an exception, which is *correct*:
```
unicorn.unicorn.UcError: Hook for this type event already exists (UC_ERR_HOOK_EXIST)
```

However, if I change *UC_HOOK_INTR* to *UC_HOOK_CODE*, no exception is raised:
```python
#####
       
emu.hook_add(UC_HOOK_CODE, hook_code, None)
emu.hook_add(UC_HOOK_CODE, hook_code, None)
       
#####
```

```
>>> Tracing instruction at 0x8048054, instruction size = 2
>>> Tracing instruction at 0x8048056, instruction size = 1
>>> Tracing instruction at 0x8048057, instruction size = 1
EIP: 0x8048058
>>> Tracing instruction at 0x8048054, instruction size = 2
>>> Tracing instruction at 0x8048056, instruction size = 1
>>> Tracing instruction at 0x8048057, instruction size = 1
EIP: 0x8048058
```
**2) hook_del does not delete UC_HOOK_CODE hooks**

This works OK, no exception raised:

```python
#####
       
emu.hook_add(UC_HOOK_INTR, hook_code, None)
emu.hook_del(UC_HOOK_INTR)
emu.hook_add(UC_HOOK_INTR, hook_code, None)
       
#####
```

However, if I change *UC_HOOK_INTR* to *UC_HOOK_CODE* and remove the second *hook_add*, nothing happens - the hook still works.

```python
#####
       
emu.hook_add(UC_HOOK_CODE, hook_code, None)
emu.hook_del(UC_HOOK_CODE)
       
#####
```

```
>>> Tracing instruction at 0x8048054, instruction size = 2
>>> Tracing instruction at 0x8048056, instruction size = 1
>>> Tracing instruction at 0x8048057, instruction size = 1
EIP: 0x8048058
>>> Tracing instruction at 0x8048054, instruction size = 2
>>> Tracing instruction at 0x8048056, instruction size = 1
>>> Tracing instruction at 0x8048057, instruction size = 1
EIP: 0x8048058
```

Is it something I missed in the documentation or this should not happen?

Thank you

**Comment by farmdve** [comment]
The issue with the hooks is actually a bit more subtle than that. In events where the jitted code exits the translation block, the hook is called twice for the same instruction.

**Comment by aquynh** [comment]
@michalmalik, please could you send in a pull request to put your testcase under tests/unit/ or tests/regress/ ?

**Comment by aquynh** [comment]
be sure to use hex form for the input code (rather than CODE = "1\xDBSCSj\x02jfX\x89\xE1"), and also to have a comment on the assembly of the code.

thanks.

**Comment by michalmalik** [comment]
Done. Could you please check it?

**Comment by aquynh** [comment]
this is because you use the API in the wrong way. see the fix for your testcase at https://github.com/unicorn-engine/unicorn/commit/2984901f6288d95cfab68770777dbdc17a56b87d.

you can pull again and try if your testcase works now.

**Comment by michalmalik** [comment]
Yes, thank you for that. Although, I submitted another issue that might be related to this. https://github.com/unicorn-engine/unicorn/issues/337
