### ISSUE TITLE
Cross-compile for Android

### ISSUE THREAD

**Issue by melbshark** [unicorn-engine/unicorn#340]
not work on Ubuntu14.04 x64, always using default cc compiler instead of ndk-gcc

**Comment by farmdve** [comment]
Don't use NDK, it's a severely limited compiler that lacks support for lots of things.

You need to build a cross-compiler that uses glib instead of Bionic(Android's libc).

**Comment by melbcat** [comment]
thank you for your reply, however, i'm doing as the compile.txt said, which is NDK=/android/android-ndk-r10e ./make.sh cross-android arm.

how to build the cross-compiler then? thank you very much.
