### ISSUE TITLE
SYSENTER instruction is not properly hooked in x86 emulation.

### ISSUE THREAD

**Issue by Spl3en** [unicorn-engine/unicorn#341]
[helper_sysenter](https://github.com/unicorn-engine/unicorn/blob/ed319bda0b7f7b6bb4a946d24682897e7f465c23/qemu/target-i386/seg_helper.c#L2304) don't check properly if a call interrupt callback is registred with uc_hook_add.

**Comment by farmdve** [comment]
Why did you remove the exception code?

**Comment by Spl3en** [comment]
Solely based on experimentation, helper_sysenter isn't called with this check. It might reveals the presence of another issue.

**Comment by Spl3en** [comment]
I've recovered the exception check, consequently the protected mode has been correctly initlialized in https://github.com/Spl3en/unicorn/commit/bb375e4fa9d68bf2878048d77ef07db7e209f1b1
