### ISSUE TITLE
Starting MIPS emulation at 0x80000000 or higher results in fetch from 0 (and PC of 0)

### ISSUE THREAD

**Issue by metrzero** [unicorn-engine/unicorn#343]
This issue can be reproduced by changing the MIPS sample to set the ADDRESS value to 0x80000000 instead of 0x10000.

**Comment by metrzero** [comment]
It seems as though this is because of the implicit user/kernel mapping. However, Unicorn does not seem to provide an API for setting the MIPS coprocessor registers prior to emulation.

**Comment by aquynh** [comment]
sounds like some issues with the MMU of Mips. would you mind sending in a pull request to put a testcase under `tests/` directory, so we can confirm & test the bugfix?

**Comment by metrzero** [comment]
Looks good on current head.
