### ISSUE TITLE
Please note pkgsrc (NetBSD) support

### ISSUE THREAD

**Issue by krytarowski** [unicorn-engine/unicorn#344]
The unicorn engine has been packaged for pkgsrc [1].

It has been noted [2] that unicorn was built for NetBSD, FreeBSD, Bitrig and OpenBSD.

Please note about it on the project website.

Installation from binary prebuilt packages:

```
pkgin install unicorn
```

Installation from sources:

```
cd /usr/pkgsrc/emulators/unicorn && make install
```

[1] http://pkgsrc.se/emulators/unicorn
[2] https://bulktracker.appspot.com/pkgresults/emulators/unicorn

**Comment by aquynh** [comment]
great, thanks! will update few docs, but in https://github.com/unicorn-engine/unicorn/blob/master/README.md we already said Unicorn support all kinds of BSD.

**Comment by krytarowski** [comment]
I was thinking about this website:

http://www.unicorn-engine.org/download/

**Comment by aquynh** [comment]
i updated this docs with instructions on pkgsrc: http://www.unicorn-engine.org/docs/

i also updated https://github.com/unicorn-engine/unicorn/blob/master/CREDITS.TXT with your name credited. thanks!

**Comment by krytarowski** [comment]
Thank you!

**Comment by aquynh** [comment]
btw, we had some minor changes in Makefile recently. would you mind trying to compile the latest code on *BSD to see it still works without any issues?

thanks.

**Comment by krytarowski** [comment]
53a989a751fd39a05ef25a8cf2a580c0f0c61b71 was built properly on NetBSD, no further test done

**Comment by aquynh** [comment]
great, thanks!
