### ISSUE TITLE
Implement callback function for emulation completion

### ISSUE THREAD

**Issue by mattifestation** [unicorn-engine/unicorn#345]
Is there any way you might consider implementing a callback function that fires upon completion or time out of an emulator run?

Something along the lines of this function signature:

`typedef void (*uc_cb_emu_complete_t)(uc_engine *uc, uint32_t status, void *user_data);`

where status refers to a successful completion or a timeout.

**Comment by lunixbochs** [comment]
why do you need a callback for that? the function will return and you can do whatever you want

**Comment by mattifestation** [comment]
Due to a unique threading situation when callbacks are executed in the binding I'm writing, uc_emu_start returns prior to completion of execution of all callbacks. Having a callback to signal completion would allow me to wait for completion since I'm unable to do so by waiting for uc_emu_start to return.

**Comment by lunixbochs** [comment]
Does emu_start return before the main thread of all callbacks returns, or is the problem due to you handling callbacks asynchronously?

If it's the former, that sounds like a different bug. In both cases, I think adding a callback on exit is the wrong solution.

**Comment by mattifestation** [comment]
Ultimately, my handling of callbacks is being handled asynchronously. This isn't by choice. Rather, it's a limitation in the binding language. Such a completion callback would personally benefit me.

**Comment by lunixbochs** [comment]
Handling callbacks asynchronously will cause other problems. How do you return true/false in the invalid memory access hooks?

**Comment by mattifestation** [comment]
It does indeed cause some issues that I'm aware of.

**Comment by lunixbochs** [comment]
If you create the "unicorn exited" callback handler script block in PowerShell and cast it to a delegate, can't you then invoke it directly from PowerShell instead of requiring support from Unicorn?

**Comment by mattifestation** [comment]
Sure. I can now bind a PowerShell scriptblock to all the Unicorn callback functions (a major hurdle that I needed to clear) via a delegate. I'm not sure what you mean by a "unicorn exited" callback. I have a workaround for awaiting for callback execution completion but it's far from elegant. A dedicated Unicorn callback is the easiest, most elegant way that I can think of to handle signaling completion but that would assume such a callback existed.

**Comment by lunixbochs** [comment]
If you're proposing this:

    your_callback {
        // unicorn and all callbacks are done
    }

    some_delegate = your_callback
    uc_hook_add(UC_HOOK_DONE, some_delegate)
    uc_emu_start()

How is it different from this?

    your_callback {
        // unicorn and all callbacks are done
    }

    some_delegate = your_callback
    uc_emu_start()
    some_delegate()

**Comment by mattifestation** [comment]
because some_delegate triggers prior to completion of the async callbacks

**Comment by lunixbochs** [comment]
You can invoke (through P/Invoke or whatever) C functions, right? And PowerShell can bind script blocks to C function pointers, or you wouldn't be able to pass them to `uc_hook_add()`.

Why can't you create a delegate as though you were going to pass it into `uc_hook_add()`, then call it yourself using the C function invocation interface?

**Comment by mattifestation** [comment]
That is precisely what I'm doing (passing a scriptblock via uc_hook_add). The delegate has to be an async callback however due to the fact that the PowerShell runspace doesn't exist in the callback thread context. As a side effect, the scriptblocks bound to the async callback complete their execution after uc_emu_start has already returned.

I am collecting objects based on the arguments passed in to the callbacks back to my main thread via the New-Event cmdlet and after uc_emu_start returns, I collect them with Get-Event. The problem is that I'm not capturing all of the events because the scriptblocks are still being processed asynchronously. Again, I have a workaround (synchronous) but it is far from elegant. A dedicated emulator completion callback would allow me to signal a completion event that I could wait for in my main thread via Wait-Event.

**Comment by lunixbochs** [comment]
You still don't seem to understand. Can't you do literally everything you would do as if Unicorn actually supported this callback, then dispatch the async delegate for the callback yourself from the main PowerShell thread (which should run in the async context after the other Unicorn callbacks) instead of relying on Unicorn to call it for you?

**Comment by mattifestation** [comment]
Thank you for you input. I understand just fine. We don't have to go back and forth though. This was merely a request that can certainly not be implemented. If not, no sweat. If it can, great!

**Comment by lunixbochs** [comment]
I did some further reading and it looks like asynchronous callbacks will be handled by a thread pool, so unless I misinterpreted it you can't guarantee callback ordering and a Unicorn callback thus won't help (as it will still be a data race)

I don't like the idea of adding callbacks that would need to be maintained in every binding unless they're actually necessary, and this duplicates a feature Unicorn already provides (as the return from `emu_start()` will happily provide a synchronization point indicating the end of emulation and the status code), which is why I'm advising against it.

The decision is ultimately up to @aquynh but I'm trying to determine if the callback would help at all, let alone be a significant improvement over your other options.

**Comment by mattifestation** [comment]
Ultimately, I think you're right. A feature shouldn't be implemented to cater to the unique, less than ideal situation of an individual. I have a workaround that will suffice. Thanks again for your input.

**Comment by aquynh** [comment]
yes we will only add a new feature/API if that is demanded by many apps. for one-off case, please implement that yourself. in the case of @mattifestation, that can certainly be done.

thanks.
