### ISSUE TITLE
Crash after Double mapping

### ISSUE THREAD

**Issue by eqv** [unicorn-engine/unicorn#350]
If the same memory reagion is mapped twice, unmapping any region will crash the emulator with a assertion failure. It is unclear if mapping an already mapped page should fail, but it certainly shouldn't assert-fail to unmap.  A testcase was added in #349.

**Comment by farmdve** [comment]
I wonder if this has anything to do with my fix for calling the memory destructor.

**Comment by lunixbochs** [comment]
if you map the same page twice, then unmap it twice, which MemoryRegion is used for the second unmap? I'm assuming it will unmap the same region twice

**Comment by ranmrdrakono** [comment]
I'm only unmaping once. I think a hypothetical second unmap should fail since unmaping pages that are not mapped should fail. The only question is: Do we expect multiple maps to overlapping pages to fail / succeed?

**Comment by aquynh** [comment]
to keep it simple, we can just disallow mapping overlapped memory. the returned value can be either UC_ERR_MAP or a new error type.

**Comment by lunixbochs** [comment]
Would I still be able to map 0-8000, unmap 2000-4000, and map something else there?

**Comment by aquynh** [comment]
yes it should be OK now. if not, then it is a bug.

**Comment by aquynh** [comment]
i modified uc_mem_map() and uc_mem_map_ptr() so they cannot map a new range that overlaps existing memory regions. see https://github.com/unicorn-engine/unicorn/commit/7e16f7a50d8150625c16529e09009de7fd6ac998

thanks
