### ISSUE TITLE
Trace RET instructions

### ISSUE THREAD

**Issue by eqv** [unicorn-engine/unicorn#352]
There is a constant for X86_INS_RET but as far as I can tell there is currently no way of hooking RET instructions without explicitly hooking all instructions and perform checks yourself.

**Comment by williballenthin** [comment]
Yes, you must do the checks yourself.

**Comment by aquynh** [comment]
currently we only support hooking some instructions that are usually required to be traced in most apps, such as INT, SYSCALL, SYSENTER, etc.

if you think RET deserves to be treated in the same way, please go ahead doing that and send in a pull request.

**Comment by ranmrdrakono** [comment]
I honestly have no idea how to patch this. I'm fine with tracing instructions myself for now. However I believe that call/ret are interesting for stuff such as call graph construction etc.

**Comment by Spl3en** [comment]
> I honestly have no idea how to patch this
Look at here https://github.com/unicorn-engine/unicorn/blob/f4a5273ce7f0bd67f1039f309f34719d3c052165/uc.c#L997

**Comment by JonathonReinhart** [comment]
```
static uc_err _hook_insn(struct uc_struct *uc, unsigned int insn_id, void *callback,
        void *user_data, uc_hook *evh)
{
    switch(uc->arch) {
        default: break;                      // return UC_ERR_OK
        case UC_ARCH_X86:
                 switch(insn_id) {
                     default: break;         // return UC_ERR_OK
                     // ...
                 }
                 break;
    }

    return UC_ERR_OK;
}
```

![Doge meme: WOW SO ERROR CHECKING MUCH FAIL MANY IGNORE AMAZE](https://i.imgflip.com/x66d2.jpg)
