### ISSUE TITLE
Make.sh install broken

### ISSUE THREAD

**Issue by GrannyDanny** [unicorn-engine/unicorn#355]
It's about `capstone` as well that uses the same build system. 

Running `make.sh` with a bunch of options to build the selected features doesn't get carried to `make.sh install` or in my case `checkinstall make.sh install`;  the system starts building **everything** again.

Presently, to make it work you have to run install with the same set of variables which is not how `make install` normally works.

**Comment by aquynh** [comment]
did you use "make.sh" as instructed in https://github.com/unicorn-engine/unicorn/blob/master/COMPILE.TXT? how to reproduce your issue?

thanks.

**Comment by GrannyDanny** [comment]
Did I sound like I didn't manage to install it in the end? 

The default for make.sh is `build everything` and that gets carried over to install despite the flags that were used (after switching to root which is needed by checkinstall).

**Comment by egberts** [comment]
I too was stymied as a veteran builder... Compile and link should be doable at non-root account and install is at destination owner's.   many different distro packagers rely on this concept.  How can we help take this to the next level of supporting multiple package managements?

**Comment by danghvu** [comment]
Several changes to the Makefile has been made since then, please open a new one if this is still and issue.
