### ISSUE TITLE
Common register ID suggestion

### ISSUE THREAD

**Issue by xorstream** [unicorn-engine/unicorn#359]
When using multiple cpus/archs for unicorn in a project I have noticed that one of the things I do a fair bit is to work out what the register id is for the PC, SP, etc registers for each different CPU. With the the current unicorn API the register ids are the main thing that need to be handled specially across different cpus.

So my suggestion is to add an alias for these common types of special registers that would work across different cpus/archs. It would only require adding some more special register ids and then handling them. It wouldn't require any API changes and would simplify the users access to such registers.

I'm thinking like:
UC_REG_PC = 0x80000001,
UC_REG_SP = 0x80000002,
UC_REG_GP = 0x80000003,
UC_REG_FP = 0x80000004,

Which would then be used like:
uc_reg_read(uc, UC_REG_PC, &pc_val);
uc_reg_read(uc, UC_REG_SP, &sp_val);

This might also be used to provide access to the PC value for CPUs that don't have an explicit PC register. I am happy to add these changes and make a pull request. I just wanted to get ppls thoughts on the idea before doing so.

**Comment by lunixbochs** [comment]
Can you talk about the kind of tool/code patterns using Unicorn where this would be most useful?

I have a couple of thoughts.

Based on my experience integrating the architecture-specific backends with Usercorn (which is one of the only projects I know supporting all Unicorn architecture), I don't immediately see the utility here beyond PC/SP, and even that was *very* minimal (painless) code for handling PC/SP register enums myself per arch. I don't think it's a stumbling block, as you almost certainly need other architecture-specific code so you can probably bundle PC/SP enums with it in your codebase.

It may also be worth noting that every architecture currently supported by Unicorn does have both PC and SP register enums exposed (so "CPUs that don't have an explicit PC register" doesn't apply right now). I do like the idea of exposing PC even if the CPU wouldn't normally.

Additionally, only some have FP or GP registers, so adding generic enums for those could be a bit confusing.

**Comment by xorstream** [comment]
tbh it is mainly for the PC register access for me.
But then when i thought about the best way to do it without cluttering the API it seemed that having a special alias register id value was the best way to go. And then if going that way it seems you might as well provide access to other common registers such as SP, GP, FP etc. Sure the latter ones might not be in all CPUs, but they may prove useful across the cpus that do support them.

I am using unicorn emulator as a debugger for code snippets. So I am setting the PC value to start at as well as checking it while stepping into/over code and running to cursor etc etc.

**Comment by farmdve** [comment]
@lunixbochs 

A hackish way to expose internal stuff is to typecast uc_engine to uc_struct. Then you would get direct access to the registers.

**Comment by aquynh** [comment]
personally i dont see much improvement with this change. we already have UC_xxx_REG_PC for all archs (please send pull requests if you find something still missing). having a generic id for PC can help very little here.

for other registers such as SP or FP, if a particular arch does not have them, adding aliases can make it more confused, like @lunixbochs said.

**Comment by danghvu** [comment]
No update or discussion since then, please open a new one if this is still an issue.
