### ISSUE TITLE
Thread racing or false-positive?

### ISSUE THREAD

**Issue by farmdve** [unicorn-engine/unicorn#362]
If you run sample_x86 -32 on unicorn master under valgrind memcheck, you'd get after 10-20 seconds a few invalid read of size 8 errors(on a 64-bit build).

==758== Invalid read of size 8
==758==    at 0x40577B: uc_reg_read (uc.c:302)
==758==    by 0x40340E: hook_code (in /home/_/unicorn/unicorn2/samples/sample_x86.static)
==758==    by 0x40839E: helper_uc_tracecode (hook.c:278)
==758==    by 0x7CE242: ??? (in /home/_/unicorn/unicorn2/samples/sample_x86.static)
==758==    by 0x4A01000002: ???
==758==  Address 0x66171a8 is 360 bytes inside a block of size 2,240 free'd
==758==    at 0x53FAD37: free (vg_replace_malloc.c:530)
==758==    by 0x40575C: uc_close (uc.c:293)
==758==    by 0x403921: test_i386 (in /home/_/unicorn/unicorn2/samples/sample_x86.static)
==758==    by 0x405207: main (in /home/__/unicorn/unicorn2/samples/sample_x86.static)
==758==  Block was alloc'd at
==758==    at 0x53FB994: calloc (vg_replace_malloc.c:711)
==758==    by 0x405430: uc_open (uc.c:144)
==758==    by 0x403722: test_i386 (in /home/_/unicorn/unicorn2/samples/sample_x86.static)
==758==    by 0x405207: main (in /home/*/unicorn/unicorn2/samples/sample_x86.static)

These errors shouldn't be posible. How can uc_reg_read be called if we called uc_close, the program should have ended by then and all other threads for that instance. There is a possible thread race with the timeout option in uc.c, but that is only a part of the problem as it only works if timeout > 1, there is some kind of other race here.

I really wonder if it's a false positive.

EDIT:perhaps indeed it's a false-positive. In gen_uc_tracecode we do TCGv_ptr tuc = tcg_const_ptr(tcg_ctx, uc);, which returns an index, not a pointer, which is swapped with the real pointer later in tcg_constant_folding.

With this I at least conclude my memory leak branch is not responsible, as this is reported with unicorn master 
https://github.com/farmdve/unicorn/commit/036763d6aec6a725930989090f47049471d173fa

**Comment by danghvu** [comment]
Can you check the master branch if this is still an issue ?
