### ISSUE TITLE
ARM pc-relative VLDR UC_ERR_INSN_INVALID

### ISSUE THREAD

**Issue by lunixbochs** [unicorn-engine/unicorn#366]
This throws invalid instruction:

    vldr s16, [pc, #244]

This works fine:

    vldr	s15, [r6]

**Comment by aquynh** [comment]
how does Qemu handle this code?
if Qemu 2.2.1 cannot handle it, how about Qemu 2.5.0?

**Comment by farmdve** [comment]
Latest qemu supports the instruction, however their code base has been significantly altered for the ARM arch.

If we are to fix this we must backport all changes as they have disentangled VFP instruction decoding from disas_coproc_insn

**Comment by aquynh** [comment]
@lunixbochs, can you add more code after the call to `emu_start()` to assert new CPU context (registers + memory value), so it is easier to confirm the fix?

thanks

**Comment by farmdve** [comment]
I am attempting to update to 2.3.0 and then to 2.4.0, but this will be a very slow and tedious process with lots of manual patching.

**Comment by aquynh** [comment]
no worry, i will sync straightly to 2.5.0.

**Comment by farmdve** [comment]
How? Most of the commits introduced are breaking.

**Comment by aquynh** [comment]
Manually, of course.

**Comment by farmdve** [comment]
Like, diffing 2.2.1 and current unicorn master, creating a patch, then applying it to 2.5.0 and manually fixing the hunks?

**Comment by aquynh** [comment]
Yes, that is only way.

**Comment by aquynh** [comment]
Ah no, a better way is to diff 2.2.1 and 2.5, then manually patch the diff to current code.

**Comment by farmdve** [comment]
As far as I understood, 2.2.1 is a fork of 2.2.0 with some select patches of master, in essence it's it's own beast so to say. To do it you'd have to diff with 2.2.0.

**Comment by aquynh** [comment]
what is in 2.2.1, but not in 2.5.0?

**Comment by farmdve** [comment]
The qemu developers told me that 2.2.1 is a fork of 2.2.0 with select fixes backported. It means that 2.2.1 doesn't match up with master at any point in time or other releases. Only 2.X.0 e.g 2.2.0, 2.3.0, 2.4.0, 2.5.0 match up with each other as far as i understood it.

**Comment by aquynh** [comment]
actually Unicorn was based on 2.2.0, then i ported it to 2.2.1. and i dont remember anything special in this version at all.

i am not worried anyway. lets see how it works ...

**Comment by aquynh** [comment]
so can you confirm that Qemu 2.2.1 cannot handle this code, but Qemu 2.5.0 can?

**Comment by farmdve** [comment]
I believe we can agree that 2.2.1 can't, as Unicorn is based on 2.2.1 and the instruction isn't decoded. I've asked a qemu dev, Peter Maydell and he said it works in 2.5.0. Other than his word, I have no direct  proof.

**Comment by farmdve** [comment]
@aquynh 

Any progress on the 2.5.0 fork?

**Comment by lunixbochs** [comment]
closing in favor of #461
