### ISSUE TITLE
qemu throws assertion on mem_map with size 0

### ISSUE THREAD

**Issue by lunixbochs** [unicorn-engine/unicorn#369]
from unicorn import *
    uc = Uc(UC_ARCH_X86, UC_MODE_32)
    uc.mem_map(0x2000, 0)

Sorry, in a rush and don't have time to submit a regress PR.

**Comment by farmdve** [comment]
Impossible. 

In uc.c in uc_mem_map

```c
    if (size == 0)
        // invalid memory mapping
        return UC_ERR_ARG;
```

**Comment by aquynh** [comment]
this is now fixed thanks to a PR of @farmdve, thanks.

**Comment by lunixbochs** [comment]
Confirmed.
