### ISSUE TITLE
should uc_emu_start always return an error if it encountered a memory access error?

### ISSUE THREAD

**Issue by williballenthin** [unicorn-engine/unicorn#371]
Lets use the sample test code in #368 as an example.

The emulator executes begins executing and immediately hits an instruction that reads invalid memory. A `UC_HOOK_MEM_UNMAPPED` is correctly invoked, and this function has the option to return true or false. The emulator stops executing after the first instruction, because of the memory error. The return value from `uc_emu_start` does not signal that anything exceptional happened.

As a user, it would surprise me that the emulator did not execute until the requested address (or other limit, like time or insn count). I'd have to check the side effects of the memory hook, or confirm that PC matches the intended address. I would have expected that `uc_emu_start` would return something other than `UC_ERR_OK` if there was a memory read/write/fetch error during emulation.

I tried changing the return value from the memory hook to true and false. This did not have an effect on the return value from `uc_emu_start`. If I removed the hook completely, then `uc_emu_start` returns the unmapped read error. So, I think this boils down to my (personal) opinion: *the return values from `uc_emu_start` should be the same whether or not there are hooks installed.*

Thoughts?

**Comment by aquynh** [comment]
if you cancel emulation by returning *false* from the callback, then yes `uc_emu_start()` should return the error code rather than `UC_ERR_OK`. this should be fixed.

but if you continue to emulate, then i think `uc_emu_start()` should return `UC_ERR_OK` because you already handled errors yourself.

**Comment by aquynh** [comment]
actually we already handled the case when you return False from the callback: `uc_emu_start()` would return with the error code, but not with value 0. 

see a new testcase in the commit https://github.com/unicorn-engine/unicorn/commit/d0125eb8bf0a8c4757c93cc1482c2ba5d5fa3a70. its output is like this:

    $ ./invalid_write.py
    .
    ----------------------------------------------------------------------
    Ran 1 test in 0.001s
    
    OK
