### ISSUE TITLE
Proposing new API.

### ISSUE THREAD

**Issue by farmdve** [unicorn-engine/unicorn#372]
`uc_reg_lock(int regid, int lock)`
`uc_reg_unlock(int regid) OR uc_reg_lock(int regid, int lock) with type of UNLOCK`

types of lock

`LOCK_READ`
`LOCK_WRITE`

Purpose of the API:
Locking a specific register, any instruction that tries to modify it/read it will fail and/or trigger an exception callback by the user.

This is to further add fine-tuned control over which registers can be modified by user-code when attempting to emulate certain conditions.

**Comment by egberts** [comment]
Love it.  Curious, which API callback gets triggered?

**Comment by farmdve** [comment]
None, exception callbacks are not yet implemented, but I will work on it.

**Comment by aquynh** [comment]
this is nice to have, but implementation will not be easy.

to be consistent with current API, how about setting this as another kind of hook? something like:

    uc_hook_add(uc, &trace, UC_HOOK_REG, callback, NULL, UC_X86_REG_EAX)

with this approach, you dont need to add `uc_reg_unlock()`, but can use existing facilities (such as `uc_hook_del()` and other internal housekeeping structs)

**Comment by lunixbochs** [comment]
I think this makes perfect sense under the hook system. You can do `UC_HOOK_REG_READ|WRITE` with an optional register parameter.

What's your implementation strategy? One way could be to flush the block cache when adding a new register hook, and add a provision to have TCG insert a callback immediately before instructions with register access that matches your hook.

**Comment by farmdve** [comment]
My strategy was exactly what you mentioned, after the TCG code has been generated, scan for any type of access of the specified register and do something.

**Comment by aquynh** [comment]
this is the easiest solution and can work with all kind of instructions and architectures. however, it is the most expensive one in term of performance as you have to save the context before every instruction, then verify if anything is changed after that.

but for the first version this is OK. we will try to improve the performance in the future.

**Comment by lunixbochs** [comment]
What do you mean "verify if anything is changed"?

**Comment by aquynh** [comment]
oh no, it is more complicated than that. we might need to hook all the code accessing registers, and have to take into account read and write events, too.

**Comment by xorstream** [comment]
Having a read/write reg callback would be nice. Currently I am hooking code execution and checking all registers against their previous values to determine changes which is a lot more costly than just checking regs that are written to.

**Comment by Invincibl-e** [comment]
Is it possible to continue to implement this idea? @aquynh

**Comment by wtdcode** [comment]
> Is it possible to continue to implement this idea? @aquynh

The performance overhead is almost the same as hooking each instruction. You may implement your own register hook with that.
