### ISSUE TITLE
instruction hook behavior

### ISSUE THREAD

**Issue by lunixbochs** [unicorn-engine/unicorn#377]
maybe instruction hooks like syscall should have an option (boolean return?) to allow or block the original behavior

because we need to prevent qemu from jumping to the syscall handler itself when doing syscall/kernel emulation, but if someone ever wants to run an actual kernel in unicorn we'll need the real cpu behavior.

**Comment by farmdve** [comment]
Define `kernel`. The way I see it, because Unicorn does not emulate anything more than a CPU, and raw one at that, I don't think it can ever run a full-fledged kernel.

If you are talking however, about the boot up code, that might work, but still not the same as original QEMU.

And yes, I also think that hooking any instruction should allow us to return before it executes. Perhaps some API that inserts an early exit from the TB.

**Comment by aquynh** [comment]
@lunixbochs is there any real applications needing this feature? if there is none, we dont need to worry about the future demand.

@farmdve, in the callback if you call uc_emu_stop(), you will stop emulation immediately. other than that, i dont see why you want to just exit the basic block and continue to emulate after that.

**Comment by farmdve** [comment]
Ah yeah, sorry. Forgot about uc_emu_stop.

**Comment by lunixbochs** [comment]
@aquynh yes, I have a legitimate reason to run a reduced Linux kernel under Unicorn. I've already confirmed I seem to be able to to switch between user/kernel mode as well.

Unless you delete/stub anything important, Unicorn should be able to run code that expects to be running on raw hardware, as long as the user implements enough hooks (like in/out ports). In this case, syscall is the only thing I know is stubbed.

**Comment by lunixbochs** [comment]
The main issue here, the thing that "won't work", is Unicorn's interrupt/syscall handlers currently call the hook if it exists, but usually *does not attempt to invoke a real CPU interrupt handler*. This means a real kernel can't boot in Unicorn unless you monkeypatch interrupt handling back on yourself, which is a shame because the code is already there in QEMU :)

**Comment by aquynh** [comment]
yes, this is nice to have. can you propose the API change for this?

**Comment by lunixbochs** [comment]
I think all we need is a boolean return from instruction and interrupt hooks that indicates "this was handled". If an event is "handled", the chain stops and the CPU proceeds to the next instruction. If "not handled" propagates all the way to the top, the original behavior will occur, which could be a kernel interrupt handler or even Unicorn throwing an error.

This would just be something like:

    HOOK_FOREACH {
        if (! hook_call()) {
            break;
        }
    }

**Comment by elliott-wen** [comment]
Hi @lunixbochs 

I tried to run linux in unicorn, and have implemented the basic hardware like PIC, timer, and pci bus stuff. 

I noticed that system call/ system enter / interrupt handlers have been stubbed. So I patched them. 

Other than that, I also notice in mmu, the do mapping is also stubbed.

I am just wondering, any other stuff I should patch?

**Comment by farmdve** [comment]
Perhaps you should wait a bit, there is currently a discussion for Unicorn
2, a rewrite with latest QEMU and hopefully emphasis on being able to merge
newer changes from upstream QEMU.
