### ISSUE TITLE
Python binding unit test, file placement?

### ISSUE THREAD

**Issue by egberts** [unicorn-engine/unicorn#381]
Where would you like the unit test for Unicorn Python to-C API binding?  under unicorn/bindings/python/tests?  

Do you have a preference as to whether you want to use Python unittest2 framework or higher frameworks (decorator, factory) like nose (xUnit-compatible test output, coverage reporting, and test selection)

Is there a minimum version of Python in which we must support?

**Comment by aquynh** [comment]
i think it is better to put all the tests under `tests/`, and leave bindings/ for just binding code. so you just can create a new directory `tests/python`.

i never use those Python unit test framework, so i have no preference here. if nobody else has any comments on this, please go ahead choosing the most popular one.

regarding the Python version, i think we can target Python 2.6 an up.

thanks.

**Comment by aquynh** [comment]
btw, if you are into Python, one item in TODO list to make the current binding more "Pythonic", which many people want to have in the next version: https://github.com/unicorn-engine/unicorn/issues/201

thanks.
