### ISSUE TITLE
Some UNICORN_QEMU_FLAGS options are not buildable.

### ISSUE THREAD

**Issue by egberts** [unicorn-engine/unicorn#384]
I'll hold off on putting out new issues regarding broken combination of `./make.sh` options until QEMU 2.5 port is done.  Ones that I thought were noteworthy are:
- `V=1 UNICORN_QEMU_FLAGS="--enable-debug --enable-debug-tcg"./make.sh`
  - has conflicting [function declarator] types for `tcg_check_temp_count()` and `tcg_clear_temp_count() functions in`tcg.c`/`tcg.h` source files.
- `V=1 UNICORN_QEMU_FLAGS="--static" ./make.sh`
  - requires libz.a

**Comment by aquynh** [comment]
i am working on Qemu 2.5 sync, but this is not trivial, and will take a while. so go ahead do what you plan, and dont wait for that.

one solution to this issue is to remove those options we do not support inside `qemu/configure`. pull request on this is welcome!

**Comment by egberts** [comment]
Do you have a decision as to what build tool set to fully use? Autoconf, cmake, scon, or ???

**Comment by aquynh** [comment]
please use what we are using now: Makefile & configure

**Comment by aquynh** [comment]
actually if you can convert everything to CMake (including code under `qemu/`, we can make an important step towards MSVC build? wishful thinking ...

**Comment by JonathonReinhart** [comment]
I suggested SCons in #200, but got shut down pretty hard.

**Comment by egberts** [comment]
Couldn't believe that CONFIG_ defines are being used intensively instead of HAVE_.  Cmake can handle that. Autoconf, not so much.

**Comment by aquynh** [comment]
@JonathonReinhart i was content with cross-compile for Windows at that time. but now Unicorn improved, we can think about native MSVC support. then some sacrifices must be made for this demand :-)

not quite sure about SCons, but i think CMake would be a better choice because more people known about it, so getting more contributions is easier.

**Comment by egberts** [comment]
Prototyping of cmake to go in [egberts/unicorn](https://github.com/egberts/unicorn).  No push yet.

**Comment by aquynh** [comment]
sounds great! would you do a PR for reviewing?

have you tried to compile with Cmake on Windows, with either `-G "NMake Makefiles"` or `-G “Visual Studio 11 2012 Win64”`, then compile with MSVC to see how if it works?
