### ISSUE TITLE
make.sh needs separate install and build

### ISSUE THREAD

**Issue by egberts** [unicorn-engine/unicorn#385]
When doing `./make.sh` on a NFS mount (where writing root-owned file is typically forbidden), the `./make.sh install` does yet another build then install

Ideally, one would (and ideally, should) do this in their NFS-provided $HOME directory:

``` sh
 ./make.sh build
 sudo ./make.sh install
```

Under ideal condition, the `make.sh install` should just find these pre-existing binaries (and assuming that these binaries are newer than all of its object/source/include) and just install these binaries, as root.

Currently, `make.sh install` summarily proceeds to delete various binary files (as root, that was just built by `make.sh build`) off of that non-root `unicorn` directory which fails when residing in a NFS-mount having forbade any direct root interaction.

A list of files that were attempted to be -->ALWAYS<-- deleted under `make.sh install` are:
- `libunicorn*` non-root
- `unicorn*.lib` non-root
- `unicorn*.dll` non-root
- `cygunicorn*.dll` non-root

Furthermore, this `sudo make.sh install` also caused secondary problem of -->ALWAYS<-- trying to recreate build object and binaries files as root into a non-root NFS mount (fails there too).

**Comment by egberts** [comment]
My workaround is to work out of `/var/tmp`.

**Comment by aquynh** [comment]
yes, this should be fixed. keep us updated if you have a solution, thanks.

**Comment by egberts** [comment]
Mon Deux!  Fabrice sure did a brute force hand-rolled `configure` of his own.
