### ISSUE TITLE
incorrect PC values during execution

### ISSUE THREAD

**Issue by lunixbochs** [unicorn-engine/unicorn#386]
Okay, so I've reproduced this on ARM, MIPS, x86, and x86_64.

Usercorn has an instruction trace mode that prints each instruction as it executes using HOOK_CODE. Sometimes Unicorn returns a wildly incorrect PC address, but the correct instruction is at both addresses. Sometimes the traced instruction is actually different from the instruction at the correct address, and in this case the incorrect instruction seems to execute.

In this case, ret was the wrong instruction. Note the address: https://bochs.info/p/nmbpb5
ret actually executes here.

A simple reproduction of the wrong address but correct instruction is to run Usercorn against bins/x86.linux.elf - https://bochs.info/p/ejwgz
0x8048cbc is repeated twice.

I haven't reproduced this in any way other than "use Usercorn" because it's coming from complex binaries so I can't really submit a regression. This looks like bad JIT output of some kind.

**Comment by aquynh** [comment]
if you can dump that related basic block out, you can reproduce this issue with a minimal code?

**Comment by lunixbochs** [comment]
I haven't gotten that far yet. Notice in the second trace it's reusing an address from earlier.

**Comment by lunixbochs** [comment]
Nevermind, this was indeed a bug in Usercorn. Carry on!
