### ISSUE TITLE
[arm] is UC_MODE_ARM enum correct ?

### ISSUE THREAD

**Issue by xorstream** [unicorn-engine/unicorn#389]
In "typedef enum uc_mode" is the value for UC_MODE_ARM correct?
It is currently: UC_MODE_ARM = 0,    // 32-bit ARM
But that makes it impossible to see if it is set or not!?

Is it supposed to be this instead?: UC_MODE_ARM = 1 << 0,    // 32-bit ARM

**Comment by aquynh** [comment]
this is a good question, but we have no issue with UC_MODE_ARM=0 because ARM & THUMB are mutually exclusive: it is either UC_MODE_ARM or UC_MODE_THUMB. if UC_MODE_THUMB is there, we dont check for UC_MODE_ARM. if UC_MODE_THUMB is not there, we enable UC_MODE_ARM mode.

**Comment by xorstream** [comment]
One of the checks that is done in uc_open() is:
    if (mode != UC_MODE_ARM && mode != UC_MODE_THUMB)

This check is incorrect because it does not allow for other flags being set such as:
UC_MODE_BIG_ENDIAN
UC_MODE_MCLASS
UC_MODE_V8

If UC_MODE_ARM was set to "1<<0" then it could be used as a bitflag check in the form:
    if ( !(mode & UC_MODE_ARM) && !(mode & UC_MODE_THUMB) )
which would then allow the use of other mode flags.

**Comment by aquynh** [comment]
yes, this implementation is not right here, and should be fixed. PR is welcome. 

(but note that at the moment this is not a problem since we do not support Big endian and other combination yet.)

no, we dont really need to set UC_MODE_ARM to non-zero value, because we can do something like this:

    if (mode & UC_MODE_THUMB) then turn-on-Thumb-mode; else turn-on-ARM-mode.

**Comment by xorstream** [comment]
The verify code that I pasted specifically checks for whether it is ARM or THUMB though. So if UC_MODE_ARM is left as 0 then it makes no sense to perform the check at all since then you are just checking "if thumb-is-set and thumb-is-not-set". So basically that whole block should just be removed:

                // verify mode
                if (mode != UC_MODE_ARM && mode != UC_MODE_THUMB) {
                    free(uc);
                    return UC_ERR_MODE;
                }

Also if big endian and the other arm flags are not supported it should probably say this next to them in the header file, or have them commented out to show they are not yet in use.

**Comment by xorstream** [comment]
Looking through the sourcecode it seems that everywhere that UC_MODE_ARM and UC_MODE_THUMB are used, it is to check that the mode is either UC_MODE_ARM or UC_MODE_THUMB and then does the same code for each case. So basically it is just not allowing any other modes. But what other modes is it "protecting" against? One of these 3 mode flags?
UC_MODE_BIG_ENDIAN
UC_MODE_MCLASS
UC_MODE_V8

It seems to me that all the checks for UC_MODE_ARM and UC_MODE_THUMB could be removed and only leave the code that checks if UC_MODE_THUMB is set and sets the thumb mode variable if so.

Do you agree that these checks have no use? Or is there is hidden use I am missing?
If you agree I'll do a pull request removing them (which would then allow the use of the other 3 mode flags in the future once they are implemented).

**Comment by aquynh** [comment]
a properly check is like in the commit i just pushed https://github.com/unicorn-engine/unicorn/commit/21c614d0af0d77405bcdd7b290854e5232dfd1e8

yes, if you see anywhere that simply verifies only value UC_MODE_ARM or UC_MODE_THUMB, then please fix it.

thanks.

**Comment by xorstream** [comment]
I notice that you allow the currently unsupported mode UC_MODE_BIG_ENDIAN but you don't allow the other unsupported modes UC_MODE_V8 and UC_MODE_MCLASS.

This should probably either allow all 3 unsupported modes or not allow all 3 unsupported modes. It seems strange to allow some but not others.

Also if such checks are repeated it might be better to make a combined mask enum for them so that future changes can all be done by just changing the one mask value and not every instance in the code, like:
UC_MODE_ARM_MASK = UC_MODE_ARM | UC_MODE_THUMB | UC_MODE_MCLASS | UC_MODE_V8 | UC_MODE_LITTLE_ENDIAN | UC_MODE_BIG_ENDIAN,

and then in the code do:
if (mode & ~UC_MODE_ARM_MASK)

**Comment by aquynh** [comment]
yes,  that was a mistake. please remove UC_MODE_BIG_ENDIAN.

you can add the mask somewhere, such as `include/uc_priv.h`

**Comment by aquynh** [comment]
Solved, thanks.
