### ISSUE TITLE
ARM and THUMB interchange

### ISSUE THREAD

**Issue by xorstream** [unicorn-engine/unicorn#391]
ARM and THUMB modes are not mutually exclusive modes, it is very common for the mode to dynamically change during execution. Therefore it doesn't make sense to set them as a static mode in uc_open.

There are a probably few ways the mode changes but one of the most common is to branch via the BX instruction to an odd address to change to thumb mode or an even address for arm mode. When in thumb mode the bit value 0x20 is set in the processor status register (PSR), when in arm mode this bit is cleared. Quick link to PSR bits: https://en.wikipedia.org/wiki/ARM_architecture#Registers

Based on this information it makes sense to allow the arm/thumb mode to be set dynamically either via PC manipulation or PSR manipulation. It is much less of a headache to just set a bit in the status register instead of specially handling the "odd bit" of an instruction address in all cases.

Therefore I suggest that we allow dynamic selection of arm/thumb mode via the "thumb mode" bit in the status register. And that we do away with the static mode values for ARM/THUMB.

Note that the above suggestion does not currently work! If I emulate ARM code that jumps to THUMB mode, then I reposition the PC to some arm code and alter the PSR value to specify to run in ARM mode, it will still change itself back into thumb mode when it executes the instruction, thereby failing to execute the arm instruction.

**Comment by aquynh** [comment]
> ARM and THUMB modes are not mutually exclusive modes, 

at initialize time (when we call `uc_open()`), it should be either ARM or THUMB, not both. this is what i mean when i said "mutually exclusive".

**Comment by aquynh** [comment]
at the run-time, we will get the mode dynamically, but do not rely on the initialized mode. so there is no problem with the value UC_MODE_ARM=0.

**Comment by aquynh** [comment]
for the last part of your issues, we need a  newmechanism (via a new API `uc_option()` as i once mentioned) to set the ARM mode at runtime.

**Comment by xorstream** [comment]
If you are setting up an emulator for non-trivial cases you will likely call uc_open() to create your ARM emulator before you know whether the code you plan to execute is ARM or THUMB. I guess if there was a dynamic option for setting the mode, ie via some uc_option() function, then you could just select ARM during uc_open() and then dynamically alter the value to ARM/THUMB later via a call to uc_option() before then starting execution.

Btw do you consider the fact that I cannot change the value of the PSR via uc_reg_write() to be a bug?

**Comment by aquynh** [comment]
yes, uc_option() should solve your problem, so you can dynamically change the mode at runtime.

yes, cannot change any register is a bug. please send PR to fix that.

**Comment by aquynh** [comment]
@xorstream, i need to ask you something. can you please email me?

thanks

**Comment by esanfelix** [comment]
Hello,

Is there any progress on this issue? I have a similar case to @xorstream in which I am loading an ELF file into memory and taking the architecture to initialize a Unicorn object. I only know the address to emulate later on (from user-provided input) and would like to change at runtime without having to create a new unicorn instance each time, re-map memory segments, etc.

**Comment by esanfelix** [comment]
By the way, I looked into how to implement this but I am not very familiar with Unicorn/qemu internals. For this case specifically (ARM vs THUMB) wouldn't it be better to just set the thumb mode based on the PC?

I've tried doing this in unicorn_arm.c:

```
--- a/qemu/target-arm/unicorn_arm.c
+++ b/qemu/target-arm/unicorn_arm.c
@@ -106,8 +106,9 @@ int arm_reg_write(struct uc_struct *uc, unsigned int *regs, void* const* vals, i
                     break;
                 //case UC_ARM_REG_PC:
                 case UC_ARM_REG_R15:
-                    ARM_CPU(uc, mycpu)->env.pc = *(uint32_t *)value;
-                    ARM_CPU(uc, mycpu)->env.regs[15] = *(uint32_t *)value;
+                    ARM_CPU(uc, mycpu)->env.pc = (*(uint32_t *)value & ~1);
+                    ARM_CPU(uc, mycpu)->env.thumb = (*(uint32_t *)value & 1);
+                    ARM_CPU(uc, mycpu)->env.regs[15] = (*(uint32_t *)value & ~1);
                     // force to quit execution and flush TB
                     uc->quit_request = true;
                     uc_emu_stop(uc);
```

Which basically masks off the last bit of the PC when it's being set, and sets thumb mode to whatever value the last bit of the requested pc had.

This seems to work fine for me... so if you think it's a valid solution I could send a pull request.

**Comment by esanfelix** [comment]
@aquynh any thoughts on this?

**Comment by aquynh** [comment]
yes this sounds reasonable to me. anybody objects this move, that we should automatically change from ARM mode to Thumb mode at `uc_emu_start()` if PC address is odd?

**Comment by petmac** [comment]
No real objections, but the user could specify Thumb mode with uc_open and then enter ARM mode accidentally with uc_emu_start.

**Comment by aquynh** [comment]
yes, obviously if we choose to go with this, the actual mode will be adjusted when emulation start, so the mode specified at uc_open() time does not really matter.

**Comment by xorstream** [comment]
Thumb and Arm are often intimately tied. And from what I recall thumb
universally uses a PC target with lowest bit set.

I do know that the current setup treats them as way too seperate, so
something is needed to easily handle the easy change between them. ( and
while you're at it possible leave provisions for jazzelle and other
extensions too?)

**Comment by aquynh** [comment]
@esanfelix, can you send in a PR to implement this?

**Comment by esanfelix** [comment]
Done. I tested this and it seems ok, but I am not intimately familiar with Unicorn/Qemu internals so it might be good to perform additional tests...

**Comment by danghvu** [comment]
No issue since then, close this for now, please feel free to open a new issue or reopen if needed.
