### ISSUE TITLE
Proposed new function wrappers related to uc_hook_add

### ISSUE THREAD

**Issue by mike820324** [unicorn-engine/unicorn#394]
Hi I want to proposed some new function wrappers that is related to  `uc_hook_add`.

What I'm concern is that when someone is very new to unicorn, and try to use uc_hook_add, he/she can not fully understand how to use `uc_hook_add` when reading the header file. 

Moreover, since  `uc_hook_add` is using `va_XXX` to get the optional parameters, and  the formal parameter of the callback field is a type of `void*`, when the user is passing the wrong type for optinal parameters or wrong prototype of callback, the compiler will not generate any warning. 
In worse case, the user may encounter some undefined behavior when running the code.

As a result, I would like to proposed some new function wrappers that are related to `uc_hook_add`.
For example, take `UC_HOOK_CODE` type for instance, we can add a new function with the following format.

``` c
uc_err uc_hook_add_code(uc_engine* uc, uc_hook* hh, uc_cb_hookcode_t cb, void* userdata, uint64_t begin, uint64_t end)
{
    return uc_hook_add(uc, hh, UC_HOOK_CODE, cb, userdata, begin, end);
}
```

The same approach can also applied to the other uc hook type.

The advantage of this approach is that when someone is using the function with the wrong type, the compiler will generate warning, so that he/she may have a chance to take a look at what is going wrong.

And since it is just a simple wrapper function, if the compiler optimization flag is on, it may be inlined into the code, so the performance impact would be pretty low.

Tks

**Comment by lunixbochs** [comment]
The new API will have mandatory begin/end I think, so the only special case will be HOOK_INSN.

**Comment by aquynh** [comment]
yes, the docs in unicorn.h is incomplete. please send pull requests to fix what you found.

at the moment Ryan is working to make all the hooks support begin/end, see https://github.com/unicorn-engine/unicorn/pull/378. 

after this is merged, we will do this to HOOK_INSN too (thus break compatibility). so eventually, all the hooks will have the same prototype.

**Comment by mike820324** [comment]
No problem, should I send a pull request after #378 is merged?

**Comment by aquynh** [comment]
you should not wait, but send PR for the branch "hook" at https://github.com/unicorn-engine/unicorn/tree/hook.
this branch will be merged soon, after some more reviews.

**Comment by danghvu** [comment]
PR is merged, no comment so close this for now. Please feel free to open a new one or reopen if needed.
