### ISSUE TITLE
ARM backend w/m68k broken by -mthumb

### ISSUE THREAD

**Issue by petevine** [unicorn-engine/unicorn#398]
I'm having [this](https://github.com/lunixbochs/usercorn/issues/129) issue using usercorn but it seems it's rather related to the engine itself. 
Which compiler optimizations should be avoided, if any? (`gcc 4.9.3`)

What should I do to get you more useful debugging info? 

**EDIT, TL;DR**
`gcc 4.9.3` configured for mode=thumb miscompiles? UC `w/m68k` target enabled.

**Comment by aquynh** [comment]
can you can debug your issue and find out what is wrong?

if you are using the latest Unicorn, the bug is at this line:

    target_ulong tlb_addr = env->tlb_table[mmu_idx][index].ADDR_READ;

can you insert a **printf** before this line to print out the values of `addr` & `index`, to see why segfault happens?

**Comment by petevine** [comment]
Sure, just give me the preferred formatting options.

**Comment by aquynh** [comment]
just get those numbers in hex format

**Comment by petevine** [comment]
After a fresh checkout, I can't reproduce any longer even with the same optimizations.

The only change from last time (to shorten compilation time) was to use just `x86` and `arm` arches. Either some bugs was fixed between now and then or the above made a difference.

**Comment by petevine** [comment]
Grr, I was right unfortunately, a full optimized build crashes again (that's why I gave it a full bill of health initially).

I'm not going to do another build today, maybe tomorrow. Hopefully, I've given you some ideas.

**Comment by petevine** [comment]
Ok, as I said, I'll revisit the issue soon. It's clear though having everything linked in breaks something - that's already a nice discovery.

**Comment by petevine** [comment]
Tried again today and it seems not using any optimizations definitely solves this issue.
Optimizations don't hurt minimal builds but do full ones. It looks like this then:

```shell
./usercorn ~/Downloads/busybox-x86_64 cal
0X0.0000000400194P-1022
 addr 0x458128
 index 0X0.00000607FED9P-1022
 addr 0x654128
 index 0X0.00000004A0566P-1022
 addr 0x598128
Segmentation fault
````

These are the flags present in my environment:  '-mcpu=cortex-a5 -O3 -fomit-frame-pointer -fipa-pta`
and the lines added:
```c
        printf("%A\n addr ", addr);
        printf("%p\n index ", env->tlb_table[index]);
````

There's a warning that might be related:
````
/tmp/unicorn/qemu/target-m68k/translate.c: In function ‘disas_tas’:
/tmp/unicorn/qemu/m68k.h:2909:29: warning: ‘addr’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 #define tcg_gen_qemu_st_i32 tcg_gen_qemu_st_i32_m68k
                             ^
/tmp/unicorn/qemu/target-m68k/translate.c:1535:10: note: ‘addr’ was declared here
     TCGv addr;
          ^
````

**Comment by farmdve** [comment]
You are printing stuff incorrectly.

for printing addr you need to use %llx, %A is for double type. And then you are printing a pointer, not index itself, you should use 

```c
        printf("addr %llX\n ", addr);
        printf("index %08X\n", index);
```

**Comment by petevine** [comment]
Thanks for the corrections; I'll recompile and paste the correct output (if UC still crashes).

**Comment by petevine** [comment]
With all optimizations in apart from `-fipa-pta`, we're still getting the crash:

```shell
./usercorn ~/Downloads/busybox-x86_64 cal
addr 400194
 index 00000000
 addr 607FED70
 index 000000FE
 addr 4A0566
 index 000000A0
Segmentation fault
````

I'm going to leave `m68k` out to see if that uninitialized variable matters - in qemu it lives in a separate binary so maybe it doesn't make a difference over there.

**Comment by petevine** [comment]
That's probabably it: `x86 + m68k` -> crash
                                  `all - m68k` -> no crash

Back to you guys!

**Comment by farmdve** [comment]
Might I ask what compiler version you are using? When I compile all arches on Windows I definitely don't get that warning.

**Comment by petevine** [comment]
It's gcc 4.9, I've added the info to the original post.

**Comment by farmdve** [comment]
So I am assuming you are running this directly on ARM on a Raspberry Pi?

**Comment by petevine** [comment]
Indeed, on an Odroid C1 to be precise.

**Comment by petevine** [comment]
Did I get the terminology wrong re arm backend? I thought it meant arm host more or less.

**Comment by petevine** [comment]
Leaving just the -mcpu and -O1/2 flags was still crashing, but the trace got longer:

````
 addr 400194
 index 00000000
 addr 607FED70
 index 000000FE
 addr 4A0566
 index 000000A0
 addr 607FF000
 index 000000FF
 addr 4B45E4
 index 000000B4
Segmentation fault
````

Eventually I got this funny idea: `-mthumb` is normally being passed implicitly (configured at gcc build time) so I tried passing `-marm` explicitly and that was finally it!

I guess it could be gcc bug material if only I could create a test case...

**Comment by farmdve** [comment]
I was going to suggest a different compiler as I had the small thought it could be a compiler bug, they are unlikely, but not impossible or unheard of.

**Comment by petevine** [comment]
Yeah, the x86 versions - the situation is somewhat less mature on arm.

**Comment by petevine** [comment]
This is exactly my system info as reported by usercorn ;)

`Linux sercorn 13.0-24-generic mal copy of Linux minding my business 64 GNU/Linux`
