### ISSUE TITLE
unicorn swallows all qemu pthread errors

### ISSUE THREAD

**Issue by williballenthin** [unicorn-engine/unicorn#400]
Since 2f297bd, unicorn has swallowed all qemu pthread errors. `qemu-thread-posix.c:error_exit` ([link](https://github.com/unicorn-engine/unicorn/blob/master/qemu/util/qemu-thread-posix.c#L32)) does not log nor abort on any errors. I can't tell from 2f297bd if this is intended, or left over from developing the fix to #237, otherwise I'd simply send a PR uncommenting those two lines. 

I recommend that unicorn at least log errors. I spent a long time today tracking down a deadlock whose source was ultimately swallowed by `error_exit` (on Linux/pthreads, you have to make `uc_emu_*` calls from the same thread). On the upside, I became more familiar with the internals of unicorn! Still, I could have solved my bug quicker if unicorn either died horribly at the source, or logged a message that something was up.

**Comment by aquynh** [comment]
as a framework, we should not print out to the console like error_exit() did. that is why those 2 lines were commented out.

to solve this problem, what we need to do is to propagate this pthread error back to `uc_emu_start()`, so it can exit properly (probably with a new error code) when pthread errors happen.

pull request to do this is welcome!

**Comment by aquynh** [comment]
anyway, printing out the error is still better than nothing, so please send a PR to uncomment those 2 lines. thanks.

**Comment by aquynh** [comment]
i added the idea of propagating pthread errors back to `uc_emu_start()` to TODO list: https://github.com/unicorn-engine/unicorn/wiki/TODO

thanks.

**Comment by aquynh** [comment]
among the below functions, can list all functions causing the exit error?

```
qemu_mutex_init(QemuMutex *mutex);
qemu_mutex_destroy(QemuMutex *mutex);
qemu_mutex_lock(QemuMutex *mutex);
qemu_cond_init(QemuCond *cond);
qemu_cond_destroy(QemuCond *cond);
qemu_cond_signal(QemuCond *cond);
qemu_cond_broadcast(QemuCond *cond);
qemu_cond_wait(QemuCond *cond, QemuMutex *mutex);
qemu_sem_init(QemuSemaphore *sem, int init);
qemu_sem_post(QemuSemaphore *sem);
qemu_sem_wait(QemuSemaphore *sem);
qemu_sem_destroy(QemuSemaphore *sem);
```

**Comment by williballenthin** [comment]
The error I encountered was in `qemu_cond_wait`, since I was using the API incorrectly from different threads. I suspect I'd receive similar errors in different APIs with a different call sequence or thread scheduling (Go was transparently rescheduling logical threads to different pthreads).

**Comment by egberts** [comment]
Thought I got that until I discovered the timeout in uc_emu_start().
