### ISSUE TITLE
mem_map addres limit

### ISSUE THREAD

**Issue by McLovi9** [unicorn-engine/unicorn#410]
Hi, question is there any max-limit for mem_map address ? I just tried to emulate ARM code starting from imagebase 0xF0000000 but unicorn failed to start. Works fine if I start from lower address, though.

**Comment by aquynh** [comment]
this looks like a bug. please send in a testcase in a pull request (put it under `tests/` directory)

**Comment by McLovi9** [comment]
sorry my bad, I was mapping large imagebase 0xF0000000 with incorrect (huge) memory size and it was crashing unicorn.

**Comment by aquynh** [comment]
Oh no, no input should crash Unicorn. This is a bug, so please send your testcase in so we can fix the issuse

**Comment by McLovi9** [comment]
OK done, I added the testcase. I'm not sure maybe this bug is already fixed I don't have the latest unicorn on Windows only the one from download "Python module for Windows"  so I get a crash but on Linux I just checked the latest version from github its OK message "Emulate ARM code ERROR: No memory available or memory not present (UC_ERR_NOMEM)" no crash.
