### ISSUE TITLE
Understanding GUI Potential

### ISSUE THREAD

**Issue by cforger** [unicorn-engine/unicorn#412]
One item I'm unsure of is if it is/would be possible to have GUI output for the emulator.

I know the version of qemu in the tree is streamlined, but unsure at this stage if that was stripped, or it's on the roadmap.

**Comment by lunixbochs** [comment]
UI is provided by hardware/bios, which is totally feasible for someone to build/integrate back on top of Unicorn.

I don't think it's Unicorn's job to provide the UI anymore. It's Unicorn's job to give you enough hooks into the CPU to emulate text mode graphics hardware and draw the UI itself.

**Comment by cforger** [comment]
Yes, I see GUI as secondary to the stepping/testing hooks, but it could be useful at times.

I take it from your statement that there is no option for BIOS or more specifically UEFI in Unicorn at the moment?

**Comment by lunixbochs** [comment]
Unicorn is a CPU emulator. The OS, memory layout, hardware, etc is all up to the user.

**Comment by aquynh** [comment]
Unicorn is a framework, so i dont see how GUI fits into the picture.

**Comment by aquynh** [comment]
Something like https://github.com/hugsy/cemu can make you happy.

**Comment by darvin** [comment]
or something like https://github.com/dbalsom/martypc
