### ISSUE TITLE
Zero BB length returned if BB ends in invalid instruction

### ISSUE THREAD

**Issue by eqv** [unicorn-engine/unicorn#414]
Test case added in #413

**Comment by aquynh** [comment]
actually it is legal for the BB size to be 0, for example when the BB is too big, so the size is unknown: https://github.com/unicorn-engine/unicorn/commit/39d38568717220e629e404b6f5f3b856d87e04a7. and apparently this is what happens with your testcase.

documentation is still lacking to make users aware of this situation. if you can, please send a PR to document this in `include/unicorn/unicorn.h`.

thanks.

**Comment by eqv** [comment]
I'm not sure what documentation would be needed since include/unicorn/unicorn.h does contain a note that 0 is returned on blocks with unknown size.

**Comment by aquynh** [comment]
ok then this is not really an issue.
