### ISSUE TITLE
uc_reg_read/write incorrect for x86 segment registers

### ISSUE THREAD

**Issue by cseagle** [unicorn-engine/unicorn#417]
Why does uc_reg_read/write for segment registers (CS, DS, SS, ...) assign to/read from the base field in 32/64 bit modes? Example:

                case UC_X86_REG_GS:
                    X86_CPU(uc, mycpu)->env.segs[R_GS].base = *(uint32_t *)value;
                    break;
These registers never hold a base or limit. They are selectors used to index into a descriptor table.

**Comment by Nukem9** [comment]
Probably a hack because the LDT/GDT was never implemented? It's been there since the first commits. PR https://github.com/unicorn-engine/unicorn/pull/216 switched it to full addr width.

**Comment by cseagle** [comment]
Correct, in testing, LDT/GDT do not seem to be implemented or consulted by the underlying software mmu. I suppose segmented 32 bit code can't be properly emulated then.

**Comment by aquynh** [comment]
yes this is a bug. please send pull request to fix it, thanks.

**Comment by feliam** [comment]
yup.  
lsl, lar, mov gs, ax are not emulated correctly with the current scheme.
Also a really easy anti-unicorn/ unicorn-detector right there.
Need a way to set segment base, limit and perms. Not just in env->segs. As some instructions consult the actual tables.
fix fix fiiIIIiiiIIIIiiIIIIiiiiIIIIiiiIIiiiIIIiiiIIIIIIIIIIIIIIIIIIIiiiiiiiiiiiiiiiiix
http://x86.renejeschke.de/html/file_module_x86_id_162.html
http://x86.renejeschke.de/html/file_module_x86_id_149.html

**Comment by aquynh** [comment]
this was already fixed, thanks.
