### ISSUE TITLE
mips n32,n64 ABI registers

### ISSUE THREAD

**Issue by michalmalik** [unicorn-engine/unicorn#418]
As per http://man7.org/linux/man-pages/man2/syscall.2.html

MIPS o32 ABI uses A0, A1, A2, A3 registers and stack to pass arguments to syscalls.

MIPS n32,n64 additionally uses A4 and A5, which are not handled by Unicorn AFAIK.

EDIT: http://www.linux-mips.org/pub/linux/mips/doc/ABI/MIPS-N32-ABI-Handbook.pdf

**Comment by aquynh** [comment]
could you please send a PR to put a testcase for this under `tests/`?
