### ISSUE TITLE
x86-32: emulation exits on `mov gs, eax`

### ISSUE THREAD

**Issue by lunixbochs** [unicorn-engine/unicorn#421]
A simple test case could not reproduce this.

A complex case can be reproduced with Usercorn and [busybox-i686](https://busybox.net/downloads/binaries/)

    ./usercorn -v -trace busybox-i686

              + block @0x80f7b00
                0x80f7b00: 8b44240c mov eax, dword ptr [esp + 0xc]
                0x80f7b04: 8d04c503000000 lea eax, dword ptr [eax*8 + 3]  eax 0xffffffff 
                0x80f7b0b:     8ee8 mov gs, eax           eax 0xfffffffb 
              R 0x607ff84c: ffffffff                                     [....                    ] R 

              + block @0x80f7b0b
                0x80f7b0b:     8ee8 mov gs, eax

After this emulation simply exits with UC_ERR_OK. Also note the instruction hook was called twice (I checked and the same behavior happens with Unicorn before the hook refactor).

**Comment by Nukem9** [comment]
`mov <segment reg>, <reg>` can generate a fault/exception when a segment (`reg` value) is not present. Is unicorn exiting because of it?

**Comment by lunixbochs** [comment]
LDT/GDT aren't properly set up as per #406 so that's not surprising.

There's no error or callback produced by Unicorn, however. It just stops emulation.

**Comment by aquynh** [comment]
why cant we write a testcase for this issue?

**Comment by lunixbochs** [comment]
I wasn't entirely sure what was happening so my basic test didn't reproduce it, but @Nukem9 was right. If EAX is a huge number (like `~0`), Unicorn just quietly stops emulation.

**Comment by cseagle** [comment]
The emulation quits for me with no error indication on any attempt to mov into any segment register with virtually any value

for example:

mov ax, 7
mov gs, ax     ; fails regardless of the segment register
mov eax, 0x11111111

never reaches the last mov

I don't think the emulation ever gets out of helper_load_seg (target-i386/seg_helper.c) which probably hits one of many possible calls to raise_exception_err.

helper_load_seg wants to reference an ldt or gdt, but none is ever configured when the emulation is started.

**Comment by cseagle** [comment]
FWIW, with my proposed pull that allows setting IDTR, GDTR, etc, it is possible to map and initialize a gdt before uc_emu_start such that valid segment selectors do not cause exits for things like 'mov gs, ax'

It does not eliminate the issue that GPFs should be communicated in some way either by implementing a GPF related hook or setting appropriate state within uc_engine that can be tested for on return from uc_emu_start. Certainly uc_emu_start should not return success in these cases.

**Comment by farmdve** [comment]
@cseagle 

Hooking exceptions(of all kinds) was something I had planned to do. They are simply a must, especially if we want to emulate Windows SEH.

**Comment by egberts** [comment]
In my VM memory region snapshot, my TIB is located in 0x7FFDF000, but I have no way to configure the FS register, no?  Writing `0x00007FFD` to `UC_X86_REG_FS` isn't cutting it (due to missing `0x000F000` part).

What we really need is a `WRFSBASE` capability during setup.

**Comment by cseagle** [comment]
You need to setup a GDT, which unicorn allows you to do. Then you can set fs to the appropriate selector value in the GDT, this should cause the appropriate segment cache values to get updated from the gdt. There is no way to set fs base directly in the x86 architecture other than configuring an appropriate GDT/LDT entry.

**Comment by aquynh** [comment]
@edgarmb, see related conversations at https://github.com/unicorn-engine/unicorn/issues/417, https://github.com/unicorn-engine/unicorn/issues/406. @cseagle had some PRs on this at https://github.com/unicorn-engine/unicorn/pull/422 & https://github.com/unicorn-engine/unicorn/pull/416

the question on how to setup GDT/IDT/LDT comes up again and again. if anybody has a good example code, please consider sending a PR to include it into `samples/` or `bindings/`, so others can learn from it. thanks.

**Comment by aquynh** [comment]
sorry @edgarmb, i mean @egberts for this coversation  :-)

**Comment by sashs** [comment]
Hi,

I tried to create a GDT. Maybe I did something wrong, but if you look at the example I am trying to read gs:[0x18]. A segment is set to 0x5000. I added a UC_HOOK_MEM_READ_UNMAPPED hook to print which address is accessed. Shouldn't unicorn access the address 0x5018 instead of 0x18?

This is the output of the script:
`python2 gdt.py 
0x18L
Traceback (most recent call last):
  File "gdt.py", line 84, in <module>
    uc.emu_start(CODE_ADDR, CODE_ADDR+CODE_SIZE)
  File "/usr/lib/python2.7/site-packages/unicorn/unicorn.py", line 214, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory read (UC_ERR_READ_UNMAPPED)
`

This is the script:
https://gist.github.com/sashs/8dad80b0fbe20b4e0e98

**Comment by lunixbochs** [comment]
I think your GDT bits are wrong.

It looks like you have this:

    `[base 24:31][flags 0:8][limit 16:19][access 0:7][base 0:23][limit 0:15]`

According to http://wiki.osdev.org/GDT_Tutorial#Filling_the_table

    target[0] = limit & 0xff
    target[1] = (limit >> 8) & 0xff
    target[6] = (limit >> 16 & 0xf)

**Comment by lunixbochs** [comment]
I added a print to the `UC_X86_REG_GDTR` reg_write case in `qemu/target-i386/unicorn.c` and it printed `base=0x3000 limit=0x0`

**Comment by sashs** [comment]
Hey,

I think my code means the same.


Am 18.03.16 um 17:22 schrieb Ryan Hileman:
> I think your GDT bits are wrong.
> 
> It looks like you have this:
> 
> |`[base 24:31][flags 0:8][limit 16:19][access 0:7][base 0:23][limit 0:15]` |
> 
> According to http://wiki.osdev.org/GDT_Tutorial#Filling_the_table
> 
> |target[0] = limit & 0xff target[1] = (limit >> 8) & 0xff target[6] =
> (limit >> 16 & 0xf) |
>

**Comment by lunixbochs** [comment]
Posting that was a mistake, when writing it up I compared more closely and decided I was wrong, but accidentally hit close and comment before I erased it.

**Comment by aquynh** [comment]
looking at this. for some reasons, the segment is not taken into consideration for the virtual address, hence the core refers to a totally different part of memory.

**Comment by aquynh** [comment]
@sashs, would you send a PR to put your testcase under tests/? just a note: the line https://gist.github.com/sashs/8dad80b0fbe20b4e0e98#file-gdt-py-L83 should be rewritten to:

    uc.emu_start(CODE_ADDR, CODE_ADDR+len(CODE))

thanks.

**Comment by aquynh** [comment]
also, can you make this Python code to use regress module, like other testcases under tests/regress/?

thanks.

**Comment by danghvu** [comment]
https://github.com/unicorn-engine/unicorn/commit/9cdca5a32b52c028c6889ae42334cf53dd6b6cc2

This patch will raise an exception since the interrupt is not handled. Any comment ?

**Comment by danghvu** [comment]
Fixed in latest commit to master.
