### ISSUE TITLE
Threads that share MMU.

### ISSUE THREAD

**Issue by farmdve** [unicorn-engine/unicorn#425]
In the future it would be nice if we could somehow start threads that execute different code, but share the MMU. Basically, to emulate threading.

Do you think would be possible to implement?

**Comment by aquynh** [comment]
dont really get your idea. Can you elaborate?

**Comment by farmdve** [comment]
Executing more threads simultaneously that access the same MMU. So we can emulate multi-threaded code, e.g by interpcepting calls to pthread_create or CreateThread(on Windows).

**Comment by lunixbochs** [comment]
see also #142
