### ISSUE TITLE
Minor: suggesting python2 or python3?

### ISSUE THREAD

**Issue by cyphunk** [unicorn-engine/unicorn#429]
COMPILE.txt says python2 is required but some code suggests using python3.

see:

https://github.com/unicorn-engine/unicorn/blob/master/COMPILE.TXT#L110

https://github.com/unicorn-engine/unicorn/commit/44fa4e29e70743a98d67a800feed596f4909fd12

**Comment by aquynh** [comment]
you need Python2 just to compile, but then the Python binding should support both Python2 & Python3 (so your Python code can work regardless of Python version on your machine)
