### ISSUE TITLE
uc_hook_add() API: add begin, end arguments to all hook types

### ISSUE THREAD

**Issue by aquynh** [unicorn-engine/unicorn#430]
i added begin & end arguments to uc_hook_add() API. so from now on, all type of hooks support memory range. this change is pushed to a new branch "hook" at https://github.com/unicorn-engine/unicorn/tree/hook. the related commit is https://github.com/unicorn-engine/unicorn/commit/a7a1dcc66128801d1ef82e992a6cc4ff10fcce5d.

NOTE:
- the API version is bumped from 0.9 to 1.0 after this change (https://github.com/unicorn-engine/unicorn/commit/0822c0af85c6623a4c905a3673c233c0ccfbf98a).
- Python binding is already updated in this branch.
- @lunixbochs , @cseagle, @enkomio, @xorstream: please update your bindings accordingly. i will merge this branch to "master" soon.

**Comment by aquynh** [comment]
i merged the "hook" branch into the "master" branch.

note that for now all the bindings, except Python, break  because of the change of the `uc_hook_add()` API. existing Python apps do not need to be rewritten because this upgrade does not break compatibility, but C apps must be modified a little bit to properly call `uc_hook_add()`.

**Comment by crowell** [comment]
@aquynh can you update @radare for similar breaking changes in the future

**Comment by aquynh** [comment]
What do you mean by updating @radare?

**Comment by crowell** [comment]
I mean let us know in your alert so we aren't broken when the API changes

**Comment by aquynh** [comment]
Yes, will do.
