### ISSUE TITLE
push ss; pop ss causes execution to stop?

### ISSUE THREAD

**Issue by farmdve** [unicorn-engine/unicorn#433]
Executing push ss pop ss causes the emulator to stop. Any ideas why?

Essentially:

push ss
pop ss
mov eax, 1 <--- never reached.

I am on latest commit.

**Comment by JonathonReinhart** [comment]
Loading `ss` on a real CPU involves a whole slew of checks. Perhaps another qemu exception being swallowed?

**Comment by farmdve** [comment]
If we're in ring0 mode, then pop ss should execute regardless.

**Comment by JonathonReinhart** [comment]
From the `POP` instruction in the Intel Vol 2. document:

> If the destination operand is one of the segment registers DS, ES, FS, GS, or SS, the value loaded into the register must be a valid segment selector. In protected mode, popping a segment selector into a segment register automatically causes the descriptor information associated with that segment selector to be loaded into the hidden (shadow) part of the segment register and causes the selector and the descriptor information to be validated (see the “Operation” section below).

**Operation**
```
PROTECTED MODE OR COMPATIBILITY MODE;

IF SS is loaded;
THEN
    IF segment selector is NULL
        THEN #GP(0);
    FI;
    IF segment selector index is outside descriptor table limits
        or segment selector's RPL  ≠ CPL
        or segment is not a writable data segment
        or DPL ≠ CPL
            THEN #GP(selector);
    FI;
    IF segment not marked present
        THEN #SS(selector);
        ELSE
            SS ← segment selector;
            SS ← segment descriptor;
    FI;
FI;
```

I agree this shouldn't cause Unicorn to break, I'm just saying it's much more complex than popping into a GPR.

**Comment by aquynh** [comment]
@farmdve, can you send in a testcase? thanks

**Comment by cseagle** [comment]
It's likely that if you have not configured a GDT/LDT that pop ss will fail as the popped value will not be a valid selector and you will fail the same checks that cause the emulator to bail on things like mov es, ax as discussed in another thread

**Comment by aquynh** [comment]
yes, we need a testcase to test the fix, so emulation can quit with a proper error code.
