### ISSUE TITLE
HOOK_BLOCK being called twice at beginning

### ISSUE THREAD

**Issue by egberts** [unicorn-engine/unicorn#436]
Is this normal to be seeing HOOK_BLOCK being called twice in the beginning of the test code?

I've been seeing that with `test_tb_x86.c`.  And I see who is writing the `helper_uc_tracecode` twice for HOOK_BLOCK.

**Comment by aquynh** [comment]
perhaps that is 2 separate callbacks: one for BLOCK hook, one for CODE instruction hook (the first instruction of block)?

if indeed there are 2 calls on a block with BLOCK type, then this is a bug.

**Comment by egberts** [comment]
In `test_tb_x86.c`, hooks are fired in the following order between just `hook_code32` and `hook_block`:

1. `hook_block`
2. `hook_code32`
3. `hook_block (same address as above)`

Does this pertain to regeneration by any chance (due to this self-modification?)

**Comment by aquynh** [comment]
ah if i remember correctly this is expected: the block is regenerated due to self-modifying-code, then block callback is called once more. i suppose this is acceptable.

**Comment by egberts** [comment]
Thank you.  That design is clearer now.  It's got the 'updated' code.

**Comment by egberts** [comment]
ADDENDUM:  Unfortunately, I'm "pulling a sweater yarn" there.   The updated 2nd HOOK_BLOCK picked up the old `0x51` value again after fixing the exec.c for correct ordering of "pc.mem" then code regeneration.  This issue remains closed.

**Comment by egberts** [comment]
ADDENDUM:  Unfortunately, I'm "pulling a sweater yarn" there.   The updated 2nd HOOK_BLOCK picked up the old `0x51` value again after fixing the exec.c for correct ordering of "pc.mem" then code regeneration.  This is a function of me swapping the `tb_invalidate` vs. updating "pc.mem" logic inside `notdirty_mem_write`/exec.c in response to issue #364.

It was a case of execution of my "supposedy-flip-flop-fixed" emulator performing TB regeneration TWICE but with different "pc.ram" memory content (in my case, XOR'd of 0x41 on 0x10 gives me a flip-flop of 0x51 and 0x10).

Now, I know why (in the master branch) that there is a delay in updating the "pc.ram" by doing `tb_invalidate_fast` FIRSTLY... 

I see HOOK_CODE being called twice.... I think the callbacks should be something like:

1. HOOK_BLOCK (pc=1)
2. HOOK_CODE (pc=1)  # Oopps, self-modifying codes!
3. HOOK_BLOCK (pc= don't care)
4. HOOK_CODE (pc=2)  <---- proper stepping

And not the current:
1. HOOK_BLOCK (pc=1)
2. HOOK_CODE (pc=1)
3. HOOK_BLOCK(pc=1)
4. HOOK_CODE(pc=1)
5. HOOK_CODE(pc=2)

But seriously (and ignoring my fix to keep focus on Unicorn's master branch), this "appearance of" emulating the same instruction twice, @farmdve @JonathonReinhart?

**Comment by egberts** [comment]
Now that I think about it...  we're actually emulate-executing all the codes that had been found in the newly generated TB, no?

**Comment by farmdve** [comment]
There are particular instructions that are jitted in a way that exit the translation block and re-enter it(essentially emulating a loop). This causes hooks to be called again. But these instructions are very specific(like those with REP/REPZ prefix).

**Comment by egberts** [comment]
Merged it with #437
