### ISSUE TITLE
HOOK_CODE shows same instruction again after both TB regeneration and HOOK_BLOCK

### ISSUE THREAD

**Issue by egberts** [unicorn-engine/unicorn#437]
Assuming that HOOK_CODE shows the assembly instruction of what it was BEFORE its microcode emulation....

If a TCG regeneration occurs due to its emulated instruction modifying something within the same code-based TranslationBlock, why is it essential to show another HOOK_CODE again for the same instruction after its TG regeneration?

I mean, if the instruction modified itself, I don't mind seeing yet another HOOK_BLOCK showing this new assembly sequence, but we shouldn't be executing that new opcode sequence but instead to continue emulation based on old RIP/PC advancing over its old instruction.

Currently, the behavior is like this:
1. HOOK_BLOCK (pc=1)
2. HOOK_CODE (pc=1)  # Oops, self-modifying codes!
3. HOOK_BLOCK(pc=1) # We see the code change
4. HOOK_CODE(pc=1) # Uh?
5. HOOK_CODE(pc=2)

Ideally, callbacks should be something like:
1. HOOK_BLOCK (pc=1)
2. HOOK_CODE (pc=1) # Oops, self-modifying codes!
3. HOOK_BLOCK (pc=1) # at least you'll get the opportunity to see any code change at pc=1
4. HOOK_CODE (pc=2) <---- proper stepping

At the moment, #364 is seeing this unrelated issue where pc=3 is changed, not pc=1 as described here.

**Comment by egberts** [comment]
Identified the culprit of double HOOK_CODE

So, we're calling `gen_uc_tracecode(HOOK_CODE)` three times for the same XOR instruction in `test_tb_x86.c`:
1. During start_thread, (first-time initialization of TranslationBlock)

So far, so good....  Now 
2. During TB regeneration due to `tb_invalidate_fast` (ie., XOR self-modify code in same TB)
3. And again in `tb_gen_code()` in `tb_invalidate_phys_page_range` triggered by `current_tb_modified`.

**Comment by egberts** [comment]
Yeah.... a simple fix with a snippet of a single-liner in [`tb_invalidate_phys_page_range()` in `qemu/translate-all.c`](https://github.com/unicorn-engine/unicorn/blob/master/qemu/translate-all.c#L1204):

```c
    if (current_tb == tb &&
        (current_tb->cflags & CF_COUNT_MASK) != 1) {
    /* If we are modifying the current TB, we must stop
    its execution. We could be more precise by checking
    that the modification is after the current PC, but it
    would require a specialized function to partially
    restore the CPU state */
    current_tb_modified = 1;
    // self-modifying code will restore state from TB
    cpu_restore_state_from_tb(cpu, current_tb, cpu->mem_io_pc);
    cpu_get_tb_cpu_state(env, &current_pc, &current_cs_base,
                                         &current_flags);
    current_tb_modified = 0;    //   This is the new line....
}
```

**Comment by egberts** [comment]
My new fix for unrelated issue #364 is working better now.

**Comment by egberts** [comment]
The different between cpu_restore_state_from_tbl and gen_tbl_code is the reused of the same TB buffer.

If a self-modify code made an in-situ instruction LONGER, overflow will happen during cpu_state_from_tbl at the end of the TB block.

**Comment by egberts** [comment]
Gawd.... I would love to insert comments into the code to make things more permanent....

**Comment by aquynh** [comment]
are you sure? i believe that callbacks is only executed before the instruction really runs. 
this is a bug only if callbacks do not go together with instruction execution.

**Comment by egberts** [comment]
I think you might be right... 

This was thought to be an issue on the basis that the HOOKs are being shown twice but not before knowingly that emulator was doing all relevant HOOK_CODEs before actually executing an instruction: 
* first time as a nominal HOOK_CODE, but no emulation being done yet then,
* second time after a new TranslationBlock was overwritten (not created as a new one)
THEN, microcode emulation began.

Closing this issue.

**Comment by egberts** [comment]
Now actively fixing this...

**Comment by egberts** [comment]
I believe I can account for that discrepancies in the executed instruction count (is that still a problem for you as it is for me now as I'm now using today's GIT master (75e5fb4).?)

In the same [`test_tb_x86.c`](https://github.com/unicorn-engine/unicorn/blob/master/tests/unit/test_tb_x86.c) (in tests/unit), this discrepancy is **NOW** found *EARLIER* in the test code whose opcode sequence being UC_HOOK_CODE'd twice in Unicorn.  (Tweaked `test_tb_x86.c` RIP/PC to start earlier at 0x60000021).

```asm
; ECX=0x5ffffff8
; memory being modified at 0x60000028 (self-modify scenario)
60000021 304130    xor    [ecx+0x30], al
60000024 41        inc    ecx
```

The TCG buffer had two UC_HOOK_CODE_IDX entries for helper to process on before emulating the `xor` opcode.

It APPEARS to be specific to indexed-operand. This is well-documented in #364 (and is also happening before the  problematic #364 issue and GDT-related issues). This is now my primary focus.

My plan is to reconfirm how many UC_HOOK_CODE_IDX were initially created at start_thread() and then how many were there after that indexed-operand-to-its-own-memory-block-triggered TCG regeneration.  Earlier recollection shows one at initial start_thread(), and two at regeneration due to self-modify of its own resident code block condition.

**Comment by aquynh** [comment]
if there are 2 callbacks installed at the same place, perhaps we failed to take this into account that there was already one callback, thus installed it once more when SMC happens?

**Comment by egberts** [comment]
Yes, there are two helper callbacks found; one generated by `cpu_restore_state_from_tb` and other was by `tb_gen_code` all within the same 0x60000021 address.  Will get traceback of each one of those created this UC_HOOK_CODE_IDX helper callbacks.

**Comment by egberts** [comment]
yes.  I see that `gen_uc_tracecode` got called twice before emulation started for the same address location `0x60000021`.

I've outputted two tracebacks and first listed the common tracebacks between the two.
```gdb
  0x0000000000596d04 in gen_intermediate_code_internal_x86_64 (
    gen_opc_cc_op=0x7ffff780db7c "", cpu=0x14f7af40, tb=0x7ffff59b8010, 
    search_pc=0x0) at /git/unicorn-master/qemu/target-i386/translate.c:8398
  0x000000000059706a in gen_intermediate_code_x86_64 (env=0x14f83170, 
    tb=0x7ffff59b8010) at /git/unicorn-master/qemu/target-i386/translate.c:8478
  0x0000000000413794 in cpu_x86_gen_code (env=0x14f83170, tb=0x7ffff59b8010, 
    gen_code_size_ptr=0x7ffff59b6c54)
    at /git/unicorn-master/qemu/translate-all.c:179
  0x0000000000414de7 in tb_gen_code_x86_64 (cpu=0x14f7af40, pc=0x60000021, 
    cs_base=0x0, flags=0x4000f4, cflags=0x0)
    at /git/unicorn-master/qemu/translate-all.c:1100
  0x0000000000440c54 in tb_find_slow_x86_64 (env=0x14f83170, pc=0x60000021, 
    cs_base=0x0, flags=0x4000f4) at /git/unicorn-master/qemu/cpu-exec.c:370
  0x0000000000440e01 in tb_find_fast_x86_64 (env=0x14f83170)
    at /git/unicorn-master/qemu/cpu-exec.c:398
  0x0000000000440690 in cpu_x86_exec (uc=0x14f61230, env=0x14f83170)
    at /git/unicorn-master/qemu/cpu-exec.c:204
  0x0000000000437c86 in tcg_cpu_exec_x86_64 (uc=0x14f61230, env=0x14f83170)
    at /git/unicorn-master/qemu/cpus.c:214
  0x0000000000437d2f in tcg_exec_all_x86_64 (uc=0x14f61230)
    at /git/unicorn-master/qemu/cpus.c:235
 0x0000000000437a56 in qemu_tcg_cpu_thread_fn_x86_64 (arg=0x14f7af40)
    at /git/unicorn-master/qemu/cpus.c:160
 0x00000031f5607a51 in start_thread () from /lib64/libpthread.so.0
 0x00000031f52e893d in clone () from /lib64/libc.so.6
```
Then listed out the traceback of each that had only one thing in common:
1. First gen_uc_tracecode()
```gdb
#0  gen_uc_tracecode (tcg_ctx=0x7ffff77b8010, size=0xf8f8f8f8, type=0x3, 
    uc=0x14f61230, pc=0x60000021) at /git/unicorn-master/qemu/tcg/tcg-op.h:31
#1  0x0000000000596d04 in gen_intermediate_code_internal_x86_64 (
    gen_opc_cc_op=0x7ffff780db7c "", cpu=0x14f7af40, tb=0x7ffff59b8010, 
    search_pc=0x0) at /git/unicorn-master/qemu/target-i386/translate.c:8398
```
2. Second gen_uc_tracecode()
```gdb
#0  gen_uc_tracecode (tcg_ctx=0x7ffff77b8010, size=0xf1f1f1f1, type=0x2, 
    uc=0x14f61230, pc=0x60000021) at /git/unicorn-master/qemu/tcg/tcg-op.h:31
#1  0x00000000005893d3 in disas_insn (env=0x14f83170, s=0x7ffff59b6a00, 
    pc_start=0x60000021)
    at /git/unicorn-master/qemu/target-i386/translate.c:4786
#2  0x0000000000596e68 in gen_intermediate_code_internal_x86_64 (
    gen_opc_cc_op=0x7ffff780db7c "", cpu=0x14f7af40, tb=0x7ffff59b8010, 
    search_pc=0x0) at /git/unicorn-master/qemu/target-i386/translate.c:8429
```

**Comment by egberts** [comment]
Something happened to make gen_uc_tracecode() twice for the same 0x60000021

* [ /git/unicorn-master/qemu/target-i386/translate.c:8398](https://github.com/unicorn-engine/unicorn/blob/master/qemu/target-i386/translate.c#L8398)
and
* [/git/unicorn-master/qemu/target-i386/translate.c:8429](https://github.com/unicorn-engine/unicorn/blob/master/qemu/target-i386/translate.c#L8429)

**Comment by egberts** [comment]
In the `gen_intermediate_code_internal()`, we have 
* a pre-emptive "generate a tracecode" hidden in `disas_insn()` based on TB block being tainted and 
* a post-processing "generate a tracecode" at the end of TB generation (also based on TB block being tainted).

**Comment by egberts** [comment]
Shall I clone the `test_tb_x86.c` into a new `test_regen_1_hookcode.c`, or something for the above?

**Comment by egberts** [comment]
All I did was proved above that there is exactly one HOOK_CODE at start_thread() time....which is correct.

Moving on toward subsequential HOOK_CODE generations.

**Comment by egberts** [comment]
(sigh)... Fast forwarding to emulation stage, I got two of the following (same address location, same opcode, same tracecode type:
`gen_uc_tracecode(..., type=0x2,...,pc=0x60000021)`....

Common traceback between the two is literally identical:
```gdb
#0  gen_uc_tracecode (tcg_ctx=0x7ffff77b8010, size=0xf1f1f1f1, type=0x2, 
    uc=0x14f61230, pc=0x60000021) at /git/unicorn-master/qemu/tcg/tcg-op.h:31
#1  0x00000000005893d3 in disas_insn (env=0x14f83170, s=0x7ffff59b6210, 
    pc_start=0x60000021)
    at /git/unicorn-master/qemu/target-i386/translate.c:4786
#2  0x0000000000596e68 in gen_intermediate_code_internal_x86_64 (
    gen_opc_cc_op=0x7ffff780db7c "", cpu=0x14f7af40, tb=0x7ffff59b8010, 
    search_pc=0x1) at /git/unicorn-master/qemu/target-i386/translate.c:8429
#3  0x00000000005970e6 in gen_intermediate_code_pc_x86_64 (env=0x14f83170, 
    tb=0x7ffff59b8010) at /git/unicorn-master/qemu/target-i386/translate.c:8485
#4  0x0000000000413909 in cpu_restore_state_from_tb_x86_64 (cpu=0x14f7af40, 
    tb=0x7ffff59b8010, searched_pc=0xf5ed5c)
    at /git/unicorn-master/qemu/translate-all.c:242
#5  0x0000000000415177 in tb_invalidate_phys_page_range_x86_64 (uc=0x14f61230, 
    start=0x28, end=0x29, is_cpu_write_access=0x1)
    at /git/unicorn-master/qemu/translate-all.c:1214
#6  0x0000000000415494 in tb_invalidate_phys_page_fast_x86_64 (uc=0x14f61230, 
    start=0x28, len=0x1) at /git/unicorn-master/qemu/translate-all.c:1414
#7  0x000000000043d233 in notdirty_mem_write (uc=0x14f61230, opaque=0x0, 
    ram_addr=0x28, val=0x41, size=0x1) at /git/unicorn-master/qemu/exec.c:1389
#8  0x0000000000430f3d in memory_region_write_accessor_x86_64 (mr=0x14f61558, 
    addr=0x28, value=0x7ffff59b6678, size=0x1, shift=0x0, mask=0xff)
    at /git/unicorn-master/qemu/memory.c:511
---Type <return> to continue, or q <return> to quit---
#9  0x000000000043108a in access_with_adjusted_size_x86_64 (addr=0x28, 
    value=0x7ffff59b6678, size=0x1, access_size_min=0x1, access_size_max=0x4, 
    access=0x430ea7 <memory_region_write_accessor_x86_64 at
/git/unicorn-master/qemu/memory.c:504>, mr=0x14f61558) at
/git/unicorn-master/qemu/memory.c:548
#10 0x0000000000434397 in memory_region_dispatch_write_x86_64 (mr=0x14f61558, 
    addr=0x28, data=0x41, size=0x1) at /git/unicorn-master/qemu/memory.c:1182
#11 0x00000000004375cf in io_mem_write_x86_64 (mr=0x14f61558, addr=0x28, 
    val=0x41, size=0x1) at /git/unicorn-master/qemu/memory.c:1888
#12 0x0000000000423009 in io_writeb_x86_64 (env=0x14f83170, physaddr=0x28, 
    val=0x41, addr=0x60000028, retaddr=0xf5ed5c)
    at /git/unicorn-master/qemu/softmmu_template.h:633
#13 0x00000000004237d8 in helper_ret_stb_mmu_x86_64 (env=0x14f83170, 
    addr=0x60000028, val=0x41, mmu_idx=0x2, retaddr=0xf5ed5c)
    at /git/unicorn-master/qemu/softmmu_template.h:739
#14 0x0000000000f5ed5e in static_code_gen_buffer ()
#15 0x000000e900f5f7e4 in ?? ()
#16 0x00007ffff77b8010 in ?? ()
#17 0x0000000000f5f809 in static_code_gen_buffer ()
#18 0x99c7c681a8036e99 in ?? ()
#19 0x00007ffff59b68b0 in ?? ()
```

As a result, I'm still seeing two `helper_ret_stb_mmu_x86_64()` for `xor` opcode

I'm going to assume that generation of these gen_uc_tracecode() is being inserted AFTER the original gen_uc_tracecode()... so going back to pre-emulation TB setup stage.

**Comment by egberts** [comment]
Managed to start using `systemtap` with `para-callgraph.stp` feature to get a sequential list of all functions called within Unicorn/QEMU.

http://gnu.wildebeest.org/blog/mjw/2008/11/27/observe-systemtap-and-oprofile-updates/

**Comment by egberts** [comment]
Output of `systemtap` and `test_tb_x86`.... (WARNING: 4MB text file)

[callgraph-uninema-stp.txt](https://github.com/unicorn-engine/unicorn/files/172895/callgraph-uninema-stp.txt)

**Comment by egberts** [comment]
There is a correct number of `gen_uc_tracecode(...,type=0x2,...,addr=0x60000021)`.
1.  during start_thread
2.  during self-modify of its own memory region

The extra insertion of gen_uc_tracecode() occurred during.... regeneration of TB upon seeing an indexed operand modifying its own instruction block region (dirty TB).  It would appear all within the same `0x60000021` address that:

a. `gen_intermediate_code_internal_x86_64(...,search_pc=0x1)` was creating a new TB and added the `gen_uc_tracecode(type=0x2, addr=0x60000021)`
b. didn't detect an existing UC_HOOK_CODE_IDX in the just-newly-created TB before `gen_intermediate_code_internal_x86_64(...,search_pc=0x1)` wrote an extra `gen_uc_tracecode`.

**Comment by egberts** [comment]
Refining the gdb breakpoint for `test_tb_x86` to:
```gdb
break gen_uc_tracecode if pc == 0x60000021
```
I show that there are three `gen_uc_tracecode` being evoked having `type = 0x2`:
1. During `start_thread()`
And the second and last were created during helpers from static_code_gen_buffer (is that called SMC in Unicorn parlance?) under `tb_invalidate_phys_page_range` but in two different places within that function:

Second traceback is partially listed as:
```
#0  gen_uc_tracecode (tcg_ctx=0x7ffff77b8010, size=0xf1f1f1f1, type=0x2, 
    uc=0x14f61230, pc=0x60000021) at /git/unicorn-master/qemu/tcg/tcg-op.h:35
#1  0x00000000005893d3 in disas_insn (env=0x14f83170, s=0x7ffff59b6210, 
    pc_start=0x60000021)
    at /git/unicorn-master/qemu/target-i386/translate.c:4786
#2  0x0000000000596e68 in gen_intermediate_code_internal_x86_64 (
    gen_opc_cc_op=0x7ffff780db7c "", cpu=0x14f7af40, tb=0x7ffff59b8010, 
    search_pc=0x1) at /git/unicorn-master/qemu/target-i386/translate.c:8429
#3  0x00000000005970e6 in gen_intermediate_code_pc_x86_64 (env=0x14f83170, 
    tb=0x7ffff59b8010) at /git/unicorn-master/qemu/target-i386/translate.c:8485
#4  0x0000000000413909 in cpu_restore_state_from_tb_x86_64 (cpu=0x14f7af40, 
    tb=0x7ffff59b8010, searched_pc=0xf5ee1e)
    at /git/unicorn-master/qemu/translate-all.c:242
#5  0x0000000000415177 in tb_invalidate_phys_page_range_x86_64 (uc=0x14f61230, 
    start=0x28, end=0x29, is_cpu_write_access=0x1)
    at /git/unicorn-master/qemu/translate-all.c:1214
```
We can see that `cpu_restore_state_from_tb` had kicked in.

Third traceback is partially listed as:
```gdb
#0  gen_uc_tracecode (tcg_ctx=0x7ffff77b8010, size=0xf1f1f1f1, type=0x2, $
    uc=0x14f61230, pc=0x60000021) at /git/unicorn-master/qemu/tcg/tcg-op.h:35$
#1  0x00000000005893d3 in disas_insn (env=0x14f83170, s=0x7ffff59b61a0, $
    pc_start=0x60000021)$
    at /git/unicorn-master/qemu/target-i386/translate.c:4786$
#2  0x0000000000596e68 in gen_intermediate_code_internal_x86_64 ($
    gen_opc_cc_op=0x7ffff780db7c "", cpu=0x14f7af40, tb=0x7ffff59b8088, $
    search_pc=0x0) at /git/unicorn-master/qemu/target-i386/translate.c:8429$
#3  0x000000000059706a in gen_intermediate_code_x86_64 (env=0x14f83170, $
    tb=0x7ffff59b8088) at /git/unicorn-master/qemu/target-i386/translate.c:8478$
#4  0x0000000000413794 in cpu_x86_gen_code (env=0x14f83170, tb=0x7ffff59b8088, $
    gen_code_size_ptr=0x7ffff59b63f4)$
    at /git/unicorn-master/qemu/translate-all.c:179$
#5  0x0000000000414de7 in tb_gen_code_x86_64 (cpu=0x14f7af40, pc=0x60000021, $
    cs_base=0x0, flags=0x4000f4, cflags=0x1)$
    at /git/unicorn-master/qemu/translate-all.c:1100$
#6  0x00000000004152b4 in tb_invalidate_phys_page_range_x86_64 (uc=0x14f61230, $
    start=0x28, end=0x29, is_cpu_write_access=0x1)$
    at /git/unicorn-master/qemu/translate-all.c:1251$
```
Common traceback found between 2nd and 3rd `gen_uc_tracecode`:
```gdb
XX  0x0000000000415494 in tb_invalidate_phys_page_fast_x86_64 (uc=0x14f61230, 
    start=0x28, len=0x1) at /git/unicorn-master/qemu/translate-all.c:1414
XX  0x000000000043d233 in notdirty_mem_write (uc=0x14f61230, opaque=0x0, 
    ram_addr=0x28, val=0x10, size=0x1) at /git/unicorn-master/qemu/exec.c:1389
XX  0x0000000000430f3d in memory_region_write_accessor_x86_64 (mr=0x14f61558, 
    addr=0x28, value=0x7ffff59b6678, size=0x1, shift=0x0, mask=0xff)
    at /git/unicorn-master/qemu/memory.c:511
XX  0x000000000043108a in access_with_adjusted_size_x86_64 (addr=0x28, 
    value=0x7ffff59b6678, size=0x1, access_size_min=0x1, access_size_max=0x4, 
    access=0x430ea7 <memory_region_write_accessor_x86_64 at
/git/unicorn-master/qemu/memory.c:504>, mr=0x14f61558) at
/git/unicorn-master/qemu/memory.c:548
XX 0x0000000000434397 in memory_region_dispatch_write_x86_64 (mr=0x14f61558, 
    addr=0x28, data=0x10, size=0x1) at /git/unicorn-master/qemu/memory.c:1182
XX 0x00000000004375cf in io_mem_write_x86_64 (mr=0x14f61558, addr=0x28, 
    val=0x10, size=0x1) at /git/unicorn-master/qemu/memory.c:1888
XX 0x0000000000423009 in io_writeb_x86_64 (env=0x14f83170, physaddr=0x28, 
    val=0x10, addr=0x60000028, retaddr=0xf5ee1e)
    at /git/unicorn-master/qemu/softmmu_template.h:633
XX 0x00000000004237d8 in helper_ret_stb_mmu_x86_64 (env=0x14f83170, 
    addr=0x60000028, val=0x10, mmu_idx=0x2, retaddr=0xf5ee1e)
    at /git/unicorn-master/qemu/softmmu_template.h:739
XX 0x0000000000f5ee20 in static_code_gen_buffer ()
```
We can see that `tb_gen_code` was used to regenerate the TB with an extra UC_HOOK_CODE_IDX.

**Comment by egberts** [comment]
Seems to me like there some kind of fragment scoping of design issue as to where to singularly place the UC_HOOK_CODE... within the same RIP/PC address and not generate multiple `gen_uc_tracecode`.

**Comment by egberts** [comment]
Curious...

Is "helpers from static_code_gen_buffer" equivalent to "SMC" parlance?

**Comment by egberts** [comment]
You can get there the fastest to just before the double `gen_uc_tracecode()` using 
```sh
gdb ./test_tb_x86
```
Execute GDB breaks
```gdb
break gen_uc_tracecode if pc == 0x60000021
break notdirty_mem_write if ram_addr == 0x28
run
# breaks at gen_uc_tracecode
continue
# breaks at notdirty_mem_write
next
next
# go down into tb_invalidate_phys_page_range_x86_64
step
record
```
Then rock back and forth between the two gen_uc_tracecode using 'next' and 'reverse-next'
between the double `gen_uc_tracecode()` activities at that function level.

**Comment by aquynh** [comment]
regarding your question on having new testcase, please feel free to do that, or just extend the existing testcase. it is OK to have more than one test in the same file (like test_tb_x86.c)

you seem to go very far on this issue. can you summarize the bug, and propose the solution yet?

**Comment by egberts** [comment]
I'm now confident that this is a Unicorn design issue and not that those of a QEMU.  I will need to study the TB structure and its actual content between those two points and formulate some alternatives for you to decide (I've already tried a few failed knee-jerk fixes).

It is important to fix this because it is impacting self-modify scenarios with premature double-modification of indexed/indirect code space.

**Comment by aquynh** [comment]
yes, it is highly possible that this is the bug of Unicorn. i dont think it is as serious as "design" issue, however. thanks for pushing so hard, and look forward to your solution.

**Comment by egberts** [comment]
It is definitely within the TARGET_HAS_PRECISE_SMC define region and related to synchronizing how many TB regeneration we want within the same address location.

**Comment by egberts** [comment]
And learning what we want from `cpu_restore_state_from_tb()`.

**Comment by egberts** [comment]
Fixing this, most likely will fix #364 .

**Comment by egberts** [comment]
There you go.

It is also a vulnerability.  

Too bad, I didn't fix this in time.

https://bugs.chromium.org/p/project-zero/issues/detail?id=1122

**Comment by aquynh** [comment]
Lets wait to see how Qemu fixes this upstream, then we port the fix over.

**Comment by aquynh** [comment]
not sure that Qemu will fix this bug, so if you come up with a patch, please do pull req.
