### ISSUE TITLE
(x86) Virtual memory outside of unicorn-mapped memory

### ISSUE THREAD

**Issue by Ramirez57** [unicorn-engine/unicorn#439]
Not sure if this is intended behavior.

When trying to access virtual memory whose address is not mapped by Unicorn, the memory access fails and Unicorn reports so (error code 6/7/8). This happens even when the guest code has mapped this memory using pages.

I believe it's not an error on my part as moving the page within address ranges that Unicorn has mapped will work as expected.

**Comment by aquynh** [comment]
can you please provide a testcase for this issue, so we can confirm and test the fix?

thanks.

**Comment by aquynh** [comment]
you can look at the testcases under tests/regress (Python) or test/unit (C code) for reference.

**Comment by aquynh** [comment]
the testcase provided by the PR https://github.com/unicorn-engine/unicorn/pull/441 is very interesting. a quick glance, and perhaps this is because the machine is not in a proper mode yet (we need protected + paging mode enable). maybe we can skip setting up GDT in this case?

**Comment by Ramirez57** [comment]
I do not set up protected mode in the test cases, but paging works anyway. Even in protected mode, the results are the same.
