### ISSUE TITLE
Windows Environment, setup of.

### ISSUE THREAD

**Issue by egberts** [unicorn-engine/unicorn#442]
Documentation:

I found this document to be the best in setting up a Windows Environment using Unicorn.

http://yaokai.org/dl/avar2007/data/11_Design%20of%20X86%20Emulator%20for%20Generic%20Unpacking/Design%20of%20X86%20Emulator%20for%20Generic%20Unpacking.pdf

**Comment by halsten** [comment]
I don't see any relevance between the article and the title of this issue.
