### ISSUE TITLE
(x86-32) FS always 0 due to missing CPU ENV

### ISSUE THREAD

**Issue by egberts** [unicorn-engine/unicorn#443]
For x86-32 mode, I see that the value of FS has been given a zero value...always, regardless of poking the FS via `uc_mem_write()`.

To recap, If I want to do the following instruction after performing:
```c
uint32_t r_fs = 0x7ff7;
uc_mem_write(uc, UC_X86_REG_FS, &r_fs):
```
then emulate:
```
60000153 64A130000000     mov  eax, fs:[0x30]
```
The debugging the microcode operation for the instruction above shows this:
```
  helper_le_ldul_mmu_x86_64(env, addr=0x30, mmu_idx=0x2, retaddr)
```
Whoa, addr is already at `0x30`, when it should have been FS:[0x30], or something like `0x7ff70030`.   I know that the default of FS is at CPU reset state, which is FS=0x00.  But I was curious as to where do I set this 'FS' register for use at either micro-operation/code-regeneration time...

The FS value retrieval during emulation certainly isn't done with the desired 0x7FF70030 physical range value during micro-operation, so going back to TB generation (TCG) which is during the `disas_insn()` loop, TCG wrote out the following steps:
* `0x30` = insn_get()
* tcg_gen_movi_tl(tcg_ctx, cpu_A0=0x17, offset_addr=0x30)
 * wm 0x00000017
 * wm 0x00000030
* gen_add_A0_ds_seg(s)
 * gen_op_addl_A0_seg(s, reg=0x4)
  * tcg_gen_ld_i64_x86_64(s, ret=0x18, arg2=0x0, offset=0x128)
   * Get direct segment value of FS and put into tmp[18] 
   * wm 0x00000018
   * wm 0x00000000   # WUT?  Supposed to be 0x7FF7?
   * wm 0x00000128
 * tcg_gen_add_i64_x86_64(s, ret=0x17, arg1=0x17, arg2=0x18)
  * wm INDEX_op_add_i64
  * wm 0x00000017
  * wm 0x00000017
  * wm 0x00000018
 * tcg_gen_andi_i64_x86_64(s, ret=0x17, arg1=0x17, arg2=0xfffffff)
  * wm 0x00000017
  * wm 0x00000017
  * wm 0x00000017

It is self-evident that the retrieval of the value FS during TCG/TB generation is being done during `tcg_gen_ld_i64_x86_64(s, ret=0x18, arg2=0x0, offset=0x128)`, so traceback is given below: 

```
#0  tcg_gen_ld_i64_x86_64 (s=0x7ffff77b8010, ret=0x18, arg2=0x0, offset=0x128)
    at /tmp/unicorn-master/qemu/tcg/tcg-op.h:1060
#1  0x000000000057a3ac in gen_op_addl_A0_seg (s=0x7ffff59b6a00, reg=0x4)
    at /tmp/unicorn-master/qemu/target-i386/translate.c:465
#2  0x0000000000580cc1 in gen_add_A0_ds_seg (s=0x7ffff59b6a00)
    at /tmp/unicorn-master/qemu/target-i386/translate.c:2348
#3  0x000000000058d814 in disas_insn (env=0x14f83310, s=0x7ffff59b6a00, 
    pc_start=0x60000153)
    at /tmp/unicorn-master/qemu/target-i386/translate.c:5865
#4  0x0000000000596e1b in gen_intermediate_code_internal_x86_64 (
    gen_opc_cc_op=0x7ffff780db7c "", cpu=0x14f7b0e0, tb=0x7ffff59b8088, 
    search_pc=0x0) at /tmp/unicorn-master/qemu/target-i386/translate.c:8417
#5  0x000000000059701d in gen_intermediate_code_x86_64 (env=0x14f83310, 
    tb=0x7ffff59b8088) at /tmp/unicorn-master/qemu/target-i386/translate.c:8466
#6  0x0000000000413600 in cpu_x86_gen_code (env=0x14f83310, tb=0x7ffff59b8088, 
    gen_code_size_ptr=0x7ffff59b6c54)
    at /tmp/unicorn-master/qemu/translate-all.c:179
#7  0x0000000000414c53 in tb_gen_code_x86_64 (cpu=0x14f7b0e0, pc=0x60000151, 
    cs_base=0x0, flags=0x4000f4, cflags=0x0)
    at /tmp/unicorn-master/qemu/translate-all.c:1100
#8  0x0000000000440b48 in tb_find_slow_x86_64 (env=0x14f83310, pc=0x60000151, 
    cs_base=0x0, flags=0x4000f4) at /tmp/unicorn-master/qemu/cpu-exec.c:370
#9  0x0000000000440cf5 in tb_find_fast_x86_64 (env=0x14f83310)
```
so I stepped into that code and found out that the `tsg_ctx->cpu_env` is `NULL` as denoted in [MAKE_TCGV_PTR(i=0x0)/qemu/tcg/tcg.h:304](https://github.com/unicorn-engine/unicorn/blob/2304bbfc96e85cd9c94e02b4244359b408dafc01/qemu/tcg/tcg.h#L302) as called by [optimize_flags_init() of target-i386/translate.c](https://github.com/unicorn-engine/unicorn/blob/2304bbfc96e85cd9c94e02b4244359b408dafc01/qemu/target-i386/translate.c#L8240) below:

```
#0  MAKE_TCGV_PTR (i=0x0) at /tmp/unicorn-master/qemu/tcg/tcg.h:304
#1  optimize_flags_init (uc=0x14f613c0)
    at /tmp/unicorn-master/qemu/target-i386/translate.c:8234
#2  0x00000000005a1be1 in x86_cpu_initfn (uc=0x14f613c0, obj=0x14f7b0e0, 
    opaque=0x14f613c0) at /tmp/unicorn-master/qemu/target-i386/cpu.c:2411
#3  0x000000000044798b in object_init_with_type (uc=0x14f613c0, 
    obj=0x14f7b0e0, ti=0x14f64ab0) at qom/object.c:310
#4  0x000000000044795e in object_init_with_type (uc=0x14f613c0, 
    obj=0x14f7b0e0, ti=0x14f64d10) at qom/object.c:306
#5  0x0000000000447ba8 in object_initialize_with_type (uc=0x14f613c0, 
    data=0x14f7b0e0, size=0x10f90, type=0x14f64d10) at qom/object.c:340
#6  0x00000000004480b1 in object_new_with_type (uc=0x14f613c0, type=0x14f64d10)
    at qom/object.c:426
#7  0x0000000000448128 in object_new (uc=0x14f613c0, 
    typename=0x14f64ea0 "qemu64-x86_64-cpu") at qom/object.c:436
#8  0x000000000059fff7 in cpu_x86_create (uc=0x14f613c0, 
    cpu_model=0xb7d3a0 "qemu64", errp=0x7fffffffe338)
    at /tmp/unicorn-master/qemu/target-i386/cpu.c:1698
#9  0x0000000000412dc8 in pc_new_cpu (uc=0x14f613c0, 
    cpu_model=0xb7d3a0 "qemu64", apic_id=0x0, errp=0x7fffffffe388)
    at /tmp/unicorn-master/qemu/hw/i386/pc.c:100
#10 0x0000000000412ef9 in pc_cpus_init (uc=0x14f613c0, 
    cpu_model=0xb7d3a0 "qemu64") at /tmp/unicorn-master/qemu/hw/i386/pc.c:132
```
We cannot set the value of FS register for this particular `mov` instruction.

Are we supposed to provide our own `tcg_ctx->cpu_env` sometime after the `uc_open()`?

**Comment by aquynh** [comment]
have you setup the GDT yet?

**Comment by egberts** [comment]
Trying... Dearth of example.

**Comment by egberts** [comment]
> Current QEMU limitations:
>
> * Limited x86-64 support.
> * IPC syscalls are missing.
> * **The x86 segment limits and access rights are not tested at every memory access (yet). Hopefully, very few OSes seem to rely on that for normal use.** 

Source: http://qemu.weilnetz.de/qemu-tech.html#intro_005fx86_005femulation

**Comment by aquynh** [comment]
that is ok, we should find and fix all the remaining issues :-)

**Comment by egberts** [comment]
> Current QEMU limitations:
>
> * Limited x86-64 support.
> * IPC syscalls are missing.
> * The x86 segment limits and access rights are not tested at every memory access (yet). Hopefully, very few OSes seem to rely on that for normal use. 

Source: http://qemu.weilnetz.de/qemu-tech.html#intro_005fx86_005femulation
