### ISSUE TITLE
UC_HOOK_MEM_READ_UNMAPPED | UC_HOOK_MEM_WRITE_UNMAPPED hook doesn't give accurate eip

### ISSUE THREAD

**Issue by ohjeongwook** [unicorn-engine/unicorn#460]
Following code always give me wrong address.

	def HookInvalidMemoryAccess(self, uc, access, address, size, value, user_data):
		eip=uc.reg_read(UC_X86_REG_EIP)
		print 'eip: %.8X' % eip

self.MU.hook_add(UC_HOOK_MEM_READ_UNMAPPED | UC_HOOK_MEM_WRITE_UNMAPPED, self.HookInvalidMemoryAccess)

If I add hook code for UC_HOOK_CODE, then it will display correct address. Is that register update issue?

**Comment by aquynh** [comment]
unfortunately, this is not enough to debug. could you please send a pull request to put the full testcase under tests/regress/?

**Comment by ohjeongwook** [comment]
This bug is fixed already - I originally used October release which didn't install memory hook correctly.
