### ISSUE TITLE
Userland instruction tracing with memory access information

### ISSUE THREAD

**Issue by gitttt** [unicorn-engine/unicorn#462]
I would like to run an executable and generate a trace, i.e. I want to record every (userland) instruction that gets executed. In addition, I would like to record if there was a memory read access or write access, together with the info from which address the instruction has read (resp. written to) and what value has been read (resp. written).

Is unicorn the right base to build such a tool? If yes, could you point me to the relevant documentation (or even example code?). I am not sure if it can be done with the qemu monitor (I don't think so) or with the qemu trace functionality (see e.g. https://github.com/qemu/qemu/blob/master/docs/tracing.txt)

Maybe there exists even such a script? I mean, I am probably not the first person to look for such a functionality, right?

Thank you for your help!

**Comment by aquynh** [comment]
you can find some docs here: https://github.com/unicorn-engine/unicorn/tree/master/docs

there is a slides with some technical details: https://github.com/unicorn-engine/unicorn/blob/master/docs/BHUSA2015-unicorn.pdf

finally, reading existing samples is a good way to learn how to code your own tools: https://github.com/unicorn-engine/unicorn/tree/master/samples (for C) and https://github.com/unicorn-engine/unicorn/tree/master/bindings (for Java, dotNet, Go & Python)

**Comment by gitttt** [comment]
So in other words, you think Unicorn is the right framework for the task, i.e. it can provide the information I need?

**Comment by aquynh** [comment]
you might be interested in Usercorn, a very cool application using Unicorn inside for CPU emulation: https://github.com/lunixbochs/usercorn

**Comment by lunixbochs** [comment]
This is exactly what Usercorn provides with `-trace`, though I'm crazy and also writing kernel emulators (so many syscalls are unsupported, and things like `/proc`, `/dev`, ioctls will take even longer), but I'm interested in writing a "native passthrough" kernel backend where most syscalls are blindly passed to your host, which would be able to run most programs as long as you're emulating the same arch/OS as your host.

This would function more like Intel PIN / DynamoRIO, but likely faster.

**Comment by danghvu** [comment]
No more requests from op, close for now, feel free to open a new one or reopen it if needed.
