### ISSUE TITLE
FS register is not used for memory access

### ISSUE THREAD

**Issue by ohjeongwook** [unicorn-engine/unicorn#468]
I'm trying to emulate code that looks like following.

mov ebx, fs:[0x30]

Even when I set fs, it would access 00:30. I commented on the related commit.

https://github.com/unicorn-engine/unicorn/commit/f3dc2522a090e1f8467f5a67571dc3e1bef49786?diff=unified

**Comment by ohjeongwook** [comment]
Created patch: https://github.com/unicorn-engine/unicorn/pull/469

**Comment by ohjeongwook** [comment]
Looks like there is name confusion with these. We might put _BASE postfix to code that can set base for each segment addresses.

**Comment by JonathonReinhart** [comment]
See #422.

**Comment by cseagle** [comment]
See #478 for possible fix

**Comment by zachriggle** [comment]
Setting `fs` just sets the segment *index*.  You need to set up the GDT and LDT -- see `UC_X86_REG_LDTR`.

**Comment by ohjeongwook** [comment]
I'm closing this not to make any confusion. Discussions are all here: https://github.com/unicorn-engine/unicorn/pull/422
