### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by egberts** [unicorn-engine/unicorn#474]
GPLv2 (and implicitly, GPLv2 Only) license makes it difficult to leverage code-contributions made under corporate-funded university research and to permit creation of a commercial product on top of Unicorn library (university professors need grants too).

Is this something we want to consider expanding to, perhaps, something like:
* [Apache 2.0](https://tldrlegal.com/license/apache-license-2.0-%28apache-2.0%29) - This is preferable over ExPat.
 * protects against patent treachery over BSD/OpenBSD license
* [ExPat](https://tldrlegal.com/license/mit-license) (MIT)  
 

A LICENSE file probably would not be easily found if it were not be buried deeply but be placed in its top-level directory.

**Comment by JonathonReinhart** [comment]
This is impossible as QEMU (which unicorn embeds) is [licensed under GPL v2](http://wiki.qemu.org/License).
