### ISSUE TITLE
Cross-compile for Android doesn't work properly

### ISSUE THREAD

**Issue by ThomasKing2014** [unicorn-engine/unicorn#479]
From the compiling parameters in COMPILE.TXT, I think make.sh is same with capstone. But it seems that cross-compile for Android does not work properly. I tried to solve it, but failed. So any suggestions?

**Comment by aquynh** [comment]
so can you confirm that on your machine, this works well for Capstone, but not for Unicorn?

can you post the output here?

**Comment by ThomasKing2014** [comment]
Thanks for your reply. I'm sorry to say that Capstone works well. I do a test as following:

1) I use "NDK=/Users/thomasking/Documents/Android/android-ndk-r10d ./make.sh cross-android arm" to cross-compile Capstone, and it works well. The verbose logs are in "capstone compiling log.txt"
2) I use the same command. The core problem is "arm-linux-androideabi-gcc: command not found". You can find the verbose logs in "unicorn_compiling_log1.txt"
3) I export "arm-linux-androideabi-gcc" cross-compiler and compile again. There are two problems: 1> The linker "ld" cannot open "crtbegin_so.o" object file. 2> Many "invalid character" errors.  The verbose logs are in "unicorn_compiling_log2.txt"

[capstone compiling log.txt](https://github.com/unicorn-engine/unicorn/files/187116/capstone.compiling.log.txt)
[unicorn_compiling_log1.txt](https://github.com/unicorn-engine/unicorn/files/187117/unicorn_compiling_log1.txt)
[unicorn_compiling_log2.txt](https://github.com/unicorn-engine/unicorn/files/187118/unicorn_compiling_log2.txt)

**Comment by mmyydd** [comment]
is there any solution yet ?

**Comment by EgyptianM** [comment]
Is this solved yet?
