### ISSUE TITLE
Question: how to emulate exceptions

### ISSUE THREAD

**Issue by mkravchik** [unicorn-engine/unicorn#504]
Hi,

I have an emulated code that tries to access memory and if it gets a not allocated memory exception - it goes and allocates it. When I emulate it I get the UC_MEM_READ_UNMAPPED error. How do I propagate
 it back to the code so that the flow is preserved?

Thanks a lot!

**Comment by lunixbochs** [comment]
Which arch/OS? Is this usermode or kernel code?

**Comment by mkravchik** [comment]
ARM/iOS, user mode

**Comment by lunixbochs** [comment]
Unicorn is an emulator at the CPU level, but exceptions happen at the OS level. You'll need to figure out how an exception is dispatched to your process (like SIGSEGV) and emulate that.

**Comment by mkravchik** [comment]
Right, had anyone done something similar on any arch/Os?

**Comment by cseagle** [comment]
First, let's assume that your unmapped memory is a segfault and not just a pagefault.

You could mimic windows by having your hook function look up the installed exception handlers via fs:0, then build the exception record on the stack and invoke the installed exception handler which could map the memory.

For Linux you would need to first emulate signal handler installation by hooking the sigaction syscall and remembering the signal handler for SIGSEGV, then in your hook function you would need to setup the signal handler's stack and transfer control to the signal handler. 

Note that in both case, you need a mechanism to trap return from your signal/exception handler and resume normal execution by re-running the faulting instruction.

I have no idea what is involved with iOS.

All non-trivial, but certainly doable.

**Comment by lunixbochs** [comment]
This should be about the same on iOS as Linux. A general solution would hook both `sigaction()` and `signal()`.

In Usercorn, I have a trampoline helper which works like this:

1. I run uc_emu_start() in a loop.
2. Each time it exits, I check a list of trampoline callbacks and execute the next one if available.
3. To trampoline, I invoke a function that calls uc_emu_stop() and pushes a helper function to the trampoline list.
4. The helper function sets up the stack/registers and calls uc_emu_start() at the location I wanted.
5. To handle the return, iirc you can push a return address that's anywhere in unmapped memory, and pass that as your ending address in uc_emu_start().
6. When the trampoline is finished, you restore stack/registers and call the original function.

This is just a tool for calling a subroutine while Unicorn is executing. You'll still need to figure out the syscall and segfault signal handler semantics for your platform.
