### ISSUE TITLE
Dynamic translator buffer issue

### ISSUE THREAD

**Issue by emdel** [unicorn-engine/unicorn#508]
Hi guys,
anyone experienced during the emulation of many instructions the message:

`Could not allocate dynamic translator buffer`

This message is from: qemu/translate-all.c:688
Unfortunately I'm not confident with the Qemu code so before digging into the 'softmmu' I ask 
for advices from the community.
By playing with the parameters of unicorn_code and stack I can reach different points.
From the code I understood I have to allocated at least one page and the granularity is at the page level, and I got always this message.

If it's necessary I can create a testcase.

Thanks a lot,

mariano

**Comment by lunixbochs** [comment]
What's your host arch/OS? How much RAM do you have?

**Comment by emdel** [comment]
Yep sorry. Host OS: Ubuntu; RAM: 8GB; arch: x86_64

**Comment by lunixbochs** [comment]
Can you run under strace and post that?

**Comment by aquynh** [comment]
@emdel, yes please send a testcase so we can test the fix.

**Comment by emdel** [comment]
strace output (around the error):

```
stat("/home/emdel/projects/ropmemu/volatility/plugins/ropmemu/disass.py", {st_mode=S_IFREG|0664, st_size=1919, ...}) = 0
lseek(3, 62967808, SEEK_SET)            = 62967808
read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 4096) = 4096
lseek(3, 62976000, SEEK_SET)            = 62976000
read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 4096) = 4096
lseek(3, 62992384, SEEK_SET)            = 62992384
read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 4096) = 4096
lseek(3, 53821440, SEEK_SET)            = 53821440
read(3, "\376\377\377\17\267\22H\211KX\306CE\2\306CD\1\306C<\1\211S@\351\304\375\377\377f\220"..., 4096) = 4096
write(1, "\t | 0xffffffff8135469f \t| pop rd"..., 35     | 0xffffffff8135469f   | pop rdi 
) = 35
write(1, "\t | 0xffffffff813546a0 \t| ret  \n", 32       | 0xffffffff813546a0   | ret  
) = 32
stat("/home/emdel/projects/ropmemu/volatility/debug.py", {st_mode=S_IFREG|0664, st_size=2769, ...}) = 0
stat("/home/emdel/projects/ropmemu/volatility/plugins/ropemu.py", {st_mode=S_IFREG|0664, st_size=7510, ...}) = 0
stat("/home/emdel/projects/ropmemu/volatility/debug.py", {st_mode=S_IFREG|0664, st_size=2769, ...}) = 0
stat("/home/emdel/projects/ropmemu/volatility/plugins/ropemu.py", {st_mode=S_IFREG|0664, st_size=7510, ...}) = 0
stat("/home/emdel/projects/ropmemu/volatility/debug.py", {st_mode=S_IFREG|0664, st_size=2769, ...}) = 0
stat("/home/emdel/projects/ropmemu/volatility/plugins/ropemu.py", {st_mode=S_IFREG|0664, st_size=7510, ...}) = 0
stat("/home/emdel/projects/ropmemu/volatility/debug.py", {st_mode=S_IFREG|0664, st_size=2769, ...}) = 0
stat("/home/emdel/projects/ropmemu/volatility/plugins/ropmemu/emulator.py", {st_mode=S_IFREG|0664, st_size=11288, ...}) = 0
brk(0x4f5f9000)                         = 0x4f5f9000
mmap(NULL, 8388608, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
write(2, "Could not allocate dynamic trans"..., 45Could not allocate dynamic translator buffer
) = 45
exit_group(1)                           = ?
+++ exited with 1 +++
```

if you need the entire strace output I can store it somewhere and give you the link.

A little bit of context. I'm cleaning the code of my ropmemu framework. During this phase I'm trying to make it more modular and I changed some parts in the code. At the moment, I created an emulator object for every instruction. The instructions comes from the physical memory dump and I interact with it through the Volatility APIs. Before I used only one emulator and I was able to follow the complex chain I dissected.

I opened the issue to discuss with the community about a massive usage of Unicorn. I managed to emulate and generate traces for ~400K instructions fetched from the physical memory dump. Now I'm trying to make my code more modular and easy to include in other projects.

I will create a testcase soon.

Any hint is really appreciated.

mariano

**Comment by lunixbochs** [comment]
Either Python GC isn't triggering or Unicorn isn't freeing the codegen buffer. A C test case would be good here.

**Comment by lunixbochs** [comment]
Okay it's both. Python GC doesn't get called in your loop, even if you `del E` or `del E.mu`. I vote Unicorn's Python bindings should have an explicit `close()` method which `__del__` simply calls.

I verified this calls `uc->release()` properly, but there's still no code to unmap the code_gen_buffer, and when I added some it didn't work.

**Comment by emdel** [comment]
Quick update.
I tried to play a little bit with the code allocating the buffer. But I didn't have any meaningful result.

      qemu/translate_all.c:code_gen_alloc:689
      here it's invoked `size_code_gen_buffer`

If we have a look at this function:
it should be clear that the tb_size is 0, thus the size will be set to: `DEFAULT_CODE_GEN_BUFFER_SIZE`

this is a define and I played with its value. No luck so far.

@lunixbochs I confirm that it looks like __del__ is not invoked at all

**Comment by lunixbochs** [comment]
it's two problems, `__del__` isn't called and even if it is something isn't freed :)

**Comment by emdel** [comment]
Quick update.
I tried to modify on my own the object's refcount (via ctypes) so the counter is zero and `__del__` 
is invoked but it's not a good idea (it segfaults :/).

I managed to invoke `__del__`  by looping on the garbage collector list and call directly the deconstructor method and in this way `uc_close` is called but the bug still persists.

Any hint is appreciated.

**Comment by aquynh** [comment]
i merged the "memleak" branch into "master" branch, which handled some memory leaking issues. can you try again to see that improves now?

**Comment by emdel** [comment]
It improves a little bit, but we end up always with the same error message.
In addition, if you modify my testcase and make it return E (the emulator object), 
and then you call E.mu.__del__(), now you get:

*** Error in `python': double free or corruption (fasttop): 0x0000000002101450 ***
And from my framework something similar:
*** Error in `python': corrupted double-linked list: 0x0000000003a81b70 ***

I managed to have a working environment last night, with the @lunixbochs idea to directly 
call munmap and from my script I was calling __del__ directly to force the deletion. I will 
dig into the changes or revert to the previous state.

**Comment by emdel** [comment]
OK. I confirm I have a kind of working environment (I have to test it extensively) with the commit 8ee696f.
I then added to: qemu/target-i386/unicorn.c

 `22 void x86_release(void *ctx)
  23 {
  24     release_common(ctx);
  25     TCGContext *s = (TCGContext *) ctx;
  26 
  27     
  28     munmap(s->code_gen_buffer, s->code_gen_buffer_size);
  29 
  30     // arch specific
  31     g_free(s->cpu_A0);`

As you can see on line 28 there's the @lunixbochs suggested modification.
From my testcase:

` 76             h = self.init_unicorn(i, sps[index], j)
 77             h.mu.__del__()`

Where h is E from the `init_unicorn` method:1

` 59         E.emu(1)
 60         return E`

And also from my Volatility plugin (by invoking the `__del__` method) it seems to work.

**Comment by aquynh** [comment]
so what is the conclusion? if you need to fix the core for this problem, please send a PR to do so.

thanks.

**Comment by emdel** [comment]
I don't have any real, clean and working solution.
At the moment the best result is what I've explained here: https://github.com/unicorn-engine/unicorn/issues/508#issuecomment-212461572

In this way I can emulate up to 84k gadgets, but I always end up with the dynamic translator buffer issue. I can split the emulation in multiple runs (and it's what I will do), but this is just a workaround to continue my work and the issue is still there.

**Comment by danghvu** [comment]
`munmap(s->code_gen_buffer, s->code_gen_buffer_size);` is in the master branch. Can you check if you are still having issues ?
