### ISSUE TITLE
Trampoline Unicorn on reg_write(EFLAGS)

### ISSUE THREAD

**Issue by lunixbochs** [unicorn-engine/unicorn#512]
Assuming this works, you won't need to insert an EFLAGS sync block after every x86 HOOK_CODE return (and it shouldn't introduce side effects).

**Comment by aquynh** [comment]
this might work. can you send in a PR?

**Comment by lunixbochs** [comment]
Does Unicorn sync registers on emu_stop?

**Comment by aquynh** [comment]
yes it does.
