### ISSUE TITLE
not enough arguments in call to mu.HookAdd

### ISSUE THREAD

**Issue by adesnos** [unicorn-engine/unicorn#515]
I got this error on OSX:

$ go version
go version go1.6 darwin/amd64
$ go run bindings/go/sample.go
\# command-line-arguments
bindings/go/sample.go:22: not enough arguments in call to mu.HookAdd
bindings/go/sample.go:25: not enough arguments in call to mu.HookAdd
bindings/go/sample.go:33: not enough arguments in call to mu.HookAdd
bindings/go/sample.go:48: not enough arguments in call to mu.HookAdd
bindings/go/sample.go:52: not enough arguments in call to mu.HookAdd

**Comment by lunixbochs** [comment]
The sample probably wasn't updated for the begin/end range API change.

**Comment by aquynh** [comment]
i expected that you use default values for those range? like in Python, i set default begin address to 1, and default end address to 0, so the same samples work without having to change after the API modification. can we do that to Go binding, too?

**Comment by lunixbochs** [comment]
Go doesn't have default arguments, just varargs, so I didn't want to do that.

**Comment by aquynh** [comment]
this issue should be solved now thanks to PR https://github.com/unicorn-engine/unicorn/pull/516.

thanks.
