### ISSUE TITLE
I think switching threads between emu_start() calls will break Unicorn

### ISSUE THREAD

**Issue by lunixbochs** [unicorn-engine/unicorn#517]
#400 might be related

`uc->tcg_cpu_thread` should probably be updated on every call to `emu_start()`, which honestly means it should be removed and `cpu->thread` should just always be set to the current thread on `emu_start()`

I have a WIP patch that will probably fix this if/when it lands.

**Comment by JonathonReinhart** [comment]
That seems like an elegant, simple solution. I recall a similar thought crossing my mind when I was looking into the threading issue with the cmocka unit tests.
