### ISSUE TITLE
python bindings fail

### ISSUE THREAD

**Issue by drmint80** [unicorn-engine/unicorn#521]
Hello, I have encountered a problem when import unicorn on python3 version. 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ownager/unicorn-0.9/bindings/python/unicorn/__init__.py", line 4, in <module>
    from unicorn import Uc,uc_version, uc_arch_supported, version_bind, debug, UcError
ImportError: cannot import name 'Uc'

**Comment by aquynh** [comment]
please consider using the lastest Unicorn from Github. be sure to install the binding coming with the core.

    $ ./make.sh
    $ sudo ./make.sh install
    $ cd bindings/python
    $ sudo make install

the report if you still have bugs, thanks.

**Comment by drmint80** [comment]
problem fixed :)  thanks a lot for your help.
