### ISSUE TITLE
Rust bindings

### ISSUE THREAD

**Issue by ekse** [unicorn-engine/unicorn#525]
Hi, 

I hope you don't mind me posting this here, I was too lazy to subscribe to the mailing-list. I have written Rust bindings for the unicorn emulator. It's still a work in progress but most of the features are now supported. 

You can find the project on https://github.com/ekse/unicorn-rs. There are build instructions in the README.md if anyone wants to try it. I would be really glad if you have any type of feedback.

The main design limitation is that I had to define regid in reg_read() and reg_write() as an i32 instead of a Register type as I couldn't find a way in Rust to have a generic type that would support the different types of registers (RegisterX86, RegisterARM, RegisterMIPS). This is inconvenient as the registers have to be explicitly converted with `as i32` when calling these functions, I will try to find a way around this.

Thanks, 
Sébastien

**Comment by aquynh** [comment]
oh this is awesome, thanks for your effort! 

the reason we have int32 as regid type for uc_reg_read()/uc_reg_write() is that this API must support all architectures. it seems there is no better way, though. i believe it is not a big issue to find workaround for your problem.

please keep us updated on your progress.

**Comment by aquynh** [comment]
linked to Unicorn-Rs binding now with this commit https://github.com/unicorn-engine/unicorn/commit/a015ddc348e97c8b6f247f89647b8ffddbaad128

thanks for your great work!

**Comment by ekse** [comment]
Thanks! I added the bindings to crates.io so they are now available from the Rust package manager. Closing this issue as it was just to let you know about the bindings.
