### ISSUE TITLE
Debugging code which uses the Python bindings - pdb breakpoint not triggering

### ISSUE THREAD

**Issue by SeanHeelan** [unicorn-engine/unicorn#527]
Hi guys,

So I have a Python script which uses unicorn and in one of the callbacks there is a bug which I would like to track down via pdb. I run my script via `python3 -m pdb ./myscript.py`, set a breakpoint in my callback (for UC_HOOK_CODE) and then continue the execution. My breakpoint is never hit and the program fails. The code where the breakpoint is is executed however, and I'm certain of that. 

Has anyone else encountered this problem? I'm not familiar with unicorn's internals or the details of the Python bindings so I don't have any real hypothesis for why it's happening. 

Cheers,
Sean

**Comment by aquynh** [comment]
Can you post your code? Without it, it is impossible to verify the bug.

**Comment by SeanHeelan** [comment]
It seemed to be an issue with all scripts I tried, hence the lack of an example. However, it seems the VM I was testing on was running an outdated version and I can't recreate the problem with the latest master branch.
