### ISSUE TITLE
RIP value failure inside UC_HOOK_MEM_UNMAPPED hook?

### ISSUE THREAD

**Issue by gdbinit** [unicorn-engine/unicorn#534]
The following piece of code appears to show a bug inside a unmapped memory events hook:

.text:00000000100002C0 48 89 4C 24 08                          mov     [rsp+arg_0], rcx
.text:00000000100002C5 48 83 EC 28                             sub     rsp, 28h
.text:00000000100002C9 48 8B 42 60                             mov     rax, [rdx+0x60]

The unmapped memory exception will be hit at 0x60 (since RDX is just 0x0), but a RIP uc_read_reg inside the hook (is there any other way to get RIP there) will point to 0x100002C0, which is wrong. I know this because I had set RSP to allocated stack area and the instruction at 0x100002C5 was already executed, since the RSP value is correct from uc_read_reg.

Is this expected behavior or something is wrong tracking RIP inside the hook?

**Comment by aquynh** [comment]
is there any testcase to reproduce this issue? otherwise it is hard to say what is happening: the bug can be in Unicorn, or in your own code.

**Comment by aquynh** [comment]
btw i think there are few samples in the source dealing with UC_HOOK_MEM_UNMAPPED, and none of them has this issue. this is why a testcase is needed for further examination.

**Comment by gdbinit** [comment]
You have the test, case, that piece of code will reproduce the bug.
Just allocate a memory for those bytes, allocate a stack and set RSP and execute the code.
Add a hook for the unmapped memory and retrieve RIP there. It should point to the first instruction instead of the third.

**Comment by aquynh** [comment]
if you can put together a real testcase, and send a PR to put it under `tests/unit/`, i will debug and fix this issue right away. deal? :-)

**Comment by nbsdx** [comment]
@aquynh This bug still exists on master, attached is a unit test with and example code.

[test_x86_rip_bug.c](https://github.com/unicorn-engine/unicorn/files/428616/test_x86_rip_bug.txt)

**Comment by aquynh** [comment]
can you please send a pull request to put this under tests/unit/ directory?

**Comment by nbsdx** [comment]
Submitted.

**Comment by nbsdx** [comment]
I'm kinda looking into this independently; it looks like it might be an issue with the mmu stuff in general. 

I added the following debug statement in `helper_le_ld_name`, and it displayed the bugged EIP value.

```
--- a/qemu/softmmu_template.h
+++ b/qemu/softmmu_template.h
@@ -197,6 +197,9 @@ WORD_TYPE helper_le_ld_name(CPUArchState *env, target_ulong addr, int mmu_idx,
         }
 #else
         error_code = UC_ERR_READ_UNMAPPED;
+#ifdef CPU_NB_REGS // Ensure we're only accessing env->eip for i386/amd64
+        printf("[#] QEMU: EIP: 0x%016lX\n", env->eip);
+#endif
         HOOK_FOREACH(uc, hook, UC_HOOK_MEM_READ_UNMAPPED) {
             if (!HOOK_BOUND_CHECK(hook, addr))
                 continue;
```

Output:
```
nbdsx@ubuntu:~/Code/unicorn-nbsdx/tests/unit$ ./test_x86_rip_bug 
[==========] Running 2 test(s).
[ RUN      ] test_i386
[#] QEMU: EIP: 0x0000000000010000                        ////// Above debug message
De-synced EIP value. 0x00010000 != 0x00010005
ERROR: Invalid memory read (UC_ERR_READ_UNMAPPED)
test_x86_rip_bug.c:134: error: Failure!

[  FAILED  ] test_i386
[ RUN      ] test_amd64
[#] QEMU: EIP: 0x0000000000010000                        ////// Above debug message
De-synced RIP value. 0x0000000000010000 != 0x0000000000010005
ERROR: Invalid memory read (UC_ERR_READ_UNMAPPED)
test_x86_rip_bug.c:159: error: Failure!

[  FAILED  ] test_amd64
[==========] 2 test(s) run.
[  PASSED  ] 0 test(s).
[  FAILED  ] 2 test(s), listed below:
[  FAILED  ] test_i386
[  FAILED  ] test_amd64

 2 FAILED TEST(S)

```

**Comment by nbsdx** [comment]
Sorry for the spam, but it appears that if you register a hook on UC_HOOK_CODE, then the address is correct when reading from the `{,R,E}IP` registers. In uc.c,  `helper_uc_tracecode`, which is only called when you have setup a code hook, the PC is updated.

Now, in qemu/cpu-exec.c, `cpu_tb_exec`, PC is updated after the instruction is executed. It's possible that this logic is incorrect. 

Relative Code:
```
void helper_uc_tracecode(int32_t size, uc_hook_type type, void *handle, int64_t address)
{
    /// [OMIT]
    // sync PC in CPUArchState with address
    if (uc->set_pc) {
        uc->set_pc(uc, address);      // PC is updated
    }
    /// [OMIT]
}

/* Execute a TB, and fix up the CPU state afterwards if necessary */
static tcg_target_ulong cpu_tb_exec(CPUState *cpu, uint8_t *tb_ptr)
{
    /// [OMIT]
    if ((next_tb & TB_EXIT_MASK) > TB_EXIT_IDX1) {
        /* We didn't start executing this TB (eg because the instruction
         * counter hit zero); we must restore the guest PC to the address
         * of the start of the TB.
         */
        CPUClass *cc = CPU_GET_CLASS(env->uc, cpu);
        TranslationBlock *tb = (TranslationBlock *)(next_tb & ~TB_EXIT_MASK);
        if (cc->synchronize_from_tb) {
            // avoid sync twice when helper_uc_tracecode() already did this.
            if (env->uc->emu_counter <= env->uc->emu_count &&
                    !env->uc->stop_request && !env->uc->quit_request)
                cc->synchronize_from_tb(cpu, tb);
        } else {
            assert(cc->set_pc);
            // avoid sync twice when helper_uc_tracecode() already did this.
            if (env->uc->emu_counter <= env->uc->emu_count && !env->uc->quit_request)
                cc->set_pc(cpu, tb->pc);
        }
    }
    /// [OMIT]
}
```
