### ISSUE TITLE
malloc/free functions like for Unicorn memory?

### ISSUE THREAD

**Issue by gdbinit** [unicorn-engine/unicorn#535]
I guess this would be a feature request.
How about adding an API function that will be similar in functionality to malloc/free for Unicorn memory?
uc_mem_map demands a fixed address, so we must decided before where to allocate.
This means that if we want to emulate malloc inside emulation we need to write our own allocator outside to manage the memory to be mapped into the Unicorn emulation "machine".
A Unicorn API that would manage Unicorn memory would be a great feature to add. 
Or am I missing something that already does this?

**Comment by aquynh** [comment]
can you propose the API?

**Comment by lunixbochs** [comment]
I think malloc/free are too high level to implement in Unicorn. I could see a mem_map that picks a free addr though.

**Comment by cseagle** [comment]
"I could see a mem_map that picks a free addr though."

++ to this. Similar to passing NULL into mmap or VirtualAlloc. However in this case you might also want the ability to dictate a personality for such allocations, like a Linux, Windows, or BSD style address selection personality

**Comment by gdbinit** [comment]
I guess that uc_mem_map_ptr  could be used with a small wrapper against malloc allocating the minimum 4kb pages required by Unicorn API.

This could be added into uc_mem_map via NULL address, or a new API that would allocate the memory using malloc and return the pointer to the caller.

It would avoid writing a whole new memory manager although a memory manager inside the Unicorn "vm" could be useful, something like define an heap area and allocate from there, so we could have some kind of debugging capabilities over the heap area we allocated and assigned to the host.

**Comment by lunixbochs** [comment]
I think that's losing sight of the vision of Unicorn. The two comments in this thread are pretty different use cases. I think the core API should focus on CPU/machine emulation and a second library should exist for usermode or guest-OS-specific helpers on top of Unicorn (such as many of the Usercorn helper functions).

**Comment by gdbinit** [comment]
What's the point of adding another library on top of another library?
If people want to build helpers and so on, fine.
If people just want to do some stuff with Unicorn without caring about finer low level OS details they should be able to do it easily, from a Unicorn supported API. That's where the value from Unicorn is, easy access to a emulation API, that can be set and run in a couple of minutes for small projects where we don't want and need to spend a whole lot of time in finer details. For me it doesn't make any sense to *not* create this added value in Unicorn. It doesn't make much sense to depend on another external project to expose valuable features, at least basic ones.
