### ISSUE TITLE
Exposing instructions?

### ISSUE THREAD

**Issue by gdbinit** [unicorn-engine/unicorn#536]
How hard would it be to expose the current instruction that Unicorn is emulating?

For example I'm thinking about conditional jumps. Because Unicorn is emulating the instruction and contains full context it would be easy for it to expose if a given conditional instruction would lead follow or not. 

It can be done using Capstone and Unicorn at the same time, and coding all the conditions inside a wrapper. Just wondering how hard it would be for Unicorn to simply expose what's going app to instruction flow.

**Comment by lunixbochs** [comment]
You can already get the current instruction - can you be more specific? If you add a `HOOK_CODE` callback or just `reg_read(IP)`, you can `mem_read()` the instruction pointer address to get the raw opcode, then use something like Capstone to recover more information about the instruction.

**Comment by gdbinit** [comment]
Capstone is just a disassembler, it has no context of what is going to happen with conditional instructions for example. Unicorn does have that information somewhere internally since it will emulate the instruction so it must know what's the next address to execute.
Makes no sense for everyone to write wrappers to do this for whatever arch they are working with if Unicorn can easily expose this kind of information for all archs it supports.

**Comment by cseagle** [comment]
But you can just read eflags for example on x86 and observe whether a given conditional branch will be taken right? Are you looking for access to some deeper internal QEMU "I am about to branch" flag (assuming one exists)?

**Comment by aquynh** [comment]
even though Unicorn already decoded the instructions internally when it does binary translation, the result is not really ready for consumption. so to do what you want, we need to include a disassembler in Unicorn source. i am not sure many people would agree with this. imo, it is better to keep Unicorn simple as it is now. what you want is actually trivial to implement with an external disassembler & some hooking callbacks anyway.

**Comment by gdbinit** [comment]
Hi Chris,

Yes, I can always look at eflags and do like in gdbinit, a huge decision tree about what's going to happen to what instruction. I was precisely trying to avoid that code since I assume Unicorn/QEMU already have that information somewhere inside, so I was wondering how hard would it be to expose it.
I'm buidling an EFI binaries emulator and also want to add interactive debugging features to it and output like gdbinit/softice.

I guess a lot of other internal information could be extremely useful to expose without having to add a disassembler to my code and do all this work myself. Not that I care about platforms other than X86 but but would be great to have this info in a generic way for all supported platforms.

**Comment by aquynh** [comment]
close, thanks!
