### ISSUE TITLE
Hooks can only be added before uc_emu_start?

### ISSUE THREAD

**Issue by gdbinit** [unicorn-engine/unicorn#537]
Hi,

I was trying to add new hooks inside an existing UC_HOOK_CODE but it doesn't work at all, since the hook is ignored.

It seems hooks can only be added before uc_emu_start? Is this true?

What's the workaround? Need to stop and restart the emulation? Is that even possible inside the hook, since the hook is before instruction is executed (from what I can understand from other open issues).

Basically I'm trying to write something like a debugger for the code being emulated by Unicorn. I have a prompt inside the code hook where I can dump registers and do other operations before the current instruction is executed, like gdb and any other debugger.

**Comment by aquynh** [comment]
new hooks can be added any time, and it should be OK to do that from inside a callback.

can you send a testcase for your issue?

**Comment by gdbinit** [comment]
#include <stdio.h>
#include <unicorn/unicorn.h>

#define CODE "\x90\x90\x90"

#define ADDRESS 0x1000000

void
hook_code(uc_engine *uc, uint64_t address, uint32_t size, void *user_data)
{
 static int x = 0;
 if (x == 0)
 {
	printf("adding new hook\n");
        static uc_hook a;
	if (uc_hook_add(uc, &a, UC_HOOK_CODE, hook_code, NULL, address+2, address+3) != UC_ERR_OK)
	{
		printf("error on new hook\n");
	} 
	x++;
 }
 uint64_t r_rip = 0;
 if (uc_reg_read(uc, UC_X86_REG_RIP, &r_rip) != UC_ERR_OK)
 {
	printf("Error!\n");
	return;
 }
 printf("Current RIP 0x%llx\n", address);
}

int main(void)
{
 uc_engine *uc;
 uc_err err;
 err = uc_open(UC_ARCH_X86, UC_MODE_64, &uc);
 if (err != UC_ERR_OK)
 {
	return -1;
 }

 uc_mem_map(uc, ADDRESS, 2 * 1024 * 1024, UC_PROT_ALL);

 if (uc_mem_write(uc, ADDRESS, CODE, sizeof(CODE) -1))
 {
	return -1;
 }
 uc_hook hook1;
 uc_hook_add(uc, &hook1, UC_HOOK_CODE, hook_code, NULL, ADDRESS, ADDRESS+1);
 err = uc_emu_start(uc, ADDRESS, ADDRESS + sizeof(CODE) -1, 0,0);
 if (err)
 {
	return -1;
 }
 uc_close(uc);
 return 0;
}

**Comment by gdbinit** [comment]
The hook at 0x1000002 is set but never triggered.

**Comment by aquynh** [comment]
this is not a full testcase in which it cannot compile.

would you mind sending a PR to put this into tests/regress/, or tests/unit/ (which requires you to modify it to be in cmocka form)?

**Comment by gdbinit** [comment]
clang -o hook_fail hook_fail.c -I/usr/local/include -L/usr/local/lib -lunicorn

**Comment by lunixbochs** [comment]
If you add a code hook to a new address during execution, the JIT cache needs to be flushed for the block containing the hook. This doesn't currently happen. What are you trying to do? I might be able to suggest a workaround until this is fixed.

**Comment by gdbinit** [comment]
Yeah, I expected it to be a JIT cache issue from other open issues I read.

I'm trying to build an interactive debugger for the emulated code (I'm doing full EFI binary emulation).

Since a code hook is where I have control (a bit like INT3) I have a prompt to process debugger commands. I want to be able to step through code with gdb like step commands and set breakpoints in other addresses. 

The obvious workaround seems to make the code hook wrap around the whole code area and deal with the conditions inside hook code, continue executing the code if no breakpoint is hit else bring up the interactive prompt to act on current code. Any other way to workaround this?

**Comment by lunixbochs** [comment]
Adding a code hook to all instructions in the area is the easiest but slowest solution. Doing a uc_emu_stop() might be enough to register the hook (then set a flag in your code to immediately resume emulation after stop)

**Comment by gdbinit** [comment]
How would that work? Putting a uc_emu_stop, and then a uc_emu_start inside the hook will crash Unicorn. From what I can see Unicorn will stop after executing the current instruction, but then I have no control over emulation. I guess I would have to sync current instruction with a loop after the first Unicorn start and resume there. That might work, but wouldn't that also be slow with JIT cache having to be created every single time I do a start?

Not that I'm much worried with speed, it's more important to have interactive debugging access since that's the main thing I lack with reversing EFI code.

**Comment by lunixbochs** [comment]
It's just a trade-off on how many unhooked instructions you'd be executing. If you step over a huge subroutine, it should be significantly faster to trampoline than single step >1,000 instructions.

To trampoline:

1. inside your code hook, do a uc_emu_stop() and set a flag in your program. you can create new hooks at this point as well.
2. when uc_emu_start exits, check the flag and call uc_emu_start again with your new PC

**Comment by gdbinit** [comment]
Just need to save the whole context since I assume uc_emu_start knows nothing about what was running before uc_emu_stop.

**Comment by lunixbochs** [comment]
no, it remembers. you only need to know the new pc, which you can also reg_read.

**Comment by bet4it** [comment]
I also want to implement a debugger bases on unicorn. Do you solve this problem?
