### ISSUE TITLE
compile 32 bit target from osx 64 bit os

### ISSUE THREAD

**Issue by MatrixLing** [unicorn-engine/unicorn#544]
I want to compile to 32 bit target libunicorn.dylib  from my osx 64 bits OS. I don't know how to compile it.
The command "./make.sh nix32" from the document is not correct.

**Comment by aquynh** [comment]
have you found out how to do this yet?

**Comment by cseagle** [comment]
I think this was addressed in this comment:

https://github.com/unicorn-engine/unicorn/issues/482#issuecomment-201727015

I use this method to 32-bit unicorn libraries for use with Ida on OS X.

**Comment by aquynh** [comment]
@cseagle, would you mind sending a PR from your fix?

**Comment by aquynh** [comment]
@MatrixLing, i just pushed a commit to build universal binaries on MacOS by default: https://github.com/unicorn-engine/unicorn/commit/eea0b2d520dd3d40f35fa887913066d6e413a5a2

you just need to compile like usual `./make.sh`, without needing any extra option.

let me know if you still have issues, thanks.

**Comment by aquynh** [comment]
this is actually not a good idea, as dependency must be in universal format as well. so i committed a fix to build native binaries by default. now to build universal binaries, you have to run `make.sh` with `macos-universal` option, like below.

    $ ./make.sh macos-universal

then install binaries as usual (example, with `sudo ./make.sh install`)
