### ISSUE TITLE
Infinite loop inside a code hook

### ISSUE THREAD

**Issue by gdbinit** [unicorn-engine/unicorn#545]
Hi,

This simple hook in the sample Unicorn code at the website will infinite loop the hook and never advance EIP.

void
infinite_hook(uc_engine *uc, uint64_t address, uint32_t size, void *user_data)
{
    uint32_t r_eip = 0;
    uc_reg_read(uc, UC_X86_REG_EIP, &r_eip);
    uc_reg_write(uc, UC_X86_REG_EIP, &r_eip);
}

Add hook in the sample code:
    uc_hook trace;
    uc_hook_add(uc, &trace, UC_HOOK_CODE, infinite_hook, NULL, ADDRESS, ADDRESS+0x10);

EIP will be stuck at 0x1000000 address and loop forever.

**Comment by lunixbochs** [comment]
The code hook should give you EIP for the instruction (the same one passed in addr) instead of the next EIP. You should add size to actually advance it.

**Comment by gdbinit** [comment]
That makes sense except that advancing doesn't seem to work (check next open issue).
It seems like setting to same EIP guarantees instruction execution but advancing to next will just skip the instruction but also not execute the next one.

So there seems to exist some inconsistent behavior here. Normal registers are updated but both EIP/EFLAGS appear to have inconsistencies if we modify them?

**Comment by lunixbochs** [comment]
Everything here seems reasonable. The only problem looks to be in #546, where I'll comment further.

**Comment by aquynh** [comment]
i think this happens when you modify the EIP to point to a new address in the same basic block, but if the EIP is far enough, you dont have this issue. can you confirm?
