### ISSUE TITLE
Advancing EIP inside a hook skips all instructions

### ISSUE THREAD

**Issue by gdbinit** [unicorn-engine/unicorn#546]
Add this code hook in the Unicorn sample code at the website:

void
advance_rip_hook(uc_engine *uc, uint64_t address, uint32_t size, void *user_data)
{
    uint32_t r_eip = 0;
    uc_reg_read(uc, UC_X86_REG_EIP, &r_eip);
    printf("Current before advancing EIP: 0x%x\n", r_eip);
    r_eip += 1;
    uc_reg_write(uc, UC_X86_REG_EIP, &r_eip);
}

The result:
$ ./test1
Emulate i386 code
Current before advancing EIP: 0x1000000
Current before advancing EIP: 0x1000001
Emulation done. Below is the CPU context

> > > ECX = 0x1234
> > > EDX = 0x7890

This means that both instructions were skipped. It would be expected EDX to decrease on the first cycle, and then some crash since it would be pointing to some junk on the mapped memory (the example code is only two instructions).

**Comment by gdbinit** [comment]
I guess this happens because EIP will advance but the current instruction will never be executed, and when EIP advances the next instruction will trigger the hook before being executed, so in practice they have advanced on every iteration before they execute.

Just modified to test for that and it is indeed what happens:

void
advance_rip_hook(uc_engine *uc, uint64_t address, uint32_t size, void *user_data)
{
    static int x = 0;
    if (x == 0)
    {
        uint32_t r_eip = 0;
        uc_reg_read(uc, UC_X86_REG_EIP, &r_eip);
        printf("Current before advancing EIP: 0x%x\n", r_eip);
        r_eip += 1;
        uc_reg_write(uc, UC_X86_REG_EIP, &r_eip);
        x++;
    }
}

$ ./test1
Emulate i386 code
Current before advancing EIP: 0x1000000
Emulation done. Below is the CPU context
>>> ECX = 0x1234
>>> EDX = 0x788f

It seems only EFLAGS have problems being modified inside the hook then.

**Comment by lunixbochs** [comment]
@farmdve's post-instruction hook might be the solution here #346

**Comment by aquynh** [comment]
yes we should have the post-instruction hook, but the confusion raised by this issue still needs to be fixed.

**Comment by farmdve** [comment]
The way QEMU jits some instructions prevents us from having post-instruction hooks without undefined behaviour.
