### ISSUE TITLE
JWASM & MASM Assembler bindings

### ISSUE THREAD

**Issue by UnlimitedChild** [unicorn-engine/unicorn#556]
Hallo, 

How can I make a complete Include file, I tried to do from the files for Visual Studio. Unfortunately structures are not fully described, and if they are described, are scattered throughout the QEMU Include files. This makes the emulator incapacitated to work with assembler. Since this is a low-level code emulator, it would be cool to have the support of assembler compilers.

Regards

**Comment by radare** [comment]
Wat

**Comment by aquynh** [comment]
Do you mean you want to use assembler to compile assembly, the feed the output to Unicorn for emulation? Then that part does not belong to Unicorn, you have to compile assembly yourself

**Comment by UnlimitedChild** [comment]
What is not clear? This code will not work, because of the above. 

`option casemap:none

WINVER equ 0500h
WIN32_LEAN_AND_MEAN equ 1
OPTION PROLOGUE:rbpFramePrologue
OPTION EPILOGUE:rbpFrameEpilogue

.nolist
.nocref

include C:\masm32\jWasm\Include\WINDOWS.INC

include C:\masm32\2016Project\Template_\include\unicorn\x86.INC
include C:\masm32\2016Project\Template_\include\unicorn\unicorn.INC
;include C:\masm32\2016Project\Template_\include\uc_priv.INC
includelib C:\masm32\2016Project\Template_\unicorn_staload64.LIB

;include C:\masm32\jWasm\sdkrc100\shared\sdk64.INC

includelib C:\masm32\jWasm\Lib\Lib64\USER32.LIB
includelib C:\masm32\jWasm\Lib\Lib64\KERNEL32.LIB
includelib C:\masm32\jWasm\Lib\Lib64\GDI32.LIB

push2 MACRO args:VARARG
   FOR p,<args>
      push p
   ENDM
ENDM

pop2 MACRO args:VARARG
   FOR p,<args>
      pop p
   ENDM
ENDM

.data
uc equ uc_engine

.data?


.code
start:

    ;Initialize emulator in X86-64bit mode
    invoke uc_open,UC_ARCH_X86, UC_MODE_64, uc;

;include hexa_proc.inc
;include hexa_data.inc
end start`

**Comment by radare** [comment]
Unicorn is not an assembler

**Comment by lunixbochs** [comment]
I think you can treat all of the structures as opaque pointers except the x86 mmu ones.

**Comment by UnlimitedChild** [comment]
Hallo, 

> Unicorn is not an assembler
Really? And I didn't know =D What are you talking about? This is nowhere stated o_O 

> I think you can treat all of the structures as opaque pointers except the x86 mmu ones.

Thank you, I also came to this conclusion. I spent a lot of time and tried to translate all the header files in the normal form. But still too many nested errors.

**Comment by aquynh** [comment]
close, thanks!
