### ISSUE TITLE
memory mapping speed regression

### ISSUE THREAD

**Issue by lunixbochs** [unicorn-engine/unicorn#560]
If I rapidly uc_mem_map / uc_mem_unmap, I hit a speed regression very quickly.

Here's a test case:

```
#include <unicorn/unicorn.h>
#include <stdio.h>
#include <time.h>

int main(int argc, char **argv) {
    uc_engine *uc;
    uc_open(UC_ARCH_X86, UC_MODE_32, &uc);

    int64_t count = 0;
    int64_t start = time(NULL);
    while (1) {
        count++;
        uc_mem_map(uc, 0x1000, 0x10000, UC_PROT_ALL);
        uc_mem_unmap(uc, 0x1000, 0x10000);
        int64_t now = time(NULL);
        printf("%.4f maps per second\n", count / (double)(now - start));
    }
}
```

**Comment by lunixbochs** [comment]
I've hooked Usercorn up to AFL but both methods of forkserver are causing me problems-

If I reuse a single Unicorn instance but remap its memory every run, I hit this regression within seconds.
If I use a new Unicorn instance every time, memory usage balloons out of control (talking like 1TB virtual memory) very quickly.

**Comment by aquynh** [comment]
interesting, what can be the reason of this speed issue?

**Comment by lunixbochs** [comment]
No idea. I did some basic debugging and didn't find it. I see a slow memory leak as well, not sure if it's related.

**Comment by lunixbochs** [comment]
Also happens with `mem_map_ptr()`

**Comment by lunixbochs** [comment]
Speed increases from ~500 to ~20000 maps per second and the speed regression seems to disappear (albeit with a leak) if I stub out memory_region_unref and delete all the mr->name stuff in memory_region_init

**Comment by aquynh** [comment]
Can Valgrind find this memleak?

Yes, Unicorn can be optimized to remove some dependency layers we dont really need. This is quite a lot of work however.

**Comment by danghvu** [comment]
There are some memory that are not free-ed during uc_mem_unmap but eventually is free-ed during `uc_close` .. I am trying to track these down.

**Comment by lunixbochs** [comment]
this issue is more about the speed than the leak, though both matter when trying to use unicorn as an afl forkserver

**Comment by danghvu** [comment]
I'm more concerning the reduced in speed, which is due to memory leak so far as my investigation

**Comment by ltfish** [comment]
I assume this issue has been fixed. Maybe it's time to close it?
