### ISSUE TITLE
Memory leak in uc_open / uc_close

### ISSUE THREAD

**Issue by salls** [unicorn-engine/unicorn#564]
I'm using the python bindings for unicorn. I noticed that when making `Uc` objects, memory wasn't being freed when the object was deleted / garbage collected.

Looking further, it seems like `uc_close` should be cleaning up the memory from `uc_open`. However, if I call them repeatedly in a loop I will quickly run out of memory.

``` python
for j in xrange(0x20000):
    status = _uc.uc_open(arch, mode, ctypes.byref(self._uch))
    status = _uc.uc_close(self._uch)
```

**Comment by aquynh** [comment]
Is this against latest Unicorn code from Github?

**Comment by salls** [comment]
Yep

**Comment by lunixbochs** [comment]
Previously discussed in the middle of #508.

**Comment by danghvu** [comment]
Which arch are you using ? If it is `x86/arm/arm64` can you check against the master branch ?
