### ISSUE TITLE
setting stack segment in syscall reinvokes syscall

### ISSUE THREAD

**Issue by lunixbochs** [unicorn-engine/unicorn#570]
```
from unicorn import *
from unicorn.x86_const import *
import binascii
import struct

code = 'cd809090'.decode('hex')
CODE = 0x1000
STACK = 0x8000
GDTR = 0x20000

uc = Uc(UC_ARCH_X86, UC_MODE_32)
uc.mem_map(CODE, 0x1000)
uc.mem_write(CODE, code)

uc.mem_map(STACK, 0x2000)
uc.mem_map(GDTR, 0x1000)

def hook_intr(uc, intno, user_data):
    if intno == 0x80:
        print 'syscall'
        uc.mem_write(GDTR + 8 * 2, struct.pack('<Q', 65535))
        uc.reg_write(UC_X86_REG_GDTR, (0, GDTR, 0x1000, 0))
        uc.reg_write(UC_X86_REG_SS, 2)

def hook_code(uc, addr, size, user_data):
    print '0x%04x: %s' % (addr, binascii.hexlify(uc.mem_read(addr, size)))

uc.hook_add(UC_HOOK_INTR, hook_intr)
uc.hook_add(UC_HOOK_CODE, hook_code)

uc.emu_start(CODE, CODE + len(code))
```

This will print `syscall` 3+ times and exit without running the nops. None of the other segment selectors have this problem.

`uc.reg_write(UC_X86_REG_SS, 2)` seems to be longjmp'ing back to the instruction, as `hook_intr` is repeatedly invoked without returning.

**Comment by danghvu** [comment]
There is an `0xd` after you perform the SS write. I suppose you need to handle it somehow, that is an interrupt which doesn't update the EIP.

**Comment by aquynh** [comment]
Ryan, this is a dilemma: your code causes a GPF, but your interrupt handler does not handle it. the question is: how does the emulation proceed after unhandled GPF? at the moment, EIP is not updated due to GPF, hence your problem.

**Comment by lunixbochs** [comment]
Related to #377 - if the handler doesn't return `true` to indicate the interrupt was handled properly by the hook, Unicorn should probably stop with an error.

**Comment by aquynh** [comment]
this means we need to change the interrupt handler semantics.

anyway, is there any cases that interrupt handler can handle GPF? looks like we should always break emulation for this interrupt
