### ISSUE TITLE
"unicorn" package is not claimed on PyPI

### ISSUE THREAD

**Issue by zachriggle** [unicorn-engine/unicorn#573]
While I understand there is not currently a deployable package for `pip install unicorn`, currently this is open for registration and available for squatting.  I recommend that it gets registered quickly :-)

**Comment by aquynh** [comment]
done, thanks!

**Comment by zachriggle** [comment]
You should also probably register `unicorn-engine` since the Keystone package name is `keystone-engine`.

**Comment by aquynh** [comment]
i did, thanks!
