### ISSUE TITLE
Emulation hangs at certain offsets

### ISSUE THREAD

**Issue by NUko32** [unicorn-engine/unicorn#575]
Hello, I was using unicorn in a project and encountered a problem. I noticed that emulation hangs when the execution offset for an instruction reaches a quarter of pages (i.e. _0x1400_, _0x1800_, _0x1c00_ and _0x2000_).

I have done some testing and here's a simple snippet to reproduce.

```
    uint32_t code[] = {
        0xd503201f, /* NOP */
        0xd503201f, /* NOP */
        0xd503201f, /* NOP */
        0xaa0103e0  /* MOV X0, X1 */
    };

    uc_engine *uc;

    uint64_t x0 = 0;
    uint64_t x1 = 1;

    if (uc_open(UC_ARCH_ARM64, UC_MODE_ARM, &uc) != UC_ERR_OK) {
        printf("error on open\n");
        return -1;
    }

    uint64_t addr = 0x13f0;
    uint64_t trunc_addr = trunc_page(addr);    // round down to nearest page

    uc_mem_map(uc, trunc_addr, 2 * 1024 * 1024, UC_PROT_ALL);

    if (uc_mem_write(uc, addr, &code, sizeof(code))) {
        printf("error on write\n");
        return -2;
    }

    uc_reg_write(uc, UC_ARM64_REG_X0, &x0);
    uc_reg_write(uc, UC_ARM64_REG_X1, &x1);

    if (uc_emu_start(uc, addr, addr + sizeof(code), 0, 0)) {
        printf("error on start\n");
        return -3;
    }

    uc_reg_read(uc, UC_ARM64_REG_X0, &x0);
    uc_reg_read(uc, UC_ARM64_REG_X1, &x1);

    printf("x0: %#llx\n", x0);
    printf("x1: %#llx\n", x1);
```

I will explain the problem in more detail.

unicorn, as far as I have noticed, only allows emulation mapping addresses (specified via `uc_mem_map`) to be multiple of a page. If not, mapping fails.

Since I need to emulate code at a specific address, I came up with a workaround. This consists in truncating (i.e. rounding down to the nearest page) the address where I want emulation to start. 
For example, _0x1100_ becomes _0x1000_ when truncated.
Once this has been done, I call `uc_mem_map` with that address, which gets accepted and mapped. Then I simply write code at the original address, and start emulating there. This works fine, and no problems whatsoever.

But, when executing some code that was large enough to hit a quarter of a page, I noticed that emulation was hanging. I tried to write the code further down, so that no instructions were emulating on the quarter of a page, and it worked fine.

In the attached code the emulation map gets allocated at _0x1000_, while code is written at _0x13f0_. This is calculated so that the last instruction (`mov x0, x1`) gets emulated at _0x1400_. You can try the same code using _0x17f0_, _0x1bf0_ and _0x1ff0_ and you will get the same result; emulation hanging.
By using a different address, everything works fine and instructions are executed.

Why is this happening? It is a unicorn known problem or am I doing something wrong?

**Comment by aquynh** [comment]
this can be a bug, but your code is incomplete, so i cannot compile & reproduce. 

can you send in a pull req to put this as a testcase under tests/unit/? (see some existing code there to make a proper form for it)

thanks

**Comment by NUko32** [comment]
I have created the pull request #579  and added the hang test. I also tried with x86 and it doesn't seem to hang, so it may just be an ARM64 problem.

**Comment by lunixbochs** [comment]
x86, x86_64, and arm are probably the most used targets
sparc and m68k are likely the most broken (and m68k doesn't have capstone/keystone support either iirc)

**Comment by aquynh** [comment]
M68k is supported in the "next" branch of Capstone. 
but M68k assembler for Keystone is not available yet.

**Comment by aquynh** [comment]
arm64 should be in a great shape for both Capstone & Keystone.
