### ISSUE TITLE
code hook callback passes an invalid 'size' for invalid opcode (i.e. instruction 0xf1)

### ISSUE THREAD

**Issue by sparktrend** [unicorn-engine/unicorn#577]
First of all, I'd like to thank you guys' tremendous and consistent effort to get unicorn straightened. I know it requires a mountain of work. Much appreciated.

The code that doesn't work is:

https://gist.github.com/sparktrend/0d9dcf8c2b431b9fa77fcbb656e2a5d6

The output is below:

byte f1 size 4059165169
ERROR: Invalid instruction (UC_ERR_INSN_INVALID)

0xf1 is an invalid opcode according to intel manual. There are other invalid opcodes as well. The expected behaviour in this case is to have either size of 0 at hook_code at least, or to have hook_int invoked (preferably before hook_code). Could you fix this?

**Comment by aquynh** [comment]
Can you send a PR to put this testcase under tests/regress/ ?

**Comment by sparktrend** [comment]
I forgot to do:
self.emu.reg_write(UC_X86_REG_EIP, self.entrypoint)

But it still generates the same output. So it's a bug.

**Comment by danghvu** [comment]
```diff
diff --git a/uc.c b/uc.c
index 1e72b87..76da4a7 100644
--- a/uc.c
+++ b/uc.c
@@ -1110,6 +1110,11 @@ void helper_uc_tracecode(int32_t size, uc_hook_type type, void *handle, int64_t
         uc->set_pc(uc, address);
     }

+    if (size == 0xf1f1f1f1 || size == 0xf2f2f2f2) {
+        // These are magic number, if they are not updated, we have a problem.
+        size = 0;
+    }
```

Can you test this patch ? @aquynh -- is this the right way to catch the magic number ?

**Comment by aquynh** [comment]
that looks OK, but this trick may hide other issues, for example when the size is not updated due to other exceptions.

@sparktrend, can you send a PR to put your Gist script under tests/regress/?
