### ISSUE TITLE
General Protection Fault (Int 13) followed by Double Fault (Int 8)

### ISSUE THREAD

**Issue by sparktrend** [unicorn-engine/unicorn#578]
Hi Folks,

For some of the troublesome instructions I have, #GP (int 13) followed by #DF (int8) is triggered. There is no way I can simply ignore these instructions and get the control back. See the sample code below.

https://gist.github.com/sparktrend/cf99ba6d6b024b3182865ea47afb6ed2

These instructions include:
    - ca (retf 0), cb (retf) -> #GP 
    - cf (iretd)
    - d4 (aam 0) -> # DE (Divide By Zero)
    - ea (ljmp 0:0)
    - f1 (Invalid code)
    - f4 (hlt)

Since these instructions access segment selectors (which I haven't set up), they cause #GP, #DE, etc (See the exception table below). I understand the triggering mechanism of these exceptions. Ideally software (like operating system) should process these exceptions appropriately. **_However, is there any way we can get the control back from unicorn so that we can restart emulation at different locations or do something else? Implementing proper exception handling is very difficult._**

I tried setting EIP to the next location in the interrupt hook, but it doesn't work (I'm using newer version of unicorn which this EIP reset works, but not in this context). The EIP is stuck at the same location as you can see below:

0: byte cb size 1
Interrupt 13
0: byte cb size 1
Interrupt 8
0: byte cb size 1
2: byte cb size 1
2: byte cb size 1
2: byte cb size 1
.. (infinite)

* Exception types
    http://wiki.osdev.org/Exceptions
    
    Name 	                      Vector nr. 	    Type 	    Mnemonic 	Error code?
    Divide-by-zero Error 	      0 (0x0) 	        Fault 	    #DE 	    No
    Debug 	                      1 (0x1) 	        Fault/Trap 	#DB 	    No
    Non-maskable Interrupt 	      2 (0x2) 	        Interrupt 	- 	        No
    Breakpoint 	                  3 (0x3) 	        Trap 	    #BP 	    No
    Overflow 	                  4 (0x4) 	        Trap 	    #OF 	    No
    Bound Range Exceeded 	      5 (0x5) 	        Fault 	    #BR 	    No
    Invalid Opcode 	              6 (0x6) 	        Fault 	    #UD 	    No
    Device Not Available 	      7 (0x7) 	        Fault 	    #NM 	    No
    Double Fault 	              8 (0x8) 	        Abort 	    #DF 	    Yes (Zero)
    Coprocessor Segment Overrun   9 (0x9) 	        Fault 	    - 	        No
    Invalid TSS 	              10 (0xA) 	        Fault 	    #TS 	    Yes
    Segment Not Present 	      11 (0xB) 	        Fault 	    #NP 	    Yes
    Stack-Segment Fault 	      12 (0xC) 	        Fault 	    #SS 	    Yes
    General Protection Fault 	  13 (0xD) 	        Fault 	    #GP 	    Yes
    Page Fault 	                  14 (0xE) 	        Fault 	    #PF 	    Yes
    Reserved 	                  15 (0xF) 	        - 	        - 	        No
    x87 Floating-Point Exception  16 (0x10) 	    Fault 	    #MF 	    No
    Alignment Check 	          17 (0x11) 	    Fault 	    #AC 	    Yes
    Machine Check 	              18 (0x12) 	    Abort 	    #MC 	    No
    SIMD Floating-Point Exception 19 (0x13) 	    Fault 	    #XM/#XF 	No
    Virtualization Exception 	  20 (0x14) 	    Fault 	    #VE 	    No
    Reserved 	                  21-29 (0x15-0x1D) - 	        - 	        No
    Security Exception 	          30 (0x1E) 	    - 	        #SX 	    Yes
    Reserved 	                  31 (0x1F) 	    - 	        - 	        No
    Triple Fault 	              - 	            - 	        - 	        No
    FPU Error Interrupt 	      IRQ 13 	        Interrupt 	#FERR 	    No

**Comment by lunixbochs** [comment]
Maybe reg_write(EIP) should trampoline the emulator if it's running? Then it's not hook-specific.

See also #546 and #512

**Comment by sparktrend** [comment]
Could you elaborate on 'trampoline the emulator'? I don't understand what it means.

Thanks lunixbochs.

**Comment by lunixbochs** [comment]
emu_stop(), emu_start(new_ip)

**Comment by sparktrend** [comment]
Hmm.... I've got something interesting going on here. 'except' block in try-except wasn't called when #GP followed by #DF occurred. I didn't call emu_stop() in hook_int. So it appears emu_start() call simply returns when emulation can't continue any more instead of triggering UcError exception. Is that the desired behaviour?

**Comment by lunixbochs** [comment]
If it faults after an interrupt that should probably be an error.

**Comment by sparktrend** [comment]
Yes, but it doesn't trigger exception at the moment. I noticed several conditions that stop emulation automatically and transfers the control to the next line of **_emu_start_**().
1. Invalid opcode (try '\xf1')
2. Exception conditions not resolved apart from unmapped memory condition (this includes all exceptions I described in the table originally)
3. Directly call emu_stop().

So from unicorn user's perspective, you can' distinguish those 3 cases when emu_start() returns.

**Comment by lunixbochs** [comment]
You can tell (3) simply by setting a flag in your program before calling emu_stop(). In Usercorn I actually track "stop reasons" so I can tell the difference between a debugger, a signal, etc

**Comment by sparktrend** [comment]
It would be more structurally nicer to incorporate those exceptional cases in exception category rather than terminating the emulation. However, I shouldn't really complain about that given that this is an open source project.

Thanks heaps for replying to my questions, Lunixbochs! It really helped me digging further in.

**Comment by aquynh** [comment]
yes the core should exit uc_emu_start() cleanly with an exception. patch to fix this is welcome.

**Comment by danghvu** [comment]
The master branch should now raise an exception or return error if an interrupt is not handled, but handling the interrupt is still an issue, some interrupt doesn't advance the $PC$ automatically.
