### ISSUE TITLE
Lower bits of CPSR values returned by `reg_read` imply invalid processor mode

### ISSUE THREAD

**Issue by neobrain** [unicorn-engine/unicorn#582]
Reading the CPSR register on ARM returns invalid values. In particular, the lower bits seem to be read off as `0x1d3`, which indicates the processor mode (lowest 5 bits) of `0x3`, which is an invalid mode.

For a test case, consider the following program:
```python
from unicorn import *
from unicorn.arm_const import *
import binascii

MB = 1024 * 1024
PAGE = 4 * 1024

def PrintArmRegisters(uc_emu):
    print 'R0 : '+hex(uc_emu.reg_read(UC_ARM_REG_R0))
    flags = uc_emu.reg_read(UC_ARM_REG_CPSR)
    print 'cpsr : '+hex(flags)
    print 'carry : '+str(flags >> 29 & 0x1)
    print 'overflow : '+str(flags >> 28 & 0x1)
    print 'negative : '+str(flags >> 31 & 0x1)
    print 'zero : '+str(flags >> 30 & 0x1)


# cmp r0, r1
TestCode = b'\x01\x00\x50\xe1'

def UseUcToEmulate():
    try:
        uc_emu = Uc(UC_ARCH_ARM, UC_MODE_ARM)
        uc_emu.mem_map(0, 2*MB)
        uc_emu.reg_write(UC_ARM_REG_R0, 0)
        uc_emu.reg_write(UC_ARM_REG_R1, PUT_ZERO_OR_ONE_HERE)
        uc_emu.reg_write(UC_ARM_REG_CPSR, 0x10)
        uc_emu.mem_write(0, TestCode)
        uc_emu.mem_write(0x1c, b'\xef\xbe\xad\xde')
        uc_emu.emu_start(0, 4)
        PrintArmRegisters(uc_emu)

    except UcError as e:
        print("ERROR: %s" % e)
        PrintArmRegisters(uc_emu)


UseUcToEmulate()
```
This program outputs a CPSR value of 0x800001d3 or 0x600001d3 for me, depending on the choice of `PUT_ZERO_OR_ONE_HERE`. In other words, condition flags (the upper 4 CPSR bits) do get updated properly, however the lower bits seem to be nonsensical as explained above.

**Comment by danghvu** [comment]
I am not sure here, reading [this](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0311d/ch02s04s02.html):

> [4:0]	M	
Mode field:
b10000 = User mode
b10001 = FIQ mode
b10010 = IRQ mode
b10011 = Supervisor mode
b10111 = Abort mode
b11011 = Undefined mode
b11111 = System mode.

We report the mode bit as `0b10011` which is "supervisor" mode, not `invalid` -- maybe I am wrong, not an expert of Arm mode. If you can point me to a reference that will be good.

**Comment by neobrain** [comment]
@danghvu Uhm, you're right. I derped and missed that the lowest 5 bits of 0x1d3 are indeed 0b10011, which is supervisor mode as you said :)
