### ISSUE TITLE
Need to refactor code for porting to iOS

### ISSUE THREAD

**Issue by Proteas** [unicorn-engine/unicorn#584]
Thank you for this project.
The following is an advise.
-------------------------------------
Reason: 
        on iOS, normal process can't have memory with PROT_READ | PROT_WRITE | PROT_EXEC.
        It should be RW- for writing by unicorn, or R-X for executing, managed by programmer.
        Currently in Unicorn, the RWX buffer is directly accessed by pointer, for example: tcg_ctx->code_gen_buffer.

Target:
        Create a layer for wring to RWX buffer, for example: use a function, other code use the function, not the buffer pointer. And the platform depended code should be wrapped in this function, for iOS, change the protection to RW before writing, and change back to R-X after writing.

Other:
        1. Seems that there are some RWX buffers during runtime, not only one, for example: mu.hook_add(UC_HOOK_BLOCK, hook_block) will create another 16K RWX buffer.
        2. when defined USE_MMAP, the allocated RWX is leaked after calling uc_close().
-------------------------------------
@ProteasWang

**Comment by lunixbochs** [comment]
I'm pretty sure iOS has never allowed App Store apps to mark pages executable after writing to them- the only JIT allowed is for WebKit/JavaScript

**Comment by Proteas** [comment]
I mean on jailbreaked iDevice.

**Comment by lunixbochs** [comment]
isn't the JIT prevention still in the kernel, which as of ios9 doesn't get patched?

you can sign with the safari JIT entitlement but I think that just lets you allocate one rwx page on program start

**Comment by Proteas** [comment]
1. I have implemented this: map JIT.
2. Only one JIT buffer is not enough.
