### ISSUE TITLE
Python library not installed on linux

### ISSUE THREAD

**Issue by iN3O** [unicorn-engine/unicorn#585]
I did

>$ ./make.sh
>$ sudo ./make.sh install
>$ python
> Python 2.7.11+ (default, Apr 17 2016, 14:00:29) 
> [GCC 5.3.1 20160413] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> \>>>import unicorn
>Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: No module named unicorn

But it didn't copy the python library to the `/usr/lib/python2.7/dist-packages/` . I had to manually copy the folder to the directory and then it was working perfectly.

> Python 2.7.11+ (default, Apr 17 2016, 14:00:29) 
> [GCC 5.3.1 20160413] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> \>>> import unicorn

You guys should make changed to make.sh file to copy python binding folder also.

**Comment by aquynh** [comment]
No, Python binding is installed separately from the core. You miss
following steps:

$ cd bindings/python
$ sudo make install

**Comment by petevine** [comment]
@aquynh That's exactly the point the OP was making. Any reason why the python bindings are packaged separately?

**Comment by aquynh** [comment]
do you mean Python binding should be installed by default (with the core)? if so, then we need to install all the bindings by default?

**Comment by petevine** [comment]
On Sun, 03 Jul 2016 09:47:35 -0700
Nguyen Anh Quynh <notifications@github.com> wrote:

> do you mean Python binding should be installed by default (with the core)? if so, then we need to install all the bindings by default?

IMHO, Python bindings should be installed by default - they also work in Pypy (via PYTHONPATH) and besides, according to a recent survey, Python has emerged as the dominant scripting language, leaving Ruby behind.

It wouldn't hurt to include the rest of the bindings in the default installation either, provided they work out of the box (like the python ones).

**Comment by danghvu** [comment]
I see no reason for giving privilege to python at the moment. I would prefer someone providing a package for python which allows `pip install unicorn` such that install both unicorn and python binding, similar to [capstone](https://pypi.python.org/pypi/capstone/3.0.4)

**Comment by aquynh** [comment]
yes, i dont think `make.sh` should only install the core, but not any bindings. finally, that is only 2 more simple commands, why users cannot do that?

**Comment by aquynh** [comment]
Close, thanks
