### ISSUE TITLE
6b9f17f2f7 breaks windows mingw build

### ISSUE THREAD

**Issue by cseagle** [unicorn-engine/unicorn#587]
The problem seems to be the change to munmap in qemu/unicorm-common.h along with the requirement to include sys/mman.h in that file. This should be blocked inside an #ifndef _WIN32 but I have no idea what motivated the change from g_free(s->code_gen_buffer); to a call to munmap. On windows that might be a VirtualFree, but I have no idea where/how s->code_gen_buffer was originally allocated.

The original author of this patch should revisit and fix.

**Comment by danghvu** [comment]
I was patching this for memory leak in Linux: 

See this: https://github.com/unicorn-engine/unicorn/blob/master/qemu/translate-all.c#L617

And: https://github.com/unicorn-engine/unicorn/blob/master/qemu/translate-all.c#L473

The default uses mmap and leaking in Linux, will submit a patch for non-mmap case.

**Comment by danghvu** [comment]
Fixed in https://github.com/unicorn-engine/unicorn/commit/b9a10152f149871a9e1ea8116fe0833df7c23291

**Comment by cseagle** [comment]
I still had to add 

#ifndef _WIN32
#endif

around the #include <sys/mman.h>
in qemu/unicorn_common.h

to get it to build. That file is not available on windows.

**Comment by danghvu** [comment]
I see.. I missed that part, could you submit a patch for that ? Otherwise I will check that once I get a windows machine.
