### ISSUE TITLE
x86: Infinite hang when executing `fsqrt` on 80-bit float.

### ISSUE THREAD

**Issue by niklasb** [unicorn-engine/unicorn#589]
The following code reproduces what seems like an infinite hang at 100% CPU:

```
from unicorn import *
from unicorn.x86_const import *

code_addr = 0x1000000
code = (
    '\xb8\x00\x00\x00\x02' # mov eax, 0x2000000
    '\xdb\x28'             # fldt [eax]
    '\xd9\xfa'             # fsqrt
)
data_addr = 0x2000000
data = '\0\0\0\0\0\0\0\0\0\1'

mu = Uc(UC_ARCH_X86, UC_MODE_32)
mu.mem_map(code_addr, 0x1000)
mu.mem_map(data_addr, 0x1000)
mu.mem_write(code_addr, code)
mu.mem_write(data_addr, data)
mu.emu_start(code_addr, code_addr + len(code), 10000, 10)
```

**Comment by aquynh** [comment]
Can you send a pull req to put this testcase under tests/regress/ ?

Thanks

**Comment by niklasb** [comment]
Done.

**Comment by niklasb** [comment]
@robbje says that probably the culprit is an infinite loop at https://github.com/unicorn-engine/unicorn/blob/master/qemu/fpu/softfloat.c#L5369 So most likely a bug in QEMU, not Unicorn. How do you guys typically handle this?

**Comment by robbje** [comment]
It's likely a qemu issue:

    $ gcc -o test test.c
Does not hang:

    $ ./test
hangs infinitely:
    
    $ qemu-x86_64 test

```
#include <math.h>
#include <string.h>
#include <stdint.h>

typedef struct floatx80_s {
	int64_t low;
	int16_t high;
} floatx80_t;

int main(int argc, char **argv)
{
	floatx80_t x80 = {.low = 0x0000000100000064, .high = 0x0002};
	long double x;
	memcpy(&x, &x80, sizeof(x));
	sqrtl(x);
	return 0;
}
```

**Comment by danghvu** [comment]
Which version of qemu in your run? It's worth to report upstream if this is their latest version.

**Comment by robbje** [comment]
I tried against 2.6.0 (current release) and 2.6.50 (git). Both go into an infinite loop.

**Comment by aquynh** [comment]
Please report this bug to Qemu. We will port their fix as soon as they do
it. This is a good approach as we need to sync with upstream later.

But if anybody can fix this independently, go ahead and send in pull req,
thanks.

**Comment by robbje** [comment]
Thanks, I reported the bug to qemu:
https://bugs.launchpad.net/qemu/+bug/1603734

**Comment by aquynh** [comment]
great, but do you think it is a good idea to report this to the mailing list of Qemu at the same time? i am not sure if a lot of people will get the report from launchpad, or if launchpad forwards this bug to their mailing list.

**Comment by robbje** [comment]
Apparently launchpad forwards the bug to their qemu-devel ML:
http://lists.nongnu.org/archive/html/qemu-devel/2016-07/msg03623.html

**Comment by aquynh** [comment]
Awesome, plz keep us updated, thanks.
