### ISSUE TITLE
 recipe for target 'qemu/config-host.h-timestamp' failed

### ISSUE THREAD

**Issue by geek-li** [unicorn-engine/unicorn#598]
when I compile the unicorn,drop this error info.how to solve this error?

![qq 20160801153310](https://cloud.githubusercontent.com/assets/5059057/17286636/6db9b112-57fd-11e6-8011-4ebcbf66a921.png)

**Comment by aquynh** [comment]
you can always "make clean" and try again.

but apparently the error says you dont have MingW installed on your machine. are you cross-compiling to Windows?

**Comment by geek-li** [comment]
yep.I wanna   cross-compiling  unicorn for windows
