### ISSUE TITLE
undefined reference to `__stack_chk_fail' 

### ISSUE THREAD

**Issue by geek-li** [unicorn-engine/unicorn#599]
when I compile the unicorn with mingw ,there is some  error:
![qq 20160801210406](https://cloud.githubusercontent.com/assets/5059057/17294823/a5c777be-582b-11e6-8133-99524ad71ea5.png)

**Comment by samothtronicien** [comment]
Got the same issue when cross compiling in 64 bits with mingw.
I've fixed the issue by editing the makefile :

> \# mingw?
> IS_MINGW := $(shell $(CC) --version | grep -i mingw | wc -l)
> ifeq ($(IS_MINGW),1)
> EXT = dll
> AR_EXT = lib
> BIN_EXT = .exe
> **UNICORN_QEMU_FLAGS += --disable-stack-protector**

**Comment by aquynh** [comment]
no, do not edit Makefile. can you try something like this?

    $ UNICORN_QEMU_FLAGS="--disable-stack-protector" ./make.sh

**Comment by aquynh** [comment]
if this works, please consider sending a pull req to update `docs/COMPILE-*.md`, thanks.

**Comment by s0ns0n** [comment]
Unfortunately it didn't work for me, and I had to modify the makefile also...
