### ISSUE TITLE
cffi Python bindings

### ISSUE THREAD

**Issue by lunixbochs** [unicorn-engine/unicorn#6]
ctypes is pretty slow, and especially bad with pypy. What are your thoughts on using cffi instead? I know it adds an extra dependency, so maybe cffi could be used if available with a ctypes fallback?

**Comment by petevine** [comment]
A quick question - would there be any benefit from using PyPy? A jitting assembly of sorts :) (pun intended)

**Comment by lunixbochs** [comment]
I wrote the cffi bindings in an attempt to add pypy support but it didn't work with either binding type.

**Comment by petevine** [comment]
So you expected some performance gain from using pypy?

**Comment by lunixbochs** [comment]
pypy can jit the hook callbacks to native code. faster hooks = faster emulation. usercorn was 10-20x slower in cpython than Go

**Comment by petevine** [comment]
Thanks, that's exactly was I was interested to hear.

**Comment by petevine** [comment]
If you could direct me to some tests that show where pypy is lacking I'm going to open an issue at bitbucket.

**Comment by lunixbochs** [comment]
I honestly haven't tried anything complicated with Unicorn + Python in a month or two. Maybe try running the tests under pypy.

**Comment by petevine** [comment]
That was my original plan but then I found this issue :)

**Comment by petevine** [comment]
The python samples (and a few regression tests) run fine. So either we're not talking about the same tests or you were using an outdated pypy.

**Comment by lunixbochs** [comment]
I don't remember offhand what the exact problem was.

**Comment by lunixbochs** [comment]
Oh, found the problem. Exceptions thrown in callbacks are swallowed by cffi, but not ctypes.

**Comment by petevine** [comment]
The gist runs ok in pypy (albeit quietly) - maybe it could be made into a benchmark?

**Comment by lunixbochs** [comment]
The gist is a module you import instead of Unicorn, so running it directly does nothing.

**Comment by petevine** [comment]
Ah, sorry; did a quick copy/paste - any ideas for a benchmark?

**Comment by lunixbochs** [comment]
A loop doing HOOK_CODE would be good.
