### ISSUE TITLE
Mapping 0x100000000 from IDAPython fails (tested on OS X and Linux)

### ISSUE THREAD

**Issue by argp** [unicorn-engine/unicorn#602]
The following works from normal Python:

```
$ cat test-unicorn-2.py 
from unicorn import *
from unicorn.x86_const import *
from unicorn.arm_const import *
from unicorn.arm64_const import *

# import idaapi
# import idc
# import idautils

emu = Uc(UC_ARCH_ARM64, UC_MODE_ARM)

addr = 0x100000000
emu.mem_map(addr, 0x20000)
emu.mem_write(addr, b'\x00')

print 'ok'
$ python test-unicorn-2.py 
ok
```

Commenting in the IDAPython imports and running it from IDA I get:

```
/Users/argp/tmp/test-unicorn-2.py: Invalid memory write (UC_ERR_WRITE_UNMAPPED)
Traceback (most recent call last):
  File "/Users/argp/ida/idaq64.app/Contents/MacOS/python/idaapi.py", line 601, in IDAPython_ExecScript
    execfile(script, g)
  File "/Users/argp/tmp/test-unicorn-2.py", line 14, in <module>
    emu.mem_write(addr, b'\x00')
  File "/Library/Python/2.7/site-packages/unicorn/unicorn.py", line 305, in mem_write
    raise UcError(status)
UcError: Invalid memory write (UC_ERR_WRITE_UNMAPPED)
```

It seems to be related to [this issue](https://github.com/unicorn-engine/unicorn/issues/523).

Any ideas?

**Comment by argp** [comment]
[This patch](https://github.com/unicorn-engine/unicorn/pull/526/files) from [issue 526](https://github.com/unicorn-engine/unicorn/pull/526) seems to solve this bug for me.

I am leaving it open for the time being to do more testing.

**Comment by aquynh** [comment]
fixed now, please confirm.

**Comment by argp** [comment]
Confirmed (only tested on OS X though).

**Comment by aquynh** [comment]
On OSX (64bit), it always works. This fix just targets 32bit OS.

**Comment by aquynh** [comment]
Ah you mean tested in IDA 32bit.

**Comment by argp** [comment]
Both idaq and idaq64 are 32-bit binaries (on all platforms). I tested idaq64 (32-bit) on a latest OS X (64-bit).

**Comment by aquynh** [comment]
yes i know
