### ISSUE TITLE
Python bindings cannot load library from /usr/lib64

### ISSUE THREAD

**Issue by starfleetcadet75** [unicorn-engine/unicorn#603]
I have compiled Unicorn on my Debian system using Python 2.7 for the initial build and then used 3.5 for the Python bindings. Importing Unicorn then results in the message "ERROR: fail to load the dynamic library" which is caused by the bindings/python/unicorn/unicorn.py file. Looking through the file, it appears that it does not check for the library in /usr/lib64 which is where the makefile installs it on my system.

**Comment by aquynh** [comment]
fixed, thanks.
