### ISSUE TITLE
windows error code 0x80000026， A long jump has been executed.

### ISSUE THREAD

**Issue by geek-li** [unicorn-engine/unicorn#610]
when I set fs register value by using msvc project,will  drop this error ,I didn't know what happened!
just  like this :   

                        ` uint32_t value=0x7ffe;` 
                        `uc_reg_write(uc,UC_X86_REG_FS,&value);`
===========================

**Comment by geek-li** [comment]
and after some reversing work,I find some clues ,maybe own to cpu env is not initial properly.
and the call routines just like this:
cpu_x86_load_seg->helper_load_seg->raise_exception_err(env, EXCP0D_GPF, selector & 0xfffc);
uninitial env->cr[0]  raise the exception code executed:
![qq 20160810122610](https://cloud.githubusercontent.com/assets/5059057/17541862/480b03a8-5ef6-11e6-8c70-3808831ca58f.png)

**Comment by geek-li** [comment]
@lunixbochs @aquynh

**Comment by aquynh** [comment]
your setup is incomplete. see this sample code on how to setup GDT: https://github.com/unicorn-engine/unicorn/blob/master/tests/regress/x86_gdt.py

**Comment by geek-li** [comment]
thx

**Comment by geek-li** [comment]
@aquynh But there is no  UC_X86_REG_GDTR  register in  x86.h ,how  to  inital the GDTR in  msvc program?

**Comment by geek-li** [comment]
sorry, my unicron  is not the newest,now
