### ISSUE TITLE
UC_ERR_MAP Error

### ISSUE THREAD

**Issue by horsicq** [unicorn-engine/unicorn#616]
uc_err err1=uc_mem_map(uc,0x0018D000,0x00006000,UC_PROT_ALL); // UC_ERR_OK
uc_err err2=uc_mem_map(uc,0x100000000,0x002c0000,UC_PROT_ALL); // UC_ERR_OK

But in reverse:

uc_err err1=uc_mem_map(uc,0x100000000,0x002c0000,UC_PROT_ALL); // UC_ERR_OK
uc_err err2=uc_mem_map(uc,0x0018D000,0x00006000,UC_PROT_ALL); // **UC_ERR_MAP**

Tested on Windows 7 x64

**Comment by aquynh** [comment]
can you send a testcase for this, to put that under tests/regress/?

**Comment by horsicq** [comment]
Done.

**Comment by horsicq** [comment]
It' on 32bits Systems only because ram_addr_t in MemoryRegion is dword.

**Comment by aquynh** [comment]
fixed now, please confirm.

**Comment by horsicq** [comment]
It works perfectly.
