### ISSUE TITLE
Makefile deletes its work directory when used with Arch build system

### ISSUE THREAD

**Issue by 4577** [unicorn-engine/unicorn#629]
It is not possible to install Unicorn using the yaourt package manager, because the Makefile deletes its own work directory.

This is due to this line from the Makefile:

    ifdef BUILDDIR
	    rm -rf $(BUILDDIR)
    endif

Here, BUILDDIR is an environment variable set to /tmp/yaourt-tmp-$HOME/aur-unicorn by makepkg, and the root for all files used by yaourt to perform. As $BUILDDIR is removed, the installation process fails with an error.

Thus I am not sure about the reason of the presence of this, BUILDDIR being not set anywhere in the source and seeming to be primarily an Archlinux/makepkg-specific variable. Can this be explained?

**Comment by aquynh** [comment]
Do you have a solution for this? If you do, would you please send a pull req for that? Thanks

**Comment by aquynh** [comment]
if you remove all those BUILDDIR lines from Makefile, can you compile in Arch with `./make.sh`?

**Comment by 4577** [comment]
I can make the build process succeed by clearing the BUILDDIR (using "BUILDDIR= make" instead of "make"), so it seems that yes. (Only removing the rm line throws another error about not finding the .a later).

I was just willing to ask whether this Arch-specific code had a purpose before suggesting to remove it (:

**Comment by aquynh** [comment]
Please send a pull req to remove BUILDDIR.
