### ISSUE TITLE
how to deal with interrupt instruction more easily?

### ISSUE THREAD

**Issue by geek-li** [unicorn-engine/unicorn#632]
now,in unicorn for  "int n" instruction .there will be use hook callback function to execute some specical things which u  want, but obviously ,it's not a smooth way,a more easy is just use IDT in the initialty stage I think ,but I  find  it's hard to initialize  the IDT and run the program correctly.Anyone have a good idea?

**Comment by aquynh** [comment]
why the current approach is "not a smooth way"?

**Comment by geek-li** [comment]
what I means is execute interrupt instruction  automatically,which by initialized IDT and  then just  dispatch the multiple interrupt instructions instead to hook  int  instructions.
