### ISSUE TITLE
why can't change eip value in int ins hook callback function?

### ISSUE THREAD

**Issue by geek-li** [unicorn-engine/unicorn#633]
after execute int 0x80 instruction,in the callback routine and then write value to eip,seems no error return ,but eip don't changed ,what's the reason ?

**Comment by lunixbochs** [comment]
flag and pc register writes should trampoline. I can fix this at the same time as #512

**Comment by geek-li** [comment]
@lunixbochs ok,I find another way  to chinange eip. when excute "int xxx"  ins,which is  change eip in code hook  callback .

**Comment by lunixbochs** [comment]
hrm, reg_write(EIP) already trampolines. can you post a test case?

**Comment by geek-li** [comment]
well  I means u can change eip when u find the executed ins is int xxx which u can change the eip value in code hook callback and in the same time int ins hook callback well not be called .
