### ISSUE TITLE
License unclear:  "GPLv2 only" or "GPLv2 or later"

### ISSUE THREAD

**Issue by JayFoxRox** [unicorn-engine/unicorn#634]
COPYING and README claim this is GPL, but it doesn't specify which version exactly? It looks like GPLv2, the question is: "GPLv2 only" or "GPLv2 or later"?
The current uc.c only contains a copyright where it's unclear wether that file also belongs to GPL'd code.
The source files or README should contain [the license text as per COPYING file](https://github.com/unicorn-engine/unicorn/blob/master/COPYING#L288), where it would be made clear if "or later" applies.

I'd strongly prefer the "GPLv2 or later" because the qemu portions which are "GPLv2 only" seem to be gone?
As far as my understanding goes, if that is the case unicorn-engine could be used as LGPL (which I intend to do, so I can possibly license my project differently to avoid commercial use by certain parties).

Making unicorn a "GPLv2 only" library would be really bad because it means any project using it would also have to be GPL.

**Comment by aquynh** [comment]
i prefer LGPL as well, but there is no clear evidence that we can use that for QEMU code. if you have a convincing proof, let me know.

uc.c can be in LGPL if there rest is.
