### ISSUE TITLE
get_clock() is not monotonic (on non _WIN32)

### ISSUE THREAD

**Issue by JayFoxRox** [unicorn-engine/unicorn#635]
`get_clock` (include/qemu/timer.h) is  used in the timeout calculation (and probably in various other places too?). However, that timer is _not_ monotonic and might jump between loop iterations.
This probably makes it possible to jump back in time after `uc_emu_start` which would mean the timeout won't trigger as expected.

This is partially an upstream (documentation) issue. Unicorn trips on it.

---

Here is a rundown of the involved components:

**[gettimeofday manpage](http://man7.org/linux/man-pages/man2/gettimeofday.2.html)**

"The time returned by gettimeofday() is affected by discontinuous jumps in the system time (e.g., if the system administrator manually        changes the system time). If you need a monotonically increasing clock, see clock_gettime(2)."

**[Unicorn timer.h (get_clock_realtime)](https://github.com/unicorn-engine/unicorn/blob/master/qemu/include/qemu/timer.h#L631:)**

The comment reads `/* real time host monotonic timer */` but the function internally uses the non-monotonic `gettimeofday`.

([This documentation errror also exists upstream!](https://github.com/qemu/qemu/blob/master/include/qemu/timer.h#L800))

**[Unicorn timer.h (get_clock)](https://github.com/unicorn-engine/unicorn/blob/master/qemu/include/qemu/timer.h#L657)**

This calls `get_clock_realtime` internally which, as I've just shown, is _not_ monotonic.
So if the system time changes, the timeout calculation will fail.

(This issue does _not exist_ upstream)

**[QEMU timer.h (get_clock)](https://github.com/qemu/qemu/blob/master/include/qemu/timer.h#L826)**

Note that they are aware of the previously mentioned monotonic-issue: `/* XXX: using gettimeofday leads to problems if the date changes, so it should be avoided. */`
They have a precompiler check for `CLOCK_MONOTONIC` which resolves the issue.

---

This issue only affects posix. Windows already uses the monotonic performance counters.

**Comment by aquynh** [comment]
this is interesting! can you come up with a fix?

**Comment by JayFoxRox** [comment]
Why was this closed?

**Comment by wtdcode** [comment]
> Why was this closed?

Thanks for your interest. You could have a try on our new version: Unicorn2 on dev branch. If the problem still exists, please re-open this issue.

**Comment by wtdcode** [comment]
> Why was this closed?

Confirmed. Re-open.

**Comment by wtdcode** [comment]
Manually fixed in 81942e9
