### ISSUE TITLE
"Thread-safety by design" not true

### ISSUE THREAD

**Issue by JayFoxRox** [unicorn-engine/unicorn#636]
There are various race conditions in Unicorn.

Take `uc_emu_stop` for example:

```
if (uc->current_cpu) {
  // exit the current TB
  cpu_exit(uc->current_cpu);
}
```

`cpu_exit` operates directly on variables of the referenced CPU struct. So we can't pass a null pointer.
However, the check is useless here because another thread might have finished `cpu_exec` first which will set `current_cpu = NULL` between check and use of it.
This is _probably_ the reason why [this comment](https://github.com/unicorn-engine/unicorn/blob/9a2a5b15d8ae1e65a58b066d8b585a7e6fa77bec/qemu/cpu-exec.c#L292) exists: "fail safe : never use current_cpu outside cpu_exec()".

The solution would probably be to add a mutex around these variables, or to find a different solution altogether.

**Comment by aquynh** [comment]
that is right. can you add a mutex & send a pull req?

**Comment by danghvu** [comment]
I think "by designed" means you use different context for different thread, do you mean to share one context with multiple threads -- if that's the case there are much more variable to worry about.

**Comment by lunixbochs** [comment]
I think due to the design of Unicorn versus QEMU it makes more sense to remove "multiple cpu" support for a single uc instance, then don't set `current_cpu = NULL` (and ensure uc->cpu is always stable).

**Comment by JayFoxRox** [comment]
@danghvu note that this does even happen internally. The emulation runs on the main thread. However if a duration-timeout is specified the timeout thread (!) will come into action and call `uc_emu_stop()` (which may create a race condition if the main thread finishes while `uc_emu_stop` is performed on the timeout thread). If UC claims it's thread safe by design then it should have these mutexes internally if necessary?

@lunixbochs I think this is a major design decision to be made. I'm currently running a Windows 32 bit game in Unicorn Engine on Linux. The game uses 2 threads and I'm currently using a single UC instance to simulate both threads. I use the uc_reg_read/write to move the context around (which is probably bad, but shouldn't cause any issues). However, I get a lot of random errors / miscalculations, especially if lowering the thread quantum
I think if Unicorn supported multiple virtual CPUs / threads per instance I could solve these issues.
I don't think a "multiple cpu" interface is even exposed by UC yet?
(This probably should have its own issue?)

---

I'm not sure when I'll find time to add this. I also feel like it might open a can of worms if I try to fix it, as I'm not sure if there are other cases which have to be guarded.

**Comment by lunixbochs** [comment]
The underlying QEMU SMP interface can't be easily exposed by Unicorn so it's just broken right now. I think properly supporting SMP would be a significantly harder problem than removing it for the time being.

**Comment by aquynh** [comment]
yes we can remove multiple CPU support. please send pull req for this.

**Comment by lunixbochs** [comment]
PR #643 - it also obsoletes `uc->current_cpu` which should be replaced with some other flag

**Comment by aquynh** [comment]
it seems current_cpu can be removed. same for cpu_index?
