### ISSUE TITLE
allow grouping unicorn handles for SMP, TLB operations, etc

### ISSUE THREAD

**Issue by lunixbochs** [unicorn-engine/unicorn#642]
related to removing multiple CPU support

https://github.com/unicorn-engine/unicorn/issues/636#issuecomment-249103954

maybe an API to have TLB flush happen manually, or the ability to put multiple unicorn handles in a shared TLB flush or memory group of some kind?

any other SMP operations should be supported across unicorn cpu groups as well

Here are some spots where it matters:

https://github.com/unicorn-engine/unicorn/blob/fe96e8325b60ced08ce5eaa7bf09bf58878167d4/qemu/target-arm/helper.c#L290
https://github.com/unicorn-engine/unicorn/blob/fe96e8325b60ced08ce5eaa7bf09bf58878167d4/qemu/target-mips/op_helper.c#L1804

MWAIT https://github.com/unicorn-engine/unicorn/blob/fe96e8325b60ced08ce5eaa7bf09bf58878167d4/qemu/target-i386/misc_helper.c#L581

**Comment by aquynh** [comment]
this looks good, except some functions should have deadcode cleaned, like tlbimvaa_is_write().

since this pull req means no more SMP, what do you mean by supporting other SMP operations?

what do you mean with the links above?

**Comment by aut0** [comment]
I noticed that this commit https://github.com/unicorn-engine/unicorn/commit/cb615fdba778939108f59a9507c9d033fa74ddc2 comments out tlb_flush() in qemu/target-arm/helper.c. There is a TODO there leading to this issue. Why is tlb_flush() commented out? It took considerable time to debug this, maybe there could be an assert there?

**Comment by lunixbochs** [comment]
Because no `other_cpu` in Unicorn.

**Comment by aut0** [comment]
I think the user of the emulator should be made aware that a tlb_flush is supposed to have happend. Unicorn does not really support using the MMU anyways so maybe that's not too important, but still putting an assert there is better than nothing IMHO. If one were to make the MMU work again, doing nothing for a tlb_flush without even printing an error, is pretty hard to find. At least it took me quite some time. My PR remains unmerged though.

Regarding the tlb_flush. I think for the instructions that flush only the main cpu tlb they could have been kept. Also copypasting this code fragement there for all tlb instructions is kind of misleading.

**Comment by lunixbochs** [comment]
All of the modified TLB instructions flushed every CPU. It’s fine to make them flush just the uc->cpu if that fixes a bug for you. If there’s still another issue with unicorn’s mmu breaking guest TLB you should open a new github issue to track it.
