### ISSUE TITLE
new api request:get host address and get guest address

### ISSUE THREAD

**Issue by geek-li** [unicorn-engine/unicorn#644]
I think it's useful to add this feature for users to debug their pogram ,when they want to know the virtual unicorn memory status.

**Comment by lunixbochs** [comment]
You want Unicorn to do address translation for you and tell you where guest pages are actually located in memory? I don't know if I like crossing the API boundary like that.

You should be able to do this yourself with `uc_mem_map_ptr()` anyway.

**Comment by geek-li** [comment]
@lunixbochs  
 uc_mem_hostaddr(guestaddr,&hostaddr);//guestaddr is unicorn mapped address ,hostaddr is the real address which getted by this function;
the following is just another direct,used to get unicorn mapped address by real memory address
 uc_mem_guestaddr(hostaddr,&guestaddr)
====
I think it's useful when u want to managent ur unicorn memory dynamically，and write or read ur unicorn quickly and  with a  good performance

**Comment by lunixbochs** [comment]
`uc_mem_map_ptr()` should already solve all of your concerns here - it allows you to assign a host memory page to back a Unicorn guest region. If you do this, you'll implicitly know the backing address for guest memory and can do all of the things you say. Keep in mind this won't flush caches (and neither will your proposal).

**Comment by geek-li** [comment]
@
