### ISSUE TITLE
invalid-shift-exponent  in normalizeFloatx80Subnormal_x86_64 

### ISSUE THREAD

**Issue by felixgr** [unicorn-engine/unicorn#645]
We found a UBSan error which crashes unicorn. I don't think it has security impact.

`echo '2MbYKLr+uri6ura6usnYAAyn0Ngp2CgMICUnFokS3RQnIbiNyigVedghySHW1dXV1dXVgtXV1dXV1dXVCgoK3g==' | base64 -d > repro_normalizeFloatx80Subnormal_x86_64`

Offending line:

`*zSigPtr = aSig<<shiftCount;`

`unicorn/src/qemu/fpu/softfloat.c:672:20: runtime error: shift exponent 64 is too large for 64-bit type 'uint64_t' (aka 'unsigned long')`

```
#0 in normalizeFloatx80Subnormal_x86_64 unicorn/src/qemu/fpu/softfloat.c:672:20
#1 in addFloatx80Sigs_x86_64 unicorn/src/qemu/fpu/softfloat.c:4996:13
#2 in floatx80_add_x86_64 unicorn/src/qemu/fpu/softfloat.c:5100:16
#3 in helper_fadd_ST0_FT0 unicorn/src/qemu/target-i386/fpu_helper.c:413:11
```

**Comment by aquynh** [comment]
could you provide the source code of the testcase `repro_normalizeFloatx80Subnormal_x86_64`?

**Comment by aquynh** [comment]
do you have this issue with original Qemu?

**Comment by felixgr** [comment]
I didn't check original Qemu.

```
#define ADDRESS 0x10000

struct CleanUpHandle {
  uc_engine *handle;
  ~CleanUpHandle() { uc_close(handle); }
};

extern "C" int LLVMFuzzerTestOneInput(const uint8_t* code_data,
                                      size_t code_size) {
  CleanUpHandle H;
  uc_err err;
  int ecx = 0x12345678;

  err = uc_open(UC_ARCH_X86, UC_MODE_32, &H.handle);
  if (err != UC_ERR_OK) {
    return 0;
  }

  err = uc_mem_map(H.handle, ADDRESS, 0x1000, UC_PROT_ALL);
  if (err != UC_ERR_OK) {
    return 0;
  }

  err = uc_mem_write(H.handle, ADDRESS, code_data, code_size);
  if (err != UC_ERR_OK) {
    return 0;
  }

  err = uc_reg_write(H.handle, UC_X86_REG_ECX, &ecx);
  if (err != UC_ERR_OK) {
    return 0;
  }

  err = uc_emu_start(H.handle, ADDRESS, ADDRESS + code_size, 0, 1);
  if (err != UC_ERR_OK) {
    return 0;
  }

  err = uc_reg_read(H.handle, UC_X86_REG_ECX, &ecx);
  if (err != UC_ERR_OK) {
    return 0;
  }

  return 0;
}
```

**Comment by danghvu** [comment]
Reference code in upstream qemu: https://github.com/qemu/qemu/blob/master/fpu/softfloat.c#L731

Looks the same as in unicorn, unless they have some check earlier to prevent this. It happens when value `aSig` is `0`, which makes number of leading zero `64`. 

To please the sanitizer we may want change it to: `shiftCount = countLeadingZeros64( aSig ) % 64`
