### ISSUE TITLE
invalid-shift-exponent in tb_invalidate_phys_page_fast_x86_64 

### ISSUE THREAD

**Issue by felixgr** [unicorn-engine/unicorn#646]
We found a UBSan error which crashes unicorn. I don't think it has security impact.

`third_party/unicorn/src/qemu/translate-all.c:1428:42: runtime error: shift exponent 54 is too large for 32-bit type 'int'`

Offending line:

`b = p->code_bitmap[BIT_WORD(nr)] >> (nr & (BITS_PER_LONG - 1));`

Stack trace:

```
#0 in tb_invalidate_phys_page_fast_x86_64 third_party/unicorn/src/qemu/translate-all.c:1428:42
#1 in notdirty_mem_write third_party/unicorn/src/qemu/exec.c:1386:9
#2 in access_with_adjusted_size_x86_64 third_party/unicorn/src/qemu/memory.c:555:13
#3 in memory_region_dispatch_write_x86_64 third_party/unicorn/src/qemu/memory.c:1195:9
#4 in io_writeb_x86_64 third_party/unicorn/src/qemu/softmmu_template.h:633:5
#5 0x1e8c7e6 in helper_ret_stb_mmu_x86_64 third_party/unicorn/src/qemu/softmmu_template.h:739
#6 in helper_le_stq_mmu_x86_64 third_party/unicorn/src/qemu/softmmu_template.h:765:13
#7 in cpu_stq_data third_party/unicorn/src/qemu/include/exec/cpu_ldst_template.h:127:9
#8 in helper_fstt third_party/unicorn/src/qemu/target-i386/fpu_helper.c:85
#9 in helper_fsave third_party/unicorn/src/qemu/target-i386/fpu_helper.c:1052
```

Reproduce:

`echo 'Z91z/////4h+' | base64 -d > repro_tb_invalidate_phys_page_fast_x86_64`

**Comment by aquynh** [comment]
could you provide the source code of the testcase `repro_tb_invalidate_phys_page_fast_x86_64`?

**Comment by danghvu** [comment]
same code upstream qemu : https://github.com/qemu/qemu/blob/master/translate-all.c#L1577

Not sure what is the implication of this sanitizer alert ?

**Comment by egberts** [comment]
This is still open.

**Comment by wtdcode** [comment]
> This is still open.

By how? Could you provide a reproduction script?

**Comment by wtdcode** [comment]
Link to #1449 for further examination. If no more information is provided, I would close it again after a week or so.

**Comment by wtdcode** [comment]
I checked it manually and the `nr` is already unsigned int. Closed.
