### ISSUE TITLE
OSX compilation error

### ISSUE THREAD

**Issue by 0xmilkmix** [unicorn-engine/unicorn#647]
Using either the 0.9 tarball or clone, I get this error while compiling using ./make.sh on OSX
/usr/local/Cellar/glib/2.50.0/include/glib-2.0/glib/gtypes.h:423:3: error:      '_GStaticAssertCompileTimeAssertion_0' declared as an array with a negative size

glib: stable 2.50.0 (bottled)
--universal

Any idea what could be wrong?

**Comment by aquynh** [comment]
Did you follow the docs? There are some dependency that you must install
first.

Also, you should use the latest Github cide, not 0.9, since we fixed many
issues since.

**Comment by 0xmilkmix** [comment]
Yes, followed the docs and compiled glib in both 32 and 64 bits. pkg-config installed as well

**Comment by aquynh** [comment]
Do you have same issue with Github code?

What is your clang version?

**Comment by 0xmilkmix** [comment]
Yes
glib header was included from unicorn/qemu/include/glib-compat.h:19
clang  is "Apple LLVM version 7.3.0 (clang-703.0.29)"

**Comment by aquynh** [comment]
something must be wrong with your setup, as i have the same glib version, and use clang-703.0.31, but have no issues at all.

if you figure out what is wrong, please report back here.

**Comment by 0xmilkmix** [comment]
will continue looking into this and keep you informed. Thanks

**Comment by 0xmilkmix** [comment]
Solved it:
$ export CC=clang
$ ./make.sh macos-universal

**Comment by aquynh** [comment]
interesting. what was the default CC then?

**Comment by 0xmilkmix** [comment]
strange thing is that env variable wasn't defined...

**Comment by aquynh** [comment]
so you can compile now, but dont have universal binary? 

are you sure that you install glib with universal format? if you are not, then install again with:

    $ brew unlink glib
    $ brew install glib --universal

**Comment by 0xmilkmix** [comment]
unfortunately it does not solved the issue. Pulled the latest version this morning and it does not changed the outcome.

**Comment by aquynh** [comment]
sorry, cant tell what is wrong with your system. Travis now compiles on OSX without any issues.

**Comment by stephengroat** [comment]
@0xmilkmix if you look at the .travis.yml in #666, i now build MACOS_UNIVERSAL builds in travis

**Comment by ludwigschwardt** [comment]
For folks tracking down the general glib bug: I had better luck by setting the `ARCHFLAGS="-arch x86_64"` environment variable before the build, while fixing the obit formula in my Homebrew tap (ska-sa/homebrew-tap).

**Comment by corydodt** [comment]
@ludwigschwardt thanks, this also fixes it for me!
