### ISSUE TITLE
ARM: read / write coprocessor via API

### ISSUE THREAD

**Issue by mothran** [unicorn-engine/unicorn#652]
I am currently trying to emulate a usermode ARM process and ran into some issues with the Android TLS system, in order to get thread locals such as thread ID and other components, the process attempts to read the coprocessor registers, example:

```
mrc     p15, #0, r2, c13, c0, #3
```

Which reads the Read only coprocessor for thread locals (http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0344k/Babeihid.html)

Tracking it down in QEMU I found that this specific variable SHOULD be the referenced registers:
https://github.com/unicorn-engine/unicorn/blob/master/qemu/target-arm/cpu.h#L215

Along side that should be the other coprocessor registers as well. 

I was going to start attempting to include these coprocessors into the uc_arm_reg structure and implement read / write functions for the registers I needed.  But first I wanted to open this issue and request feedback about naming convention for the coprocessor registers and if there is and better way I should implement this feature. 

I wanted to provide a more light weight method than introducing a injected code sub as per these two tickets: #446 and #571

Thanks.

**Comment by aquynh** [comment]
yes, please go ahead to support these registers, and send pull req when you are done.

there are many registers inside cp15. perhaps we should expose this struct, and perform read/write to the whole struct?

**Comment by mothran** [comment]
It would make the registers much cleaner in that case.  Would you expose it as a member of the uc_engine handle, or as a new API method?

Also the actual variable names inside of the cp15 struct are a little obtuse, if we implement them as individual registers it could a much more clear translation for the unicorn user.  For example:

```
mrc     p15, #0, r2, c13, c0, #3
```
Becomes (or something similar):
```
UC_ARM_REG_CP13_C0_3
```
vs:
```
cp15.tpidrro_el0
```
What are your thoughts?

**Comment by aquynh** [comment]
I think we can do both.

**Comment by mothran** [comment]
Great, do you have any examples of exposing structs like that via the API that I can try and model my code after?

**Comment by aquynh** [comment]
you can copy the struct `cp15` to include/unicorn/arm.h, then add code so that we can read/write  to the whole struct with new register `UC_ARM_REG_CP15`. 

we did something similar for XMM register before, you can take a look at this: https://github.com/unicorn-engine/unicorn/commit/4a8f52ae7f24e9dbbf05d792a91825cdffe7b54d

**Comment by jbcayrou** [comment]
Hi,

I have developped a patch to read/write ARM coproc registers with a generic way.
https://github.com/unicorn-engine/unicorn/compare/master...jbcayrou:arm_cpregs_access
I would like your comments before creating a pull request.

**Details**

In qemu coproc registers are describe with a ARMCPRegInfo structure

```
struct ARMCPRegInfo {

    const char *name;

    uint8_t cp;
    uint8_t crn;
    uint8_t crm;
    uint8_t opc0;
    uint8_t opc1;
    uint8_t opc2;

    //[...]

    ptrdiff_t fieldoffset; /* offsetof(CPUARMState, field) */

    CPReadFn *readfn;

    CPWriteFn *writefn;

    CPReadFn *raw_readfn;

    CPWriteFn *raw_writefn;

    CPResetFn *resetfn;
};
```

This structure contains interesting information: 
- Configuration of registers (cp, crn, crm ... )
- The qemu internal variable containing the value (fieldoffset)
- function handlers to read/write them (readfn, writefn)

Here an example with the description of the 'CPARC' register :

```
    { "CPACR", 0,1,0, 3,0,2, ARM_CP_STATE_BOTH, 
      0, PL1_RW, NULL, 0, offsetof(CPUARMState, cp15.c1_coproc),
      NULL, NULL, cpacr_write },
```


The patch gets  `ARMCPRegInfo` structs using the 'configuration' of coproc registers (cp, crn, crm, ops ..). In this way if internal cp15.* attributes change it will still work and new coproc registers in future version of qemu will work in unicorn without modifications.

A `ARM/ARM64_CP_REGS_INFO `table contains the correspondance between UC_REG_NAME and (cp, crn, crm, op0, op1, op2)

```
const uc_arm_cp_reg ARM64_CP_REGS_INFO[] =  {
    //{ UC_ARM64_REG_XXXXX,           cp, crn,crm,opc0,opc1,opc2 }

    // Manual entries

    // Automatical generated entries
    UC_ARM64_CPREG_INFO_LIST       // C macro, see arm_cpgreg_info.h
};
```

`UC_ARM64_CPREG_INFO_LIST` is a macro that contains all coproc registers.
Coproc registers are automatically generated from ARM XML documentation (https://developer.arm.com/products/architecture/a-profile/exploration-tools) and can be regenerated runing `./utils/gen_arm_cpregs.sh`
This script generates following files :
- include/unicorn/[arm/arm64]_cpreg.h : contains register enums
- qemu/target-arm/[arm/arm64]_cpreg_info.h : contains translation table described above.

Generated registers are included in uc_arm64_reg of  include/unicorn/[arm/arm64].h using a macro to integrate them with manual defined `uc_arm64_reg`
Example with arm.h
```
    //> CP registers
    UC_ARM64_CPREG_LIST       // C macro, see arm64_cpgreg.h

    UC_ARM64_REG_ENDING,		// <-- mark the end of the list of registers

    //> alias registers

    UC_ARM64_REG_IP1 = UC_ARM64_REG_X16,
    UC_ARM64_REG_IP0 = UC_ARM64_REG_X17,
    UC_ARM64_REG_FP = UC_ARM64_REG_X29,
    UC_ARM64_REG_LR = UC_ARM64_REG_X30,
} uc_arm64_reg;
```

Test `/test/regress/arm_enable_fvp.c` works after these modifitcations.

In addition of standard read/write registers,  two dedicate functions `arm_cpreg_read` and `arm_cpreg_write` were added to use coproc with (cp, crn, crm, ops).


**Bindings Issue**

C macro are not correctly parsed by `const_generator.sh` and generated enum registers are not visible in bindings. (And possibly this produces wrong enum values)
To solve it, _bindings/Makefile_ was modified to create intermediary header file with macro expanded. (`gcc -E` command)

https://github.com/unicorn-engine/unicorn/compare/master...jbcayrou:refactor_const_generator

So coproc patch needs this 'const_generator' patch before.

In bindings folder, `make test` does not reveal any issue.
 
 


What do you think about these modifications ?

**Comment by aquynh** [comment]
wow nice work! 

after a quick look, in general this looks fine. however, since it removes UC_ARM_REG_C1_C0_2 & so on, it breaks compatibility. what do you think about keeping these, for ex by some alias mapping, so no apps break?

**Comment by jbcayrou** [comment]
Thanks :)

Yep good idea, i added these aliases.

Moreover I patched the generation script, some generated registers were not correct due to a python bug. Now it is ok.

**Comment by mothran** [comment]
Thanks @jbcayrou!  Your solution is much more complete than mine.

**Comment by jbcayrou** [comment]
I hope all will work correctly :)

Do you have a project/use case (more complexe than `arm_enable_fvp.c`) on which you can test this solution ?

**Comment by mothran** [comment]
Yes, it will take me some time to get back into that code but I will try and verify it for you later.

**Comment by jbcayrou** [comment]
Ok thank you !

**Comment by jbcayrou** [comment]
Any news ?

@aquynh, Do you want I open a pull request ?

**Comment by aquynh** [comment]
yes please go ahead with a PR - for the "next" branch.
