### ISSUE TITLE
some error when run the same code

### ISSUE THREAD

**Issue by seem111** [unicorn-engine/unicorn#653]
when I run the code from the network and the local disk. I got different result. As you can see the result like:
the code is \x01\x00\x8F\xE2\x10\xFF\x2F\xE1\x00\x20\xD5\x27\x00\xDF\x02\x20\x01\x21\x06\x22\xFA\x27\x1F\x37\x00\xDF\x04\x1C\x0D\xA1\x10\x22\xFA\x27\x21\x37\x00\xDF\x20\x1C\x00\x21\x3F\x27\x00\xDF\x20\x1C\x01\x21\x3F\x27\x00\xDF\x20\x1C\x02\x21\x3F\x27\x00\xDF\x07\xA0\x00\x21\x02\xB4\x01\xB4\x69\x46\x00\x22\x0B\x27\x00\xDF\x00\x20\x01\x27\x00\xDF\x02\x00\x08\xAE\x0A\x00\x02\x02\x2F\x73\x79\x73\x74\x65\x6D\x2F\x62\x69\x6E\x2F\x73\x68\x00\x00

 1) network
current RIP is 0
address 0:add	r3, pc, #1
current RIP is 4
address 4:bx	r3
current RIP is 8
address 8:andlo	r4, sl, r8, ror r6
current RIP is 12
address c:stmdbge	r1, {r0, ip, pc}
current RIP is 16
current RIP is 20
address 14:svchs	#0x2fdf01
current RIP is 24
address 18:svchs	#0x6e6962

2)local disk
RIP is 0
address 0:add	r3, pc, #1
current RIP is 4
address 4:bx	r3
current RIP is 8
address 8:mov	r0, pc
current RIP is 10
address a:adds	r0, #0xa
current RIP is 12
address c:str	r0, [sp, #4]
syscall:setuid32
current RIP is 14
address e:add	r1, sp, #4
current RIP is 16
address 10:subs	r2, r2, r2
current RIP is 18
address 12:movs	r7, #0xb
current RIP is 20
address 14:svc	#1
current RIP is 22
address 16:cmp	r7, #0x2f
current RIP is 24
address 18:ldr	r2, [r4, #0x14]
current RIP is 26
address 1a:cmp	r7, #0x6e
current RIP is 28
address 1c:ldr	r3, [r6, #4]
current RIP is 30
current RIP is 32
current RIP is 34
current RIP is 36
current RIP is 38
current RIP is 40
current RIP is 42
current RIP is 44
current RIP is 46
current RIP is 48
syscall:dup2
current RIP is 50
current RIP is 52
current RIP is 54
current RIP is 56
syscall:dup2

WHY?

**Comment by aquynh** [comment]
without more details, it is impossible to tell. can you post your code?

**Comment by seem111** [comment]
ok, it's my fault. There is the bug in my code. Thanks all the same.
