### ISSUE TITLE
Emulating an ARM based binary and call a function at a specified address, possible?

### ISSUE THREAD

**Issue by LaChancla0** [unicorn-engine/unicorn#657]
Just discovered Unicorn and I found it amazing. 
What Im a trying to do is loading an ARM binary into Unicorn which somewhere at address 0xYYYYYY has a func(R0,R1) method and I would like to 'start' the emulation from that address.

Is this possible with Unicorn? In the example provided is only shown how to 'manually' write some ARM code at a specified address but not how to load a full binary.

If this possible would it be possible to get some pointers to achieve this?

Thank you

**Comment by Nukem9** [comment]
AFAIK Unicorn doesn't provide any binary loading functions - just emulation, which means you need to write an ARM (elf?) loader by yourself. The executable regions can then be mapped with `uc_mem_map()`.

[Usercorn](https://github.com/lunixbochs/usercorn) might be helpful for you.

**Comment by aquynh** [comment]
we have the API `uc_mem_map_ptr()` to map a pointer in, which may interests you. see the sample at https://github.com/unicorn-engine/unicorn/blob/master/samples/sample_x86.c#L286
