### ISSUE TITLE
update bindings to support uc_context_save() & uc_context_restore()

### ISSUE THREAD

**Issue by aquynh** [unicorn-engine/unicorn#662]
attention: @sashs, @enkomio, @adrianherrera, @cseagle, @xorstream, @lunixbochs.  

recently we have new APIs `uc_context_save()` & `uc_context_restore()`. at the moment, only Python binding supports these API.

thus we need to update other bindings: .Net, Go, Haskell, Java, msvc & ruby. 

thanks!

**Comment by adrianherrera** [comment]
Please see PR #667

**Comment by aquynh** [comment]
Haskell binding now is updated, thanks!

**Comment by adrianherrera** [comment]
BTW could we please have a sample in `samples/` that uses the `uc_context_*` functions? It is helpful to have something to test against for the bindings.

**Comment by danghvu** [comment]
@adrianherrera There is a test here, and another one in the unit test.
https://github.com/unicorn-engine/unicorn/blob/master/bindings/python/sample_x86.py#L315

**Comment by adrianherrera** [comment]
Oh cool, thanks! I'll copy that Python one

**Comment by aquynh** [comment]
yes the C sample for these context API is still missing. pull req to add one is welcome.

**Comment by adrianherrera** [comment]
PR made. See PR #669

**Comment by aquynh** [comment]
excellent, thanks a lot, @adrianherrera! now we have a sample code in C for these API: https://github.com/unicorn-engine/unicorn/blob/master/samples/sample_x86.c#L672-L769

**Comment by aquynh** [comment]
we are moving towards v1.0 release, in few weeks. can you guys please update your bindings before that? most of the work is to add new APIs (since v0.9): uc_query, uc_reg_write_batch, uc_reg_read_batch, uc_mem_map_ptr, uc_mem_regions, uc_context_alloc, uc_context_save & uc_context_restore.

last time i checked, only Python & Haskell fully support all these new APIs.

**Comment by adrianherrera** [comment]
Actually the Haskell bindings don't support all of those APIs. It is missing uc_reg_write_batch, uc_reg_read_batch and uc_mem_map_ptr. I'll look at implementing them as soon as I can.

**Comment by lunixbochs** [comment]
The Go bindings support all of these APIs: https://godoc.org/github.com/unicorn-engine/unicorn/bindings/go/unicorn#Unicorn

**Comment by cseagle** [comment]
I basically don't know go, but how do the go bindings support batch read/write of FPU/MMR etc (ie anything larger than uint64) since the functions take []uint64 and you derive pointers to each uint64 in your helpers. Are the uint64 themselves opaque somehow?

**Comment by lunixbochs** [comment]
The Go bindings don't support special registers through the normal APIs yet. There's a special function for x86 mm registers. Was hard to reconcile with the type system and performance. I might just implement an opaque byte array special register read/write function.

**Comment by cseagle** [comment]
That's basically where I am with the Java bindings. Special registers are a slippery slope. I barely have a handle on all the x86 oddities. I have no idea whether any of the other archs support anything larger than a 64-bit integer register type, but special cases would need to be added to deal with any of them.

**Comment by aquynh** [comment]
turn out we need an API to free memory allocated by `uc_mem_regions()`, see https://github.com/unicorn-engine/unicorn/pull/373

i think we should rename `uc_context_free()` to `uc_mem_free()`, and we use this API to free memory allocated by both `uc_context_alloc` & `uc_mem_regions`. (i also thought about `uc_free`, but `uc_mem_free` seems a better name)

if there is no objection, i will make this change in the core & all the bindings (so binding authors do not need to update your bindings)

**Comment by cseagle** [comment]
Why? With the elimination of the glib dependency, uc_mem_regions pointers should be able to be passed straight to free correct? In fact why do we have uc_context_free since a uc_context allocated by uc_context_alloc can also be passed straight to free?

**Comment by aquynh** [comment]
in the above link, you can see that Windows code is using unicorn.dll library created by Msys. if we just use free(), this would mix Windows heap management code with Msys heap management code (note that free() of Windows & free() of Msys work differently). 

so to be safe, the memory allocated by Msys must be freed by Msys as well. for this reason, we need to have an API to ensure that we allocate & free memory in compatible way.

**Comment by cseagle** [comment]
This leads to the question, why is msys needed anymore following the elimination of glib? Does anyone have the chops to create a Visual studio solution file for unicorn? The incompatibility stems from the fact that mingw links against msvcrt.dll while anyone using Visual Studio is linking against MSVCRxxx.dll.

Also, the g_free function in glib_compat already does what you want to do with a uc_mem_free.

**Comment by aquynh** [comment]
so this line is actually wrong https://github.com/unicorn-engine/unicorn/blob/master/tests/regress/mem_64_c.c#L35, as we must not use `free()` there (but our own API)

@cseagle yes, that is g_free(), but we still need an API so user can free those memory allocated by Unicorn.

would love to use VS instead of Msys. i dont know if anybody is willing to do this, though.

**Comment by aquynh** [comment]
btw, looks like we can remove all those pthread code now, thus make it easier to port to Visual Studio later. anybody wants to work on this?

**Comment by cseagle** [comment]
Is it generally agreed that none of the mutex and thread signaling code is needed because there is exactly one cpu thread?

If that is the case then this task might boil down to replacing the timeout thread with platform specific timers to handle the timeout value.

**Comment by aquynh** [comment]
yes i just removed lots of redundant sync code in qemu/util/qemu-thread-xxx

now the only code depends on pthread is the timer to stop emulation regarding the `timeout` param of `uc_emu_start()`.

**Comment by aquynh** [comment]
@cseagle, @lunixbochs, @adrianherrera: i just committed a change to rename uc_context_free() to uc_mem_free(), in https://github.com/unicorn-engine/unicorn/commit/fdbbdc6216af3bacd1f61c149a5660bf51062dfe. please double check to make sure i did not make any mistakes when modifying your bindings.

**Comment by aquynh** [comment]
@lunixbochs, turn out my last commit broke the Go binding: https://travis-ci.org/unicorn-engine/unicorn/jobs/190238018. can you fix this for me?

**Comment by aquynh** [comment]
@cseagle, what do you think can be the remaining issues that we need to fix towards supporting Visual Studio?

**Comment by sashs** [comment]
Hey, I will update the ruby bindings this week.

**Comment by adrianherrera** [comment]
Haskell bindings look fine. I'll update the missing features this week.

**Comment by lunixbochs** [comment]
I think uc_mem_free is confusing because there's also uc_mem_map etc which all talk about guest regions. I vote uc_free.

**Comment by cseagle** [comment]
Off the top of my head, dealing with stdint.h which is not present in Visual Studio (at least older version like VS2010), and figuring out some way to approximate what ./configure does for qemu and how to deal with config-host.h.

There are probably other things as well.

**Comment by cseagle** [comment]
I concur, if this is a general purpose UI to free memory allocated internally to unicorn, then uc_free makes the most sense

**Comment by aquynh** [comment]
Ryan, i considered that too, but then went with uc_mem_free because (1) this is about memory, so the name is more clear (2) i already documented this API in unicorn.h, making it more clear.

But if most people want uc_free() rather than uc_mem_free(), i can change my mind.

**Comment by lunixbochs** [comment]
It's not clear because (1) every other API in Unicorn prefixed with mem is talking about guest memory and this is a host function, (2) "mem_free" is redundant to anyone familiar with posix, and (3) it frees context objects which aren't under the uc_mem prefix

**Comment by cseagle** [comment]
++

**Comment by adrianherrera** [comment]
I also agree with @lunixbochs and @cseagle. uc_mem_free is not related to the other uc_mem_* functions, which is confusing.

**Comment by cseagle** [comment]
I poked at this a little today.

stdbool.h is not available in VS 11.0 and earlier, this can be handled w/ ifdef blocks because stdbool.h only contains 4 defines.

inttypes.h is similarly not available. we probably need to include a local copy of an open source inttypes.h in this case perhaps from here: https://code.google.com/archive/p/msinttypes/
Alternatively we can figure out exactly what is used from inttypes and if it is only a few things, just typedef them.

config-host.h is generated from qemu's configure script and largely reflects platform specific build parameters. Including this file would probably need to be disabled in Visual Studio and the associated build parameters made part of the visual studio project specific defines

Lastly, there are a number of source files generated by the scripts in qemu/scripts and some part of the configure/make process that is responsible for generating all of the code in the xxx-softmmu directories. Visual Studio would need to be configured to make all of that happen as well

**Comment by aquynh** [comment]
no worry, those stdint/stdbool/inttypes.h are easy to handle. i did this for Capstone, and everything is in this file https://github.com/aquynh/capstone/blob/next/include/capstone/platform.h

**Comment by aquynh** [comment]
to start, we can pre-generate all those auto-gen files, and make VS compile them.

**Comment by aquynh** [comment]
i renamed uc_mem_free() to uc_free() just now. please double check your bindings still work.

**Comment by xorstream** [comment]
I am hoping to have some time to look into porting to msvc over the next
week.
I didn't want to say anything till i knew i could spare some time.

Has anyone else worked on this in files that aren't part of the man repo?
Or almost finished doing it?
Just thought I'd check before I start looking into it and find someone has
already done it :)

On Wed, Jan 11, 2017 at 12:00 AM, Nguyen Anh Quynh <notifications@github.com

**Comment by aquynh** [comment]
@xorstream, so everything is still good with your binding?

**Comment by xorstream** [comment]
Oh I assumed if we had msvc native then the old msvc binding would be
superseded.

Is there any reason to keep the msvc binding if we have msvc native support?


On Fri, Jan 13, 2017 at 10:24 PM, Nguyen Anh Quynh <notifications@github.com

**Comment by aquynh** [comment]
what do you mean? we dont have MSVC native support yet.

**Comment by xorstream** [comment]
I have a few days to work on this.

I can spend it adding msvc bindings to the ming build dlls, or I could
spend it getting a native msvc build working.

I figure the way forward is a native msvc build so I should spend the time
doing that instead.

If I get a native msvc build working then there is no longer a need for
"msvc bindings" right?

On Fri, Jan 13, 2017 at 10:27 PM, Nguyen Anh Quynh <notifications@github.com

**Comment by aquynh** [comment]
yes, i think very few people still need that if we have MSVC native build. you would be a hero ;-)

**Comment by xorstream** [comment]
oh no, now you've gone and made it sound like it might be harder to do than
i expect! hehe

well i'll give it a go, and if i don't succeed i'll update the binding
instead :)

On Fri, Jan 13, 2017 at 10:36 PM, Nguyen Anh Quynh <notifications@github.com

**Comment by xorstream** [comment]
Is it ok to ask questions about porting to msvc native in this email thread?
Or should we start a new one?

If a new thread is preferred can you please start one up and include anyone
who might be able and interested in helping or answering questions? Also
move the question below into the new thread if new thread is required.

So far I have added a platform.h file, based on the one from capstone with
some additions to handle the OS specific headers. I have also made *lots*
of little changes here and there for things like structure initialisation
and __attribute__ tags.

One thing I'd like to ask about though is the calls to error_report() in
"qemu/util/qemu-error.c".
Can I just as a MSVC version of these calls that does calls to fprintf(
stderr, "") ?
Or are they doing something more?
error_report() only seems to be called from qemu/hw/sparc/sun4m.c, it has
been commented out everywhere else.

**Comment by aquynh** [comment]
yes, please open a new issue on MSVC porting.

regarding the error_report() function, yes you can replace that with a simpler function. will see how to patch it back later.

**Comment by xorstream** [comment]
Ok I have done so at https://github.com/unicorn-engine/unicorn/issues/719
In case anyone wants to be involved.

On Mon, Jan 16, 2017 at 12:40 PM, Nguyen Anh Quynh <notifications@github.com

**Comment by aquynh** [comment]
the RC3 release is pretty stable, so we plan to get v1.0 out in a week or so. still hope to have all the bindings updated by then ;-)
