### ISSUE TITLE
Go bindings not working

### ISSUE THREAD

**Issue by tanis2000** [unicorn-engine/unicorn#663]
```
$ go get -u github.com/unicorn-engine/unicorn/bindings/go
# github.com/unicorn-engine/unicorn/bindings/go/unicorn
could not determine kind of name for C.uc_mem_map_ptr
could not determine kind of name for C.uc_mem_region
could not determine kind of name for C.uc_mem_regions
could not determine kind of name for C.uc_query
could not determine kind of name for C.uc_query_type
```

I'm using Go 1.7.3
Same issue with 1.6.2 so I guess it's not a problem with Go, rather with unicorn. 

I'm using the 0.9 release through homebrew on OSX.

**Comment by aquynh** [comment]
I think you need the latest Github code, not v0.9, which is very much
behind the latest binding of Go. So compile and install the core from
Github to see it fixes this issue.

**Comment by tanis2000** [comment]
I tried compiling the latest master but I'm having some issues as well.
I used `brew install unicorn --HEAD` as it does it all in an automatic way.
The formula it uses is here https://github.com/Homebrew/homebrew-core/blob/master/Formula/unicorn.rb

Nothing special.. pretty much like manual compilation.

But it fails with the following error:

```
==> make install
Last 15 lines from /Users/tanis/Library/Logs/Homebrew/unicorn/01.make:
ar: creating archive ./libunicorn.a
Undefined symbols for architecture x86_64:
  "_ARM64_REGS_STORAGE_SIZE", referenced from:
      _uc_context_alloc in uc.o
  "_M68K_REGS_STORAGE_SIZE", referenced from:
      _uc_context_alloc in uc.o
  "_SPARC64_REGS_STORAGE_SIZE", referenced from:
      _uc_context_alloc in uc.o
  "_SPARC_REGS_STORAGE_SIZE", referenced from:
      _uc_context_alloc in uc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libunicorn.1.dylib] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [compile_lib] Error 2
```

The archs being set in `UNICORN_ARCHS` are `x86 x86_64 arm mips`

**Comment by aquynh** [comment]
but brew also uses v0.9, which is very much behind. we plan to release v1.0 very soon.

it is very simple to compile from source with latest Github code:

- install dependency with:

        $ brew install pkg-config glib

- then from the Unicorn Github code, do:

        $ ./make.sh
        $ sudo ./make.sh install

- done.

**Comment by tanis2000** [comment]
nope, brew is using the latest master:

```
$ brew install unicorn --HEAD
==> Using the sandbox
==> Cloning https://github.com/unicorn-engine/unicorn.git
Cloning into '/Users/tanis/Library/Caches/Homebrew/unicorn--git'...
remote: Counting objects: 886, done.
remote: Compressing objects: 100% (801/801), done.
remote: Total 886 (delta 117), reused 583 (delta 66), pack-reused 0
Receiving objects: 100% (886/886), 3.32 MiB | 478.00 KiB/s, done.
Resolving deltas: 100% (117/117), done.
Checking connectivity... done.
==> Checking out branch master
==> make install
Last 15 lines from /Users/tanis/Library/Logs/Homebrew/unicorn/01.make:
ar: creating archive ./libunicorn.a
Undefined symbols for architecture x86_64:
  "_ARM64_REGS_STORAGE_SIZE", referenced from:
      _uc_context_alloc in uc.o
  "_M68K_REGS_STORAGE_SIZE", referenced from:
      _uc_context_alloc in uc.o
  "_SPARC64_REGS_STORAGE_SIZE", referenced from:
      _uc_context_alloc in uc.o
  "_SPARC_REGS_STORAGE_SIZE", referenced from:
      _uc_context_alloc in uc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libunicorn.1.dylib] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [compile_lib] Error 2
```

**Comment by aquynh** [comment]
Then it is broken. Can you try what i post above?

**Comment by tanis2000** [comment]
yes, that did work. I think the issue is that the brew formula is explicitly specifying x86_64 as an arch to compile against, while standard make.sh isn't.
I'll try modify the formula and check that.

**Comment by aquynh** [comment]
let me ping the author of the Brew formula

**Comment by shaunwheelhouse** [comment]
I haven't updated this since creating it and don't have a testing environment on hand, so I can't be of much help here. Sorry!

**Comment by tanis2000** [comment]
I tried looking at the brew formula but it doesn't really look like there's anything wrong. Even compiling it by hand from within brew's shell is failing so I guess it's something tied to the brew environment, but I don't know enough about it to be able to say what's wrong.

**Comment by OctHex2016** [comment]
I also get this error 
go get -u github.com/unicorn-engine/unicorn/bindings/go
# github.com/unicorn-engine/unicorn/bindings/go/unicorn
could not determine kind of name for C.uc_context
could not determine kind of name for C.uc_context_alloc
could not determine kind of name for C.uc_context_free
could not determine kind of name for C.uc_context_restore
could not determine kind of name for C.uc_context_save

**Comment by aquynh** [comment]
@OctHex2016, did you install the latest Unicorn core yet? otherwise, @lunixbochs may help with Go issue.

**Comment by lunixbochs** [comment]
that error means the unicorn header found by Go was probably older than the context commit

**Comment by aquynh** [comment]
@tanis2000 @OctHex2016: i just pushed a commit to fix this issue with Brew. can you try again now with "brew install unicorn --HEAD" ?

**Comment by Paul776** [comment]
Unix latest git code the do 'make' in the go folder

/tmp/go-build756131574/_/home/ec2-user/unicorn/bindings/go/unicorn/_obj/context.cgo2.o: In function `_cgo_8595014cb151_Cfunc_uc_context_alloc':
./context.go:52: undefined reference to `uc_context_alloc'
/tmp/go-build756131574/_/home/ec2-user/unicorn/bindings/go/unicorn/_obj/context.cgo2.o: In function `_cgo_8595014cb151_Cfunc_uc_context_free':
./context.go:70: undefined reference to `uc_context_free'
/tmp/go-build756131574/_/home/ec2-user/unicorn/bindings/go/unicorn/_obj/context.cgo2.o: In function `_cgo_8595014cb151_Cfunc_uc_context_restore':
./context.go:89: undefined reference to `uc_context_restore'
/tmp/go-build756131574/_/home/ec2-user/unicorn/bindings/go/unicorn/_obj/context.cgo2.o: In function `_cgo_8595014cb151_Cfunc_uc_context_save':
./context.go:108: undefined reference to `uc_context_save'
/tmp/go-build756131574/_/home/ec2-user/unicorn/bindings/go/unicorn/_obj/unicorn.cgo2.o: In function `_cgo_8595014cb151_Cfunc_uc_mem_map_ptr':
./unicorn.go:142: undefined reference to `uc_mem_map_ptr'
/tmp/go-build756131574/_/home/ec2-user/unicorn/bindings/go/unicorn/_obj/unicorn.cgo2.o: In function `_cgo_8595014cb151_Cfunc_uc_mem_regions':
./unicorn.go:205: undefined reference to `uc_mem_regions'
/tmp/go-build756131574/_/home/ec2-user/unicorn/bindings/go/unicorn/_obj/unicorn.cgo2.o: In function `_cgo_8595014cb151_Cfunc_uc_query':
./unicorn.go:287: undefined reference to `uc_query'
/tmp/go-build756131574/_/home/ec2-user/unicorn/bindings/go/unicorn/_obj/uc.o: In function `uc_reg_read_batch_helper':
./uc.c:11: undefined reference to `uc_reg_read_batch'
/tmp/go-build756131574/_/home/ec2-user/unicorn/bindings/go/unicorn/_obj/uc.o: In function `uc_reg_write_batch_helper':
./uc.c:22: undefined reference to `uc_reg_write_batch'
collect2: error: ld returned 1 exit status
make: *** [all] Error 2

**Comment by tanis2000** [comment]
@aquynh you fix to brew did the trick. HEAD is working fine here now. Thanks!

**Comment by aquynh** [comment]
close, thanks
