### ISSUE TITLE
an arm_reg_write bug

### ISSUE THREAD

**Issue by fr0zenrain** [unicorn-engine/unicorn#677]
if we use uc_open(UC_ARCH_ARM, UC_MODE_THUMB, &uc) set init mode thumb
when emulator start,arm_reg_write will overwrite the thumb flag if the start address is even number.
in an arm device , pc odd impossible. unicorn will fetch the code as arm mode,it's not correct,and now i comment that two line,it's ok.

**Comment by Normmatt** [comment]
lowest bit of pc specifies thumb mode if its 1 its thumb otherwise it's arm.
It works this way on a real arm cpu as well.

**Comment by fr0zenrain** [comment]
i think pc's lowest bit will not be 1 in fact, arm just set cpsr T bit,you can find an ELF symbol address lowest indicate code mode, PC in here also even, you can see that with a debugger. and i said the bug is env->thumb will overwrite,this will cause fetch code issue.thx

**Comment by Normmatt** [comment]
yes if you read back pc it won't have that bit set... but setting pc with lowest bit changes cpsr T bit as you said.
