### ISSUE TITLE
errors in loading libunicorn.so

### ISSUE THREAD

**Issue by seem111** [unicorn-engine/unicorn#678]
ctypes.cdll.LoadLibrary("/usr/lib/python2.6/site-packages/unicorn-1.0.0-py2.6.egg/unicorn/lib/libunicorn.so")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.6/ctypes/__init__.py", line 431, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib64/python2.6/ctypes/__init__.py", line 353, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/python2.6/site-packages/unicorn-1.0.0-py2.6.egg/unicorn/lib/libunicorn.so: undefined symbol: clock_gettime

when I compile the unicorn and run the unicorn. I got the above errors. why?

**Comment by aquynh** [comment]
on Linux, can you try this installation instead?

    $ sudo pip install "https://github.com/unicorn-engine/unicorn/archive/master.zip#egg=unicorn&subdirectory=bindings/python"

**Comment by seem111** [comment]
I have uninstalled the unicorn and install it with your code and got the error:

>>> import unicorn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/unicorn/__init__.py", line 4, in <module>
    from .unicorn import Uc, uc_version, uc_arch_supported, version_bind, debug, UcError, __version__
  File "/usr/lib/python2.6/site-packages/unicorn/unicorn.py", line 73, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.

**Comment by aquynh** [comment]
can you remove all that, and try again with latest Github code like below, to see how it works?

```
$ ./make.sh
$ sudo ./make.sh install
$ cd bindings/python
$ sudo make install
```

**Comment by seem111** [comment]
I got the same error.  I try to add -lrt in the makefile. But it doesn't work. 

$ ./make.sh
if [ "x86 m68k arm aarch64 mips sparc" != "`cat config.log`" ]; then make clean; fi
cd qemu && make -j 4
make[1]: Entering directory `/home/admin/unicorn/unicorn-master/qemu'
make[1]: Leaving directory `/home/admin/unicorn/unicorn-master/qemu'
make unicorn
make[1]: Entering directory `/home/admin/unicorn/unicorn-master'
make[1]: Nothing to be done for `unicorn'.
make[1]: Leaving directory `/home/admin/unicorn/unicorn-master'
make[1]: Entering directory `/home/admin/unicorn/unicorn-master/samples'
  LINK    sample_arm
../libunicorn.so: undefined reference to `clock_gettime'
collect2: ld ▒▒▒▒ 1
make[1]: *** [sample_arm] ▒▒▒▒ 1
make[1]: Leaving directory `/home/admin/unicorn/unicorn-master/samples'
make: *** [all] ▒▒▒▒ 2

**Comment by aquynh** [comment]
no, dont make that change in Makefile.

looks like you cannot even compile yet. what is your Linux version? and did you install dependency, as instructed in https://github.com/unicorn-engine/unicorn/blob/master/docs/COMPILE-NIX.md yet?

```
- For Linux, "glib2-dev" is needed.
  Ubuntu/Debian users can install this with:

        $ sudo apt-get install libglib2.0-dev
```

**Comment by seem111** [comment]
My linux is (Red Hat 4.4.4-13). So I can't find the libglib2-dev. Which dependency should I have?

**Comment by aquynh** [comment]
This is why you cannot compile. You need libglib2, but i dont know if they
have that on this old Redhat version
