### ISSUE TITLE
W^X in OpenBSD 6.0 preventing execution of Unicorn samples

### ISSUE THREAD

**Issue by oblivia-simplex** [unicorn-engine/unicorn#679]
I just moved over to OpenBSD from Arch, and have been having some trouble getting a project I'm working on with Unicorn to execute. When I tried to get the samples to run, I ran into the same difficulty. Looking at the kdump of sample_arm (https://ghostbin.com/paste/x526y), it looks like this is a W^X issue, which I understand is enforced on OpenBSD 6.0. 

Is there a workaround for this, or will the code need to be refactored so that it doesn't map any memory as simultaneously writeable and executable? 

post on hacker news about W^X woes on openbsd: https://news.ycombinator.com/item?id=11789819

**Comment by aquynh** [comment]
Does it work on older OpenBSD? And does Qemu still work on v6.0?

Btw, make sure to use latest Github code all the time

**Comment by oblivia-simplex** [comment]
Qemu seems to work fine. I just booted up a qemu-system-mips instance of a linux vm. Haven't tried Unicorn on older OpenBSD installs. 

and yes I'm using a fresh pull from github.

**Comment by oblivia-simplex** [comment]
Ah here's a workaround, apparently: http://undeadly.org/cgi?action=article&sid=20160527203200

> W^X violating programs can be permitted on a ffs/nfs filesystem-basis,
using the "wxallowed" mount option.  One day far in the future
upstream software developers will understand that W^X violations are a
tremendously risky practice and that style of programming will be
banished outright.  Until then, we recommend most users need to use the
wxallowed option on their /usr/local filesystem.

**Comment by aquynh** [comment]
is this on sample_arm.c? perhaps it is because we map memory as PROT_ALL at https://github.com/unicorn-engine/unicorn/blob/master/samples/sample_arm.c#L69 ?

**Comment by oblivia-simplex** [comment]
I think that's probably the issue. In any case, the easiest workaround for me is to just edit /etc/fstab to include the option "wxallowed" for the /home partition, since that's where my dev projects usually live. Turns out that openbsd mounts /usr/local/bin as wxallowed by default.

**Comment by oblivia-simplex** [comment]
I'm happy to mark this issue closed, now. Thanks.

**Comment by aquynh** [comment]
if you change that `UC_PROT_ALL` to `UC_PROT_READ | UC_PROT_EXEC`, what happens?

**Comment by aquynh** [comment]
anyway, would you mind documenting this issue + your solution, and send a pull req to put it under docs/ directory, so in the future other OpenBSD users can learn from it? something like docs/OPENBSD_NOTES.TXT will be fine, thanks.

**Comment by oblivia-simplex** [comment]
Okay, so sample_arm still crashes on a non-wxallowed filesystem, even if I replace ```UC_PROT_ALL``` with ```UC_PROT_READ | UC_PROT_EXEC```, which makes me think that the issue is deeper in the library. 

I'll write up some notes and issue a pull request for them in a little bit.  In the meantime, here's a quick hint at what your OpenBSD fstab entry should look like for the partition you plan to use for any unicorn-related development/testing/tool use:
```
73ae23beef091234.g /home ffs rw,nodev,wxallowed,nosuid 1 2
```
and not
```
73ae23beef091234.g /home ffs rw,nodev,nosuid 1 2
```

(The nodev and nosuid options are other, standard OpenBSD security features, and are neither a problem nor necessary, as far as I can tell, for unicorn.)
