### ISSUE TITLE
RDGSBASE Invalid Instruction

### ISSUE THREAD

**Issue by JohnSully** [unicorn-engine/unicorn#683]
Sample code:
	uc_reg_write(uc, UC_X86_REG_RDX, &vT);
	uc_reg_write(uc, UC_X86_REG_RAX, &pctxt->gsBase);
	vT = 0xC0000102;
	uc_reg_write(uc, UC_X86_REG_RCX, &vT);
	const char *rgbWRMSR = /* WRMSR*/ "\x0f\x30"  /* SWAPGS */ "\x0f\x01\xf8" /* RDGSBASE rbx */ "\xF3\x48\x0F\xAE\xCB"  /* hlt */ "\xf4";
	uint64_t t_base = 0xffff0000;
	uc_mem_map(uc, t_base, 4096, UC_PROT_ALL);
	uc_mem_write(uc, t_base, rgbWRMSR, 11);
	uc_emu_start(uc, t_base, t_base + 10, 0, 0);

Results in UC_ERR_INSN_INVALID, with RIP == 0x0ffff0005 (the RDGSBASE op-code)

**Comment by aquynh** [comment]
would you mind sending a pull req with the full code as a testcase, and put it under either https://github.com/unicorn-engine/unicorn/tree/master/tests/regress (Python) or https://github.com/unicorn-engine/unicorn/tree/master/tests/unit (C) ?
