### ISSUE TITLE
how to make such call chain work? guestcode->>host-code -->guest-code and so on

### ISSUE THREAD

**Issue by wellcomez** [unicorn-engine/unicorn#685]
how to make such call chain work?
 guestcode->>host-code -->guest-code and so on. 
I guest i can use multi uc instances to make such process work. But i think it too ugly. Could anybody give me any suggestion to  hack unicorn ?  Such kind of call stack is so popular at real case. How to simulate it smoothly?

**Comment by fr0zenrain** [comment]
multi uc instances shared a single memory?  i think maybe you need uc_emu_pause. you can pause emulator, and run your host code , also you can implement  that use guest code ,and emulate it , ha ha ha

**Comment by wellcomez** [comment]
@fr0zenrain In my case host-side code  is called inside of  code _trace_hook， at time uc is running nativecode and hasn't any chance to check it own state and don't it's paused by me.

**Comment by wellcomez** [comment]
@fr0zenrain yes ,multi uc instances shared a single memory.

**Comment by paulsapps** [comment]
@wellcomez did  you ever find a clean way of doing this?
