### ISSUE TITLE
remove glib dependency?

### ISSUE THREAD

**Issue by m4b** [unicorn-engine/unicorn#686]
Iirc, the only dynamic dependency besides regular system libraries is glib.

After investigating the `libunicorn.so`'s imports, it appears to only use a hash table implementation from glib.

I suspect this is inherited from the qemu code.

So, assuming the above is correct, how feasible would it be to replace the glib hashtable dependency with an internal implementation?

Some motivations for this:

1. The library is would essentially be capable of static compilation, which means it's extremely amenable to compilation to JS/web assembly (I've already done this for a [rust capstone wrapper](https://github.com/m4b/capstone-rs), which is similarly dependency free)
2. Easier compilation, easier cross compilation.
3. That's really all I've got ;)

I actually came very close to having a bare bones qemu instance cross compiled into asm.js but the glib dependency was the stopping point.

Anyway, just something to marinate on, or perhaps it's impractical, etc, but might be worth pursuing

**Comment by aquynh** [comment]
Yes, it is good to get rid of glib. Feel free to send us a pull req to
implement your idea.

**Comment by cseagle** [comment]
This would be fantastic, but it would be useful to know what the transition path to a newer version of qemu is or we will need to do this all over again.

**Comment by aquynh** [comment]
once we remove glib dependency, we will maintain that even when we sync with newer version of Qemu.

after release 1.0, i will try to find time to update the code with newer version of Qemu.

**Comment by m4b** [comment]
It might be best to remove the dependency after the 1.0 release with the newer version of Qemu, since this may or may not introduce additional dynamic dependencies, and then you'll have a better starting point?

I would love to send a PR but:

1. I have too many projects in the boiler room right now and i need to finally finish some of them
2. I am _definitely_ not a strong enough C programmer to mess around with a hash table implementation :P and I'm also lazy so I'd probably end up just giving up and copying the glib source code and tainting your repo :laughing:

**Comment by aquynh** [comment]
yes, we can do that after v1.0, but since there is no major change until the release, you can start this work anytime.

**Comment by cseagle** [comment]
It looks like GList is used as well, and perhaps more. I am trying to determine the level of effort required here.

**Comment by cseagle** [comment]
I just submitted pr #690 that does this. It needs much more testing than I have done with it if anyone wants to test it with their current unicorn use cases.

**Comment by aquynh** [comment]
@m4b: we now have a new branch "noglib" which removes glib dependency. please help to test it.

**Comment by m4b** [comment]
whoohoo! checked out `noglib`, `make` and I've got a static lib and:

```
rdr -l libunicorn.so
ELF X86_64 DYN @ 0x6a980
Soname: libunicorn.so.1
Libraries (2)
	libm.so.6
	libc.so.6
```

So looks good on that front.  I then hacked the current rust bindings to build unicorn from source with the `noglib` branch, and it builds and links properly, and passes all the tests on the [rust repo](https://github.com/ekse/unicorn-rs), so seems the replacement functions are working?

The C tests all pass on my side as well.

Awesome job!

**Comment by aquynh** [comment]
@m4b, can you help to test the branch https://github.com/unicorn-engine/unicorn/tree/noglib2? this should do the same thing as "noglib" branch.

**Comment by aquynh** [comment]
i merged the branch "noglib2", and the "master" branch now longer uses glib. please report if you have any issues.

**Comment by m4b** [comment]
Whoohoo!
