### ISSUE TITLE
towards release 1.0

### ISSUE THREAD

**Issue by aquynh** [unicorn-engine/unicorn#687]
i think we can release version 1.0-rc1 next week. the plan is to fix the known segfaults before v1.0.

currently we still have #646 & #645 issues, which are release blockers. anybody can look at that?

**Comment by danghvu** [comment]
I revisit all issues, there are possibly more. Please go over and close if you know it is fixed:

https://github.com/unicorn-engine/unicorn/issues?page=1&q=is%3Aopen+is%3Aissue+label%3Abug

**Comment by aquynh** [comment]
Yes there are still open issues, but i just listed those segfaults as critical that must be fixed for 1.0. The rest, without crash, can be fixed in future versions.

**Comment by JayFoxRox** [comment]
This should be closed? 1.0 has been out for a while
