### ISSUE TITLE
running make twice fails the second time

### ISSUE THREAD

**Issue by lunixbochs** [unicorn-engine/unicorn#696]
I'm on OS X

```
$ ./make.sh
cc -g   -c -o uc.o uc.c
uc.c:16:10: fatal error: 'uc_priv.h' file not found
#include "uc_priv.h"
         ^
1 error generated.
make: *** [uc.o] Error 1
```

If I `make clean` it works fine. This is 100% reliable.

**Comment by aquynh** [comment]
confirmed. this can be reproduced with:

```
$ ./make.sh
$ touch uc.c
$ ./make.sh
```

**Comment by aquynh** [comment]
this should be fixed now thanks to commit https://github.com/unicorn-engine/unicorn/commit/06541894ea6dc2f187ffb7c63e40bb687e6e56e7
