### ISSUE TITLE
unicorn emulate game on win7 x64

### ISSUE THREAD

**Issue by killpy** [unicorn-engine/unicorn#701]
I want to emulate run my online games on win7 x64， can unicorn do this？I thought for a few days but no ideas What information can refer to?Or give me some ideas thanks Maybe I can buy your sourcecode,Please contact me with email:killpy178@gmail.com

**Comment by aquynh** [comment]
interesting, which game are you running?

**Comment by killpy** [comment]
http://lol.qq.com/

**Comment by aquynh** [comment]
why cant you run LOL on Win7 64bit?

**Comment by killpy** [comment]
I want to kill the game detection

**Comment by danghvu** [comment]
I don't think unicorn can help you unless you invest a lot of time writing codes (even so it's a maybe).
