### ISSUE TITLE
VFP/Neon troubles

### ISSUE THREAD

**Issue by hedger** [unicorn-engine/unicorn#704]
I'm trying to emulate some code with NEON/VFP instructions, but can't make it work. 
I am using freshly-compiled 32-bit unicorn with Python 2.7 bindings under Win10 64bit.
I tried running CPU code that should do the trick as advised in #571 and #446, but it fails with `UC_ERR_INSN_INVALID`. Neither can I run packaged regression test.
Am I missing something or is VFP support broken ATM?
```
H:\code\unicorn\tests\regress>git log -n1
commit a963326dbad567dfc54a35287012c47474c558b6
Merge: 2e8fa1d 3d76007
Author: Nguyen Anh Quynh <aquynh@gmail.com>
Date:   Mon Jan 2 11:58:34 2017 +0800

    Merge pull request #703 from angr/fix/staticlib_export

    Make the call out to visual studio extremely resilient

H:\code\unicorn\tests\regress>arm_fp_vfp_disabled.py
E
======================================================================
ERROR: runTest (__main__.FpVfpDisabled)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "H:\code\unicorn\tests\regress\arm_fp_vfp_disabled.py", line 41, in runTest
    uc.emu_start(address, address + len(code_bytes))
  File "C:\Python27\lib\site-packages\unicorn\unicorn.py", line 250, in emu_start
    raise UcError(status)
UcError: Invalid instruction (UC_ERR_INSN_INVALID)

----------------------------------------------------------------------
Ran 1 test in 0.006s

FAILED (errors=1)
```

**Comment by hedger** [comment]
Can anyone check if `tests/regress/arm_fp_vfp_disabled.py` passes for you and post the results here?

**Comment by danghvu** [comment]
Confirm this is failing on me too, not sure when it was broken (or ever green).

**Comment by aquynh** [comment]
@mothran did something along this line before, so perhaps he will have some comments.

**Comment by mothran** [comment]
@hedger try my branch located at https://github.com/unicorn-engine/unicorn/pull/684, I added example code in to enable the VFP using additional COPROC registers.

See if your ARM code will work when the example for initialization in: https://github.com/mothran/unicorn/blob/master/tests/regress/arm_enable_vfp.c

**Comment by mothran** [comment]
Interestingly enough I am also seeing that test fail with a INSN_INVALID, @aquynh can you confirm?

Is it possible that in this test the instruction base address is 0x1000 but the mode is THUMB?

**Comment by hedger** [comment]
@mothran I cherry-picked your commits on top of `master`, rebuilt Python constants, and using following initialization code succesfully ran code with VFP operations:
```
        regval = self.vm.reg_read(UC_ARM_REG_C1_C0_2)
        regval |= (0xF << 20)
        self.vm.reg_write(UC_ARM_REG_C1_C0_2, regval)
        self.vm.reg_write(UC_ARM_REG_FPEXC, 0x40000000)
```
@aquynh please consider merging #684, currently it is the only way to run VFP code.

**Comment by aquynh** [comment]
well, the sample is wrong since when we decided that emulation in Thumb mode should start at odd address.

i push this commit https://github.com/unicorn-engine/unicorn/commit/353dc99af6d9469155e74f66129cdfe2d248e9fa, and `arm_fp_vfp_disabled.py` passes the test now.

**Comment by hedger** [comment]
Thanks, it works. For anyone who comes across this issue - here's valid initialization code for current version, based on `arm_fp_vfp_disabled.py`:
```
            try:
                code = '11EE501F41F4700101EE501F4FF0000107EE951F4FF08040E8EE100A2ded028b'
                
                address = 0x1000
                mem_size = 0x1000
                code_bytes = code.decode('hex')

                uc.mem_map(address, mem_size)
                uc.mem_write(address, code_bytes)
                uc.reg_write(UC_ARM_REG_SP, address + mem_size)
                uc.emu_start(address | 1, address + len(code_bytes))
            finally:
                self.vm.mem_unmap(address, mem_size)
```

**Comment by fr0zenrain** [comment]
@aquynh  if Thumb mode should start at odd address.it can be emulate a real world file,such as android shared library #677
