### ISSUE TITLE
batch mode reg read/write does not support emulating 64 bit archs on 32-bit platforms

### ISSUE THREAD

**Issue by cseagle** [unicorn-engine/unicorn#708]
The "vals" argument to these functions is either "void *const *vals" or "void **vals", since sizeof(void*) is only 4 bytes on 32-bit platforms, how are we to specify full 64-bit values for 64-bit registers when emulating 64-bit architectures on 32-bit platforms? It seems like vals should be "uint64_t *vals"

**Comment by lunixbochs** [comment]
Each val pointer will be cast to the target type, picked by the enum in the other list. This allows you to batch regs that won't fit in 64-bit, like FP or GDT regs. It has the exact same semantics as a single reg_read/write, but with fewer function calls to churn through.

This has a tradeoff (you need to build a list of pointers to values). I couldn't think of a better way to do it given the constraints. There's time to change it by 1.0 if anyone has a better idea.
