### ISSUE TITLE
Imports Table

### ISSUE THREAD

**Issue by naweiss** [unicorn-engine/unicorn#717]
I'm using the python bindings to try and emulate unpacker.
I the process the code uses LoadLibraryA and some other imports.
I maped all the sections of the PE into Unicorn, but when trying to run the code I get the following message: 

>[ HOOK_MEM_FETCH - Address: 0x82a0 ]
[ mem_fetch_unmapped: faulting address at 0x82a0 ]
[ HOOK_MEM_FETCH - Address: 0x82a0 ]
[ mem_fetch_unmapped: faulting address at 0x82a0 ]
[ HOOK_MEM_FETCH - Address: 0x82a0 ]
[ mem_fetch_unmapped: faulting address at 0x82a0 ]
[ HOOK_MEM_FETCH - Address: 0x82a1 ]
[ mem_fetch_unmapped: faulting address at 0x82a1 ]

The error is in this line (call to LoadLibraryA):
`call    dword ptr [esi+7250h]`

Any suggestions?

**Comment by cseagle** [comment]
My guess is that's upx. Independent of that, even though you mapped the pe
into unicorn you may not have resolved the addesses of imported functions
in the iat so you are not reading the address of and calling out to
LoadLibrary.

You will need to decide how you want to deal with the call to LoadLibrary.
You probably don't want to load all of kernel32 and emulate into it. One
approach would be to write magic values into the iat and when you see jumps
to them in your unmapped hook, do some python magic to emulate the library
function. For LoadLibrary you need to return a handle and remember the
library associated with that handle so that you can properly handle the
calls to GetProcAddress that will inevitably follow.

Chris

**Comment by naweiss** [comment]
I didn't understand your answer.
I can run LoadLibraryA in python,but how to attach the result back to Unicorn?
Can you give me some code (even Pseudo-Code) so I will understand you better?

**Comment by cseagle** [comment]
Sure, you can call LoadLibraryA from Python. I wouldn't load any library that the code you are emulating happens to ask for as you would just be running code on behalf of the emulated code, and in any case the library that it is requesting may not even be available on your system or you might be emulating code on a non-Windows system. 

You said you mapped all the section of the PE. During that time you need to process the .idata section and patch in values that you can recognize in your hook functions. Bad pseudo code follows:

fake_addr = 0xdeadbeef
imports = {}
for lib in imported_libraries:
   for imported_func in lib:
      uc.mem_write(imported_func.iat_addr, struct.pack("<I", fake_addr))
      imports[fake_addr] = imported_func.name
      fake_addr += 1

then your unmapped hook might look something like this:

# callback for tracing invalid memory access (READ or WRITE)
def hook_mem_invalid(uc, access, address, size, value, user_data):
    if access == UC_MEM_FETCH_UNMAPPED and address in imports:
        func = imports[address]
        print "Emulated program attempting to call " + func

        #setup return to the caller
        ret_addr = struct.unpack("<I", uc.mem_read(uc.reg_read(UC_X86_REG_ESP), 4))
        uc.reg_write(UC_X86_REG_EIP, ret_addr)

        #call out to your python emulation of "func"
        #also make any necessary stack adjustments before return to caller

        return True
    else:
        # address doesn't appear to point to imported function
        # return False to indicate we want to stop emulation
        return False

**Comment by fr0zenrain** [comment]
i have emulate the ELF upx x86 before, it  was running ok.the only one you need caution was the instruction with fs &gs. i didn't have test PE.

**Comment by naweiss** [comment]
@cseagle Thank you very much.
I took your idea and changed it a little so it we suite my needs.
But I still have little question: what is the minimal value of mem_map?
I tried to map something like 10 bytes but the map falied

**Comment by cseagle** [comment]
You need to map multiples of pages (4096 bytes)
