### ISSUE TITLE
Building unicorn engine 32bit with python2-32 for IDA pro under Arch linux

### ISSUE THREAD

**Issue by dummys** [unicorn-engine/unicorn#732]
Hi,
I'm struggling make it work. I successfully compiled the engine and tested it with samples.
Using the make.sh with: _UNICORN_QEMU_FLAGS="--python=/usr/bin/python2-32" make.sh linux32_  is not working due that in the make.sh under linux32 there is already the unicorn_qemu_flags used.
I modified the make.sh to test:

> build_linux32() {
> PKG_CONFIG_PATH="/usr/lib/i386-linux-gnu/pkgconfig" \
> CFLAGS=-m32 \
>   LDFLAGS=-m32 \
>   LDFLAGS_STATIC=-m32 \
>   LIBRARY_PATH="/usr/lib/i386-linux-gnu" \
>   UNICORN_QEMU_FLAGS="--cpu=i386 --python=/usr/bin/python2-32" \
>   ${MAKE}
> }

And I was able to compile and install it.
My  problem is with the python bindings, I installed it with _sudo /usr/bin/python2-32 setup.py install_.
I found a unicorn folder under /usr/lib32/python2.7/site-packages but when I try to do _from unicorn import *_ I get a "package unicorn is not found".
Do you have an idea how I can debug that ?
Thanks

**Comment by aquynh** [comment]
try avoid hacking if possible. in `make.sh`, if you change the line

```
UNICORN_QEMU_FLAGS="--cpu=i386"
```

to 

```
UNICORN_QEMU_FLAGS="--cpu=i386 ${UNICORN_QEMU_FLAGS}"
```

then compile again with:

```
$ UNICORN_QEMU_FLAGS="--python=/usr/bin/python2-32" make.sh linux32
```

does it work for you?

**Comment by aquynh** [comment]
on the "package not found" issue, can you uncomment the 2 lines at https://github.com/unicorn-engine/unicorn/blob/master/bindings/python/unicorn/unicorn.py#L87-L88, then reinstall the Python binding (with `cd bindings/python; sudo make install`), then try to `import unicorn` in Python again. what is the output now?

**Comment by dummys** [comment]
I think I need to do some cleaning. Because I tried installing first unicorn with make install and not make.sh.
So first:
UNICORN_QEMU_FLAGS="--python=/usr/bin/python2-32" make.sh linux32
Then sudo make.sh install ?

**Comment by aquynh** [comment]
yes, better to use `sudo ./make.sh install`

**Comment by dummys** [comment]
Yes, seems to be not working, look the output I pasted

**Comment by dummys** [comment]
For python error: in the doc it's written:
1. Installing on Linux:
	$ sudo python setup.py install
My  problem is that I need to install it for the /usr/lib32/python2 install and not the normal python 64 bit install
So is it ok if I do sudo /usr/bin/python2-32 setup.py install ?

**Comment by aquynh** [comment]
yes `make.sh install` installs to system directory, which is based on the architecture. so installation does not work for cross-compile.

**Comment by dummys** [comment]
output of the command:

> -> $ sudo /usr/bin/python2-32 setup.py install 
> [sudo] password for dummys: 
> /usr/lib/python2.7/site-packages/setuptools/dist.py:333: UserWarning: Normalizing '1.0.0.rc2' to '1.0.0rc2'
>   normalized_version,
> running install
> running bdist_egg
> running build
> Building C extensions
> make -C samples
> make[1]: Entering directory '/home/dummys/works/project/ida_unicorn/unicorn/samples'
> make[1]: Nothing to be done for 'all'.
> make[1]: Leaving directory '/home/dummys/works/project/ida_unicorn/unicorn/samples'
> running build_py
> copying unicorn/unicorn.py -> build/lib/unicorn
> running egg_info
> writing unicorn.egg-info/PKG-INFO
> writing top-level names to unicorn.egg-info/top_level.txt
> writing dependency_links to unicorn.egg-info/dependency_links.txt
> reading manifest file 'unicorn.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> warning: no files found matching '*' under directory 'src'
> warning: no files found matching 'LICENSE.TXT'
> writing manifest file 'unicorn.egg-info/SOURCES.txt'
> copying unicorn/lib/libunicorn.so -> build/lib/unicorn/lib
> copying unicorn/lib/libunicorn.a -> build/lib/unicorn/lib
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> creating build/bdist.linux-x86_64/egg
> creating build/bdist.linux-x86_64/egg/unicorn
> copying build/lib/unicorn/arm64_const.py -> build/bdist.linux-x86_64/egg/unicorn
> copying build/lib/unicorn/unicorn_const.py -> build/bdist.linux-x86_64/egg/unicorn
> creating build/bdist.linux-x86_64/egg/unicorn/lib
> copying build/lib/unicorn/lib/libunicorn.so -> build/bdist.linux-x86_64/egg/unicorn/lib
> copying build/lib/unicorn/lib/libunicorn.a -> build/bdist.linux-x86_64/egg/unicorn/lib
> copying build/lib/unicorn/sparc_const.py -> build/bdist.linux-x86_64/egg/unicorn
> copying build/lib/unicorn/arm_const.py -> build/bdist.linux-x86_64/egg/unicorn
> copying build/lib/unicorn/unicorn.py -> build/bdist.linux-x86_64/egg/unicorn
> copying build/lib/unicorn/m68k_const.py -> build/bdist.linux-x86_64/egg/unicorn
> copying build/lib/unicorn/x86_const.py -> build/bdist.linux-x86_64/egg/unicorn
> copying build/lib/unicorn/__init__.py -> build/bdist.linux-x86_64/egg/unicorn
> creating build/bdist.linux-x86_64/egg/unicorn/include
> creating build/bdist.linux-x86_64/egg/unicorn/include/unicorn
> copying build/lib/unicorn/include/unicorn/unicorn.h -> build/bdist.linux-x86_64/egg/unicorn/include/unicorn
> copying build/lib/unicorn/include/unicorn/mips.h -> build/bdist.linux-x86_64/egg/unicorn/include/unicorn
> copying build/lib/unicorn/include/unicorn/arm.h -> build/bdist.linux-x86_64/egg/unicorn/include/unicorn
> copying build/lib/unicorn/include/unicorn/sparc.h -> build/bdist.linux-x86_64/egg/unicorn/include/unicorn
> copying build/lib/unicorn/include/unicorn/arm64.h -> build/bdist.linux-x86_64/egg/unicorn/include/unicorn
> copying build/lib/unicorn/include/unicorn/m68k.h -> build/bdist.linux-x86_64/egg/unicorn/include/unicorn
> copying build/lib/unicorn/include/unicorn/x86.h -> build/bdist.linux-x86_64/egg/unicorn/include/unicorn
> copying build/lib/unicorn/mips_const.py -> build/bdist.linux-x86_64/egg/unicorn
> byte-compiling build/bdist.linux-x86_64/egg/unicorn/arm64_const.py to arm64_const.pyc
> byte-compiling build/bdist.linux-x86_64/egg/unicorn/unicorn_const.py to unicorn_const.pyc
> byte-compiling build/bdist.linux-x86_64/egg/unicorn/sparc_const.py to sparc_const.pyc
> byte-compiling build/bdist.linux-x86_64/egg/unicorn/arm_const.py to arm_const.pyc
> byte-compiling build/bdist.linux-x86_64/egg/unicorn/unicorn.py to unicorn.pyc
> byte-compiling build/bdist.linux-x86_64/egg/unicorn/m68k_const.py to m68k_const.pyc
> byte-compiling build/bdist.linux-x86_64/egg/unicorn/x86_const.py to x86_const.pyc
> byte-compiling build/bdist.linux-x86_64/egg/unicorn/__init__.py to __init__.pyc
> byte-compiling build/bdist.linux-x86_64/egg/unicorn/mips_const.py to mips_const.pyc
> creating build/bdist.linux-x86_64/egg/EGG-INFO
> copying unicorn.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying unicorn.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying unicorn.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying unicorn.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying unicorn.egg-info/zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
> writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
> creating 'dist/unicorn-1.0.0rc2-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
> removing 'build/bdist.linux-x86_64/egg' (and everything under it)
> Processing unicorn-1.0.0rc2-py2.7.egg
> Removing /usr/lib32/python2.7/site-packages/unicorn-1.0.0rc2-py2.7.egg
> Copying unicorn-1.0.0rc2-py2.7.egg to /usr/lib32/python2.7/site-packages
> unicorn 1.0.0rc2 is already the active version in easy-install.pth
> 
> Installed /usr/lib32/python2.7/site-packages/unicorn-1.0.0rc2-py2.7.egg
> Processing dependencies for unicorn==1.0.0rc2
> Finished processing dependencies for unicorn==1.0.0rc2
>

**Comment by dummys** [comment]
Same problem, it seems it didn't find the unicorn bindings at all:

> -> $ /usr/bin/python2-32
> Python 2.7.13 (default, Jan 22 2017, 01:48:17) 
> [GCC 6.3.1 20170109] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import unicorn
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: No module named unicorn
> >>>

**Comment by aquynh** [comment]
i pushed a commit so you can use Python2 to cross-compile Linux32 at the same time: https://github.com/unicorn-engine/unicorn/commit/0c55648deec70927b00c83bd7cd69aebeb8583af

i think you dont need to do system-wide install for IDA, but just ccopy Unicorn Python module somewhere for IDA to find that. section A3 of http://www.keystone-engine.org/keypatch/ maybe useful for you.

**Comment by dummys** [comment]
Ok thanks, I tried to use this plugin: https://github.com/36hours/idaemu

**Comment by dummys** [comment]
After trying your idea I get this:

> raceback (most recent call last):
>   File "/opt/ida-6.95/python/ida_idaapi.py", line 509, in IDAPython_ExecScript
>     execfile(script, g)
>   File "/home/dummys/.idapro/plugins/idaemu.py", line 4, in <module>
>     from unicorn import *
>   File "/opt/ida-6.95/python/unicorn/__init__.py", line 2, in <module>
>     from . import arm_const, arm64_const, mips_const, sparc_const, m68k_const, x86_const
> ImportError: cannot import name arm_const
>

**Comment by dummys** [comment]
tried to add the folder unicorn to my sys.path in IDA, same problem...

**Comment by dummys** [comment]
Same kind of error when I try to use the keypatch:


> 
> Loading processor module /opt/ida-6.95/procs/pc.ilx for metapc...OK
> keypatch.py: ERROR: fail to load the dynamic library.
> Traceback (most recent call last):
>   File "/opt/ida-6.95/python/ida_idaapi.py", line 509, in IDAPython_ExecScript
>     execfile(script, g)
>   File "/home/dummys/.idapro/plugins/keypatch.py", line 23, in <module>
>     from keystone import *
>   File "/opt/ida-6.95/python/keystone/__init__.py", line 4, in <module>
>     from .keystone import Ks, ks_version, ks_arch_supported, version_bind, debug, KsError, __version__
>   File "/opt/ida-6.95/python/keystone/keystone.py", line 74, in <module>
>     raise ImportError("ERROR: fail to load the dynamic library.")
> ImportError: ERROR: fail to load the dynamic library.

**Comment by dummys** [comment]
Hashlib seems to be bugged with the python bundled in IDA...

> Python>import hashlib
> ERROR:root:code for hash md5 was not found.
> Traceback (most recent call last):
>   File "/opt/ida-6.95/python/lib/python27.zip/hashlib.py", line 147, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/opt/ida-6.95/python/lib/python27.zip/hashlib.py", line 97, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type md5
> ERROR:root:code for hash sha1 was not found.
> Traceback (most recent call last):
>   File "/opt/ida-6.95/python/lib/python27.zip/hashlib.py", line 147, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/opt/ida-6.95/python/lib/python27.zip/hashlib.py", line 97, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha1
> ERROR:root:code for hash sha224 was not found.
> Traceback (most recent call last):
>   File "/opt/ida-6.95/python/lib/python27.zip/hashlib.py", line 147, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/opt/ida-6.95/python/lib/python27.zip/hashlib.py", line 97, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha224
> ERROR:root:code for hash sha256 was not found.
> Traceback (most recent call last):
>   File "/opt/ida-6.95/python/lib/python27.zip/hashlib.py", line 147, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/opt/ida-6.95/python/lib/python27.zip/hashlib.py", line 97, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha256
> ERROR:root:code for hash sha384 was not found.
> Traceback (most recent call last):
>   File "/opt/ida-6.95/python/lib/python27.zip/hashlib.py", line 147, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/opt/ida-6.95/python/lib/python27.zip/hashlib.py", line 97, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha384
> ERROR:root:code for hash sha512 was not found.
> Traceback (most recent call last):
>   File "/opt/ida-6.95/python/lib/python27.zip/hashlib.py", line 147, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/opt/ida-6.95/python/lib/python27.zip/hashlib.py", line 97, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha512

**Comment by aquynh** [comment]
why hashlib has anything to do with Unicorn?

so can you use Unicorn with IDA yet?

**Comment by cseagle** [comment]
My recommendation to IDA users is to always install a supported 32-bit Python for your platform rather than the version that ships with IDA so that you receive python updates via your platform's official update mechanism

**Comment by aquynh** [comment]
@cseagle, yes we can always install the standard Python (from python.org), but then how to tell IDA to use that, rather than its own Python?

another thing: can we install "idaapi" & "idc" Python modules independently with standard Python, so we can "import idc, idaapi" in independent Python code, without having to run this under IDA environment?

**Comment by dummys** [comment]
@cseagle @aquynh Yes I followed this documentation: [ida with python and pip](http://www.hexblog.com/?p=726) but on my arch linux it's not working, when starting ida, I get a "import error" for the "time" module...

**Comment by dummys** [comment]
@aquynh I found a post by @cseagle on IDA forum:

> Re: IDA 6.9, Linux 64 bit, and custom 32 bit Python issues 
> Postby Chris Eagle » Wed Jan 13, 2016 7:17 am
> For what it's worth, I faced the same problem a few days ago and solved it by deleting ida/python/lib/python2.7 and replacing it with a symlink to my 32-bit python install at /lib/python2.7

I'm trying his technic now.

**Comment by dummys** [comment]
@cseagle I can't make it work with your technic:

> Import failed: No module named _ida_idaapi. Current sys.path:
> 	/usr/lib32/python27.zip
> 	/usr/lib32/python2.7
> 	/usr/lib32/python2.7/plat-linux2
> 	/usr/lib32/python2.7/lib-tk
> 	/usr/lib32/python2.7/lib-old
> 	/usr/lib32/python2.7/lib-dynload
> 	/opt/ida-6.95/python
> 	/usr/lib/python2.7/site-packages
> 	/usr/lib/python2.7/site-packages/gtk-2.0
> 	/usr/lib/python2.7/site-packages/wx-3.0-gtk2
> 	/opt/ida-6.95/python/lib/python2.7/lib-dynload/ida_32
> Traceback (most recent call last):
>   File "/opt/ida-6.95/python/init.py", line 22, in <module>
>     import ida_idaapi
>   File "/opt/ida-6.95/python/ida_idaapi.py", line 32, in <module>
>     _ida_idaapi = swig_import_helper()
>   File "/opt/ida-6.95/python/ida_idaapi.py", line 24, in swig_import_helper
>     import _ida_idaapi
> ImportError: No module named _ida_idaapi
>

**Comment by dummys** [comment]
Ok I finally figured it out with the help of hexrays support.
First I removed /opt/ida/libpython27xxx and moved /opt/ida/python/lib/*
Then I simlinked /usr/lib32/python2.7 in /opt/ida/python/lib
Then I copied back folder ida_32 and ida_64 from old /opt/ida/python/lib/python2.7/lib-dynload to /usr/lib32/python2.7/lib-dynload.
My python2.7 external is working normaly now.
I know it's a mess, but next version of IDA will be shipped with x64 libz :D

**Comment by cseagle** [comment]
You don't need to tell Ida to use it. It will find it if it's present in my experience.

Also, you cannot use idaapi and idc without ida as far as I know.

**Comment by dummys** [comment]
In Arch linux it's not working... When I removed the python from ida, it says that the ELF was wrong, because it use my system's python which is 64bit. I tried with PYTHONPATH, PYTHONHOME and LD_LIBRARY_PATH without luck, It make a big big mess on Arch Linux as well. For me it's the cleanest way to do it on Arch linux.

**Comment by cseagle** [comment]
Most sane 64-bit Linux distros offer you a way to install 32-bit packages. I don't know how to do that on Arch. On Fedora, all I need to do is "dnf install python.i686" Debian/Ubuntu are similar w/ apt-get

**Comment by dummys** [comment]
Yes I installed lib32-python2 from the AUR repository package...
