### ISSUE TITLE
Python3 bindings error

### ISSUE THREAD

**Issue by dummys** [unicorn-engine/unicorn#748]
Hello,
Using unicorn 0.9 tgz under ubuntu. After installing the python3 bindings I run Ipython3 and get the following error:

import unicorn

ImportError: No module named 'unicorn_const'

Checked in the folder and unicorn_const.py is here

**Comment by dummys** [comment]
Same with the installation that come from AUR package In Arch...
Seems python3 binding is broken.

**Comment by aquynh** [comment]
can you try with the latest version 1.0-rc3, released at https://github.com/unicorn-engine/unicorn/releases/tag/1.0-rc3?

do install with:

```
$ cd bindings/python
$ sudo make install3
```

**Comment by dummys** [comment]
yup testing now

**Comment by dummys** [comment]
still not working :( 

from unicorn import *
from unicorn.mips_const import *

No module named unicorn.mips_const

**Comment by aquynh** [comment]
i believe you can also install from PyPi now (for v1.0-rc3), with

```
$ sudo pip3 install unicorn
```

if this doesnt work, what is your Linux distro?

**Comment by dummys** [comment]
ok let me test pip.

I'm on Arch linux and on ubuntu, trying both

**Comment by dummys** [comment]
Ok pip install worked on arch linux

**Comment by dummys** [comment]
Does it means that the package from source is broken ?

**Comment by aquynh** [comment]
What is your Ubuntu version?

**Comment by aquynh** [comment]
on Ubuntu 16.04 64bit, i did this and had no problem at all

```
$ cd bindings/python
$ sudo make install3
$ python3 -c "import unicorn; print(unicorn.__version__)"
1.0.0
```

**Comment by dummys** [comment]
ok solved
