### ISSUE TITLE
ERROR: Invalid memory read (UC_ERR_READ_UNMAPPED)

### ISSUE THREAD

**Issue by mustakcsecuet** [unicorn-engine/unicorn#749]
Hi
I have an issue with unicorn emulator when I have tried decode some code. The error is:
`ERROR: Invalid memory read (UC_ERR_READ_UNMAPPED)`

This is the code I tried to decode:
`CODE = b"\x8b\x55\xfc\x8b\x45\xf8\x39\xc2\x75\x0c"`
which is actually should be decoded as: 
```
movl  -4(%rbp), %edx
movl  -8(%rbp), %eax
cmpl  %eax, %edx
jne  0x40055e
```
I have followed the code from [https://github.com/DeveloppSoft/EliDecode]

Here I provide details what I have tried:
```
# my code is in python and I am working on a x86-64 code
uc_arch = UC_ARCH_X86
uc_mode = UC_MODE_64

PAGE_SIZE = 2 * 1024 * 1024
START_RIP = 0x0000000

emu = Uc(uc_arch, uc_mode)

emu.mem_map(0, PAGE_SIZE)
emu.mem_write(START_RIP, code)

emu.hook_add(UC_HOOK_CODE, hook_code)

# I add following if there is some issue with RBP value or not, the issue also occurs when it was not there
emu.reg_write(UC_X86_REG_RBP, 0x3000000)
emu.reg_write(UC_X86_REG_RSP, 0x2000)

try:
    emu.emu_start(START_RIP, end_addr)
except UcError as e:
    print("ERROR: %s" % e)
```

Here is the callback hook_code:
```
def hook_code(uc, addr, size, user_data):
	mem = uc.mem_read(addr, size)
        # The following line disassemble the data to assembly code. that works fine
	#uc.disasm.disas_single(str(mem), addr)
	return True

```

Here is the output what its shows with disassemble code being enabled:
```
0x00000000:	movl	-4(%rbp), %edx
ERROR: Invalid memory read (UC_ERR_READ_UNMAPPED)

```
I am not sure am I missing something, or there is really a bug for x86-64?

**Comment by cseagle** [comment]
Your rbp register points well outside the memory you mapped.

You mapped 0x200000 bytes beginning at address 0 but you set rbp to 0x3000000.

I you don't set rbp, it will start at 0 and you will still write outside your range because 0-4 == 0xfffffffffffffffc

**Comment by mustakcsecuet** [comment]
Thanks.
