### ISSUE TITLE
Add callback io APIs

### ISSUE THREAD

**Issue by radare** [unicorn-engine/unicorn#754]
This issue aims to track the support for a callback model for the IO handling in Unicorn.

The idea behind this is to avoid having to setup maps because it can be everything emulated by 3rd party libraries or implementations, in addition to externalize all the memory logic from the core of the emulator.

The proposal doesn't aims to break the current design model, but just to extend it.

There's no rigid design for this callback, but i think that mem read/write operations can be wrapped into a single function with the following arguments:

* read or write operation
* address
* length
* buffer
* reference to exception error if address can't be accessed

This functionality is pretty similar to the current uc_hook one, but handling it one step before.

Also it will be good if the user can use maps and io callbacks at the same time, just skipping the callback and letting the maps to do the rest.

**Comment by markyi370** [comment]
I would like this as well! Allows virtual hardware emulation.
