### ISSUE TITLE
memorymap->size int128?

### ISSUE THREAD

**Issue by radare** [unicorn-engine/unicorn#761]
i don't get why the size in the memorymap is 128bits when the address is 64bit. is there any 128bit architecture supported? hwaddr should be 128 too. to simplify everything should be ut64
```
typedef uint64_t hwaddr;

...

struct MemoryRegion {
...
    Int128 size;
    hwaddr addr;
...
``

**Comment by aquynh** [comment]
i dont get it either, but they must have a good reason to do so: https://github.com/qemu/qemu/blob/master/include/exec/memory.h#L203

**Comment by markyi370** [comment]
It's true that it makes no sense, but look at int128.h:

https://github.com/qemu/qemu/blob/5929d7e8a0e1f43333bc3528b50397ae8dd0fd6b/include/qemu/int128.h

int128_get64() and int128_make64() are what you are looking for.
