### ISSUE TITLE
Build fails on arm64

### ISSUE THREAD

**Issue by luigino** [unicorn-engine/unicorn#764]
Using gcc6, see attached log.
[unicorn_aarch64_log.txt](https://github.com/unicorn-engine/unicorn/files/799992/unicorn_aarch64_log.txt)

**Comment by aquynh** [comment]
this should be fixed now with commit https://github.com/unicorn-engine/unicorn/commit/b12ce92468309d5eaf645406db8ea2f2d33733d1. could you confirm it works now?

**Comment by luigino** [comment]
I'm afraid not, see new log.
[unicorn_aarch64_test2_log.txt](https://github.com/unicorn-engine/unicorn/files/800061/unicorn_aarch64_test2_log.txt)

**Comment by MagaTailor** [comment]
@luigino The original issue is fixed and the failure comes from using `-Werror` in the test's Makefile (qemu even has a configure flag to disable this behaviour)

**Comment by aquynh** [comment]
@luigino, i fixed that now with https://github.com/unicorn-engine/unicorn/commit/a40e5aae092781b6ddba003e8ac7ef29152f39cf, please try again.

**Comment by luigino** [comment]
I can confirm everything works properly now, TYVM.

**Comment by aquynh** [comment]
are you building Unicorn package for some Linux distro? let us know, will be nice to have Unicorn available as a package, thanks.

**Comment by luigino** [comment]
Yes, for openSUSE.
I plan on having it in the Emulators project on OBS once a few kinks are ironed out.

**Comment by aquynh** [comment]
cool, what is that OBS?

**Comment by luigino** [comment]
[Open Build Service](https://en.opensuse.org/Portal:Build_Service)
