### ISSUE TITLE
Test failure on armv7l

### ISSUE THREAD

**Issue by lgbaldoni** [unicorn-engine/unicorn#765]
And gcc6, on this I'm not completely sure it's  not a problem with the VM I'm using to build, but still it seems sensible to report it.

[unicorn_armv7l_test_log.txt](https://github.com/unicorn-engine/unicorn/files/800154/unicorn_armv7l_test_log.txt)

**Comment by aquynh** [comment]
i need an ARM machine to verify & fix this issue. for now, you can temporarily disable the below line in Makefile to skip unit test to avoid this.

    make -C tests/unit test
