### ISSUE TITLE
Build failure on ppc, ppc64, ppc64le, s390x

### ISSUE THREAD

**Issue by lgbaldoni** [unicorn-engine/unicorn#766]
I'm posting them all together because the error appears to be the same.

[unicorn_ppc_log.txt](https://github.com/unicorn-engine/unicorn/files/801145/unicorn_ppc_log.txt)
[unicorn_ppc64le_log.txt](https://github.com/unicorn-engine/unicorn/files/801146/unicorn_ppc64le_log.txt)
[unicorn_ppc64_log.txt](https://github.com/unicorn-engine/unicorn/files/801148/unicorn_ppc64_log.txt)
[unicorn_s390x_log.txt](https://github.com/unicorn-engine/unicorn/files/801147/unicorn_s390x_log.txt)

EDIT: I forgot to say it's gcc 6.3 for all of the above. Perhaps those architectures aren't supported at all?

**Comment by aquynh** [comment]
i pushed few commits to fix this, can you pull & try again?

**Comment by luigino** [comment]
Alas we aren't there yet.
See:

[unicorn_ppc64_log.txt](https://github.com/unicorn-engine/unicorn/files/801759/unicorn_ppc64_log.txt)
[unicorn_ppc64le_log.txt](https://github.com/unicorn-engine/unicorn/files/801760/unicorn_ppc64le_log.txt)
[unicorn_ppc_log.txt](https://github.com/unicorn-engine/unicorn/files/801761/unicorn_ppc_log.txt)
[unicorn_s390x_log.txt](https://github.com/unicorn-engine/unicorn/files/801762/unicorn_s390x_log.txt)

**Comment by aquynh** [comment]
just pushed a new commit, can you pull & try again now?

**Comment by luigino** [comment]
Build succeeds but unit test fails.
The ppc problems appear to be related to #765, while the s390x ones are possibly co-caused by the VM configuration.

[ppc64_unit_log.txt](https://github.com/unicorn-engine/unicorn/files/801778/ppc64_unit_log.txt)
[ppc64le_unit_log.txt](https://github.com/unicorn-engine/unicorn/files/801779/ppc64le_unit_log.txt)
[ppc_unit_log.txt](https://github.com/unicorn-engine/unicorn/files/801780/ppc_unit_log.txt)
[s390x_unit_log.txt](https://github.com/unicorn-engine/unicorn/files/801781/s390x_unit_log.txt)

**Comment by luigino** [comment]
Removing the `make -C tests/unit test` line, fixes the problem only for ppc64le.

Everything else still has problems:
[ppc64_regress_log.txt](https://github.com/unicorn-engine/unicorn/files/801801/ppc64_regress_log.txt)
[ppc_regress_log.txt](https://github.com/unicorn-engine/unicorn/files/801800/ppc_regress_log.txt)
[s390x_samples_log.txt](https://github.com/unicorn-engine/unicorn/files/801799/s390x_samples_log.txt)

**Comment by aquynh** [comment]
there is no more building issue, this is just about diffing the output of core & Python binding. for some unknown reasons,  the Python arm code behaves differently. for now, you can ignore this by pulling the latest code, and comment out this line https://github.com/unicorn-engine/unicorn/blob/master/bindings/Makefile#L45

**Comment by luigino** [comment]
Is this wise? If there is an endianness problem, is LE code ever going to run?

**Comment by aquynh** [comment]
Just to pass the test, so you can build packages. I have no PPC machine to test & fix the bug for now. If you can figure out what is wrong, please report.

**Comment by aquynh** [comment]
Btw, the core still looks good, but Python binding has some weird issues it seems. You still build your packages i think

**Comment by luigino** [comment]
I see. Can you recommend a test to run on a ppc machine to see if the core works properly?

By the way, even after commenting out line 45 from bindings/Makefile I'm still seeing this error:
```
make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/unicorn-1.0/tests/regress'
make -C bindings test
make[1]: Entering directory '/home/abuild/rpmbuild/BUILD/unicorn-1.0/bindings'
make[1]: *** No rule to make target 'sample_arm.py.test', needed by 'test'.  Stop.
make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/unicorn-1.0/bindings'
```

**Comment by aquynh** [comment]
you can get the output of samples/sample_all.sh on x86, and compare with the same output on ppc. if 2 outputs are the same, then the core works properly on ppc.

you can also comment out "make -C bindings test" to see if it passes?

**Comment by luigino** [comment]
> you can get the output of samples/sample_all.sh on x86, and compare with the same output on ppc. if 2 outputs are the same, then the core works properly on ppc. 

I must be doing something wrong: I compared all the binaries found into samples after the installation for all of the architectures (arm, x86, ppc,s390) and I couldn't find two that matched.

> you can also comment out "make -C bindings test" to see if it passes?

That did the trick.

**Comment by aquynh** [comment]
not sure if you got it, but i dont mean to compare the binaries. i mean you run samples/sample_all.sh on X86 machine and on PPC machine, and compare the output from 2 runs. if they match, then PPC works. 

or if you actually did above thing, then please post the output of running sample_all.sh for all architectures, so we can see what is wrong.

**Comment by luigino** [comment]
Oh, sorry. I get it now.

[sample_all_aarch64.txt](https://github.com/unicorn-engine/unicorn/files/806130/sample_all_aarch64.txt)
[sample_all_armv7l.txt](https://github.com/unicorn-engine/unicorn/files/806131/sample_all_armv7l.txt)
[sample_all_i586.txt](https://github.com/unicorn-engine/unicorn/files/806132/sample_all_i586.txt)
[sample_all_ppc.txt](https://github.com/unicorn-engine/unicorn/files/806133/sample_all_ppc.txt)
[sample_all_ppc64.txt](https://github.com/unicorn-engine/unicorn/files/806134/sample_all_ppc64.txt)
[sample_all_ppc64le.txt](https://github.com/unicorn-engine/unicorn/files/806135/sample_all_ppc64le.txt)
[sample_all_s390x.txt](https://github.com/unicorn-engine/unicorn/files/806136/sample_all_s390x.txt)
[sample_all_x86_64.txt](https://github.com/unicorn-engine/unicorn/files/806137/sample_all_x86_64.txt)

Everything was built with gcc 6.3 and every other library should also be (pretty much) the same version.
