### ISSUE TITLE
.lib build error MSYS2 && Win 10 Home(64 Bit)

### ISSUE THREAD

**Issue by BlackADeath** [unicorn-engine/unicorn#768]
After building my depends from scratch via the commands in the COMPILE-WINDOWS.md. I attempted to build using the `UNICORN_ARCHS="arm aarch64 x86 mips" UNICORN_SHARED=yes ./make.sh cross-win32` command in MSYS2 MINGW32 Shell(Elevated) I got the following errors:

```
cmd /c "windows_export.bat x86"
Searching for installed visual studio version...
...trying registry key HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\12.0
...trying registry key HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0
...trying registry key HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\15.0
...trying registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\12.0
...trying registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0
...trying registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\15.0
Could not find an installed visual studio version. Abandoning windows static lib export operation.
```

![lib export fail0](https://cloud.githubusercontent.com/assets/452060/23340631/461256e0-fbff-11e6-9227-9ceb494b0b24.jpg)
![lib export fail1](https://cloud.githubusercontent.com/assets/452060/23340632/4612d34a-fbff-11e6-9b1c-b55059235ce5.jpg)

**Comment by aquynh** [comment]
is this on the latest Github code?

@rhelmot, do you have any comments?

**Comment by BlackADeath** [comment]
I did a ```cat``` of the .bat and found out I was missing the regkey ```InstallDir``` for some reason. Forgive my sleepy eyes. You should be able to close this issue once I fix that and retest.
