### ISSUE TITLE
ARM emulator crashing with 'Bad condition code', instead of returning bad instruction error code

### ISSUE THREAD

**Issue by oblivia-simplex** [unicorn-engine/unicorn#769]
I'm noticing that the unicorn engine sometimes crashes with a 'Bad condition code 0x%x' error message when the condition code of an ARM instruction is garbage. Is there a reason why the engine doesn't just treat instructions with mangled condition codes the same way it treats other junk instructions (returning with an error code, instead of aborting)? It would definitely be more convenient if it returned an error code instead, so that I could handle the exception on the side of the application, instead of just aborting execution. 

The case expression where this occurs is in qemu/target-arm/translate.c, in arg_gen_test_cc().

**Comment by aquynh** [comment]
Can you reproduce this bug?

**Comment by oblivia-simplex** [comment]
Sure, I can probably hack something together that'll trigger it. Here's the exact circumstance that would seem to do the trick, though:
```
  801     case 13: /* le: Z || N != V */
  802         tcg_gen_brcondi_i32(tcg_ctx, TCG_COND_EQ, tcg_ctx->cpu_ZF, 0, label);
  803         tmp = tcg_temp_new_i32(tcg_ctx);
  804         tcg_gen_xor_i32(tcg_ctx, tmp, tcg_ctx->cpu_VF, tcg_ctx->cpu_NF);
  805         tcg_gen_brcondi_i32(tcg_ctx, TCG_COND_LT, tmp, 0, label);
  806         tcg_temp_free_i32(tcg_ctx, tmp);
  807         break;
  808     default:
  809         /* This should have the emulator return with an error
  810          * code, not terminate the programme!
  811          */
  812         fprintf(stderr, "Bad condition code 0x%x\n", cc);
  813         abort();
  814     }
  815 }
```
So, I suppose that any instruction that can pass through the "bad instruction" filter, but have a most significant byte > 13, would trigger this error. Test case on the way, though.

**Comment by xizhizhang** [comment]
It seems qemu have fix this issue at this point.

https://github.com/qemu/qemu/blob/master/target/arm/translate.c#L821


And, I guess it aborts directly is because: author thinks there never got, the functions which calls it have already make sure case's would not bigger than 13.
