### ISSUE TITLE
Python Start-up Time Slow

### ISSUE THREAD

**Issue by zachriggle** [unicorn-engine/unicorn#770]
The Python bindings are extremely slow on first-import.

```
$ pip install unicorn
Collecting unicorn
Installing collected packages: unicorn
Successfully installed unicorn-1.0.0rc3
$ for i in {1..10}; do time python -c 'import unicorn'; done
python -c 'import unicorn'  0.23s user 0.26s system 91% cpu 0.537 total
python -c 'import unicorn'  0.22s user 0.25s system 94% cpu 0.498 total
python -c 'import unicorn'  0.23s user 0.25s system 94% cpu 0.509 total
python -c 'import unicorn'  0.23s user 0.24s system 94% cpu 0.506 total
python -c 'import unicorn'  0.23s user 0.25s system 94% cpu 0.499 total
python -c 'import unicorn'  0.26s user 0.24s system 90% cpu 0.556 total
python -c 'import unicorn'  0.23s user 0.21s system 92% cpu 0.481 total
python -c 'import unicorn'  0.23s user 0.19s system 93% cpu 0.450 total
python -c 'import unicorn'  0.23s user 0.20s system 93% cpu 0.463 total
python -c 'import unicorn'  0.24s user 0.20s system 93% cpu 0.465 total
```

**Comment by aquynh** [comment]
Can you investigate why?

**Comment by lallousx86** [comment]
I experienced the same. I think it had to do with the unicorn binary with various arch support resulting in a 20mb file. Zach, try to compile unicorn with just the arch you are using only. For instance if you want just x86 that would trip the size to just 3mb.

**Comment by zachriggle** [comment]
I'm using Unicorn as directly compiled from `pip install unicorn`. 

It doesn't make any sense at all to "only" compile-in support for individual architectures, nor should it incur any performance penalty just to *import* the Python module, regardless of which architectures are compiled-in.

**Comment by lunixbochs** [comment]
It's 5x slower for me to import from an egg.
