### ISSUE TITLE
make.sh fails when `which python` links to `which python3`

### ISSUE THREAD

**Issue by oblivia-simplex** [unicorn-engine/unicorn#771]
This is just a tiny issue, but it would be nice if the make scripts detected which python was in use, rather than assuming it to be python 2.7. On some linux systems (Arch and Gentoo, e.g.), /usr/bin/python is a symlink to /usr/bin/python3, not /usr/bin/python2 as assumed (mainly by qemu/configure, I think). But on every linux system that I know of, python 2.7 can be found via `which python2` (and I think this works for some BSDs as well). 

The fix is pretty straightforward: just add "--python=$(shell which python2)" to line 212 of the Makefile:
```
210 qemu/config-host.h-timestamp:                                                                                                                      
211         cd qemu && \                                                                                                                               
212         ./configure --python=$(shell which python2) --cc="${CC}" --extra-cflags="$(UNICORN_CFLAGS)" --target-list="$(UNICORN_TARGETS)" ${UNICORN_QEMU_FLA    GS}                                                                                                                                                
213         printf "$(UNICORN_ARCHS)" > config.log                                                                                                     
214         $(MAKE) -C qemu $(SMP_MFLAGS)                                                                                                              
215         $(eval UC_TARGET_OBJ += $$(wildcard qemu/util/*.o) $$(wildcard qemu/*.o) $$(wildcard qemu/qom/*.o) $$(wildcard qemu/hw/core/*.o) $$(wildcar    d qemu/qapi/*.o) $$(wildcard qemu/qobject/*.o))        
```

**Comment by aquynh** [comment]
did you follow the docs at https://github.com/unicorn-engine/unicorn/blob/master/docs/COMPILE-NIX.md? there is a part about using python2: ".. If Python 2.x is not the default Python interpreter, ensure that the appropriate option is set ...".

so basically you can run:

```
$ UNICORN_QEMU_FLAGS="--python=/path/to/python2" ./make.sh
```

but i think it is a good idea to:

- verify if the default python is python2
- if not, then find if there is python2 somewhere, and use that if you can find it
- warn & quit if nothing is found

PR to do this is welcome.

**Comment by oblivia-simplex** [comment]
Ah, I'd missed that. But sure, I'd be happy to tweak make.sh to have it do what you suggest.

**Comment by XVilka** [comment]
Should be this closed? https://github.com/unicorn-engine/unicorn/commit/27cf6617a3d9b0824fe40badf2c6b97d40e395c8
