### ISSUE TITLE
Unicorn crashes on vmovdqa

### ISSUE THREAD

**Issue by Grazfather** [unicorn-engine/unicorn#772]
I get `Error: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)`.

Regs at the time of the failure:
```
rax            0x400526 0x400526
rbx            0x7fffffffe480   0x7fffffffe480
rcx            0x0      0x0
rdx            0x7fffffffe598   0x7fffffffe598
rsi            0x7fffffffe588   0x7fffffffe588
rdi            0xa      0xa
rbp            0x7fffffffe4a0   0x7fffffffe4a0
rsp            0x7fffffffe300   0x7fffffffe300
r8             0x4005b0 0x4005b0
r9             0x7ffff7de78e0   0x7ffff7de78e0
r10            0x846    0x846
r11            0x7ffff7a2e740   0x7ffff7a2e740
r12            0x400430 0x400430
r13            0x7fffffffe580   0x7fffffffe580
r14            0x0      0x0
r15            0x0      0x0
rip            0x7ffff7dee6e7   0x7ffff7dee6e7 <_dl_runtime_resolve_avx+71>
eflags         0x206    [ PF IF ]
cs             0x33     0x33
ss             0x2b     0x2b
ds             0x0      0x0
es             0x0      0x0
fs             0x0      0x0
gs             0x0      0x0
```

```asm
0x7ffff7dee6e7  <_dl_runtime_resolve_avx+71>  vmovdqa YMMWORD PTR [rsp], ymm0   ← $pc
```
[bla.tgz.txt](https://github.com/unicorn-engine/unicorn/files/818244/bla.tgz.txt)

**Comment by aquynh** [comment]
`Error: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED).` <-- that means your memory is not mapped yet?

**Comment by Grazfather** [comment]
But see: `rsp            0x7fffffffe300   0x7fffffffe300`

And in the attached script:
```python
    # Mapping [stack]: 0x7ffffffde000-0x7ffffffff000
    emu.mem_map(0x7ffffffde000, 0x21000, 3)
    emu.mem_write(0x7ffffffde000, open('/tmp/gef-a.out-0x7ffffffde000.raw', 'r').read())
```

Unless vmovdqa is touching other memory this doesn't make sense.

**Comment by aquynh** [comment]
Can you send in a pull req with this testcase, putting it under tests/ ?

**Comment by Grazfather** [comment]
I can repro it with a one line change:

https://github.com/unicorn-engine/unicorn/blob/master/bindings/python/sample_x86.py#L15

Change to
```python
X86_CODE64 = b"\xc5\xfd\x7f\x04\x24"
```

**Comment by Grazfather** [comment]
```python
Emulate x86_64 code
>>> Tracing basic block at 0x1000000, block size = 0x4
>>> Tracing instruction at 0x1000000, instruction size = 0x4
>>> RIP is 0x1000000
ERROR: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)
```

I think that it might be choosing in incorrect opcode length (it is a five byte instruction, but thinks, above, that it's 4.

```
0x7ffff7dee6e7  <_dl_runtime_resolve_avx+71>  vmovdqa YMMWORD PTR [rsp], ymm0   ← $pc
0x7ffff7dee6ec  <_dl_runtime_resolve_avx+76>  vmovdqa YMMWORD PTR [rsp+0x20], ymm1
gef➤  x/5bx $rip
0x7ffff7dee6e7 <_dl_runtime_resolve_avx+71>:    0xc5    0xfd    0x7f    0x04    0x24
gef➤  x/5bx $rip+5
0x7ffff7dee6ec <_dl_runtime_resolve_avx+76>:    0xc5    0xfd    0x7f    0x4c    0x24
```

**Comment by aquynh** [comment]
You can find the unmapped address that Unicorn reports?

**Comment by Grazfather** [comment]
How can I do that? I can open it iteractively in python to check the state, but I don't know what to look for.

**Comment by aquynh** [comment]
you can hook `UC_MEM_FETCH_UNMAPPED`, with `hook_add()`, then in your callback you print out the address.

**Comment by Grazfather** [comment]
Yes I already said I could break open an interpreter, i just don't know the API.

I've given you a one line change to repro. Can you confirm you can repro? From there I'm hoping you'll know what to look for.

**Comment by frapik99** [comment]
Hi, I would like to help with this issue but changing the line 15 as suggested by @Grazfather does not generate the issue anymore. Are you still able to reproduce it just changing that line?

Thanks

**Comment by hugsy** [comment]
I am experiencing the same issue than @Grazfather described:
```bash
root@kali:/vagrant# ./uc
Failed on uc_emu_start() with error returned 8: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)
```
Source code attached for repro. I'll try to investigate...
[uc.c.txt](https://github.com/unicorn-engine/unicorn/files/1511385/uc.c.txt)

**Comment by aar0nge** [comment]
Just met the exactly same issue

**Comment by kr1tzb1tz** [comment]
Still experiencing the issue on the latest version of Unicorn. vmovdqu causes the same UC_ERR_FETCH_UNMAPPED exception too.

**Comment by Waterman178** [comment]
Is there a solution? How to solve it?

**Comment by aar0nge** [comment]
what's your unicorn version?  if you pop install it,  it may not be the latest

**Comment by kr1tzb1tz** [comment]
1.0.1 @aar0nge

**Comment by aar0nge** [comment]
install from source then,  it will be 1.0.2

**Comment by aar0nge** [comment]
if I remember correctly, install python bindings from source can solve it in python.
![image](https://user-images.githubusercontent.com/20163299/63562231-67900e00-c58f-11e9-9ba7-853d0254c4fa.png)
In my case, codes like this:
![image](https://user-images.githubusercontent.com/20163299/63562273-973f1600-c58f-11e9-9b64-fd4615e9aee5.png)
with certain context can run normally
