### ISSUE TITLE
Cannot read/write ARM64 Neon registers

### ISSUE THREAD

**Issue by stevielavern** [unicorn-engine/unicorn#773]
Hello,
Reading/writing ARM64 Neon registers don't seem to be implemented. For instance the following code:

```python
from unicorn import *
from unicorn.arm64_const import *

uc = Uc(UC_ARCH_ARM64, UC_MODE_ARM)

uc.reg_write(UC_ARM64_REG_X0, 1)  # General Purpose
print "X0 = 0x%x" % uc.reg_read(UC_ARM64_REG_X0)

uc.reg_write(UC_ARM64_REG_V0, 1) # Neon
print "V0 = 0x%x" % uc.reg_read(UC_ARM64_REG_V0)

uc.reg_write(UC_ARM64_REG_D0, 1) # Neon
print "D0 = 0x%x" % uc.reg_read(UC_ARM64_REG_D0)
```

produces:

```
X0 = 0x1
V0 = 0x0
D0 = 0x0
```

This seems to be because of `arm64_reg_read` and `arm64_reg_write` (cf https://github.com/unicorn-engine/unicorn/blob/master/qemu/target-arm/unicorn_aarch64.c#L45 ) which only handle General Purpose registers.
Would it be possible to add support for Neon registers?

**Comment by aquynh** [comment]
yes, that is possible. pull req to support this is welcome.
