### ISSUE TITLE
Is Unicorn multi-thread safe?

### ISSUE THREAD

**Issue by gdbinit** [unicorn-engine/unicorn#783]
So I am trying to use a bunch of Unicorn parallel threads to emulate a few thousand functions of a target binary.
I'm using OS X NSOperationQueue to take care of the threading, which is essentially something like queue all operations you want and manage/run X simultaneous threads.
The method will call a entrypoint function that sets a Unicorn instance, maps binary, and starts emulation. Two hooks are set, one for code and one for memory.
From a thread dump it seems that the hooks run on their own threads. Are the hooks thread safe, meaning one thread hook per Unicorn instance started?
The reason for this is that I increased the number of threads from 8 to 16 (I have 16 cores available) and now my app got stuck in some loop so that got me thinking if there are any multi-threading issues on my scenario with the hooks. The only global being used is a global structure that contains some data and a pointer to a mmap'ed buffer being used by each instance to map the binary I want to emulate.

**Comment by aquynh** [comment]
so that may indicate a bug somewhere?

this reminds me of this issue https://github.com/unicorn-engine/unicorn/issues/636

**Comment by gdbinit** [comment]
I'm trying to find where the problem is and create a test if possible.
