### ISSUE TITLE
Publish ruby bindings at rubygems.org

### ISSUE THREAD

**Issue by anatol** [unicorn-engine/unicorn#784]
Rubygems is a standard way to distribute and install packages in the ruby world. It would be really great to have ruby bindins hosted at rubygems (similar how python lib is hosted at pipy).

**Comment by aquynh** [comment]
yes that would be perfect! however, the Ruby binding @sashs is quite busy. can you contribute this feature?

**Comment by sashs** [comment]
I am working on that. ;-)

**Comment by anatol** [comment]
Thanks @sashs. Out of curiosity what gem name are you going to use? `unicorn` is a widely known web server for Ruby apps.

**Comment by anatol** [comment]
Hi @sashs any update on it?

**Comment by sashs** [comment]
HI @anatol, sorry, unfortunately not. Time is a rare thing.

**Comment by fallenoak** [comment]
@sashs In the interim, any chance the Ruby bindings gem could be renamed to something like `unicorn-engine`? When doing local installs of the bindings, it's a bit frustrating to have a conflict with `unicorn` (the web server mentioned by @anatol).

**Comment by sashs** [comment]
The ruby binding is available on rubygems. But it is just the binding. So the unicorn library needs to be installed on the system

**Comment by anatol** [comment]
Thank you very much. Could you please provide name or link to the ruby gem you published?

**Comment by sashs** [comment]
It's https://rubygems.org/gems/unicorn-engine/versions/1.0.0

**Comment by aquynh** [comment]
But the current version is 1.0.1, not 1.0.0?

**Comment by sashs** [comment]
Oh, sorry, I forgot to change the version number. :)
I will fix that today.
