### ISSUE TITLE
ARM BE8 mode

### ISSUE THREAD

**Issue by zachriggle** [unicorn-engine/unicorn#785]
The ARM spec was written by people who hit their head too many times, and includes a "be8" mode in addition to traditional "big" and "little" endiannesses.  Specifically, BE8 uses little-endian instructions and big-endian data memory. 

If it helps any, qemu-user supports this mode.  ARMv7 either added or removed support for traditional BE32, in favor of BE8, so it's recent and relevant.  The current GCC for Ubuntu targeting ARMBE will emit BE8 binaries.

**Comment by aquynh** [comment]
@xizhizhang, what do you think?

**Comment by aquynh** [comment]
for reference: http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0290g/ch06s05s01.html

**Comment by zachriggle** [comment]
Relevant patches: https://patchwork.ozlabs.org/patch/143758/

**Comment by aquynh** [comment]
if the patch you provided above is enough, that is not a lot of work to port over. can you do that?

**Comment by xizhizhang** [comment]
It seems qemu have already commit BE8's in 2012:
https://github.com/qemu/qemu/commit/d8fd2954996255ba6ad610917e7849832d0120b7
so, is also in unicorn too.

> BE-32(traditional big endian) is supported by ARM cores up to the ARM11 family (v6) (for example ARM7TDMI, ARM926EJ-S, ARM1136JF-S). BE-8 is supported by the ARM11 family and later (for example ARM1136JF-S, Cortex-R4, Cortex-A8). ARMv7 and ARMv8 cores do not support BE-32.

And, gcc toolchain already choose --be8 as the default link option.

I have just test a BE8 style THUMB2 code in big endian example.
`\xf0\x4f\x00\x37\xeb\xa2\x01\x03`
Above binary means "mov r0, #0x37; sub r1, r2, r3". and it works correctly.

If there are some bugs in ARM big endian mode's implementation, I would like to try to fix it.

Thanks~

**Comment by zachriggle** [comment]
@aquynh That's the patch that adds support for QEMU.  The code is all there already, support just needs to be added to Unicorn.

**Comment by aquynh** [comment]
Zach, can you send a testcase for this?

**Comment by yekscorp** [comment]
I just ran into this problem with a binary I am working with. Is there a plan to add a flag to enable this mode in unicorn?
