### ISSUE TITLE
Mem leak in uc_mem_protect?

### ISSUE THREAD

**Issue by gdbinit** [unicorn-engine/unicorn#786]
uc_mem_protect() appears to be leaking serious memory.
It calls split_region() which then calls copy_region(), which allocates memory that is only freed on error and not on success case. The allocated backup pointer is only used for uc_mem_write and not returned so I guess it should be ok to also free it on success return.

I'll test it later on and put a PR if it fixes this issue.

**Comment by gdbinit** [comment]
Sounds like it was just the missing free(). Pull request made. There are a few more leaks somewhere else, trying to find them.

**Comment by aquynh** [comment]
fantastic, thanks!
