### ISSUE TITLE
Do Unicorn can add a  pause API?

### ISSUE THREAD

**Issue by maldiohead** [unicorn-engine/unicorn#789]
During run a  instruction stream,I wanna to see the execution states (like:cpu context,memory state)
,I think add a press  key(eg: Ctrl+C) event handler when execution instruction and if trigger the key ,the unicorn can pause  is a good idea.

**Comment by aquynh** [comment]
Note that Unicorn is a framework, not a tool, so you cannot have what you want in Unicorn.

**Comment by maldiohead** [comment]
ok! I do it by myself.
