### ISSUE TITLE
Arm64 interface does not expose NZCV

### ISSUE THREAD

**Issue by bunnei** [unicorn-engine/unicorn#790]
There exists a definition to read the NZCV flags from the ARM64 CPU core (UC_ARM64_REG_NZCV), but searching through the code, this does not seem to actually be used anywhere. Apologies if this is a duplicate/known issue - but I didn't see anything here. Thanks!

**Comment by aquynh** [comment]
you need to add that to https://github.com/unicorn-engine/unicorn/blob/master/qemu/target-arm/unicorn_aarch64.c, then please send us pull req.
