### ISSUE TITLE
cycle counter tool ?

### ISSUE THREAD

**Issue by rofl0r** [unicorn-engine/unicorn#792]
is there an existing tool using unicorn that can count the exact number of instructions executed ? 

i tried compiling dynamorio, but that is highly [unportable](https://github.com/DynamoRIO/dynamorio/issues/2324). i've had some issues with unicorn too (due to the very badly written Makefile which doesn't quite work how it should... for example hardcoded toolchain names, include and library dirs, etc...) but it was not too hard to [work around](https://github.com/sabotage-linux/sabotage/blob/master/pkg/unicorn#L13).

dynamorio apparently ships a tool called "drrun" and a plugin for it called "inscount" which was demonstrated in [this youtube video](https://www.youtube.com/watch?v=B6Zh3pFcZog) and this looks like a very nice way for sidechannel attacks.

**Comment by aquynh** [comment]
Can you elaborate the problem with building?

To count instructions, you can hook with UC_HOOK_CODE, and have the callback count every time it runs.

**Comment by aquynh** [comment]
ah i see your workaround to build Unicorn now. that is what we saw before, hence all those env variables. so this is not really an issue.

**Comment by rofl0r** [comment]
thanks for your reply; and sorry for bringing up the Makefile without hard facts!
also sorry for this sounding like a rant, when in fact i'm very grateful that you invest your time into making this great project.
but since we're now talking of it already:
i had some issues to get the .so built correctly. when i just did `make all install`, it produced .a and .so, however the .so was missing some symbols which the .a had (something from the qemu dir):
```
>>> import angr
<type 'exceptions.OSError'> Error loading shared library libunicorn.so.1: Exec format error (needed by /lib/python2.7/site-packages/simuvex/lib/sim_unicorn.so) <traceback object at 0x7fa4b36ec5a8>
```
some other things i noticed:
- usage of $(CROSS) instead of the standard $(CROSS_COMPILE)
- usage of $(shell uname) to find out the arch, which is not compatible with crosscompiling (usually if this info is required, it is taken from the cross-compiler triplet: e.g. `$(CC) -dumpmachine`

**Comment by rofl0r** [comment]
oops. seems the exec format error is unrelated; i fixed that with a wrapper setting LD_LIBRARY_PATH before launching python. i tried quite hard to reproduce the invalid .so; but it seems i'm currently unable to.

**Comment by aquynh** [comment]
you can always install unicorn for Python from Pypi, with just one command "pip install unicorn".

**Comment by rofl0r** [comment]
i know, but i want to make a reproducible solution for my distro, i.e. i don't want to circumvent the system package manager.

**Comment by radare** [comment]
1 instruction != 1 cycle

ESIL supports both

**Comment by rofl0r** [comment]
@radare nice! do you have a link or some other documentation handy, that explains how radare2's ESIL can be used to execute a given binary/function and count the instructions?

**Comment by lunixbochs** [comment]
https://github.com/lunixbochs/inscount

This will cycle count i386 and x86_64. You should probably edit https://github.com/lunixbochs/inscount/blob/master/linux-user/syscall.c#L5958 and add `if (arg1 == 2) break;` as the instruction count is printed to stdout.

    ./configure --target-list=x86_64-linux-user

**Comment by aquynh** [comment]
is this possible because of this commit https://github.com/lunixbochs/inscount/commit/0e511994a91526bb4c6714532047cf59787f9407? i see that your patch exposes the internal `inscount`, but that counts the number of instructions, but not instruction cycle?

**Comment by lunixbochs** [comment]
from the original question

> that can count the exact number of instructions executed

cycle counting is harder, and ESIL is a better tool for that, but qemu-user is better for running a real-world program

**Comment by danghvu** [comment]
@rofl0r can you please iterate again whether you need "cycle" or "instruction" ? It's one in the title and one in the text which is confusing, they are very different.

Please feel free to submit another issue if you are having problem with the Makefile.

**Comment by lunixbochs** [comment]
@radare what source are you using for instruction latency/throughput data?

**Comment by aquynh** [comment]
btw, is there any demand to add instruction cycle info to Capstone?

**Comment by lunixbochs** [comment]
Yes! But for which CPU? I've been looking for this information and found it in PDF form only. I'm planning to generate machine-readable latency and throughout information for whichever CPUs I can find, and write a Go library that adds this information to Capstone instructions. Help with the data would be nice, especially for the non-Intel platforms. (even cooler would be to collect enough information to determine things like NEON pipeline stall cycles on a specific ARM CPU, for example IIRC the Cortex A8 has two NEON lanes, you stall one lane for N cycles when writing a register, but any NEON op that doesn't use the same register will stall the second lane instead... so the latencies overlap).

**Comment by aquynh** [comment]
for all architectures, starting from x86, arm & arm64.

**Comment by lunixbochs** [comment]
I figured you meant multiarch. Cycle timings vary greatly even within the same arch, and based on workload, pipeline, stalls, etc on the same CPU model.

**Comment by rofl0r** [comment]
cool stuff @lunixbochs ! as for the confusion cycle/instruction count, i meant instruction count originally. but both are interesting, of course.
