### ISSUE TITLE
Error UC_ERR_READ_UNMAPPED despite hooking unmapped memory reads

### ISSUE THREAD

**Issue by AlexAltea** [unicorn-engine/unicorn#793]
Not sure if there's something wrong on my side. I want to intercept and allow any unmapped memory read/write event and allow my program to continue regardless. For that matter, I create a hook for such events in the entire address space, which will *always* return `true`.

As expected, the access will be marked as handled in [`qemu/softmmu_template.h:203`](https://github.com/unicorn-engine/unicorn/blob/1.0/qemu/softmmu_template.h#L203). However, shortly after, in [`qemu/softmmu_template.h:304`](https://github.com/unicorn-engine/unicorn/blob/1.0/qemu/softmmu_template.h#L304), it will be treated as an IO access which will result in throwing back a `UC_ERR_READ_UNMAPPED` error.

Minimal test case:
```cpp
#include <stdint.h>
#include <unicorn/unicorn.h>

bool hookfunc(uc_engine *uc, uc_mem_type type, uint64_t address, int size, int64_t value, void *user_data) {
    printf("READ!\n");
    return true;
}

int main(int argc, char **argv, char **envp) {
    uc_engine *uc;
    uc_err err;
    uc_hook h;

    // mov ecx, dword ptr [0x20000]
    char code[] = { 0x8B, 0x0D, 0x00, 0x00, 0x02, 0x00 };
    int addr = 0x10000;

    uc_open(UC_ARCH_X86, UC_MODE_32, &uc);
    uc_mem_map(uc, addr, 4*1024, UC_PROT_EXEC);
    uc_mem_write(uc, addr, code, sizeof(code));
    uc_hook_add(uc, &h, UC_ERR_READ_UNMAPPED, hookfunc, NULL, 1, 0);
    err = uc_emu_start(uc, addr, addr + sizeof(code), 0, 0);
    if (err) {
        printf("Failed on uc_emu_start() with error returned: %s\n", uc_strerror(err));
    }
    uc_close(uc);
    return 0;
}
```

This should return `UC_ERR_OK`, but instead returns `UC_ERR_READ_UNMAPPED` .

**Comment by AlexAltea** [comment]
I suspect this might be caused because `helper_le_ld_name`/`helper_be_ld_name`  *needs* to read from some actual address at [`qemu/softmmu_template.h:376`](https://github.com/unicorn-engine/unicorn/blob/1.0/qemu/softmmu_template.h#L376-L381).

## Proposal
Create a new memory hook event type (e.g. `UC_HOOK_MEM_READ_BYPASS` or any more suitable name) that is checked at the beginning of `helper_*_ld_name` and allows the user to specify the read value.
```cpp
HOOK_FOREACH(uc, hook, UC_HOOK_MEM_READ_BYPASS) {
    if (!HOOK_BOUND_CHECK(hook, addr))
        continue;
    if ((handled = ((uc_cb_readmem_t)hook->callback)(uc, UC_MEM_READ_UNMAPPED, addr, DATA_SIZE, &res, hook->user_data)))
        return res;
}
```

These events should be handled by a new callback type:
```cpp
/*
  Callback function for handling arbitrary memory read events (UC_MEM_READ)
  @address: address where the code is being executed
  @size: size of data being read or written
  @value: value of data being read from memory.
  @user_data: user data passed to tracing APIs
  @return: return true to use user-specified value, or false to continue with actual memory read.
*/
typedef bool (*uc_cb_readmem_t)(uc_engine *uc, uint64_t address,
    int size, int64_t& value, void *user_data);
```

The naming, comments and callback type definitions can be improved. If we all agree with this, we could consider adding it to Unicorn, the pull request should be relatively small.

**Comment by danghvu** [comment]
So the use-case is that you don't want to map that memory but want to emulate its value ?
This is quite a weird situation, we have a `FIXME` at line 209 that we are unsure when the user does not actually mapped / handled it properly.

If this is the idea, we need something similar for EXEC / WRITE UNMAPPED, to allow continue without the user mapping the memory.

**Comment by AlexAltea** [comment]
Yes, basically I want to allow users to replace `helper_*_ld_name` and `helper_*_st_name` with their custom implementation (only taking into account the target address).

Sounds weird, but that's what I need in my situation: I only map PROT_EXEC memory containing my code, and all R/W accesses need to be intercepted and the values delivered to/from the *real* VAS (and not the emulated memory).

If that's too uncommon to be accepted as a part of Unicorn.

I'

**Comment by aquynh** [comment]
agreed with @danghvu that if we do this, we want to also handle WRITE, not just READ (sounds like we dont need to handle EXEC). can you send a pull req, then we have further discussion on that?

**Comment by lunixbochs** [comment]
> delivered to/from the real VAS 

You can use `uc_mem_map_ptr` for this - on page fault, you `uc_mem_map_ptr()` the corresponding host page. See here: https://github.com/lunixbochs/precorn/blob/master/src/precorn.c#L15

Works great in my tests.
