### ISSUE TITLE
Cross compile is failing on Ubuntu 64

### ISSUE THREAD

**Issue by lallousx86** [unicorn-engine/unicorn#795]
Hello,

That's my system configuration:

Linux ubuntu 4.8.0-36-generic #36~16.04.1-Ubuntu SMP Sun Feb 5 09:39:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

I clone Unicorn, and do:

$ ./make cross-win32

It fails after a while with:

  LINK    sample_arm
/usr/bin/i686-w64-mingw32-ld: cannot find -lrt
collect2: error: ld returned 1 exit status
Makefile:103: recipe for target 'sample_arm' failed
make[1]: *** [sample_arm] Error 1
make[1]: Leaving directory '/home/elias/projects/44/unicorn/samples'
Makefile:211: recipe for target 'all' failed
make: *** [all] Error 2

How did you guys cross build for Windows from Linux? what am I missing?

**Comment by aquynh** [comment]
for Windows binary, i always compile with msys2, which is well tested by Appveyor: https://github.com/unicorn-engine/unicorn/blob/master/docs/COMPILE-WINDOWS.md

cross compile on Linux must be broken. you may try to remove that "-lrt", and see if that helps. if you can fix this, please pull req, thanks.

**Comment by lallousx86** [comment]
Thanks for the fast reply. I am really having problems compiling on Windows and Linux by just following the instructions.

For instance, the instructions do not describe fully the dependencies needed, etc.

While I give that another shot, do you think you can compile the Windows binaries (32bits and 64bits) with TARGET_X86_64 defined?

I am having problems working with RIP register and what not using both public Windows Python binding binaries (1.0).

Thanks!

**Comment by lallousx86** [comment]
Hello,

So if I follow the windows compilation notes and download MSYS2, here are all the errors:

After install MSYS and following the instructions with pacman, I proceed to build:
1)
$ ./make.sh cross-win32
cd qemu && \
./configure --cc="i686-w64-mingw32-gcc" --extra-cflags="-DUNICORN_HAS_X86 -fPIC -fvisibility=hidden" --target-list="x86_64-softmmu,"

ERROR: Python not found. Use --python=/path/to/python

make: *** [Makefile:214: qemu/config-host.h-timestamp] Error 1


2)
I figure I have to make a link to python2:

$ ln -s /usr/bin/python2 /usr/bin/python

3)
Now I think it should compile, but another error:

$ ./make.sh cross-win32
cd qemu && \
./configure --cc="i686-w64-mingw32-gcc" --extra-cflags="-DUNICORN_HAS_X86 -fPIC -fvisibility=hidden" --target-list="x86_64-softmmu,"

ERROR: "i686-w64-mingw32-gcc" either does not exist or does not work

make: *** [Makefile:214: qemu/config-host.h-timestamp] Error 1

user@WIN-3LEAQH3387K MSYS /c/projects/unicorn
$

4)
Perhaps I should 'ln' again?!!?
user@WIN-3LEAQH3387K MSYS /c/projects/unicorn
$ ln -s /mingw32/bin/i686-w64-mingw32-gcc.exe i686-w64-mingw32-gcc    

5)
Nope, I was wrong again...

$ ./make.sh cross-win32
cd qemu && \
./configure --cc="i686-w64-mingw32-gcc" --extra-cflags="-DUNICORN_HAS_X86 -fPIC -fvisibility=hidden" --target-list="x86_64-softmmu,"

ERROR: "i686-w64-mingw32-gcc" either does not exist or does not work

make: *** [Makefile:214: qemu/config-host.h-timestamp] Error 1


==========
Are the instructions missing?

What am I doing wrong?

Thanks!

**Comment by aquynh** [comment]
either your Mys setup is broken, or you miss something in the setup step. i dont have to do step (2) & (4) at all.

my experience is that never install Cygwin & Msys on the same machine, or it totally messes up.

in case you still cant use Msys, i recommend to compile the branch "msvc" using MSVC: https://github.com/unicorn-engine/unicorn/tree/msvc/msvc

note that there are some issues with the latest commits on that branch, which breaks compilation, so you should check out the older commit https://github.com/unicorn-engine/unicorn/commit/1bef32fff600b4c7188447da36124398421e97b2 of that branch.

btw, the broken comes from a new architecture "armbe", so we need to update MSVC solution files for that. if you can fix that, please send pull req.

**Comment by ril3y** [comment]
FWIW - I followed the same instructions and had the very same error.
