### ISSUE TITLE
CPU state API

### ISSUE THREAD

**Issue by lunixbochs** [unicorn-engine/unicorn#8]
It would reduce API overhead if a pointer to an arch-specific CPU state could be retrieved via an API call as well as passed into callbacks.

If I add a basic block hook that prints changed registers on block entry (which can be found in usercorn), it generates 15+ extra `read_reg()` API calls per invocation.

You could pass callbacks a zero-copy pointer to a CPU state which could be accessed for current registers. This can be useful on almost all of the callback hook types. For example, on syscall I need to access rax unconditionally, as well as a variable number of registers.

This could also make generic instruction hooking nicer, as you only need to pass the CPU state and immediate values.

Example state struct:

    struct uc_x86_state {
        uint64_t *rip;
        uint64_t *rax, *rbx, *rcx, *rdx, *rsi, *rdi,
                 *r8, *r9, *r10, *r11, *r12, *r13, *r14, *r15;
    };

I don't think there's a nice way to both make this zero-cost and keep the Unicorn register consts, due to overlapping registers like `X86_REG_AX`, `X86_REG_EAX`, `X86_REG_RAX`

**Comment by lunixbochs** [comment]
What about this API?

    uc_get_regs(handle, uint32_t *names, uint64_t *values_out, uint32_t length);
    uc_set_regs(handle, uint32_t *names, uint64_t *values_in, uint32_t length);

    uint32_t names[] = {RDI, RSI, RDX, RCX, R8, R9};
    uint64_t values[6];
    uc_get_regs(handle, names, values, 6);
    values[0] = 1;
    uc_set_regs(handle, names, values, 6);

It's not the safest API (potential for off-by-one errors) but I'm mostly aiming for fast.

The alternative in my mind is:

    uint64_t regs[UC_X86_REG_COUNT];
    uc_get_all_regs(handle, regs);
    regs[UC_X86_REG_RDI] = 1;
    uc_set_all_regs(handle, regs);

where the main downside here is that some architectures have a LOT of regs, which is why I'd prefer the former.

**Comment by aquynh** [comment]
to keep it simple, i think it would be better if the new APIs get all the registers at once, not only those selected one.

about API names, to be consistent, `uc_reg_read_all()` & `uc_reg_write_all()` sound OK to me. any other ideas?

**Comment by lunixbochs** [comment]
I don't think we should include vector registers (32 512-bit AVX registers is 16KB), and it should be either a uint64_t array indexed by the register's enum, or a flat union-free struct (though a struct is much harder to integrate with bindings).

**Comment by lunixbochs** [comment]
I'm satisfied by the performance and ability of #506 to handle weird register types, so I'm closing this.
