### ISSUE TITLE
Illegal instructions on M68K e.g. lsl and subi instructions

### ISSUE THREAD

**Issue by jventer** [unicorn-engine/unicorn#804]
I'm getting a few illegal instruction errors from qemu. For example, changing the sample code in sample_m68k.c as follows:
`#define M68K_CODE "\xe5\x4a"  ; //lsl.w #$2, d2`
results in 
> qemu: fatal: Illegal instruction: e54a @ 00010000

and

`#define M68K_CODE "\x04\x42\x00\x08" ; //subi.w #$8, d2`
results in 
> qemu: fatal: Illegal instruction: 0442 @ 00010000

Moves seem to work OK. Seems qemu considers an incomplete instruction set?

**Comment by aquynh** [comment]
which disassembler are you using?

it is possible that this code is unsupported yet. you can look at the latest Qemu version can handle it, and port it back to Unicorn if possible.

**Comment by jventer** [comment]
Capstone handles the byte code just fine and maps to mnemonics without problem, it's basic 68000 code.  I doubt QEMU is unable to handle it as it seems the implementation is relatively comprehensive.

**Comment by aquynh** [comment]
you can confirm your doubt by investigating how the above code is handled in https://github.com/unicorn-engine/unicorn/blob/master/qemu/target-m68k/translate.c. let me know what you find.

**Comment by jventer** [comment]
Ok thanks, this helps. I have checked the current implementation in unicorn, it misses opcode both opcode definitions and a new M68K_FEATURE compared to the official qemu repo. 

Qemu lags a bit behind vivier for opcode implementation [here]([https://github.com/vivier/qemu-m68k/blob/680x0-v2.7.0/target-m68k/translate.c])), but even this is not fully complete.

**Comment by aquynh** [comment]
great, now go ahead fixing this issue, then send in pull req ;-)
