### ISSUE TITLE
check_exit_request on every memory access?

### ISSUE THREAD

**Issue by lunixbochs** [unicorn-engine/unicorn#823]
this seems expensive, is there a better way?

```
 qemu_st_i64 rbx,tmp2,leq,$0x2
 ld_i32 tmp11,env,$0xffffffffffffffec
 movi_i32 tmp12,$0x0
 brcond_i32 tmp11,tmp12,ne,$0x0

 qemu_ld_i64 tmp0,tmp2,ub,$0x2
 ld_i32 tmp11,env,$0xffffffffffffffec
 movi_i32 tmp12,$0x0
 brcond_i32 tmp11,tmp12,ne,$0x0
```

---

does cpu_exit only exist because cpu_loop_exit only works from the same thread? that shouldn't matter for memory exceptions

**Comment by lunixbochs** [comment]
okay, so after removing `check_exit_request` from `tcg_gen_qemu_{ld,st}_*` and updating the `cpu_exit()` calls in `softmmu-template.h` to also call `cpu_loop_exit()`, it looks like the behavior of Unicorn has strictly *improved*. I can't help but think I'm missing something here. It looks like Unicorn has a bug with exit PC on fetch errors that this also fixes.

Here's my Unicorn commit: https://github.com/lunixbochs/unicorn/commit/08049f765aaa08ca0a14f6899eaaa7f4f878f9d7

Here's a usercorn trace for the previous behavior dubbed "asmexit": https://bochs.info/p/39mt6
And here's a trace for the patched behavior dubbed "jmpexit": https://bochs.info/p/u4952

It exits successfully without looping in both versions, but notice the final PC (RIP) is different:

asmexit: `0x4d8590`
jmpexit: `0x4d85a2`

From the trace, the faulting code is at `0x4d85a2`, so the current behavior (asmexit) doesn't sync the correct PC on exit.
```
0x4d85a2: mov rdx, qword ptr [rax]
invalid read: @0x0, 0x8 = 0x0
```

@aquynh what's the reason for `check_exit_request` on each memory access? do you see anything wrong with changing it to use the longjmp exit?

**Comment by lunixbochs** [comment]
The same applies to check_exit_request on HOOK_CODE (which is emitted way too often for check_exit_request to be sane). I get around a 10% speedup on a very complex workload with this patch: https://bochs.info/p/nnwb3e

I assume there are problems with register syncing or something? But TCG should have enough information to recover register states even on a longjmp out.

**Comment by aquynh** [comment]
i remember that i had to check exit request on every memory access because the callback can request to stop emulation.

not sure what is missing with your approach. i need to look closer to the code when i have time.

**Comment by aquynh** [comment]
to improve the performance, perhaps we need to have a way to specify the wanted "instrumentation strategy", because the strategies can be mutually exclusive.

**Comment by lunixbochs** [comment]
What conflicts between instrumentation and hooks? I think hooks will just slow down the instrumentation, but they should layer fine.

**Comment by aquynh** [comment]
for example, if we know that we never quit emulation in memory access callback, we can tell the core not to inject "check_exit_request" into JIT code.

**Comment by lunixbochs** [comment]
This says the main reason is "check if the last memory access was invalid", which is already handled by longjmp: https://github.com/unicorn-engine/unicorn/blob/513075e061e6642af696380f189d17a84b95241e/qemu/tcg/tcg.c#L936
