### ISSUE TITLE
Fix const_generator.py Comment Detection

### ISSUE THREAD

**Issue by 0xAlexei** [unicorn-engine/unicorn#829]
When adding comments in unicorn.h, I noticed that const_generator.py gets confused when constant names are used in multiline comments. As a simple test, try adding the following to unicorn.h:

/*
	UC_MEM_WRITE foobar UC_MEM_READ
*/

Then run:
$ python const_generator.py go
WARNING: Unable to convert ['UC_MEM_WRITE', 'foobar', 'UC_MEM_READ']
  Line = UC_MEM_WRITE foobar UC_MEM_READ

------------------------------------------------------------

Additionally, try:

/*
	UC_NOT_A_REAL_CONSTANT
*/

Then run
$ python const_generator.py ruby

No error is emitted from this comment, but a constant is created automatically in unicorn_const.rb
        ....
	UC_HOOK_MEM_VALID = 7168
	UC_NOT_A_REAL_CONSTANT = 7169
	UC_QUERY_MODE = 1
        ....

------------------------------------------------------------

Finally, try:

/*
this will cause problems:
UC_X86_INS_IN
*/

$ python const_generator.py go

Now in unicorn_const.go we get:
        ....
	HOOK_MEM_VALID = 7168
	X86_INS_IN = 7169
	QUERY_MODE = 1
        ....

But in x86_const.go we also have:
       ....
	X86_INS_IMUL = 217
	X86_INS_IN = 218
	X86_INS_INC = 219
        ....

This will cause problems later (I noticed it during CI building after a PR) as the Go compiler will choke on the redefinition of the const.

**Comment by aquynh** [comment]
yes const_generator.py is not smart enough: it should ignore everything being commented. it is good to have a simple parser inside to solve this problem.
