### ISSUE TITLE
AArch64 Exception Syndrome Inaccessible

### ISSUE THREAD

**Issue by misson20000** [unicorn-engine/unicorn#838]
When an exception is taken, Unicorn will [invoke the interrupt hooks](https://github.com/unicorn-engine/unicorn/blob/513075e061e6642af696380f189d17a84b95241e/qemu/cpu-exec.c#L134), passing `cpu->exception_index` to the `uc_cb_hookintr_t`.

For my use case, I want to hook `SVC` instructions on AArch64, which take an exception to EL1. On an actual piece of hardware, this writes the immediate value provided in the `SVC` instruction to an [exception syndrome register](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.den0024a/CHDEIEBG.html). The QEMU code to do this is in [`aarch64_cpu_do_interrupt`](https://github.com/unicorn-engine/unicorn/blob/513075e061e6642af696380f189d17a84b95241e/qemu/target-arm/helper-a64.c#L489), and I would submit a pull request adding [the exception syndrome registers](https://github.com/unicorn-engine/unicorn/blob/master/qemu/target-arm/cpu.h#L198) to reg_read and reg_write, but `cc->do_interrupt(cpu)` is only run for x86, and on AArch64, it messes with some CPU state that we probably don't want it to.

I'm not sure how exceptions work on other architectures, but for AArch64, I think the best solution would be to add a `uint32_t syndrome` parameter to [`uc_cb_hookintr_t`](https://github.com/unicorn-engine/unicorn/blob/master/include/unicorn/unicorn.h#L171). This would break ABI, but I'm also not sure how much that matters to Unicorn.

**Comment by lunixbochs** [comment]
Instead of passing `syndrome` to the hook, why not manually write the same register and expose it via `reg_read()`?

**Comment by misson20000** [comment]
There isn't a way to properly determine the level the exception is taken to, so we don't know which exception syndrome register to read from. I say "properly" because an exception will *probably* be taken to EL1, but that's not a good assumption to be making.

Maybe make some sort of pseudo-registers for the exception syndrome and target exception level? Actually, that might be a better job for the `uc_query` endpoint.

**Comment by lunixbochs** [comment]
To handle the interrupt, you just need the last esr written, not the level right? Why not just add an ESR psuedoreg?

**Comment by misson20000** [comment]
I'd feel dirty making registers that don't actually exist, but that sounds like it'd work. I'll open a pull request soon.
