### ISSUE TITLE
Gitignored version.rb file, but it is required in const.rb

### ISSUE THREAD

**Issue by s-ashwinkumar** [unicorn-engine/unicorn#839]
We are using a solution where we want to freeze gems into our vendor directory and not depend on the server having the gems. When Pushing the gem builds into version control, because of the gitignore entry, vendor.rb never gets checked in.

But when I try to run unicorn (or even just unicorn -v) it results in an error
```
bash-4.1# bundle exec unicorn -v
bundler: failed to load command: unicorn (/office/vendor/gems/ruby/2.1.0/bin/unicorn)
LoadError: cannot load such file -- unicorn/version
  /office/vendor/gems/ruby/2.1.0/gems/unicorn-4.8.2/lib/unicorn/const.rb:44:in `require'
  /office/vendor/gems/ruby/2.1.0/gems/unicorn-4.8.2/lib/unicorn/const.rb:44:in `<top (required)>'
  /office/vendor/gems/ruby/2.1.0/gems/unicorn-4.8.2/lib/unicorn.rb:108:in `require'
  /office/vendor/gems/ruby/2.1.0/gems/unicorn-4.8.2/lib/unicorn.rb:108:in `<top (required)>'
  /office/vendor/gems/ruby/2.1.0/gems/unicorn-4.8.2/lib/unicorn/launcher.rb:9:in `require'
  /office/vendor/gems/ruby/2.1.0/gems/unicorn-4.8.2/lib/unicorn/launcher.rb:9:in `<top (required)>'
  /office/vendor/gems/ruby/2.1.0/gems/unicorn-4.8.2/bin/unicorn:3:in `require'
  /office/vendor/gems/ruby/2.1.0/gems/unicorn-4.8.2/bin/unicorn:3:in `<top (required)>'
  /office/vendor/gems/ruby/2.1.0/bin/unicorn:23:in `load'
  /office/vendor/gems/ruby/2.1.0/bin/unicorn:23:in `<top (required)>'
```

This is because const.rb refers to the version.rb file, but when we commit the frozen gems, because of gitignore the version.rb never made it inside our version control.  Why is there a file in the code base and still in gitignore ?

**Comment by aquynh** [comment]
@sashs, do you have any comments?

**Comment by sashs** [comment]
Hi, in which gitignore is version.rb? I haven't found it in anyone and git status shows that the file has changes when I change this file.
