### ISSUE TITLE
Broken installation package on Windows 10 x64 python Python 2.7.12 on 64 bit

### ISSUE THREAD

**Issue by 0xbadc0de1** [unicorn-engine/unicorn#848]
As suggested by the website, for python bindings only, it should be enough to download the python installer for the x64 version of python. However one cannot import unicorn.x86_const. I was able to fix this by abruptly clone the git repo and run setup.py and manually copy the core DLL of the emulator.

**Comment by aquynh** [comment]
will see how to fix this. but you can always install Python binding (including the core inside) with Pip from Windows machine, with:

```
c:\> pip install unicorn
```
