### ISSUE TITLE
Splitting uc_hook_add API

### ISSUE THREAD

**Issue by felberj** [unicorn-engine/unicorn#849]
Hi, I was looking into the **uc_hook_add** API and there are two things that I am not so happy with:

- It accepts a variable amount of parameters
  - For when a specific hook type is requested
- The callback is a void*

I think this is bad and I wanted to ask whether a pull request would be appreciated that does the following:

- Split uc_hook_add into a function for each callback type
- Make the functions accept a fixed amount of arguments
- Break the existing API **(?)**

Currently the **uc_hook_add** API was very hard to read for me.  This should make the API easier to understand and also adds some compile-time checks.

## Proposed new API

```c
uc_err uc_hook_insn_out(uc_engine *uc, uc_hook *hh, int type, uc_cb_insn_out_t *callback,
        void *user_data, uint64_t begin, uint64_t end);

uc_err uc_hook_insn_in(uc_engine *uc, uc_hook *hh, int type, uc_cb_insn_in_t *callback,
        void*user_data, uint64_t begin, uint64_t end);

uc_err uc_hook_intr(uc_engine *uc, uc_hook *hh, int type, uc_cb_hookintr_t *callback,
        void *user_data, uint64_t begin, uint64_t end);

uc_err uc_hook_code(uc_engine *uc, uc_hook *hh, int type, uc_cb_hookcode_t *callback,
        void *user_data, uint64_t begin, uint64_t end);

uc_err uc_hook_insn(uc_engine *uc, uc_hook *hh, int type, uc_cb_hookcode_t *callback,
        void *user_data, uint64_t begin, uint64_t end, uint32_t instruction);
```

And more for the memory access hooks.

Thoughts?

Related Issues: #394

**Comment by danghvu** [comment]
I agree the callback shouldn't be `void*`.
The original `hook_add` however I think is generic enough to implement all of these. I'm not convinced we need to add this add the API level unless there is a use-case that the generic version doesn't handle well.
