### ISSUE TITLE
ARM Thumb ite instructions don't work when they get interrupted by an instruction limit

### ISSUE THREAD

**Issue by flowergrass** [unicorn-engine/unicorn#853]
Using the Unicorn instruction limit feature will give invalid emulation of ARM Thumb code when interrupting **ite** instructions (and other variants, it, itte, ittee etc).

In this example only the movne effects the register when running the entire sample code (of 4 instructions), which is the expected result. When stepping through instructions however, the moveq is executed regardless of the **ite** instruction and r2 is overwritten.

```C
#include <stdio.h>
#include <string.h>
#include <unicorn/unicorn.h>

#define CODE "\x9a\x42\x14\xbf\x68\x22\x4d\x22"
#define ADDRESS 0x10000

void run_test(bool stepping) {
    uc_engine *uc;
    uc_err err;

    int sp = 0x1234;
    int r2 = 0, r3 = 1;

    err = uc_open(UC_ARCH_ARM, UC_MODE_THUMB, &uc);
    if (err) {
        printf("Failed on uc_open() with error returned: %u (%s)\n",
                err, uc_strerror(err));
        return;
    }

    uc_mem_map(uc, ADDRESS, 2 * 1024 * 1024, UC_PROT_ALL);

    uc_mem_write(uc, ADDRESS, CODE, sizeof(CODE) - 1);

    uc_reg_write(uc, UC_ARM_REG_SP, &sp);

    uc_reg_write(uc, UC_ARM_REG_R2, &r2);
    uc_reg_write(uc, UC_ARM_REG_R3, &r3);

    if (!stepping) {
        printf("Running entire binary.\n");
        err = uc_emu_start(uc, ADDRESS | 1, ADDRESS + sizeof(CODE) - 1, 0, 0);
        if (err) {
            printf("Failed on uc_emu_start() with error returned: %u\n", err);
        }
    } else {
        int i, addr = ADDRESS;
        printf("Running binary one instruction at a time.\n");
        for (i = 0; i < sizeof(CODE) / 2; i++) {
            err = uc_emu_start(uc, addr | 1, ADDRESS + sizeof(CODE) - 1, 0, 1);
            if (err) {
                printf("Failed on uc_emu_start() with error returned: %u\n", err);
            }
            uc_reg_read(uc, UC_ARM_REG_PC, &addr);
        }
    }

    uc_reg_read(uc, UC_ARM_REG_R2, &r2);
    uc_reg_read(uc, UC_ARM_REG_R3, &r3);

    printf("R2: %d\n", r2);
    printf("R3: %d\n\n", r3);

    uc_close(uc);
}

int main(){
    printf("Executing\ncmp    r2, r3\nite    ne\nmovne  r2, #104\nmoveq  r2, #77\n\n");
    run_test(false);
    run_test(true);
}
```

**Comment by dpgeorge** [comment]
This is a pretty general issue that means that ARM Thumb2 code can't be reliable executed using the instruction limit feature, because it may be that emu_stop() is executed in the middle of an ite instrution and breaks the emulation.

Would any one of the core developers be able to look into this, or should we try to make a PR with a fix?

**Comment by aquynh** [comment]
yes please send in PR if you can.

**Comment by aquynh** [comment]
this should be fixed now, thanks.

**Comment by vforkliu** [comment]
the fix cause "IT AL" not working
sample code
```c++
/* Unicorn Emulator Engine */
/* By Nguyen Anh Quynh, 2015 */

/* Sample code to demonstrate how to emulate ARM code */

#include <unicorn/unicorn.h>
#include <string.h>


// code to be emulated
#define THUMB_CODE "\x10\xb5\x4f\xf6\x00\x74\xe8\xbf\x10\xbd"

// memory address where emulation starts

int STACK_MEMORY_BASE = 0x00000000;
int STACK_MEMORY_SIZE = 0x00800000;

int HOOK_MEMORY_BASE = 0x1000000;
int HOOK_MEMORY_SIZE = 0x0800000;



static void hook_code(uc_engine *uc, uint64_t address, uint32_t size, void *user_data)
{
    unsigned char bytes[8];
    char instruction[32] = {0};
    int i = 0;
    uc_mem_read(uc,address,bytes,size);
    for(i = 0; i < size; i++){
      sprintf(instruction + i * 3,"%02x ", bytes[i]);
    }
    printf(">>> Tracing instruction at 0x%"PRIx64 ", instruction size = 0x%x, instruction = %s\n", address, size, instruction);
    
    
}

unsigned char bytes[32];
char instruction[64] = {0};
static void test_thumb(void)
{
    uc_engine *uc;
    uc_err err;
    uc_hook trace2;

    int sp = 1024;     // R0 register
    int code_length;

    printf("Emulate THUMB code\n");

    // Initialize emulator in ARM mode
    err = uc_open(UC_ARCH_ARM, UC_MODE_THUMB, &uc);
    if (err) {
        printf("Failed on uc_open() with error returned: %u (%s)\n",
                err, uc_strerror(err));
        return;
    }

    // map 2MB memory for this emulation
    uc_mem_map(uc, HOOK_MEMORY_BASE, HOOK_MEMORY_SIZE, UC_PROT_ALL);
    uc_mem_map(uc, STACK_MEMORY_BASE, STACK_MEMORY_SIZE, UC_PROT_ALL);

    // write machine code to be emulated to memory
    code_length = sizeof(THUMB_CODE) - 1;
    
    uc_mem_write(uc, HOOK_MEMORY_BASE, THUMB_CODE, code_length);
    

    // initialize machine registers
    int lr = HOOK_MEMORY_BASE + 0x80;
    sp = STACK_MEMORY_BASE + STACK_MEMORY_SIZE;
    uc_reg_write(uc, UC_ARM_REG_SP, &sp);
    printf(">>> SP = 0x%x\n", sp);
    uc_reg_write(uc, UC_ARM_REG_LR, &lr);

    // tracing all basic blocks with customized callback
    //uc_hook_add(uc, &trace1, UC_HOOK_BLOCK, hook_block, NULL, 1, 0);

    // tracing one instruction at ADDRESS with customized callback
    uc_hook_add(uc, &trace2, UC_HOOK_CODE, hook_code, NULL, HOOK_MEMORY_BASE, HOOK_MEMORY_BASE + HOOK_MEMORY_SIZE);

    // emulate machine code in infinite time (last param = 0), or when
    // finishing all the code.
    // Note we start at ADDRESS | 1 to indicate THUMB mode.
    err = uc_emu_start(uc, (HOOK_MEMORY_BASE) | 1, lr, 0, 0);
    if (err) {
        printf("Failed on uc_emu_start() with error returned: %u\n", err);
    }

    // now print out some registers
    printf(">>> Emulation done. Below is the CPU context\n");

    uc_reg_read(uc, UC_ARM_REG_SP, &sp);
    printf(">>> SP = 0x%x\n", sp);

    uc_close(uc);
}

int main(int argc, char **argv, char **envp)
{
    // dynamically load shared library
#ifdef DYNLOAD
    if (!uc_dyn_load(NULL, 0)) {
        printf("Error dynamically loading shared library.\n");
        printf("Please check that unicorn.dll/unicorn.so is available as well as\n");
        printf("any other dependent dll/so files.\n");
        printf("The easiest way is to place them in the same directory as this app.\n");
        return 1;
    }
#endif
    
    // test_arm();
    printf("==========================\n");
    test_thumb();

    // dynamically free shared library
#ifdef DYNLOAD
    uc_dyn_free();
#endif
    
    return 0;
}
```

unicorn 1.0.2 output
```shell
==========================
Emulate THUMB code
>>> SP = 0x800000
>>> Tracing instruction at 0x1000000, instruction size = 0x2, instruction = 10 b5
>>> Tracing instruction at 0x1000002, instruction size = 0x4, instruction = 4f f6 00 74
>>> Tracing instruction at 0x1000006, instruction size = 0x2, instruction = e8 bf
>>> Tracing instruction at 0x1000008, instruction size = 0x2, instruction = 10 bd
>>> Emulation done. Below is the CPU context
>>> SP = 0x800000
```
unicorn 1.0.3 output
```shell
==========================
Emulate THUMB code
>>> SP = 0x800000
thumb insn: 0xb510
thumb insn: 0xb510 gen_uc_tracecode
thumb2:insn: 0xf64f
thumb insn: 0xbfe8
>>> Tracing instruction at 0x1000000, instruction size = 0x2, instruction = 10 b5
>>> Tracing instruction at 0x1000002, instruction size = 0x4, instruction = 4f f6 00 74
>>> Emulation done. Below is the CPU context
>>> SP = 0x800000
```

**Comment by wtdcode** [comment]
> the fix cause "IT AL" not working
> sample code
> 
> ```c++
> /* Unicorn Emulator Engine */
> /* By Nguyen Anh Quynh, 2015 */
> 
> /* Sample code to demonstrate how to emulate ARM code */
> 
> #include <unicorn/unicorn.h>
> #include <string.h>
> 
> 
> // code to be emulated
> #define THUMB_CODE "\x10\xb5\x4f\xf6\x00\x74\xe8\xbf\x10\xbd"
> 
> // memory address where emulation starts
> 
> int STACK_MEMORY_BASE = 0x00000000;
> int STACK_MEMORY_SIZE = 0x00800000;
> 
> int HOOK_MEMORY_BASE = 0x1000000;
> int HOOK_MEMORY_SIZE = 0x0800000;
> 
> 
> 
> static void hook_code(uc_engine *uc, uint64_t address, uint32_t size, void *user_data)
> {
>     unsigned char bytes[8];
>     char instruction[32] = {0};
>     int i = 0;
>     uc_mem_read(uc,address,bytes,size);
>     for(i = 0; i < size; i++){
>       sprintf(instruction + i * 3,"%02x ", bytes[i]);
>     }
>     printf(">>> Tracing instruction at 0x%"PRIx64 ", instruction size = 0x%x, instruction = %s\n", address, size, instruction);
>     
>     
> }
> 
> unsigned char bytes[32];
> char instruction[64] = {0};
> static void test_thumb(void)
> {
>     uc_engine *uc;
>     uc_err err;
>     uc_hook trace2;
> 
>     int sp = 1024;     // R0 register
>     int code_length;
> 
>     printf("Emulate THUMB code\n");
> 
>     // Initialize emulator in ARM mode
>     err = uc_open(UC_ARCH_ARM, UC_MODE_THUMB, &uc);
>     if (err) {
>         printf("Failed on uc_open() with error returned: %u (%s)\n",
>                 err, uc_strerror(err));
>         return;
>     }
> 
>     // map 2MB memory for this emulation
>     uc_mem_map(uc, HOOK_MEMORY_BASE, HOOK_MEMORY_SIZE, UC_PROT_ALL);
>     uc_mem_map(uc, STACK_MEMORY_BASE, STACK_MEMORY_SIZE, UC_PROT_ALL);
> 
>     // write machine code to be emulated to memory
>     code_length = sizeof(THUMB_CODE) - 1;
>     
>     uc_mem_write(uc, HOOK_MEMORY_BASE, THUMB_CODE, code_length);
>     
> 
>     // initialize machine registers
>     int lr = HOOK_MEMORY_BASE + 0x80;
>     sp = STACK_MEMORY_BASE + STACK_MEMORY_SIZE;
>     uc_reg_write(uc, UC_ARM_REG_SP, &sp);
>     printf(">>> SP = 0x%x\n", sp);
>     uc_reg_write(uc, UC_ARM_REG_LR, &lr);
> 
>     // tracing all basic blocks with customized callback
>     //uc_hook_add(uc, &trace1, UC_HOOK_BLOCK, hook_block, NULL, 1, 0);
> 
>     // tracing one instruction at ADDRESS with customized callback
>     uc_hook_add(uc, &trace2, UC_HOOK_CODE, hook_code, NULL, HOOK_MEMORY_BASE, HOOK_MEMORY_BASE + HOOK_MEMORY_SIZE);
> 
>     // emulate machine code in infinite time (last param = 0), or when
>     // finishing all the code.
>     // Note we start at ADDRESS | 1 to indicate THUMB mode.
>     err = uc_emu_start(uc, (HOOK_MEMORY_BASE) | 1, lr, 0, 0);
>     if (err) {
>         printf("Failed on uc_emu_start() with error returned: %u\n", err);
>     }
> 
>     // now print out some registers
>     printf(">>> Emulation done. Below is the CPU context\n");
> 
>     uc_reg_read(uc, UC_ARM_REG_SP, &sp);
>     printf(">>> SP = 0x%x\n", sp);
> 
>     uc_close(uc);
> }
> 
> int main(int argc, char **argv, char **envp)
> {
>     // dynamically load shared library
> #ifdef DYNLOAD
>     if (!uc_dyn_load(NULL, 0)) {
>         printf("Error dynamically loading shared library.\n");
>         printf("Please check that unicorn.dll/unicorn.so is available as well as\n");
>         printf("any other dependent dll/so files.\n");
>         printf("The easiest way is to place them in the same directory as this app.\n");
>         return 1;
>     }
> #endif
>     
>     // test_arm();
>     printf("==========================\n");
>     test_thumb();
> 
>     // dynamically free shared library
> #ifdef DYNLOAD
>     uc_dyn_free();
> #endif
>     
>     return 0;
> }
> ```
> 
> unicorn 1.0.2 output
> 
> ```shell
> ==========================
> Emulate THUMB code
> >>> SP = 0x800000
> >>> Tracing instruction at 0x1000000, instruction size = 0x2, instruction = 10 b5
> >>> Tracing instruction at 0x1000002, instruction size = 0x4, instruction = 4f f6 00 74
> >>> Tracing instruction at 0x1000006, instruction size = 0x2, instruction = e8 bf
> >>> Tracing instruction at 0x1000008, instruction size = 0x2, instruction = 10 bd
> >>> Emulation done. Below is the CPU context
> >>> SP = 0x800000
> ```
> 
> unicorn 1.0.3 output
> 
> ```shell
> ==========================
> Emulate THUMB code
> >>> SP = 0x800000
> thumb insn: 0xb510
> thumb insn: 0xb510 gen_uc_tracecode
> thumb2:insn: 0xf64f
> thumb insn: 0xbfe8
> >>> Tracing instruction at 0x1000000, instruction size = 0x2, instruction = 10 b5
> >>> Tracing instruction at 0x1000002, instruction size = 0x4, instruction = 4f f6 00 74
> >>> Emulation done. Below is the CPU context
> >>> SP = 0x800000
> ```

Glad to see your feedback. Could you fire an separate issue to track it?
