### ISSUE TITLE
siglongjmp() crashes on Windows x86-64

### ISSUE THREAD

**Issue by Helios-vmg** [unicorn-engine/unicorn#857]
The siglongjmp() call in cpu_loop_exit() crashes on Windows x86-64. To reproduce, simply build and run sample_x86. I tested on MSVC 2015; I don't know if the same happens on other compilers.

**Comment by aquynh** [comment]
Is this the latest code from Github?

**Comment by Helios-vmg** [comment]
Yes, da21bd0589a1018f5c84bb3a3752d8add1b43ec0.

**Comment by gibbed** [comment]
Still happening as of bc34c36, however, I have noted that it's only happening in the Debug build. The problem does not occur in a Release build.

**Comment by goodguysoft** [comment]
I have the same issue. Are there any hope to fix it? Visual Studio version is 2017.

**Comment by NickTsl** [comment]
Hi i've been having the same exact issue, with the latest version of unicorn on visual studio 2019

**Comment by gibbed** [comment]
Since the issue was closed, was this fixed?

**Comment by wtdcode** [comment]
@gibbed This issue is fixed long ago in uc1.

**Comment by gibbed** [comment]
Great! I haven't been keeping up with Unicorn fixes and was waiting on updates to the issue to be notified.

**Comment by wtdcode** [comment]
@gibbed See https://github.com/unicorn-engine/unicorn/pull/1331
@NickTsl Sorry I just found your comment. You are still experiencing the crash?
