### ISSUE TITLE
Hippocamp/Unicorn Breeding Glitch

### ISSUE THREAD

**Issue by afghan2007** [unicorn-engine/unicorn#861]
When I am breeding two hippocampus/unicorn hybrids to geth a better gene selection hybrid, everytime I produce an offspring that has a HH for horns, the colt always come out as a pure blooded unicorn with no hippopcampus traits.  I breed two hybrids, both have the following genes: FF, GG, uu, AA, 0H, and every time I manage to get the HH, I end ups with the colt having a gene pool of: uu, AA, HH.  Can this bug be fixed please.

Mod: ultimate_unicorn_mod-1.10.2-1.5.11
Forge: 1.10.2-12.18.3.2316
Minecraft: 10.2

**Comment by aquynh** [comment]
this is definitely one of the best issues i have even seen here :-)

if you have a fix, do send in pull req!

**Comment by noxarivis** [comment]
is it a joke or meant serious?

**Comment by aquynh** [comment]
that is the best joke ever ;-)

**Comment by noxarivis** [comment]
im not sure that this is a joke

**Comment by rhelmot** [comment]
@noxarivis you have the wrong repository. This repository is for unicorn-engine, a cpu emulator that has nothing to do with minecraft.

**Comment by noxarivis** [comment]
@rhelmot

no shit Sherlock ?

how about telling that the 12 year old who opened the damn issue and not me.

**Comment by rhelmot** [comment]
oh god dammit I'm sorry, that was a brainfart. I meant to tag @afghan2007 

I am trying my best :(
