### ISSUE TITLE
uc_mem_unmap not returning expected error code

### ISSUE THREAD

**Issue by FICTURE7** [unicorn-engine/unicorn#863]
According to the documentation in [unicorn.h](https://github.com/unicorn-engine/unicorn/blob/master/include/unicorn/unicorn.h#L621-L622) uc_mem_unmap should return UC_ERR_ARG when the specified size is not a multiple of 4KB, however it returns [UC_ERR_MAP](https://github.com/unicorn-engine/unicorn/blob/master/uc.c#L955-L956).

**Comment by aquynh** [comment]
can you provide a pull req to fix this?

**Comment by FICTURE7** [comment]
yeah ^^
