### ISSUE TITLE
Emulating an ARM binary

### ISSUE THREAD

**Issue by r00tus3r** [unicorn-engine/unicorn#868]
I am new to Unicorn. In the examples I could see only one line code being emulated. 
I want to emulate an ARM executable file. How to do this using unicorn framework?
I've parsed the file and memory mapped the program headers. What should I do next?

**Comment by aquynh** [comment]
https://github.com/lunixbochs/usercorn is doing this (and more than that).

also see many sample projects at http://www.unicorn-engine.org/showcase/

**Comment by r00tus3r** [comment]
Those are some cool projects.
But can you give me some steps or guidelines that a beginner can follow and understand.
