### ISSUE TITLE
Analyzing an ELF memory image with Unicorn

### ISSUE THREAD

**Issue by Arnab035** [unicorn-engine/unicorn#871]
Hello,

This is not an issue per se. 
I am using Ubuntu 4.11.3 on a x86-64 machine.
I am planning to use Unicorn to run an ELF memory dump of a Virtual Machine. To obtain the memory dump, I first run an application on the VM, then immediately I pause the VM. From the host, I will then run a command to get the memory image of the VM. This would practically mean the VM memory has the application code and data placed in the memory.
The memory image is in an ELF format. I load the ELF image into memory, using `mmap`. The ELF image gets loaded into the memory at an address starting with **0x7f..** something like **0x7fb3ea488000**.
This would mean that the whole VMs memory image is placed in that address. I wanted to see if Unicorn would start emulating the entire memory image starting from that address(using mem_map).

I have specified a 4 GB emulation buffer, this is because the ELF loads a 4 GB image into memory.
The emulation keeps failing every time.

Below is the emulator startup code I have written 

```
#include <unicorn/unicorn.h>
#include <unistd.h>
#include <inttypes.h>
#include <string.h>


#define GIGA (1024UL*1024*1024)
#define RAM_SIZE (4*GIGA)
#define ADDRESS 0x7f4ad56c4000

static void test_x86_64(void)
{
    uc_engine *uc;
    uc_err err;
    //uc_hook trace1, trace2, trace3, trace4;

    int64_t rax = 0x7fc21aac6598 ;
    int64_t rbx = 0x7ffe23c88540;
    int64_t rcx = 0x1000;
    int64_t rdx = 0xc457004ad701;
    int64_t rsi = 0x1008;
    int64_t rdi = 0x7fc21b202018;
    int64_t r8 = 0x4;
    int64_t r9 = 0x7fc21aa02010;
    int64_t r10 = 0x14d;
    int64_t r11 = 0x207;
    int64_t r12 = 0x3;
    int64_t r13 = 0xc;
    int64_t r14 = 0x9;
    int64_t r15 = 0x4;
    //int64_t rip = 0x401838;
    int64_t rsp = 0x7ffe23c88340;
    int64_t rbp = 0x2;
    int64_t reflags = 0x202;
    int64_t rcs = 0x33;
    int64_t rss = 0x2b;
    int64_t rds = 0x0;
    int64_t res = 0x0;
    int64_t rfs = 0x0;
    int64_t rgs = 0x0;
    
    printf("Emulate x86_64 code\n");

    // Initialize emulator in X86-64bit mode
    err = uc_open(UC_ARCH_X86, UC_MODE_64, &uc);
    if (err) {
        printf("Failed on uc_open() with error returned: %u\n", err);
        return;
    }

    // map 2MB memory for this emulation  ---------    4 GB for this emulation
    uc_mem_map(uc, ADDRESS, RAM_SIZE, UC_PROT_ALL);

    err = uc_emu_start(uc, ADDRESS, RAM_SIZE, 0, 0);
    if (err) {
        printf("Failed on uc_emu_start() with error returned %u: %s\n",
                err, uc_strerror(err));
    }

    // now print out some registers
    printf(">>> Emulation done. Below is the CPU context\n");
```

I keep getting the below error--- 

**Failed on uc_emu_start() with error returned 6: Invalid memory read (UC_ERR_READ_UNMAPPED)**

 The error message makes it quite clear, but I find that the `uc_mem_map` function has completed successfully. The memory allocation functions inside the qemu source code seem to complete successfully 

Can anybody guide me on how to solve this problem ? I am finding it difficult to identify the root of this issue.

Thanks a lot!

**Comment by lunixbochs** [comment]
You should add both a code hook and a memory fault hook. The code hook should use capstone to print the disassembly of each executed instruction. The memory fault (error) hook should print the faulting address. Post that output and we can better help.

My guess is you're not setting up segment registers correctly. This sort of thing might be easier for you to build on top of usercorn.
