### ISSUE TITLE
Instruction pointer being reset on exceptions

### ISSUE THREAD

**Issue by rhelmot** [unicorn-engine/unicorn#872]
https://github.com/unicorn-engine/unicorn/blob/513075e061e6642af696380f189d17a84b95241e/qemu/cpu-exec.c#L147

In our interrupt callback, we call uc_stop and roll the registers back to the start of the previous block, so that angr can take over execution to handle the runup to the exception natively. However, the instruction pointer is clobbered by this line. I tried moving the register rollback to after uc_start returns, but that caused additional issues. It would be one thing if it were being set to a meaningful address, but in my case, `exception_next_eip` seems to be zero.

What is the purpose of this line? Do we actually want to be clobbering the instruction pointer in the case that the interrupt was handled by a user's callback? How can I accomplish what I want to accomplish?

**Comment by aquynh** [comment]
i remember this was to set the EIP to the next instruction, after INT, when you handle INT instruction with your handler.

**Comment by rhelmot** [comment]
This sounds like a great feature for handling INT instructions, but when handling exceptions generated by unrelated code, e.g. a divide-by-zero exception, exception_next_eip is zero. Can we just put that line in a condition that it was set by an int instruction?
