### ISSUE TITLE
Impossible to get accurate BB size from HOOK_BLOCK for large blocks

### ISSUE THREAD

**Issue by bennofs** [unicorn-engine/unicorn#874]
Unicorn / Qemu has a max basic block size. If a BB is bigger than that, BLOCK will receive `0` as the size argument *and* not be called again for the remaining parts of that BB.

This is really annoying for two reasons:

* you cannot, possibly, get the correct size of the whole BB (since you won't even be called for follow-up parts)
* you have to special-case `size == 0` for the first part to at least get the size of the first part correct. 

Why is this check there? Just calling `HOOK_BLOCK` for every part, with the correct size & address of the part would make everything easier *and* requires less code / special cases.

**Comment by pgarba** [comment]
Just ran into this problem. 
We be great if there would be an fix for it
