### ISSUE TITLE
reg_write(X86_*S) should not longjmp

### ISSUE THREAD

**Issue by lunixbochs** [unicorn-engine/unicorn#881]
The seg_helper functions borrowed from qemu-user do the wrong thing in unicorn - they can trigger a fault / interrupt on error, which iirc will even segfault if unicorn wasn't inside a uc_emu_start() call. They should be modified to return an error on invalid segment write, instead of doing a longjmp.

**Comment by sneakin** [comment]
Sure does. I can't initialize any segment registers without segfaulting.

**Comment by lunixbochs** [comment]
Usercorn works now btw. https://github.com/lunixbochs/usercorn/blob/master/go/arch/x86/linux.go
I call `setupGdt` before the target is started.
