### ISSUE TITLE
invalid memory write error on vmulpd instruction

### ISSUE THREAD

**Issue by mcgrady1** [unicorn-engine/unicorn#883]
Hi, everyone
    we tried to use unicorn to test "vmulpd xmm1, xmm2, xmm3" instruction, but we got a error as follow:
    >>> Missing memory is being Read at 0x0, data size = 4
    >>> Memory is being READ at 0x4, data size = 4, data value = 0x0
    ERROR: Invalid memory read (UC_ERR_READ_UNMAPPED) 

    this instruction doesn't access memory, why we got this error?someone can help me?
    we tested this instruction in gdb, we only set value of xmm registers and it worked well.
    So i think it is a bug of unicorn-engine.

Thanks.

**Comment by aquynh** [comment]
You should post your code, otherwise it is hard to tell what is wrong.

**Comment by mcgrady1** [comment]
it is easy to reproduce, just set code = b"\xc5\xe9\x59\xcb",
and set xmm1, xmm2, xmm3 register before you run the code,
then you will see the error.

**Comment by aquynh** [comment]
Can you post your code here?

**Comment by mcgrady1** [comment]
install capstone and keystone first
[test.py.zip](https://github.com/unicorn-engine/unicorn/files/1284703/test.py.zip)

**Comment by mcgrady1** [comment]
[test.py.zip](https://github.com/unicorn-engine/unicorn/files/1284711/test.py.zip)
install capstone and keystone first

**Comment by aquynh** [comment]
the reason is because this AVX (VEX2) instruction is wrongly emulated.

do you know any such instructions that work properly?

**Comment by mcgrady1** [comment]
So it is a bug of qemu?

**Comment by aquynh** [comment]
yes, that is Qemu bug. not sure if latest Qemu v2.10 fixed this. let me
know if you find out. i am travelling, and have no time to look at that yet
-- 
Thanks,
Quynh

http://www.keystone-engine.org
http://www.capstone-engine.org
http://www.unicorn-engine.org
