### ISSUE TITLE
How to hook calls?

### ISSUE THREAD

**Issue by P4nda0s** [unicorn-engine/unicorn#885]
I am new to unicorn , I want to use unicorn to execute arm on x86.
I don't know how to set up a callback on api calls
For eample:
blx r8

Thanks~

**Comment by TehRick** [comment]
Hi Chenyuxin,

What you are looking for is a combination of unicorn code hook and capstone disassembler.
As a starting point, don't miss the unicorn tutorial and the arm sample:
https://github.com/unicorn-engine/unicorn/blob/master/samples/sample_arm.c#L111
Then something like this should work (it's python, but the api is quite the same in C++):
```
def hook_code(uc, address, size, user_data):
    # the '8' here is a guess, replace with arm maximum length for opcode+operands
    instr_bytes = uc.mem_read(address, 8) 
    # choose the right arch and mode
    md = capstone.Cs(capstone.CS_ARCH_ARM, capstone.CS_MODE_BIG_ENDIAN)
    instr = next(md.disasm(instr_bytes))
    # now you can access the mnemonic ! just filter blx, look at operands etc...
    print("0x%x:\t%s\t%s" % (instr.address, instr.mnemonic, instr.op_str))
```
For the capstone part, you can read this: http://www.capstone-engine.org/documentation.html
