### ISSUE TITLE
Ruby bindings: add support for reading and writing FPU stack registers

### ISSUE THREAD

**Issue by fallenoak** [unicorn-engine/unicorn#891]
With the current Ruby bindings, calling `#reg_read(Unicorn::UC_Unicorn::UC_X86_REG_FP0)` (and the rest of the FPU stack registers) causes a crash. I'm assuming this happens because the 80-bit floats present in the registers are larger than the type used to read the register value.

See: https://github.com/unicorn-engine/unicorn/blob/master/bindings/ruby/unicorn_gem/ext/unicorn.c#L173

Similarly, I'm assuming writing proper values to the FPU stack registers is not possible via `#reg_write` since it makes similar assumptions about sizes. It doesn't crash, but it's effectively capped at writing the `sigificand` + 1 bit.

See: https://github.com/unicorn-engine/unicorn/blob/master/bindings/ruby/unicorn_gem/ext/unicorn.c#L225

Reads could be handled with a `float80` struct, converted to a Ruby array.

For ex:

```c
typedef struct uc_x86_float80 {
    uint64_t significand   : 63;
    uint64_t normalized    : 1;
    uint16_t exponent      : 15;
    uint16_t sign          : 1;
} uc_x86_float80;
```

```c
VALUE fp_ary;
uc_x86_float80 f80;

case UC_X86_REG_FP0:
case UC_X86_REG_FP1:
case UC_X86_REG_FP2:
case UC_X86_REG_FP3:
case UC_X86_REG_FP4:
case UC_X86_REG_FP5:
case UC_X86_REG_FP6:
case UC_X86_REG_FP7:
    f80.significand = 0;
    f80.normalized = 0;
    f80.exponent = 0;
    f80.sign = 0;

    err = uc_reg_read(_uc, tmp_reg, &f80);

    if (err != UC_ERR_OK) {
        rb_raise(UcError, "%s", uc_strerror(err));
    }

    fp_ary = rb_ary_new();
    rb_ary_store(fp_ary, 0, ULL2NUM(f80.significand));
    rb_ary_store(fp_ary, 1, UINT2NUM(f80.normalized));
    rb_ary_store(fp_ary, 2, UINT2NUM(f80.exponent));
    rb_ary_store(fp_ary, 3, UINT2NUM(f80.sign));
    return fp_ary;
```

Writes could presumably be handled using the reverse.

**Comment by aquynh** [comment]
yes, Python binding already supported these, but other bindings are still behind. would you mind sending a pull req for Ruby?

**Comment by fallenoak** [comment]
@aquynh Talk about a fast reply! Thanks!

Just a few questions prior to opening a PR:

* Do we have preferences about where a `uc_x86_float80` typedef belongs? Should it be in Ruby's `unicorn.h`, or would it be useful to define it more generally?

* Should we keep the type simpler and just break it into `sigificand` and `exponent`? It's fairly trivial to shift to get the `normalized` and `sign` values back out. (I believe this is how you set this up for the Python bindings).

**Comment by aquynh** [comment]
i will leave the answer to @sashs, the maintainer & author of the Ruby binding.

**Comment by fallenoak** [comment]
@aquynh Sounds good. I'll open a PR as soon as @sashs has a chance to weigh in.

**Comment by fallenoak** [comment]
Just opened a PR. Hopefully @sashs will have some time to lend to a review in the future.
