### ISSUE TITLE
About ios simulator version

### ISSUE THREAD

**Issue by wellcomez** [unicorn-engine/unicorn#896]
I've compiled it as ios simulator version.  After many additional things have been done, I can make real ios application run inside of simulator. I'm glad to submit my modification,  but there is an issue, the static library  built by me  can't  be debugged although I have change everyplace I think i need to create a debug build.

**Comment by wellcomez** [comment]
@aquynh  while I change compile options to

# UNICORN_DEBUG ?= yes
# ifeq ($(UNICORN_DEBUG),yes)
CFLAGS += -g -O0 
# else
# CFLAGS += -O3

It is still hard to  debug with  xcode or lldb.   I don't know its your build script's problem or  from xcode toolchain.  
Do you have any suggestion or share some typical debug skill with me?
 
Anyway so thank for latest version, compared with previous version it is much easier for  integration.

**Comment by aquynh** [comment]
What do you mean by "hard to debug"?

The most simple, but very effective way is to insert "printf" to dump runtime info, so you can observe execution. I still use this all the time :-)

**Comment by wellcomez** [comment]
@aquynh  It is hard to set breakpoint.  According to my previous experience, sometime program can be stop at the breakpoint which I suppose to be, but sometimes not.
