### ISSUE TITLE
dependent package bug

### ISSUE THREAD

**Issue by stephengroat** [unicorn-engine/unicorn#902]
msys build currently failing

track

https://github.com/Alexpux/MSYS2-packages/issues/1014

**Comment by stephengroat** [comment]
@aquynh could you try clearing the appveyor cache using (https://www.appveyor.com/docs/build-cache/#rest-api)?

**Comment by aquynh** [comment]
is this something like this (with curl, and APPVEYOR_TOKEN exported)?

```
$ curl -H "Authorization: Bearer $APPVEYOR_TOKEN" -H DELETE https://ci.appveyor.com/project/aquynh/unicorn/buildcache
```

**Comment by stephengroat** [comment]
the msys issue seems fixed, but the appveyor caches may be too big now

@aquynh want me to disable the appveyor caches for now since the sizes seem to have gotten too big?

**Comment by aquynh** [comment]
what is the problem of a big cache?

if we disable the cache, Appveyor needs to download packages every time, thus slow down the build process?
