### ISSUE TITLE
'uc_context_free' not found - unicorn-1.0.1-python-win32.msi

### ISSUE THREAD

**Issue by trietptm** [unicorn-engine/unicorn#903]
Because API uc_context_free() is renamed to uc_free() , 
uc_context_free() should be renamed to uc_free() in the file Lib\site-packages\unicorn\unicorn.py .

>   File "C:\Python27\lib\site-packages\unicorn\__init__.py", line 4, in <module>
>     from .unicorn import Uc, uc_version, uc_arch_supported, version_bind, debug, UcError, __version__
>   File "C:\Python27\lib\site-packages\unicorn\unicorn.py", line 129, in <module>
>     _setup_prototype(_uc, "uc_context_free", ucerr, uc_context)
>   File "C:\Python27\lib\site-packages\unicorn\unicorn.py", line 102, in _setup_prototype
>     getattr(lib, fname).restype = restype
>   File "C:\Python27\lib\ctypes\__init__.py", line 375, in __getattr__
>     func = self.__getitem__(name)
>   File "C:\Python27\lib\ctypes\__init__.py", line 380, in __getitem__
>     func = self._FuncPtr((name_or_ordinal, self))
> AttributeError: function 'uc_context_free' not found

**Comment by aquynh** [comment]
Would you please send a pull req to fix this?

**Comment by trietptm** [comment]
Oh, I see the Python module for Windows Binaries should be recompiled. It's already fixed at https://github.com/unicorn-engine/unicorn/blob/master/bindings/python/unicorn/unicorn.py .

**Comment by trietptm** [comment]
I uninstalled the old version and reinstall unicorn-1.0.1-python-win32.msi, it's already fixed.
