### ISSUE TITLE
More Pythonic Bindings

### ISSUE THREAD

**Issue by STKFLT** [unicorn-engine/unicorn#909]
Hello all, I recently started a similar project that I have integrated into the bindings directly (https://github.com/Jake-R/unicorn) and I'm looking for some feedback on the interface and/or implementation. the interface is a superset of the old one with the following new features:
```python
from unicorn import arm64
mu = arm64.arm64el_arm()

#mapping memory
mu[ADDRESS] = 2*1024*1024  # I don't really like this, any suggestions? 

#writing to memory:
mu[ADDRESS] = ARM64_CODE

#reading memory:
mem = mu[ADDRESS:ADDRESS+len(ARM64_CODE)]

#reading a register
x11 = mu.reg.x11

#writing a register:
mu.reg.x11 = 0x12345678

#hooking
@Hook.block
def hook_block(uc, address, size, user_data):
    print(">>> Tracing basic block at 0x%x, block size = 0x%x" %(address, size))
# or
mu.hook.block(hook_block)
```
The bindings are generated by looking at the values in {}_const modules and inserting them into a jinja2 template. I haven't done a ton of testing for speed but it seems like the performance impact is pretty minimal since there is only the overhead of  `__get__/__set__` and `__getitem__/__setitem__`. Replicating @lunixbochs 's test I got:
```
magic: 4.411244699997042
native: 3.900663774998975

magic: 4.60627108799963
native: 3.8136738930006686

magic: 4.460894711999572
native: 3.8876221419996
```

Are there any other features you would like to see? would you change anything about the implementation?

if you want to try it out I've found that the easiest way to install it is with `sudo -H pip3 install -e 'git+https://github.com/Jake-R/unicorn.git#egg=unicorn&subdirectory=bindings/python'`

**Comment by lunixbochs** [comment]
```
mu[ADDRESS] = 2*1024*1024  # I don't really like this, any suggestions? 
```

yeah:

```
mu.map(addr, 2*1024*1024, prot="rwx")
mu.unmap(addr, 2*1024*1024)
```

**Comment by lunixbochs** [comment]
For `@mu.hook.block`, how do you unhook?

**Comment by Jake-R** [comment]
unhooking is definitely a missing feature. when that's added, unhooking will work the same way for hooks defined with a decorator or a hook function.

Going of off that, the decorator currently adds a hook to every Uc instance spawned in that context. Does this seem like a useful feature? If not, I will move the decorator into the Uc class itself. This would have the affect of forcing the user to define their functions after creating a Uc instance if they want to use the decorator.

**Comment by lunixbochs** [comment]
hooking should really be less rather than more magical I think

**Comment by yhql** [comment]
> mu[ADDRESS] = 2*1024*1024  # I don't really like this, any suggestions? 

Maybe something like this :  
```mu[ADDRESS:2*1024*1024, 'rwx'] = 0```
so that you can easily distinguish mapping and writing. If the argument to __setitem__ is a tuple, then it's a mapping of the area described by the slice in the first element, with the rights given in the second. Then you can write the initial value on the right side of the equality.

For unmapping, I'm not sure... `mu[ADDRESS:SIZE, 'u']` ?
