### ISSUE TITLE
tcg target arm : all args are put on the stack.

### ISSUE THREAD

**Issue by jief666** [unicorn-engine/unicorn#910]
The 19th of january, these lines (in bold) were added to the beginning of tcg_reg_alloc_call :
`  nb_regs = ARRAY_SIZE(tcg_target_call_iarg_regs);`
**`#if TCG_TARGET_REG_BITS == 32`
`	// do this because msvc cannot have arrays with 0 entries.`
`	nb_regs = 0; <----------- that makes all args on the stack.`
`#endif`**
`	if (nb_regs > nb_params) {`
`        nb_regs = nb_params;`
 `   }`
As I read it, it broke all 32 bits arm host. At least it broke mine. It don't really get the comment meaning, but it suggest it should be enclosed by #ifdef _MSC_VER or equivalent.
It's not in last version in qemu repo.

**Comment by aquynh** [comment]
Can you send a pull request?

**Comment by jief666** [comment]
Yes.
I'll do that very soon.

**Comment by jief666** [comment]
I had created a pull request #912, but it wasn't complete. I think it is now. Would you consider it ?
