### ISSUE TITLE
The X86 instructions "0x34, 0xA2, 0x0F, 0x42, 0x02" will cause a crash(tcg_abort).

### ISSUE THREAD

**Issue by legendwind** [unicorn-engine/unicorn#916]
run the funciton below with static lib of unicorn in a wow64 process(win32 program combined by vs2015) in win10(X64), it will led a crash(tcg_abort):

#define ADDRESS 0x1000000
static void test_i386(void)
{
    uc_engine *uc;
    unsigned char testcode[] = {
		0x34, 0xA2, 0x0F, 0x42, 0x02
	};
    int r_esp = ADDRESS + 0x200000;
    uc_open(UC_ARCH_X86, UC_MODE_32, &uc);
    uc_mem_map(uc, ADDRESS, 4 * 1024 * 1024, UC_PROT_ALL);
    uc_mem_write(uc, ADDRESS, testcode, sizeof(testcode) - 1);
    uc_reg_write(uc, UC_X86_REG_ESP, &r_esp);
    uc_emu_start(uc, ADDRESS, ADDRESS + sizeof(testcode) - 1, 0, 0);
    uc_close(uc);
}

**Comment by wonderzdh** [comment]
779E000D | 34 A2                    | xor al,A2                               |
779E000F | 0F 42 02                 | cmovb eax,dword ptr ds:[edx]            |

Obvious edx can not read.
But this should be a emulate error and will not result in it abort.

**Comment by legendwind** [comment]
as you see,the edx is not inited,but it will not make a abort, I tested the code, the bug is only exist in the 32 bit static lib of unicorn (combined by vs2015) in windows。 the code runs fine in linux。

**Comment by mrexodia** [comment]
Today I encountered a crash similar to this. In my case it crashes on 32 bit debug, but on 64 bit everything is working fine.

Sample:

```python
#!/usr/bin/python

from __future__ import print_function
from unicorn import *
from unicorn.x86_const import *

# code to be emulated:
'''
000000014DC50D26 | 310424      | xor dword ptr ss:[rsp],eax
000000014DC50D29 | 44:0F42E8   | cmovb r13d,eax

'''
X86_CODE64 = b"\x31\x04\x24"+"\x44\x0F\x42\xE8"

# memory address where emulation starts
ADDRESS = 0x1000000

print("Emulate amd64 code")
try:
    # Initialize emulator in X86-64bit mode
    mu = Uc(UC_ARCH_X86, UC_MODE_64)

    # map 2MB memory for this emulation
    mu.mem_map(ADDRESS, 2 * 1024 * 1024)

    # write machine code to be emulated to memory
    mu.mem_write(ADDRESS, X86_CODE64)

    # initialize machine registers
    mu.reg_write(UC_X86_REG_RAX, 1337)

    # emulate code in infinite time & unlimited instructions
    mu.emu_start(ADDRESS, ADDRESS + len(X86_CODE64))

    # now print out some registers
    print("Emulation done. Below is the CPU context")

    r_rax = mu.reg_read(UC_X86_REG_RAX)
    print(">>> RAX = 0x%x" %r_rax)

except UcError as e:
    print("ERROR: %s" % e)
```

**Comment by wonderzdh** [comment]
> 今天我遇到了类似的崩溃。在我的情况下，它在32位调试时崩溃，但在64位上一切正常。
> 
> 样品：
> 
> ```python
> ＃！的/ usr / bin中/蟒蛇
> 
> 从 __future__  进口 print_function
> 从麒麟进口 * 
> 从 unicorn.x86_const进口 * 
> 
> ＃代码来进行仿真
> ：''”
>  000000014DC50D26 | 310424 | xor dword ptr ss：[rsp]，eax 
> 000000014DC50D29 | 44：0F42E8 | cmovb r13d，eax
> 
> ''”
>  X86_CODE64  =  b “ \ X31 \ X04 \ X24 ” + “ \ X44 \ X0F \ X42 \ xE8 ” 
> 
> ＃存储器地址，其中仿真开始
> ADDRESS  =  0X百万
> 
> 打印（ “效法AMD64代码”）
> 尝试：
>     ＃在X86初始化仿真器-64bit模式 
>     亩 = UC（ UC_ARCH_X86， UC_MODE_64）＃地图2MB记忆此仿真 
>     mu.mem_map（ ADDRESS， 2 * 1024 * 1024
> 
>         ）＃写入机器代码要被模仿到存储器 
>     mu.mem_write（ADDRESS，X86_CODE64）＃初始化机器寄存器 
>     mu.reg_write（UC_X86_REG_RAX，1337）＃无限时间＆无限的指令仿真代码 
>     mu.emu_start（ADDRESS，ADDRESS + LEN（X86_CODE64））＃ now打印出一些寄存器print（“ Emulation done。下面是CPU上下文”）
>     r_rax = mu.reg_read（
> 
>     
> 
>     
> 
>       
> 
>     
>     
> UC_X86_REG_RAX）
>      打印（“ >>> RAX = 0x ％x ” ％ r_rax），除了 UcError 为 e：
>      print（“ ERROR：％s ”％ e）
> 
>  
> ```

you need mu.reg_write UC_X86_REG_RSP first.
