### ISSUE TITLE
x86_64 vxorps is not correctly handled

### ISSUE THREAD

**Issue by gibbed** [unicorn-engine/unicorn#917]
instruction: `vxorps xmm0, xmm0, xmm0`
bytes: `C5 F8 57 C0`

Currently, it handles `vxorps` and passes off execution into `push rdi`, which is wrong, it gets treated as a 3-byte instruction (when it is definitely a 4-byte instruction).

From my testing, changing the following line:

[qemu/target-i386/translate.c#L5147](https://github.com/unicorn-engine/unicorn/blob/ad767abda815f5c79b6658bf75ffc393a6a3c45c/qemu/target-i386/translate.c#L5147)

from: `b = cpu_ldub_code(env, s->pc++);`
to: `b = cpu_ldub_code(env, s->pc++) | 0x100`;

Causes it to go down the correct execution path (this switches it into the extended opcode format), eg:

instruction: `xorps xmm0, xmm0`:
bytes: `0F 57 C0`

I don't know if this currently breaks other VMX instructions, I have not thoroughly tested.

**Comment by gibbed** [comment]
#772 might be a related issue.

instruction: `vmovdqa ymmword ptr [rsp], ymm0`
bytes: `C5 FD 7F 04 24`

instruction: `movdqa xmmword ptr [rsp], xmm0`
bytes: `66 0F 7F 04 24`

**Comment by aquynh** [comment]
you may want to look at the latest Qemu version to see if they handled this
issue.

**Comment by gibbed** [comment]
Looks like it's an issue upstream as well.
