### ISSUE TITLE
New stable release with MSVC support

### ISSUE THREAD

**Issue by JayFoxRox** [unicorn-engine/unicorn#920]
To my understanding, the MSVC support is considered stable now?
Therefore, in my opinion, adding MSVC as a supported compiler should have resulted in a new stable release so natively build unicorns can be packaged with applications.

~~I'm asking for this because I'm [currently in the process](https://github.com/JayFoxRox/vcpkg/pull/1) of adding unicorn to [vcpkg](https://github.com/Microsoft/vcpkg) but I'd rather not have a random git revision as version number.~~ //Edit: There is a vcpkg "unicorn" port now.
As MSVC was added over multiple commits I'd also like to avoid patchfiles or some frankenstein 1.0.1-msvc.

Please consider a new release which contains MSVC compatibility.

**Comment by aquynh** [comment]
yes, will do soon.
