### ISSUE TITLE
License the interfaces and new code under the LGPL

### ISSUE THREAD

**Issue by JayFoxRox** [unicorn-engine/unicorn#925]
I think new contributions should be licensed under the LGPL. More specifically, the unicorn headers / include files and interface definitions should also be LGPL.

While a compiled library would still have to be GPLv2 with the QEMU backend, another backend could be used which is not licensed under the GPLv2.
[OpenSWE1R has a (hacky) KVM backend for a subset of unicorn for example](https://github.com/OpenSWE1R/openswe1r/blob/master/uc_kvm.c). With the KVM interface, we only use the unicorn headers, but nothing else.
Similar interfaces for HAXM and other libs might follow.

To avoid being forced to use "GPLv2 only" for builds using just those backends, it would be nice if those headers could be licensed differently.

If this is not done, we'll have to write our own wrappers / interfaces for the virtual CPU, just so we could optionally remove Unicorn from builds altogether (if we need a non-GPL build for other dependencies or platforms which don't allow GPL).

*(This is somewhat related to #634 ; I'd still be interested in "GPLv2 or later" + LGPL headers)*

**Comment by aquynh** [comment]
yes we can surely license all the headers under LGPL.

adding a line into those files would be enough for this

**Comment by aquynh** [comment]
see https://github.com/unicorn-engine/unicorn/commit/e6c27cfbd5aa389d95ea6dd583e6f40b44318d34
