### ISSUE TITLE
Forcing ZF in code hook does not affects emulation

### ISSUE THREAD

**Issue by PixelRick** [unicorn-engine/unicorn#937]
Referring to the regression test jumping.py #434

After a few hours I found out the cause: JZ/JNZ translation tests cc_dst instead of the carry flag itself.
Here is my own fix in unicorn.c : x86_reg_write : 
```c++
case UC_X86_REG_EFLAGS:
    cpu_load_eflags(&X86_CPU(uc, mycpu)->env, *(uint64_t *)value, -1);
    X86_CPU(uc, mycpu)->env.eflags0 = *(uint64_t *)value | 0x2;
    /* forces Z flag at qemu level (for JZ/JNZ) */
    if (*(uint64_t *)value & CC_Z) {
        X86_CPU(uc, mycpu)->env.cc_dst = 0;
    } else if (X86_CPU(uc, mycpu)->env.cc_dst == 0) {
        X86_CPU(uc, mycpu)->env.cc_dst = 0x0F012CED;
    }
    break;
```
(should be done with uint32_t in mode_32 too)

I didn't want to put it directly in cpu_load_eflags since it's specific to code hooks.
There is another way of doing it, that is to change how JZ is translated.. but it'd be 1 more instruction in the tb for everyone, while we don't often set the Z flag..
I also modified this regress test (jumping.py) to check both flag switch cases (0->1 and 1->0).

Should I propose a pull request ?
My next target is the self-modifying code bug, harder, better, stronger ;)

**Comment by rhelmot** [comment]
I touched that code last, and I think this is a good fix, given that you comment it a bit more thoroughly.

(sorry I don't watch this repository but I do pop in to see how things are going from time to time)

**Comment by aquynh** [comment]
@TefRick, can you do pull req?

**Comment by aquynh** [comment]
Sorry for typo, @TehRick

**Comment by AntiBlueQuirk** [comment]
I think this problem may be more general than just JZ/JNZ. I've also had problems with JC instructions not respecting the carry flag after I modify it in a hook.

**Comment by AntiBlueQuirk** [comment]
I believe I've solved the problem by calling x86_cpu_exec_enter(cpu) ([helper.c:1134](https://github.com/unicorn-engine/unicorn/blob/19ffa83d4353af8834c4c55590ca2ecd357a6bbe/qemu/target-i386/helper.c#L1134)) after/right before exiting my interrupt hook. As it says, it "Frob eflags into the CPU temporary format".
