### ISSUE TITLE
CPU exception in Arm64

### ISSUE THREAD

**Issue by HclX** [unicorn-engine/unicorn#940]
I found it triggers exception when running instruction "STP Q6,Q6,[SP]", any idea what's wrong?

Here is the actual code:
>>> from unicorn import *
>>> code=b"\xe6\x1f\x00\xad"  <==== STP Q6, Q7, [SP]
>>> addr = 0x1000000
>>> mu = Uc(UC_ARCH_ARM64, UC_MODE_ARM)
>>> mu.mem_map(addr, 1024)
>>> mu.mem_write(addr, code)
>>> mu.reg_write(UC_ARM64_REG_SP, addr + 512)
>>> mu.reg_write(UC_ARM64_REG_PC, addr)
>>> mu.emu_start(addr, addr + 4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/unicorn/unicorn.py", line 288, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Unhandled CPU exception (UC_ERR_EXCEPTION)

**Comment by gunyarakun** [comment]
I faced the similar issue with the instruction `stp d9, d8, [sp, #-112]!` (6d b9 23 e9)

**Comment by gunyarakun** [comment]
@HclX 
I found that FPEN bit on CPACR_EL1 must be set if you access vector registers such as Qx or Dx.

```
uint32_t x;
uc_reg_read(uc, UC_ARM64_REG_CPACR_EL1, &x)
x |= 0x300000; // set FPEN bit
uc_reg_write(uc, UC_ARM64_REG_CPACR_EL1, &x);
```

This solves our problems.
