### ISSUE TITLE
AARCH64: size of the "context" object?

### ISSUE THREAD

**Issue by HclX** [unicorn-engine/unicorn#943]
Where do I get the size of this object? I want to preserve my emulation state into disk, currently trying to persists the memory and also the context object, but found no way to get the size of this object. Does it currently not support this kind of operations?

**Comment by rhelmot** [comment]
It's heavily questionable whether you're going to be able to do that. The "opaque context" is actually the [cpu state struct](https://github.com/unicorn-engine/unicorn/blob/master/qemu/target-arm/cpu.h), and it looks like it contains pointers, which are not going to work if the data leaves the process. Hell, it contains a pointer to the uc instance, so it can't even be shared among multiple unicorns in the same process. imo it's a miracle any of unicorn works at all.

If you wanted to fix up these pointer fields on restore it would be a neat PR.

The exact size of the struct is really hard to unearth from the depths of qemu, there are some hacks to make it available as `ARM64_REGS_STORAGE_SIZE_aarch64`, but I have no idea what the visibility on that variable is. See [here](https://github.com/unicorn-engine/unicorn/blob/master/qemu/target-arm/unicorn.h).
