### ISSUE TITLE
(x86) Emulated CPU is not translating virtual memory addresses

### ISSUE THREAD

**Issue by StrikerX3** [unicorn-engine/unicorn#947]
The emulated CPU does not translate memory addresses after setting up paging correctly. The two tests related to paging ([here](https://github.com/unicorn-engine/unicorn/blob/master/tests/unit/test_x86_soft_paging.c)) are skipped; they fail if enabled. 

I also tried using `uc_map_mem_ptr` with a `char[]` already containing the PDEs, PTEs, code and data, then prepared the CPU registers, protected mode, MTRRs and PAT with `uc_reg_write` and tried to run only the last part of the code where it reads from the virtual address. This fails too. If I manually translate the address using the data existing on the memory and CR3 register at the end of emulation, I can fetch the correct value.

If the CPU tries to read, write or execute code that was not previously mapped with `uc_mem_map` or `uc_mem_map_ptr`, `uc_emu_start` returns one of `UC_ERR_READ_UNMAPPED`, `UC_ERR_WRITE_UNMAPPED` or `UC_ERR_FETCH_UNMAPPED`, depending on what happened. I believe #439 is related to this.

I built Unicorn from master with MSYS2 / MinGW32 and MinGW64 on Windows 10 and with the default C++ toolchain on Ubuntu 16.04.3.

**Comment by sleirsgoevy** [comment]
Still doesn't work properly in 2020
