### ISSUE TITLE
new release 1.0.2

### ISSUE THREAD

**Issue by anthraxx** [unicorn-engine/unicorn#948]
Hey all, hey @aquynh

can we expect a simple 1.0.2 tag? Guess it looks stable enough for now, and a new release would really be great. especially as of the rename of ruby things, which is a pita to backport.

**Comment by aquynh** [comment]
we still need to fix those bugs reported by Google AutoFuzz before going
for 1.0.2.

**Comment by anthraxx** [comment]
@aquynh I see, really looking forward to it :smile_cat:
