### ISSUE TITLE
unicorn还支持cygwin吗？

### ISSUE THREAD

**Issue by Introspelliam** [unicorn-engine/unicorn#952]
这几天在cygwin上安装unicorn，一直都没安装上，最后手动将CC改为x86_64-w64-mingw32-gcc才顺利编译安装成功！但是我比较喜欢用python，看了下python/setup.py文件，发现python支持的选项是./make.sh cygwin-mingw64，但是make.sh中已经删除了cygwin-mingw64，倒是加了msvc_update_genfiles，是不是mingw、cygwin等已经退出舞台了！

**Comment by aquynh** [comment]
please use English.

**Comment by EcmaXp** [comment]
`These days installed unicorn on cygwin, has not been installed, and finally manually changed the CC to x86_64-w64-mingw32-gcc to successfully compile and install successfully! But I prefer to use python and watch python.` (Google Translator)

Please check [https://github.com/unicorn-engine/unicorn/tree/master/bindings/python](https://github.com/unicorn-engine/unicorn/tree/master/bindings/python).

**Comment by EcmaXp** [comment]
`These days installed unicorn on cygwin, has not been installed, and finally manually changed the CC to x86_64-w64-mingw32-gcc to successfully compile and install successfully! But I prefer to use python, looked at the python/setup.py file, and found that the option supported by python is ./make.sh cygwin-mingw64, but cygwin-mingw64 has been removed from make.sh, but msvc_update_genfiles is added. Not mingw, cygwin, etc. have already withdrawn from the stage!` (Google Translator)
