### ISSUE TITLE
Accessing aarch64 special registers such as CurrentEl/ELR_ELx?

### ISSUE THREAD

**Issue by HclX** [unicorn-engine/unicorn#953]
I didn't check the C code, but it looks like we don't have definitions in python binding. Are those not available at all or just not implemented in python binding? any plan to implement them?

**Comment by elp0t0r1c0** [comment]
Hi @HclX,
This is now possible since https://github.com/unicorn-engine/unicorn/commit/149121539b6cc8a349be513d834da91ba37a3253 and https://github.com/unicorn-engine/unicorn/commit/cf3451c37a6c4bf78ebcc0af28def0730533251c
