### ISSUE TITLE
Why is uc_mem_protect calling uc_emu_stop when removing UC_PROT_EXEC on non-executed mem-area

### ISSUE THREAD

**Issue by MichaWe** [unicorn-engine/unicorn#956]
I was running an ELF executable in a x86_64 environment and noticed, that by calling `uc_mem_protect(uc, addr, size, UC_PROT_NONE)` causes the emulator to quit and continue at the same position.

This behavior results from the given code:

```c
if (((mr->perms & UC_PROT_EXEC) != 0) && ((perms & UC_PROT_EXEC) == 0))
    remove_exec = true;
...
if (remove_exec) {
    uc->quit_request = true;
    uc_emu_stop(uc);
}
```

Is it correct that execution is suspended and resumed even if the currently executed instruction is outside of `addr`? It appears strange to me that changing permissions of a different memory segment than the one with the currently executed code would trigger such behavior.

**Comment by sh1ftchg** [comment]
First of all it looks like this is an issue for all emulated processors.

But to answer your question, no this behavior is bad. 

That said, it should be:
```c
tb_lock();
page_set_flags(...);
tb_unlock();
```
