### ISSUE TITLE
x86 opcode 8F always executes pop

### ISSUE THREAD

**Issue by gynvael** [unicorn-engine/unicorn#957]
According to Intel Manual vol 2 Appendix A.4 the 8F opcode is a start of the 1A group (with opcode selector in the bits 3-5 of ModR/M byte). The group consists only of the POP instruction (case 000 binary).

Problem: unicorn-engine (and Qemu) execute any opcode from this group as the POP instruction

Expected behavior: Invalid Opcode (Undefined Opcode) is raised.

Test case in Python:
```
from unicorn import *
from unicorn.x86_const import *

def test_8f():
  print "Testing 8F (group 1A):",
  uc = Uc(UC_ARCH_X86, UC_MODE_32)
  uc.mem_map(0x1000, 0x1000, UC_PROT_ALL)
  uc.reg_write(UC_X86_REG_ESP, 0x1800)

  # Test case.
  uc.mem_write(0x1800, "A" * 4)
  uc.mem_write(0x1000, "\x8f\xd0")

  try:
    uc.emu_start(0x1000, 0x1002, count=1)
  except unicorn.UcError as e:
    print "CPU exception was thrown, good!", e
    return

  eax = uc.reg_read(UC_X86_REG_EAX)

  if eax == 0x41414141:
    print "Bug! Intel x86 should crash, but a pop eax was executed."
  else:
    print "This is really weird... This should never happen."

def main():
  test_8f()

if __name__ == "__main__":
  main()
```

Actual output:
```
> python test_8f.py
Testing 8F (group 1A): Bug! Intel x86 should crash, but a pop eax was executed.
```

Expected output:
```
Testing 8F (group 1A): CPU exception was thrown, good! Invalid instruction (UC_ERR_INSN_INVALID)
```

Code in nasm to test on actual x86-32 / GNU/Linux:
```
; nasm -felf linux_test_8f.nasm
; ld linux_test_8f.o -melf_i386
[bits 32]

section .data

section .text
global _start
_start:
  push 123
  db 0x8f, 0xd0  ; Should crash, but will act as pop eax in qemu/unicorn-engine.

  mov ebx, eax ; Exit code.
  mov eax, 1  ; Exit.
  int 0x80
```

Output:
```
$ ./a.out 
Illegal instruction (core dumped)
$ 
```

Btw, I saw the [C7 group was fixed in unicorn-engine](https://github.com/unicorn-engine/unicorn/pull/844/commits/ad767abda815f5c79b6658bf75ffc393a6a3c45c#diff-a84d869a16d93ba3091d2c95fbdadd27), but not Qemu - are you upstreaming changes to Qemu code, or should I report this bug there as well?

Cheers!

**Comment by aquynh** [comment]
please fix the bug, and send pull req if you can.

regarding the C7 fix, i remember @vardyh said he would send the fix to Qemu, but unsure how it went.
