### ISSUE TITLE
How to get the current  instruction in uc.HOOK_CODE?

### ISSUE THREAD

**Issue by usualwyy** [unicorn-engine/unicorn#958]
I'm a freshman at unicorn,need help.
Thx.

**Comment by usualwyy** [comment]
ah, sorry for my dumb question,I thought of a way to get the instrction:
Get 4 bytes from current address,and translate them to asm with keystone.
Is this the only solution?

**Comment by aquynh** [comment]
Yes, reading bytes at current PC, but then you need disassembler to decode, which can be Capstone (not Keystone assembler)

**Comment by usualwyy** [comment]
Appreciate!!
