### ISSUE TITLE
ARM64 Emulation hangs

### ISSUE THREAD

**Issue by bkerler** [unicorn-engine/unicorn#963]
Trying to emulate the instruction b.eq on arm64le using python3, unicorn just hangs.

Example code:

```
from keystone import *
from unicorn import *

asm = '''
cmp w0, 0x22
b.eq hh
ldr w0, [x1]
ret
hh: str w2, [x1]
    ret
'''
code = b"\x1F\x88\x00\x71\x60\x00\x00\x54\x20\x00\x40\xB9\xC0\x03\x5F\xD6\x22\x00\x00\xB9\xC0\x03\x5F\xD6"
addr = 0

uc = Uc(UC_ARCH_ARM64, UC_MODE_ARM)
ks = Ks(KS_ARCH_ARM64, KS_MODE_LITTLE_ENDIAN)
uc.mem_map(addr, 2 * 1024 * 1024)
uc.mem_write(addr, code)
uc.emu_start(addr, addr + len(code))
print("Done.")
```

**Comment by aquynh** [comment]
this is not a bug. in your code, you have a forever loop because of RET instruction at 0xc address, that jump to X0, which is 0 by default. so your code never quit the loop, thus "hang" from your observation.

**Comment by bkerler** [comment]
Ok. But it hangs on stepping on b.eq, even if I remove Ret.

**Comment by aquynh** [comment]
Please post your new code

**Comment by bkerler** [comment]
from keystone import *
from unicorn import *

asm = '''
mov X0, 0x22
cmp w0, 0x22
b.eq hh
ldr w0, [x1]
b exit
hh: 
str w2, [x1]
exit: 
mov X3, 0
'''
code = b"\x40\x04\x80\xd2\x1f\x88\x00\x71\x60\x00\x00\x54\x20\x00\x40\xb9\x02\x00\x00\x14\x22\x00\x00\xb9\x03\x00\x80\xd2"
addr = 0

uc = Uc(UC_ARCH_ARM64, UC_MODE_ARM)
ks = Ks(KS_ARCH_ARM64, KS_MODE_LITTLE_ENDIAN)
uc.mem_map(addr, 2 * 1024 * 1024)
uc.mem_write(addr, code)
uc.emu_start(addr, addr + len(code))
print("Done.")
