### ISSUE TITLE
Wrong PC on ARM after stop from hook

### ISSUE THREAD

**Issue by abiondo** [unicorn-engine/unicorn#969]
When stopping the emulation from a hook, the PC is correct within the hook, but it's then set to the beginning of the basic block when reading it outside the hook.

Here's a minimal testcase:

```python
#!/usr/bin/env python

from __future__ import print_function
from unicorn import *
from unicorn.arm_const import *

# +0: mov r0, #0
#     loop:
# +4:   add r0, r0, 1
# +8:   b loop
CODE = b'\x4f\xf0\x00\x00\x00\xf1\x01\x00\xfc\xe7'
ADDRESS = 0x10000

# Alternates between True and False so that the hook
# does not hit when continuing
trigger = True


def hook_code(uc, address, size, user_data):
    global trigger
    if trigger:
        pc = uc.reg_read(UC_ARM_REG_PC)
        print('    Inside hook, pc = 0x{:x}'.format(pc))
        uc.emu_stop()
    trigger = not trigger


def smoke_test():
    uc = Uc(UC_ARCH_ARM, UC_MODE_THUMB)
    uc.mem_map(ADDRESS, 2 * 1024 * 1024)
    uc.mem_write(ADDRESS, CODE)
    uc.hook_add(UC_HOOK_CODE, hook_code, begin=ADDRESS+8, end=ADDRESS+8)

    uc.reg_write(UC_ARM_REG_PC, ADDRESS)

    for _ in range(5):
        pc = uc.reg_read(UC_ARM_REG_PC)
        print('>>> Before start, pc = 0x{:x}'.format(pc))
        uc.emu_start(pc | 1, ADDRESS + len(CODE))
        r0 = uc.reg_read(UC_ARM_REG_R0)
        print('    After stop, r0 = {}'.format(r0))


if __name__ == '__main__':
    smoke_test()
```

I'm trying to do something like a breakpoint: stop at `0x10008` from the hook, then do something from outside, then resume emulation. The output is:

```
>>> Before start, pc = 0x10000
    Inside hook, pc = 0x10008
    After stop, r0 = 1
>>> Before start, pc = 0x10000
    Inside hook, pc = 0x10008
    After stop, r0 = 2
>>> Before start, pc = 0x10004
    Inside hook, pc = 0x10008
    After stop, r0 = 4
>>> Before start, pc = 0x10004
    Inside hook, pc = 0x10008
    After stop, r0 = 6
>>> Before start, pc = 0x10004
    Inside hook, pc = 0x10008
    After stop, r0 = 8
```

Two things are clear from this:
- after emulation stops, the PC is set to the beginning of the basic block that contained the hook address (`0x10000` at first, `0x10004` after the branch);
- the register state is not rolled back, as it's incrementing twice.

What I would expect is a consistent behavior: either PC equal to `0x10008` after the hook (to resume the hooked instruction), or rolled back registers so that it looks like the instructions from the beginning of the block to the hook were never executed. The former definitely makes more sense.

Am I doing something wrong or misunderstanding how `emu_stop` is supposed to work, or is this a bug?

**Comment by aquynh** [comment]
this is a bug, yes

**Comment by aquynh** [comment]
this and the other issue you post has the same mechanism of only calling emu_stop() when Trigger is True. why is that?
