### ISSUE TITLE
EFlags reserved bits not respected

### ISSUE THREAD

**Issue by stevemk14ebr** [unicorn-engine/unicorn#970]
```
push dword ptr [ebp]
add ebp, 4     
popfd	

```
Test: run with random values at [ebp] for a few rounds. Check EFLAGS after the popfd. The reserved bits are not set properly. Some of the lower 16 bits said to be always 1 are sometimes zero and vice versa. I believe the same is true with the interrupt enable bit too, i did not check the upper 16 at all. It seems to me these bits are treated as undefined and allowed to be any value, which is incorrect.	

Examples:
[ebp] = 0xeb5c6d08
eflags before: 0x00000000b68cbc7c
eflags after:    0x00000000b68cbc28

afterwards bit 1 should be set, bit 15 should be zero as just two examples. There's many more inputs that do this.

**Comment by stevemk14ebr** [comment]
Why was this closed, was it addressed?

**Comment by wtdcode** [comment]
@stevemk14ebr Not exactly, I'm doing cleaning for issues/PR. You may try our new version on dev branch. If the problem still exists, please re-open the issue.
