### ISSUE TITLE
x86 - eflags

### ISSUE THREAD

**Issue by Paliha** [unicorn-engine/unicorn#971]
hi, very good tool, thank you!
x64 example:
@L00000001:
        mov r12d, 0x0000000068A4247E
        shl r12d, 0x10
        jb short @L00000001<- eflags = 204; cf = 0;
but the emulator does not exit the loop..(((

**Comment by Paliha** [comment]
eflags = 200; 
run x64 example:
@L00000001:
	mov r11d, 0xB1819D46
	shl r11d, 0x1E
	mov ebp, 0x1866C543
	or r11d, ebp
	xor r11d, ebp
	ror ebp, 0x1D
	shl ebp, 0x1A
	adc r11d, 0x76E2E42F
	jp short @L00000001<- eflags = 294; pf = 1;
the behavior of the flag operator is correct, but the state of the flag is incorrect.
in this example, pf must be 0. 
The emulation again goes into an infinite loop...(((

**Comment by RYDB3RG** [comment]
complete repro (it shouldnt hit INT3 but NOP):

```
import unicorn

def code_hook(mu, address, size, user_data):
    print(hex(address))

uc = unicorn.Uc(unicorn.UC_ARCH_X86, unicorn.UC_MODE_64)
uc.hook_add(unicorn.UC_HOOK_CODE, code_hook)

# 1000      48 BB 29 A2 B7 8D 00 00 00 00     mov       rbx,   8DB7A229h  
# 100A      48 C1 E3 1C                       shl       rbx,   1Ch  
# 100E      73 01                             jae       label1 
# 1010      CC                                int       3  
# label1:
# 1011      90                                nop
code = b"\x48\xBB\x29\xA2\xB7\x8D\x00\x00\x00\x00\x48\xC1\xE3\x1C\x73\x01\xCC\x90"
addr = 0x1000

uc.mem_map(addr, 0x1000)
uc.mem_write(addr, code)
uc.emu_start(addr, addr + len(code))
```
