### ISSUE TITLE
Segmentation fault when writing UC_X86_REG_EAX with uc_reg_write_batch

### ISSUE THREAD

**Issue by AlexAltea** [unicorn-engine/unicorn#978]
As the title says, while passing 32-bit registers, e.g. `UC_X86_REG_EAX`, to `uc_reg_write_batch`, it will cause a segmentation fault. Demo:

```c
#include <unicorn/unicorn.h>

int main()
{
    uc_err err;
    uc_engine *uc;

    err = uc_open(UC_ARCH_X86, UC_MODE_32, &uc);
    if (err != UC_ERR_OK) {
        return 1;
    }
    int regs[] = { UC_X86_REG_EAX };
    uint64_t values[] = { 0 };
    err = uc_reg_write_batch(uc, regs, (void * const*)values, 1);
    return 0;
}
```

Note that `uc_reg_write` works fine in this scenario and you can easily replace the `uc_reg_write_batch` line with the following, and it will run successfully:
```c
    err = uc_reg_write(uc, UC_X86_REG_EAX, values);
```

**Comment by aquynh** [comment]
can you fix this bug?

**Comment by cseagle** [comment]
I think you are using the API incorrectly. The third argument to uc_reg_write_batch is "void *const *vals" for a reason. Each element in this array is expected to be a pointer, yet you have provided NULL as values[0] which will naturally segfault when dereferenced.

Please refer to the example usage of this function in samples/sample_batch_reg.c. To fix your code you need something like the following:

#include <unicorn/unicorn.h>

int main()
{
    uc_err err;
    uc_engine *uc;

    err = uc_open(UC_ARCH_X86, UC_MODE_32, &uc);
    if (err != UC_ERR_OK) {
        return 1;
    }
    int regs[] = { UC_X86_REG_EAX };
    uint32_t values[] = { 0 };
    uint32_t *val_ptrs[1];
    val_ptrs[0] = &values[0];
    err = uc_reg_write_batch(uc, regs, (void * const*)val_ptrs, 1);
    return 0;
}

**Comment by AlexAltea** [comment]
@cseagle My bad, after that change everything works fine. Thanks for pointing it out.
I got confused since using `UC_X86_REG_RAX` didn't cause segmentation fault for mysterious reasons.

I'll close the issue now.

**Comment by summershrimp** [comment]
This is a really confusing api design, please consider change.
