### ISSUE TITLE
mem_map issue in python binding.

### ISSUE THREAD

**Issue by bitrot7** [unicorn-engine/unicorn#991]
It seems that the following `mu.mem_map(addr, size)` will only work if size is evenly divisible by 1024.  If size / 1024 produces a fractional result then the mapping will produce `UC_ERR_ARG`.  I suspect this is because allocation is done in KiB.  The workaround is to do `mu.mem_map(addr, size + size % 1024)` when size is in bytes.  Is this expected behavior?

**Comment by bitrot7** [comment]
As a matter of fact not only must it be divisible by 1024, it must **also** result in an even number.  `mu.mem_map(addr, size)` will only succeed when size / 1024 results in an even integer.  Is that normal???

**Comment by aquynh** [comment]
yes, that is how that API works.
